Repository ant-design/ant-design, pull requests merged in 2019-08, with the labels that each got.

#17858 feat: Added swedish translations for `Typography`-components
  components/locale/sv_SE.tsx
Labels: PR: reviewed-approved

#18020 chore: antd-tools => @ant-design/tools
  package.json
Labels: PR: unreviewed

#18044 fix: Fix statistic font
  components/style/themes/default.less
Labels: PR: unreviewed

#18034 fix: select-search-box broken style
  components/select/style/index.less
Labels: PR: unreviewed

#17740 fix: tooltip arrows do not fuse in dark
  components/tooltip/style/index.less
Labels: PR: reviewed-approved

#18043 feat: rotate zero width sider trigger in right mode
  components/layout/style/index.less
Labels: PR: reviewed-approved

#18058 fix typo for form api documentation
  components/form/index.en-US.md
Labels: PR: reviewed-approved

#17873 feat: add Breadcrumb.Separator
  components/breadcrumb/Breadcrumb.tsx
  components/breadcrumb/BreadcrumbItem.tsx
  components/breadcrumb/BreadcrumbSeparator.tsx
  components/breadcrumb/__tests__/Breadcrumb.test.js
  components/breadcrumb/__tests__/__snapshots__/demo.test.js.snap
  components/breadcrumb/demo/separator-indepent.md
  components/breadcrumb/index.tsx
  components/breadcrumb/index.zh-CN.md
Labels: PR: reviewed-approved

#18046 add waring for props#iconType in component Alert
  components/alert/__tests__/index.test.js
  components/alert/index.tsx
Labels: PR: unreviewed

#17273 feat: menu component customization: create new variables for easy customization
  components/menu/style/dark.less
  components/menu/style/index.less
  components/style/themes/default.less
Labels: PR: reviewed-approved

#18059 fix: Checkbox checked extra space
  components/checkbox/style/mixin.less
Labels: PR: unreviewed

#18063 Fixed typo in theme documentation.
  docs/react/customize-theme.en-US.md
Labels: PR: reviewed-approved

#18067 chore: transfer ajax table demo
  components/transfer/index.en-US.md
  components/transfer/index.zh-CN.md
Labels: PR: reviewed-approved

#18009 feat(Upload): add transformFile option for transform file before request
  components/upload/__tests__/__snapshots__/demo.test.js.snap
  components/upload/__tests__/upload.test.js
  components/upload/__tests__/uploadlist.test.js
  components/upload/demo/transform-file.md
  components/upload/index.en-US.md
  components/upload/index.zh-CN.md
  components/upload/interface.tsx
  package.json
Labels: PR: reviewed-approved

#18069 Feature
  components/breadcrumb/Breadcrumb.tsx
  components/breadcrumb/BreadcrumbItem.tsx
  components/breadcrumb/BreadcrumbSeparator.tsx
  components/breadcrumb/__tests__/Breadcrumb.test.js
  components/breadcrumb/__tests__/__snapshots__/demo.test.js.snap
  components/breadcrumb/demo/separator-indepent.md
  components/breadcrumb/index.tsx
  components/breadcrumb/index.zh-CN.md
  components/menu/style/dark.less
  components/menu/style/index.less
  components/style/themes/default.less
  components/upload/__tests__/__snapshots__/demo.test.js.snap
  components/upload/__tests__/upload.test.js
  components/upload/__tests__/uploadlist.test.js
  components/upload/demo/transform-file.md
  components/upload/index.en-US.md
  components/upload/index.zh-CN.md
  components/upload/interface.tsx
  package.json
Labels: PR: unreviewed

#18071 docs: 3.21.0 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/locale/ta_IN.tsx
Labels: PR: unreviewed

#18075 fix: ConfigProvider wrapper locale no need with only children
  components/config-provider/__tests__/locale.test.js
  components/locale-provider/index.tsx
Labels: PR: reviewed-approved

#18073 fix: update changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed

#18076 docs: changelog of 3.21.1
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#18088 fix: `noStyle` throws react warning
  components/_util/transButton.tsx
Labels: PR: unreviewed

#18097 fix: Revert #17684
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/demo/presuffix.md
  components/input/style/mixin.less
Labels: PR: unreviewed

#18105 fix: ConfigProvider should not block LocaleProvider
  components/config-provider/__tests__/locale.test.js
  components/config-provider/index.tsx
  components/locale-provider/LocaleReceiver.tsx
Labels: PR: reviewed-changes-requested

#18106 docs: add 3.21.2 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#18092 fix: timeline-content-word-break
  components/timeline/style/index.less
Labels: PR: unreviewed

#18093 fix: timeline_left/alternate tail&content
  components/timeline/style/index.less
Labels: PR: unreviewed

#18112 fix: Tabs content with margin collapse
  components/tabs/style/index.less
Labels: PR: reviewed-approved

#18114 fix: Textarea show scroll when autosize
  components/input/TextArea.tsx
  components/input/__tests__/index.test.js
Labels: PR: reviewed-approved

#18133 更新 Pagination 组件 文档的版本号
  components/pagination/index.en-US.md
  components/pagination/index.zh-CN.md
Labels: PR: unreviewed

#18138 fix: tooltip not work with disabled checkbox
  components/checkbox/Checkbox.tsx
  components/tooltip/__tests__/__snapshots__/tooltip.test.js.snap
  components/tooltip/__tests__/tooltip.test.js
  components/tooltip/index.tsx
Labels: PR: reviewed-changes-requested

#18139 fix: button line-height style
  components/button/style/index.less
Labels: PR: unreviewed

#18140 Fixed lightweight spec missing space
  docs/spec/lightweight.en-US.md
Labels: PR: unreviewed

#18141 Fixed typo in FAQ documentation.
  docs/react/faq.en-US.md
Labels: PR: unreviewed

#18147 Fixed typos and grammatical errors in Button and Tabs documentation.
  components/button/demo/ghost.md
  components/tabs/demo/card.md
  components/tabs/demo/custom-tab-bar.md
  components/tabs/demo/size.md
Labels: PR: unreviewed

#18132 fix: add focus and blur for Mentions
  components/mentions/__tests__/index.test.js
  components/mentions/index.tsx
Labels: PR: unreviewed

#18130 fix: button should accept title prop
  components/button/button.tsx
  components/dropdown/dropdown-button.tsx
Labels: PR: unreviewed

#18115 fix: IE9 throw File not defined
  components/upload/UploadList.tsx
Labels: PR: reviewed-approved

#18116 chore: ⌨️ Improve Divider accessibility by adding role="separator"
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/divider/__tests__/__snapshots__/demo.test.js.snap
  components/divider/index.tsx
  components/empty/__tests__/__snapshots__/demo.test.js.snap
  components/page-header/__tests__/__snapshots__/demo.test.js.snap
  components/steps/__tests__/__snapshots__/demo.test.js.snap
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/typography/__tests__/__snapshots__/demo.test.js.snap
Labels: PR: unreviewed

#18160 :bug: fix form doc typo
  components/form/demo/inline-login.md
Labels: PR: unreviewed

#18125 fix: remove unwanted vertical space at the top of Tabs
  components/tabs/style/index.less
Labels: PR: reviewed-approved

#18151 fix: Input clear icon align problem
  components/input/style/index.less
Labels: PR: unreviewed

#18161 refactor: Migrate to react-intl@3
  package.json
  site/bisheng.config.js
  site/theme/en-US.js
  site/theme/index.js
  site/theme/static/template.html
  site/theme/template/Content/Article.jsx
  site/theme/template/Content/ComponentDoc.jsx
  site/theme/template/Content/Demo.jsx
  site/theme/template/Content/MainContent.jsx
  site/theme/template/Home/Banner.jsx
  site/theme/template/Home/index.jsx
  site/theme/template/Layout/Header.jsx
  site/theme/template/Layout/index.jsx
  site/theme/template/Redirect.jsx
  site/theme/zh-CN.js
Labels: PR: unreviewed

#18179 fix: Card action style when it is a button
  components/card/style/index.less
Labels: PR: unreviewed

#18180 fix: TypeScript errors
  package.json
  site/theme/template/IconDisplay/Category.tsx
  site/theme/template/IconDisplay/index.tsx
Labels: PR: unreviewed

#18182 fix: update getContainer to props before
  components/modal/confirm.tsx
Labels: PR: unreviewed

#18184 chore: Improve cov
  components/auto-complete/InputElement.tsx
  components/auto-complete/__tests__/focus.test.js
  components/auto-complete/__tests__/index.test.js
  components/auto-complete/index.en-US.md
  components/auto-complete/index.zh-CN.md
Labels: PR: reviewed-changes-requested

#18185 test: Add test case for AutoComplete
  components/auto-complete/__tests__/index.test.js
Labels: PR: reviewed-changes-requested

#18187 Add 3.21.3 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed, needs-more-info

#18190 fix(Cascader): check if options exists before use options.length
  components/cascader/index.tsx
Labels: PR: unreviewed

#18192 types: complete monthCellContentRender property type definition on Da…
  components/date-picker/interface.tsx
Labels: PR: unreviewed

#18196 chore: update ts define
  components/upload/Dragger.tsx
Labels: PR: unreviewed

#18167 style: Drawer get container
  components/drawer/__tests__/__snapshots__/demo.test.js.snap
  components/drawer/demo/render-in-current.md
  components/drawer/style/drawer.less
Labels: PR: unreviewed

#18208 fix: 🐛Button loading prop warning
  components/button/button.tsx
Labels: PR: unreviewed

#18172 feat: Tree support virtual scroll
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/form/FormItemInput.tsx
  components/form/FormList.tsx
  components/transfer/__tests__/__snapshots__/demo.test.js.snap
  components/tree/DirectoryTree.tsx
  components/tree/Tree.tsx
  components/tree/__tests__/__snapshots__/demo.test.js.snap
  components/tree/__tests__/__snapshots__/directory.test.js.snap
  components/tree/__tests__/util.test.js
  components/tree/demo/basic-controlled.md
  components/tree/demo/basic.md
  components/tree/demo/customized-icon.md
  components/tree/demo/directory.md
  components/tree/demo/draggable.md
  components/tree/demo/dynamic.md
  components/tree/demo/line.md
  components/tree/demo/search.md
  components/tree/style/directory.less
  components/tree/style/index.less
  components/tree/util.ts
  package.json
Labels: 4.0, PR: reviewed-approved, PR: unreviewed

#18221 fix: timeline-right-content-width
  components/timeline/style/index.less
Labels: PR: unreviewed

#18209 chore: 🆙 upgrade react-slick and eslint-config-airbnb
  .eslintrc.js
  components/_util/__tests__/util.test.js
  components/_util/throttleByAnimationFrame.tsx
  components/badge/__tests__/__snapshots__/index.test.js.snap
  components/badge/__tests__/index.test.js
  components/carousel/__tests__/index.test.js
  components/form/Form.tsx
  components/form/demo/customized-form-controls.md
  components/modal/ActionButton.tsx
  components/modal/index.tsx
  components/upload/__tests__/uploadlist.test.js
  package.json
Labels: PR: unreviewed

#18242 Fixed grammatical errors in Button and Icon documentation.
  components/button/demo/icon.md
  components/icon/demo/basic.md
  components/icon/demo/two-tone.md
  components/icon/index.en-US.md
Labels: PR: unreviewed

#18229 chore: gh-pages action
  .github/main.workflow
Labels: PR: unreviewed, needs-more-info

#17994 feat: steps component support type navigation
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/steps/__tests__/__snapshots__/demo.test.js.snap
  components/steps/demo/nav.md
  components/steps/demo/simple.md
  components/steps/index.en-US.md
  components/steps/index.tsx
  components/steps/index.zh-CN.md
  components/steps/style/index.less
  components/steps/style/nav.less
  components/steps/style/small.less
  components/steps/style/vertical.less
  package.json
Labels: PR: reviewed-approved

#18261 style: fix Table row selected hover style
  components/table/style/index.less
Labels: PR: unreviewed

#18168 fix: Checkbox should not show highlight when disabled
  components/checkbox/style/mixin.less
Labels: PR: unreviewed

#18265 docs: Fix ConfigProvider demo
  components/config-provider/demo/locale.md
  docs/react/getting-started.zh-CN.md
  docs/react/i18n.zh-CN.md
Labels: PR: unreviewed

#18266 refactor: Use new lifecycle methods for Table SelectionCheckboxAll
  components/table/SelectionCheckboxAll.tsx
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/demo/basic.md
  components/table/demo/bordered.md
  components/table/demo/colspan-rowspan.md
  components/table/demo/dynamic-settings.md
  components/table/demo/edit-cell.md
  components/table/demo/edit-row.md
  components/table/demo/expand.md
  components/table/demo/fixed-columns-header.md
  components/table/demo/fixed-columns.md
  components/table/demo/jsx.md
  components/table/demo/nested-table.md
  components/table/demo/resizable-column.md
  components/table/demo/row-selection.md
Labels: PR: unreviewed

#18279 fix: Allows to override the autocomplete prop in Cascader
  components/cascader/index.tsx
Labels: PR: unreviewed

#18282 fix: ts compile error with import React fix-ts-1259
  components/badge/ScrollNumber.tsx
  components/breadcrumb/Breadcrumb.tsx
  components/tooltip/index.tsx
Labels: PR: unreviewed

#18287 feat: use warning from rc-util
  components/_util/warning.ts
  components/_util/warning.tsx
  package.json
Labels: PR: unreviewed

#18291 Update `okText` documentation for `PopConfirm` Component
  components/popconfirm/index.en-US.md
Labels: PR: unreviewed

#18289 fix: ResizeObserver should ignore shaking
  components/__tests__/util/domHook.js
  components/_util/__tests__/util.test.js
  components/_util/resizeObserver.tsx
  components/affix/__tests__/Affix.test.js
Labels: PR: unreviewed

#18300 fix: add style to CheckableTagProps
  components/tag/CheckableTag.tsx
Labels: PR: unreviewed

#18270 style: descriptions style update
  components/calendar/locale/ro_RO.tsx
  components/descriptions/__tests__/__snapshots__/demo.test.js.snap
  components/descriptions/demo/size.md
  components/descriptions/index.en-US.md
  components/descriptions/index.zh-CN.md
  components/descriptions/style/index.less
Labels: PR: reviewed-approved

#18305 fix: cn pages locale
  package.json
Labels: PR: unreviewed

#17823 feat(Anchor): add getCurrentAnchor prop
  components/anchor/Anchor.tsx
  components/anchor/__tests__/Anchor.test.js
  components/anchor/__tests__/__snapshots__/demo.test.js.snap
  components/anchor/demo/customizeHighlight.md
  components/anchor/index.en-US.md
  components/anchor/index.zh-CN.md
Labels: PR: reviewed-approved

#18284 fix(module:progress): fix progress styles to adapt changes in rc progress
  components/progress/style/index.less
Labels: PR: unreviewed

#18311 The last-child highlight, whether or not it is linkable
  components/breadcrumb/style/index.less
Labels: PR: unreviewed

#18320 Update main.workflow
  .github/main.workflow
Labels: PR: reviewed-approved, needs-more-info

#17827 feat(Anchor): add targetOffset prop
  components/_util/__tests__/easings.test.js
  components/_util/__tests__/scrollTo.test.js
  components/_util/easings.ts
  components/_util/scrollTo.ts
  components/anchor/Anchor.tsx
  components/anchor/__tests__/Anchor.test.js
  components/anchor/__tests__/__snapshots__/demo.test.js.snap
  components/anchor/demo/targetOffset.md
  components/anchor/index.en-US.md
  components/anchor/index.zh-CN.md
  components/back-top/__tests__/index.test.js
  components/back-top/index.tsx
  components/statistic/__tests__/index.test.js
  components/tooltip/__tests__/tooltip.test.js
  components/upload/__tests__/uploadlist.test.js
  tests/utils.js
Labels: PR: unreviewed

#18298 feat: upgrade rc-mentions
  components/mentions/index.en-US.md
  components/mentions/index.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#18309 feat: Modal closeIcon
  components/modal/Modal.tsx
  components/modal/__tests__/Modal.test.js
  components/modal/__tests__/__snapshots__/Modal.test.js.snap
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
Labels: PR: reviewed-approved

#18322 fix: support `jfif` image in Upload
  components/upload/utils.tsx
Labels: PR: unreviewed

#18323 fix: model close
  components/modal/Modal.tsx
  components/modal/__tests__/__snapshots__/Modal.test.js.snap
Labels: PR: reviewed-approved

#18325 fix: Cascader notFoundContent width
  components/cascader/__tests__/__snapshots__/index.test.js.snap
  components/cascader/__tests__/index.test.js
  components/cascader/index.tsx
  package.json
Labels: PR: unreviewed

#18290 fix: submenu popupClassName and className chaos
  components/menu/SubMenu.tsx
  components/menu/index.en-US.md
  components/menu/index.zh-CN.md
Labels: PR: reviewed-changes-requested

#18324 chore: Merge master into feature
  .github/main.workflow
  components/__tests__/util/domHook.js
  components/_util/__tests__/util.test.js
  components/_util/resizeObserver.tsx
  components/_util/warning.ts
  components/_util/warning.tsx
  components/affix/__tests__/Affix.test.js
  components/badge/ScrollNumber.tsx
  components/breadcrumb/Breadcrumb.tsx
  components/breadcrumb/style/index.less
  components/cascader/__tests__/__snapshots__/index.test.js.snap
  components/cascader/__tests__/index.test.js
  components/cascader/index.tsx
  components/menu/SubMenu.tsx
  components/menu/index.en-US.md
  components/menu/index.zh-CN.md
  components/popconfirm/index.en-US.md
  components/progress/style/index.less
  components/tag/CheckableTag.tsx
  components/tooltip/index.tsx
  components/upload/utils.tsx
  package.json
Labels: PR: unreviewed

#18328 docs: changelog for 3.22.0
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/anchor/index.en-US.md
  components/anchor/index.zh-CN.md
  components/steps/__tests__/__snapshots__/demo.test.js.snap
  components/steps/demo/nav.md
  package.json
Labels: PR: unreviewed

#18326 fix: fix descriptions demo warning
  components/descriptions/__tests__/__snapshots__/demo.test.js.snap
  components/descriptions/demo/border.md
Labels: PR: unreviewed

#18331 chore: Revert locking less
  package.json
Labels: PR: reviewed-approved

#18332 perf: check prop only from metadata of demo
  .circleci/config.yml
  package.json
  scripts/check-demo.js
Labels: PR: unreviewed

#18335 fix: Anchor.Link add add new property target
  components/anchor/AnchorLink.tsx
  components/anchor/__tests__/__snapshots__/demo.test.js.snap
  components/anchor/demo/basic.md
  components/anchor/index.en-US.md
  components/anchor/index.zh-CN.md
Labels: PR: reviewed-approved

#18330 fix: Prop style is getting duplicated on Table (#18315)
  components/empty/__tests__/__snapshots__/demo.test.js.snap
  components/table/Table.tsx
Labels: PR: unreviewed

#18346 feat: Upgrade rc-input-number
  components/input-number/index.en-US.md
  components/input-number/index.tsx
  components/input-number/index.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#18329 chore: Merge master into feature
  .circleci/config.yml
  .eslintignore
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/anchor/index.en-US.md
  components/anchor/index.zh-CN.md
  components/descriptions/__tests__/__snapshots__/demo.test.js.snap
  components/descriptions/demo/border.md
  components/empty/__tests__/__snapshots__/demo.test.js.snap
  components/steps/__tests__/__snapshots__/demo.test.js.snap
  components/steps/demo/nav.md
  components/table/Table.tsx
  package.json
  scripts/check-demo.js
  site/theme/template/Layout/index.jsx
Labels: PR: reviewed-approved

#18348 fix: 🐛 Input align broken in IE11
  components/input/style/mixin.less
Labels: PR: unreviewed

#18353 docs: Fix typo in Steps demo
  components/steps/demo/nav.md
Labels: PR: unreviewed

#18356 fix: Steps vertical progressDot style
  components/steps/__tests__/__snapshots__/demo.test.js.snap
  components/steps/demo/progress-dot.md
  components/steps/style/progress-dot.less
Labels: PR: unreviewed

#18340 fix: Breadcrumb filtering react.fragment
  components/breadcrumb/Breadcrumb.tsx
  components/breadcrumb/__tests__/Breadcrumb.test.js
  components/breadcrumb/__tests__/__snapshots__/Breadcrumb.test.js.snap
Labels: PR: reviewed-changes-requested

#18377 docs: typo(version not exist)
  components/menu/index.zh-CN.md
Labels: PR: unreviewed

#18378 docs: typo(version not exist)
  components/menu/index.en-US.md
Labels: PR: unreviewed

#18383 typofix
  docs/spec/feedback.en-US.md
Labels: PR: unreviewed

#18393 fix: Steps progressDot style
  components/steps/style/progress-dot.less
Labels: PR: unreviewed

#18401 fix: Not shaking with autosize of TextArea
  components/input/TextArea.tsx
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/__tests__/index.test.js
  components/input/demo/autosize-textarea.md
Labels: PR: unreviewed

#18406 test: Increase BackTop code coverage
  components/back-top/__tests__/index.test.js
  components/back-top/index.tsx
Labels: PR: unreviewed

#18423 fix: upload newline bug
  components/upload/style/index.less
Labels: PR: unreviewed

#18432 docs: Update AutoComplete first demo with control mode & add faq
  components/auto-complete/__tests__/__snapshots__/demo.test.js.snap
  components/auto-complete/demo/basic.md
  components/auto-complete/index.en-US.md
  components/auto-complete/index.zh-CN.md
Labels: PR: reviewed-approved

#18433 feat: Add tabBarExtraContent property to Card component
  components/card/__tests__/__snapshots__/demo.test.js.snap
  components/card/demo/tabs.md
  components/card/index.en-US.md
  components/card/index.tsx
  components/card/index.zh-CN.md
Labels: PR: reviewed-approved

#18438 docs: link
  components/form/index.zh-CN.md
Labels: PR: unreviewed

#18440 fix: descriptions background is not themeable (#18372)
  components/descriptions/style/index.less
  components/style/themes/default.less
Labels: PR: unreviewed

#18444 feat: less vars for select and anchor
  components/anchor/style/index.less
  components/select/style/index.less
  components/style/themes/default.less
Labels: PR: unreviewed

#18441 fix: Input.Password cannot get input element
  components/input/Password.tsx
  components/input/__tests__/Password.test.js
  components/input/__tests__/__snapshots__/Password.test.js.snap
  components/input/__tests__/__snapshots__/index.test.js.snap
  components/input/__tests__/index.test.js
Labels: PR: unreviewed

#18425 docs: Search icon by image
  site/theme/en-US.js
  site/theme/static/icon-pic-searcher.less
  site/theme/static/index.less
  site/theme/template/IconDisplay/IconPicSearcher.tsx
  site/theme/template/IconDisplay/index.tsx
  site/theme/zh-CN.js
Labels: PR: unreviewed

#18128 🔥feat: new pageheader style
  components/page-header/__tests__/__snapshots__/demo.test.js.snap
  components/page-header/__tests__/index.test.js
  components/page-header/demo/actions.md
  components/page-header/demo/breadcrumb.md
  components/page-header/demo/content.md
  components/page-header/demo/responsive.md
  components/page-header/index.en-US.md
  components/page-header/index.tsx
  components/page-header/index.zh-CN.md
  components/page-header/style/index.less
  components/page-header/style/index.tsx
  components/style/themes/default.less
Labels: PR: reviewed-approved

#18458 style: 修复纯图标按钮在默认形状下不同大小均显示为正方形
  components/button/__tests__/__snapshots__/demo.test.js.snap
  components/button/button.tsx
  components/button/demo/button-group.md
  components/button/demo/loading.md
  components/button/demo/size.md
  components/button/style/index.less
  components/button/style/mixin.less
  components/style/themes/default.less
Labels: PR: unreviewed

#18465 add 3.22.1 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed

#18472 Create deploy-site.yml
  .github/main.workflow
  .github/workflows/deploy-site.yml
Labels: PR: reviewed-approved

#18475 fix: Input.Password unmount crash
  components/input/Password.tsx
  components/input/__tests__/Password.test.js
Labels: PR: reviewed-changes-requested

#18478 fix: Mentions in Form has additional height
  components/mentions/__tests__/__snapshots__/demo.test.js.snap
  components/mentions/demo/form.md
  components/mentions/style/index.less
Labels: PR: unreviewed

#18456 feat: configurable heading font-weight less var
  components/style/themes/default.less
  components/typography/style/index.less
Labels: PR: reviewed-approved

#18482 fix: Input disabled should not be allowed to clear
  components/input/Input.tsx
  components/input/__tests__/index.test.js
Labels: PR: reviewed-changes-requested

#18488 replace instances of typo 'collpse' with collapse
  site/theme/en-US.js
  site/theme/template/Content/ComponentDoc.jsx
  site/theme/zh-CN.js
Labels: PR: reviewed-changes-requested

#18471 fix: Capitalize Text and PageHeader default locale strings
  components/locale/default.tsx
  components/page-header/__tests__/__snapshots__/demo.test.js.snap
  components/typography/__tests__/__snapshots__/demo.test.js.snap
Labels: PR: unreviewed

#18494 fix(Table): apply props.style to container div
  components/empty/__tests__/__snapshots__/demo.test.js.snap
  components/table/Table.tsx
Labels: PR: unreviewed

#18491 doc: changelog add data
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: reviewed-approved

#18498 docs: changelog 3.22.2
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#18497 chore: Add warning when use `value` of Switch, Checkbox, Upload
  components/checkbox/Checkbox.tsx
  components/checkbox/__tests__/checkbox.test.js
  components/switch/__tests__/index.test.js
  components/switch/index.tsx
  components/upload/Upload.tsx
  components/upload/__tests__/upload.test.js
  components/upload/__tests__/uploadlist.test.js
Labels: PR: unreviewed

#18517 build: fix eslint issue of no-undef
  .eslintrc.js
Labels: PR: unreviewed

#18516 fix: circle button is not circle
  .eslintrc.js
  components/button/__tests__/__snapshots__/demo.test.js.snap
  components/button/demo/icon.md
  components/button/style/mixin.less
  site/theme/template/IconDisplay/IconPicSearcher.tsx
Labels: PR: unreviewed

#18521 fix: Input.Password Icon Position
  components/input/style/mixin.less
Labels: PR: unreviewed

#18522 feat: modal footer border-color less vars
  components/modal/style/modal.less
  components/style/themes/default.less
Labels: PR: unreviewed

#18525 fix(Steps): add subTitle propType declaration for Steps.Step component
  components/steps/index.tsx
Labels: PR: unreviewed

#18533 feat: input-number less vars
  components/input-number/style/index.less
  components/style/themes/default.less
Labels: PR: unreviewed

#18531 feat: card-bg-color less vars
  components/card/style/index.less
  components/style/themes/default.less
Labels: PR: unreviewed

#18515 feat: improve prop def for tooltip
  components/menu/MenuItem.tsx
  components/tooltip/index.tsx
Labels: PR: unreviewed

#18541 fix: Change to arrow function
  components/_util/styleChecker.tsx
Labels: PR: unreviewed

#18546 Update presetted-ranges.md
  components/date-picker/demo/presetted-ranges.md
Labels: PR: unreviewed

#18567 chore: rm bundlesize in test script
  scripts/test-all.sh
Labels: PR: unreviewed

#18559 fix: Tweak RangePicker extra selected style
  components/date-picker/style/Calendar.less
Labels: PR: unreviewed

#18568 fix: Adjust Descriptions column calcuation logic
  components/descriptions/__tests__/__snapshots__/demo.test.js.snap
  components/descriptions/__tests__/index.test.js
  components/descriptions/demo/vertical.md
  components/descriptions/index.tsx
Labels: PR: reviewed-changes-requested

#18574 fix: Tab content has wrong width in Safari
  components/tabs/style/index.less
Labels: PR: unreviewed

#18576 fix: Mentions should not collapse when prefix is empty
  components/mentions/style/index.less
Labels: PR: unreviewed

#18578 chore: Col support key if user providered
  components/descriptions/__tests__/__snapshots__/index.test.js.snap
  components/descriptions/__tests__/index.test.js
  components/descriptions/index.tsx
Labels: PR: reviewed-changes-requested

#18580 fix: Upload.Dragger should work with multiple is false
  components/upload/Upload.tsx
  components/upload/__tests__/upload.test.js
Labels: PR: reviewed-changes-requested

#18457 feat: allow disabling hover effect for Card.Grid
  components/card/Grid.tsx
  components/card/__tests__/__snapshots__/demo.test.js.snap
  components/card/demo/grid-card.md
  components/card/index.en-US.md
  components/card/index.zh-CN.md
  components/card/style/index.less
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
Labels: PR: reviewed-approved

#18588 fix: Card actions style when contains link Button
  components/card/style/index.less
Labels: PR: unreviewed
