Repository ant-design/ant-design, pull requests merged in 2019-07, with the labels that each got.

#17385 docs: Fix result demo title error
  components/result/demo/basic.md
Labels: PR: unreviewed

#17392 fix: Upload preview should work with Blob
  components/upload/UploadList.tsx
  components/upload/__tests__/uploadlist.test.js
  components/upload/interface.tsx
Labels: PR: unreviewed

#17389 fix: fix classname is undefined
  components/result/__tests__/__snapshots__/demo.test.js.snap
  components/result/__tests__/index.test.js
  components/result/index.tsx
  components/result/style/index.less
Labels: PR: reviewed-approved

#17382 fix: fix gh-pages ci running problem
  package.json
Labels: PR: unreviewed

#17412 fix: Form onSubmit type
  components/form/Form.tsx
Labels: PR: unreviewed

#17421 fix: DatePicker's input box is obscured on safari
  components/date-picker/style/RangePicker.less
Labels: PR: unreviewed

#17418 Add missing French translation
  components/locale-provider/fr_BE.tsx
  components/locale-provider/fr_FR.tsx
Labels: PR: reviewed-approved

#17433 fix: Omit AutoComplete loading type
  components/auto-complete/index.tsx
Labels: PR: unreviewed

#17447 style: 💄 optimize TimePicker focus style
  components/date-picker/style/TimePicker.less
  components/time-picker/style/index.less
Labels: PR: unreviewed

#17457 feat: Form support `scrollToField`
  components/form/Form.tsx
  components/form/FormItem.tsx
  components/form/FormItemLabel.tsx
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/__tests__/index.test.js
  components/form/demo/register.md
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/form/util.ts
  components/form/v3.en-US.md
  components/form/v3.zh-CN.md
  components/mention/__tests__/__snapshots__/demo.test.js.snap
  components/mentions/__tests__/__snapshots__/demo.test.js.snap
  package.json
  typings/custom-typings.d.ts
Labels: PR: reviewed-approved

#17458 fix: icon typo
  components/icon/__tests__/index.test.js
  components/icon/utils.ts
  components/popconfirm/__tests__/__snapshots__/index.test.js.snap
  package.json
  site/theme/template/IconDisplay/fields.ts
Labels: PR: unreviewed

#17415 doc: split demos
  components/result/__tests__/__snapshots__/demo.test.js.snap
  components/result/demo/403.md
  components/result/demo/404.md
  components/result/demo/500.md
  components/result/demo/basic.md
  components/result/demo/customIcon.md
  components/result/demo/error.md
  components/result/demo/info.md
  components/result/demo/success.md
  components/result/demo/warning.md
Labels: PR: unreviewed

#17464 chore: Merge master
  components/date-picker/style/TimePicker.less
  components/icon/__tests__/index.test.js
  components/icon/utils.ts
  components/popconfirm/__tests__/__snapshots__/index.test.js.snap
  components/result/__tests__/__snapshots__/demo.test.js.snap
  components/result/demo/403.md
  components/result/demo/404.md
  components/result/demo/500.md
  components/result/demo/basic.md
  components/result/demo/customIcon.md
  components/result/demo/error.md
  components/result/demo/info.md
  components/result/demo/success.md
  components/result/demo/warning.md
  components/time-picker/style/index.less
  package.json
  site/theme/template/IconDisplay/fields.ts
Labels: PR: unreviewed

#17390 rm drawer config consumer props
  components/drawer/index.tsx
  components/drawer/style/index.tsx
Labels: PR: unreviewed

#17486 chore: Lock @babel/plugin-transform-typescript version
  package.json
Labels: PR: unreviewed

#17480 fix: 💄 change DatePicker arrow style
  components/date-picker/style/Calendar.less
  components/date-picker/style/RangePicker.less
Labels: PR: unreviewed

#17502 fix: fix type of SwitchProps
  components/switch/index.tsx
Labels: PR: unreviewed

#17500 fix: some tabs style
  components/tabs/style/card-style.less
  components/tabs/style/index.less
Labels: PR: unreviewed

#17499 chore: changelog for 3.20.1
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#17505 fix: typo in console.error
  components/icon/__tests__/index.test.js
  components/icon/utils.ts
Labels: PR: reviewed-changes-requested

#17511 chore: Add warn of `value` not provided in Cascader
  components/cascader/__tests__/index.test.js
  components/cascader/index.tsx
Labels: PR: unreviewed

#17526 Improve code style
  components/cascader/index.tsx
Labels: PR: unreviewed

#17508 fix: optimize Input presuffix style(#17414)
  components/input/style/mixin.less
Labels: PR: unreviewed

#17517 chore: use none-dist icons entry
  components/badge/__tests__/__snapshots__/demo.test.js.snap
  components/drawer/__tests__/__snapshots__/demo.test.js.snap
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/icon/index.tsx
  components/progress/__tests__/__snapshots__/demo.test.js.snap
  components/tabs/__tests__/__snapshots__/demo.test.js.snap
  components/tag/__tests__/__snapshots__/demo.test.js.snap
Labels: PR: unreviewed

#17536 chore: Merge master
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/badge/__tests__/__snapshots__/demo.test.js.snap
  components/cascader/__tests__/index.test.js
  components/cascader/index.tsx
  components/date-picker/style/Calendar.less
  components/date-picker/style/RangePicker.less
  components/drawer/__tests__/__snapshots__/demo.test.js.snap
  components/drawer/index.tsx
  components/drawer/style/index.tsx
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/icon/__tests__/index.test.js
  components/icon/index.tsx
  components/icon/utils.ts
  components/input/style/mixin.less
  components/list/index.en-US.md
  components/list/index.zh-CN.md
  components/locale-provider/index.en-US.md
  components/locale-provider/index.zh-CN.md
  components/progress/__tests__/__snapshots__/demo.test.js.snap
  components/switch/index.tsx
  components/tabs/__tests__/__snapshots__/demo.test.js.snap
  components/tabs/style/card-style.less
  components/tabs/style/index.less
  components/tag/__tests__/__snapshots__/demo.test.js.snap
  package.json
Labels: PR: reviewed-changes-requested

#17540 Revert "chore: use none-dist icons entry"
  components/badge/__tests__/__snapshots__/demo.test.js.snap
  components/drawer/__tests__/__snapshots__/demo.test.js.snap
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/icon/index.tsx
  components/progress/__tests__/__snapshots__/demo.test.js.snap
  components/tabs/__tests__/__snapshots__/demo.test.js.snap
  components/tag/__tests__/__snapshots__/demo.test.js.snap
Labels: PR: unreviewed

#17510 Feat/remove deprecated
  components/breadcrumb/Breadcrumb.tsx
  components/breadcrumb/__tests__/Breadcrumb.test.js
  components/menu/__tests__/index.test.js
  components/menu/index.tsx
  components/popover/__tests__/index.test.js
  components/popover/index.tsx
  components/table/Table.tsx
  components/table/__tests__/Table.test.js
  components/tag/__tests__/index.test.js
  components/tag/index.en-US.md
  components/tag/index.tsx
  components/tag/index.zh-CN.md
  components/transfer/__tests__/customize.test.js
  components/transfer/__tests__/index.test.js
  components/transfer/__tests__/search.test.js
  components/transfer/index.tsx
  components/transfer/list.tsx
  components/transfer/renderListBody.tsx
Labels: PR: reviewed-approved

#17545 fix: props#locale description in Transfer
  components/transfer/index.en-US.md
  components/transfer/index.zh-CN.md
Labels: PR: unreviewed

#17538 fix(Cascader): Should show not found content when options.length is 0
  components/cascader/__tests__/__snapshots__/index.test.js.snap
  components/cascader/__tests__/index.test.js
  components/cascader/index.tsx
Labels: PR: reviewed-approved

#17537 chore: Merge master into feature
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  README-zh_CN.md
  README.md
  components/auto-complete/index.en-US.md
  components/auto-complete/index.tsx
  components/cascader/__tests__/__snapshots__/index.test.js.snap
  components/cascader/__tests__/index.test.js
  components/cascader/index.tsx
  components/date-picker/style/Calendar.less
  components/date-picker/style/RangePicker.less
  components/date-picker/style/TimePicker.less
  components/drawer/index.tsx
  components/drawer/style/index.tsx
  components/form/Form.tsx
  components/form/__tests__/message.test.js
  components/icon/__tests__/index.test.js
  components/icon/utils.ts
  components/input/style/mixin.less
  components/list/index.en-US.md
  components/list/index.zh-CN.md
  components/locale-provider/index.en-US.md
  components/locale-provider/index.zh-CN.md
  components/popconfirm/__tests__/__snapshots__/index.test.js.snap
  components/result/__tests__/__snapshots__/demo.test.js.snap
  components/result/__tests__/index.test.js
  components/result/demo/403.md
  components/result/demo/404.md
  components/result/demo/500.md
  components/result/demo/basic.md
  components/result/demo/customIcon.md
  components/result/demo/error.md
  components/result/demo/info.md
  components/result/demo/success.md
  components/result/demo/warning.md
  components/result/index.tsx
  components/result/style/index.less
  components/select/index.en-US.md
  components/select/index.zh-CN.md
  components/switch/index.tsx
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/tabs/style/card-style.less
  components/tabs/style/index.less
  components/time-picker/style/index.less
  components/tooltip/__tests__/__snapshots__/tooltip.test.js.snap
  components/tooltip/__tests__/tooltip.test.js
  components/tooltip/index.tsx
  components/transfer/index.en-US.md
  components/transfer/index.zh-CN.md
  components/upload/UploadList.tsx
  components/upload/__tests__/uploadlist.test.js
  components/upload/interface.tsx
  docs/react/introduce.en-US.md
  docs/react/introduce.zh-CN.md
  package.json
  site/theme/static/markdown.less
  site/theme/template/IconDisplay/fields.ts
Labels: PR: reviewed-approved

#17550 fix: Align cascader loading style & update doc
  components/cascader/index.en-US.md
  components/cascader/index.zh-CN.md
  components/cascader/style/index.less
Labels: PR: unreviewed

#17559 fix Descriptions title ts type
  components/descriptions/index.tsx
Labels: PR: reviewed-approved

#17558 Fix: Apply inline style for Descriptions component
  components/descriptions/__tests__/__snapshots__/index.test.js.snap
  components/descriptions/__tests__/index.test.js
  components/descriptions/index.tsx
Labels: PR: reviewed-changes-requested

#17560 feat: Descriptions support colon props
  components/descriptions/Col.tsx
  components/descriptions/__tests__/__snapshots__/demo.test.js.snap
  components/descriptions/__tests__/__snapshots__/index.test.js.snap
  components/descriptions/__tests__/index.test.js
  components/descriptions/index.en-US.md
  components/descriptions/index.tsx
  components/descriptions/index.zh-CN.md
  components/descriptions/style/index.less
Labels: PR: reviewed-approved

#17581 fix: Typescript definition of CascaderOptionType missing some fields #17555
  components/cascader/index.tsx
Labels: PR: unreviewed

#17583 fix: 💄 Optimize Cascader input style
  components/cascader/style/index.less
Labels: PR: unreviewed

#17589 Update the markup example in API section of menu.md
  components/menu/index.en-US.md
  components/menu/index.zh-CN.md
Labels: PR: unreviewed

#17596 fix: button loading style(#17569)
  components/button/style/index.less
Labels: PR: unreviewed

#17592 docs: fix typo
  components/breadcrumb/index.zh-CN.md
Labels: PR: unreviewed

#17586 Update responsive.md
  components/descriptions/demo/responsive.md
Labels: PR: unreviewed

#17607 fix(test): Jest with ES Modules of react-dnd
  .jest.js
  .jest.node.js
  components/descriptions/__tests__/__snapshots__/demo.test.js.snap
Labels: PR: unreviewed

#17557 fix: Collapse Panel key type definition
  components/collapse/Collapse.tsx
  components/collapse/CollapsePanel.tsx
  components/collapse/index.en-US.md
  components/collapse/index.zh-CN.md
Labels: PR: reviewed-approved

#17620 feat: Anchor组件当前activeLink和之前activeLink变化后才setState
  components/anchor/Anchor.tsx
Labels: PR: reviewed-approved

#17621 docs: Add the changelog of 3.20.2
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: reviewed-approved

#17633 Update 404.md
  components/result/demo/404.md
Labels: PR: unreviewed

#17639 Revert #17508
  components/button/style/index.less
  components/descriptions/style/index.less
  components/input/style/mixin.less
  components/mentions/style/index.less
Labels: PR: reviewed-approved

#17646 Add 3.20.3 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: reviewed-approved, needs-more-info

#17629 Extend MenuItemProps from HTMLAttributes<HTMLLIElement>
  components/menu/MenuItem.tsx
Labels: PR: unreviewed

#17641 fix: Table border radius missing in Firefox
  components/table/style/index.less
Labels: PR: unreviewed

#17656 chore: update snapshot
  components/table/__tests__/__snapshots__/demo.test.js.snap
Labels: PR: unreviewed

#17653 chore: merge master into feature
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/input/style/mixin.less
  components/menu/MenuItem.tsx
  components/result/__tests__/__snapshots__/demo.test.js.snap
  components/result/demo/404.md
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/style/index.less
  package.json
Labels: PR: reviewed-approved

#17664 fix: Adjust `onSelect` & `onChange` trigger order
  package.json
Labels: PR: unreviewed

#17657 fix: Cannot update during an existing state transition
  components/menu/__tests__/index.test.js
  components/menu/index.tsx
Labels: PR: unreviewed

#17673 修改api的样式错误
  components/drawer/index.zh-CN.md
Labels: PR: unreviewed

#17676 feat(Form): upgrade setFieldsValue function declaration
  components/form/Form.tsx
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: PR: unreviewed

#17678 fix: Adjust measure logic
  components/affix/__tests__/Affix.test.js
  components/affix/__tests__/__snapshots__/demo.test.js.snap
  components/affix/demo/debug.md
  components/affix/index.tsx
Labels: PR: unreviewed

#17677 feat: Re-bind scroll events when components change, add test cases
  components/anchor/Anchor.tsx
  components/anchor/__tests__/Anchor.test.js
Labels: PR: reviewed-changes-requested

#17675 fix: Correct renderTabBar type
  components/tabs/index.en-US.md
  components/tabs/index.tsx
  components/tabs/index.zh-CN.md
Labels: PR: unreviewed

#17659 feat(Empty): description prop support false value to remove description node
  components/empty/__tests__/__snapshots__/demo.test.js.snap
  components/empty/__tests__/index.test.js
  components/empty/demo/description.md
  components/empty/index.tsx
Labels: PR: unreviewed

#17692 汉化api标题
  components/comment/index.zh-CN.md
Labels: PR: unreviewed

#17652 update the form typescript definition（branch 4.0-prepare）
  components/form/Form.tsx
Labels: PR: unreviewed

#17695 汉化api标题
  components/card/index.zh-CN.md
Labels: PR: unreviewed

#17696 docs: correct form documentation
  components/form/index.zh-CN.md
Labels: PR: unreviewed

#17600 fix: unified modal and drawer protal and fix overflow conflict
  components/config-provider/__tests__/components.test.js
  components/drawer/index.en-US.md
  components/drawer/index.tsx
  components/drawer/index.zh-CN.md
  components/locale-provider/__tests__/index.test.js
  components/modal/Modal.tsx
  components/modal/__tests__/__snapshots__/Modal.test.js.snap
  components/modal/__tests__/confirm.test.js
  components/modal/confirm.tsx
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
  package.json
Labels: PR: unreviewed

#17698 fix: delete drawer in child and re-render, no push started
  components/drawer/__tests__/MultiDrawer.test.js
  components/drawer/index.tsx
  components/drawer/style/drawer.less
Labels: PR: unreviewed

#17613 feat: create variable for customize size of icon on menu
  components/menu/style/index.less
  components/style/themes/default.less
Labels: PR: reviewed-approved

#17697 style: Improve less variables
  components/button/style/mixin.less
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/progress/Line.tsx
  components/progress/__tests__/__snapshots__/demo.test.js.snap
  components/progress/__tests__/__snapshots__/index.test.js.snap
  components/progress/style/index.less
  components/slider/style/index.less
  components/style/themes/default.less
  components/tabs/style/card-style.less
  components/tabs/style/index.less
  components/timeline/style/index.less
  components/tree-select/style/index.less
  components/upload/__tests__/__snapshots__/uploadlist.test.js.snap
Labels: PR: unreviewed

#17703 Update FormItem typescript definition
  components/form/FormItem.tsx
Labels: PR: unreviewed

#17705 style: expand card action click area
  components/card/style/index.less
Labels: PR: unreviewed

#17707 chore: fix dekko test
  tests/dekko/lib.test.js
Labels: PR: unreviewed

#17719 Fixed typo in use-with-create-react-app.en-US.md
  docs/react/use-with-create-react-app.en-US.md
Labels: PR: unreviewed

#17728 :lipstick: pagiation item hovering without underline
  components/pagination/style/index.less
Labels: PR: unreviewed

#17732 Merge master into feature
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/pr_cn.md
  components/affix/__tests__/Affix.test.js
  components/affix/__tests__/__snapshots__/demo.test.js.snap
  components/affix/demo/debug.md
  components/affix/index.tsx
  components/anchor/Anchor.tsx
  components/anchor/__tests__/Anchor.test.js
  components/button/style/mixin.less
  components/card/index.zh-CN.md
  components/card/style/index.less
  components/comment/index.zh-CN.md
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/config-provider/__tests__/components.test.js
  components/drawer/__tests__/MultiDrawer.test.js
  components/drawer/index.en-US.md
  components/drawer/index.tsx
  components/drawer/index.zh-CN.md
  components/drawer/style/drawer.less
  components/empty/__tests__/__snapshots__/demo.test.js.snap
  components/empty/__tests__/index.test.js
  components/empty/demo/description.md
  components/empty/index.tsx
  components/form/Form.tsx
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/locale-provider/__tests__/index.test.js
  components/menu/__tests__/index.test.js
  components/menu/index.tsx
  components/modal/Modal.tsx
  components/modal/__tests__/__snapshots__/Modal.test.js.snap
  components/modal/__tests__/confirm.test.js
  components/modal/confirm.tsx
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
  components/pagination/style/index.less
  components/progress/Line.tsx
  components/progress/__tests__/__snapshots__/demo.test.js.snap
  components/progress/__tests__/__snapshots__/index.test.js.snap
  components/progress/style/index.less
  components/slider/style/index.less
  components/style/themes/default.less
  components/tabs/index.en-US.md
  components/tabs/index.tsx
  components/tabs/index.zh-CN.md
  components/tabs/style/card-style.less
  components/tabs/style/index.less
  components/timeline/style/index.less
  components/tree-select/style/index.less
  components/upload/__tests__/__snapshots__/uploadlist.test.js.snap
  docs/react/use-with-create-react-app.en-US.md
  package.json
  site/bisheng.config.js
  site/theme/static/common.less
  site/theme/template/Content/MainContent.jsx
  tests/dekko/lib.test.js
Labels: PR: reviewed-approved

#17733 Update lodash
  package.json
Labels: PR: unreviewed

#17729 feat: rename FormItem `inline` to `noStyle`
  components/form/FormItem.tsx
  components/form/__tests__/index.test.js
  components/form/context.tsx
  components/form/demo/control-hooks.md
  components/form/demo/control-ref.md
  components/form/demo/dynamic-form-item.md
  components/form/demo/normal-login.md
  components/form/demo/register.md
  components/form/demo/validate-other.md
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/form/v3.en-US.md
  components/form/v3.zh-CN.md
Labels: PR: reviewed-approved

#17731 feat: support gray color Timeline.Item
  components/timeline/TimelineItem.tsx
  components/timeline/__tests__/__snapshots__/demo.test.js.snap
  components/timeline/demo/color.md
  components/timeline/index.en-US.md
  components/timeline/index.zh-CN.md
  components/timeline/style/index.less
Labels: PR: reviewed-approved

#17739 docs: update changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#17708 chore: remove unnecessary disable default props
  components/input/Input.tsx
  components/input/__tests__/__snapshots__/index.test.js.snap
  components/radio/group.tsx
  components/time-picker/index.tsx
  components/transfer/__tests__/__snapshots__/search.test.js.snap
Labels: PR: unreviewed

#17743 fix: Button danger style when type is ghost
  components/button/style/index.less
Labels: PR: unreviewed

#17751 Add deploy workflow
  .github/main.workflow
Labels: PR: unreviewed

#17748 fix: All .ant-col sets the min-height
  components/grid/style/index.less
  components/grid/style/mixin.less
Labels: PR: unreviewed

#17756 fix: Cascader broken when option children is null
  components/cascader/__tests__/index.test.js
  components/cascader/index.tsx
Labels: PR: unreviewed

#17752 fix: Styling issue where all spans next to a checkbox wrapper get a padding
  components/checkbox/style/mixin.less
  components/table/style/index.less
Labels: PR: unreviewed

#17759 fix: Input line height in IE
  components/input/style/mixin.less
Labels: PR: unreviewed

#17761 fix: Styling issue where all spans next to a checkbox wrapper get a padding
  components/transfer/ListItem.tsx
  components/transfer/__tests__/__snapshots__/index.test.js.snap
  components/transfer/__tests__/__snapshots__/list.test.js.snap
  components/transfer/style/index.less
Labels: PR: unreviewed

#17764 style: Remove right-margin of last item in Rate component
  components/rate/__tests__/__snapshots__/demo.test.js.snap
  components/rate/demo/clear.md
  components/rate/style/index.less
Labels: PR: unreviewed

#17767 Update electron official website;
  docs/react/introduce.zh-CN.md
Labels: PR: unreviewed

#17775 fix: Radio.Button disabled item style
  components/radio/style/index.less
Labels: PR: unreviewed

#17784 style: DatePicker hover style less variable
  components/date-picker/style/Picker.less
Labels: PR: unreviewed

#17783 fix: Transfer change `dataSource` will re-fresh lazy render
  components/transfer/renderListBody.tsx
Labels: PR: unreviewed

#17694 fix: DatePicker date order
  components/date-picker/RangePicker.tsx
  components/date-picker/__tests__/RangePicker.test.js
Labels: PR: unreviewed

#17792 Add link for UI Kit for Framer X
  docs/spec/download.en-US.md
Labels: PR: unreviewed

#17797 Long placeholders truncate
  components/style/mixins/compatibility.less
Labels: PR: unreviewed

#17805 fix: circular dependency in Menu
  components/menu/MenuContext.tsx
  components/menu/MenuItem.tsx
  components/menu/SubMenu.tsx
  components/menu/index.tsx
Labels: PR: unreviewed

#17808 fix: make alert message attribute affect message even without description
  components/alert/style/index.less
Labels: PR: unreviewed

#17786 fix: Result extra is not centered
  components/result/style/index.less
Labels: PR: unreviewed

#17806 feat: Table getPopupContainer
  components/table/Table.tsx
  components/table/__tests__/Table.filter.test.js
  components/table/__tests__/__snapshots__/Table.filter.test.js.snap
  components/table/filterDropdown.tsx
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/table/interface.tsx
Labels: PR: reviewed-approved

#17818 completing the Chinese document for Select component
  components/select/index.zh-CN.md
Labels: PR: unreviewed

#17819 fix: Line Progress with mini value should keep bar radius round
  components/progress/style/index.less
Labels: PR: unreviewed

#17820 style: correct @input-hover-border-color
  components/input/style/mixin.less
  components/style/themes/default.less
Labels: PR: unreviewed

#17832 Update faq.en-US.md
  docs/react/faq.en-US.md
Labels: PR: unreviewed

#17841 fix: CountDown should support escape
  components/statistic/__tests__/index.test.js
  components/statistic/utils.tsx
Labels: PR: reviewed-changes-requested

#17846 fix: table filter dropdown trigger onChange on some situation
  components/table/__tests__/Table.filter.test.js
  components/table/filterDropdown.tsx
Labels: PR: reviewed-changes-requested

#17857 fix: TimePicker safari weird render bug
  components/time-picker/style/index.less
Labels: PR: unreviewed

#17861 Release 3.20.6
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#17897 fix: Upload can not click in Form.Item
  components/upload/style/index.less
Labels: PR: unreviewed

#17902 docs: add changelog of 3.20.7
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#17943 style: unified drawer and modal mask opacity
  components/drawer/style/drawer.less
  components/style/themes/default.less
Labels: PR: unreviewed

#17945 fix: Wave perf
  components/_util/wave.tsx
Labels: PR: reviewed-approved

#17760 fix: Optimize select with search field style
  components/select/style/index.less
Labels: PR: unreviewed

#17959 fix: make timeline component show more comfort under none-white background color
  components/timeline/style/index.less
Labels: PR: unreviewed

#17961 chore: prerender support title
  site/theme/static/template.html
Labels: PR: unreviewed

#17968 docs: Add faq about form validator errors
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: PR: unreviewed

#17970 fix: Remove extra margin right of Table placeholder
  components/table/style/index.less
Labels: PR: unreviewed

#17969 fix: Tabs extraContent line-height
  components/tabs/style/card-style.less
Labels: PR: unreviewed

#17955 fix: DatePicker onChange types
  components/date-picker/interface.tsx
Labels: PR: unreviewed

#17971 refactor: Tag should be span than a div semantically
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/date-picker/__tests__/__snapshots__/RangePicker.test.js.snap
  components/page-header/__tests__/__snapshots__/demo.test.js.snap
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/tag/CheckableTag.tsx
  components/tag/__tests__/__snapshots__/demo.test.js.snap
  components/tag/__tests__/__snapshots__/index.test.js.snap
  components/tag/__tests__/index.test.js
  components/tag/index.tsx
  components/transfer/__tests__/__snapshots__/demo.test.js.snap
Labels: PR: reviewed-changes-requested

#17887 fix: the DatePicker border bug when the chose was century
  components/date-picker/style/MonthPanel.less
  components/date-picker/style/RangePicker.less
  components/date-picker/style/YearPanel.less
Labels: PR: unreviewed

#17974 upd: bisheng
  package.json
Labels: PR: unreviewed, needs-more-info

#17965 fix: children of Tabs[type="editable-card"] cannot be falsy
  components/tabs/__tests__/index.test.js
  components/tabs/index.tsx
Labels: PR: unreviewed

#17872 fix: remove a tag in Alert component
  components/alert/__tests__/__snapshots__/demo.test.js.snap
  components/alert/index.tsx
  components/alert/style/index.less
Labels: PR: unreviewed

#17983 style: optimize RangePicker active cell style
  components/date-picker/style/Calendar.less
  components/date-picker/style/RangePicker.less
Labels: PR: unreviewed

#17976 feat(default.less): add table-footer-bg and table-footer-color variable
  components/style/themes/default.less
  components/table/style/index.less
Labels: PR: reviewed-approved

#17985 fix(Form.Item): fix label replace regexp err replace
  components/form/FormItem.tsx
Labels: PR: unreviewed

#17989 fix: range picker and select broken style
  components/date-picker/style/Calendar.less
  components/date-picker/style/RangePicker.less
  components/select/style/index.less
Labels: PR: unreviewed

#17990 doc: update Table component's selectedRowKeys wrong type
  components/table/index.en-US.md
  components/table/index.zh-CN.md
Labels: PR: unreviewed

#17993 chore: use pretty-quick
  package.json
Labels: PR: unreviewed
