Repository ant-design/ant-design, pull requests merged in 2019-09, with the labels that each got.

#18598 简字化
  docs/react/i18n.zh-CN.md
Labels: PR: unreviewed

#18589 fix: nested List style in grid layout
  components/list/style/index.less
Labels: PR: unreviewed

#18603 fix: Chrome input position not align with button
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/demo/algin.md
  components/input/style/mixin.less
  components/mentions/style/index.less
Labels: PR: reviewed-approved

#18606 docs: fix option-label-prop.md typo error
  components/select/demo/option-label-prop.md
Labels: PR: unreviewed

#18455 doc: 3.23.0 Changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed

#18616 chore: upgrade version to 3.23.0
  package.json
Labels: PR: unreviewed

#18584 fix: add missing typescript inputValue to Select to enable placeholder to display for type string
  components/select/index.en-US.md
  components/select/index.tsx
Labels: PR: unreviewed

#18593 feat: Add @tree-node-hover-bg and @tree-node-selected-bg less variables
  components/style/themes/default.less
  components/tree/style/index.less
Labels: PR: unreviewed

#18624 fix: MonthPicker switch icon overflow style
  components/date-picker/style/DecadePanel.less
  components/date-picker/style/MonthPanel.less
  components/date-picker/style/YearPanel.less
Labels: PR: unreviewed

#18626 fix: Revert "fix: Upload.Dragger should work with multiple is false"
  components/upload/Upload.tsx
  components/upload/__tests__/upload.test.js
Labels: PR: reviewed-changes-requested

#18627 docs: 3.23.1 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#18553 fix(layoutSider): dimensionMap for max-width media query
  components/layout/Sider.tsx
Labels: PR: unreviewed

#18628 chore: fix site deploy actions
  .github/workflows/deploy-site.yml
Labels: PR: unreviewed, needs-more-info

#18636 fix: #18607
  components/drawer/style/drawer.less
Labels: PR: unreviewed

#18637 fix: Descriptions warning with key
  components/descriptions/__tests__/__snapshots__/index.test.js.snap
  components/descriptions/__tests__/index.test.js
  components/descriptions/index.tsx
Labels: PR: reviewed-changes-requested

#18645 fix error of tree component doc
  components/tree/index.en-US.md
Labels: PR: unreviewed

#18646 fix: Anchor.Link target should not be required
  components/anchor/AnchorLink.tsx
Labels: PR: unreviewed

#18656 refactor: Use slice instead of filter
  components/table/Table.tsx
Labels: PR: unreviewed

#18665 docs: Fix PageHeader demo
  components/page-header/demo/actions.md
  components/page-header/demo/responsive.md
Labels: PR: unreviewed

#18663 test(Anchor): optimize dataNowMockFn, avoid being consumed in advance
  .circleci/config.yml
  components/anchor/__tests__/Anchor.test.js
Labels: PR: unreviewed

#18668 fix: navigation Steps hover color
  components/steps/style/index.less
Labels: PR: unreviewed

#18671 fix: transformFileHandler ts def
  components/upload/interface.tsx
Labels: PR: unreviewed

#18697 fix: update type
  components/table/interface.tsx
Labels: PR: unreviewed

#18518 fix: unused Descriptions parameter "border"
  components/descriptions/demo/size.md
Labels: PR: reviewed-approved

#18701 fix: round button font size too large
  components/button/style/mixin.less
Labels: PR: unreviewed

#18691 fix(PageHeader): Allow back icon to coexist with breadcrumb
  components/page-header/__tests__/index.test.js
  components/page-header/index.tsx
Labels: PR: reviewed-approved

#18445 fix: result types
  components/result/index.tsx
Labels: PR: unreviewed

#18710 docs: Add the changelog of 3.23.2
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed

#18715 feat(Anchor): add onChange prop
  components/anchor/Anchor.tsx
  components/anchor/__tests__/Anchor.test.js
  components/anchor/__tests__/__snapshots__/demo.test.js.snap
  components/anchor/demo/onChange.md
  components/anchor/demo/targetOffset.md
  components/anchor/index.en-US.md
  components/anchor/index.zh-CN.md
Labels: PR: reviewed-approved

#18720 test: fix ci fail
  components/progress/__tests__/__snapshots__/demo.test.js.snap
Labels: PR: unreviewed

#18723 Fixed error in modal documentation
  components/modal/index.en-US.md
Labels: PR: unreviewed

#18724 fix: link button should not insert space
  components/button/__tests__/__snapshots__/index.test.js.snap
  components/button/__tests__/index.test.js
  components/button/button.tsx
Labels: PR: unreviewed

#18732 fix: ConfigProvider locale not working with Modal in some situation
  components/config-provider/__tests__/locale.test.js
  components/locale-provider/index.tsx
Labels: PR: reviewed-changes-requested

#18737 fix: the doc of tree component
  components/tree/index.en-US.md
  components/tree/index.zh-CN.md
Labels: PR: unreviewed

#18755 chore(docs): update for #18719
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: PR: unreviewed

#18747 chore: sort package.json by sort-package-json
  package.json
Labels: PR: unreviewed

#18770 chore(docs): add dropdownMenuStyle props for AutoComplete and Select
  components/auto-complete/index.en-US.md
  components/auto-complete/index.tsx
  components/auto-complete/index.zh-CN.md
  components/select/index.en-US.md
  components/select/index.zh-CN.md
Labels: PR: unreviewed

#18664 feat: upload add download icon
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/locale/default.tsx
  components/locale/zh_CN.tsx
  components/upload/Upload.tsx
  components/upload/UploadList.tsx
  components/upload/__tests__/__snapshots__/demo.test.js.snap
  components/upload/__tests__/__snapshots__/uploadlist.test.js.snap
  components/upload/__tests__/upload.test.js
  components/upload/__tests__/uploadlist.test.js
  components/upload/index.en-US.md
  components/upload/index.zh-CN.md
  components/upload/interface.tsx
  components/upload/style/index.less
Labels: PR: reviewed-approved

#18768 fix(module:avatar): Extrusion Deformation of Long Pictures
  components/avatar/style/index.less
Labels: PR: unreviewed

#18775 docs: update Descriptions documentation
  components/descriptions/index.zh-CN.md
  components/page-header/index.en-US.md
  components/page-header/index.zh-CN.md
Labels: PR: unreviewed

#18741 docs: update param version info(3.10.0) for title
  components/table/index.zh-CN.md
Labels: PR: unreviewed

#18764 chore: publish to github-package when released
  .github/workflows/publish-to-github-package.yml
Labels: PR: unreviewed

#18802 chore: merge master into feature
  .github/workflows/publish-to-github-package.yml
  CHANGELOG.zh-CN.md
  README-zh_CN.md
  README.md
  components/alert/__tests__/__snapshots__/demo.test.js.snap
  components/alert/index.tsx
  components/alert/style/index.less
  components/auto-complete/index.en-US.md
  components/auto-complete/index.tsx
  components/auto-complete/index.zh-CN.md
  components/avatar/style/index.less
  components/button/__tests__/__snapshots__/index.test.js.snap
  components/button/__tests__/index.test.js
  components/button/button.tsx
  components/config-provider/__tests__/locale.test.js
  components/descriptions/index.zh-CN.md
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/demo/validate-other.md
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/input-number/style/index.less
  components/input/Search.tsx
  components/input/__tests__/Search.test.js
  components/input/__tests__/__snapshots__/index.test.js.snap
  components/locale-provider/index.tsx
  components/modal/index.en-US.md
  components/page-header/index.en-US.md
  components/page-header/index.zh-CN.md
  components/select/index.en-US.md
  components/select/index.zh-CN.md
  components/table/index.zh-CN.md
  components/transfer/index.en-US.md
  components/transfer/index.zh-CN.md
  components/tree/Tree.tsx
  components/tree/index.en-US.md
  components/tree/index.zh-CN.md
  docs/spec/overview.en-US.md
  package.json
  scripts/check-demo.js
  site/theme/en-US.js
  site/theme/static/template.html
  site/theme/template/Content/Article.jsx
  site/theme/template/Content/ComponentDoc.jsx
  site/theme/template/Home/index.jsx
  site/theme/template/Layout/index.jsx
  site/theme/template/utils.jsx
Labels: PR: reviewed-approved

#18800 fix: redundant jobs of github actions
  .github/workflows/deploy-site.yml
Labels: PR: unreviewed

#18817 chore: merge master
  .github/workflows/deploy-site.yml
  .github/workflows/publish-to-github-package.yml
  CHANGELOG.zh-CN.md
  README-zh_CN.md
  README.md
  components/alert/__tests__/__snapshots__/demo.test.js.snap
  components/alert/index.tsx
  components/alert/style/index.less
  components/avatar/style/index.less
  components/button/__tests__/__snapshots__/index.test.js.snap
  components/button/__tests__/index.test.js
  components/button/button.tsx
  components/config-provider/__tests__/locale.test.js
  components/descriptions/index.zh-CN.md
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/demo/validate-other.md
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/input-number/style/index.less
  components/input/Search.tsx
  components/input/__tests__/Search.test.js
  components/input/__tests__/__snapshots__/index.test.js.snap
  components/locale-provider/index.tsx
  components/page-header/index.en-US.md
  components/page-header/index.zh-CN.md
  components/select/index.en-US.md
  components/select/index.zh-CN.md
  components/table/index.zh-CN.md
  components/transfer/index.en-US.md
  components/transfer/index.zh-CN.md
  components/tree/Tree.tsx
  components/tree/index.en-US.md
  components/tree/index.zh-CN.md
  docs/spec/overview.en-US.md
  package.json
  scripts/check-demo.js
  site/theme/en-US.js
  site/theme/static/template.html
  site/theme/template/Content/Article.jsx
  site/theme/template/Content/ComponentDoc.jsx
  site/theme/template/Home/index.jsx
  site/theme/template/Layout/index.jsx
  site/theme/template/utils.jsx
Labels: PR: reviewed-changes-requested

#18815 docs: Add `Article` in guideline
  docs/spec/article.en-US.md
  docs/spec/article.zh-CN.md
  docs/spec/work-with-us.en-US.md
  docs/spec/work-with-us.zh-CN.md
Labels: PR: unreviewed

#18820 fix: Button text color inside Menu
  components/menu/style/dark.less
Labels: PR: unreviewed

#18828 fix: Improve code for better compatibility
  components/_util/responsiveObserve.ts
  components/carousel/index.tsx
  components/layout/Sider.tsx
Labels: PR: reviewed-changes-requested

#18835 Fix grammar
  docs/react/getting-started.en-US.md
Labels: PR: unreviewed

#18821 fix: small table headers missing border
  components/table/style/size.less
Labels: PR: reviewed-approved

#18819 release: 3.23.3 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: reviewed-approved, needs-more-info

#18850 fix: multiple should work with Upload.Dragger
  package.json
Labels: PR: reviewed-changes-requested

#18849 fix: fix #18848
  components/transfer/__tests__/index.test.js
  components/transfer/renderListBody.tsx
Labels: PR: unreviewed

#17614 feat: Add visible to filterDropdown function
  components/card/index.zh-CN.md
  components/date-picker/__tests__/RangePicker.test.js
  components/table/__tests__/Table.filter.test.js
  components/table/filterDropdown.tsx
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/table/interface.tsx
  site/theme/static/common.less
Labels: PR: reviewed-approved

#18852 chore: merge master into feature
  .github/workflows/deploy-site.yml
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/_util/responsiveObserve.ts
  components/alert/style/index.less
  components/carousel/index.tsx
  components/input-number/style/index.less
  components/layout/Sider.tsx
  components/menu/style/dark.less
  components/table/style/size.less
  components/tabs/style/index.less
  components/timeline/style/index.less
  components/transfer/__tests__/index.test.js
  components/transfer/renderListBody.tsx
  components/typography/style/index.less
  docs/react/getting-started.en-US.md
  docs/spec/article.en-US.md
  docs/spec/article.zh-CN.md
  docs/spec/work-with-us.en-US.md
  docs/spec/work-with-us.zh-CN.md
  package.json
  site/theme/static/markdown.less
Labels: PR: reviewed-approved

#18854 chore: remove unneccessary changes of #17614
  components/card/index.zh-CN.md
  components/table/filterDropdown.tsx
Labels: PR: reviewed-approved

#18858 fix: Input addonAfter icon height bug in Chrome
  components/input/style/mixin.less
Labels: PR: unreviewed

#18859 docs: 添加tooltip destroyTooltipOnHide Api说明
  components/tooltip/index.en-US.md
  components/tooltip/index.zh-CN.md
Labels: PR: unreviewed

#18866 feat: Tree support accessibility & keyboard
  components/input-number/style/index.less
  components/tree/style/index.less
  package.json
Labels: PR: unreviewed

#18882 fix: site ssr react-intl
  package.json
  site/theme/template/Layout/index.jsx
Labels: PR: unreviewed

#18871 chore: upd antd 4.0 version
  README.md
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/tooltip/index.en-US.md
  components/tooltip/index.zh-CN.md
  components/transfer/__tests__/__snapshots__/demo.test.js.snap
  components/tree/__tests__/__snapshots__/demo.test.js.snap
  components/tree/__tests__/__snapshots__/directory.test.js.snap
  package.json
  site/theme/template/Layout/index.jsx
Labels: PR: unreviewed

#18851 fix: correct registry-url
  .github/workflows/publish-to-github-package.yml
Labels: PR: unreviewed

#18884 restore: react-intl intl polyfill
  package.json
  site/theme/template/Layout/index.jsx
Labels: PR: unreviewed

#18887 style: add @page-header-back-color less variable
  components/page-header/style/index.less
  components/style/themes/default.less
Labels: PR: unreviewed

#18906 docs: Add TreeSelect async demo
  components/tree-select/__tests__/__snapshots__/demo.test.js.snap
  components/tree-select/demo/async.md
Labels: PR: unreviewed

#18900 fix: Disabled input should not trigger the action of suffix part #18889
  components/input/Password.tsx
  components/input/Search.tsx
  components/input/__tests__/Password.test.js
  components/input/__tests__/Search.test.js
  components/input/style/mixin.less
Labels: PR: unreviewed

#18910 table: Correct onRow event handlers to receive a MouseEvent
  components/table/interface.tsx
Labels: PR: unreviewed

#18915 docs: update props data description for Upload
  components/upload/index.en-US.md
  components/upload/index.zh-CN.md
Labels: PR: unreviewed

#18922 tweak: site specialChar encoding
  site/theme/template/Content/Article.jsx
  site/theme/template/Content/ComponentDoc.jsx
  site/theme/template/Home/index.jsx
  site/theme/template/Layout/index.jsx
Labels: PR: reviewed-approved

#18929 fix: Alert add css word break
  components/alert/style/index.less
Labels: PR: unreviewed

#18932 docs: add 3.23.4 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/tooltip/index.en-US.md
  components/tooltip/index.tsx
  components/tooltip/index.zh-CN.md
  package.json
Labels: PR: unreviewed

#18933 fix: skip postinstall of antd-tools
  .github/workflows/publish-to-github-package.yml
Labels: PR: unreviewed

#18937 feat: upload should not be aborted until handleRemove is resolved
  components/upload/Upload.tsx
  components/upload/__tests__/upload.test.js
Labels: PR: reviewed-approved

#18941 feat: Breadcrumb support data against
  components/breadcrumb/Breadcrumb.tsx
  components/breadcrumb/__tests__/Breadcrumb.test.js
  components/breadcrumb/__tests__/__snapshots__/Breadcrumb.test.js.snap
  components/menu/__tests__/index.test.js
Labels: PR: unreviewed

#18946 RowAligns add 'stretch' value
  components/grid/row.tsx
Labels: PR: unreviewed

#18952 chore: merge master into feature
  .github/workflows/publish-to-github-package.yml
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  README-zh_CN.md
  README.md
  components/alert/style/index.less
  components/breadcrumb/Breadcrumb.tsx
  components/breadcrumb/__tests__/Breadcrumb.test.js
  components/breadcrumb/__tests__/__snapshots__/Breadcrumb.test.js.snap
  components/grid/row.tsx
  components/input/Password.tsx
  components/input/Search.tsx
  components/input/__tests__/Password.test.js
  components/input/__tests__/Search.test.js
  components/input/style/mixin.less
  components/menu/__tests__/index.test.js
  components/menu/index.tsx
  components/page-header/style/index.less
  components/style/themes/default.less
  components/table/interface.tsx
  components/tooltip/index.tsx
  components/tree-select/__tests__/__snapshots__/demo.test.js.snap
  components/tree-select/demo/async.md
  components/upload/Dragger.tsx
  components/upload/index.en-US.md
  components/upload/index.zh-CN.md
  docs/spec/overview.zh-CN.md
  package.json
  site/theme/en-US.js
  site/theme/static/footer.less
  site/theme/static/responsive.less
  site/theme/template/Content/Article.jsx
  site/theme/template/Content/ComponentDoc.jsx
  site/theme/template/Home/index.jsx
  site/theme/template/Layout/Footer.jsx
  site/theme/template/Layout/index.jsx
  site/theme/zh-CN.js
Labels: PR: reviewed-approved

#18949 fix: TreeSelect removeIcon and clearIcon not working
  components/tree-select/__tests__/__snapshots__/index.test.js.snap
  components/tree-select/__tests__/index.test.js
  components/tree-select/index.tsx
  components/tree-select/interface.tsx
Labels: PR: unreviewed

#18964 feat(actions): Automatic Rebase
  .github/workflows/rebase.yml
Labels: PR: unreviewed

#18977 docs: fix API link
  components/page-header/index.zh-CN.md
Labels: PR: unreviewed

#18987 test: ✅ react-router@5.1 cannot work in React 15
  components/breadcrumb/__tests__/router.test.js
Labels: PR: reviewed-changes-requested

#18990 chore: Put origin img size to fill the box
  components/upload/style/index.less
Labels: PR: unreviewed

#18678 feat: support updating message content with a unique key
  components/message/__tests__/__snapshots__/demo.test.js.snap
  components/message/__tests__/index.test.js
  components/message/demo/update.md
  components/message/index.en-US.md
  components/message/index.tsx
  components/message/index.zh-CN.md
Labels: PR: unreviewed

#18994 fix: Button.Group large="size" icon only style
  components/button/style/mixin.less
Labels: PR: unreviewed

#19003 fix: 🗑 Remove useless prop `searchValue`
  components/select/__tests__/index.test.js
  components/select/index.en-US.md
  components/select/index.tsx
  components/select/index.zh-CN.md
Labels: PR: unreviewed

#19011 test: ✅ add more test cases for Transfer
  components/transfer/__tests__/__snapshots__/index.test.js.snap
  components/transfer/__tests__/index.test.js
  components/transfer/__tests__/search.test.js
Labels: PR: reviewed-changes-requested

#19012 feat: Add sortColumn to title render
  components/table/Table.tsx
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/table/interface.tsx
Labels: PR: reviewed-approved

#19014 Rename algin.md to align.md
  components/input/demo/align.md
Labels: PR: unreviewed

#19025 Input.tsx的otherProps为什么不去掉size
  components/input/Input.tsx
Labels: PR: unreviewed

#19029 fix: ssr should not render string at first
  components/avatar/__tests__/__snapshots__/demo.test.js.snap
  components/avatar/index.tsx
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
Labels: PR: reviewed-approved, bug

#19031 test: ✅ Add more test cases for DatePicker
  components/date-picker/WeekPicker.tsx
  components/date-picker/__tests__/WeekPicker.test.js
  components/date-picker/__tests__/invalid.test.js
Labels: PR: reviewed-changes-requested, test

#19041 test: add test case for Collapse
  components/collapse/__tests__/index.test.js
Labels: PR: reviewed-changes-requested, test

#19042 fix: detect antd button by children.type.[staticProperty] instead of the same class
  components/input/Search.tsx
Labels: PR: unreviewed, bug

#19040 feat: TreeSelect use virtual scroll
  components/auto-complete/__tests__/__snapshots__/demo.test.js.snap
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/empty/__tests__/__snapshots__/demo.test.js.snap
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/select/index.tsx
  components/select/style/index.less
  components/select/utils/iconUtil.tsx
  components/tree-select/__tests__/__snapshots__/demo.test.js.snap
  components/tree-select/__tests__/__snapshots__/index.test.js.snap
  components/tree-select/__tests__/index.test.js
  components/tree-select/index.tsx
  components/tree-select/interface.tsx
  components/tree-select/style/index.less
  components/tree-select/style/index.tsx
  components/tree/DirectoryTree.tsx
  components/tree/Tree.tsx
  components/tree/__tests__/util.test.js
  components/tree/style/index.less
  components/tree/style/mixin.less
  components/tree/utils/dictUtil.ts
  components/tree/utils/iconUtil.tsx
  package.json
  typings/custom-typings.d.ts
Labels: PR: unreviewed, enhancement

#19044 fix: IE11 syntax error
  site/bisheng.config.js
Labels: PR: reviewed-changes-requested, bug

#19045 Fix/detect antd button by static
  components/input/Search.tsx
Labels: PR: unreviewed

#19052 test: ✅ increase upload test cov
  components/upload/Upload.tsx
  components/upload/__tests__/__snapshots__/uploadlist.test.js.snap
  components/upload/__tests__/dragger.test.js
  components/upload/__tests__/upload.test.js
  components/upload/__tests__/uploadlist.test.js
  components/upload/utils.tsx
Labels: PR: unreviewed, test

#19057 chore: replace resizeObserver with `rc-resize-observer`
  components/_util/__tests__/util.test.js
  components/_util/resizeObserver.tsx
  components/affix/__tests__/Affix.test.js
  components/affix/index.tsx
  components/input/TextArea.tsx
  components/input/__tests__/__snapshots__/index.test.js.snap
  components/typography/Base.tsx
  package.json
Labels: PR: unreviewed, chore

#19056 docs: 3.23.5 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed, documentation

#19059 docs: Update demo
  components/select/demo/custom-dropdown-menu.md
Labels: PR: reviewed-approved, documentation

#19062 master to feature
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/_util/__tests__/util.test.js
  components/_util/resizeObserver.tsx
  components/affix/__tests__/Affix.test.js
  components/affix/index.tsx
  components/input/TextArea.tsx
  components/input/__tests__/__snapshots__/index.test.js.snap
  components/typography/Base.tsx
  components/upload/Upload.tsx
  components/upload/__tests__/__snapshots__/uploadlist.test.js.snap
  components/upload/__tests__/dragger.test.js
  components/upload/__tests__/upload.test.js
  components/upload/__tests__/uploadlist.test.js
  components/upload/utils.tsx
  package.json
Labels: PR: reviewed-changes-requested

#19066 fix: Typography function component use Ref console log warning
  components/typography/Typography.tsx
Labels: PR: unreviewed, bug
