Repository ant-design/ant-design, pull requests merged in 2019-10, with the labels that each got.

#19074 fix: Typography warning for `ref` error
  components/_util/ref.ts
  components/typography/Base.tsx
  components/typography/Typography.tsx
  components/typography/__tests__/index.test.js
Labels: PR: unreviewed, bug

#19075 tweak: site title unescape
  site/theme/static/template.html
Labels: PR: unreviewed, tweak

#19102 docs: changelog for 3.23.6
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed, documentation

#19103 chore: merge master to feature
  .eslintrc.js
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/_util/ref.ts
  components/button/__tests__/index.test.js
  components/collapse/__tests__/__snapshots__/demo.test.js.snap
  components/collapse/demo/extra.md
  components/drawer/demo/user-profile.md
  components/form/__tests__/message.test.js
  components/result/__tests__/__snapshots__/demo.test.js.snap
  components/result/demo/error.md
  components/select/demo/option-label-prop.md
  components/table/__tests__/Table.test.js
  components/typography/Base.tsx
  components/typography/Typography.tsx
  components/typography/__tests__/__snapshots__/demo.test.js.snap
  components/typography/__tests__/index.test.js
  components/typography/demo/basic.md
  components/typography/demo/ellipsis-debug.md
  components/typography/demo/paragraph-debug.md
  components/upload/__tests__/__snapshots__/uploadlist.test.js.snap
  package.json
  site/theme/static/template.html
  site/theme/template/Layout/Footer.jsx
Labels: chore

#19079 feat(Layout): add prop zeroWidthTriggerStyle
  components/layout/Sider.tsx
  components/layout/__tests__/index.test.js
  components/layout/index.en-US.md
  components/layout/index.zh-CN.md
Labels: PR: reviewed-approved, enhancement

#19109 feat: Add `drawerStyle` and `headerStyle`
  components/drawer/__tests__/Drawer.test.js
  components/drawer/__tests__/__snapshots__/Drawer.test.js.snap
  components/drawer/index.en-US.md
  components/drawer/index.tsx
  components/drawer/index.zh-CN.md
  package.json
Labels: PR: reviewed-changes-requested, enhancement

#19113 fix: description demo update
  components/descriptions/__tests__/__snapshots__/demo.test.js.snap
  components/descriptions/demo/vertical-border.md
Labels: PR: unreviewed, bug

#19115 fix: ConfigProvider miss in tree shaking
  components/config-provider/context.ts
  components/config-provider/index.tsx
Labels: PR: reviewed-changes-requested, bug

#19114 fix: 4.0 select hover less vars
  components/select/style/index.less
Labels: PR: unreviewed, bug

#19121 docs: Clear up confusing language about dataSource keys
  components/table/index.en-US.md
Labels: PR: unreviewed, documentation

#19120 improvement: improve Slider component handle style
  components/slider/style/index.less
Labels: PR: reviewed-approved, improvement

#19133 docs: optimize the description of key in the Table component
  components/table/index.zh-CN.md
Labels: PR: unreviewed, documentation

#19140 Update documentation (en-US) for Input.Search: Clicking clear-icon fires onSearch
  components/input/index.en-US.md
Labels: PR: unreviewed, Search

#19135 Collapse ie11 view fix
  components/collapse/style/index.less
Labels: PR: unreviewed

#19144 docs: document drawer default height
  components/drawer/index.en-US.md
Labels: PR: unreviewed, documentation

#19142 Update theme.md
  components/menu/demo/theme.md
Labels: PR: unreviewed

#19161 docs: link related issue of Form initialValue option
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: PR: unreviewed, documentation

#19160 Fix: keep className given to expandIcon in Collapse component
  components/collapse/Collapse.tsx
  components/collapse/__tests__/index.test.js
Labels: Fix, PR: unreviewed

#19163 feat: Select & TreeSelect support auto realign & animate
  package.json
Labels: PR: unreviewed, enhancement

#19175 chore: docs cases Umi UI image compress
  docs/spec/cases.en-US.md
  docs/spec/cases.zh-CN.md
Labels: PR: unreviewed, chore

#19177 fix: replace autosize with autoSize
  components/input/TextArea.tsx
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/__tests__/index.test.js
  components/input/demo/autosize-textarea.md
  components/input/demo/textarea-resize.md
  components/input/index.en-US.md
  components/input/index.zh-CN.md
  components/typography/Editable.tsx
Labels: PR: reviewed-changes-requested, bug

#19202 chore: master merge feature
  components/collapse/Collapse.tsx
  components/collapse/__tests__/index.test.js
  components/collapse/style/index.less
  components/config-provider/context.ts
  components/config-provider/index.tsx
  components/descriptions/__tests__/__snapshots__/demo.test.js.snap
  components/descriptions/demo/vertical-border.md
  components/drawer/index.en-US.md
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/input/TextArea.tsx
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/__tests__/index.test.js
  components/input/demo/autosize-textarea.md
  components/input/demo/textarea-resize.md
  components/input/index.en-US.md
  components/input/index.zh-CN.md
  components/menu/__tests__/__snapshots__/demo.test.js.snap
  components/menu/demo/theme.md
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/tree/DirectoryTree.tsx
  components/tree/__tests__/__snapshots__/directory.test.js.snap
  components/tree/__tests__/directory.test.js
  components/tree/util.ts
  components/typography/Editable.tsx
  docs/spec/cases.en-US.md
  docs/spec/cases.zh-CN.md
  package.json
  site/theme/en-US.js
  site/theme/static/responsive.less
  site/theme/template/Content/MainContent.jsx
  site/theme/template/Layout/Footer.jsx
  site/theme/template/Layout/index.jsx
Labels: PR: reviewed-changes-requested, chore

#15478 refactor: add @form-item-label-colon-margin-{right,left}
  components/form/style/index.less
  components/style/themes/default.less
Labels: Inactive, PR: unreviewed

#19205 refactor: Use CSSMotion
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/layout/__tests__/__snapshots__/demo.test.js.snap
  components/menu/__tests__/__snapshots__/demo.test.js.snap
  components/menu/__tests__/index.test.js
  components/menu/index.tsx
  components/table/filterDropdown.tsx
  components/table/interface.tsx
  package.json
  typings/custom-typings.d.ts
Labels: PR: reviewed-approved, refactor

#19208 fix: tuple for column fixed prop types
  components/table/interface.tsx
Labels: PR: unreviewed, bug

#19209 docs: Add promote link in home page
  docs/react/recommendation.en-US.md
  docs/react/recommendation.zh-CN.md
  site/theme/en-US.js
  site/theme/static/home.less
  site/theme/static/responsive.less
  site/theme/template/Home/Banner.jsx
  site/theme/zh-CN.js
Labels: PR: unreviewed, documentation

#19100 feat: Pageheader new style and props
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/config-provider/__tests__/components.test.js
  components/config-provider/context.ts
  components/config-provider/index.en-US.md
  components/config-provider/index.tsx
  components/config-provider/index.zh-CN.md
  components/drawer/index.tsx
  components/page-header/__tests__/__snapshots__/demo.test.js.snap
  components/page-header/__tests__/__snapshots__/index.test.js.snap
  components/page-header/demo/actions.md
  components/page-header/demo/basic.md
  components/page-header/demo/breadcrumb.md
  components/page-header/demo/content.md
  components/page-header/demo/ghost.md
  components/page-header/demo/responsive.md
  components/page-header/index.en-US.md
  components/page-header/index.tsx
  components/page-header/index.zh-CN.md
  components/page-header/style/index.less
Labels: PR: reviewed-approved, enhancement

#19216 ci: fix node version of github action
  .github/workflows/nodejs.yml
  .github/workflows/test.yml
Labels: PR: unreviewed, ci

#18746 add: Typography mixins. add: Created typography variables (margin, fo…
  components/style/mixins/index.less
  components/style/mixins/typography.less
  components/style/themes/default.less
  components/typography/style/index.less
Labels: PR: unreviewed

#19054 Docs: upload with aliyun oss
  components/upload/__tests__/__snapshots__/demo.test.js.snap
  components/upload/demo/upload-with-aliyun-oss.md
Labels: Docs, PR: unreviewed

#19230 fix(snapshot): update snapshot
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/grid/__tests__/__snapshots__/demo.test.js.snap
  components/input-number/__tests__/__snapshots__/demo.test.js.snap
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/layout/__tests__/__snapshots__/demo.test.js.snap
  components/menu/__tests__/__snapshots__/demo.test.js.snap
  components/menu/__tests__/__snapshots__/index.test.js.snap
  components/slider/__tests__/__snapshots__/demo.test.js.snap
  components/table/__tests__/__snapshots__/Table.rowSelection.test.js.snap
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/__tests__/__snapshots__/empty.test.js.snap
  components/typography/__tests__/__snapshots__/demo.test.js.snap
Labels: PR: unreviewed, bug

#19227 fix: fix cascader placeholder internationalization
  components/cascader/__tests__/__snapshots__/index.test.js.snap
  components/cascader/__tests__/index.test.js
  components/cascader/index.tsx
Labels: PR: unreviewed, bug

#19236 Add 3.24.0 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed, needs-more-info

#19245 chore: Update demo & snapshot
  components/dropdown/__tests__/__snapshots__/demo.test.js.snap
  components/dropdown/demo/menu-full.md
Labels: PR: unreviewed, chore

#19238 chore: Use new lifecycle of `rc-menu`
  package.json
Labels: PR: reviewed-approved, chore

#19251 fix: Add missing typescript define
  components/table/Table.tsx
Labels: PR: unreviewed, bug

#19254 refactor: improve typescript module declare
  package.json
  tsconfig.json
  tslint.json
  typings/custom-typings.d.ts
Labels: PR: unreviewed, refactor

#19257 docs: fix page header API
  components/config-provider/index.zh-CN.md
  components/page-header/index.en-US.md
Labels: PR: unreviewed, documentation

#19262 fix: should work in old version react
  .circleci/config.yml
  components/table/Table.tsx
  tests/setup.js
Labels: PR: unreviewed, bug

#19270 docs: Update 3.24.1 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed, documentation

#19277 Fix typos in en-US contributing guide
  docs/react/contributing.en-US.md
Labels: PR: unreviewed

#19278 chore: Improve types for customRequest prop on Upload component
  components/upload/interface.tsx
Labels: PR: unreviewed, chore

#19279 chore: Remove React function polyfill
  components/table/__tests__/demo.test.js
  tests/__mocks__/react.js
Labels: PR: unreviewed, chore

#19282 chore: fix compile fail when use cnpm installed
  package.json
  typings/custom-typings.d.ts
Labels: PR: reviewed-changes-requested, chore

#19290 docs: corrected the typographical error of word 'case' to 'care'
  docs/react/use-with-create-react-app.en-US.md
Labels: PR: unreviewed, documentation

#19286 fix: Select Mode Type
  components/select/index.tsx
Labels: PR: unreviewed, bug

#19284 fix: Table scroll.x max-content not working in Chrome
  components/table/__tests__/__snapshots__/Table.rowSelection.test.js.snap
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/__tests__/__snapshots__/empty.test.js.snap
  components/table/demo/grouping-columns.md
  package.json
Labels: PR: unreviewed, bug

#19247 test: official site checker before publish
  .jest.site.js
  package.json
  scripts/check-site.js
Labels: PR: unreviewed, test

#19300 fix(#18280): add type [Moment.moment, undefined] to RangePickerValue
  components/date-picker/interface.tsx
Labels: PR: unreviewed, bug

#19302 test: add test case for ref test
  components/table/__tests__/Table.filter.test.js
Labels: PR: unreviewed, test

#19295 docs: release 3.24.2
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed, documentation

#19311 add commit lint action description
  docs/react/contributing.en-US.md
  docs/react/contributing.zh-CN.md
Labels: PR: unreviewed

#19312 fix: small table border radius issue
  components/table/style/size.less
Labels: PR: unreviewed, bug

#19313 fix: Menu in Dropdown submenu selected style
  components/dropdown/style/index.less
Labels: PR: unreviewed, bug

#19317 fix: Tree shaking should works on withContext
  components/config-provider/context.ts
  components/config-provider/context.tsx
  components/config-provider/index.tsx
  components/drawer/index.tsx
  components/statistic/Statistic.tsx
  components/typography/Base.tsx
Labels: PR: reviewed-changes-requested, bug

#19321 chore: sync master to feature
  components/config-provider/context.ts
  components/config-provider/context.tsx
  components/config-provider/index.tsx
  components/drawer/index.tsx
  components/dropdown/style/index.less
  components/grid/__tests__/index.test.js
  components/grid/row.tsx
  components/statistic/Statistic.tsx
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/style/size.less
  components/typography/Base.tsx
  docs/react/contributing.en-US.md
  docs/react/contributing.zh-CN.md
  site/theme/static/home.less
  site/theme/template/Home/Banner.jsx
Labels: PR: reviewed-changes-requested, chore

#19333 Improve typing of `UploadFile` interface
  components/upload/interface.tsx
Labels: PR: unreviewed

#19330 fix(#11119): fix Transfer listStyle support function callback
  components/transfer/__tests__/__snapshots__/index.test.js.snap
  components/transfer/__tests__/index.test.js
  components/transfer/index.en-US.md
  components/transfer/index.tsx
  components/transfer/index.zh-CN.md
Labels: PR: reviewed-changes-requested, bug

#19342 fix: small table bottom border radius issue
  components/table/style/size.less
Labels: PR: unreviewed, bug

#19343 fix: TableProps ts definition
  components/table/Table.tsx
  components/table/interface.tsx
Labels: PR: unreviewed, bug

#19347 chore: Temporary lock eslint parser version
  package.json
Labels: PR: unreviewed, chore

#19361 feat: Add tag downloadFile in all languages
  components/locale/ar_EG.tsx
  components/locale/bg_BG.tsx
  components/locale/ca_ES.tsx
  components/locale/cs_CZ.tsx
  components/locale/da_DK.tsx
  components/locale/de_DE.tsx
  components/locale/el_GR.tsx
  components/locale/en_GB.tsx
  components/locale/es_ES.tsx
  components/locale/et_EE.tsx
  components/locale/fa_IR.tsx
  components/locale/fi_FI.tsx
  components/locale/fr_BE.tsx
  components/locale/fr_FR.tsx
  components/locale/he_IL.tsx
  components/locale/hi_IN.tsx
  components/locale/hr_HR.tsx
  components/locale/hu_HU.tsx
  components/locale/hy_AM.tsx
  components/locale/id_ID.tsx
  components/locale/is_IS.tsx
  components/locale/it_IT.tsx
  components/locale/ja_JP.tsx
  components/locale/kn_IN.tsx
  components/locale/ko_KR.tsx
  components/locale/ku_IQ.tsx
  components/locale/lv_LV.tsx
  components/locale/mn_MN.tsx
  components/locale/ms_MY.tsx
  components/locale/nb_NO.tsx
  components/locale/ne_NP.tsx
  components/locale/nl_BE.tsx
  components/locale/nl_NL.tsx
  components/locale/pl_PL.tsx
  components/locale/pt_BR.tsx
  components/locale/pt_PT.tsx
  components/locale/ro_RO.tsx
  components/locale/ru_RU.tsx
  components/locale/sk_SK.tsx
  components/locale/sl_SI.tsx
  components/locale/sr_RS.tsx
  components/locale/sv_SE.tsx
  components/locale/ta_IN.tsx
  components/locale/th_TH.tsx
  components/locale/tr_TR.tsx
  components/locale/uk_UA.tsx
  components/locale/vi_VN.tsx
  components/locale/zh_TW.tsx
Labels: PR: reviewed-approved, enhancement

#19366 chore: Merge master into feature
  CHANGELOG.zh-CN.md
  components/input/Search.tsx
  components/input/__tests__/Search.test.js
  components/input/__tests__/__snapshots__/Search.test.js.snap
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/__tests__/__snapshots__/index.test.js.snap
  components/input/demo/align.md
  components/input/demo/search-input-loading.md
  components/table/Table.tsx
  components/table/interface.tsx
  components/table/style/size.less
  components/upload/interface.tsx
  package.json
  scripts/check-site.js
  tests/setup.js
Labels: PR: reviewed-approved, chore

#19368 Feature avatar icon
  components/avatar/__tests__/__snapshots__/demo.test.js.snap
  components/avatar/demo/type.md
  components/avatar/index.en-US.md
  components/avatar/index.tsx
  components/avatar/index.zh-CN.md
Labels: PR: reviewed-approved

#19240 docs: practical projects using Umi UI
  docs/react/practical-projects.en-US.md
  docs/react/practical-projects.zh-CN.md
Labels: PR: unreviewed, documentation

#19383 Fix: Input addon with Select style
  components/input/style/mixin.less
Labels: Fix, PR: unreviewed

#19385 style: add @modal-header-color variable
  components/modal/style/modal.less
  components/style/themes/default.less
Labels: PR: unreviewed, style

#19410 add CODEOWNERS file
  CODEOWNERS
Labels: PR: unreviewed

#19416 General components doc tweaks
  components/button/index.en-US.md
  components/icon/index.en-US.md
  components/typography/index.en-US.md
Labels: PR: unreviewed

#19411 docs:Use tensorflow.js to predict icon
  site/theme/en-US.js
  site/theme/template/IconDisplay/IconPicSearcher.tsx
  site/theme/zh-CN.js
Labels: PR: unreviewed

#19403 fix: disabled cursor
  components/checkbox/style/mixin.less
Labels: PR: reviewed-approved, bug

#19399 feat: Preset status color into Tag
  components/_util/colors.ts
  components/tag/__tests__/__snapshots__/demo.test.js.snap
  components/tag/demo/status.md
  components/tag/index.tsx
  components/tag/style/index.less
Labels: PR: reviewed-approved, enhancement

#19419 fix: Modal icon position while no title
  components/modal/__tests__/confirm.test.js
  components/modal/confirm.tsx
  components/modal/demo/info.md
Labels: PR: unreviewed, bug

#19434 fix: lint
  components/transfer/__tests__/index.test.js
Labels: PR: reviewed-changes-requested, bug

#19414 feat: Add some code owner
  CODEOWNERS
Labels: PR: unreviewed, enhancement

#19404 fix: sort order of columns inside render
  components/table/Table.tsx
  components/table/__tests__/Table.sorter.test.js
Labels: PR: reviewed-changes-requested, bug

#19441 refactoring: refactor search code
  components/breadcrumb/Breadcrumb.tsx
  components/tooltip/index.tsx
Labels: PR: unreviewed, Refactoring

#19436 docs: changelog for 3.24.3
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed, documentation

#19446 Fix/legacy icon usage
  components/button/__tests__/__snapshots__/index.test.js.snap
  components/button/__tests__/index.test.js
  components/progress/__tests__/__snapshots__/demo.test.js.snap
  components/progress/demo/circle-dynamic.md
  components/progress/demo/dynamic.md
Labels: PR: reviewed-changes-requested

#19447 Navigation components doc tweaks
  components/affix/index.en-US.md
  components/dropdown/index.en-US.md
  components/menu/index.en-US.md
  components/page-header/index.en-US.md
  components/pagination/index.en-US.md
  components/steps/index.en-US.md
Labels: PR: unreviewed

#19453 fix: Icon Button align issue
  components/button/style/mixin.less
Labels: PR: unreviewed, bug

#19452 fix: Checkbox not aligned center in some cases
  components/checkbox/style/mixin.less
Labels: PR: unreviewed, bug

#19455 refactor: alert code for better semantic
  components/alert/index.tsx
  components/alert/style/index.less
Labels: PR: unreviewed, refactor

#19456 chore: Merge master into feature
  components/affix/index.en-US.md
  components/alert/index.tsx
  components/alert/style/index.less
  components/button/style/mixin.less
  components/checkbox/style/mixin.less
  components/dropdown/index.en-US.md
  components/menu/index.en-US.md
  components/page-header/index.en-US.md
  components/pagination/index.en-US.md
  components/steps/index.en-US.md
Labels: PR: reviewed-approved, chore

#19348 fix: modify textarea resize demo defaultValue to english
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/demo/textarea-resize.md
Labels: PR: unreviewed, bug

#19448 docs: Responsive fixes for examples pages
  components/cascader/index.en-US.md
  components/cascader/index.zh-CN.md
  components/slider/__tests__/__snapshots__/demo.test.js.snap
  components/slider/demo/vertical.md
  components/tree-select/__tests__/__snapshots__/demo.test.js.snap
  components/tree-select/demo/async.md
  components/tree-select/demo/basic.md
  components/tree-select/demo/checkable.md
  components/tree-select/demo/multiple.md
  components/tree-select/demo/suffix.md
  components/tree-select/demo/treeData.md
Labels: PR: unreviewed, documentation

#19141 Fix defaultPickerValue in WeekPicker
  components/date-picker/WeekPicker.tsx
Labels: PR: unreviewed

#19474 fix: DatePicker throw onEsc error
  components/date-picker/wrapPicker.tsx
Labels: PR: unreviewed, bug

#19476 Update index.less
  components/menu/style/index.less
Labels: PR: unreviewed

#19496 fix(Upload): add interface field (#19485)
  components/upload/interface.tsx
Labels: PR: unreviewed

#19510 fix: Remove the unnecessary padding-right when use allowClear on Select
  components/select/style/index.less
Labels: PR: unreviewed
