Repository ant-design/ant-design, pull requests merged in 2019-11, with the labels that each got.

#19310 feat: Add allowClear to TextArea
  components/input/ClearableLabeledInput.tsx
  components/input/Input.tsx
  components/input/ResizableTextArea.tsx
  components/input/TextArea.tsx
  components/input/__tests__/__snapshots__/Password.test.js.snap
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/__tests__/__snapshots__/index.test.js.snap
  components/input/__tests__/index.test.js
  components/input/demo/allowClear.md
  components/input/index.en-US.md
  components/input/index.zh-CN.md
  components/input/style/index.less
  components/input/style/mixin.less
  components/transfer/__tests__/__snapshots__/search.test.js.snap
Labels: PR: reviewed-approved, enhancement

#19465 fix: table does not automatically scroll to the top when change page size
  components/table/Table.tsx
  components/table/__tests__/Table.pagination.test.js
Labels: PR: reviewed-approved, bug

#19533 feat: upload method canbe customized
  components/upload/index.en-US.md
  components/upload/index.zh-CN.md
  components/upload/interface.tsx
  package.json
Labels: PR: reviewed-changes-requested, enhancement

#19539 feat: Gets the XMLHttpRequest Object in Onchange function
  components/upload/Upload.tsx
  components/upload/index.en-US.md
  components/upload/interface.tsx
Labels: PR: reviewed-approved, enhancement

#19546 feat: input,select less vars
  components/input-number/style/index.less
  components/select/style/index.less
  components/style/themes/default.less
Labels: PR: unreviewed, enhancement

#19543 fix: FormLabelAlign item types tuple
  components/form/FormItem.tsx
Labels: PR: unreviewed, bug

#19547 chore: Delete duplicate variables
  components/style/themes/default.less
Labels: PR: unreviewed, chore

#19549 docs: 3.25.0 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/pagination/__tests__/__snapshots__/demo.test.js.snap
  package.json
Labels: PR: unreviewed, documentation

#19553 chore: use menu icon less variable
  components/menu/style/index.less
Labels: PR: unreviewed, chore

#19550 fix(Form): remove labelAlign PropTypes def
  components/form/FormItem.tsx
Labels: PR: unreviewed, bug

#19558 fix: Table inifinite loop and defaultSortOrder
  components/table/Table.tsx
  components/table/__tests__/Table.sorter.test.js
  components/table/__tests__/__snapshots__/Table.sorter.test.js.snap
Labels: PR: reviewed-changes-requested, bug

#19559 fix: Table border missing in fixed columns
  components/table/style/index.less
Labels: PR: unreviewed, bug

#19557 chore: 🆙 upgrade some devDependencies
  .eslintrc.js
  components/breadcrumb/__tests__/router.test.js
  components/typography/__tests__/index.test.js
  package.json
  tests/shared/focusTest.js
  tests/shared/mountTest.js
Labels: PR: unreviewed, chore

#19568 fix: listStyle Typescript def
  components/transfer/index.tsx
Labels: PR: unreviewed, bug

#19572 fix: extraCommonProps not work properly
  components/icon/IconFont.tsx
  components/icon/__tests__/__snapshots__/index.test.js.snap
  components/icon/__tests__/index.test.js
Labels: PR: unreviewed, bug

#19578 fix: Menu.ItemGroup styles inside Dropdown
  components/dropdown/demo/menu-full.md
  components/dropdown/style/index.less
  site/theme/static/demo.less
Labels: PR: unreviewed, bug

#19586 chore: Merge master into feature
  .eslintrc.js
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/breadcrumb/__tests__/router.test.js
  components/cascader/index.en-US.md
  components/cascader/index.zh-CN.md
  components/date-picker/WeekPicker.tsx
  components/date-picker/wrapPicker.tsx
  components/dropdown/demo/menu-full.md
  components/dropdown/style/index.less
  components/form/FormItem.tsx
  components/icon/IconFont.tsx
  components/icon/__tests__/__snapshots__/index.test.js.snap
  components/icon/__tests__/index.test.js
  components/input-number/style/index.less
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/demo/textarea-resize.md
  components/layout/index.en-US.md
  components/layout/index.zh-CN.md
  components/menu/style/index.less
  components/pagination/__tests__/__snapshots__/demo.test.js.snap
  components/select/style/index.less
  components/slider/__tests__/__snapshots__/demo.test.js.snap
  components/slider/demo/vertical.md
  components/style/themes/default.less
  components/table/Table.tsx
  components/table/__tests__/Table.pagination.test.js
  components/table/__tests__/Table.sorter.test.js
  components/table/__tests__/__snapshots__/Table.sorter.test.js.snap
  components/table/demo/fixed-columns-header.md
  components/table/demo/fixed-columns.md
  components/table/demo/fixed-header.md
  components/table/style/index.less
  components/transfer/index.tsx
  components/tree-select/__tests__/__snapshots__/demo.test.js.snap
  components/tree-select/demo/async.md
  components/tree-select/demo/basic.md
  components/tree-select/demo/checkable.md
  components/tree-select/demo/multiple.md
  components/tree-select/demo/suffix.md
  components/tree-select/demo/treeData.md
  components/typography/__tests__/index.test.js
  components/upload/interface.tsx
  package.json
  site/theme/static/demo.less
  tests/shared/focusTest.js
  tests/shared/mountTest.js
Labels: PR: unreviewed, chore

#19506 fix: Drawer content overflow when placement is top or bottom
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/drawer/__tests__/__snapshots__/Drawer.test.js.snap
  components/drawer/__tests__/__snapshots__/DrawerEvent.test.js.snap
  components/drawer/__tests__/__snapshots__/demo.test.js.snap
  components/drawer/index.tsx
  components/drawer/style/drawer.less
Labels: PR: unreviewed

#19498 refactor: upgrade rc-dropdown
  components/breadcrumb/Breadcrumb.tsx
  components/breadcrumb/__tests__/__snapshots__/router.test.js.snap
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/dropdown/dropdown.tsx
  components/table/__tests__/__snapshots__/Table.filter.test.js.snap
  components/table/__tests__/__snapshots__/Table.rowSelection.test.js.snap
  package.json
  typings/custom-typings.d.ts
Labels: PR: unreviewed

#19599 chore(Form.Item): form item passing anyother attrs
  components/form/FormItem.tsx
  components/form/__tests__/__snapshots__/index.test.js.snap
  components/form/__tests__/index.test.js
Labels: PR: reviewed-changes-requested, chore

#19606 docs: 📝 fix doc of labelAlign in Form.Item
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: PR: unreviewed, documentation

#19421 fix: date range picker type interface
  components/date-picker/RangePicker.tsx
  components/date-picker/interface.tsx
  components/date-picker/utils.ts
Labels: PR: unreviewed, bug

#19610 Unify type declaration.
  components/drawer/index.zh-CN.md
Labels: PR: unreviewed

#19233 fix: Scrollbar on Modal Confirm
  components/modal/confirm.tsx
Labels: PR: reviewed-approved, bug

#19635 fix: Dropdown icon missing margin right
  components/dropdown/style/index.less
Labels: PR: unreviewed, bug

#19618 feat: notification component support closeIcon props
  components/notification/__tests__/index.test.js
  components/notification/index.en-US.md
  components/notification/index.tsx
  components/notification/index.zh-CN.md
Labels: PR: reviewed-approved, enhancement

#19651 fix: translate Typography for pt_BR
  components/locale/pt_BR.tsx
Labels: PR: reviewed-approved, bug

#19657 docs: Add the changelog of 3.25.1
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: reviewed-approved, documentation

#19665 docs: Fix typo in image
  docs/spec/values.en-US.md
Labels: PR: unreviewed, documentation

#19669 chore: react-helmet-async title ssr
  package.json
  scripts/check-site.js
  site/theme/template/Layout/index.jsx
Labels: PR: unreviewed, chore

#19689 fix: fix upload error style
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/upload/UploadList.tsx
  components/upload/__tests__/__snapshots__/demo.test.js.snap
  components/upload/__tests__/__snapshots__/uploadlist.test.js.snap
  components/upload/demo/picture-card.md
  components/upload/demo/picture-style.md
Labels: PR: unreviewed, bug

#19700 docs: 改进 skeleton 首次加载数据使用场景描述
  components/skeleton/index.zh-CN.md
Labels: PR: unreviewed, documentation

#19701 fix: Table > FilterDropdownProps definition
  components/table/interface.tsx
Labels: PR: unreviewed, bug

#19693 fix: style of search padding in transfer
  components/transfer/style/index.less
Labels: PR: reviewed-approved, bug

#19713 fix: type interface SliderProps
  components/slider/index.tsx
Labels: PR: unreviewed, bug

#19714 feat: code add stackblitz
  package.json
  site/theme/en-US.js
  site/theme/static/demo.less
  site/theme/template/Content/Demo.jsx
  site/theme/zh-CN.js
Labels: PR: unreviewed, enhancement

#19722 fix: add missing null option type
  components/table/interface.tsx
Labels: PR: unreviewed, bug

#19730 fix: update Select type interface
  components/select/index.tsx
Labels: PR: reviewed-approved, bug

#19733 Revert "fix: update Select type interface"
  components/select/index.tsx
Labels: PR: unreviewed, bug

#19698 refactor: Upgrade rc-time-picker for new rc-trigger
  components/time-picker/index.tsx
  components/time-picker/style/index.less
  package.json
Labels: PR: unreviewed, refactor

#19751 fix: drawer footer fixed
  components/drawer/demo/form-in-drawer.md
  components/drawer/style/drawer.less
Labels: PR: unreviewed, bug

#19757 fix: Documentation typo for Menu API
  components/menu/index.en-US.md
  components/menu/index.zh-CN.md
Labels: PR: unreviewed, bug

#19721 test: introduce codesandbox ci
  .codesandbox/ci.json
  package.json
  tsconfig.json
  webpack.config.js
Labels: PR: unreviewed, test

#19760 docs: 🎬 improve notification placement demo
  components/notification/__tests__/__snapshots__/demo.test.js.snap
  components/notification/demo/placement.md
Labels: PR: unreviewed, documentation

#18925 feat(table): Add defaultFilteredValues to table columns
  components/table/Table.tsx
  components/table/__tests__/Table.filter.test.js
  components/table/demo/head.md
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/table/interface.tsx
Labels: PR: reviewed-approved, enhancement

#19768 docs: 3.25.2 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed, documentation

#19770 chore: Export some useful define
  components/table/Table.tsx
  components/table/interface.tsx
  package.json
Labels: PR: unreviewed, chore

#19778 chore: add packtracker back
  package.json
  webpack.config.js
Labels: PR: unreviewed, chore

#19783 fix: upload-picture-card-style-error
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/upload/UploadList.tsx
  components/upload/__tests__/__snapshots__/demo.test.js.snap
  components/upload/__tests__/__snapshots__/uploadlist.test.js.snap
  components/upload/style/index.less
Labels: PR: unreviewed, bug

#19789 Update link to latest ColumnProps
  components/table/index.en-US.md
  components/table/index.zh-CN.md
Labels: PR: unreviewed

#19780 fix: typescript define
  components/table/Table.tsx
  components/table/interface.tsx
Labels: PR: unreviewed, bug

#19786 ci: enable cache and multithreading for GA
  .github/workflows/test.yml
Labels: PR: unreviewed, ci

#19719 tweak: 4.0 less token
  components/calendar/style/index.less
  components/card/style/index.less
  components/cascader/style/index.less
  components/checkbox/style/mixin.less
  components/date-picker/style/Calendar.less
  components/date-picker/style/DecadePanel.less
  components/date-picker/style/MonthPanel.less
  components/date-picker/style/YearPanel.less
  components/mentions/style/index.less
  components/select/style/index.less
  components/select/style/multiple.less
  components/slider/style/index.less
  components/style/themes/default.less
  components/table/style/index.less
  components/tabs/style/card-style.less
  components/transfer/ListItem.tsx
  components/transfer/__tests__/__snapshots__/index.test.js.snap
  components/transfer/__tests__/__snapshots__/list.test.js.snap
  components/transfer/style/index.less
  components/tree/style/index.less
  site/theme/static/colors.less
  site/theme/static/demo.less
  site/theme/static/highlight.less
  site/theme/static/markdown.less
Labels: PR: reviewed-approved, tweak

#19810 fix: menu link color inside badge
  components/menu/style/index.less
Labels: PR: unreviewed, bug

#16635 feat: Col support `flex` prop
  components/auto-complete/__tests__/__snapshots__/demo.test.js.snap
  components/calendar/__tests__/__snapshots__/demo.test.js.snap
  components/calendar/demo/customize-header.md
  components/comment/__tests__/__snapshots__/demo.test.js.snap
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/form/FormItem.tsx
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/__tests__/__snapshots__/index.test.js.snap
  components/grid/__tests__/__snapshots__/demo.test.js.snap
  components/grid/__tests__/index.test.js
  components/grid/col.tsx
  components/grid/demo/basic.md
  components/grid/demo/flex-align.md
  components/grid/demo/flex-order.md
  components/grid/demo/flex-stretch.md
  components/grid/demo/flex.md
  components/grid/demo/playground.md
  components/grid/demo/responsive-more.md
  components/grid/demo/responsive.md
  components/grid/index.en-US.md
  components/grid/index.zh-CN.md
  components/grid/row.tsx
  components/grid/style/index.less
  components/grid/style/mixin.less
  components/mention/__tests__/__snapshots__/demo.test.js.snap
  components/mentions/__tests__/__snapshots__/demo.test.js.snap
  components/page-header/__tests__/__snapshots__/demo.test.js.snap
  components/page-header/demo/actions.md
  components/page-header/demo/content.md
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/upload/__tests__/__snapshots__/demo.test.js.snap
  site/theme/static/markdown.less
Labels: 4.0, Inactive, PR: reviewed-approved, PR: unreviewed, enhancement

#19816 chore: add @types/jest dependencies
  package.json
Labels: PR: unreviewed, chore

#19820 docs: Removed version column in 4.0
  components/cascader/index.en-US.md
  components/cascader/index.zh-CN.md
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
Labels: PR: unreviewed, documentation

#19823 docs: Removed version column in 4.0
  components/auto-complete/index.en-US.md
  components/auto-complete/index.zh-CN.md
  components/checkbox/index.en-US.md
  components/checkbox/index.zh-CN.md
Labels: PR: unreviewed, documentation

#19821 docs: Removed version column in 4.0
  components/select/index.en-US.md
  components/select/index.zh-CN.md
  components/slider/index.en-US.md
  components/slider/index.zh-CN.md
  components/time-picker/index.en-US.md
  components/time-picker/index.zh-CN.md
  components/transfer/index.en-US.md
  components/transfer/index.zh-CN.md
  components/tree-select/index.en-US.md
  components/tree-select/index.zh-CN.md
  components/upload/index.en-US.md
  components/upload/index.zh-CN.md
Labels: PR: unreviewed, documentation

#19833 fix: Omit useless props & fix icon missing
  components/form/FormItem.tsx
  components/form/FormItemInput.tsx
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/demo/register.md
Labels: PR: unreviewed, bug

#19832 docs: Removed version column in 4.0
  components/alert/index.en-US.md
  components/alert/index.zh-CN.md
  components/drawer/index.en-US.md
  components/drawer/index.zh-CN.md
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/message/index.en-US.md
  components/message/index.zh-CN.md
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
  components/notification/index.en-US.md
  components/notification/index.zh-CN.md
  components/popconfirm/index.en-US.md
  components/popconfirm/index.zh-CN.md
  components/progress/index.en-US.md
  components/progress/index.zh-CN.md
  components/result/index.en-US.md
  components/result/index.zh-CN.md
  components/skeleton/index.en-US.md
  components/skeleton/index.zh-CN.md
  components/spin/index.en-US.md
  components/spin/index.zh-CN.md
  components/table/index.en-US.md
  components/table/index.zh-CN.md
Labels: PR: unreviewed, documentation

#19834 docs: Removed version column in 4.0
  components/tooltip/index.en-US.md
  components/tooltip/index.zh-CN.md
  components/tree/index.en-US.md
  components/tree/index.zh-CN.md
Labels: PR: unreviewed, documentation

#19825 docs: Removed version column in 4.0
  components/breadcrumb/index.en-US.md
  components/breadcrumb/index.zh-CN.md
  components/dropdown/index.en-US.md
  components/dropdown/index.zh-CN.md
Labels: PR: unreviewed, documentation

#19827 docs(update): removed 3.x version description in 4.0-prepare
  components/avatar/index.en-US.md
  components/avatar/index.zh-CN.md
  components/badge/index.en-US.md
  components/badge/index.zh-CN.md
  components/calendar/index.en-US.md
  components/calendar/index.zh-CN.md
  components/card/index.en-US.md
  components/card/index.zh-CN.md
  components/carousel/index.en-US.md
  components/carousel/index.zh-CN.md
  components/collapse/index.en-US.md
  components/collapse/index.zh-CN.md
  components/comment/index.en-US.md
  components/comment/index.zh-CN.md
  components/descriptions/index.en-US.md
  components/descriptions/index.zh-CN.md
  components/empty/index.en-US.md
  components/empty/index.zh-CN.md
  components/list/index.en-US.md
  components/list/index.zh-CN.md
  components/statistic/index.en-US.md
  components/statistic/index.zh-CN.md
Labels: PR: unreviewed, documentation

#19848 docs: Update ConfigProvider documentation grammar
  components/config-provider/index.en-US.md
Labels: PR: reviewed-approved, documentation

#19845 docs: Button & Icon remove version column in 4.0-repare
  components/button/index.en-US.md
  components/button/index.zh-CN.md
  components/icon/index.en-US.md
  components/icon/index.zh-CN.md
Labels: PR: unreviewed, documentation

#19842 docs(Timeline, Tabs): removed version column in 4.0
  components/tabs/index.en-US.md
  components/tabs/index.zh-CN.md
  components/timeline/index.en-US.md
  components/timeline/index.zh-CN.md
Labels: PR: unreviewed, documentation

#19844 docs: Layout and Affix clean version
  components/affix/index.en-US.md
  components/affix/index.zh-CN.md
  components/layout/index.en-US.md
  components/layout/index.zh-CN.md
Labels: PR: unreviewed, documentation

#19846 fix: Export tooltip helper interfaces
  components/tooltip/index.tsx
Labels: PR: unreviewed, bug

#19867 docs: Fix default values for unclear types
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: PR: unreviewed, documentation

#19868 docs: correct maxTagTextLength description in Select.
  components/select/index.en-US.md
Labels: PR: unreviewed, documentation

#19854 docs: delete version
  components/anchor/index.en-US.md
  components/anchor/index.zh-CN.md
  components/config-provider/index.en-US.md
  components/config-provider/index.zh-CN.md
  components/divider/index.en-US.md
  components/divider/index.zh-CN.md
Labels: PR: unreviewed, documentation

#19699 feat: Add skeleton button
  components/skeleton/Avatar.tsx
  components/skeleton/Button.tsx
  components/skeleton/Skeleton.tsx
  components/skeleton/SkeletonElement.tsx
  components/skeleton/__tests__/__snapshots__/demo.test.js.snap
  components/skeleton/__tests__/__snapshots__/index.test.js.snap
  components/skeleton/__tests__/index.test.js
  components/skeleton/demo/button.md
  components/skeleton/index.en-US.md
  components/skeleton/index.tsx
  components/skeleton/index.zh-CN.md
  components/skeleton/style/index.less
Labels: PR: unreviewed, enhancement

#19875 docs: Improved grammar in AutoComplete docs
  components/auto-complete/index.en-US.md
Labels: PR: unreviewed, documentation

#19872 docs: Removed version column in 4.0
  components/grid/index.en-US.md
  components/grid/index.zh-CN.md
  components/menu/index.en-US.md
  components/menu/index.zh-CN.md
  components/page-header/index.en-US.md
  components/page-header/index.zh-CN.md
  components/pagination/index.en-US.md
  components/pagination/index.zh-CN.md
  components/steps/index.en-US.md
  components/steps/index.zh-CN.md
  components/typography/index.en-US.md
  components/typography/index.zh-CN.md
Labels: PR: unreviewed, documentation

#19874 docs(Tag): remove version column in 4.0
  components/tag/index.en-US.md
  components/tag/index.zh-CN.md
Labels: PR: unreviewed, documentation

#19613 Progress bar with steps
  components/progress/Steps.tsx
  components/progress/__tests__/__snapshots__/demo.test.js.snap
  components/progress/demo/steps.md
  components/progress/index.en-US.md
  components/progress/index.zh-CN.md
  components/progress/progress.tsx
  components/progress/style/index.less
Labels: PR: unreviewed

#19876 docs: clean up version info in 4.0
  components/input-number/index.en-US.md
  components/input-number/index.zh-CN.md
  components/input/demo/autosize-textarea.md
  components/input/demo/password-input.md
  components/input/demo/search-input.md
  components/input/index.en-US.md
  components/input/index.zh-CN.md
  components/mentions/index.en-US.md
  components/mentions/index.zh-CN.md
  components/radio/index.en-US.md
  components/radio/index.zh-CN.md
  components/rate/index.en-US.md
  components/rate/index.zh-CN.md
  components/switch/index.en-US.md
  components/switch/index.zh-CN.md
Labels: PR: unreviewed, documentation

#19812 fix(TimePicker): fix time-picker disabled item focus style
  components/time-picker/style/index.less
Labels: PR: unreviewed, bug

#19902 fix: icon styles precedence
  package.json
Labels: PR: unreviewed, bug

#19900 fix: AutoComplete doc example TypeError
  components/auto-complete/demo/non-case-sensitive.md
Labels: PR: unreviewed, bug

#19908 fix: Mentions form example not correct display
  components/mentions/__tests__/__snapshots__/demo.test.js.snap
  components/mentions/demo/form.md
Labels: PR: unreviewed, bug

#19907 fix: Select doc edit icon margin
  components/select/demo/option-label-prop.md
Labels: PR: unreviewed, bug

#19899 chore(Table): Update custom-filter-panel.md demo
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/demo/custom-filter-panel.md
Labels: PR: unreviewed, chore

#19905 docs: 3.25.3 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed, documentation

#19920 ci: fix cannot create directory with mkdir
  .github/workflows/test.yml
Labels: PR: unreviewed, ci

#19926 fix: Input.Group compact border radius issue
  components/input/style/mixin.less
Labels: PR: unreviewed, bug

#19935 chore: Remove LocaleProvider & Mention in export
  components/__tests__/__snapshots__/index.test.js.snap
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/config-provider/__tests__/components.test.js
  components/index.tsx
  components/locale-provider/__tests__/__snapshots__/demo.test.js.snap
  components/locale-provider/__tests__/demo.test.js
  components/locale-provider/__tests__/index.test.js
  components/locale-provider/demo/all.md
  components/locale-provider/demo/basic.md
  components/locale-provider/index.en-US.md
  components/locale-provider/index.zh-CN.md
  components/mention/__tests__/__snapshots__/demo.test.js.snap
  components/mention/__tests__/demo.test.js
  components/mention/__tests__/index.test.js
  components/mention/demo/async.md
  components/mention/demo/avatar.md
  components/mention/demo/basic.md
  components/mention/demo/controllder-simple.md
  components/mention/demo/controlled.md
  components/mention/demo/custom-tag.md
  components/mention/demo/multilines.md
  components/mention/demo/multiple-trigger.md
  components/mention/demo/placement.md
  components/mention/demo/popupContainer.md
  components/mention/demo/readonly.md
  components/mention/index.en-US.md
  components/mention/index.tsx
  components/mention/index.zh-CN.md
  components/mention/style/index.less
  components/mention/style/index.tsx
  components/mentions/index.en-US.md
  components/mentions/index.zh-CN.md
  package.json
  tests/__snapshots__/index.test.js.snap
Labels: PR: unreviewed, chore

#19873 fix: 4.0 table filters value may be previous
  components/table/__tests__/Table.filter.test.js
  components/table/__tests__/__snapshots__/Table.filter.test.js.snap
  components/table/hooks/useFilter/FilterDropdown.tsx
  components/table/hooks/useSyncState.ts
Labels: PR: unreviewed, bug

#19943 fix(Spin): should not be render default indicator when indicator value is null
  components/spin/__tests__/__snapshots__/index.test.js.snap
  components/spin/__tests__/index.test.js
  components/spin/index.tsx
Labels: PR: reviewed-changes-requested, bug

#19939 feat: 💄 Add @table-header-bg-sm and fix footer style
  components/style/themes/default.less
  components/table/style/size.less
Labels: PR: reviewed-approved, enhancement

#19958 fix(Button): Button disabled with loading not prevent pointer-events
  components/button/style/index.less
Labels: PR: unreviewed, bug

#19960 docs: Update FAQ replace momentjs to Day.js with antd-dayjs-webpack-plugin
  docs/react/faq.en-US.md
  docs/react/faq.zh-CN.md
  docs/react/getting-started.en-US.md
  docs/react/getting-started.zh-CN.md
  docs/react/use-with-create-react-app.en-US.md
  docs/react/use-with-create-react-app.zh-CN.md
Labels: PR: reviewed-approved, documentation

#19937 docs(Form): 如何在函数组件中拿到 form 实例
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: PR: reviewed-approved, documentation

#19967 fix: update message content with a unique key and cancel manually
  components/message/__tests__/index.test.js
  components/message/demo/update.md
  components/message/index.tsx
Labels: PR: reviewed-changes-requested, bug

#19980 fix: Table ajax pagination should work
  components/table/__tests__/Table.pagination.test.js
  components/table/hooks/usePagination.ts
Labels: PR: reviewed-changes-requested, bug

#19987 fix(Upload.Dragger): move className and Style pass to ant-upload-drag
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/upload/Upload.tsx
  components/upload/__tests__/__snapshots__/demo.test.js.snap
Labels: PR: reviewed-approved, bug

#19837 feat: 4.0 danger button
  components/button/__tests__/__snapshots__/demo.test.js.snap
  components/button/button.tsx
  components/button/demo/basic.md
  components/button/demo/block.md
  components/button/demo/button-group.md
  components/button/demo/disabled.md
  components/button/demo/ghost.md
  components/button/demo/icon.md
  components/button/demo/loading.md
  components/button/demo/size.md
  components/button/index.en-US.md
  components/button/index.zh-CN.md
  components/button/style/index.less
  components/button/style/mixin.less
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/demo/advanced-search.md
  components/form/demo/form-context.md
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/demo/basic.md
  components/table/demo/dynamic-settings.md
  components/table/demo/jsx.md
Labels: PR: unreviewed, enhancement

#19983 fix: Col default width
  components/grid/__tests__/__snapshots__/demo.test.js.snap
  components/grid/demo/basic.md
  components/grid/style/index.less
Labels: PR: unreviewed, bug

#19968 feat: dark theme in 4.0
  .antd-tools.config.js
  components/anchor/style/index.less
  components/button/style/index.less
  components/checkbox/style/mixin.less
  components/comment/style/index.less
  components/date-picker/style/Calendar.less
  components/date-picker/style/RangePicker.less
  components/date-picker/style/TimePicker.less
  components/drawer/style/drawer.less
  components/dropdown/style/index.less
  components/message/style/index.less
  components/modal/style/modal.less
  components/notification/style/index.less
  components/pagination/style/index.less
  components/radio/style/index.less
  components/style/color/colors.less
  components/style/dark.less
  components/style/themes/dark.less
  components/style/themes/default.less
  components/switch/style/index.less
  components/table/style/index.less
  components/time-picker/style/index.less
  components/upload/style/index.less
  docs/react/customize-theme.en-US.md
  docs/react/customize-theme.zh-CN.md
Labels: PR: unreviewed, enhancement

#20008 fix: fix upload long picture style
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/upload/UploadList.tsx
  components/upload/__tests__/__snapshots__/demo.test.js.snap
  components/upload/__tests__/__snapshots__/uploadlist.test.js.snap
  components/upload/style/index.less
Labels: PR: unreviewed, bug

#20017 fix: 🐛 Input clear icon overclap with feedback icon
  components/form/style/index.less
Labels: PR: unreviewed, bug

#20016 fix: 🐛 Slider tooltip not aligned center
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/slider/__tests__/__snapshots__/demo.test.js.snap
  components/slider/__tests__/__snapshots__/index.test.js.snap
  components/slider/index.tsx
  components/slider/style/index.less
Labels: PR: unreviewed, bug

#20019 fix: 🐛 Descriptions items not working with React.Fragment
  components/descriptions/__tests__/__snapshots__/index.test.js.snap
  components/descriptions/__tests__/index.test.js
  components/descriptions/index.tsx
Labels: PR: reviewed-changes-requested, bug
