Repository ant-design/ant-design, pull requests merged in 2019-06, with the labels that each got.

#16915 doc: changelog 3.19.2
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed

#16916 3.19.2 changelog
  CHANGELOG.en-US.md
Labels: PR: unreviewed

#16917 3.19.2 changelog doc
  CHANGELOG.en-US.md
Labels: PR: unreviewed

#16918 fix: cascader unable to enter space during search #16871
  components/cascader/index.tsx
Labels: PR: unreviewed

#16851 fix: fix type of action and RcFile
  components/upload/interface.tsx
Labels: PR: unreviewed

#16922 Remove useless type
  components/upload/interface.tsx
Labels: PR: unreviewed

#16921 test: Add packtracker
  package.json
  webpack.config.js
Labels: PR: unreviewed

#16843 feat: Added 2 variables to flexibly control the background of the table cells
  components/style/themes/default.less
  components/table/style/index.less
Labels: PR: reviewed-approved

#16925 fix: Transfer render Empty when customize without data
  components/transfer/list.tsx
Labels: PR: unreviewed

#16926 fix: Hide Spinner of InputNumber when type is number
  components/input-number/style/index.less
Labels: PR: unreviewed

#16928 feat: Add bug icon
  package.json
Labels: PR: reviewed-approved

#16929 fix: Breadcrumb validateDOMNesting warning
  components/breadcrumb/BreadcrumbItem.tsx
  components/breadcrumb/__tests__/__snapshots__/Breadcrumb.test.js.snap
  components/breadcrumb/__tests__/__snapshots__/demo.test.js.snap
  components/breadcrumb/demo/overlay.md
Labels: PR: unreviewed

#16885 fix(Breadcrumb): when route.children exist, the path of children is wrong
  components/breadcrumb/Breadcrumb.tsx
Labels: PR: unreviewed

#16950 fix(Table): Hide header extra scrollbar control
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/style/index.less
  components/time-picker/__tests__/__snapshots__/index.test.js.snap
  components/time-picker/__tests__/index.test.js
  package.json
Labels: PR: unreviewed

#15224 Add fault-tolerant processing for rowSelection.getCheckboxProps
  components/table/Table.tsx
Labels: Inactive, PR: unreviewed

#16958 :lipstick: use marginRight remind developer
  components/auto-complete/__tests__/__snapshots__/demo.test.js.snap
  components/auto-complete/demo/uncertain-category.md
Labels: PR: unreviewed

#16957 fix: Table miss border-raidus in Firefox
  components/table/style/index.less
Labels: PR: unreviewed

#16934 fix: abnormal scrollbar in Chrome
  components/table/style/index.less
Labels: PR: unreviewed

#16973 chore: update snapshots
  components/layout/__tests__/__snapshots__/demo.test.js.snap
Labels: PR: unreviewed

#16971 chore: 🆙 upgrade all deps to latest version
  components/config-provider/index.tsx
  components/drawer/index.tsx
  components/form/context.ts
  components/layout/layout.tsx
  components/menu/index.tsx
  package.json
Labels: PR: unreviewed

#16977 Suppress autoprefixer warning
  package.json
Labels: PR: unreviewed

#16984 docs: Add FAQ for DatePicker/RangePicker mode prop usage
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
  docs/react/faq.en-US.md
  docs/react/faq.zh-CN.md
  webpack.config.js
Labels: PR: unreviewed

#16988 fix: Divider `orientation="center"` style
  components/divider/__tests__/__snapshots__/demo.test.js.snap
  components/divider/index.tsx
  components/divider/style/index.less
Labels: PR: unreviewed

#17003 Export TextProps and update english in error
  components/typography/Text.tsx
Labels: PR: unreviewed

#17000 Add attribute background to stylize the one of the input in the validation
  components/form/style/mixin.less
Labels: PR: reviewed-approved

#16965 Dark theme
  components/checkbox/style/mixin.less
  components/dropdown/style/index.less
  components/style/themes/default.less
Labels: PR: unreviewed

#16985 feat(popconfirm): add disabled in popconfirm
  components/layout/__tests__/__snapshots__/demo.test.js.snap
  components/popconfirm/__tests__/index.test.js
  components/popconfirm/index.en-US.md
  components/popconfirm/index.tsx
  components/popconfirm/index.zh-CN.md
  components/time-picker/__tests__/__snapshots__/index.test.js.snap
  components/time-picker/__tests__/index.test.js
Labels: PR: reviewed-approved

#17002 Add missing spanish translations
  components/locale-provider/es_ES.tsx
Labels: PR: unreviewed

#16961 docs: Add width attr to the table's grouping columns demo
  components/table/demo/grouping-columns.md
Labels: PR: unreviewed

#16741 add missing prop in documentation
  components/pagination/index.en-US.md
Labels: PR: unreviewed

#16996 feat: added three variables to allow customization of the dropdown list
  components/dropdown/style/index.less
  components/style/themes/default.less
Labels: PR: reviewed-approved

#16998 docs: 3.19.3 change-log
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed

#17020 fix: Table with sort should reset to first page
  components/table/Table.tsx
  components/table/__tests__/Table.sorter.test.js
Labels: PR: unreviewed

#17026 fix(PageHeader): abnormal margin issue of PageHeader extra
  components/page-header/index.tsx
  components/page-header/style/index.less
Labels: PR: unreviewed

#17029 fix(PageHeader): abnormal margin issue of PageHeader extra
  components/page-header/style/index.less
Labels: PR: unreviewed

#17031 feat: Border-radius customization for Collapse Panel
  components/collapse/style/index.less
  components/style/themes/default.less
Labels: PR: reviewed-approved

#17038 chore: update rc-calendar deps
  package.json
Labels: PR: unreviewed

#17039 style: Keep submenu selected style
  components/menu/style/index.less
Labels: PR: unreviewed

#17041 style: less variables for comment component font-size
  components/comment/style/index.less
  components/style/themes/default.less
Labels: PR: unreviewed

#17042 chore: Translate remainder of Typography & AutoComplete
  components/auto-complete/demo/certain-category.md
  components/auto-complete/demo/uncertain-category.md
Labels: PR: unreviewed

#17045 docs: fix image in feedback spec documentation
  docs/spec/feedback.en-US.md
  docs/spec/feedback.zh-CN.md
Labels: PR: unreviewed

#17055 fix: Tree with `showLine` animation shake
  components/tree/style/index.less
Labels: PR: reviewed-approved

#17057 fix: add link type to Button's doc
  components/button/demo/basic.md
Labels: PR: unreviewed

#17065 style: adjust bordered table header scrollbar style
  components/table/style/index.less
Labels: PR: unreviewed

#17066 style: optimize bordered table header scrollbar style
  components/table/style/index.less
Labels: PR: unreviewed

#17070 Fix grammar on message documentation
  components/message/demo/other.md
Labels: PR: unreviewed

#17009 fix: remove margin for collapse arrow
  components/collapse/style/index.less
Labels: PR: unreviewed

#17092 fix: Fixing date formats for Arabic-Egypt locale
  components/date-picker/locale/ar_EG.tsx
Labels: PR: unreviewed

#17098 Update index.zh-CN.md
  components/auto-complete/index.zh-CN.md
Labels: PR: unreviewed

#17100 fix: Input not align with other components in Chrome
  components/input/style/mixin.less
  components/time-picker/style/index.less
Labels: PR: unreviewed

#17108 fix: Add missing russian translations
  components/locale-provider/ru_RU.tsx
Labels: PR: unreviewed

#17113 style: Make Divider style customization easier
  components/divider/__tests__/__snapshots__/demo.test.js.snap
  components/divider/demo/customize-style.md
  components/divider/demo/horizontal.md
  components/divider/demo/vertical.md
  components/divider/demo/with-text.md
  components/divider/style/index.less
Labels: PR: unreviewed

#17114 fix: PageHeader back icon pointers is not always clickable problem
  components/page-header/style/index.less
Labels: PR: unreviewed

#17115 Add 3.19.4 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: reviewed-approved

#17119 chore: upgrade eslint-config-prettier version
  package.json
  scripts/check-commit.js
Labels: PR: reviewed-changes-requested

#17118 refactor: Fix lgtm errors
  components/affix/index.tsx
  components/badge/ScrollNumber.tsx
  components/descriptions/index.tsx
Labels: PR: unreviewed

#17049 fix eslint error and Descriptions.Item ts define
  components/descriptions/index.tsx
  components/descriptions/style/index.less
Labels: PR: reviewed-approved

#17130 chore: Fix react-dnd CI
  .jest.js
  .jest.node.js
  components/tabs/demo/custom-tab-bar-node.md
Labels: PR: unreviewed

#17126 fix: RangerPicker style
  components/date-picker/style/RangePicker.less
Labels: PR: unreviewed

#17132 fix: `getPopupContainer` of ConfigProvider not works on Modal
  components/modal/Modal.tsx
Labels: PR: unreviewed

#17133 chore: 3.19.5 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#17137 docs: update modal doc
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
Labels: PR: unreviewed

#17140 fix: Nest Card extra position not correct
  components/card/style/index.less
Labels: PR: reviewed-approved

#17141 fix: Table crash when filter dynamic change
  components/table/__tests__/Table.filter.test.js
  components/table/filterDropdown.tsx
Labels: PR: unreviewed

#17161 Fix English translation
  components/input/demo/allowClear.md
Labels: PR: unreviewed

#17165 fix: Wrong height of TextArea & DatePicker
  components/date-picker/style/Picker.less
  components/date-picker/style/RangePicker.less
  components/input/style/mixin.less
Labels: PR: reviewed-approved

#17166 docs: 3.19.6 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#17172 style: run lint-fix
  components/_util/__tests__/util.test.js
  components/badge/ScrollNumber.tsx
  components/breadcrumb/Breadcrumb.tsx
  components/button/button.tsx
  components/button/demo/size.md
  components/collapse/demo/accordion.md
  components/collapse/demo/basic.md
  components/collapse/demo/borderless.md
  components/collapse/demo/custom.md
  components/collapse/demo/mix.md
  components/collapse/demo/noarrow.md
  components/date-picker/demo/start-end.md
  components/form/demo/customized-form-controls.md
  components/form/demo/form-in-modal.md
  components/form/demo/global-state.md
  components/form/demo/register.md
  components/form/demo/without-form-create.md
  components/form/interface.ts
  components/input/demo/search-input.md
  components/input/style/mixin.less
  components/list/Item.tsx
  components/list/demo/infinite-load.md
  components/list/demo/infinite-virtualized-load.md
  components/mention/demo/avatar.md
  components/mention/demo/custom-tag.md
  components/mentions/index.tsx
  components/menu/demo/horizontal.md
  components/menu/demo/inline-collapsed.md
  components/menu/demo/inline.md
  components/menu/demo/sider-current.md
  components/menu/demo/theme.md
  components/menu/demo/vertical.md
  components/modal/demo/confirm-promise.md
  components/modal/demo/confirm-router.md
  components/modal/demo/confirm.md
  components/select/demo/search-box.md
  components/select/index.en-US.md
  components/select/index.zh-CN.md
  components/statistic/demo/countdown.md
  components/table/demo/drag-sorting.md
  components/table/demo/dynamic-settings.md
  components/table/interface.tsx
  components/tabs/demo/custom-add-trigger.md
  components/tabs/demo/editable-card.md
  components/tabs/demo/slide.md
  components/tag/CheckableTag.tsx
  components/tag/demo/hot-tags.md
  components/time-picker/__tests__/index.test.js
  components/tree-select/demo/basic.md
  components/tree-select/demo/checkable.md
  components/tree-select/demo/multiple.md
  components/tree-select/demo/suffix.md
  components/tree/demo/search.md
  components/upload/demo/avatar.md
  components/upload/demo/drag.md
  docs/react/faq.en-US.md
  renovate.json
  scripts/check-commit.js
  site/theme/template/IconDisplay/index.tsx
  site/theme/template/IconDisplay/themeIcons.tsx
Labels: PR: reviewed-changes-requested

#17168 chore: upgrade rc-progress to 2.4.0
  components/progress/Circle.tsx
  components/progress/__tests__/__snapshots__/demo.test.js.snap
  components/progress/__tests__/__snapshots__/index.test.js.snap
  components/progress/progress.tsx
  package.json
Labels: PR: reviewed-approved

#17177 fix(Doc): remove useless option in API Doc for row-selection-custom Table
  components/table/demo/row-selection-custom.md
Labels: PR: unreviewed

#17191 使操纵杆右侧半边也可以操作
  components/table/demo/resizable-column.md
Labels: PR: unreviewed

#17198 docs: Fix site Table resize demo
  components/table/demo/resizable-column.md
Labels: PR: unreviewed

#17211 docs: add documentation about button autoInsertSpaceInButton
  components/button/index.en-US.md
  components/button/index.zh-CN.md
Labels: PR: reviewed-approved

#17215 docs: update progress docs to mark only line support active
  components/progress/index.en-US.md
  components/progress/index.zh-CN.md
Labels: PR: unreviewed

#17207 fix: Clone only valid react child elements
  components/descriptions/__tests__/__snapshots__/index.test.js.snap
  components/descriptions/__tests__/index.test.js
  components/descriptions/index.tsx
Labels: PR: unreviewed

#17223 fix: Table scrollbar style in IE
  components/table/style/index.less
Labels: PR: unreviewed

#17209 fix: Fix single Breadcrumb not show on PageHeader
  components/page-header/__tests__/index.test.js
  components/page-header/index.tsx
Labels: PR: unreviewed

#17120 refactor: eliminate `any` type in exported interfaces.#14044
  components/_util/interopDefault.ts
  components/anchor/AnchorLink.tsx
  components/auto-complete/InputElement.tsx
  components/auto-complete/index.tsx
  components/avatar/index.tsx
  components/back-top/index.tsx
  components/badge/ScrollNumber.tsx
  components/breadcrumb/Breadcrumb.tsx
  components/button/button.tsx
  components/calendar/Header.tsx
  components/checkbox/Checkbox.tsx
  components/checkbox/Group.tsx
  components/collapse/Collapse.tsx
  components/comment/index.tsx
  components/date-picker/InputIcon.tsx
  components/date-picker/interface.tsx
  components/dropdown/dropdown-button.tsx
  components/form/Form.tsx
  components/icon/IconFont.tsx
  components/input/Group.tsx
  components/input/Search.tsx
  components/list/index.tsx
  components/locale-provider/LocaleReceiver.tsx
  components/mention/index.tsx
  components/mentions/index.tsx
  components/menu/index.tsx
  components/message/index.tsx
  components/modal/Modal.tsx
  components/popconfirm/index.tsx
  components/radio/interface.tsx
  components/rate/index.tsx
  components/select/index.tsx
  components/slider/index.tsx
  components/spin/index.tsx
  components/steps/index.tsx
  components/switch/index.tsx
  components/table/FilterDropdownMenuWrapper.tsx
  components/table/Table.tsx
  components/table/createStore.tsx
  components/table/filterDropdown.tsx
  components/table/interface.tsx
  components/tabs/index.tsx
  components/tooltip/placements.tsx
  components/transfer/index.tsx
  components/transfer/search.tsx
  components/tree-select/index.tsx
  components/tree-select/interface.tsx
  components/tree/Tree.tsx
  components/upload/interface.tsx
Labels: PR: reviewed-changes-requested

#17063 fix: prop headerRender should be optional for component Calendar
  components/calendar/Header.tsx
  components/calendar/index.tsx
Labels: PR: unreviewed

#17228 fix: Layout sider trigger z-index too low
  components/layout/style/index.less
Labels: PR: unreviewed

#17229 fix: Modal 24px bottom area not trigger mask click
  components/modal/style/modal.less
Labels: PR: reviewed-approved

#17227 docs: release 3.19.7
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  docs/react/practical-projects.en-US.md
  docs/react/practical-projects.zh-CN.md
  package.json
Labels: PR: unreviewed

#17237 Tabs props missing prop
  components/tabs/index.tsx
Labels: PR: unreviewed

#17239 Update SubMenu.tsx
  components/menu/SubMenu.tsx
Labels: PR: unreviewed

#17236 chore: upgrade eslint to 6.0
  package.json
Labels: PR: reviewed-approved

#17247 chore: Support TypeScript & JavaScript with Demo
  components/form-legacy/Form.tsx
  components/form-legacy/FormItem.tsx
  components/form-legacy/__tests__/__snapshots__/demo.test.js.snap
  components/form-legacy/__tests__/__snapshots__/label.test.js.snap
  components/form-legacy/__tests__/__snapshots__/message.test.js.snap
  components/form-legacy/__tests__/demo.test.js
  components/form-legacy/__tests__/index.test.js
  components/form-legacy/__tests__/label.test.js
  components/form-legacy/__tests__/message.test.js
  components/form-legacy/__tests__/type.tsx
  components/form-legacy/constants.tsx
  components/form-legacy/context.ts
  components/form-legacy/demo/advanced-search.md
  components/form-legacy/demo/coordinated.md
  components/form-legacy/demo/customized-form-controls.md
  components/form-legacy/demo/dynamic-form-item.md
  components/form-legacy/demo/dynamic-rule.md
  components/form-legacy/demo/form-in-modal.md
  components/form-legacy/demo/global-state.md
  components/form-legacy/demo/horizontal-login.md
  components/form-legacy/demo/layout.md
  components/form-legacy/demo/normal-login.md
  components/form-legacy/demo/register.md
  components/form-legacy/demo/style-check-debug.md
  components/form-legacy/demo/time-related-controls.md
  components/form-legacy/demo/validate-other.md
  components/form-legacy/demo/validate-static.md
  components/form-legacy/demo/without-form-create.md
  components/form-legacy/docs/tutorial.md
  components/form-legacy/index.en-US.md
  components/form-legacy/index.tsx
  components/form-legacy/index.zh-CN.md
  components/form-legacy/interface.ts
  components/form-legacy/style/index.less
  components/form-legacy/style/index.tsx
  components/form-legacy/style/mixin.less
  components/form/Form.tsx
  components/form/demo/horizontal-login.md
  components/form/index.tsx
  components/form/style/index.less
  components/form/style/mixin.less
  package.json
  site/theme/static/demo.less
  site/theme/template/Content/Demo/CodePreview.jsx
  site/theme/template/Content/Demo/index.jsx
  site/theme/template/Content/index.jsx
Labels: PR: reviewed-changes-requested

#17249 fix: revert `unknown` to `any`
  components/auto-complete/InputElement.tsx
  components/auto-complete/index.tsx
  components/breadcrumb/Breadcrumb.tsx
  components/button/button.tsx
  components/checkbox/Checkbox.tsx
  components/checkbox/Group.tsx
  components/date-picker/interface.tsx
  components/form/Form.tsx
  components/icon/IconFont.tsx
  components/mention/index.tsx
  components/mentions/index.tsx
  components/menu/index.tsx
  components/message/index.tsx
  components/modal/Modal.tsx
  components/radio/interface.tsx
  components/select/index.tsx
  components/table/Table.tsx
  components/table/filterDropdown.tsx
  components/table/interface.tsx
  components/tabs/index.tsx
  components/tree-select/interface.tsx
  components/tree/Tree.tsx
  package.json
Labels: PR: unreviewed

#17262 test: fix jest timer warning
  components/carousel/__tests__/index.test.js
  components/table/demo/drag-sorting.md
Labels: PR: reviewed-changes-requested

#17264 style: fix Tooltip arrow shadow
  components/tooltip/style/index.less
Labels: PR: unreviewed

#17289 docs: update design resource page
  docs/spec/download.en-US.md
  docs/spec/download.zh-CN.md
Labels: PR: unreviewed

#17300 fix: size fields in Skeleton AvatarProps to accept numbers
  components/skeleton/Avatar.tsx
Labels: PR: unreviewed

#17280 fix: Descriptions.Item not support className
  components/descriptions/__tests__/__snapshots__/demo.test.js.snap
  components/descriptions/__tests__/__snapshots__/index.test.js.snap
  components/descriptions/__tests__/index.test.js
  components/descriptions/index.tsx
  components/descriptions/style/index.less
Labels: PR: unreviewed

#17319 chore: Clean up useless style
  components/form/style/index.less
Labels: PR: reviewed-approved

#17318 [Mentions] style: Fix placeholder color
  components/mentions/style/index.less
Labels: PR: unreviewed

#17311 chore: Update rc-drawer version to fix afterVisibleChange issue
  components/drawer/index.tsx
  package.json
Labels: PR: unreviewed

#17315 feat: progress circle add support gradient
  components/progress/Circle.tsx
  components/progress/__tests__/__snapshots__/demo.test.js.snap
  components/progress/__tests__/__snapshots__/index.test.js.snap
  components/progress/demo/gradient-line.md
  components/progress/index.en-US.md
  components/progress/index.zh-CN.md
  components/progress/style/index.less
  package.json
Labels: PR: reviewed-approved

#17337 fix: Descriptions组件不设置label的显示问题
  components/descriptions/__tests__/index.test.js
  components/descriptions/index.tsx
  components/descriptions/style/index.less
Labels: PR: reviewed-changes-requested

#17330 feat: Descriptions add vertical layout
  components/descriptions/__tests__/__snapshots__/demo.test.js.snap
  components/descriptions/__tests__/__snapshots__/index.test.js.snap
  components/descriptions/__tests__/index.test.js
  components/descriptions/demo/vertical-border.md
  components/descriptions/demo/vertical.md
  components/descriptions/index.en-US.md
  components/descriptions/index.tsx
  components/descriptions/index.zh-CN.md
Labels: PR: reviewed-approved

#17316 fix: add maskClosable is false ESC close
  components/drawer/index.en-US.md
  components/drawer/index.tsx
  components/drawer/index.zh-CN.md
Labels: PR: reviewed-approved

#17331 chore: Extract SwitchChangeEventHandler and SwitchSize
  components/switch/index.tsx
Labels: PR: unreviewed

#17336 Add missing info in documents
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
Labels: PR: unreviewed

#17347 fix(Mentions): Incorrect line-height from .input() style
  components/mentions/style/index.less
Labels: PR: unreviewed

#17351 fix: small table header background
  components/table/style/size.less
Labels: PR: unreviewed

#17342 fix: CheckboxGroup onChange 值保持选项的顺序
  components/checkbox/Group.tsx
  components/checkbox/__tests__/group.test.js
Labels: PR: unreviewed

#17350 chore: move scripts to antd-tools
  .remarkrc.js
  package.json
  scripts/apiCollection.js
  scripts/sort-api-table.js
Labels: PR: reviewed-changes-requested

#17345 docs: Tree treeData
  components/tree/Tree.tsx
  components/tree/index.en-US.md
  components/tree/index.zh-CN.md
Labels: PR: unreviewed

#17321 chore: Optimize PageHeader className naming
  components/page-header/__tests__/__snapshots__/demo.test.js.snap
  components/page-header/__tests__/__snapshots__/index.test.js.snap
  components/page-header/index.tsx
  components/page-header/style/index.less
Labels: PR: reviewed-approved

#17355 docs(Table): update description of hideDefaultSelections
  components/table/index.en-US.md
  components/table/index.zh-CN.md
Labels: PR: unreviewed

#17372 fix: Tooltip not work correctly on disabled Switch
  components/switch/index.tsx
  components/tooltip/__tests__/__snapshots__/tooltip.test.js.snap
  components/tooltip/__tests__/tooltip.test.js
  components/tooltip/index.tsx
Labels: PR: unreviewed

#17244 feat: New Components Result
  components/__tests__/__snapshots__/index.test.js.snap
  components/index.tsx
  components/result/__tests__/__snapshots__/demo.test.js.snap
  components/result/__tests__/demo.test.js
  components/result/__tests__/index.test.js
  components/result/demo/basic.md
  components/result/demo/complex.md
  components/result/demo/customIcon.md
  components/result/index.en-US.md
  components/result/index.tsx
  components/result/index.zh-CN.md
  components/result/noFound.tsx
  components/result/serverError.tsx
  components/result/style/index.less
  components/result/style/index.tsx
  components/result/unauthorized.tsx
  tests/__snapshots__/index.test.js.snap
Labels: PR: reviewed-approved

#17376 merge Feather into master
  components/__tests__/__snapshots__/index.test.js.snap
  components/index.tsx
  components/result/__tests__/__snapshots__/demo.test.js.snap
  components/result/__tests__/demo.test.js
  components/result/__tests__/index.test.js
  components/result/demo/basic.md
  components/result/demo/complex.md
  components/result/demo/customIcon.md
  components/result/index.en-US.md
  components/result/index.tsx
  components/result/index.zh-CN.md
  components/result/noFound.tsx
  components/result/serverError.tsx
  components/result/style/index.less
  components/result/style/index.tsx
  components/result/unauthorized.tsx
  tests/__snapshots__/index.test.js.snap
Labels: PR: unreviewed

#17377 chore: update test case
  components/form/__tests__/message.test.js
Labels: PR: reviewed-changes-requested

#17365 add 3.20.0 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  site/theme/static/markdown.less
Labels: PR: unreviewed

#17378 fix typo
  components/auto-complete/index.en-US.md
Labels: PR: reviewed-approved
