Repository ant-design/ant-design, pull requests merged in 2019-04, with the labels that each got.

#15911 3.16.2 changelog
  CHANGELOG.zh-CN.md
Labels: needs-more-info

#15912 upd: version package.json
  package.json
Labels: needs-more-info

#15970 fix: Menu defaultOpenKeys not work as expect
  components/_util/raf.ts
  components/menu/__tests__/index.test.js
  components/menu/index.tsx
Labels: PR: unreviewed

#15971 feat: table customizing variable
  components/style/themes/default.less
  components/table/style/index.less
Labels: PR: reviewed-approved

#15978 fix: Use `box-shadow` to handle wave effect
  components/_util/wave.tsx
  components/style/core/motion/other.less
Labels: PR: unreviewed

#15982 docs: Optimize form demo of customize functional component
  components/form/demo/customized-form-controls.md
Labels: PR: unreviewed

#15995 test: recover openAnimation
  components/menu/index.tsx
Labels: PR: unreviewed

#15962 fix(Tree): Switcher loading icon and checkbox should be vertical align when @tree-title-height is modified
  components/tree/style/index.less
Labels: PR: reviewed-approved

#15990 refactor: Optimize default selection column width implement
  components/table/Table.tsx
  components/table/__tests__/__snapshots__/Table.rowSelection.test.js.snap
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/table/style/index.less
Labels: PR: unreviewed

#16008 fix: Nest table with middle size style not correct
  components/table/style/size.less
Labels: PR: reviewed-approved

#15997 chore: menu openAnimation use object
  components/menu/index.tsx
Labels: PR: unreviewed

#15984 feat: Upload support customize previewFile
  components/__tests__/util/domHook.js
  components/upload/Upload.tsx
  components/upload/UploadList.tsx
  components/upload/__tests__/__snapshots__/demo.test.js.snap
  components/upload/__tests__/uploadlist.test.js
  components/upload/demo/preview-file.md
  components/upload/index.en-US.md
  components/upload/index.zh-CN.md
  components/upload/interface.tsx
  components/upload/utils.tsx
Labels: PR: reviewed-approved

#16040 Update use-with-create-react-app.zh-CN.md
  docs/react/use-with-create-react-app.zh-CN.md
Labels: PR: unreviewed

#15954 feat: form customizing variables
  components/form/style/index.less
  components/form/style/mixin.less
  components/style/themes/default.less
Labels: PR: reviewed-approved

#15976 chore: site static js use contentHash
  package.json
  site/bisheng.config.js
  site/theme/static/template.html
Labels: PR: unreviewed

#16051 docs: 📝 3.16.3 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed

#16064 docs: 📝 3.16.3 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed

#16063 fix: loading circle button can handle pointer events.
  components/button/__tests__/__snapshots__/demo.test.js.snap
  components/button/demo/loading.md
  components/button/style/index.less
Labels: PR: unreviewed

#16068 docs: 📝 Optimize table and form documentation
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/table/demo/fixed-columns-header.md
  components/table/demo/fixed-columns.md
  components/table/demo/fixed-header.md
  components/table/index.en-US.md
  components/table/index.zh-CN.md
Labels: PR: unreviewed

#16072 fix: labelAlign should work in Form.Item
  components/form/Form.tsx
  components/form/FormItem.tsx
  components/form/__tests__/__snapshots__/label.test.js.snap
  components/form/__tests__/label.test.js
  components/form/context.ts
Labels: PR: unreviewed

#16071 chore: 🆙 upgrade devDependencies
  .stylelintrc.json
  components/alert/style/index.less
  components/anchor/style/index.less
  components/auto-complete/style/index.less
  components/avatar/style/index.less
  components/back-top/style/index.less
  components/badge/style/index.less
  components/breadcrumb/style/index.less
  components/button/style/mixin.less
  components/calendar/style/index.less
  components/card/style/index.less
  components/cascader/style/index.less
  components/checkbox/style/mixin.less
  components/collapse/style/index.less
  components/date-picker/style/Calendar.less
  components/date-picker/style/Picker.less
  components/date-picker/style/RangePicker.less
  components/divider/style/index.less
  components/dropdown/style/index.less
  components/form/style/index.less
  components/grid/style/index.less
  components/input-number/style/index.less
  components/list/style/index.less
  components/mention/style/index.less
  components/menu/style/index.less
  components/message/style/index.less
  components/modal/style/modal.less
  components/notification/style/index.less
  components/page-header/style/index.less
  components/pagination/style/index.less
  components/popover/style/index.less
  components/progress/style/index.less
  components/radio/style/index.less
  components/rate/style/index.less
  components/select/style/index.less
  components/slider/style/index.less
  components/spin/style/index.less
  components/steps/style/index.less
  components/style/core/motion/swing.less
  components/style/mixins/iconfont.less
  components/style/mixins/motion.less
  components/switch/style/index.less
  components/table/style/index.less
  components/tabs/style/index.less
  components/tag/style/index.less
  components/time-picker/style/index.less
  components/timeline/style/index.less
  components/tooltip/style/index.less
  components/transfer/style/index.less
  components/tree-select/style/index.less
  components/tree/style/index.less
  components/tree/style/mixin.less
  components/upload/style/index.less
  package.json
  site/theme/static/colors.less
  site/theme/static/highlight.less
  site/theme/static/home.less
  site/theme/static/new-version-info-modal.less
Labels: PR: unreviewed

#16081 fix: If there is an existing debounce in progress, cancel that
  components/spin/index.tsx
Labels: PR: unreviewed

#16077 chore: Fix CI again
  components/date-picker/__tests__/DatePicker.test.js
  components/tree/__tests__/directory.test.js
Labels: PR: unreviewed

#16085 fix: Correct typo of theme less
  components/style/themes/default.less
Labels: PR: unreviewed

#16090 docs: Add responsive polyfill of Grid FAQ
  components/grid/index.en-US.md
  components/grid/index.zh-CN.md
Labels: PR: unreviewed

#16103 fix: Should Pagination of List default work
  components/list/__tests__/__snapshots__/pagination.test.js.snap
  components/list/__tests__/pagination.test.js
  components/list/index.tsx
Labels: PR: unreviewed

#16106 fix: PageHeader which tags should use ReactNode
  components/page-header/index.tsx
Labels: PR: unreviewed

#15310 style: 🏷 static tags
  components/tag/index.tsx
  components/tag/style/index.less
Labels: PR: unreviewed

#16110 fix: typescript of moment warning should work.
  components/date-picker/wrapPicker.tsx
Labels: PR: unreviewed

#16111 chore: Improve footer style
  site/theme/static/footer.less
  site/theme/template/Home/index.jsx
Labels: PR: unreviewed

#16119 fix: Adjust Radio active dot size to fix display in Firefox
  components/radio/style/index.less
Labels: PR: unreviewed

#16121 Update colors.en-US.md
  docs/spec/colors.en-US.md
Labels: PR: unreviewed

#16127 docs: Update AutoComplete demo
  components/auto-complete/demo/uncertain-category.md
Labels: PR: reviewed-approved

#16125 docs: Add FAQ of Affix window scroll
  components/affix/index.en-US.md
  components/affix/index.zh-CN.md
Labels: PR: unreviewed

#16126 fix: form typescript definition
  components/form/Form.tsx
  components/form/__tests__/type.tsx
  components/form/interface.ts
  package.json
Labels: PR: reviewed-approved

#16134 chore: add pre-publish commit check
  package.json
  scripts/check-commit.js
Labels: PR: reviewed-approved

#16146 fix: Affix dynamic change target should work
  components/affix/__tests__/Affix.test.js
  components/affix/index.tsx
  components/affix/utils.ts
Labels: PR: unreviewed

#16145 docs: Fix selector in demo 'Playground'.
  components/grid/demo/playground.md
Labels: PR: unreviewed

#16155 add text selection in less vars so we can overwrite it independent
  components/style/core/base.less
  components/style/themes/default.less
Labels: PR: unreviewed

#16144 fix: Modal's open animation
  components/modal/Modal.tsx
Labels: PR: unreviewed

#16128 feat: Support SkeletonAvatarProps.size accept number (#16078)
  components/skeleton/Avatar.tsx
  components/skeleton/__tests__/__snapshots__/index.test.js.snap
  components/skeleton/__tests__/index.test.js
  components/skeleton/index.en-US.md
  components/skeleton/index.zh-CN.md
Labels: PR: reviewed-approved

#16156 add react spring
  docs/react/recommendation.en-US.md
  docs/react/recommendation.zh-CN.md
Labels: PR: unreviewed

#15996 feat: Dropdown support set right icon
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/dropdown/__tests__/__snapshots__/demo.test.js.snap
  components/dropdown/__tests__/__snapshots__/dropdown-button.test.js.snap
  components/dropdown/demo/dropdown-button.md
  components/dropdown/demo/sub-menu.md
  components/dropdown/dropdown-button.tsx
  components/dropdown/index.en-US.md
  components/dropdown/index.zh-CN.md
Labels: PR: reviewed-approved

#16196 English documentation improvements (#6931)
  components/alert/demo/custom-icon.md
  components/alert/demo/icon.md
  components/alert/demo/smooth-closed.md
  components/avatar/demo/badge.md
  components/avatar/demo/type.md
  components/badge/demo/colorful.md
  components/collapse/demo/accordion.md
  components/collapse/demo/basic.md
  components/collapse/demo/noarrow.md
  components/comment/demo/editor.md
  components/divider/demo/horizontal.md
  components/divider/demo/orientation.md
  components/drawer/demo/form-in-drawer.md
  components/drawer/demo/multi-level-drawer.md
  components/drawer/demo/placement.md
  components/drawer/demo/user-profile.md
  components/drawer/index.en-US.md
  components/list/demo/grid.md
  components/list/demo/infinite-virtualized-load.md
  components/list/demo/resposive.md
  components/list/demo/vertical.md
  components/locale-provider/index.en-US.md
  components/message/demo/info.md
  components/message/demo/loading.md
  components/message/demo/thenable.md
  components/modal/demo/async.md
  components/modal/demo/button-props.md
  components/modal/demo/confirm-promise.md
  components/modal/demo/confirm-router.md
  components/modal/demo/confirm.md
  components/modal/demo/footer.md
  components/modal/demo/manual.md
  components/notification/demo/placement.md
  components/popconfirm/demo/placement.md
  components/skeleton/index.en-US.md
  components/spin/demo/nested.md
  components/spin/demo/size.md
  components/table/demo/size.md
  components/tag/demo/colorful.md
  components/timeline/index.en-US.md
  components/tooltip/demo/auto-adjust-overflow.md
  components/tooltip/demo/basic.md
  components/tooltip/demo/placement.md
  components/tree/demo/basic-controlled.md
  components/tree/demo/basic.md
Labels: PR: unreviewed

#16197 chore: upgrade devDeps and doc
  docs/react/introduce.en-US.md
  docs/react/introduce.zh-CN.md
  package.json
Labels: PR: unreviewed

#16202 fix: typescript definition update
  components/alert/__tests__/__snapshots__/demo.test.js.snap
  components/icon/index.tsx
  components/icon/utils.ts
  components/message/__tests__/__snapshots__/demo.test.js.snap
  components/tooltip/__tests__/__snapshots__/demo.test.js.snap
  scripts/check-commit.js
  site/theme/template/IconDisplay/CopyableIcon.tsx
  site/theme/template/IconDisplay/index.tsx
  site/theme/template/IconDisplay/themeIcons.tsx
Labels: PR: unreviewed

#16180 fix: Table `rowSelection.columnWidth` should work
  components/table/Table.tsx
  components/table/__tests__/__snapshots__/Table.rowSelection.test.js.snap
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/style/index.less
  package.json
Labels: PR: reviewed-approved

#16204 chore: update check-commit script
  scripts/check-commit.js
Labels: PR: unreviewed

#16188 chore: prettier md demo
  .prettierignore
  .prettierrc
  package.json
  scripts/prettier.js
Labels: PR: reviewed-approved

#16206 Add 3.16.4 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed, needs-more-info

#16211 fix: changelog format
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed

#16174 fix: Firefox miss bottom line when use sorter
  components/table/style/index.less
Labels: PR: unreviewed

#16213 Merge master into feature
  .prettierignore
  .prettierrc
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/date-picker/InputIcon.tsx
  components/date-picker/RangePicker.tsx
  components/date-picker/WeekPicker.tsx
  components/table/style/index.less
  package.json
  scripts/check-commit.js
  scripts/prettier.js
Labels: PR: reviewed-approved

#16224 fix: Ajudst typescript def of `allowSyntheticDefaultImports: false` user
  components/form/interface.ts
Labels: PR: unreviewed

#16231 fix: List pagination is null should not crash
  components/list/__tests__/pagination.test.js
  components/list/index.tsx
Labels: PR: unreviewed

#16233 docs: 3.16.5 changelog update
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#16235 fix: Select should trigger onSearch when search input is empty
  components/select/demo/search.md
  package.json
Labels: PR: unreviewed

#16238 fix: Select active item hover color is wrong
  components/select/style/index.less
Labels: PR: unreviewed

#16251 fix: remove active style from disabled Switch
  components/switch/style/index.less
Labels: PR: unreviewed

#16253 chore: add api collection script & update input-number doc
  components/input-number/index.en-US.md
  scripts/apiCollection.js
Labels: PR: unreviewed

#16130 fix: fix card mode Tabs border style when used with tabPosition="bottom"
  components/tabs/style/card-style.less
Labels: PR: unreviewed

#16123 feat: Make notification functions accept top, bottom and getContainer as arguments
  components/notification/__tests__/placement.test.js
  components/notification/index.en-US.md
  components/notification/index.tsx
  components/notification/index.zh-CN.md
Labels: PR: reviewed-approved

#15890 feat: Wrap List in `ul` for accessibility
  components/comment/__tests__/__snapshots__/demo.test.js.snap
  components/comment/demo/list.md
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/drawer/__tests__/__snapshots__/demo.test.js.snap
  components/list/Item.tsx
  components/list/__tests__/__snapshots__/Item.test.js.snap
  components/list/__tests__/__snapshots__/demo.test.js.snap
  components/list/__tests__/__snapshots__/pagination.test.js.snap
  components/list/index.tsx
  components/list/style/index.less
  components/skeleton/__tests__/__snapshots__/demo.test.js.snap
Labels: PR: reviewed-approved

#16093 Add Italian localization of Icon, Text and global components
  components/locale-provider/it_IT.tsx
Labels: PR: reviewed-changes-requested

#16172 Updates LocaleProvider italian language package
  components/locale-provider/it_IT.tsx
Labels: PR: unreviewed

#16228 feat: Drawer after visible change
  components/drawer/index.en-US.md
  components/drawer/index.tsx
  components/drawer/index.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#16266 fix: Small table header have background color
  components/table/style/size.less
Labels: PR: unreviewed

#16239 fix: List with actions style should be the right
  components/_util/reactNode.ts
  components/list/Item.tsx
  components/list/style/index.less
Labels: PR: unreviewed

#16267 modal title break word
  components/modal/style/modal.less
Labels: PR: unreviewed

#16275 fix: Typography.Title should also support `type`
  components/typography/style/index.less
Labels: PR: unreviewed

#16276 docs: add naming rules
  docs/react/contributing.en-US.md
  docs/react/contributing.zh-CN.md
Labels: PR: unreviewed

#16278 feat: add `htmlFor` in Form.Item
  components/form/FormItem.tsx
  components/form/__tests__/label.test.js
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: PR: reviewed-approved

#16281 fix: add check prepare to make Affix smooth in Safari
  components/affix/index.tsx
  components/affix/utils.ts
Labels: PR: reviewed-approved

#16272 fix: Tree checkbox animation not correct
  components/tree/style/index.less
Labels: PR: unreviewed

#16289 feat: Button support `link` type
  components/button/__tests__/__snapshots__/demo.test.js.snap
  components/button/button.tsx
  components/button/demo/basic.md
  components/button/demo/block.md
  components/button/demo/disabled.md
  components/button/demo/ghost.md
  components/button/demo/size.md
  components/button/index.en-US.md
  components/button/index.zh-CN.md
  components/button/style/index.less
  components/button/style/mixin.less
Labels: PR: reviewed-approved

#16304 fix: Calendar select option ellipsis when not in `fullscreen`
  components/calendar/style/index.less
Labels: PR: unreviewed

#16187 Back icon should is a button
  components/_util/transButton.tsx
  components/locale-provider/default.tsx
  components/locale-provider/zh_CN.tsx
  components/locale-provider/zh_TW.tsx
  components/page-header/__tests__/__snapshots__/demo.test.js.snap
  components/page-header/__tests__/index.test.js
  components/page-header/index.tsx
  components/page-header/style/index.less
  components/style/mixins/index.less
  components/style/mixins/operation-unit.less
  components/typography/__tests__/__snapshots__/demo.test.js.snap
  components/typography/style/index.less
Labels: PR: reviewed-approved

#16306 fix: Pagination active item should have background color
  components/style/themes/default.less
Labels: PR: unreviewed

#16307 fix: Typography edit mode should support `className`
  components/typography/Base.tsx
  components/typography/Editable.tsx
  components/typography/__tests__/index.test.js
Labels: PR: unreviewed

#16332 chore: Remove useless deps
  package.json
Labels: PR: unreviewed

#16195 Fix className prop issue when using Tooltip
  components/tooltip/index.tsx
Labels: PR: unreviewed

#16335 docs: 📝 changelog for 3.16.6
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/tooltip/index.tsx
  package.json
Labels: PR: unreviewed

#16341 RangePicker.renderExtraFooter() gets no args, fix TypeScript definition and clean up code
  components/date-picker/RangePicker.tsx
  components/date-picker/interface.tsx
Labels: PR: unreviewed

#16348 docs: Improve column.align document
  components/table/index.en-US.md
  components/table/index.zh-CN.md
Labels: PR: unreviewed

#16193 feat: Add Timeline.Item.position (#16148)
  components/timeline/Timeline.tsx
  components/timeline/TimelineItem.tsx
  components/timeline/index.en-US.md
  components/timeline/index.zh-CN.md
Labels: PR: reviewed-approved

#16043 fix: error types
  components/cascader/index.tsx
  components/config-provider/index.tsx
  components/dropdown/dropdown.tsx
  components/menu/index.tsx
  components/select/index.tsx
  components/table/interface.tsx
  components/time-picker/index.tsx
  components/tooltip/index.tsx
Labels: PR: unreviewed

#16356 test: Fix cascader test snapshot
  components/cascader/__tests__/__snapshots__/index.test.js.snap
Labels: PR: unreviewed

#16330 refactor: Update Tree & TreeSelect deps
  components/_util/motion.tsx
  components/_util/openAnimation.tsx
  components/style/core/motion.less
  components/tree/Tree.tsx
  components/tree/__tests__/__snapshots__/directory.test.js.snap
  components/tree/style/index.less
  package.json
Labels: PR: reviewed-approved

#16361 docs: Update collapse FAQ demo
  components/collapse/index.en-US.md
  components/collapse/index.zh-CN.md
Labels: PR: unreviewed

#16343 Form onFieldsChange(): document third parameter "allFields", remove non-existent fourth parameter "add" from TypeScript definition
  components/form/Form.tsx
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: PR: unreviewed

#15128 adjust slider text style
  components/slider/style/index.less
Labels: Inactive, PR: unreviewed

#16354 Merge master into feature
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/_util/colors.ts
  components/_util/transButton.tsx
  components/calendar/style/index.less
  components/cascader/__tests__/__snapshots__/index.test.js.snap
  components/cascader/index.tsx
  components/collapse/index.en-US.md
  components/collapse/index.zh-CN.md
  components/config-provider/index.tsx
  components/date-picker/RangePicker.tsx
  components/date-picker/interface.tsx
  components/dropdown/dropdown.tsx
  components/form/Form.tsx
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/locale-provider/default.tsx
  components/locale-provider/zh_CN.tsx
  components/locale-provider/zh_TW.tsx
  components/menu/index.tsx
  components/page-header/__tests__/__snapshots__/demo.test.js.snap
  components/page-header/__tests__/index.test.js
  components/page-header/index.tsx
  components/page-header/style/index.less
  components/select/index.tsx
  components/slider/style/index.less
  components/style/mixins/index.less
  components/style/mixins/operation-unit.less
  components/style/themes/default.less
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/table/interface.tsx
  components/time-picker/index.tsx
  components/tooltip/index.tsx
  components/typography/Base.tsx
  components/typography/Editable.tsx
  components/typography/__tests__/__snapshots__/demo.test.js.snap
  components/typography/__tests__/index.test.js
  components/typography/style/index.less
  package.json
Labels: PR: reviewed-approved

#16365 feat: Collapse support `expandIconPosition`
  components/collapse/Collapse.tsx
  components/collapse/__tests__/__snapshots__/demo.test.js.snap
  components/collapse/__tests__/__snapshots__/index.test.js.snap
  components/collapse/demo/extra.md
  components/collapse/index.en-US.md
  components/collapse/index.zh-CN.md
  components/collapse/style/index.less
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/style/themes/default.less
Labels: PR: reviewed-approved

#16315 feat: Breadcrumb support DropDown
  components/breadcrumb/Breadcrumb.tsx
  components/breadcrumb/BreadcrumbItem.tsx
  components/breadcrumb/__tests__/Breadcrumb.test.js
  components/breadcrumb/__tests__/__snapshots__/Breadcrumb.test.js.snap
  components/breadcrumb/__tests__/__snapshots__/demo.test.js.snap
  components/breadcrumb/__tests__/__snapshots__/router.test.js.snap
  components/breadcrumb/demo/basic.md
  components/breadcrumb/demo/overlay.md
  components/breadcrumb/demo/router.md
  components/breadcrumb/index.en-US.md
  components/breadcrumb/index.zh-CN.md
  components/breadcrumb/style/index.less
  components/breadcrumb/style/index.tsx
Labels: PR: reviewed-approved

#16360 fix: Upload types
  components/upload/index.tsx
  components/upload/interface.tsx
Labels: PR: unreviewed

#16369 feat: TreeNode support checkable
  components/tree/Tree.tsx
  components/tree/index.en-US.md
  components/tree/index.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#16370 fix: raf should keep same id
  components/_util/__tests__/util.test.js
  components/_util/raf.ts
Labels: PR: unreviewed

#16373 Update index.en-US.md
  components/input-number/index.en-US.md
Labels: PR: unreviewed

#16358 fix: 🐛 Drawer wrong animation direction
  components/drawer/style/drawer.less
Labels: PR: unreviewed

#16225 feat: add optional to support top and left slick dots (#16186)
  components/carousel/__tests__/__snapshots__/demo.test.js.snap
  components/carousel/__tests__/__snapshots__/index.test.js.snap
  components/carousel/__tests__/index.test.js
  components/carousel/demo/fade.md
  components/carousel/demo/position.md
  components/carousel/demo/vertical.md
  components/carousel/index.en-US.md
  components/carousel/index.tsx
  components/carousel/index.zh-CN.md
  components/carousel/style/index.less
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
Labels: PR: reviewed-approved

#16391 Fix some typos
  CHANGELOG.en-US.md
Labels: PR: unreviewed

#16390 chore: Improve upload demo
  components/upload/demo/avatar.md
  components/upload/demo/basic.md
  components/upload/demo/defaultFileList.md
  components/upload/demo/directory.md
  components/upload/demo/drag.md
  components/upload/demo/fileList.md
  components/upload/demo/picture-card.md
  components/upload/demo/picture-style.md
  components/upload/demo/upload-manually.md
Labels: PR: reviewed-approved

#16395 fix: 🐛 Fix AutoComplete align issue
  components/auto-complete/style/index.less
Labels: PR: unreviewed

#16392 fix: Checkbox.Group onChange should not pass removed value
  components/checkbox/Checkbox.tsx
  components/checkbox/Group.tsx
  components/checkbox/__tests__/group.test.js
Labels: PR: unreviewed
