Repository ant-design/ant-design, pull requests merged in 2019-12, with the labels that each got.

#19627 Update index.zh-CN.md CheckboxGroup
  components/checkbox/index.zh-CN.md
Labels: PR: unreviewed

#20026 docs: 3.26.0 change log
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed, documentation

#20018 feat: add visible debug demo
  site/theme/en-US.js
  site/theme/static/demo.less
  site/theme/template/Content/ComponentDoc.jsx
  site/theme/zh-CN.js
Labels: PR: unreviewed, enhancement

#20038 fix: List pagniation options text align
  components/list/style/index.less
Labels: PR: unreviewed, bug

#20015 chore: 更新Picker组件TypeScript声明
  .eslintrc.js
  components/date-picker/RangePicker.tsx
  components/date-picker/interface.tsx
Labels: PR: unreviewed, chore

#19898 feat: add skeleton avatar
  components/skeleton/Avatar.tsx
  components/skeleton/Button.tsx
  components/skeleton/Element.tsx
  components/skeleton/Skeleton.tsx
  components/skeleton/__tests__/__snapshots__/demo.test.js.snap
  components/skeleton/__tests__/__snapshots__/index.test.js.snap
  components/skeleton/__tests__/index.test.js
  components/skeleton/demo/button.md
  components/skeleton/index.en-US.md
  components/skeleton/index.tsx
  components/skeleton/index.zh-CN.md
  components/skeleton/style/index.less
Labels: PR: unreviewed, enhancement

#20057 chore: upgrade @typescript-eslint/parser
  package.json
Labels: PR: unreviewed, chore

#20059 fix: 🐛 Fix Button text not align center in Chrome
  components/button/style/index.less
Labels: PR: unreviewed, bug

#20068 chore: bump 4.0.0 alpha.12
  package.json
Labels: PR: reviewed-changes-requested, chore

#20067 fix: DescriptionItem className error to label
  components/descriptions/Col.tsx
  components/descriptions/__tests__/__snapshots__/index.test.js.snap
Labels: PR: unreviewed, bug

#20069 chore: 🔧 remove antd/es/form/__tests__ from npm package
  components/form/__tests__/type.test.tsx
Labels: PR: unreviewed, chore

#20071 ci: fix test coverage
  .eslintignore
  .jest.js
  components/form/__tests__/index.test.js
Labels: PR: reviewed-changes-requested, PR: unreviewed, ci

#20086 chore: 📖 fix site scrollbar problem
  site/theme/static/common.less
Labels: PR: unreviewed, chore

#20070 fix: dark theme components
  .antd-tools.config.js
  components/button/style/mixin.less
  components/cascader/style/index.less
  components/input/style/index.less
  components/input/style/search-input.less
  components/modal/style/modal.less
  components/progress/Circle.tsx
  components/progress/__tests__/__snapshots__/demo.test.js.snap
  components/select/style/index.less
  components/skeleton/style/index.less
  components/style/themes/dark.less
  components/style/themes/default.less
  components/table/style/index.less
  components/transfer/style/index.less
  docs/react/customize-theme.en-US.md
  docs/react/customize-theme.zh-CN.md
  package.json
  tests/dekko/dist.test.js
Labels: PR: unreviewed, bug

#20087 chore: stripPrefix false
  .antd-tools.config.js
Labels: PR: reviewed-changes-requested, chore

#19986 fix: 🐛 Table column align in windows chrome
  components/table/style/index.less
  package.json
Labels: PR: unreviewed, bug

#20089 feat: export FormItemProps interface
  components/form/FormItem.tsx
Labels: PR: unreviewed, enhancement

#20102 fix: 🐛 duplicated icons when Tree showLine is true
  components/tree/Tree.tsx
  components/tree/__tests__/__snapshots__/index.test.js.snap
  components/tree/__tests__/index.test.js
  components/tree/demo/line.md
Labels: PR: unreviewed, bug

#20111 feat: export interface
  components/typography/Paragraph.tsx
  components/typography/Title.tsx
Labels: PR: unreviewed, enhancement

#20119 test: Add lighthouse-ci action
  .github/workflows/lighthouse-ci.yml
Labels: PR: unreviewed, test

#20120 docs: 📖 improve create-react-app documentation
  docs/react/use-in-typescript.en-US.md
  docs/react/use-in-typescript.zh-CN.md
  docs/react/use-with-create-react-app.en-US.md
  docs/react/use-with-create-react-app.zh-CN.md
Labels: PR: unreviewed, documentation

#20095 fix: dark theme in 4.0
  .antd-tools.config.js
  components/style/themes/dark.less
Labels: 4.0, PR: unreviewed, bug

#20115 Docs: fix table demo typing error
  components/table/demo/head.md
Labels: Docs, PR: unreviewed

#20121 feat: export interface
  components/form/Form.tsx
Labels: PR: unreviewed, enhancement

#20117 chore: add entry to dist css files for the dark theme
  index-dark.js
  package.json
  webpack.config.js
Labels: 4.0, PR: unreviewed, chore

#20127 chore: use dark-theme.js, antd.dark.less and css
  .antd-tools.config.js
  docs/react/customize-theme.en-US.md
  docs/react/customize-theme.zh-CN.md
  tests/dekko/dist.test.js
Labels: PR: unreviewed

#20130 fix: rename @gray-11 to @popover-background
  components/style/themes/dark.less
  components/style/themes/default.less
  components/table/style/index.less
Labels: 4.0, PR: reviewed-approved, PR: unreviewed, bug

#20133 chore: update 4.0.0-alpha.14
  package.json
Labels: PR: unreviewed, chore

#20140 add 3.6.1 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed, needs-more-info

#20144 When using the render property to customize the title, the title prop…
  components/transfer/index.tsx
Labels: PR: unreviewed

#20145 docs: 📖 Add docs for ConfigProvider getPopupContainer
  components/config-provider/index.en-US.md
  components/config-provider/index.zh-CN.md
Labels: PR: unreviewed, documentation

#20153 fix: "disabledTime" property type in date-picker
  components/date-picker/interface.tsx
Labels: PR: unreviewed, bug

#20158 docs: ✨ bump 3.26.2
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed, documentation

#20164 fix: Overlapping graphics with two icons in form elements
  components/form/style/index.less
Labels: PR: unreviewed, bug

#20156 style: less variables for cascader, dropdown, and select
  components/cascader/style/index.less
  components/dropdown/style/index.less
  components/select/style/index.less
  components/style/themes/default.less
Labels: PR: unreviewed, style

#20187 fix: table should not show sorter when sorter is falsy
  components/table/__tests__/Table.sorter.test.js
  components/table/hooks/useSorter.tsx
Labels: PR: reviewed-changes-requested, bug

#19923 feat: ⚡️ Alert.ErrorBoundary
  components/alert/ErrorBoundary.tsx
  components/alert/__tests__/__snapshots__/demo.test.js.snap
  components/alert/__tests__/__snapshots__/index.test.js.snap
  components/alert/__tests__/index.test.js
  components/alert/demo/error-boundary.md
  components/alert/index.en-US.md
  components/alert/index.tsx
  components/alert/index.zh-CN.md
  components/alert/style/index.less
  site/theme/template/Content/Demo/index.jsx
  site/theme/template/Content/ErrorBoundary.js
Labels: 4.0, PR: reviewed-approved, PR: unreviewed, enhancement, zap

#20088 [4.0] feat(table): Add defaultFilteredValues to table columns
  components/table/__tests__/Table.filter.test.js
  components/table/hooks/useFilter/index.tsx
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/table/interface.tsx
Labels: 4.0, PR: reviewed-changes-requested, enhancement

#20190 fix: fix type of OptionProps
  components/select/index.tsx
Labels: PR: unreviewed, bug

#20191 feat: Warning invalidate element when using `name`.
  components/form/FormItem.tsx
  components/form/__tests__/index.test.js
Labels: PR: reviewed-changes-requested, enhancement

#20193 chore: 🔧 Add unpkg field in package.json
  package.json
Labels: PR: unreviewed, chore

#19179 refactor: upgrade rc-trigger
  package.json
  typings/custom-typings.d.ts
Labels: PR: unreviewed, refactor

#20204 docs: Update Table scroll docs
  components/table/demo/fixed-columns.md
  components/table/index.en-US.md
  components/table/index.zh-CN.md
Labels: PR: unreviewed, documentation

#20207 fix: required support dynamic updated rules
  components/form/FormItem.tsx
  components/form/__tests__/index.test.js
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: PR: reviewed-changes-requested, bug

#20208 docs: Update Tree docs
  components/tree/index.en-US.md
  components/tree/index.zh-CN.md
Labels: PR: unreviewed, documentation

#20226 feat/add warning for icon props
  components/avatar/__tests__/Avatar.test.js
  components/avatar/index.tsx
  components/button/__tests__/index.test.js
  components/button/button.tsx
  components/modal/__tests__/confirm.test.js
  components/modal/confirm.tsx
  components/result/__tests__/index.test.js
  components/result/index.tsx
Labels: PR: unreviewed, WIP

#20216 fix: Form.Item align style
  components/form/style/index.less
  components/style/themes/default.less
Labels: PR: reviewed-approved, bug

#20234 docs: fixed reproduce logic
  site/bisheng.config.js
  site/theme/template/Content/Demo/index.jsx
Labels: PR: reviewed-changes-requested, documentation

#20212 docs: copy state to props is a bad practice
  components/form/demo/customized-form-controls.md
Labels: PR: unreviewed, documentation

#20242 fix: Modal combine Drawer cause overflow invalid
  package.json
Labels: PR: unreviewed, bug

#20251 docs: Add link of "Install and Initialization" to Getting started
  docs/react/getting-started.en-US.md
Labels: PR: unreviewed

#20258 docs: ✨ Release 3.26.3
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed, documentation

#20260 chore: 🔧 fix gh-pages actions
  .github/workflows/deploy-site.yml
Labels: PR: unreviewed, chore

#20235 fix: Form layout recommend vertical
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/demo/basic.md
  components/form/demo/control-hooks.md
  components/form/demo/control-ref.md
  components/form/demo/dynamic-rule.md
  components/form/demo/register.md
  components/form/demo/time-related-controls.md
  components/form/demo/validate-other.md
  components/form/demo/validate-static.md
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: 4.0, PR: unreviewed, bug

#20274 fix: 🐛 TreeNode without icon white block
  components/tree/style/index.less
Labels: PR: unreviewed, bug

#20283 fix: Tabs ink bar missing transition animation
  components/tabs/style/index.less
Labels: PR: unreviewed, bug

#20298 fix: 4.0 table demo ts to js no work
  components/table/demo/virtual-list.md
Labels: PR: unreviewed, bug

#20135 docs: Add contributors list in each documentation
  package.json
  site/theme/en-US.js
  site/theme/static/common.less
  site/theme/static/contributors.less
  site/theme/static/index.less
  site/theme/template/Content/MainContent.jsx
  site/theme/zh-CN.js
Labels: PR: unreviewed, Site, documentation

#20178 doc/v4 codemod
  docs/react/contributing.en-US.md
  docs/react/contributing.zh-CN.md
  docs/react/customize-theme.en-US.md
  docs/react/customize-theme.zh-CN.md
  docs/react/faq.en-US.md
  docs/react/faq.zh-CN.md
  docs/react/getting-started.en-US.md
  docs/react/getting-started.zh-CN.md
  docs/react/i18n.en-US.md
  docs/react/i18n.zh-CN.md
  docs/react/migration-v4.en-US.md
  docs/react/migration-v4.zh-CN.md
  docs/react/practical-projects.en-US.md
  docs/react/practical-projects.zh-CN.md
  docs/react/recommendation.en-US.md
  docs/react/recommendation.zh-CN.md
  docs/react/use-in-typescript.en-US.md
  docs/react/use-in-typescript.zh-CN.md
  docs/react/use-with-create-react-app.en-US.md
  docs/react/use-with-create-react-app.zh-CN.md
Labels: PR: unreviewed

#20316 docs: 📝 Description List => Descriptions
  components/descriptions/index.en-US.md
  scripts/check-site.js
Labels: PR: unreviewed, documentation

#20318 fix: 🐛 Alert description wrapping
  components/alert/ErrorBoundary.tsx
  components/alert/__tests__/__snapshots__/index.test.js.snap
  components/alert/style/index.less
Labels: PR: unreviewed, bug

#20320 chore: 🔧 remove css-split-webpack-plugin
  site/bisheng.config.js
Labels: PR: reviewed-changes-requested, chore

#20325 fix: 💄 optimize Steps labelPlacement vertical UI
  components/steps/style/index.less
  components/steps/style/label-placement.less
Labels: PR: unreviewed, bug

#20309 feat: form demo important tip using popover
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/demo/validate-static.md
Labels: 4.0, PR: unreviewed, enhancement

#20308 fix: form demo use placeholder
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/demo/basic.md
  components/form/demo/control-hooks.md
  components/form/demo/control-ref.md
  components/form/demo/form-context.md
  components/form/demo/nest-messages.md
  components/form/demo/register.md
  components/form/demo/validate-static.md
  components/select/__tests__/__snapshots__/demo.test.js.snap
  components/select/demo/automatic-tokenization.md
Labels: PR: unreviewed, bug

#20336 fix: dark css dist error caused by variables
  index-dark.js
  webpack.config.js
Labels: 4.0, PR: reviewed-changes-requested, bug

#20263 feat: add hideRequiredMark attribute types and add demo
  components/form/Form.tsx
  components/form/FormItemLabel.tsx
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/context.tsx
  components/form/demo/hide-required-mark.md
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/form/style/index.less
  components/locale/default.tsx
  components/locale/zh_CN.tsx
Labels: PR: unreviewed, enhancement

#20337 fix: filters define error in onChange
  components/table/interface.tsx
Labels: PR: unreviewed, bug

#20338 Fix/poweroff in btn
  components/button/__tests__/__snapshots__/demo.test.js.snap
  components/button/demo/loading.md
Labels: PR: unreviewed

#20264 feat: add Input element for Skeleton
  components/skeleton/Input.tsx
  components/skeleton/Skeleton.tsx
  components/skeleton/__tests__/__snapshots__/demo.test.js.snap
  components/skeleton/__tests__/__snapshots__/index.test.js.snap
  components/skeleton/__tests__/index.test.js
  components/skeleton/demo/element.md
  components/skeleton/index.en-US.md
  components/skeleton/index.tsx
  components/skeleton/index.zh-CN.md
  components/skeleton/style/index.less
Labels: PR: unreviewed, enhancement

#20332 fix: Disallow auto focus input after triggering "onSearch" event in m…
  components/input/Search.tsx
  package.json
Labels: PR: unreviewed, bug

#20330 docs: components and documentation in two pages
  docs/react/migration-v4.en-US.md
  docs/react/migration-v4.zh-CN.md
  site/theme/en-US.js
  site/theme/static/common.less
  site/theme/template/Content/MainContent.jsx
  site/theme/template/Layout/Header.jsx
  site/theme/template/utils.jsx
  site/theme/zh-CN.js
Labels: PR: unreviewed, documentation

#20341 docs: Update TreeSelect docs
  components/tree-select/index.en-US.md
  components/tree-select/index.zh-CN.md
Labels: PR: unreviewed, documentation

#20345 fix: Form select error style
  components/form/style/index.less
Labels: PR: unreviewed, bug

#20346 fix: datePicker popup z-index should over modal
  components/date-picker/style/index.less
Labels: PR: unreviewed, bug

#20347 fix: cascader error color
  components/form/style/index.less
Labels: PR: unreviewed, bug

#20350 4.0 table
  components/table/style/index.less
Labels: PR: unreviewed

#20355 fix: 🐛 Tag onClick triggered when close
  components/tag/__tests__/index.test.js
  components/tag/index.tsx
Labels: PR: reviewed-changes-requested, bug

#20364 chore: 📝 improve docs and config json
  .codesandbox/ci.json
  AUTHORS.txt
  components/spin/index.en-US.md
  components/spin/index.zh-CN.md
  docs/react/customize-theme.en-US.md
  docs/react/faq.en-US.md
  docs/react/faq.zh-CN.md
  docs/react/getting-started.en-US.md
  docs/react/getting-started.zh-CN.md
  docs/react/i18n.en-US.md
  docs/react/i18n.zh-CN.md
  renovate.json
  site/theme/static/index.less
Labels: PR: unreviewed, chore

#20363 fix(Form): feedback icon with input suffix display not correct
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/demo/validate-static.md
  components/form/style/index.less
Labels: PR: unreviewed, bug

#20232 fix: Select empty style & default width
  components/form/style/index.less
  components/select/style/index.less
  package.json
  site/theme/template/Layout/Header.jsx
Labels: PR: reviewed-approved, bug

#20300 refactor(Button): base style use flex
  components/auto-complete/__tests__/__snapshots__/demo.test.js.snap
  components/auto-complete/demo/form-debug.md
  components/button/style/mixin.less
  components/style/themes/default.less
Labels: PR: unreviewed, refactor

#20375 fix: upload preview not support ico file type issue(#20360)
  components/upload/__tests__/upload.test.js
  components/upload/utils.tsx
Labels: PR: unreviewed, bug

#20381 docs: Correct Grammar in Form Component's Documentation
  AUTHORS.txt
  components/form/demo/inline-login.md
Labels: PR: unreviewed, documentation

#20382 Update index.zh-CN.md
  components/typography/index.zh-CN.md
Labels: PR: unreviewed

#20379 docs: 3.26.4 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed, documentation

#20387 fix: Adjust Select style
  components/list/__tests__/__snapshots__/pagination.test.js.snap
  components/list/__tests__/pagination.test.js
  components/select/demo/option-label-prop.md
  components/select/style/index.less
  components/select/style/multiple.less
  package.json
Labels: PR: unreviewed, bug

#20400 fix: responsiveObserve init miss sizing
  components/_util/responsiveObserve.ts
  components/descriptions/__tests__/index.test.js
  components/grid/__tests__/index.test.js
  tests/setup.js
Labels: PR: unreviewed, bug

#20402 docs: Update TreeSelect docs
  components/tree-select/index.en-US.md
  components/tree-select/index.zh-CN.md
Labels: PR: unreviewed, documentation

#20224 feat: Typography add suffix
  components/typography/Base.tsx
  components/typography/__tests__/__snapshots__/demo.test.js.snap
  components/typography/__tests__/index.test.js
  components/typography/demo/suffix.md
  components/typography/index.en-US.md
  components/typography/index.zh-CN.md
  components/typography/util.tsx
Labels: PR: unreviewed, enhancement

#20395 docs: add #20325 in 3.26.4 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed, documentation

#20413 docs: fix change log time error
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed, documentation

#20406 feat: Form list add move typescript
  components/form/FormList.tsx
Labels: PR: unreviewed, enhancement

#20427 feat: update @ant-design/icons@4.0.0-alpha.13
  components/collapse/__tests__/__snapshots__/demo.test.js.snap
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/input/__tests__/__snapshots__/Password.test.js.snap
  components/input/__tests__/__snapshots__/index.test.js.snap
  components/table/__tests__/__snapshots__/Table.sorter.test.js.snap
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/transfer/__tests__/__snapshots__/demo.test.js.snap
  components/transfer/__tests__/__snapshots__/index.test.js.snap
  components/transfer/__tests__/__snapshots__/search.test.js.snap
  components/tree/__tests__/__snapshots__/demo.test.js.snap
  components/tree/__tests__/__snapshots__/directory.test.js.snap
Labels: PR: unreviewed, enhancement

#20417 fix: tab bar animated style
  components/tabs/style/index.less
Labels: PR: unreviewed, bug

#20434 chore: Bundle size opt
  .npmignore
  package.json
  webpack.config.js
Labels: PR: reviewed-changes-requested, chore

#20435 chore: Update picker deps
  package.json
Labels: PR: unreviewed, chore

#20439 chore: TimePicker types
  components/time-picker/index.tsx
Labels: PR: unreviewed, chore

#20440 refactor(Button): Back to inline-block
  components/button/style/mixin.less
Labels: PR: unreviewed, refactor

#20443 chore: Update rc-field-form deps
  package.json
Labels: PR: unreviewed, chore

#20436 perf: optimize bundlesize
  components/carousel/index.tsx
  package.json
  webpack.config.js
Labels: PR: unreviewed, needs-more-info, performance

#20384 fix: datePicker size
  components/date-picker/style/index.less
Labels: PR: unreviewed, bug

#20408 feat: TextArea add support onResize
  components/input/ResizableTextArea.tsx
  components/input/TextArea.tsx
  components/input/__tests__/index.test.js
  components/input/index.en-US.md
  components/input/index.zh-CN.md
Labels: PR: unreviewed, enhancement

#20451 feat: update to @ant-design/icons@4.0.0-alpha.16
  components/collapse/__tests__/__snapshots__/demo.test.js.snap
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/input/__tests__/__snapshots__/Password.test.js.snap
  components/input/__tests__/__snapshots__/index.test.js.snap
  components/table/__tests__/__snapshots__/Table.sorter.test.js.snap
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/transfer/__tests__/__snapshots__/demo.test.js.snap
  components/transfer/__tests__/__snapshots__/index.test.js.snap
  components/transfer/__tests__/__snapshots__/search.test.js.snap
  components/tree/__tests__/__snapshots__/demo.test.js.snap
  components/tree/__tests__/__snapshots__/directory.test.js.snap
  package.json
Labels: PR: unreviewed, enhancement

#20456 fix: TreeNode has wrong indent
  components/tree/style/index.less
Labels: PR: unreviewed, bug

#20458 docs: Update draggable.md
  components/tree/demo/draggable.md
Labels: PR: unreviewed, documentation

#20460 chore: docs upgrade
  README-zh_CN.md
  components/card/index.en-US.md
  components/card/index.zh-CN.md
  components/input/index.en-US.md
  components/input/index.zh-CN.md
  components/menu/index.en-US.md
  components/menu/index.zh-CN.md
  components/pagination/index.en-US.md
  components/pagination/index.zh-CN.md
  components/select/index.en-US.md
Labels: PR: unreviewed, chore

#20457 fix: IME should work in safari
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/form/FormItemInput.tsx
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/__tests__/index.test.js
  components/form/util.ts
  package.json
Labels: PR: unreviewed, bug

#20463 fix: Table header text align when colspan=1
  components/table/style/index.less
Labels: PR: unreviewed, bug

#20467 upd: version 4.0.0-beta.1
  components/progress/Steps.tsx
  package.json
Labels: 4.0

#20468 feat: prefetch speed up dark.css load
  site/theme/static/template.html
Labels: 4.0, Site

#20477 fix: site icons category issue
  site/theme/template/IconDisplay/fields.ts
  site/theme/template/IconDisplay/index.tsx
Labels: PR: reviewed-changes-requested, bug

#20484 fix: dark theme review
  components/button/style/mixin.less
  components/card/style/index.less
  site/theme/static/highlight.less
Labels: 4.0, PR: unreviewed, bug

#20488 test: Merge master to fix test snapshots
  components/table/style/index.less
  components/tree/demo/draggable.md
  components/tree/style/index.less
  docs/react/faq.zh-CN.md
Labels: PR: unreviewed, needs-more-info, test

#20489 fix: Should also set className with customize `help`
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/form/FormItem.tsx
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/__tests__/index.test.js
Labels: PR: reviewed-approved, bug

#20492 docs: Add form demo
  components/form/__tests__/demo.test.js
  components/form/demo/complex-form-control.md
  components/form/demo/customized-form-controls.md
  site/theme/static/demo.less
  site/theme/static/header.less
Labels: PR: unreviewed, documentation

#20500 fix: dark site theme
  site/theme/static/dark.less
  site/theme/static/demo.less
  site/theme/static/docsearch.less
  site/theme/static/header.less
  site/theme/static/highlight.less
  site/theme/static/icons.less
  site/theme/static/index.less
  site/theme/static/markdown.less
  site/theme/static/mock-browser.less
  site/theme/static/page-nav.less
  site/theme/static/toc.less
Labels: 4.0, PR: unreviewed, bug

#20486 docs: Update 4.0 site
  docs/spec/alignment.en-US.md
  docs/spec/alignment.zh-CN.md
  docs/spec/cases.zh-CN.md
  docs/spec/colors.en-US.md
  docs/spec/colors.zh-CN.md
  docs/spec/contrast.en-US.md
  docs/spec/contrast.zh-CN.md
  docs/spec/copywriting.md
  docs/spec/data-display.en-US.md
  docs/spec/data-display.zh-CN.md
  docs/spec/data-entry.en-US.md
  docs/spec/data-entry.zh-CN.md
  docs/spec/direct.en-US.md
  docs/spec/direct.zh-CN.md
  docs/spec/font.en-US.md
  docs/spec/font.zh-CN.md
  docs/spec/icon.en-US.md
  docs/spec/illustration.zh-CN.md
  docs/spec/introduce.en-US.md
  docs/spec/introduce.zh-CN.md
  docs/spec/invitation.zh-CN.md
  docs/spec/layout.en-US.md
  docs/spec/layout.zh-CN.md
  docs/spec/lightweight.zh-CN.md
  docs/spec/overview.zh-CN.md
  docs/spec/proximity.en-US.md
  docs/spec/proximity.zh-CN.md
  docs/spec/reaction.zh-CN.md
  docs/spec/reference.zh-CN.md
  docs/spec/stay.zh-CN.md
  docs/spec/transition.zh-CN.md
  docs/spec/values.en-US.md
  docs/spec/values.zh-CN.md
  docs/spec/visual.zh-CN.md
  site/bisheng.config.js
  site/theme/en-US.js
  site/theme/static/header.less
  site/theme/template/Home/DesignPage/Natural.tsx
  site/theme/template/Home/DesignPage/index.less
  site/theme/template/Home/index.less
  site/theme/template/Layout/Header.jsx
Labels: PR: unreviewed, documentation

#20509 fix: Table getPopupContainer should work
  components/table/__tests__/Table.filter.test.js
  components/table/__tests__/__snapshots__/Table.filter.test.js.snap
  components/table/hooks/useFilter/FilterDropdown.tsx
Labels: PR: reviewed-changes-requested, bug

#20512 fix: FormItem errors should show in diff line
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/form/FormItemInput.tsx
  components/form/__tests__/__snapshots__/demo.test.js.snap
Labels: PR: unreviewed, bug

#20504 fix: select icon on hover & focus in input.group
  components/input/style/mixin.less
Labels: PR: unreviewed, bug

#20507 fix: revert Table return first page after sort
  components/table/Table.tsx
  components/table/__tests__/Table.sorter.test.js
Labels: PR: unreviewed, bug

#20506 fix: padding right for select[size=small]
  components/select/style/single.less
Labels: PR: unreviewed, bug

#20516 fix: form dark theme
  site/theme/static/dark.less
Labels: 4.0, PR: unreviewed, bug

#20521 docs: Update demo error message
  components/form/demo/basic.md
Labels: PR: unreviewed, documentation

#20520 docs: Add the changelog of 3.26.5
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: reviewed-approved, documentation

#20527 chore: Add warning when use remove function
  components/form/__tests__/index.test.js
  components/form/index.tsx
Labels: PR: reviewed-changes-requested, chore

#20524 docs: Update form demo to remove defaultValue
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/demo/layout.md
  components/form/demo/validate-static.md
Labels: PR: unreviewed, documentation

#20532 fix: Table with invalidate pagination total should ignore
  components/table/__tests__/Table.pagination.test.js
  components/table/hooks/usePagination.ts
Labels: PR: reviewed-changes-requested, bug

#20533 style: Tweak Radio.Group inconsistant style
  components/radio/style/index.less
Labels: PR: unreviewed, style

#20535 chore: dev mode always show debug default
  site/theme/template/Content/ComponentDoc.jsx
Labels: PR: unreviewed, chore

#20545 fix: Improve Steps `type="navigation"` UI in small screen
  components/steps/style/nav.less
Labels: PR: unreviewed, bug

#20546 fix: use Object.prototype.toString to check object
  components/message/__tests__/index.test.js
  components/message/index.tsx
Labels: PR: unreviewed, bug

#20538 fix: Select use value width instead of default fixed width
  components/select/__tests__/__snapshots__/demo.test.js.snap
  components/select/demo/debug.md
  components/select/style/index.less
  components/select/style/single.less
  site/theme/template/Home/MorePage.less
  site/theme/template/Layout/Header.jsx
Labels: PR: unreviewed, bug

#20517 fix(style): form field error border style for select
  components/form/style/index.less
Labels: PR: unreviewed, bug

#20552 docs: Fix image misplacing
  docs/spec/reaction.en-US.md
Labels: PR: unreviewed, documentation

#20556 docs: Fix mobile logo collapsed
  site/theme/static/header.less
  site/theme/static/responsive.less
Labels: PR: unreviewed, documentation

#20560 chore: 🆙 upgrade bisheng
  package.json
Labels: PR: unreviewed, chore

#20561 style: 💄 optimize card hoverable style
  components/card/style/index.less
Labels: PR: unreviewed, style

#20544 fix: 💄 Remove Input.Password value attribute from dom
  components/input/Input.tsx
  components/input/Password.tsx
  components/input/__tests__/Password.test.js
Labels: PR: unreviewed, bug

#20562 test: 💄 fix stylelint warnings and errors
  .stylelintrc.json
  components/calendar/style/index.less
  components/date-picker/style/index.less
  components/date-picker/style/panel.less
  components/table/style/index.less
  components/table/style/radius.less
Labels: PR: unreviewed, test

#20565 fix: Tree missing aniation when virtual scrolled
  components/tree/Tree.tsx
  components/tree/__tests__/demo.test.js
  components/tree/demo/big-data.md
Labels: PR: unreviewed, bug

#20555 fix: site dark tweak style
  components/button/index.en-US.md
  components/button/index.zh-CN.md
  components/button/style/mixin.less
  components/date-picker/style/index.less
  components/style/themes/dark.less
  components/style/themes/default.less
  components/table/demo/summary.md
  components/tag/demo/colorful.md
  components/transfer/style/customize.less
  package.json
  site/theme/static/common.less
  site/theme/template/Content/MainContent.jsx
  site/theme/template/Home/Banner/index.less
  site/theme/template/Home/index.less
Labels: 4.0, PR: unreviewed, bug

#20569 docs: Update values page
  docs/spec/values.zh-CN.md
Labels: PR: unreviewed, documentation

#20554 fix: some typescript definition errors
  components/form/FormItem.tsx
Labels: PR: unreviewed, bug
