Repository ant-design/ant-design, pull requests merged in 2019-05, with the labels that each got.

#16340 fix: Allow Object.entries (only for type checks, this is not a polyfill)
  tsconfig.json
Labels: PR: unreviewed

#16398 fix: username misspelling in the form.
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/demo/horizontal-login.md
  components/form/demo/normal-login.md
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: PR: unreviewed

#16342 fix: Add some missing TypeScript prop definititions and clean up date-picker definitions
  components/checkbox/Checkbox.tsx
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
  components/date-picker/interface.tsx
  components/switch/index.tsx
  components/tooltip/index.tsx
Labels: PR: unreviewed

#16344 fix: TypeScript definitions for Select component's onSelect / onDeselect props, update inaccurate docs
  components/select/index.en-US.md
  components/select/index.tsx
  components/select/index.zh-CN.md
Labels: PR: unreviewed

#16402 refactor: Upgrade `rc-tree-select` to support pure React motion
  components/tree-select/__tests__/__snapshots__/demo.test.js.snap
  package.json
Labels: PR: unreviewed

#16026 feat: Support Transfer render
  components/style/themes/default.less
  components/transfer/ListItem.tsx
  components/transfer/__tests__/__snapshots__/demo.test.js.snap
  components/transfer/__tests__/__snapshots__/list.test.js.snap
  components/transfer/__tests__/__snapshots__/search.test.js.snap
  components/transfer/__tests__/customize.test.js
  components/transfer/__tests__/index.test.js
  components/transfer/__tests__/list.test.js
  components/transfer/__tests__/search.test.js
  components/transfer/demo/table-transfer.md
  components/transfer/demo/tree-transfer.md
  components/transfer/index.en-US.md
  components/transfer/index.tsx
  components/transfer/index.zh-CN.md
  components/transfer/list.tsx
  components/transfer/renderListBody.tsx
  components/transfer/style/customize.less
  components/transfer/style/index.less
Labels: PR: unreviewed

#16244 refactor: Render function size reduce
  components/transfer/list.tsx
Labels: PR: unreviewed

#16397 Fix hoist-non-react-statics compilation error
  components/form/interface.ts
  package.json
Labels: PR: unreviewed

#16534 docs: 📝 changelog for 3.17.1
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#16545 docs: Fix theme less file load doc
  components/style/themes/index.less
  components/style/themes/override.less
  docs/react/customize-theme.en-US.md
  docs/react/customize-theme.zh-CN.md
Labels: PR: unreviewed

#16539 docs: changelog for 3.18.0
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#16556 chore: update snapshot
  components/table/__tests__/__snapshots__/demo.test.js.snap
  package.json
Labels: PR: unreviewed

#16559 docs: Add changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#16564 Update package.json
  package.json
Labels: PR: unreviewed

#16567 chore: feature merge master
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/style/themes/index.less
  components/style/themes/override.less
  components/table/__tests__/__snapshots__/demo.test.js.snap
  docs/react/customize-theme.en-US.md
  docs/react/customize-theme.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#16550 fix children's type of interface Route
  components/breadcrumb/Breadcrumb.tsx
Labels: PR: unreviewed

#16569 fix: Spin size not correct when set `fontSize`
  components/spin/style/index.less
Labels: PR: unreviewed

#16584 Prevent negative margin-bottom for form items with help (e.g. validation errors)
  components/form/style/index.less
Labels: PR: unreviewed

#16586 test: ✅ Fix snapshots
  components/table/__tests__/__snapshots__/demo.test.js.snap
Labels: PR: unreviewed

#16592 fix: Call Carousel force update when children lenght changed
  components/carousel/__tests__/index.test.js
  components/carousel/index.tsx
Labels: PR: unreviewed

#16594 fix: Update List typescript definition
  components/list/index.tsx
Labels: PR: unreviewed

#16577 fix(Form): improve onFieldsChange params type defs
  components/form/Form.tsx
Labels: PR: unreviewed

#16597 Update use-in-typescript.zh-CN.md
  docs/react/use-in-typescript.zh-CN.md
Labels: PR: unreviewed

#16619 docs: Change changelog format in PR template
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/pr_cn.md
Labels: PR: unreviewed

#16616 fix: 🐞 Fix selectedRows missing when there is childrenColumnName in Table
  components/table/Table.tsx
  components/table/__tests__/Table.rowSelection.test.js
Labels: PR: unreviewed

#16621 Update index.zh-CN.md
  components/select/index.zh-CN.md
Labels: PR: unreviewed

#16615 chore: Fix affix navigator lost current class after click hashtag anchor.
  docs/react/use-in-typescript.en-US.md
  docs/react/use-in-typescript.zh-CN.md
  site/theme/template/Content/Article.jsx
  site/theme/template/Content/ComponentDoc.jsx
  site/theme/template/Content/MainContent.jsx
Labels: PR: unreviewed

#16623 docs: Update icons list logic
  site/theme/template/IconDisplay/fields.ts
  site/theme/template/IconDisplay/index.tsx
Labels: PR: reviewed-approved

#16624 Fix incorrect tree type
  components/tree/Tree.tsx
Labels: PR: unreviewed

#16637 Fix docs
  components/breadcrumb/index.zh-CN.md
Labels: PR: unreviewed

#16639 Format
  components/tree/Tree.tsx
Labels: PR: unreviewed

#16638 fix: Tree.onDragEnter function parameter
  components/tree/Tree.tsx
Labels: PR: reviewed-approved

#16643 fix close animation
  components/drawer/style/drawer.less
Labels: PR: unreviewed

#16551 fix: Space missing in button
  components/button/__tests__/__snapshots__/index.test.js.snap
  components/button/__tests__/index.test.js
  components/button/button.tsx
  components/input/__tests__/__snapshots__/demo.test.js.snap
Labels: PR: reviewed-approved

#16532 feat: Add Mentions component
  components/__tests__/__snapshots__/index.test.js.snap
  components/config-provider/renderEmpty.tsx
  components/form/style/index.less
  components/index.tsx
  components/mention/index.en-US.md
  components/mention/index.tsx
  components/mention/index.zh-CN.md
  components/mentions/__tests__/__snapshots__/demo.test.js.snap
  components/mentions/__tests__/demo.test.js
  components/mentions/__tests__/index.test.js
  components/mentions/demo/async.md
  components/mentions/demo/basic.md
  components/mentions/demo/form.md
  components/mentions/demo/placement.md
  components/mentions/demo/prefix.md
  components/mentions/demo/readonly.md
  components/mentions/index.en-US.md
  components/mentions/index.tsx
  components/mentions/index.zh-CN.md
  components/mentions/style/index.less
  components/mentions/style/index.tsx
  package.json
  site/bisheng.config.js
  tests/__snapshots__/index.test.js.snap
Labels: PR: reviewed-approved

#16646 style: unified Cascader selected style with Select
  components/cascader/style/index.less
Labels: PR: unreviewed

#16666 docs: Add the changelog of 3.18.2
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: reviewed-approved

#16681 Refined translation of St.Exupery quote
  docs/spec/values.en-US.md
Labels: PR: reviewed-approved

#16684 fix horizontal divider style
  components/page-header/style/index.less
Labels: PR: unreviewed

#16712 fix shouldComponentUpdate
  site/theme/template/Content/ComponentDoc.jsx
Labels: PR: unreviewed

#16570 fix: Upload prop onRemove: allow Promise as return type
  components/upload/interface.tsx
Labels: PR: unreviewed

#16716 fix: Upload prop action: fix typings
  components/upload/interface.tsx
Labels: PR: unreviewed

#16727 chore: some documents style
  components/tabs/__tests__/__snapshots__/demo.test.js.snap
  components/tabs/demo/slide.md
  docs/react/customize-theme.en-US.md
  docs/react/customize-theme.zh-CN.md
  site/theme/template/IconDisplay/index.tsx
Labels: PR: unreviewed

#16694 feat: support pressing ESC to close drawer
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/drawer/__tests__/__snapshots__/Drawer.test.js.snap
  components/drawer/__tests__/__snapshots__/DrawerEvent.test.js.snap
  components/drawer/index.tsx
  package.json
Labels: PR: reviewed-approved

#16737 docs: Add select optionLabelProp demo
  components/select/__tests__/__snapshots__/demo.test.js.snap
  components/select/demo/multiple.md
  components/select/demo/option-label-prop.md
  components/select/index.en-US.md
  components/select/index.zh-CN.md
Labels: PR: unreviewed

#14645 New component Descriptions
  components/__tests__/__snapshots__/index.test.js.snap
  components/_util/responsiveObserve.ts
  components/descriptions/__tests__/__snapshots__/demo.test.js.snap
  components/descriptions/__tests__/__snapshots__/index.test.js.snap
  components/descriptions/__tests__/demo.test.js
  components/descriptions/__tests__/index.test.js
  components/descriptions/demo/basic.md
  components/descriptions/demo/border.md
  components/descriptions/demo/responsive.md
  components/descriptions/demo/size.md
  components/descriptions/index.en-US.md
  components/descriptions/index.tsx
  components/descriptions/index.zh-CN.md
  components/descriptions/style/index.less
  components/descriptions/style/index.tsx
  components/grid/__tests__/index.test.js
  components/grid/row.tsx
  components/index.tsx
  tests/__snapshots__/index.test.js.snap
Labels: PR: unreviewed

#16756 fix: adjust Carousel children change goto Logic
  components/carousel/__tests__/index.test.js
  components/carousel/index.tsx
Labels: PR: unreviewed

#16775 docs: 📝 Add Programmatic Usage of antd colors
  docs/spec/colors.en-US.md
  docs/spec/colors.zh-CN.md
Labels: PR: unreviewed

#16777 docs: update preview demo
  components/upload/demo/picture-card.md
Labels: PR: unreviewed

#16782 fix: 🐛 Fix Cascader displayRender not interactive
  components/cascader/style/index.less
Labels: PR: unreviewed

#16786 fix: upload disabled remove
  components/upload/Upload.tsx
Labels: PR: unreviewed

#16773 feat: Steps support clickable
  components/steps/__tests__/__snapshots__/demo.test.js.snap
  components/steps/demo/clickable.md
  components/steps/index.en-US.md
  components/steps/index.zh-CN.md
  components/steps/style/index.less
  package.json
Labels: PR: reviewed-approved

#16780 feat: #16752 - Added lv_LV localization
  components/calendar/locale/lv_LV.tsx
  components/date-picker/locale/lv_LV.tsx
  components/locale-provider/lv_LV.tsx
  components/time-picker/locale/lv_LV.tsx
  package.json
Labels: PR: reviewed-approved

#16778 update getPopupContainer
  components/select/index.zh-CN.md
Labels: PR: unreviewed

#16705 Remove ancient prop types
  components/breadcrumb/Breadcrumb.tsx
  components/modal/Modal.tsx
  components/progress/progress.tsx
Labels: PR: unreviewed

#16793 chore: Merge master into feature
  .github/FUNDING.yml
  components/breadcrumb/Breadcrumb.tsx
  components/carousel/__tests__/index.test.js
  components/carousel/index.tsx
  components/cascader/style/index.less
  components/modal/Modal.tsx
  components/page-header/style/index.less
  components/progress/progress.tsx
  components/select/__tests__/__snapshots__/demo.test.js.snap
  components/select/demo/multiple.md
  components/select/demo/option-label-prop.md
  components/select/index.en-US.md
  components/select/index.zh-CN.md
  components/tabs/__tests__/__snapshots__/demo.test.js.snap
  components/tabs/demo/slide.md
  components/upload/Upload.tsx
  components/upload/demo/picture-card.md
  components/upload/interface.tsx
  docs/react/customize-theme.en-US.md
  docs/react/customize-theme.zh-CN.md
  docs/react/faq.en-US.md
  docs/react/faq.zh-CN.md
  docs/spec/colors.en-US.md
  docs/spec/colors.zh-CN.md
  docs/spec/values.en-US.md
  package.json
  renovate.json
  site/theme/template/Content/ComponentDoc.jsx
  site/theme/template/IconDisplay/index.tsx
Labels: PR: unreviewed

#16794 chore: Merge feature into master
  components/__tests__/__snapshots__/index.test.js.snap
  components/_util/responsiveObserve.ts
  components/calendar/locale/lv_LV.tsx
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/config-provider/renderEmpty.tsx
  components/date-picker/locale/lv_LV.tsx
  components/descriptions/__tests__/__snapshots__/demo.test.js.snap
  components/descriptions/__tests__/__snapshots__/index.test.js.snap
  components/descriptions/__tests__/demo.test.js
  components/descriptions/__tests__/index.test.js
  components/descriptions/demo/basic.md
  components/descriptions/demo/border.md
  components/descriptions/demo/responsive.md
  components/descriptions/demo/size.md
  components/descriptions/index.en-US.md
  components/descriptions/index.tsx
  components/descriptions/index.zh-CN.md
  components/descriptions/style/index.less
  components/descriptions/style/index.tsx
  components/drawer/__tests__/__snapshots__/Drawer.test.js.snap
  components/drawer/__tests__/__snapshots__/DrawerEvent.test.js.snap
  components/drawer/index.tsx
  components/form/style/index.less
  components/grid/__tests__/index.test.js
  components/grid/row.tsx
  components/index.tsx
  components/locale-provider/lv_LV.tsx
  components/mention/index.en-US.md
  components/mention/index.tsx
  components/mention/index.zh-CN.md
  components/mentions/__tests__/__snapshots__/demo.test.js.snap
  components/mentions/__tests__/demo.test.js
  components/mentions/__tests__/index.test.js
  components/mentions/demo/async.md
  components/mentions/demo/basic.md
  components/mentions/demo/form.md
  components/mentions/demo/placement.md
  components/mentions/demo/prefix.md
  components/mentions/demo/readonly.md
  components/mentions/index.en-US.md
  components/mentions/index.tsx
  components/mentions/index.zh-CN.md
  components/mentions/style/index.less
  components/mentions/style/index.tsx
  components/steps/__tests__/__snapshots__/demo.test.js.snap
  components/steps/demo/clickable.md
  components/steps/index.en-US.md
  components/steps/index.zh-CN.md
  components/steps/style/index.less
  components/time-picker/locale/lv_LV.tsx
  package.json
  site/bisheng.config.js
  tests/__snapshots__/index.test.js.snap
Labels: PR: unreviewed

#16535 feat: New calendar apis, headerRender method
  components/calendar/Header.tsx
  components/calendar/__tests__/__snapshots__/demo.test.js.snap
  components/calendar/__tests__/index.test.js
  components/calendar/demo/customize-header.md
  components/calendar/index.en-US.md
  components/calendar/index.tsx
  components/calendar/index.zh-CN.md
Labels: PR: unreviewed

#16641 feat: Allow users to define where tooltips should appear on slider marks
  components/slider/index.tsx
Labels: PR: reviewed-approved

#16717 Fix the problem that the Slider's Tooltip is in the incorrect position when use modal
  components/slider/index.en-US.md
  components/slider/index.tsx
  components/slider/index.zh-CN.md
Labels: PR: unreviewed

#16797 fix: Input parser type
  components/input-number/index.tsx
Labels: PR: unreviewed

#16798 chore: Feature merge master
  components/calendar/Header.tsx
  components/calendar/__tests__/__snapshots__/demo.test.js.snap
  components/calendar/__tests__/index.test.js
  components/calendar/demo/customize-header.md
  components/calendar/index.en-US.md
  components/calendar/index.tsx
  components/calendar/index.zh-CN.md
  components/slider/index.en-US.md
  components/slider/index.tsx
  components/slider/index.zh-CN.md
Labels: PR: unreviewed

#16799 给上传组件添加disabled状态的cursor样式
  components/upload/style/index.less
Labels: PR: unreviewed

#16801 style: Correct Statistic font color
  components/statistic/style/index.less
Labels: PR: unreviewed

#16796 docs: 3.19.0 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#16814 fix: mentions ts definition update
  components/mentions/__tests__/index.test.js
  components/mentions/index.tsx
Labels: PR: unreviewed

#16812 fix: Tooltip not hidden when menu is in control mode
  components/menu/MenuItem.tsx
Labels: PR: unreviewed

#16817 fix: Select ts define
  components/select/index.tsx
Labels: PR: reviewed-approved

#16819 fix: Descriptions warning should work as expect
  components/descriptions/__tests__/index.test.js
  components/descriptions/index.tsx
Labels: PR: unreviewed

#16816 Fix typescript compile error
  components/slider/index.tsx
Labels: PR: unreviewed

#16818 fix: Fix typo name icons
  components/icon/__tests__/index.test.js
  components/icon/utils.ts
  site/theme/template/IconDisplay/fields.ts
Labels: PR: reviewed-changes-requested

#16820 docs: 3.19.1 change-log
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#16825 fix: Tabs card vertical support scroll
  components/tabs/demo/nest.md
  components/tabs/style/card-style.less
Labels: PR: unreviewed

#16824 test: Add more test cases
  components/_util/__tests__/util.test.js
  components/_util/wave.tsx
Labels: PR: unreviewed

#16822 fix(Transfer): avoid setState on an unmounted component
  components/transfer/renderListBody.tsx
Labels: PR: unreviewed

#16826 chore: Add warning if use `inlineCollapsed` under Sider
  components/layout/__tests__/index.test.js
  components/menu/index.tsx
Labels: PR: reviewed-changes-requested

#16827 typescript: adding forceSubmenuRender as MenuProps
  components/menu/index.tsx
Labels: PR: unreviewed

#16829 Update index.en-US.md
  components/table/index.en-US.md
Labels: PR: unreviewed

#16835 chore: export TypographyProps
  components/typography/index.tsx
Labels: PR: unreviewed

#16845 fix: add onChange prop type definition to Steps
  components/steps/index.tsx
Labels: PR: unreviewed

#16846 add semicolon
  components/steps/index.tsx
Labels: PR: unreviewed

#16850 fix: fix type of uploadfile
  components/upload/interface.tsx
Labels: PR: reviewed-approved

#16869 fix: remove invalid Modal prop defaults
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/modal/Modal.tsx
Labels: PR: unreviewed

#16890 fix: use @error-color & @warning-color instead of @text-color-danger & @text-color-warning #16856
  components/style/themes/default.less
  components/typography/style/index.less
Labels: PR: unreviewed

#16894 docs: Add antd pro 4.0 badge on site
  site/theme/en-US.js
  site/theme/template/Layout/Header.jsx
  site/theme/zh-CN.js
Labels: PR: reviewed-changes-requested
