Repository ant-design/ant-design, pull requests merged in 2020-08, with the labels that each got.

#25945 fix: Slider tooltip visible abnormal
  components/slider/index.tsx
Labels: PR: reviewed-approved

#25949 docs: fix typo in demo
  components/form/index.zh-CN.md
Labels: PR: reviewed-approved

#25958 chore: localization update
  components/date-picker/locale/ru_RU.tsx
  components/locale/default.tsx
  components/locale/ru_RU.tsx
  components/time-picker/locale/ru_RU.tsx
Labels: PR: unreviewed

#25948 chore: added english translations for illustrations
  docs/spec/illustration.en-US.md
  docs/spec/illustration.zh-CN.md
Labels: PR: reviewed-approved

#25962 fix: date-fns format string compatible
  package.json
Labels: PR: unreviewed

#25961 fix: List actions default cursor style
  components/list/style/index.less
Labels: PR: unreviewed

#25963 docs: ✨ release 4.5.2
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#25967 fix: useModal missing prefix
  components/config-provider/context.tsx
  components/modal/__tests__/hook.test.js
  components/modal/useModal/HookModal.tsx
Labels: PR: reviewed-approved

#25968 docs: fix site problem
  components/config-provider/index.en-US.md
  components/config-provider/index.zh-CN.md
Labels: PR: unreviewed

#25970 fix: cascader disabled border color
  components/cascader/style/index.less
Labels: PR: unreviewed

#25973 docs: format api
  components/auto-complete/index.en-US.md
  components/auto-complete/index.zh-CN.md
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/input-number/index.zh-CN.md
Labels: PR: unreviewed

#25977 style: adjust mentions readonly cursor
  components/mentions/style/index.less
Labels: PR: unreviewed

#25978 site: fix toc active menu
  site/theme/template/Content/MainContent.jsx
Labels: PR: unreviewed

#25986 test: 📦 compressed-size.yml
  .github/workflows/compressed-size.yml
Labels: PR: unreviewed

#25987 Revert "test: 📦 compressed-size.yml"
  .github/workflows/compressed-size.yml
Labels: PR: unreviewed

#25990 fix: remove typo (#25954)
  components/date-picker/locale/ru_RU.tsx
Labels: PR: unreviewed

#25984 fix: fix breadcrumb separator
  components/breadcrumb/BreadcrumbItem.tsx
  components/breadcrumb/__tests__/Breadcrumb.test.js
  components/breadcrumb/__tests__/__snapshots__/Breadcrumb.test.js.snap
Labels: PR: unreviewed

#25998 style: hidden handler when inputnumber readonly
  components/input-number/index.en-US.md
  components/input-number/index.tsx
  components/input-number/index.zh-CN.md
  components/input-number/style/index.less
Labels: PR: reviewed-approved

#26001 fix: Table empty filters throw warning
  components/table/__tests__/Table.filter.test.js
  components/table/hooks/useFilter/FilterDropdown.tsx
Labels: PR: reviewed-approved

#26002 fix: select disabled icon cursor style
  components/select/style/index.less
Labels: PR: unreviewed

#25980 style: optimize select multiple disabled style
  components/select/__tests__/__snapshots__/demo.test.js.snap
  components/select/demo/multiple.md
  components/select/style/multiple.less
  components/style/themes/dark.less
  components/style/themes/default.less
Labels: PR: unreviewed

#26005 fix: transfer disabled header dropdown cursor
  components/transfer/style/index.less
Labels: PR: unreviewed

#26006 chore: 🛠 quit pub script when throw error
  package.json
  scripts/test-all.sh
Labels: PR: unreviewed

#26010 docs: update table demo action
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/demo/dynamic-settings.md
  components/table/demo/nest-table-border-debug.md
  components/table/demo/nested-table.md
  components/table/demo/pagination.md
Labels: PR: unreviewed

#26011 fix: Cascader text overflow in Firefox
  components/cascader/style/index.less
Labels: PR: unreviewed

#26014 style: add @btn-line-height
  components/button/style/index.less
  components/style/themes/default.less
Labels: PR: unreviewed

#26009 fix: transfer pagination disabled
  components/transfer/ListBody.tsx
Labels: PR: unreviewed

#26008 style: optimize pagination simple disabled
  components/pagination/__tests__/__snapshots__/demo.test.js.snap
  components/pagination/demo/mini.md
  components/pagination/demo/simple.md
  components/pagination/style/index.less
  package.json
Labels: PR: unreviewed

#26019 docs: fix typo in resposive.md
  components/list/demo/resposive.md
Labels: PR: reviewed-approved

#25997 docs: add en translation for buttons page
  docs/spec/buttons.en-US.md
  docs/spec/buttons.zh-CN.md
Labels: PR: unreviewed

#26020 fix: hidden should higher than noStyle
  components/form/FormItem.tsx
  components/form/__tests__/__snapshots__/index.test.js.snap
  components/form/__tests__/index.test.js
Labels: PR: unreviewed

#26022 docs: update grid demo
  components/grid/__tests__/__snapshots__/demo.test.js.snap
  components/grid/demo/flex-align.md
  components/grid/demo/flex-order.md
  components/grid/demo/flex-stretch.md
  components/grid/demo/flex.md
  components/grid/demo/gutter.md
  components/grid/demo/playground.md
  components/grid/index.zh-CN.md
Labels: PR: unreviewed

#26025 docs: perfect site
  components/affix/demo/debug.md
  components/affix/index.en-US.md
  components/affix/index.zh-CN.md
  components/breadcrumb/demo/basic.md
  components/breadcrumb/demo/separator-indepent.md
  components/breadcrumb/demo/separator.md
  components/breadcrumb/index.en-US.md
  components/breadcrumb/index.zh-CN.md
Labels: PR: unreviewed

#26032 fix: menu position in dark rtl
  components/menu/style/rtl.less
Labels: PR: unreviewed

#26034 fix: fr_FR Table.cancelSort spelling error
  components/locale/fr_FR.tsx
Labels: PR: reviewed-approved

#26044 chore: Replace `rc-animation/lib/CSSMotion` to `rc-motion`
  components/_util/motion.tsx
  components/menu/index.tsx
  package.json
Labels: PR: unreviewed

#26047 docs: Added UI kit for Adobe XD to Resources page
  docs/resources.en-US.md
Labels: PR: unreviewed

#26042 fix: Table crash when dataSource contains number
  components/table/Table.tsx
  components/table/__tests__/Table.test.js
  components/table/hooks/useLazyKVMap.ts
  components/table/hooks/useSelection.tsx
Labels: PR: reviewed-approved

#26050 chore: merge master into feature
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/pr_cn.md
  components/_util/motion.tsx
  components/locale/fr_FR.tsx
  components/menu/index.tsx
  components/menu/style/rtl.less
  components/table/Table.tsx
  components/table/__tests__/Table.test.js
  components/table/hooks/useLazyKVMap.ts
  components/table/hooks/useSelection.tsx
  docs/resources.en-US.md
  package.json
Labels: PR: reviewed-approved

#26049 chore: replace `rc-animate/lib/CSSMotion` with `rc-motion`
  components/button/LoadingIcon.tsx
  components/form/FormItemInput.tsx
Labels: PR: unreviewed

#26052 feat: message destroy the specified key
  components/message/__tests__/index.test.js
  components/message/index.en-US.md
  components/message/index.tsx
  components/message/index.zh-CN.md
Labels: PR: reviewed-approved

#25138 feat: Tabs add slot to support extra position
  components/tabs/__tests__/__snapshots__/demo.test.js.snap
  components/tabs/demo/extra.md
  components/tabs/index.en-US.md
  components/tabs/index.zh-CN.md
  package.json
Labels: Inactive, PR: reviewed-approved, PR: unreviewed

#26072 fix: inputnumber handler background in dark
  components/style/themes/dark.less
Labels: PR: unreviewed

#26062 fix: horizontal menu in dark & dark
  components/menu/style/dark.less
  components/menu/style/index.less
Labels: PR: unreviewed

#26069 fix: 修复紧凑模式下表单项 margin 计算错误
  components/form/style/index.less
Labels: PR: unreviewed

#26078 style: Cascader selector down arrow doesn't rotate
  components/cascader/style/index.less
Labels: PR: reviewed-approved

#26079 docs: perfect website
  components/button/index.en-US.md
  components/button/index.zh-CN.md
  components/icon/index.en-US.md
  components/icon/index.zh-CN.md
Labels: PR: unreviewed

#25939 feat: Table new sticky prop
  components/style/themes/default.less
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/demo/sticky.md
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/table/style/index.less
  package.json
Labels: PR: unreviewed

#26082 chore: ❤️ improve components overview page experience
  site/theme/template/Content/ComponentOverview.jsx
Labels: PR: unreviewed

#25953 feat: customize Typography.Paragraph copyable and editable
  components/typography/Base.tsx
  components/typography/__tests__/__snapshots__/demo.test.js.snap
  components/typography/__tests__/index.test.js
  components/typography/demo/interactive.md
  components/typography/index.en-US.md
  components/typography/index.zh-CN.md
Labels: PR: reviewed-approved

#26075 fix: Steps progress circle size & rtl style when use `progress`
  components/steps/__tests__/__snapshots__/demo.test.js.snap
  components/steps/index.tsx
  components/steps/style/progress.less
  components/steps/style/rtl.less
Labels: PR: reviewed-approved

#26106 chore: merge master into feature
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/avatar/group.tsx
  components/button/LoadingIcon.tsx
  components/button/index.en-US.md
  components/button/index.zh-CN.md
  components/cascader/style/index.less
  components/date-picker/__tests__/__snapshots__/demo.test.js.snap
  components/date-picker/demo/basic.md
  components/date-picker/demo/switchable.md
  components/form/FormItemInput.tsx
  components/form/style/index.less
  components/icon/index.en-US.md
  components/icon/index.zh-CN.md
  components/locale/ar_EG.tsx
  components/menu/style/dark.less
  components/menu/style/index.less
  components/steps/__tests__/__snapshots__/demo.test.js.snap
  components/steps/index.tsx
  components/steps/style/progress.less
  components/steps/style/rtl.less
  components/style/themes/dark.less
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/upload/__tests__/__snapshots__/demo.test.js.snap
  components/upload/demo/upload-png-only.md
  components/upload/index.en-US.md
  components/upload/index.zh-CN.md
  docs/react/i18n.en-US.md
  package.json
  site/theme/template/Content/ComponentOverview.jsx
  site/theme/template/Home/RecommendPage.tsx
Labels: PR: reviewed-approved

#26102 docs: improve typography API table
  components/typography/index.en-US.md
  components/typography/index.zh-CN.md
Labels: PR: partially-approved

#25991 feat: show line in Tree first level
  components/tree/__tests__/__snapshots__/demo.test.js.snap
  components/tree/__tests__/__snapshots__/directory.test.js.snap
  components/tree/__tests__/__snapshots__/index.test.js.snap
  components/tree/demo/line.md
  components/tree/style/mixin.less
  package.json
Labels: PR: unreviewed

#26043 style: add @badge-count-background
  components/badge/style/index.less
  components/style/themes/default.less
Labels: PR: unreviewed

#26112 chore: merge master into feature
  components/badge/style/index.less
  components/form/demo/dep-debug.md
  components/style/themes/default.less
  components/tree/__tests__/__snapshots__/demo.test.js.snap
  components/tree/__tests__/__snapshots__/directory.test.js.snap
  components/tree/__tests__/__snapshots__/index.test.js.snap
  components/tree/demo/line.md
  components/tree/style/mixin.less
  package.json
Labels: PR: reviewed-approved

#25664 docs(page-header): fix default value for onBack
  components/page-header/index.en-US.md
  components/page-header/index.zh-CN.md
Labels: PR: unreviewed

#26159 feat: Add @badge-color
  components/badge/style/index.less
  components/style/themes/default.less
Labels: PR: reviewed-approved

#26081 feat: Form.List add() support index param
  components/form/FormList.tsx
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/demo/dynamic-form-item.md
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#26145 feat: add Typography.Text type success
  components/typography/Base.tsx
  components/typography/__tests__/__snapshots__/demo.test.js.snap
  components/typography/demo/text.md
  components/typography/index.en-US.md
  components/typography/index.zh-CN.md
  components/typography/style/index.less
Labels: PR: unreviewed

#26242 docs: improve code demo box style
  .github/workflows/lighthouse-ci.yml
  azure-pipelines.yml
  components/upload/demo/preview-file.md
  site/theme/static/demo.less
Labels: PR: draft

#26243 chore: merge master into feature
  .github/workflows/lighthouse-ci.yml
  azure-pipelines.yml
  components/cascader/__tests__/index.test.js
  components/cascader/index.tsx
  components/divider/index.en-US.md
  components/divider/index.zh-CN.md
  components/dropdown/style/rtl.less
  components/grid/demo/flex-order.md
  components/grid/demo/offset.md
  components/grid/index.en-US.md
  components/grid/index.zh-CN.md
  components/grid/style/rtl.less
  components/input-number/demo/formatter.md
  components/layout/demo/responsive.md
  components/layout/demo/side.md
  components/layout/demo/top.md
  components/layout/index.en-US.md
  components/layout/index.zh-CN.md
  components/list/style/rtl.less
  components/pagination/style/index.less
  components/select/style/multiple.less
  components/select/style/rtl.less
  components/space/__tests__/__snapshots__/demo.test.js.snap
  components/space/__tests__/index.test.js
  components/space/index.tsx
  components/style/themes/default.less
  components/tree/__tests__/__snapshots__/directory.test.js.snap
  components/tree/style/rtl.less
  components/upload/demo/preview-file.md
  docs/react/migration-v4.en-US.md
  docs/react/migration-v4.zh-CN.md
  package.json
  site/theme/static/demo.less
Labels: PR: reviewed-approved

#26259 fix: Typography copyable tooltips
  components/typography/Base.tsx
  components/typography/__tests__/index.test.js
Labels: PR: reviewed-approved

#26267 chore: merge master into feature
  components/breadcrumb/demo/separator.md
  components/breadcrumb/index.en-US.md
  components/breadcrumb/index.zh-CN.md
  components/dropdown/index.en-US.md
  components/dropdown/index.zh-CN.md
  components/input/__tests__/textarea.test.js
  components/page-header/__tests__/index.test.js
  components/select/style/index.less
  components/upload/Dragger.tsx
  components/upload/Upload.tsx
  components/upload/UploadList.tsx
  components/upload/__tests__/dragger.test.js
  components/upload/__tests__/upload.test.js
  components/upload/__tests__/uploadlist.test.js
  components/upload/hooks/useForceUpdate.ts
  components/upload/hooks/useSyncState.ts
Labels: PR: reviewed-approved

#26278 chore: 🆙 upgrade rc-virtual-list
  components/auto-complete/__tests__/__snapshots__/index.test.js.snap
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/list/__tests__/__snapshots__/pagination.test.js.snap
  components/tree-select/__tests__/__snapshots__/index.test.js.snap
  package.json
Labels: PR: reviewed-approved

#26282 chore: Update rc-virtual-list deps
  package.json
Labels: PR: unreviewed

#26309 feat: Support requiredMarkType
  components/form/Form.tsx
  components/form/FormItem.tsx
  components/form/FormItemLabel.tsx
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/__tests__/index.test.js
  components/form/context.tsx
  components/form/demo/required-mark.md
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/form/style/index.less
  components/form/style/rtl.less
  components/locale-provider/LocaleReceiver.tsx
  components/locale-provider/index.tsx
  components/locale/default.tsx
  components/locale/zh_CN.tsx
Labels: PR: reviewed-approved

#26318 refactor: 🆙 upgrade TypeScript to 4.0
  package.json
Labels: PR: draft

#26354 chore: merge master into feature
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/date-picker/__tests__/DatePicker.test.js
  components/layout/Sider.tsx
  components/layout/__tests__/index.test.js
  components/menu/MenuItem.tsx
  components/menu/SubMenu.tsx
  components/upload/Upload.tsx
  components/upload/__tests__/type.test.tsx
  package.json
Labels: PR: unreviewed

#26409 fix: 🐛 Table Expand Icon size issue
  components/table/style/index.less
Labels: PR: draft

#26244 feat: add support to responsive sizes in Avatar component
  components/_util/responsiveObserve.ts
  components/avatar/__tests__/Avatar.test.js
  components/avatar/__tests__/__snapshots__/Avatar.test.js.snap
  components/avatar/__tests__/__snapshots__/demo.test.js.snap
  components/avatar/avatar.tsx
  components/avatar/demo/responsive.md
  components/avatar/index.en-US.md
  components/avatar/index.zh-CN.md
  components/avatar/style/index.tsx
Labels: PR: unreviewed
