Repository ant-design/ant-design, pull requests merged in 2020-09, with the labels that each got.

#26513 chore: merge master into feature
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/checkbox/index.en-US.md
  components/config-provider/__tests__/form-locale.test.js
  components/config-provider/__tests__/locale.test.js
  components/config-provider/index.zh-CN.md
  components/grid/style/rtl.less
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
  components/upload/Upload.tsx
  components/upload/__tests__/__snapshots__/uploadlist.test.js.snap
  components/upload/__tests__/upload.test.js
  components/upload/__tests__/uploadlist.test.js
  package.json
Labels: PR: reviewed-approved

#26523 chore: merge master into feature
  package.json
Labels: PR: reviewed-approved

#26557 chore: merge master into feature
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/_util/motion.tsx
  components/avatar/__tests__/__snapshots__/Avatar.test.js.snap
  components/avatar/avatar.tsx
  components/button/__tests__/__snapshots__/type.test.tsx.snap
  components/button/__tests__/type.test.tsx
  components/cascader/__tests__/__snapshots__/index.test.js.snap
  components/cascader/__tests__/index.test.js
  components/pagination/style/index.less
  components/popconfirm/index.tsx
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/demo/resizable-column.md
  components/tooltip/__tests__/type.test.tsx
  components/tooltip/index.tsx
  docs/spec/font.en-US.md
  docs/spec/font.zh-CN.md
  package.json
  site/theme/static/common.less
  site/theme/static/markdown.less
  site/theme/static/toc.less
  site/theme/template/Content/ComponentDoc.jsx
Labels: PR: reviewed-approved

#26507 feat: Update rc-dialog to 8.3.0, support Modal drag and drop.
  components/modal/__tests__/__snapshots__/demo.test.js.snap
  components/modal/demo/modal-render.md
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
  package.json
Labels: PR: partially-approved

#25765 fix: Modal width out of screen
  components/modal/__tests__/__snapshots__/demo.test.js.snap
  components/modal/demo/width.md
  components/modal/style/modal.less
Labels: Inactive, PR: unreviewed

#26627 perf: 📦 remove duplicated rc-dialog in deps
  package.json
Labels: PR: draft

#26655 chore: Feature merge master
  components/auto-complete/index.en-US.md
  components/auto-complete/index.zh-CN.md
  components/cascader/__tests__/__snapshots__/index.test.js.snap
  components/input/TextArea.tsx
  components/input/__tests__/textarea.test.js
  components/list/__tests__/__snapshots__/pagination.test.js.snap
  components/select/style/index.less
  components/select/style/single.less
  components/slider/__tests__/__snapshots__/index.test.js.snap
  components/style/core/motion/zoom.less
  components/table/__tests__/__snapshots__/Table.filter.test.js.snap
  components/table/__tests__/__snapshots__/Table.rowSelection.test.js.snap
  components/table/index.zh-CN.md
  components/upload/__tests__/upload.test.js
  components/upload/__tests__/uploadlist.test.js
  docs/spec/illustration.en-US.md
  docs/spec/illustration.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#26659 style: 💄 Card cover image has extra 1px border
  components/card/style/index.less
Labels: PR: unreviewed

#26672 docs: remove Anchor not use api
  components/anchor/index.en-US.md
  components/anchor/index.zh-CN.md
Labels: PR: reviewed-approved

#26597 feat: form support messageVariables
  components/form/FormItem.tsx
  components/form/__tests__/index.test.js
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: PR: reviewed-approved

#26691 docs: optimize api style
  site/theme/static/markdown.less
Labels: PR: unreviewed

#26686 fix: Table sorter compare and multiple should be optional
  components/table/interface.tsx
Labels: PR: unreviewed

#26703 [Chore] Fix typo in index.en-US.md
  components/form/index.en-US.md
Labels: PR: reviewed-approved

#26678 fix(table-pagination): make pagination.position work
  components/table/style/index.less
  components/table/style/rtl.less
Labels: PR: unreviewed

#26705 feat: expose ConfigContext in umd bundle
  components/config-provider/index.tsx
Labels: PR: unreviewed

#26676 feat: Form.List support rules
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/form/ErrorList.tsx
  components/form/FormItem.tsx
  components/form/FormItemInput.tsx
  components/form/FormList.tsx
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/__tests__/list.test.js
  components/form/context.tsx
  components/form/demo/dynamic-form-item.md
  components/form/index.en-US.md
  components/form/index.tsx
  components/form/index.zh-CN.md
  components/form/style/mixin.less
  components/form/style/status.less
  package.json
Labels: PR: unreviewed

#26684 Feat: Support callbacks for removeIcon and downloadIcon in Upload
  components/upload/UploadList.tsx
  components/upload/__tests__/uploadlist.test.js
  components/upload/index.en-US.md
  components/upload/index.zh-CN.md
  components/upload/interface.tsx
Labels: PR: partially-approved

#26720 docs: Add changelog of 4.6.4
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#26567 docs: add direction & theme to url
  site/theme/static/dark.less
  site/theme/template/Content/ComponentOverview.jsx
  site/theme/template/Content/MainContent.jsx
  site/theme/template/Home/Banner/index.tsx
  site/theme/template/Home/DesignPage/index.tsx
  site/theme/template/Home/index.tsx
  site/theme/template/Layout/Footer.tsx
  site/theme/template/Layout/Header/Logo.tsx
  site/theme/template/Layout/Header/Navigation.tsx
  site/theme/template/Layout/Header/index.tsx
  site/theme/template/Layout/index.jsx
  site/theme/template/NotFound.tsx
  site/theme/template/Resources/index.tsx
  site/theme/template/utils.tsx
Labels: PR: unreviewed

#26721 fix: don't show empty items in Space component
  components/space/style/index.less
Labels: PR: unreviewed

#26725 docs: fix heading level in replace-moment
  docs/react/replace-moment.en-US.md
  docs/react/replace-moment.zh-CN.md
Labels: PR: unreviewed

#26660 CascaderProps add name and id props
  components/cascader/index.tsx
Labels: PR: unreviewed

#26673 Update time-picker documentation
  components/time-picker/index.en-US.md
Labels: PR: unreviewed

#26738 chore: merge master into feature
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/anchor/index.en-US.md
  components/anchor/index.zh-CN.md
  components/auto-complete/__tests__/__snapshots__/index.test.js.snap
  components/card/style/index.less
  components/cascader/index.tsx
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/config-provider/index.tsx
  components/form/index.en-US.md
  components/list/__tests__/__snapshots__/pagination.test.js.snap
  components/menu/__tests__/index.test.js
  components/menu/demo/horizontal.md
  components/space/style/index.less
  components/table/__tests__/__snapshots__/empty.test.js.snap
  components/table/hooks/useFilter/FilterDropdown.tsx
  components/table/interface.tsx
  components/table/style/index.less
  components/table/style/rtl.less
  components/time-picker/index.en-US.md
  docs/react/faq.en-US.md
  docs/react/faq.zh-CN.md
  docs/react/replace-moment.en-US.md
  docs/react/replace-moment.zh-CN.md
  package.json
  site/theme/static/dark.less
  site/theme/static/markdown.less
  site/theme/template/Content/ComponentOverview.jsx
  site/theme/template/Content/MainContent.jsx
  site/theme/template/Home/Banner/index.tsx
  site/theme/template/Home/DesignPage/index.tsx
  site/theme/template/Home/index.tsx
  site/theme/template/Layout/Footer.tsx
  site/theme/template/Layout/Header/Logo.tsx
  site/theme/template/Layout/Header/Navigation.tsx
  site/theme/template/Layout/Header/index.tsx
  site/theme/template/Layout/index.jsx
  site/theme/template/NotFound.tsx
  site/theme/template/Resources/index.tsx
  site/theme/template/utils.tsx
Labels: PR: reviewed-approved

#26740 fix: `Button` as component for react-router `Link`
  components/button/button.tsx
Labels: PR: unreviewed

#26600 chore: 🆙 upgrade typescript-eslint
  .eslintrc.js
  components/_util/type.ts
  components/anchor/Anchor.tsx
  components/auto-complete/index.tsx
  components/avatar/index.tsx
  components/checkbox/Checkbox.tsx
  components/date-picker/generatePicker/index.tsx
  components/form/hooks/useForm.ts
  components/form/index.tsx
  components/modal/confirm.tsx
  components/modal/index.tsx
  components/radio/index.tsx
  components/table/ColumnGroup.tsx
  components/table/interface.tsx
  components/transfer/__tests__/index.test.js
  components/transfer/index.tsx
  package.json
  site/theme/template/Resources/index.tsx
Labels: PR: unreviewed, help wanted

#26765 fix: AutoComplete warning when using placeholder and allowClear
  components/auto-complete/__tests__/index.test.js
  components/auto-complete/index.tsx
Labels: PR: unreviewed

#26768 chore: merge master into feature
  .eslintrc.js
  SECURITY.md
  components/_util/type.ts
  components/affix/__tests__/Affix.test.tsx
  components/anchor/Anchor.tsx
  components/anchor/__tests__/__snapshots__/demo.test.ts.snap
  components/anchor/demo/basic.md
  components/anchor/demo/onClick.md
  components/anchor/index.en-US.md
  components/anchor/index.zh-CN.md
  components/auto-complete/__tests__/index.test.js
  components/auto-complete/index.tsx
  components/avatar/index.tsx
  components/button/button.tsx
  components/calendar/__tests__/index.test.js
  components/carousel/__tests__/index.test.js
  components/checkbox/Checkbox.tsx
  components/date-picker/generatePicker/index.tsx
  components/form/hooks/useForm.ts
  components/form/index.tsx
  components/modal/confirm.tsx
  components/modal/index.tsx
  components/radio/index.tsx
  components/table/ColumnGroup.tsx
  components/table/__tests__/__snapshots__/Table.rowSelection.test.js.snap
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/__tests__/__snapshots__/empty.test.js.snap
  components/table/interface.tsx
  components/transfer/__tests__/index.test.js
  components/transfer/index.tsx
  components/upload/__tests__/upload.test.js
  package.json
  site/theme/template/Resources/index.tsx
Labels: PR: unreviewed

#26779 修复Array(x).key()在codePen预览时报错
  components/tabs/demo/slide.md
Labels: PR: unreviewed

#26771 docs: Typo in complex-form-control.md
  components/form/demo/complex-form-control.md
Labels: PR: reviewed-approved

#26784 style: 💄 fix TimePicker column align problem
  components/date-picker/style/panel.less
  components/style/themes/default.less
Labels: PR: unreviewed

#26785 style: 💄 tweak button icon only align
  components/button/style/index.less
Labels: PR: unreviewed

#26786 docs: Update virtual list demo
  components/table/demo/virtual-list.md
Labels: PR: unreviewed

#26333 feat(upload): support itemRender
  components/upload/Upload.tsx
  components/upload/UploadList.tsx
  components/upload/__tests__/__snapshots__/demo.test.js.snap
  components/upload/__tests__/__snapshots__/uploadlist.test.js.snap
  components/upload/__tests__/uploadlist.test.js
  components/upload/demo/drag-sorting.md
  components/upload/index.en-US.md
  components/upload/index.zh-CN.md
  components/upload/interface.tsx
Labels: PR: unreviewed

#26791 feat: FormItem support generate for renderProps
  components/form/FormItem.tsx
  components/form/__tests__/type.test.tsx
  package.json
Labels: PR: reviewed-approved

#26780 feat: Form.Item support `tooltip`
  components/form/FormItem.tsx
  components/form/FormItemLabel.tsx
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/__tests__/index.test.js
  components/form/demo/required-mark.md
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/form/style/index.less
  components/form/style/index.tsx
Labels: PR: reviewed-approved

#26800 fix: <Table/> sticky z-index calculation.
  components/table/style/index.less
Labels: PR: unreviewed

#26803 chore: Update rc-trigger related version
  components/popover/__tests__/__snapshots__/index.test.js.snap
  components/popover/__tests__/index.test.js
  package.json
Labels: PR: unreviewed

#26808 fix: FieldForm onValuesChange
  package.json
Labels: PR: reviewed-approved

#26810 fix: @layout-sider-background cannot set to linear-gradient
  components/layout/style/index.less
Labels: PR: unreviewed

#26815 test: add test case for switch click effect
  components/_util/wave.tsx
  components/button/__tests__/wave.test.tsx
  components/switch/__tests__/wave.test.js
Labels: PR: unreviewed

#26817 fix: 🐛 SubMenu unexpected scrollbar
  components/menu/style/index.less
Labels: PR: unreviewed

#26820 style: fix description item long text
  components/descriptions/style/index.less
Labels: PR: unreviewed

#26813 docs: improve from list
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/demo/dynamic-form-items-complex.md
Labels: PR: unreviewed

#26825 docs: 4.6.5 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#26828 test: ✅ Motion for Collpase and Menu
  components/_util/__tests__/util.test.js
  components/collapse/Collapse.tsx
  components/collapse/__tests__/common.test.js
  components/collapse/openAnimation.tsx
  components/menu/__tests__/index.test.js
  tests/utils.ts
Labels: PR: unreviewed

#26831 chore: add FormListProps export in form/index.tsx
  components/form/index.tsx
Labels: PR: unreviewed

#26838 docs: Add AutoComplete migrate demo
  components/auto-complete/index.en-US.md
  components/auto-complete/index.zh-CN.md
  docs/react/migration-v4.en-US.md
  docs/react/migration-v4.zh-CN.md
Labels: PR: unreviewed

#26839 test: ✅ 100% coverage
  components/_util/__tests__/util.test.js
  components/_util/styleChecker.tsx
  components/_util/throttleByAnimationFrame.tsx
  components/_util/wave.tsx
  components/back-top/index.tsx
  components/button/__tests__/wave.test.tsx
  components/typography/Base.tsx
Labels: PR: unreviewed

#26845 feat(date-picker): support custom format
  components/date-picker/__tests__/__snapshots__/demo.test.js.snap
  components/date-picker/demo/format.md
  components/date-picker/generatePicker/index.tsx
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#26854 style: link-decoration
  components/typography/style/index.less
Labels: PR: unreviewed

#26849 style: fix Radio.Button validation error highlight
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/demo/validate-other.md
  components/form/style/status.less
Labels: PR: unreviewed

#26863 fix: Divider border style not work on text mode
  components/divider/__tests__/__snapshots__/demo.test.js.snap
  components/divider/demo/customize-style.md
  components/divider/style/index.less
Labels: PR: unreviewed

#26872 docs: Update TreeNode isLeaf desc
  components/tree/index.en-US.md
  components/tree/index.zh-CN.md
Labels: PR: unreviewed

#26873 docs: Add Form.List deps faq
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: PR: unreviewed

#26884 chore(slider): optimize type definition
  components/slider/index.tsx
  package.json
  typings/custom-typings.d.ts
Labels: PR: unreviewed

#26864 fix: fix message.destroy parameter
  components/message/index.tsx
Labels: PR: reviewed-approved

#26850 change function name correctly in index.js
  index.js
Labels: PR: unreviewed

#26894 fix(🐛): Steps item shifts in vertical mode
  components/steps/style/vertical.less
Labels: PR: unreviewed

#26906 feat: Add missing translations in Thai (th_TH) locale
  components/locale/th_TH.tsx
Labels: PR: reviewed-approved

#26916 release: 4.6.6
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: reviewed-approved

#26918 chore: release 4.6.6 version
  package.json
Labels: PR: unreviewed

#26919 chore: bump rc-notification
  components/message/__tests__/config.test.js
  components/message/__tests__/hooks.test.js
  components/message/__tests__/index.test.js
  components/message/index.tsx
  components/notification/__tests__/index.test.js
  components/notification/index.tsx
  package.json
Labels: PR: unreviewed

#26915 docs: add Image Preview doc
  components/image/index.en-US.md
  components/image/index.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#26913 feat: add several translations for pl_PL locale
  components/locale/pl_PL.tsx
Labels: PR: unreviewed

#26923 chore: merge master into feature
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/locale/pl_PL.tsx
  components/message/__tests__/config.test.js
  components/message/__tests__/hooks.test.js
  components/message/__tests__/index.test.js
  components/message/index.tsx
  components/notification/__tests__/index.test.js
  components/notification/index.tsx
  components/slider/index.tsx
  components/steps/style/vertical.less
  index.js
  package.json
  typings/custom-typings.d.ts
Labels: PR: reviewed-approved

#26932 style: optimize tag typescript define
  components/tag/index.tsx
Labels: PR: unreviewed

#26937 docs: update the Chinese doc of the Search component
  components/input/index.zh-CN.md
Labels: PR: reviewed-approved

#26956 docs: optimize site a disabled color
  site/theme/static/dark.less
Labels: PR: unreviewed

#26955 style: optimize tag style in rtl & dark
  components/tag/style/rtl.less
Labels: PR: unreviewed

#26961 fix: upload rtl style
  components/upload/style/rtl.less
Labels: PR: unreviewed

#26960 style: optimize transfer pagination rtl style
  components/transfer/style/rtl.less
Labels: PR: unreviewed

#26962 docs: update image demo
  components/image/__tests__/__snapshots__/demo.test.js.snap
  components/image/demo/placeholder.md
Labels: PR: reviewed-approved

#26968 docs: update tabs extra demo
  components/tabs/__tests__/__snapshots__/demo.test.js.snap
  components/tabs/demo/extra.md
Labels: PR: unreviewed

#26964 fix: List action rtl style
  components/list/style/rtl.less
Labels: PR: unreviewed

#26973 chore: upgrade rc-table
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/table/style/index.less
  package.json
Labels: PR: reviewed-approved
