Repository ant-design/ant-design, pull requests merged in 2020-10, with the labels that each got.

#26983 docs: ✏️ replace `is` with `are`
  components/button/index.en-US.md
Labels: PR: unreviewed

#26991 chore: `useContext` in Empty
  components/empty/index.tsx
Labels: PR: unreviewed

#26993 fix: Update th-TH locale for recently added Pickers
  components/date-picker/locale/th_TH.tsx
Labels: PR: reviewed-approved

#26984 fix: Slider step prop not accepting null value
  components/slider/__tests__/index.test.js
  components/slider/__tests__/type.test.tsx
  components/slider/index.tsx
Labels: PR: unreviewed

#26995 fix: missing autoFocus prop in Slider. Fixes #26982
  components/slider/index.tsx
Labels: PR: unreviewed

#26969 docs: fix data-format.md
  docs/spec/data-format.en-US.md
  docs/spec/data-format.zh-CN.md
Labels: PR: reviewed-approved

#26998 chore: merge master into feature
  components/button/index.en-US.md
  components/empty/index.tsx
  components/image/__tests__/__snapshots__/demo.test.js.snap
  components/image/demo/placeholder.md
  components/input/index.zh-CN.md
  components/list/style/rtl.less
  components/slider/__tests__/index.test.js
  components/slider/__tests__/type.test.tsx
  components/slider/index.tsx
  components/tabs/__tests__/__snapshots__/demo.test.js.snap
  components/tabs/demo/extra.md
  components/tag/__tests__/__snapshots__/demo.test.js.snap
  components/tag/demo/status.md
  components/tag/index.tsx
  components/tag/style/rtl.less
  components/transfer/style/rtl.less
  components/upload/style/rtl.less
  docs/spec/data-format.en-US.md
  docs/spec/data-format.zh-CN.md
  site/theme/static/dark.less
Labels: PR: reviewed-approved

#27001 chore: fix timeline TimelineItemProps typo
  components/timeline/Timeline.tsx
  components/timeline/TimelineItem.tsx
  components/timeline/index.tsx
Labels: PR: unreviewed

#27002 fix: undefined in filterDropdown in Table should not render dropdown …
  components/table/__tests__/Table.filter.test.js
  components/table/hooks/useFilter/index.tsx
Labels: PR: unreviewed

#27010 style: optimize loading icon in rtl
  components/cascader/style/rtl.less
  components/tree-select/style/index.less
  components/tree/style/rtl.less
Labels: PR: unreviewed

#27017 fix: Update tr_TR.tsx
  components/locale/tr_TR.tsx
Labels: PR: unreviewed

#27013 fix: words spell error at the file of wave.tsx
  components/_util/wave.tsx
Labels: PR: unreviewed

#27003 docs: documentation for Jest support [EN only]
  docs/react/getting-started.en-US.md
  docs/react/use-with-create-react-app.en-US.md
Labels: PR: reviewed-approved

#27029 docs: update form migrate docs title
  components/form/v3.en-US.md
  components/form/v3.zh-CN.md
Labels: PR: unreviewed

#26948 feat: Space add split
  components/space/Item.tsx
  components/space/__tests__/__snapshots__/demo.test.js.snap
  components/space/__tests__/__snapshots__/index.test.js.snap
  components/space/__tests__/index.test.js
  components/space/demo/split.md
  components/space/index.en-US.md
  components/space/index.tsx
  components/space/index.zh-CN.md
Labels: PR: partially-approved

#27037 docs: fix typo in buttons.en-US.md
  docs/spec/buttons.en-US.md
Labels: PR: reviewed-approved

#27033 fix: sliderProps typeScript define
  components/slider/index.tsx
  package.json
Labels: PR: unreviewed

#27038 docs: improve api type docs
  components/alert/index.en-US.md
  components/alert/index.zh-CN.md
  components/anchor/index.en-US.md
  components/anchor/index.zh-CN.md
  components/breadcrumb/index.en-US.md
  components/breadcrumb/index.zh-CN.md
  components/card/index.en-US.md
  components/card/index.zh-CN.md
  components/collapse/index.en-US.md
  components/collapse/index.zh-CN.md
  components/comment/index.en-US.md
  components/comment/index.zh-CN.md
  components/descriptions/index.en-US.md
  components/descriptions/index.zh-CN.md
  components/drawer/index.en-US.md
  components/drawer/index.zh-CN.md
  components/empty/index.en-US.md
  components/empty/index.zh-CN.md
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/input/index.en-US.md
  components/input/index.zh-CN.md
  components/layout/index.en-US.md
  components/layout/index.zh-CN.md
  components/list/index.en-US.md
  components/list/index.zh-CN.md
  components/menu/index.en-US.md
  components/menu/index.zh-CN.md
  components/message/index.en-US.md
  components/message/index.zh-CN.md
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
  components/notification/index.en-US.md
  components/notification/index.zh-CN.md
  components/popconfirm/index.en-US.md
  components/popconfirm/index.zh-CN.md
  components/popover/index.en-US.md
  components/popover/index.zh-CN.md
  components/select/index.en-US.md
  components/slider/index.en-US.md
  components/slider/index.zh-CN.md
  components/statistic/index.en-US.md
  components/statistic/index.zh-CN.md
  components/steps/index.en-US.md
  components/steps/index.zh-CN.md
  components/switch/index.en-US.md
  components/switch/index.zh-CN.md
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/tabs/index.en-US.md
  components/tabs/index.zh-CN.md
  components/timeline/index.en-US.md
  components/timeline/index.zh-CN.md
  components/tooltip/index.en-US.md
  components/tooltip/index.zh-CN.md
  components/tree-select/index.en-US.md
  components/tree-select/index.zh-CN.md
  components/tree/index.en-US.md
  components/tree/index.zh-CN.md
Labels: PR: unreviewed

#27039 refactor: Remove layout deprecated
  components/layout/Sider.tsx
Labels: PR: unreviewed

#27050 fix: Radio.Button cannot use Tooltip
  components/radio/radio.tsx
  components/radio/style/index.less
Labels: PR: reviewed-approved

#27043 fix: add Japanese localization for Table
  components/locale/ja_JP.tsx
Labels: PR: unreviewed

#27028 feat: add Belarusian translation
  components/calendar/locale/by_BY.tsx
  components/date-picker/locale/by_BY.tsx
  components/locale-provider/__tests__/index.test.js
  components/locale-provider/by_BY.tsx
  components/locale/by_BY.tsx
  components/time-picker/locale/by_BY.tsx
  docs/react/i18n.en-US.md
  docs/react/i18n.zh-CN.md
  package.json
Labels: PR: unreviewed

#27060 chore: add genetate authors and update authors
  AUTHORS.txt
  package.json
  scripts/generate-authors.js
Labels: PR: reviewed-approved

#26952 feat: TextArea showCount
  components/auto-complete/__tests__/__snapshots__/demo.test.js.snap
  components/comment/__tests__/__snapshots__/demo.test.js.snap
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/input/TextArea.tsx
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/__tests__/__snapshots__/textarea.test.js.snap
  components/input/__tests__/textarea.test.js
  components/input/demo/textarea-show-count.md
  components/input/index.en-US.md
  components/input/index.zh-CN.md
  components/input/style/index.less
  components/typography/__tests__/index.test.js
Labels: PR: reviewed-approved

#27065 test: fix test cov
  components/form/FormItemLabel.tsx
  components/form/__tests__/__snapshots__/list.test.js.snap
  components/form/__tests__/list.test.js
  components/upload/__tests__/__snapshots__/uploadlist.test.js.snap
  components/upload/__tests__/uploadlist.test.js
Labels: PR: reviewed-approved

#27071 docs: update Image API
  components/image/index.en-US.md
  components/image/index.zh-CN.md
Labels: PR: unreviewed

#27073 docs: Update Image index.zh-CN.md
  components/image/index.zh-CN.md
Labels: PR: unreviewed

#27075 feat: InputNumber support onStep
  components/input-number/__tests__/index.test.js
  components/input-number/index.en-US.md
  components/input-number/index.tsx
  components/input-number/index.zh-CN.md
  package.json
Labels: PR: unreviewed

#27074 docs: ✨ release 4.7.0
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#27077 docs: fix behaviour of modal draggable zone
  components/modal/demo/modal-render.md
Labels: PR: unreviewed

#27079 fix: add missing translations in Spanish (es_ES) locale
  components/locale/es_ES.tsx
Labels: PR: reviewed-approved

#27094 docs: update modal version column
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
Labels: PR: reviewed-approved

#27093 docs: update Typography.Text
  components/typography/index.en-US.md
  components/typography/index.zh-CN.md
Labels: PR: unreviewed

#27087 refactor(image): improve code
  components/image/index.tsx
Labels: PR: unreviewed

#27086 refactor(input-number): useContext
  components/input-number/index.tsx
Labels: PR: unreviewed

#27096 docs: update menu api
  components/menu/demo/switch-mode.md
  components/menu/demo/theme.md
  components/menu/index.en-US.md
  components/menu/index.zh-CN.md
Labels: PR: unreviewed

#27098 style: optimize Input.TextArea count style in rtl
  components/input/TextArea.tsx
  components/input/style/index.less
  components/input/style/rtl.less
Labels: PR: reviewed-approved

#27097 refactor(checkable-tag): improve code
  components/tag/CheckableTag.tsx
Labels: PR: unreviewed

#27101 style: 💄 fix Pickers wrong animation direction
  components/back-top/style/index.less
  components/cascader/style/index.less
  components/date-picker/style/index.less
  components/dropdown/style/index.less
  components/input-number/style/index.less
  components/select/style/multiple.less
  components/style/mixins/iconfont.less
  components/table/style/index.less
  components/tag/style/index.less
  components/transfer/style/index.less
  components/tree/style/mixin.less
  components/upload/style/index.less
Labels: PR: unreviewed

#27104 style: fix Typography Link color
  components/typography/__tests__/__snapshots__/demo.test.js.snap
  components/typography/demo/basic.md
  components/typography/style/index.less
Labels: PR: unreviewed

#27106 docs: fix url
  docs/spec/copywriting.zh-CN.md
Labels: PR: unreviewed

#27107 docs: fix invalid url
  docs/spec/copywriting.zh-CN.md
Labels: PR: unreviewed

#27110 feat: Input.Textarea support size props
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/config-provider/demo/size.md
  components/input/TextArea.tsx
  components/input/__tests__/__snapshots__/textarea.test.js.snap
  components/input/__tests__/textarea.test.js
Labels: PR: unreviewed

#27122 chore: merge 4.7.0 release to feature
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/back-top/style/index.less
  components/cascader/style/index.less
  components/date-picker/style/index.less
  components/dropdown/style/index.less
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/image/index.en-US.md
  components/image/index.tsx
  components/image/index.zh-CN.md
  components/input-number/__tests__/index.test.js
  components/input-number/index.en-US.md
  components/input-number/index.tsx
  components/input-number/index.zh-CN.md
  components/input-number/style/index.less
  components/input/TextArea.tsx
  components/input/style/index.less
  components/input/style/rtl.less
  components/locale/es_ES.tsx
  components/menu/demo/switch-mode.md
  components/menu/demo/theme.md
  components/menu/index.en-US.md
  components/menu/index.zh-CN.md
  components/modal/demo/modal-render.md
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
  components/select/style/multiple.less
  components/style/mixins/iconfont.less
  components/table/style/index.less
  components/tag/CheckableTag.tsx
  components/tag/style/index.less
  components/transfer/style/index.less
  components/tree/style/mixin.less
  components/typography/__tests__/__snapshots__/demo.test.js.snap
  components/typography/demo/basic.md
  components/typography/index.en-US.md
  components/typography/index.zh-CN.md
  components/typography/style/index.less
  components/upload/style/index.less
  docs/spec/copywriting.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#27119 style: fix Typography Link color
  components/typography/style/index.less
Labels: PR: unreviewed

#27125 fix: radio checked cursor style when disabled
  components/radio/style/index.less
Labels: PR: unreviewed

#27134 fix: Divider color with text
  components/divider/style/index.less
Labels: PR: unreviewed

#27129 refactor: 📦 some styles to reduce css bundle size
  components/auto-complete/__tests__/__snapshots__/demo.test.js.snap
  components/badge/Ribbon.tsx
  components/badge/__tests__/__snapshots__/demo.test.js.snap
  components/badge/__tests__/__snapshots__/index.test.js.snap
  components/badge/style/ribbon.less
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/form/style/status.less
  components/input/ClearableLabeledInput.tsx
  components/input/Search.tsx
  components/input/__tests__/Search.test.js
  components/input/__tests__/__snapshots__/Search.test.js.snap
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/__tests__/__snapshots__/index.test.js.snap
  components/input/__tests__/__snapshots__/textarea.test.js.snap
  components/input/__tests__/textarea.test.js
  components/input/demo/search-input-loading.md
  components/input/demo/search-input.md
  components/input/style/allow-clear.less
  components/input/style/mixin.less
  components/input/style/rtl.less
  components/input/style/search-input.less
  components/layout/style/index.less
  components/layout/style/light.less
  components/tree/__tests__/__snapshots__/demo.test.js.snap
Labels: PR: reviewed-approved

#27143 test: ✅ fix modal test cases
  components/modal/__tests__/confirm.test.js
  package.json
Labels: PR: unreviewed

#27127 refactor(grid): useContext and improve code
  components/grid/col.tsx
  components/grid/row.tsx
Labels: PR: unreviewed

#27128 refactor(result): useContext and improve code
  components/result/index.tsx
Labels: PR: unreviewed

#27145 fix: 🐛 Tabs animated={true} should works
  components/tabs/index.en-US.md
  components/tabs/index.zh-CN.md
  package.json
Labels: PR: unreviewed

#27137 chore: merge master into feature
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/auto-complete/__tests__/__snapshots__/demo.test.js.snap
  components/badge/Ribbon.tsx
  components/badge/__tests__/__snapshots__/demo.test.js.snap
  components/badge/__tests__/__snapshots__/index.test.js.snap
  components/badge/style/ribbon.less
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/divider/style/index.less
  components/form/style/status.less
  components/grid/col.tsx
  components/grid/row.tsx
  components/input/ClearableLabeledInput.tsx
  components/input/Search.tsx
  components/input/__tests__/Search.test.js
  components/input/__tests__/__snapshots__/Search.test.js.snap
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/__tests__/__snapshots__/index.test.js.snap
  components/input/__tests__/__snapshots__/textarea.test.js.snap
  components/input/__tests__/textarea.test.js
  components/input/demo/search-input-loading.md
  components/input/demo/search-input.md
  components/input/style/allow-clear.less
  components/input/style/mixin.less
  components/input/style/rtl.less
  components/input/style/search-input.less
  components/layout/style/index.less
  components/layout/style/light.less
  components/modal/__tests__/confirm.test.js
  components/popconfirm/index.zh-CN.md
  components/radio/style/index.less
  components/result/index.tsx
  components/tabs/index.en-US.md
  components/tabs/index.zh-CN.md
  components/tree/__tests__/__snapshots__/demo.test.js.snap
  components/typography/style/index.less
  package.json
  site/theme/static/common.less
Labels: PR: unreviewed

#27150 fix:Typography miss block & pre style
  components/typography/__tests__/__snapshots__/demo.test.js.snap
  components/typography/demo/basic.md
  components/typography/style/index.less
Labels: PR: unreviewed

#27156 fix(date-picker): showTime should work correctly when format is function
  components/date-picker/__tests__/DatePicker.test.js
  components/date-picker/generatePicker/index.tsx
Labels: PR: unreviewed

#27154 fix: 💄 Layout.Sider collapsedWidth cannot work without @menu-collapsed-width
  components/layout/Sider.tsx
  components/layout/__tests__/__snapshots__/demo.test.js.snap
  components/layout/demo/side.md
  components/menu/__tests__/__snapshots__/demo.test.js.snap
  components/menu/__tests__/index.test.js
  components/menu/demo/sider-current.md
  components/menu/style/index.less
  components/menu/style/rtl.less
  package.json
Labels: PR: unreviewed

#27161 docs: Update RecommendPage.tsx
  site/theme/template/Home/RecommendPage.tsx
Labels: PR: unreviewed

#27165 fix: 🐛 Dropdown icon margin style
  components/dropdown/style/index.less
Labels: PR: unreviewed

#27175 fix: if form warp drawer, close button will trigger submit
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/drawer/__tests__/__snapshots__/Drawer.test.js.snap
  components/drawer/__tests__/__snapshots__/DrawerEvent.test.js.snap
  components/drawer/index.tsx
Labels: PR: reviewed-approved

#27164 fix: add optional rules property
  components/form/FormList.tsx
Labels: PR: reviewed-approved

#26713 feat: Image support getPopupContainer
  components/image/index.en-US.md
  components/image/index.zh-CN.md
  package.json
Labels: PR: unreviewed

#27181 refactor: improve useCombinedRefs code
  components/_util/hooks/useCombinedRefs.tsx
  components/slider/SliderTooltip.tsx
Labels: PR: reviewed-approved

#27184 Update MorePage.tsx
  site/theme/template/Home/MorePage.tsx
Labels: PR: unreviewed

#27187 fix: Cascader className duplicate
  components/cascader/index.tsx
Labels: PR: unreviewed

#27159 docs(button): improve docs and shape remove undeclared doc type
  components/button/button.tsx
  components/button/index.en-US.md
  components/button/index.zh-CN.md
  components/button/style/index.less
Labels: PR: unreviewed

#27189 fix: notification width in small screen
  components/notification/style/index.less
Labels: PR: unreviewed

#27191 fix: clear Password value attribute in controlled mode
  components/input/Input.tsx
Labels: PR: unreviewed

#26422 fix: form customizing mixin
  components/form/style/mixin.less
  components/form/style/status.less
Labels: PR: unreviewed

#27195 style(descriptions): fix content overflow
  components/descriptions/style/index.less
Labels: PR: reviewed-approved

#27196 docs: Corrected "onFilter" definition for Table Column in docs (English)
  components/table/index.en-US.md
Labels: PR: unreviewed

#27158 refactor(typography): remove deprecated
  components/typography/Base.tsx
Labels: PR: unreviewed

#27147 refactor(checkbox-group): rewrite with hook
  components/checkbox/Group.tsx
  components/checkbox/__tests__/group.test.js
Labels: PR: reviewed-approved

#27212 docs(dropdown): improve type
  components/dropdown/index.en-US.md
  components/dropdown/index.zh-CN.md
Labels: PR: reviewed-approved

#27211 docs: add 4.7.1 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#27213 docs(dropdown): improve api path and function type
  components/dropdown/index.en-US.md
  components/dropdown/index.zh-CN.md
Labels: PR: unreviewed

#27216 fix: TextArea wrapper with div when `!showCount`
  components/auto-complete/__tests__/__snapshots__/demo.test.js.snap
  components/comment/__tests__/__snapshots__/demo.test.js.snap
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/input/TextArea.tsx
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/__tests__/__snapshots__/textarea.test.js.snap
  components/input/__tests__/textarea.test.js
Labels: PR: reviewed-approved

#27227 style: fix Sider light theme
  components/layout/style/light.less
Labels: PR: unreviewed

#27229 docs: ✨ release 4.7.2
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#27232 🏗 scrtipt: changelog support windows
  scripts/print-changelog.js
Labels: PR: reviewed-approved

#27231 fix: Checkbox Group TS typo
  components/checkbox/Group.tsx
  components/checkbox/__tests__/type.test.tsx
Labels: PR: unreviewed

#27236 docs: improve faq
  docs/react/faq.en-US.md
  docs/react/faq.zh-CN.md
Labels: PR: unreviewed

#27226 fix: Tag component close icon display bug
  components/tag/__tests__/__snapshots__/demo.test.js.snap
  components/tag/index.tsx
Labels: PR: unreviewed

#27246 docs(input): add showCount version
  components/input/index.en-US.md
  components/input/index.zh-CN.md
Labels: PR: unreviewed

#27221 fix: Editable Typography in Card title style problems
  components/card/style/index.less
Labels: PR: unreviewed

#27253 fix: horizontal Menu in flex layout
  components/menu/style/index.less
Labels: PR: unreviewed

#27259 fix: changed sorting and validation labels to proper English
  components/locale/default.tsx
  components/locale/en_GB.tsx
  components/locale/ga_IE.tsx
Labels: PR: unreviewed

#27261 fix: duplicated className on Search[allowClear]
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/input/ClearableLabeledInput.tsx
  components/input/__tests__/Search.test.js
Labels: PR: unreviewed

#27112 docs: fix invalid disabledDate of RangePicker demo
  components/date-picker/demo/select-in-range.md
Labels: PR: unreviewed

#27265 docs: change log
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed

#27266 chore: improve code style
  README-zh_CN.md
  components/auto-complete/__tests__/focus.test.js
  components/breadcrumb/__tests__/router.test.js
  components/card/__tests__/index.test.js
  components/cascader/__tests__/type.test.tsx
  components/date-picker/__tests__/other.test.js
  components/date-picker/__tests__/utils.js
  components/descriptions/style/index.less
  components/list/__tests__/index.test.js
  components/locale-provider/by_BY.tsx
  components/locale/ar_EG.tsx
  components/result/__tests__/type.test.tsx
  components/select/__tests__/index.test.js
  components/skeleton/Paragraph.tsx
  components/spin/__tests__/delay.test.js
  components/spin/__tests__/index.test.js
  components/statistic/__tests__/index.test.js
  components/style/mixins/customize.less
  components/timeline/__tests__/index.test.js
  components/transfer/__tests__/list.test.js
  scripts/previewEditor/template.html
  site/theme/static/template.html
  site/theme/template/Content/Demo/CodePreview.jsx
  site/theme/template/Home/RecommendPage.tsx
Labels: PR: unreviewed

#27270 chore: add prettier ignore and format demo
  .prettierignore
  SECURITY.md
  components/calendar/demo/customize-header.md
  components/cascader/demo/custom-dropdown.md
  components/comment/demo/list.md
  components/form/demo/control-hooks.md
  components/form/demo/register.md
  components/list/demo/grid-test.md
  components/modal/demo/modal-render.md
  components/modal/demo/width.md
  components/radio/demo/badge.md
  components/time-picker/demo/basic.md
  components/time-picker/demo/disabled.md
  components/time-picker/demo/hide-column.md
  components/time-picker/demo/value.md
  components/tree-select/demo/async.md
  components/tree/demo/draggable.md
  components/tree/demo/line.md
Labels: PR: unreviewed

#27271 chore: upgrade @ant-design/tools
  package.json
Labels: PR: unreviewed

#27283 docs: Document default for button size
  components/button/index.en-US.md
Labels: PR: unreviewed

#27292 feat: Modal method add bodyStyle
  components/modal/ConfirmDialog.tsx
  components/modal/Modal.tsx
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
Labels: PR: reviewed-approved

#27291 docs: image feat add version
  components/image/index.en-US.md
  components/image/index.zh-CN.md
Labels: PR: reviewed-approved

#27300 docs(Modal): add version
  components/modal/index.en-US.md
Labels: PR: reviewed-approved

#27304 docs(modal): improve style type
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
Labels: PR: unreviewed

#27285 style: notification text add word-wrap
  components/notification/style/index.less
Labels: PR: reviewed-approved

#27309 add description of v3 to v4
  docs/react/migration-v4.zh-CN.md
Labels: PR: unreviewed

#26811 feat: add loading prop for Statistic
  components/statistic/Statistic.tsx
  components/statistic/__tests__/__snapshots__/demo.test.js.snap
  components/statistic/__tests__/index.test.js
  components/statistic/demo/basic.md
  components/statistic/index.en-US.md
  components/statistic/index.zh-CN.md
  components/statistic/style/index.tsx
Labels: PR: reviewed-approved

#27305 refactor(responsive-observe): improve typescript type
  components/_util/responsiveObserve.ts
Labels: PR: unreviewed

#27312 feat: change object-fit of UploadList to contain
  components/upload/__tests__/uploadlist.test.js
  components/upload/style/index.less
  components/upload/utils.tsx
Labels: PR: unreviewed

#27319 refactor: Update rc-field-form version
  components/form/__tests__/__snapshots__/demo.test.js.snap
  package.json
Labels: PR: reviewed-approved

#27328 fix: Typography ellipsis title
  components/typography/Base.tsx
  components/typography/__tests__/index.test.js
Labels: PR: unreviewed

#27329 docs: Fix the childrenColumnN attribute type of the table component
  components/table/index.en-US.md
  components/table/index.zh-CN.md
Labels: PR: unreviewed

#27336 feat: 1024
  site/theme/template/Home/RecommendPage.tsx
Labels: PR: reviewed-approved

#27322 feat: ConfigProvider add form requiredMark
  components/config-provider/__tests__/__snapshots__/form.test.js.snap
  components/config-provider/__tests__/form.test.js
  components/config-provider/context.tsx
  components/config-provider/index.en-US.md
  components/config-provider/index.tsx
  components/config-provider/index.zh-CN.md
  components/form/Form.tsx
Labels: PR: partially-approved

#27315 docs(select): improve size default value
  components/select/index.en-US.md
  components/select/index.zh-CN.md
Labels: PR: unreviewed

#27163 feat: modal.update() supports functional updating (#27162)
  components/modal/__tests__/confirm.test.js
  components/modal/confirm.tsx
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
Labels: PR: reviewed-approved

#27343 fix: Form warning
  components/config-provider/context.tsx
  components/drawer/__tests__/Drawer.test.js
  components/drawer/index.tsx
Labels: PR: unreviewed

#27318 refactor(select): rewrite with hook
  components/auto-complete/index.tsx
  components/calendar/__tests__/__snapshots__/index.test.js.snap
  components/calendar/__tests__/index.test.js
  components/select/__tests__/index.test.js
  components/select/index.tsx
Labels: PR: unreviewed

#27348 feat: Avatar.Group add size props
  components/avatar/__tests__/__snapshots__/demo.test.js.snap
  components/avatar/avatar.tsx
  components/avatar/demo/group.md
  components/avatar/group.tsx
  components/avatar/index.en-US.md
  components/avatar/index.zh-CN.md
Labels: PR: partially-approved

#27325 fix: border style of Input.Search when allowClear
  components/auto-complete/__tests__/__snapshots__/demo.test.js.snap
  components/input/Search.tsx
  components/input/__tests__/__snapshots__/Search.test.js.snap
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/demo/group.md
  components/input/demo/search-input.md
  components/input/style/affix.less
  components/input/style/mixin.less
  components/input/style/rtl.less
  components/input/style/search-input.less
Labels: PR: unreviewed

#27350 docs: 4.7.3 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#27352 chore: improve useCombinedRefs
  components/_util/hooks/useCombinedRefs.tsx
Labels: PR: unreviewed

#27314 fix: fix package.json import for webpack@5 compatibility with antd 3.x
  components/version/index.tsx
Labels: PR: reviewed-approved

#27363 chore: Adjust collapse arrow position align with first line
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/_util/hooks/useCombinedRefs.tsx
  components/auto-complete/__tests__/__snapshots__/demo.test.js.snap
  components/collapse/style/index.less
  components/input/Search.tsx
  components/input/__tests__/__snapshots__/Search.test.js.snap
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/demo/group.md
  components/input/demo/search-input.md
  components/input/style/affix.less
  components/input/style/mixin.less
  components/input/style/rtl.less
  components/input/style/search-input.less
  docs/react/introduce.en-US.md
  docs/react/introduce.zh-CN.md
  package.json
  site/theme/static/markdown.less
Labels: PR: reviewed-approved

#27365 feat: Table summary support align
  package.json
Labels: PR: reviewed-approved

#27367 docs: docs upgrade
  components/config-provider/demo/locale.md
  components/config-provider/index.en-US.md
  components/config-provider/index.zh-CN.md
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
  components/locale/ku_IQ.tsx
  docs/react/getting-started.zh-CN.md
  docs/react/i18n.en-US.md
  docs/react/i18n.zh-CN.md
  site/theme/template/Layout/index.jsx
Labels: PR: unreviewed

#27369 docs: optimize layout demo css
  components/layout/demo/basic.md
  components/layout/demo/custom-trigger-debug.md
  components/layout/demo/custom-trigger.md
  components/layout/demo/side.md
  components/layout/demo/top-side-2.md
  components/layout/demo/top-side.md
  components/layout/demo/top.md
Labels: PR: unreviewed

#27378 fix: select focus style in form when has error
  components/form/style/status.less
Labels: PR: unreviewed

#27375 fix: Desc label with flex node
  components/descriptions/__tests__/__snapshots__/demo.test.js.snap
  components/descriptions/demo/text.md
  components/descriptions/style/index.less
Labels: PR: unreviewed

#27379 docs: ⚡️ add D2 forum promote link
  site/theme/template/Home/RecommendPage.tsx
Labels: PR: unreviewed

#27383 fix: Invalid regular expression for particular ellipsis content
  components/typography/Base.tsx
  components/typography/__tests__/index.test.js
Labels: PR: reviewed-approved

#27386 fix: Tree showLine mutiple line title breaks
  components/transfer/__tests__/__snapshots__/demo.test.js.snap
  components/tree/__tests__/__snapshots__/demo.test.js.snap
  components/tree/__tests__/__snapshots__/directory.test.js.snap
  components/tree/__tests__/__snapshots__/index.test.js.snap
  components/tree/demo/line.md
  components/tree/style/mixin.less
  package.json
Labels: PR: partially-approved

#27380 test: fix ui test base trigger
  Dockerfile.ui-test
  azure-pipelines.yml
  docker-compose.yml
Labels: PR: unreviewed

#27407 chore: resolutions fixed typescript version
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#27410 docs: update Tabs api
  components/tabs/index.en-US.md
  components/tabs/index.zh-CN.md
Labels: PR: unreviewed

#27412 fix: Not merge additional data
  components/table/__tests__/Table.pagination.test.js
  components/table/hooks/usePagination.ts
Labels: PR: unreviewed

#27406 fix: Fix the width of the step content in the horizontal direction
  components/steps/style/progress-dot.less
Labels: PR: reviewed-approved

#27394 test: argos-ci test
  azure-pipelines.yml
Labels: PR: unreviewed

#27416 docs: update Tabs api
  components/tabs/index.en-US.md
  components/tabs/index.zh-CN.md
Labels: PR: reviewed-approved

#27376 feat: components used in confirm title and content support prefixCls
  components/modal/ConfirmDialog.tsx
Labels: PR: reviewed-approved

#27417 fix: Table onShowSizeChange trigger twice
  components/table/__tests__/Table.pagination.test.js
  components/table/hooks/usePagination.ts
Labels: PR: unreviewed

#27420 test: improve argos-ci test
  tests/shared/imageTest.ts
Labels: PR: unreviewed

#27421 chore: merge master to feature
  Dockerfile.ui-test
  azure-pipelines.yml
  components/steps/style/progress-dot.less
  components/table/__tests__/Table.pagination.test.js
  components/table/hooks/usePagination.ts
  components/tabs/index.en-US.md
  components/tabs/index.zh-CN.md
  docker-compose.yml
  tests/shared/imageTest.ts
Labels: PR: reviewed-approved

#27433 test: ui test use secret and include branch
  azure-pipelines.yml
Labels: PR: unreviewed

#27434 fix: lock ignore-emit-webpack-plugin version
  package.json
Labels: PR: unreviewed

#27438 fix: RangePicker border style when has same data
  components/date-picker/style/panel.less
Labels: PR: unreviewed

#27440 test: enable pr test action
  .github/workflows/test.yml
Labels: PR: unreviewed

#27453 test: github secret token
  .github/workflows/test.yml
Labels: PR: unreviewed

#27455 test: fix lose test script
  .github/workflows/test.yml
  .github/workflows/ui.yml
Labels: PR: unreviewed

#27462 fix: Input[allowClear] className
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/input/ClearableLabeledInput.tsx
  components/input/__tests__/Search.test.js
  components/input/__tests__/__snapshots__/Search.test.js.snap
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/__tests__/__snapshots__/index.test.js.snap
  components/input/__tests__/index.test.js
Labels: PR: unreviewed

#27458 test: remove azure ui test and try test pr github action
  .github/workflows/ui.yml
  azure-pipelines.yml
Labels: PR: unreviewed

#27466 test: fix ui push trigger branch
  .github/workflows/ui.yml
Labels: PR: unreviewed

#27467 docs: update description of optionFilterProp in Select
  components/select/index.en-US.md
  components/select/index.zh-CN.md
Labels: PR: unreviewed

#27452 docs: Update home page articles
  site/theme/template/Home/RecommendPage.tsx
Labels: PR: unreviewed

#27472 chore: fix lock version
  package.json
Labels: PR: reviewed-approved

#27272 Fix Modal missing modalRender prop
  components/modal/ConfirmDialog.tsx
  components/modal/Modal.tsx
Labels: PR: unreviewed

#27465 docs: add techui promotion
  components/overview/index.zh-CN.md
  site/theme/template/Layout/Header/Navigation.tsx
  site/theme/template/Layout/Header/index.tsx
Labels: PR: unreviewed
