Repository ant-design/ant-design, pull requests merged in 2020-05, with the labels that each got.

#23797 style: optimize input search style in rtl
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/demo/group.md
  components/input/demo/search-input.md
  components/input/style/rtl.less
Labels: PR: unreviewed

#23806 fix: Table selection col width not correct
  components/table/__tests__/__snapshots__/Table.rowSelection.test.js.snap
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/hooks/useSelection.tsx
  components/table/style/index.less
  components/transfer/__tests__/__snapshots__/demo.test.js.snap
  package.json
Labels: PR: unreviewed

#23808 docs: Add FAQ of form onFieldsChange
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: PR: unreviewed

#23811 style: 💄 Fix DatePicker clear icon style
  components/date-picker/style/index.less
Labels: PR: unreviewed

#23776 style: optimize button loading style in rtl
  components/button/style/rtl.less
Labels: PR: unreviewed

#23815 Revert "[Snyk] Fix for 1 vulnerabilities"
  .snyk
  package.json
Labels: PR: unreviewed

#23816 chore: upgrade eslint-plugin-react-hooks
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/list/__tests__/__snapshots__/pagination.test.js.snap
  package.json
Labels: PR: unreviewed

#23766 fix(switch): loading color for dark theme
  components/switch/style/index.less
Labels: PR: unreviewed

#23631 refactor(timeline): rewrite with hook
  components/timeline/Timeline.tsx
  components/timeline/TimelineItem.tsx
Labels: PR: unreviewed

#23818 fix: DatePicker miss placeholder when it's undefined
  components/date-picker/__tests__/DatePicker.test.js
  components/date-picker/__tests__/RangePicker.test.js
  components/date-picker/generatePicker/generateRangePicker.tsx
  components/date-picker/generatePicker/generateSinglePicker.tsx
  components/date-picker/util.ts
  components/form/__tests__/__snapshots__/demo.test.js.snap
Labels: PR: unreviewed

#23821 docs: fix less-loader@6 customize-cra
  docs/react/use-with-create-react-app.en-US.md
  docs/react/use-with-create-react-app.zh-CN.md
Labels: PR: unreviewed

#23824 docs: Update Upload index.zh-CN.md
  components/upload/index.zh-CN.md
Labels: PR: unreviewed

#23825 docs: Update Upload index.en-US.md
  components/upload/index.en-US.md
Labels: PR: unreviewed

#23826 fix: Modal async
  components/config-provider/__tests__/locale.test.js
  components/locale-provider/__tests__/index.test.js
  components/modal/__tests__/confirm.test.js
  components/modal/confirm.tsx
Labels: PR: unreviewed

#23831 docs: Update notification onClose desc
  components/notification/index.en-US.md
  components/notification/index.zh-CN.md
Labels: PR: unreviewed

#23832 fix: Menu a color
  components/menu/__tests__/__snapshots__/demo.test.js.snap
  components/menu/demo/switch-mode.md
  components/menu/style/index.less
Labels: PR: unreviewed

#23833 docs: Add table render cache faq
  components/table/index.en-US.md
  components/table/index.zh-CN.md
Labels: PR: unreviewed

#23835 fix: Textarea height
  components/input/style/affix.less
  components/table/__tests__/__snapshots__/demo.test.js.snap
Labels: PR: unreviewed

#23845 chore: Feature merge master
  .snyk
  components/button/style/rtl.less
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/config-provider/__tests__/locale.test.js
  components/date-picker/__tests__/DatePicker.test.js
  components/date-picker/__tests__/RangePicker.test.js
  components/date-picker/generatePicker/generateRangePicker.tsx
  components/date-picker/generatePicker/generateSinglePicker.tsx
  components/date-picker/style/index.less
  components/date-picker/util.ts
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/input/style/affix.less
  components/list/__tests__/__snapshots__/pagination.test.js.snap
  components/locale-provider/__tests__/index.test.js
  components/menu/__tests__/__snapshots__/demo.test.js.snap
  components/menu/__tests__/index.test.js
  components/menu/demo/switch-mode.md
  components/menu/index.tsx
  components/menu/style/index.less
  components/modal/__tests__/confirm.test.js
  components/modal/confirm.tsx
  components/notification/index.en-US.md
  components/notification/index.zh-CN.md
  components/switch/style/index.less
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/demo/basic.md
  components/table/demo/bordered.md
  components/table/demo/jsx.md
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/timeline/Timeline.tsx
  components/timeline/TimelineItem.tsx
  components/upload/index.en-US.md
  components/upload/index.zh-CN.md
  docs/react/use-in-typescript.en-US.md
  docs/react/use-in-typescript.zh-CN.md
  docs/react/use-with-create-react-app.en-US.md
  docs/react/use-with-create-react-app.zh-CN.md
  package.json
Labels: PR: reviewed-changes-requested

#23846 fix: Form.Item warning for initialValue
  components/form/FormItem.tsx
  components/form/__tests__/index.test.js
Labels: PR: unreviewed

#23844 docs: improve link path
  components/list/demo/resposive.md
  components/rate/index.en-US.md
  components/rate/index.zh-CN.md
  docs/react/getting-started.en-US.md
  docs/react/introduce.en-US.md
  docs/react/introduce.zh-CN.md
  docs/spec/detail-page.md
  docs/spec/form-page.md
  docs/spec/introduce.en-US.md
  docs/spec/overview.en-US.md
  docs/spec/research-form.zh-CN.md
  docs/spec/research-result.zh-CN.md
Labels: PR: unreviewed

#23850 test: ✅ fix progress snapshot
  components/progress/__tests__/__snapshots__/demo.test.js.snap
  components/progress/__tests__/__snapshots__/index.test.js.snap
Labels: PR: unreviewed

#23853 chore: merge master into feature
  components/form/FormItem.tsx
  components/form/__tests__/index.test.js
  components/list/demo/resposive.md
  components/progress/__tests__/__snapshots__/demo.test.js.snap
  components/progress/__tests__/__snapshots__/index.test.js.snap
  components/rate/index.en-US.md
  components/rate/index.zh-CN.md
  docs/react/getting-started.en-US.md
  docs/react/introduce.en-US.md
  docs/react/introduce.zh-CN.md
  docs/spec/detail-page.md
  docs/spec/form-page.md
  docs/spec/introduce.en-US.md
  docs/spec/overview.en-US.md
  docs/spec/research-form.zh-CN.md
  docs/spec/research-result.zh-CN.md
Labels: PR: reviewed-changes-requested

#23852 test: fix 3.x snapshot
  components/progress/__tests__/__snapshots__/demo.test.js.snap
  components/progress/__tests__/__snapshots__/index.test.js.snap
  components/typography/Editable.tsx
Labels: PR: unreviewed

#23849 refactor: Use flex of divider
  components/divider/style/index.less
Labels: PR: reviewed-approved

#23867 chore: Update Popconfirm & Modal okType type
  components/button/button.tsx
  components/modal/ActionButton.tsx
  components/modal/Modal.tsx
  components/modal/__tests__/Modal.test.js
  components/modal/__tests__/type.test.tsx
  components/popconfirm/__tests__/type.test.tsx
  components/popconfirm/index.tsx
Labels: PR: unreviewed

#23868 Update index.zh-CN.md
  components/button/index.zh-CN.md
Labels: PR: unreviewed

#23855 style: optimize steps style
  components/steps/style/rtl.less
  components/steps/style/vertical.less
  components/style/themes/compact.less
  components/style/themes/default.less
Labels: PR: unreviewed

#23870 test: upgrade jest to 26.0.0
  package.json
Labels: PR: unreviewed

#23841 feat: ConfigProvider support virtual and dropdownMatchSelectWidth
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/config-provider/__tests__/components.test.js
  components/config-provider/context.tsx
  components/config-provider/index.en-US.md
  components/config-provider/index.tsx
  components/config-provider/index.zh-CN.md
  components/select/index.tsx
  components/tree-select/index.tsx
  components/tree/Tree.tsx
Labels: PR: reviewed-approved

#23872 feat: Cell support shouldCellUpdate
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#23871 fix: InputNumber onChange type
  components/input-number/index.tsx
Labels: PR: unreviewed

#23875 fix: FormItem getValueProps warning
  components/form/FormItem.tsx
  components/form/__tests__/index.test.js
Labels: PR: reviewed-changes-requested

#23878 chore: @radio-solid-checked-color typo
  components/style/themes/dark.less
  components/style/themes/default.less
Labels: PR: unreviewed

#23880 test: ✅ increase Anchor code cov
  components/anchor/Anchor.tsx
  components/anchor/__tests__/Anchor.test.tsx
Labels: PR: unreviewed

#23884 test: Add Table sorters test coverage
  components/table/__tests__/Table.sorter.test.js
Labels: PR: reviewed-changes-requested

#23885 test: ✅ increase Transfer code cov
  components/transfer/index.tsx
Labels: PR: unreviewed

#22552 feat: 💄 Add text type Button
  components/button/__tests__/__snapshots__/demo.test.ts.snap
  components/button/__tests__/__snapshots__/type.test.tsx.snap
  components/button/__tests__/type.test.tsx
  components/button/button.tsx
  components/button/demo/basic.md
  components/button/demo/disabled.md
  components/button/demo/ghost.md
  components/button/index.en-US.md
  components/button/index.zh-CN.md
  components/button/style/index.less
  components/button/style/mixin.less
  components/style/themes/dark.less
  components/style/themes/default.less
Labels: PR: unreviewed

#23895 docs: fix moment locale faq
  components/config-provider/index.en-US.md
  components/config-provider/index.zh-CN.md
  package.json
Labels: PR: unreviewed

#23896 docs: 📖 refactor tutorial code to React hooks
  docs/react/getting-started.en-US.md
  docs/react/getting-started.zh-CN.md
  docs/react/use-in-typescript.en-US.md
  docs/react/use-in-typescript.zh-CN.md
  docs/react/use-with-create-react-app.en-US.md
  docs/react/use-with-create-react-app.zh-CN.md
Labels: PR: unreviewed

#23897 docs: update contributing.zh-CN.md
  docs/react/contributing.zh-CN.md
Labels: PR: unreviewed

#23901 docs: 📖 update notFoundContent
  components/auto-complete/index.en-US.md
  components/auto-complete/index.zh-CN.md
  components/select/index.en-US.md
  components/select/index.zh-CN.md
Labels: PR: unreviewed

#23905 docs: improve popconfirm
  components/popconfirm/index.en-US.md
  components/popconfirm/index.zh-CN.md
Labels: PR: unreviewed

#23914 chore: Adjust table col className priority
  components/table/__tests__/__snapshots__/Table.rowSelection.test.js.snap
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/hooks/useSelection.tsx
  components/table/style/index.less
  components/transfer/__tests__/__snapshots__/demo.test.js.snap
Labels: PR: unreviewed

#23915 test: Fix Table test
  components/table/ExpandIcon.tsx
Labels: PR: unreviewed

#23916 revert: test: Fix Table test
  components/table/ExpandIcon.tsx
Labels: PR: unreviewed

#23917 docs: Fix English syntax in heading
  docs/react/replace-moment.en-US.md
Labels: PR: reviewed-approved

#23921 style: optimize layout rtl
  components/layout/style/index.less
  components/layout/style/rtl.less
Labels: PR: unreviewed

#23924 fix: Fix form input shaking
  components/form/FormItem.tsx
  components/form/__tests__/__snapshots__/index.test.js.snap
  components/form/__tests__/index.test.js
Labels: PR: reviewed-changes-requested

#23925 fix: Drawer with percentage width cannot show when no mask
  components/drawer/style/drawer.less
Labels: PR: unreviewed

#23928 docs: improve tooltip
  components/tooltip/index.en-US.md
  components/tooltip/index.zh-CN.md
Labels: PR: unreviewed

#23926 feat: fa_IR is updated based on latest options.
  components/locale/fa_IR.tsx
Labels: PR: unreviewed

#23932 chore: 🔨 replace css-animation by @ant-design/css-animation
  .jest.js
  components/_util/openAnimation.tsx
  components/_util/wave.tsx
  package.json
  typings/custom-typings.d.ts
Labels: PR: unreviewed

#23859 feat: Adds default English localisations for Form.
  components/locale/default.tsx
Labels: PR: reviewed-approved

#23939 docs: add modao.cc resource link
  docs/resources.en-US.md
  docs/resources.zh-CN.md
Labels: PR: unreviewed

#23944 docs: Update cra doc
  docs/react/use-in-typescript.en-US.md
  docs/react/use-in-typescript.zh-CN.md
  docs/react/use-with-create-react-app.en-US.md
Labels: PR: unreviewed

#23946 docs: fix typo
  components/grid/demo/useBreakpoint.md
Labels: PR: unreviewed

#23945 fix: FormItem with help
  components/form/FormItem.tsx
Labels: PR: reviewed-approved

#23952 docs(Divider): Move `Divider` to layout
  components/divider/index.en-US.md
  components/divider/index.zh-CN.md
Labels: PR: unreviewed

#23937 refactor: 🆙 upgrade rc-animate to 3.x
  components/carousel/__tests__/__snapshots__/demo.test.js.snap
  package.json
Labels: PR: unreviewed

#23953 docs: fix site css of direction
  site/theme/static/highlight.less
Labels: PR: unreviewed

#23930 refactor: 📦 use webpack-plugin-esbuild
  .antd-tools.config.js
  package.json
  site/bisheng.config.js
  webpack.config.js
Labels: PR: unreviewed

#23957 refactor: 📦 Generate version.js from package.json
  .antd-tools.config.js
  .gitignore
  components/version/index.tsx
  package.json
  scripts/generate-version.js
Labels: PR: unreviewed

#23962 style: fix transfer search padding in rtl
  components/transfer/style/index.less
  components/transfer/style/rtl.less
Labels: PR: reviewed-approved

#23963 style: 💄 Tweak Select close x position
  components/select/style/multiple.less
Labels: PR: unreviewed

#23969 refactor: 📦 remove react-lifecycles-compat
  package.json
Labels: PR: unreviewed

#23973 chore: Feature merge master
  .antd-tools.config.js
  .github/workflows/rebase.yml
  .gitignore
  .jest.js
  README.md
  components/_util/openAnimation.tsx
  components/_util/wave.tsx
  components/auto-complete/index.en-US.md
  components/auto-complete/index.zh-CN.md
  components/carousel/__tests__/__snapshots__/demo.test.js.snap
  components/config-provider/index.en-US.md
  components/config-provider/index.zh-CN.md
  components/divider/index.en-US.md
  components/divider/index.zh-CN.md
  components/drawer/style/drawer.less
  components/form/FormItem.tsx
  components/grid/demo/useBreakpoint.md
  components/layout/style/index.less
  components/layout/style/rtl.less
  components/locale/default.tsx
  components/locale/fa_IR.tsx
  components/popconfirm/index.en-US.md
  components/popconfirm/index.zh-CN.md
  components/select/index.en-US.md
  components/select/index.zh-CN.md
  components/select/style/multiple.less
  components/table/__tests__/__snapshots__/Table.rowSelection.test.js.snap
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/hooks/useSelection.tsx
  components/table/style/index.less
  components/tooltip/index.en-US.md
  components/tooltip/index.zh-CN.md
  components/transfer/__tests__/__snapshots__/demo.test.js.snap
  components/transfer/style/index.less
  components/transfer/style/rtl.less
  components/version/index.tsx
  docs/react/contributing.zh-CN.md
  docs/react/getting-started.en-US.md
  docs/react/getting-started.zh-CN.md
  docs/react/replace-moment.en-US.md
  docs/react/use-in-typescript.en-US.md
  docs/react/use-in-typescript.zh-CN.md
  docs/react/use-with-create-react-app.en-US.md
  docs/react/use-with-create-react-app.zh-CN.md
  docs/resources.en-US.md
  docs/resources.zh-CN.md
  package.json
  scripts/generate-version.js
  site/bisheng.config.js
  site/theme/en-US.js
  site/theme/static/highlight.less
  site/theme/template/Layout/Footer.tsx
  site/theme/zh-CN.js
  typings/custom-typings.d.ts
  webpack.config.js
Labels: PR: reviewed-changes-requested

#23972 feat: Form support validateTrigger
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#23981 style: opt datepicker active bar style in rtl
  components/date-picker/style/rtl.less
Labels: PR: unreviewed

#23989 fix: 🆙 upgrade rc-steps@3.6.0
  components/table/__tests__/__snapshots__/demo.test.js.snap
  package.json
Labels: PR: unreviewed

#23985 style: fix select focused in input group
  components/input/style/mixin.less
Labels: PR: unreviewed

#23994 fix: #23986 [Comment] Should not render avatar wrapper when avatar is…
  components/comment/__tests__/__snapshots__/index.test.js.snap
  components/comment/index.tsx
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
Labels: PR: unreviewed

#23987 docs: Add documentation for responsive table columns
  components/table/index.en-US.md
  components/table/index.zh-CN.md
Labels: PR: partially-approved

#23999 style: fix input clear icon in rtl
  components/input/ClearableLabeledInput.tsx
  components/input/TextArea.tsx
  components/input/style/rtl.less
Labels: PR: unreviewed

#23990 docs: optimize input demo
  components/input/demo/group.md
Labels: PR: unreviewed

#24001 fix: Tooltip in Upload components location error
  components/upload/UploadList.tsx
Labels: PR: unreviewed

#24004 test: ✅ Alert and AutoComplete test coverage
  components/alert/__tests__/__snapshots__/demo.test.ts.snap
  components/alert/__tests__/__snapshots__/index.test.tsx.snap
  components/alert/__tests__/index.test.tsx
  components/alert/demo/closable.md
  components/alert/demo/custom-icon.md
  components/alert/demo/description.md
  components/alert/demo/icon.md
  components/alert/demo/style.md
  components/alert/index.tsx
  components/auto-complete/__tests__/__snapshots__/demo.test.js.snap
  components/auto-complete/__tests__/__snapshots__/index.test.js.snap
  components/auto-complete/__tests__/index.test.js
  components/auto-complete/demo/basic.md
  components/auto-complete/demo/certain-category.md
  components/auto-complete/demo/form-debug.md
  components/auto-complete/demo/non-case-sensitive.md
  components/auto-complete/demo/options.md
Labels: PR: unreviewed

#24000 chore: 🆙 upgrade eslint
  package.json
Labels: PR: unreviewed

#24006 chore: 🔀 Master to merge feature
  .github/FUNDING.yml
  components/alert/__tests__/__snapshots__/demo.test.ts.snap
  components/alert/__tests__/__snapshots__/index.test.tsx.snap
  components/alert/__tests__/index.test.tsx
  components/alert/demo/closable.md
  components/alert/demo/custom-icon.md
  components/alert/demo/description.md
  components/alert/demo/icon.md
  components/alert/demo/style.md
  components/alert/index.tsx
  components/auto-complete/__tests__/__snapshots__/demo.test.js.snap
  components/auto-complete/__tests__/__snapshots__/index.test.js.snap
  components/auto-complete/__tests__/index.test.js
  components/auto-complete/demo/basic.md
  components/auto-complete/demo/certain-category.md
  components/auto-complete/demo/form-debug.md
  components/auto-complete/demo/non-case-sensitive.md
  components/auto-complete/demo/options.md
  components/button/index.zh-CN.md
  components/comment/__tests__/__snapshots__/index.test.js.snap
  components/comment/index.tsx
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/date-picker/style/rtl.less
  components/input/ClearableLabeledInput.tsx
  components/input/TextArea.tsx
  components/input/demo/group.md
  components/input/style/mixin.less
  components/input/style/rtl.less
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/upload/UploadList.tsx
  package.json
Labels: PR: reviewed-changes-requested

#24009 chore: Fix Form.List render logic
  components/form/FormItem.tsx
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/demo/dynamic-form-item.md
  components/form/demo/dynamic-form-items.md
  package.json
Labels: PR: reviewed-approved

#24013 docs: Update react-dnd Table example docs
  components/table/demo/drag-sorting.md
Labels: PR: unreviewed

#23938 docs: Update use-with-create-react-app.zh-CN.md
  docs/react/use-with-create-react-app.zh-CN.md
Labels: PR: unreviewed

#24015 chore: fix drawer demo
  components/drawer/__tests__/__snapshots__/demo.test.js.snap
  components/drawer/demo/basic-right.md
  components/drawer/demo/form-in-drawer.md
  components/drawer/demo/multi-level-drawer.md
  components/drawer/demo/placement.md
  components/drawer/demo/render-in-current.md
  components/drawer/demo/user-profile.md
Labels: PR: reviewed-approved

#24016 fix: en_GB does not mean global english
  docs/react/i18n.en-US.md
Labels: PR: unreviewed

#24018 chore: Feature merge master
  components/drawer/__tests__/__snapshots__/demo.test.js.snap
  components/drawer/demo/basic-right.md
  components/drawer/demo/form-in-drawer.md
  components/drawer/demo/multi-level-drawer.md
  components/drawer/demo/placement.md
  components/drawer/demo/render-in-current.md
  components/drawer/demo/user-profile.md
  components/table/demo/drag-sorting.md
  docs/react/i18n.en-US.md
  docs/react/use-with-create-react-app.zh-CN.md
Labels: PR: reviewed-approved

#23995 docs: optimize site of rtl
  components/avatar/demo/basic.md
  components/avatar/demo/type.md
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
  components/dropdown/demo/placement.md
  components/icon/demo/basic.md
  components/icon/demo/custom.md
  components/input-number/demo/size.md
  components/select/demo/size.md
  components/time-picker/index.en-US.md
  components/time-picker/index.zh-CN.md
  site/theme/static/icons.less
Labels: PR: unreviewed

#24020 refactor: Dropdown.Button icon prop
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/dropdown/__tests__/__snapshots__/demo.test.js.snap
  components/dropdown/__tests__/__snapshots__/dropdown-button.test.js.snap
  components/dropdown/demo/dropdown-button.md
  components/dropdown/dropdown-button.tsx
  components/dropdown/style/index.less
Labels: PR: unreviewed

#24028 style: fix datepicker panel style
  components/date-picker/style/index.less
Labels: PR: unreviewed

#24024 fix(#16659): support className and style for message
  components/message/__tests__/__snapshots__/demo.test.js.snap
  components/message/demo/custom-style.md
  components/message/index.en-US.md
  components/message/index.tsx
  components/message/index.zh-CN.md
Labels: PR: reviewed-approved

#23992 fix: Add closeIcon for Tabs.Tabpane
  components/tabs/__tests__/__snapshots__/demo.test.js.snap
  components/tabs/demo/editable-card.md
  components/tabs/index.en-US.md
  components/tabs/index.tsx
  components/tabs/index.zh-CN.md
Labels: PR: reviewed-approved

#24019 feat: Add Link component to prepare for rm global style
  components/style/core/base.less
  components/style/core/global.less
  components/style/core/index.less
  components/typography/Base.tsx
  components/typography/Link.tsx
  components/typography/__tests__/__snapshots__/demo.test.js.snap
  components/typography/__tests__/__snapshots__/index.test.js.snap
  components/typography/__tests__/index.test.js
  components/typography/demo/text.md
  components/typography/index.en-US.md
  components/typography/index.tsx
  components/typography/index.zh-CN.md
  components/typography/style/index.less
Labels: PR: reviewed-approved

#24032 feat: descriptions add less variable
  components/descriptions/Cell.tsx
  components/descriptions/__tests__/__snapshots__/demo.test.js.snap
  components/descriptions/__tests__/__snapshots__/index.test.js.snap
  components/descriptions/style/index.less
  components/page-header/__tests__/__snapshots__/demo.test.js.snap
  components/style/themes/default.less
Labels: PR: reviewed-approved

#24025 docs: changelog 4.2.1
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#24052 fix: @menu-item-font-size not working
  components/menu/style/index.less
  components/modal/Modal.tsx
  components/style/themes/compact.less
  components/style/themes/default.less
Labels: PR: unreviewed

#24059 fix: `npm run version` error when install antd
  package.json
  scripts/generate-color-less.js
Labels: PR: unreviewed

#24060 release: 4.2.2 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#24063 chore: Fix pub script
  package.json
Labels: PR: unreviewed

#24058 fix(#23019): display defaultValue when no matched options
  components/cascader/__tests__/index.test.js
  components/cascader/index.tsx
Labels: PR: reviewed-approved

#24067 fix: upgrade react-slick to 0.26.1
  package.json
Labels: PR: unreviewed

#24065 feat: Adds zh_TW localisations for Form
  components/locale-provider/__tests__/index.test.js
  components/locale/zh_TW.tsx
Labels: PR: unreviewed

#24082 fix: Drawer height bug
  components/drawer/index.tsx
  components/drawer/style/drawer.less
Labels: PR: unreviewed

#24084 style: optimize typography expand style in rtl
  components/typography/style/rtl.less
Labels: PR: unreviewed

#24095 fix: Child of Button should be interactive
  components/button/style/index.less
Labels: PR: unreviewed

#24101 style: fix menu border in rtl
  components/menu/style/rtl.less
Labels: PR: unreviewed

#24106 docs: Update faq of mutable data
  docs/react/faq.en-US.md
  docs/react/faq.zh-CN.md
Labels: PR: unreviewed

#24109 docs: fix typo
  components/form/index.zh-CN.md
Labels: PR: unreviewed

#24110 fix: dark menu link color
  components/menu/style/dark.less
Labels: PR: unreviewed

#24097 style: fix Button small size align when customize theme
  components/button/style/mixin.less
  components/style/themes/compact.less
Labels: PR: reviewed-approved

#24112 style: optimize select multiple tag style in rtl
  components/select/style/rtl.less
Labels: PR: unreviewed

#24096 refactor: 🔨 tree style code
  components/tree/style/directory.less
  components/tree/style/index.less
  components/tree/style/rtl.less
Labels: PR: unreviewed

#24114 fix: Table onChange pagination type
  components/table/Table.tsx
Labels: PR: unreviewed

#24127 refactor: 🆙 upgrade rc-progress
  components/progress/__tests__/__snapshots__/demo.test.js.snap
  components/progress/__tests__/__snapshots__/index.test.js.snap
  package.json
  tests/index.test.js
Labels: PR: unreviewed

#24111 chore: 🆙 upgrade typescript to 3.9.2
  package.json
Labels: PR: unreviewed

#24122 fix: Switch - no correct animation on the IOS/Chrome
  components/switch/style/index.less
Labels: PR: reviewed-approved

#24145 fix: DatePicker panel footer exceed
  components/date-picker/style/DecadePanel.less
  components/date-picker/style/panel.less
Labels: PR: unreviewed

#24150 fix: dropdown button default placement in rtl
  components/dropdown/demo/dropdown-button.md
  components/dropdown/dropdown-button.tsx
Labels: PR: unreviewed

#24152 style: adjust pagination simple background
  components/pagination/style/index.less
Labels: PR: unreviewed

#24135 chore: small bundle size
  components/_util/devWarning.ts
  components/_util/warning.ts
  components/auto-complete/index.tsx
  components/avatar/index.tsx
  components/breadcrumb/Breadcrumb.tsx
  components/button/button.tsx
  components/cascader/index.tsx
  components/checkbox/Checkbox.tsx
  components/checkbox/__tests__/checkbox.test.js
  components/descriptions/__tests__/index.test.js
  components/descriptions/index.tsx
  components/dropdown/dropdown.tsx
  components/form/FormItem.tsx
  components/form/FormList.tsx
  components/form/index.tsx
  components/icon/index.tsx
  components/input/Input.tsx
  components/locale-provider/index.tsx
  components/menu/__tests__/index.test.js
  components/menu/index.tsx
  components/modal/ConfirmDialog.tsx
  components/result/index.tsx
  components/switch/__tests__/index.test.js
  components/switch/index.tsx
  components/table/Table.tsx
  components/table/__tests__/Table.pagination.test.js
  components/table/__tests__/Table.rowSelection.test.js
  components/table/hooks/useSelection.tsx
  components/time-picker/__tests__/index.test.js
  components/time-picker/index.tsx
  components/tree-select/index.tsx
  components/typography/Base.tsx
  components/typography/Text.tsx
  components/typography/Title.tsx
  components/typography/Typography.tsx
  components/typography/__tests__/index.test.js
  components/upload/Upload.tsx
  components/upload/__tests__/upload.test.js
  package.json
  site/theme/template/Icon/index.jsx
  site/theme/template/Icon/utils.js
  webpack.config.js
Labels: PR: unreviewed

#24154 style: optimize pagination slash style in rtl
  components/pagination/style/rtl.less
Labels: PR: unreviewed

#24158 chore: Feature merge master
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/pr_cn.md
  components/_util/devWarning.ts
  components/_util/warning.ts
  components/auto-complete/index.tsx
  components/avatar/index.tsx
  components/breadcrumb/Breadcrumb.tsx
  components/button/button.tsx
  components/cascader/index.tsx
  components/checkbox/Checkbox.tsx
  components/checkbox/__tests__/checkbox.test.js
  components/date-picker/style/DecadePanel.less
  components/date-picker/style/panel.less
  components/descriptions/__tests__/index.test.js
  components/descriptions/index.tsx
  components/dropdown/demo/dropdown-button.md
  components/dropdown/dropdown-button.tsx
  components/dropdown/dropdown.tsx
  components/form/FormItem.tsx
  components/form/FormList.tsx
  components/form/index.tsx
  components/icon/index.tsx
  components/input/Input.tsx
  components/locale-provider/index.tsx
  components/menu/__tests__/index.test.js
  components/menu/index.tsx
  components/modal/ConfirmDialog.tsx
  components/pagination/style/index.less
  components/pagination/style/rtl.less
  components/progress/__tests__/__snapshots__/demo.test.js.snap
  components/progress/__tests__/__snapshots__/index.test.js.snap
  components/result/index.tsx
  components/switch/__tests__/index.test.js
  components/switch/index.tsx
  components/switch/style/index.less
  components/table/Table.tsx
  components/table/__tests__/Table.pagination.test.js
  components/table/__tests__/Table.rowSelection.test.js
  components/table/hooks/useSelection.tsx
  components/time-picker/__tests__/index.test.js
  components/time-picker/index.tsx
  components/transfer/index.tsx
  components/tree-select/index.tsx
  components/typography/Base.tsx
  components/typography/Link.tsx
  components/typography/Text.tsx
  components/typography/Title.tsx
  components/typography/Typography.tsx
  components/typography/__tests__/index.test.js
  components/upload/Upload.tsx
  components/upload/__tests__/upload.test.js
  docs/react/introduce.zh-CN.md
  package.json
  site/theme/template/Icon/index.jsx
  site/theme/template/Icon/utils.js
  tests/index.test.js
  webpack.config.js
Labels: PR: reviewed-changes-requested

#24164 chore: small bundle size follow up
  components/_util/reactNode.ts
  components/alert/index.tsx
  components/auto-complete/index.tsx
  components/badge/ScrollNumber.tsx
  components/badge/index.tsx
  components/breadcrumb/Breadcrumb.tsx
  components/button/button.tsx
  components/cascader/index.tsx
  components/collapse/Collapse.tsx
  components/descriptions/index.tsx
  components/dropdown/dropdown.tsx
  components/form/FormItem.tsx
  components/input/ClearableLabeledInput.tsx
  components/input/Search.tsx
  components/list/index.tsx
  components/menu/MenuItem.tsx
  components/menu/SubMenu.tsx
  components/spin/index.tsx
  components/statistic/Countdown.tsx
  components/tabs/TabBar.tsx
  components/tabs/index.tsx
  components/timeline/Timeline.tsx
  components/tooltip/index.tsx
  components/transfer/list.tsx
  components/tree/utils/iconUtil.tsx
  components/upload/UploadList.tsx
  webpack.config.js
Labels: PR: unreviewed

#24169 chore: Feature merge master
  components/_util/reactNode.ts
  components/alert/index.tsx
  components/auto-complete/index.tsx
  components/badge/ScrollNumber.tsx
  components/badge/index.tsx
  components/breadcrumb/Breadcrumb.tsx
  components/button/button.tsx
  components/cascader/index.tsx
  components/collapse/Collapse.tsx
  components/descriptions/index.tsx
  components/dropdown/dropdown.tsx
  components/form/FormItem.tsx
  components/input/ClearableLabeledInput.tsx
  components/input/Search.tsx
  components/list/index.tsx
  components/menu/MenuItem.tsx
  components/menu/SubMenu.tsx
  components/spin/index.tsx
  components/statistic/Countdown.tsx
  components/tabs/TabBar.tsx
  components/tabs/index.tsx
  components/timeline/Timeline.tsx
  components/tooltip/index.tsx
  components/transfer/list.tsx
  components/tree/utils/iconUtil.tsx
  components/upload/UploadList.tsx
  webpack.config.js
Labels: PR: reviewed-changes-requested

#24166 chore: update issue template
  .github/ISSUE_TEMPLATE/----please-use-new-issue-ant-design---.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: PR: unreviewed

#24170 fix: Select item z-index
  components/select/style/single.less
Labels: PR: unreviewed

#24167 fix: cherry pick #23151 into 3.x-stable
  components/tabs/style/index.less
Labels: PR: unreviewed

#23699 refactor(tooltip): rewrite with hook
  components/alert/__tests__/index.test.tsx
  components/badge/__tests__/index.test.js
  components/slider/SliderTooltip.tsx
  components/slider/__tests__/index.test.js
  components/slider/index.tsx
  components/tooltip/__tests__/tooltip.test.js
  components/tooltip/index.tsx
Labels: PR: unreviewed

#24177 chore: scrollTo add more test
  components/_util/__tests__/scrollTo.test.js
Labels: PR: reviewed-changes-requested

#24180 chore: getScroll add more test
  components/_util/__tests__/getScroll.test.js
  components/_util/__tests__/getScrollNode.test.ts
Labels: PR: unreviewed

#24184 docs: 📖 keep documentation up to date
  README-pt_BR.md
  README-zh_CN.md
  README.md
  components/button/__tests__/__snapshots__/type.test.tsx.snap
  components/button/__tests__/type.test.tsx
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
  components/form/demo/customized-form-controls.md
  components/list/__tests__/Item.test.js
  components/list/__tests__/__snapshots__/Item.test.js.snap
  components/list/__tests__/__snapshots__/demo.test.js.snap
  components/list/demo/vertical.md
  components/skeleton/demo/list.md
  docs/react/faq.en-US.md
  docs/react/faq.zh-CN.md
  docs/react/getting-started.en-US.md
  docs/react/getting-started.zh-CN.md
  docs/react/introduce.en-US.md
  docs/react/introduce.zh-CN.md
  docs/react/use-in-typescript.en-US.md
  docs/react/use-in-typescript.zh-CN.md
  docs/react/use-with-create-react-app.en-US.md
  docs/react/use-with-create-react-app.zh-CN.md
  package.json
Labels: PR: unreviewed

#24185 chore: merge master into feature
  .github/ISSUE_TEMPLATE/----please-use-new-issue-ant-design---.md
  .github/ISSUE_TEMPLATE/config.yml
  README-pt_BR.md
  README-zh_CN.md
  README.md
  components/_util/__tests__/getScroll.test.js
  components/_util/__tests__/getScrollNode.test.ts
  components/_util/__tests__/scrollTo.test.js
  components/alert/__tests__/index.test.tsx
  components/badge/__tests__/index.test.js
  components/button/__tests__/__snapshots__/type.test.tsx.snap
  components/button/__tests__/type.test.tsx
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
  components/form/demo/customized-form-controls.md
  components/icon/index.en-US.md
  components/icon/index.zh-CN.md
  components/list/__tests__/Item.test.js
  components/list/__tests__/__snapshots__/Item.test.js.snap
  components/list/__tests__/__snapshots__/demo.test.js.snap
  components/list/demo/vertical.md
  components/select/style/single.less
  components/skeleton/demo/list.md
  components/slider/SliderTooltip.tsx
  components/slider/__tests__/index.test.js
  components/slider/index.tsx
  components/tooltip/__tests__/tooltip.test.js
  components/tooltip/index.tsx
  docs/react/faq.en-US.md
  docs/react/faq.zh-CN.md
  docs/react/getting-started.en-US.md
  docs/react/getting-started.zh-CN.md
  docs/react/introduce.en-US.md
  docs/react/introduce.zh-CN.md
  docs/react/use-in-typescript.en-US.md
  docs/react/use-in-typescript.zh-CN.md
  docs/react/use-with-create-react-app.en-US.md
  docs/react/use-with-create-react-app.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#24189 style: 💄 Add @card-head-extra-color
  components/card/style/index.less
  components/style/themes/default.less
Labels: PR: unreviewed

#24190 fix: Picker disabled today
  components/date-picker/__tests__/__snapshots__/DatePicker.test.js.snap
  components/date-picker/style/panel.less
  package.json
Labels: PR: unreviewed

#24194 fix: Backtop cannot work in Chrome iframe
  components/_util/scrollTo.ts
Labels: PR: reviewed-changes-requested

#24199 chore: Feature merge master
  components/_util/scrollTo.ts
  components/card/style/index.less
  components/date-picker/__tests__/__snapshots__/DatePicker.test.js.snap
  components/date-picker/style/panel.less
  components/style/themes/default.less
  package.json
Labels: PR: reviewed-changes-requested

#23575 refactor(backtop): rewrite with hook
  components/back-top/__tests__/index.test.js
  components/back-top/index.tsx
Labels: PR: unreviewed

#24202 fix: Upload.Dragger triggered by label when disabled
  components/upload/Dragger.tsx
  components/upload/Upload.tsx
  components/upload/__tests__/upload.test.js
Labels: PR: unreviewed

#24195 feat: Text keyboard
  components/typography/Base.tsx
  components/typography/__tests__/__snapshots__/demo.test.js.snap
  components/typography/demo/basic.md
  components/typography/demo/text.md
  components/typography/index.en-US.md
  components/typography/index.zh-CN.md
  components/typography/style/index.less
Labels: PR: reviewed-approved

#24204 docs: 🚀 Release 3.26.17
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#24203 docs: 🚀 Release 4.2.3
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#24210 删除名单中重复的作者名称
  AUTHORS.txt
Labels: PR: unreviewed

#24211 refactor(card): rewrite with hook
  components/card/index.tsx
Labels: PR: unreviewed

#24212 refactor(dropdown): rewrite with hook
  components/dropdown/dropdown-button.tsx
  components/dropdown/dropdown.tsx
  components/dropdown/index.tsx
Labels: PR: unreviewed

#24215 style: tweak Dropdown down arrow position
  components/dropdown/style/index.less
Labels: PR: unreviewed

#24214 chore: merge master into feature
  AUTHORS.txt
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  README.md
  components/back-top/__tests__/index.test.js
  components/back-top/index.tsx
  components/card/index.tsx
  components/dropdown/dropdown-button.tsx
  components/dropdown/dropdown.tsx
  components/dropdown/index.tsx
  components/dropdown/style/index.less
  components/upload/Dragger.tsx
  components/upload/Upload.tsx
  components/upload/__tests__/upload.test.js
  package.json
Labels: PR: unreviewed

#24219 Add a form to ru_RU i18n
  components/locale/ru_RU.tsx
Labels: PR: unreviewed

#24220 chore: 🆙 upgrade rc-switch to 3.0.0
  package.json
Labels: PR: unreviewed

#24227 docs: 📝 fix create-react-app usage step
  docs/react/use-in-typescript.en-US.md
  docs/react/use-in-typescript.zh-CN.md
  docs/react/use-with-create-react-app.en-US.md
  docs/react/use-with-create-react-app.zh-CN.md
Labels: PR: unreviewed

#24234 docs: improve spin api
  components/spin/index.zh-CN.md
Labels: PR: reviewed-approved

#24160 style: adjust upload error icon
  components/upload/style/index.less
Labels: PR: partially-approved

#24239 docs: optimize search of header in rtl
  site/theme/template/Layout/Header/SearchBox.less
Labels: PR: unreviewed
