Repository ant-design/ant-design, pull requests merged in 2020-04, with the labels that each got.

#22666 fix: Card Tabs do not support small size
  components/style/themes/default.less
  components/tabs/__tests__/__snapshots__/demo.test.js.snap
  components/tabs/demo/size.md
  components/tabs/index.tsx
  components/tabs/style/card-style.less
Labels: PR: unreviewed

#22795 revert: "fix: set codesandbox referrer to no-referrer (#22688)"
  site/theme/static/demo.less
  site/theme/static/template.html
  site/theme/template/Content/Demo/index.jsx
Labels: PR: unreviewed

#22797 revert: "fix: set codesandbox referrer to no-referrer (#22792)"
  site/theme/static/demo.less
  site/theme/template/Content/Demo.jsx
Labels: PR: unreviewed

#22803 fix: fix less variable typo
  components/radio/style/index.less
  components/style/themes/dark.less
  components/style/themes/default.less
Labels: PR: unreviewed

#22769 fix: Fix date_picker et time_picker locale for 🇫🇷
  components/date-picker/locale/fr_FR.tsx
  components/time-picker/locale/fr_FR.tsx
Labels: PR: reviewed-approved

#22817 docs: fix compact emoji in en
  docs/react/customize-theme.en-US.md
Labels: PR: unreviewed

#22787 fix: support table getPopupContainer on row selections
  components/table/Table.tsx
  components/table/__tests__/Table.rowSelection.test.js
  components/table/__tests__/__snapshots__/Table.rowSelection.test.js.snap
  components/table/hooks/useSelection.tsx
  components/table/style/index.less
Labels: PR: unreviewed

#22788 fix: ⬆️ BackTop not working in iframe
  components/_util/__tests__/getScroll.test.js
  components/_util/getScroll.tsx
  components/_util/scrollTo.ts
  components/back-top/__tests__/__snapshots__/demo.test.js.snap
  components/back-top/__tests__/__snapshots__/index.test.js.snap
  components/back-top/__tests__/index.test.js
  components/back-top/demo/basic.md
  components/back-top/demo/custom.md
  components/back-top/index.tsx
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/upload/__tests__/uploadlist.test.js
Labels: PR: unreviewed

#22832 fix: Table expanded logic
  components/table/__tests__/Table.rowSelection.test.js
  components/table/__tests__/__snapshots__/Table.rowSelection.test.js.snap
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/__tests__/__snapshots__/empty.test.js.snap
  components/table/__tests__/empty.test.js
  components/table/style/bordered.less
  package.json
Labels: PR: unreviewed

#22723 style: 💄 @info-color should be @primary-color defaultly
  components/style/themes/default.less
Labels: PR: unreviewed

#22833 fix: support undefined remove filter icon
  components/table/__tests__/Table.filter.test.js
  components/table/hooks/useFilter/index.tsx
Labels: PR: reviewed-changes-requested

#22836 fix: Text align logic
  components/typography/__tests__/__snapshots__/demo.test.js.snap
  components/typography/demo/ellipsis-debug.md
  components/typography/style/index.less
Labels: PR: unreviewed

#22842 docs: Update visualization-page.md
  docs/spec/visualization-page.md
Labels: PR: unreviewed

#22841 style: fix menu rtl
  components/menu/style/rtl.less
Labels: PR: unreviewed

#22834 docs: specify minimum less version
  docs/react/use-with-create-react-app.en-US.md
Labels: PR: unreviewed

#22845 docs: 📖 tip for TypeScript version
  docs/react/use-in-typescript.en-US.md
  docs/react/use-in-typescript.zh-CN.md
Labels: PR: unreviewed

#22850 refactor: Refactor picker generate to multiple files
  components/date-picker/generatePicker.tsx
  components/date-picker/generatePicker/generateRangePicker.tsx
  components/date-picker/generatePicker/generateSinglePicker.tsx
  components/date-picker/generatePicker/index.tsx
Labels: PR: unreviewed

#22846 chore: 🤖 auto push gh-pages to gitee
  package.json
Labels: PR: unreviewed

#22856 docs: fix typo
  components/form/index.en-US.md
Labels: PR: unreviewed

#22858 fix: Center not work in Table
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/table/__tests__/Table.sorter.test.js
  components/table/__tests__/__snapshots__/Table.sorter.test.js.snap
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/hooks/useSorter.tsx
  components/table/style/index.less
Labels: PR: unreviewed

#22868 fix: adjust nest table logic
  components/table/style/index.less
Labels: PR: unreviewed

#22869 docs: add react-app cn
  docs/react/use-with-create-react-app.en-US.md
  docs/react/use-with-create-react-app.zh-CN.md
Labels: PR: reviewed-approved

#22872 fix: Table header columns size with filter or sorter
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/demo/dynamic-settings.md
  components/table/style/index.less
  components/table/style/size.less
Labels: PR: partially-approved

#22883 chore: 🦄 Add eslint-plugin-unicorn
  .antd-tools.config.js
  .eslintrc.js
  components/_util/wave.tsx
  components/alert/__tests__/index.test.js
  components/button/__tests__/index.test.js
  components/calendar/__tests__/index.test.js
  components/dropdown/__tests__/dropdown-button.test.js
  components/form/FormItemLabel.tsx
  components/form/__tests__/index.test.js
  components/input/demo/tooltip.md
  components/message/__tests__/index.test.js
  components/statistic/utils.tsx
  components/transfer/index.tsx
  components/typography/Editable.tsx
  components/typography/__tests__/index.test.js
  components/upload/Upload.tsx
  components/upload/__tests__/upload.test.js
  package.json
  scripts/check-site.js
  site/bisheng.config.js
  site/theme/template/Color/ColorPaletteTool.jsx
  site/theme/template/Color/ColorPaletteToolDark.jsx
  site/theme/template/Content/Article.tsx
  site/theme/template/Content/Demo/index.jsx
  site/theme/template/Content/MainContent.jsx
  site/theme/template/Home/index.tsx
  site/theme/template/Layout/Header/index.tsx
  site/theme/template/utils.tsx
  tests/dekko/dist.test.js
  tests/dekko/lib.test.js
  tests/index.test.js
Labels: PR: unreviewed

#22887 fix: Input affix prevent dropdown focus
  components/input/ClearableLabeledInput.tsx
  components/input/__tests__/textarea.test.js
Labels: PR: reviewed-changes-requested

#22888 fix: Table jsx filter not work
  components/table/Table.tsx
  components/table/__tests__/Table.filter.test.js
  components/table/hooks/useFilter/index.tsx
Labels: PR: reviewed-changes-requested

#22895 fix: FilterDropdownProps TypeScript definition update
  components/table/interface.tsx
Labels: PR: unreviewed

#22902 docs: Updating document to correct few typos
  components/form/v3.en-US.md
Labels: PR: unreviewed

#22904 style: 🐛 Fix multiple Select large size
  components/select/style/multiple.less
Labels: PR: unreviewed

#22899 docs: 3.26.15 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#22916 fix: Extract type of the element of a tuple without indexing.
  components/_util/type.ts
  components/transfer/renderListBody.tsx
Labels: PR: unreviewed

#22513 style: add message rtl
  components/message/__tests__/config.test.js
  components/message/index.en-US.md
  components/message/index.tsx
  components/message/index.zh-CN.md
  components/message/style/index.less
  components/message/style/rtl.less
Labels: PR: partially-approved

#22926 rtl(radio): fix radio rtl overrided by theme
  components/radio/style/rtl.less
Labels: PR: reviewed-approved

#22908 fix: fix menu and spin style in compact mode
  components/menu/style/dark.less
  components/spin/demo/size.md
Labels: PR: partially-approved

#22903 docs: 4.1.1 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#22934 feat(theme): extract theme-js file for supprt mixin theme
  .antd-tools.config.js
  scripts/compact-vars.js
  scripts/dark-vars.js
  scripts/default-vars.js
  scripts/generateColorLess.js
Labels: PR: reviewed-changes-requested

#22941 style: fix Notification invalid padding-top value
  components/notification/style/index.less
Labels: PR: unreviewed

#22933 chore: Use unreachable exception in favor of type safety
  components/_util/__tests__/unreachableException.test.js
  components/_util/unreachableException.ts
  components/button/__tests__/__snapshots__/index.test.js.snap
  components/button/__tests__/index.test.js
  components/button/button-group.tsx
Labels: PR: unreviewed

#22942 chore: fix packtracker token
  package.json
  webpack.config.js
Labels: PR: unreviewed

#22946 docs: update DatePicker docs to specify correct monthCellRender prop …
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
Labels: PR: unreviewed

#22921 Improve typing of `UploadProps` interface
  components/upload/interface.tsx
Labels: PR: unreviewed

#22950 fix: Statistic show -0
  components/statistic/Number.tsx
  components/statistic/__tests__/index.test.js
Labels: PR: reviewed-changes-requested

#22755 chore: export form value type
  components/form/interface.ts
Labels: PR: reviewed-changes-requested

#22947 chore: Introduce customer jest match to support matchRenderedSnapshot
  .jest.js
  .jest.node.js
  components/button/__tests__/index.test.js
  package.json
  tests/matchers/rendered-snapshot.ts
  tests/setupAfterEnv.ts
  tests/shared/rtlTest.js
  typings/jest.d.ts
Labels: PR: unreviewed

#22951 docs: 📝 update README.md badges
  README.md
Labels: PR: unreviewed

#22913 fix: Replace NativeButtonProps with ButtonProps for okButtonProps and canc…
  components/modal/ActionButton.tsx
  components/modal/Modal.tsx
Labels: PR: unreviewed

#22963 fix: confirm button should only trigger once
  components/modal/ActionButton.tsx
  components/modal/__tests__/confirm.test.js
Labels: PR: unreviewed

#22875 style: add anchor rtl
  components/anchor/Anchor.tsx
  components/anchor/style/index.less
  components/anchor/style/rtl.less
Labels: PR: unreviewed

#22975 fix: Not break input group style
  components/input/style/mixin.less
Labels: PR: unreviewed

#22981 fix(menu): fix submenu style in dark mode
  components/menu/SubMenu.tsx
Labels: PR: unreviewed

#22982 docs: optimize icon doc in rtl
  site/theme/template/IconDisplay/index.tsx
Labels: PR: unreviewed

#22984 style: optimize select dropdown show in rtl
  components/select/style/rtl.less
Labels: PR: unreviewed

#22979 test: ✅ test TransButton focus and blur
  components/_util/__tests__/util.test.js
  components/_util/transButton.tsx
Labels: PR: unreviewed

#22978 style: 💄 tweak Select cuosor position
  components/select/style/multiple.less
Labels: PR: unreviewed

#22998 chore: Feature merge master
  README.md
  components/_util/__tests__/util.test.js
  components/_util/transButton.tsx
  components/anchor/Anchor.tsx
  components/anchor/style/index.less
  components/anchor/style/rtl.less
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/input/style/mixin.less
  components/menu/SubMenu.tsx
  components/modal/ActionButton.tsx
  components/modal/__tests__/confirm.test.js
  components/select/style/multiple.less
  components/select/style/rtl.less
  docs/react/introduce.en-US.md
  docs/react/introduce.zh-CN.md
  docs/react/migration-v4.zh-CN.md
  site/theme/template/IconDisplay/index.tsx
Labels: PR: reviewed-changes-requested

#22993 feat: Form.Item support `initialValue` & `getValueProps`
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#22999 chore(Tag): improve color types
  components/_util/type.ts
  components/tag/index.tsx
Labels: PR: reviewed-changes-requested

#23004 fix: form Select status
  components/form/style/status.less
Labels: PR: unreviewed

#23013 docs: fix typo
  docs/react/customize-theme.en-US.md
Labels: PR: reviewed-approved

#23006 chore(Input): improve type types
  components/input/Input.tsx
Labels: PR: unreviewed

#23020 fix: IE11 Select flex
  components/pagination/style/index.less
  components/select/style/index.less
Labels: PR: unreviewed

#23026 chore(Badge): improve Badge color types
  components/badge/index.tsx
Labels: PR: unreviewed

#23028 fix: long submenu title display
  components/menu/style/index.less
  components/menu/style/rtl.less
Labels: PR: reviewed-approved

#23032 docs: Update tag demo to support edit
  components/tag/__tests__/__snapshots__/demo.test.js.snap
  components/tag/demo/control.md
Labels: PR: unreviewed

#23036 chore: Remove useless event handler
  components/table/Table.tsx
Labels: PR: unreviewed

#23041 fix: clean up when field reset removed
  components/form/FormItemInput.tsx
  components/form/__tests__/index.test.js
Labels: PR: reviewed-changes-requested

#23025 chore: adjust RangePicker style
  components/date-picker/style/index.less
Labels: PR: unreviewed

#23048 fix(pagination): array support for `position` in types
  components/pagination/Pagination.tsx
Labels: PR: unreviewed

#23054 fix: menu dark theme not working in submenu
  components/menu/style/dark.less
  components/menu/style/index.less
Labels: PR: unreviewed

#23053 docs: Update the content of Getting Started page
  docs/react/getting-started.en-US.md
  docs/react/getting-started.zh-CN.md
Labels: PR: unreviewed

#23055 chore: refactor Tree draggable demo code style
  components/tree/demo/draggable.md
Labels: PR: unreviewed

#23046 docs: update pagination related doc
  components/pagination/index.en-US.md
  components/pagination/index.zh-CN.md
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  docs/react/migration-v4.en-US.md
  docs/react/migration-v4.zh-CN.md
Labels: PR: unreviewed

#22595 style: optimize datepicker rtl style
  components/date-picker/style/panel.less
  components/date-picker/style/rtl.less
Labels: PR: unreviewed

#22857 style: add rtl base
  components/back-top/style/index.less
  components/cascader/style/rtl.less
  components/checkbox/Checkbox.tsx
  components/checkbox/__tests__/__snapshots__/checkbox.test.js.snap
  components/checkbox/style/rtl.less
  components/input-number/style/rtl.less
  components/mentions/__tests__/__snapshots__/index.test.js.snap
  components/mentions/index.tsx
  components/mentions/style/index.less
  components/mentions/style/rtl.less
  components/radio/style/rtl.less
  components/table/style/rtl.less
  components/transfer/__tests__/__snapshots__/index.test.js.snap
  components/upload/style/rtl.less
Labels: PR: unreviewed

#23076 style: optimize mentions dropdown in RTL
  components/mentions/index.tsx
  package.json
Labels: PR: unreviewed

#23081 fix: Calendar missing style
  components/calendar/generateCalendar.tsx
Labels: PR: unreviewed

#23078 docs: update Radio.Button
  components/tabs/index.en-US.md
  components/tabs/index.zh-CN.md
Labels: PR: unreviewed

#23087 fix: Tabs bottom style
  components/tabs/style/card-style.less
Labels: PR: reviewed-approved

#23097 style: optimize select dropdown style in rtl
  components/select/index.tsx
  package.json
Labels: PR: unreviewed

#23101 docs: update 3.x codesandbox example
  docs/react/getting-started.en-US.md
  docs/react/getting-started.zh-CN.md
Labels: PR: unreviewed

#23108 docs: Update Form normalize desc
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: PR: unreviewed

#23110 fix: Table selection style
  components/table/style/index.less
Labels: PR: unreviewed

#23113 style: 💄 Tweak Table hover background color
  components/style/themes/default.less
Labels: PR: unreviewed

#23115 fix: Input background with dark mode
  components/input/style/affix.less
Labels: PR: unreviewed

#23114 fix: substitute "易用行" with "易用性"
  docs/spec/values.zh-CN.md
Labels: PR: unreviewed

#23118 chore: Add warning for async
  components/table/Table.tsx
  components/table/__tests__/Table.pagination.test.js
Labels: PR: reviewed-changes-requested

#23102 fix: Button loading switch animation
  components/button/LoadingIcon.tsx
  components/button/__tests__/__snapshots__/demo.test.js.snap
  components/button/__tests__/__snapshots__/index.test.js.snap
  components/button/button.tsx
  components/button/demo/loading.md
  components/button/style/index.less
Labels: PR: unreviewed

#23122 docs: 📖 4.1.2 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed

#23131 chore: Fix compile error
  components/input/Password.tsx
Labels: PR: unreviewed

#23133 fix: PageHeader style breaks when title is too long
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/page-header/__tests__/__snapshots__/demo.test.js.snap
  components/page-header/__tests__/__snapshots__/index.test.js.snap
  components/page-header/demo/responsive.md
  components/page-header/index.tsx
  components/page-header/style/index.less
Labels: PR: unreviewed

#23138 docs: Update Form FAQ
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: PR: unreviewed

#23140 fix: Modify table size.less to accomodate size prop for footer padding
  components/table/style/size.less
Labels: PR: unreviewed

#23144 fix: Pagination missing showTitle (#23134)
  components/pagination/Pagination.tsx
  components/pagination/index.zh-CN.md
Labels: PR: unreviewed

#23128 chore: add preview
  .eslintignore
  .gitignore
  package.json
  scripts/previewEditor/template.html
  scripts/previewEditor/umi.css
  scripts/previewEditor/umi.js
  scripts/print-changelog.js
Labels: PR: unreviewed

#23149 fix: compact group style
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/demo/group.md
  components/input/style/mixin.less
Labels: PR: unreviewed

#23132 fix: Use ElementOf<T> instead of array indexing
  components/_util/colors.ts
Labels: PR: reviewed-approved

#23159 docs: update customize theme docs
  docs/react/customize-theme.en-US.md
  docs/react/customize-theme.zh-CN.md
Labels: PR: unreviewed

#23160 fix: Select align with diff size
  components/select/style/single.less
Labels: PR: unreviewed

#23161 fix: Safari12 fixed column
  components/table/style/index.less
Labels: PR: reviewed-approved

#23168 fix: @tabs-card-height
  components/style/themes/default.less
Labels: PR: unreviewed

#23171 feat: add getThemeVar file to support theme config and fix 4.1.2 them…
  .antd-tools.config.js
  docs/react/customize-theme.en-US.md
  docs/react/customize-theme.zh-CN.md
Labels: PR: unreviewed

#23151 fix: tabs_animation_bug
  components/tabs/style/index.less
Labels: PR: unreviewed

#22953 chore: Refactor the button test to use typescript
  .jest.js
  .jest.node.js
  components/button/__tests__/__snapshots__/demo.test.ts.snap
  components/button/__tests__/__snapshots__/type.test.tsx.snap
  components/button/__tests__/demo.test.ts
  components/button/__tests__/type.test.tsx
  package.json
  tests/shared/demoTest.ts
  tests/shared/mountTest.tsx
  tests/shared/rtlTest.tsx
  tests/utils.ts
  tsconfig.json
Labels: PR: unreviewed

#23183 style: fix steps rtl
  components/steps/style/progress-dot.less
  components/steps/style/rtl.less
Labels: PR: unreviewed

#23185 feat: add notification rtl config
  components/notification/__tests__/index.test.js
  components/notification/index.en-US.md
  components/notification/index.tsx
  components/notification/index.zh-CN.md
  components/notification/style/index.less
  components/notification/style/rtl.less
Labels: PR: partially-approved

#23192 chore: vertical from label height
  components/form/style/vertical.less
Labels: PR: unreviewed

#23198 chore: Improve changelog workflow
  package.json
  scripts/print-changelog.js
Labels: PR: reviewed-approved

#23181 fix: Table in Safari12 fixed column bug
  components/table/style/index.less
Labels: PR: unreviewed

#23199 docs: ✨ release 4.1.3
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#22962 improvement: Fix types in form item
  components/form/FormItem.tsx
  components/form/__tests__/type.test.tsx
  components/table/__tests__/type.test.tsx
Labels: PR: unreviewed

#23205 fix: Table selection `childrenColumnName` not work
  components/table/Table.tsx
  components/table/__tests__/Table.rowSelection.test.js
Labels: PR: reviewed-changes-requested

#23206 refactor(skeleton): rewrite with hook
  .antd-tools.config.js
  components/skeleton/Avatar.tsx
  components/skeleton/Button.tsx
  components/skeleton/Element.tsx
  components/skeleton/Input.tsx
  components/skeleton/Paragraph.tsx
  components/skeleton/Skeleton.tsx
  components/skeleton/index.tsx
Labels: PR: reviewed-approved

#23218 docs: 📖 Update visual.zh-CN.md
  docs/spec/visual.zh-CN.md
Labels: PR: unreviewed

#23229 chore: Release date is missing after version 4.1.0
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed

#23238 docs: Update Form required desc
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: PR: unreviewed

#23235 fix: fix select rtl
  components/select/style/rtl.less
  site/theme/template/Layout/Header/index.tsx
Labels: PR: reviewed-approved

#23240 chore: Fix console warning typo (validate -> a valid)
  components/checkbox/Checkbox.tsx
  components/checkbox/__tests__/checkbox.test.js
  components/switch/__tests__/index.test.js
  components/switch/index.tsx
  components/upload/Upload.tsx
  components/upload/__tests__/upload.test.js
  scripts/previewEditor/umi.js
Labels: PR: reviewed-changes-requested

#23214 fix: Fix popupClassName prop in timepicker
  components/time-picker/__tests__/__snapshots__/demo.test.js.snap
  components/time-picker/__tests__/index.test.js
  components/time-picker/demo/colored-popup.md
  components/time-picker/index.en-US.md
  components/time-picker/index.tsx
  components/time-picker/index.zh-CN.md
Labels: PR: unreviewed

#23251 docs(Empty component): Fix typo in image prop description 📖
  components/empty/index.en-US.md
Labels: PR: unreviewed

#23250 fix: Select caret missing in Collapse
  components/select/style/multiple.less
Labels: PR: unreviewed

#23231 fix: tree-select render blank in compact mode
  components/tree-select/index.tsx
Labels: PR: unreviewed

#23248 feat: add custom isImgurl prop to Upload Component
  components/upload/Upload.tsx
  components/upload/UploadList.tsx
  components/upload/__tests__/uploadlist.test.js
  components/upload/index.en-US.md
  components/upload/index.zh-CN.md
  components/upload/interface.tsx
Labels: PR: reviewed-approved

#23252 docs(slider): value & defaultValue not consistent with definition
  components/slider/index.en-US.md
  components/slider/index.zh-CN.md
Labels: PR: unreviewed

#23253 Update resources.zh-CN.md
  docs/resources.zh-CN.md
Labels: PR: unreviewed

#23254 docs: Update resources page sketch file
  docs/resources.en-US.md
Labels: PR: unreviewed

#23259 fix: Input inline allowClear style
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/input/ClearableLabeledInput.tsx
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/__tests__/__snapshots__/index.test.js.snap
  components/input/__tests__/__snapshots__/textarea.test.js.snap
  components/input/__tests__/index.test.js
  components/input/__tests__/textarea.test.js
  components/input/style/allow-clear.less
Labels: PR: partially-approved

#23268 docs: Add listHeight desc
  components/select/index.en-US.md
  components/select/index.zh-CN.md
  components/tree-select/index.en-US.md
  components/tree-select/index.zh-CN.md
  docs/react/migration-v4.en-US.md
  docs/react/migration-v4.zh-CN.md
Labels: PR: unreviewed

#23270 docs: Update Table edit row example
  components/table/demo/edit-row.md
Labels: PR: unreviewed

#23272 fix: 🐛 Fix Table filter menu have no height
  components/table/style/index.less
Labels: PR: unreviewed

#23274 fix: Select custom suffixIcon should be accessible
  components/select/style/index.less
Labels: PR: unreviewed

#23243 fix: fix ${theme}-theme.js file order
  .antd-tools.config.js
  docs/react/customize-theme.en-US.md
  docs/react/customize-theme.zh-CN.md
  tests/index.test.js
Labels: PR: unreviewed

#23277 fix: optimize PageHeader responsive behavior
  components/page-header/__tests__/index.test.js
  components/page-header/index.tsx
  components/page-header/style/index.less
  tests/setup.js
Labels: PR: unreviewed

#23295 fix: multiple selector disabled remove icon
  components/select/style/multiple.less
Labels: PR: reviewed-approved

#23296 fix: Dropdown submenu background
  components/dropdown/style/index.less
  components/menu/__tests__/__snapshots__/demo.test.js.snap
  components/menu/demo/horizontal.md
  components/menu/style/index.less
  components/menu/style/rtl.less
Labels: PR: unreviewed

#23303 fix: add missing translations in ru_RU
  components/locale/ru_RU.tsx
Labels: PR: reviewed-approved

#23302 fix: add missing translations in he_IL
  components/locale/he_IL.tsx
Labels: PR: reviewed-approved

#23306 feat: Space support `align`
  components/space/__tests__/__snapshots__/demo.test.js.snap
  components/space/__tests__/__snapshots__/index.test.js.snap
  components/space/demo/align.md
  components/space/demo/customize.md
  components/space/index.en-US.md
  components/space/index.tsx
  components/space/index.zh-CN.md
  components/space/style/index.less
Labels: PR: reviewed-approved

#23319 style: fix menu rtl style
  components/menu/style/rtl.less
Labels: PR: unreviewed

#23312 site: add title upload picture-card
  components/upload/demo/picture-card.md
Labels: PR: unreviewed

#23351 fix: 💄 Fix Input[type=color] height
  components/input/style/index.less
Labels: PR: unreviewed

#23355 docs(components): improve link
  components/card/index.en-US.md
  components/card/index.zh-CN.md
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/list/index.en-US.md
  components/list/index.zh-CN.md
  components/page-header/index.en-US.md
  components/page-header/index.zh-CN.md
  components/popconfirm/index.en-US.md
  components/popover/index.en-US.md
  components/table/index.en-US.md
  components/table/index.zh-CN.md
Labels: PR: unreviewed

#23354 chore: firstActiveValue has been deprecated, remove it
  components/select/index.en-US.md
  components/select/index.zh-CN.md
Labels: PR: unreviewed

#23348 fix: fix tree key ts type
  components/tree/DirectoryTree.tsx
  components/tree/Tree.tsx
  components/tree/utils/dictUtil.ts
Labels: PR: unreviewed

#23364 chore: Refactor affix test to typescript
  components/__tests__/util/domHook.ts
  components/affix/__tests__/Affix.test.tsx
  components/affix/__tests__/__snapshots__/Affix.test.tsx.snap
  components/affix/__tests__/__snapshots__/demo.test.ts.snap
  components/affix/__tests__/demo.test.ts
  components/affix/index.tsx
Labels: PR: reviewed-changes-requested

#23360 fix: Modal.info onOk execute times
  components/modal/ActionButton.tsx
  components/modal/__tests__/confirm.test.js
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
Labels: PR: unreviewed

#23367 refactor(button): rewrite with hook
  components/button/__tests__/type.test.tsx
  components/button/button.tsx
  components/button/index.tsx
Labels: PR: unreviewed

#23130 site: Add 4.x url
  site/bisheng.config.js
  site/theme/template/Layout/Header.jsx
Labels: PR: reviewed-changes-requested

#23165 improvement: Form default locale
  components/config-provider/__tests__/locale.test.js
  components/config-provider/index.tsx
  components/locale-provider/index.tsx
  components/locale/zh_CN.tsx
Labels: PR: unreviewed

#23331 fix: Input.Search ConfigProvider size
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/config-provider/__tests__/components.test.js
  components/config-provider/demo/size.md
  components/input/Search.tsx
Labels: PR: unreviewed

#23376 docs: Update migration for Select events
  docs/react/migration-v4.en-US.md
  docs/react/migration-v4.zh-CN.md
Labels: PR: unreviewed
