Repository ant-design/ant-design, pull requests merged in 2020-01, with the labels that each got.

#20577 fix: form item array children interface
  components/form/FormItem.tsx
  components/form/__tests__/index.test.js
Labels: PR: unreviewed, bug

#20567 docs: HiTu english version
  docs/spec/illustration.en-US.md
Labels: PR: unreviewed, documentation

#20585 chore: 🆙 upgrade stylelint-order
  package.json
Labels: PR: unreviewed, chore

#20588 feat: use @ant-design/icons@4.0.0-alpha.19 to fix ref issue
  components/cascader/__tests__/__snapshots__/index.test.js.snap
  components/input/__tests__/__snapshots__/Password.test.js.snap
  components/input/__tests__/__snapshots__/index.test.js.snap
  components/transfer/__tests__/__snapshots__/index.test.js.snap
  components/transfer/__tests__/__snapshots__/search.test.js.snap
  package.json
Labels: PR: unreviewed, enhancement

#20589 fix: url 404
  docs/spec/transition.en-US.md
  docs/spec/transition.zh-CN.md
Labels: PR: unreviewed, bug

#20593 docs: Update demo remove table background
  components/transfer/demo/table-transfer.md
Labels: PR: unreviewed, documentation

#20515 docs: generate picker
  components/calendar/index.en-US.md
  components/calendar/index.zh-CN.md
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
  components/time-picker/index.en-US.md
  components/time-picker/index.zh-CN.md
  docs/react/contributing.en-US.md
  docs/react/contributing.zh-CN.md
  docs/react/customize-theme.en-US.md
  docs/react/customize-theme.zh-CN.md
  docs/react/faq.en-US.md
  docs/react/faq.zh-CN.md
  docs/react/generate-picker.en-US.md
  docs/react/generate-picker.zh-CN.md
  docs/react/i18n.en-US.md
  docs/react/i18n.zh-CN.md
  docs/react/migration-v4.en-US.md
  docs/react/migration-v4.zh-CN.md
  docs/react/recommendation.en-US.md
  docs/react/recommendation.zh-CN.md
Labels: PR: unreviewed, documentation

#20601 docs: Update colors.zh-CN.md
  docs/spec/colors.zh-CN.md
Labels: PR: unreviewed, documentation

#20573 fix: dark site in Form and iframe change
  components/breadcrumb/demo/router-4.md
  components/breadcrumb/demo/router.md
  components/button/style/index.less
  components/card/style/index.less
  components/layout/__tests__/__snapshots__/demo.test.js.snap
  components/layout/demo/custom-trigger.md
  components/layout/demo/fixed-sider.md
  components/layout/demo/fixed.md
  components/layout/demo/responsive.md
  components/layout/demo/side.md
  components/page-header/__tests__/__snapshots__/demo.test.js.snap
  components/page-header/demo/responsive.md
  components/style/themes/dark.less
  components/style/themes/default.less
  package.json
  site/theme/static/dark.less
  site/theme/static/template.html
  site/theme/template/Content/ComponentDoc.jsx
  site/theme/template/Content/Demo/index.jsx
  site/theme/template/Content/MainContent.jsx
  site/theme/template/Home/index.less
  site/theme/template/Layout/index.jsx
Labels: 4.0, PR: unreviewed, bug

#20606 docs: Update colors.en-US.md
  docs/spec/colors.en-US.md
Labels: PR: unreviewed, documentation

#20607 Revert "docs: Update colors.en-US.md"
  docs/spec/colors.en-US.md
Labels: PR: unreviewed, documentation

#20608 docs: Update colors.en-US.md
  docs/spec/colors.en-US.md
Labels: PR: unreviewed, documentation

#20609 chore: update theme-switcher version
  package.json
Labels: 4.0, PR: unreviewed, chore

#20603 docs: customize-theme.zh-CN.md
  docs/react/customize-theme.zh-CN.md
Labels: 4.0, PR: unreviewed, documentation

#20605 docs: customize-theme.en-US.md
  docs/react/customize-theme.en-US.md
Labels: 4.0, PR: unreviewed, documentation

#20590 refactor: Remove duplicated less loop
  components/auto-complete/__tests__/__snapshots__/demo.test.js.snap
  components/auto-complete/__tests__/index.test.js
  components/card/__tests__/__snapshots__/demo.test.js.snap
  components/card/__tests__/__snapshots__/index.test.js.snap
  components/checkbox/__tests__/__snapshots__/demo.test.js.snap
  components/checkbox/__tests__/group.test.js
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/grid/RowContext.tsx
  components/grid/__tests__/__snapshots__/demo.test.js.snap
  components/grid/__tests__/__snapshots__/index.test.js.snap
  components/grid/__tests__/index.test.js
  components/grid/col.tsx
  components/grid/row.tsx
  components/grid/style/index.less
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/list/__tests__/__snapshots__/demo.test.js.snap
  components/list/style/index.less
  components/mentions/__tests__/__snapshots__/demo.test.js.snap
  components/slider/__tests__/__snapshots__/demo.test.js.snap
  components/statistic/__tests__/__snapshots__/demo.test.js.snap
  components/upload/__tests__/__snapshots__/demo.test.js.snap
  site/theme/static/responsive.less
Labels: PR: unreviewed, refactor

#20612 docs: update Modal docs
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
Labels: PR: unreviewed, documentation

#20622 docs: Update colors.en-US.md
  docs/spec/colors.en-US.md
Labels: PR: unreviewed, documentation

#20621 docs: Update colors.zh-CN.md
  docs/spec/colors.zh-CN.md
Labels: PR: unreviewed, documentation

#20124 docs: update demo of Affix whth hooks
  components/affix/demo/basic.md
  components/affix/demo/debug.md
  components/affix/demo/target.md
Labels: 4.0, PR: unreviewed, documentation

#20629 chore: Merge master into 4.0-prepare
  components/input/Input.tsx
  components/input/Password.tsx
  components/input/__tests__/Password.test.js
  components/message/__tests__/index.test.js
  components/message/index.tsx
  components/steps/style/nav.less
  docs/spec/reaction.en-US.md
  docs/spec/transition.en-US.md
  docs/spec/transition.zh-CN.md
  package.json
Labels: PR: unreviewed, chore

#20631 Master master to 4.x
  components/input/Input.tsx
  components/input/Password.tsx
  components/input/__tests__/Password.test.js
  components/message/__tests__/index.test.js
  components/message/index.tsx
  components/steps/style/nav.less
  docs/spec/reaction.en-US.md
  docs/spec/transition.en-US.md
  docs/spec/transition.zh-CN.md
  package.json
Labels: PR: reviewed-changes-requested

#20570 feat: Form & ConfigProvider support component size
  components/button/button-group.tsx
  components/button/button.tsx
  components/button/index.tsx
  components/calendar/Header.tsx
  components/calendar/__tests__/__snapshots__/demo.test.js.snap
  components/calendar/__tests__/__snapshots__/index.test.js.snap
  components/card/index.tsx
  components/cascader/index.tsx
  components/config-provider/SizeContext.tsx
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/config-provider/demo/size.md
  components/config-provider/index.en-US.md
  components/config-provider/index.tsx
  components/config-provider/index.zh-CN.md
  components/date-picker/generatePicker.tsx
  components/form/Form.tsx
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/demo/size.md
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/input-number/index.tsx
  components/input/ClearableLabeledInput.tsx
  components/input/Input.tsx
  components/radio/group.tsx
  components/radio/interface.tsx
  components/select/index.tsx
  components/switch/index.tsx
  components/table/Table.tsx
  components/table/interface.tsx
  components/tree-select/index.tsx
Labels: PR: reviewed-approved, enhancement

#20636 revert: "refactor: Remove duplicated less loop"
  components/auto-complete/__tests__/__snapshots__/demo.test.js.snap
  components/auto-complete/__tests__/index.test.js
  components/card/__tests__/__snapshots__/demo.test.js.snap
  components/card/__tests__/__snapshots__/index.test.js.snap
  components/checkbox/__tests__/__snapshots__/demo.test.js.snap
  components/checkbox/__tests__/group.test.js
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/grid/RowContext.tsx
  components/grid/__tests__/__snapshots__/demo.test.js.snap
  components/grid/__tests__/__snapshots__/index.test.js.snap
  components/grid/__tests__/index.test.js
  components/grid/col.tsx
  components/grid/row.tsx
  components/grid/style/index.less
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/list/__tests__/__snapshots__/demo.test.js.snap
  components/list/style/index.less
  components/mentions/__tests__/__snapshots__/demo.test.js.snap
  components/slider/__tests__/__snapshots__/demo.test.js.snap
  components/statistic/__tests__/__snapshots__/demo.test.js.snap
  components/upload/__tests__/__snapshots__/demo.test.js.snap
  package.json
  site/theme/static/responsive.less
Labels: PR: unreviewed, revert

#20640 docs: Optimize button docs and demos
  components/button/__tests__/__snapshots__/demo.test.js.snap
  components/button/demo/basic.md
  components/button/demo/block.md
  components/button/demo/danger.md
  components/button/demo/ghost.md
  components/button/demo/size.md
  components/button/index.en-US.md
  components/button/index.zh-CN.md
  components/card/style/index.less
  site/theme/template/Home/DesignPage/index.less
  site/theme/template/Home/index.less
Labels: PR: unreviewed, documentation

#20643 fix: add IE 11 css hack
  components/table/style/index.less
Labels: PR: unreviewed, bug

#20644 fix: DatePicker in Input.Group missing left border when hover
  components/date-picker/style/index.less
Labels: PR: unreviewed, bug

#20645 fix: 修复 carousel dotposition 问题
  components/carousel/__tests__/__snapshots__/index.test.js.snap
  components/carousel/index.tsx
Labels: PR: unreviewed, bug

#20647 docs: 3.26.6 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed, documentation

#20650 Update colors.zh-CN.md
  docs/spec/colors.zh-CN.md
Labels: PR: unreviewed

#20642 fix: dark theme in 4.0
  components/button/index.en-US.md
  components/button/index.zh-CN.md
  components/config-provider/demo/direction.md
  components/drawer/style/drawer.less
  components/empty/index.en-US.md
  components/empty/index.zh-CN.md
  components/form/style/components.less
  components/form/style/index.less
  components/input-number/style/index.less
  components/input/style/mixin.less
  components/menu/__tests__/__snapshots__/demo.test.js.snap
  components/menu/demo/switch-mode.md
  components/menu/style/dark.less
  components/style/themes/dark.less
  components/style/themes/default.less
  components/table/index.zh-CN.md
  components/transfer/index.zh-CN.md
  docs/react/customize-theme.en-US.md
  docs/react/customize-theme.zh-CN.md
  docs/spec/download.en-US.md
  docs/spec/download.zh-CN.md
  site/theme/static/common.less
  site/theme/static/index.less
  site/theme/static/rtl.less
  site/theme/template/Layout/index.jsx
Labels: 4.0, PR: unreviewed, bug

#20654 Update illustration.md
  docs/spec/illustration.md
Labels: PR: unreviewed

#20558 docs: 📝 Add more detail in migration-v4
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  docs/react/migration-v4.en-US.md
  docs/react/migration-v4.zh-CN.md
  package.json
Labels: PR: unreviewed, documentation

#20670 docs: Update year in change log
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed, documentation

#20671 docs/add codemod gif
  docs/react/migration-v4.en-US.md
  docs/react/migration-v4.zh-CN.md
Labels: PR: unreviewed

#20681 fix: Input.Group align in Form.Item
  components/form/style/components.less
Labels: PR: unreviewed, bug

#20685 fix(3.x): Input.Group 1px bug in vertical layout form
  components/form/style/index.less
Labels: PR: unreviewed, bug

#20686 fix: AutoComplete customize input should fully stretch
  components/select/style/single.less
Labels: PR: reviewed-approved, bug

#20690 feat: add footer property to Drawer
  components/drawer/__tests__/Drawer.test.js
  components/drawer/__tests__/__snapshots__/Drawer.test.js.snap
  components/drawer/demo/form-in-drawer.md
  components/drawer/demo/multi-level-drawer.md
  components/drawer/index.en-US.md
  components/drawer/index.tsx
  components/drawer/index.zh-CN.md
  components/drawer/style/drawer.less
  components/modal/style/modal.less
  components/style/themes/default.less
Labels: PR: reviewed-changes-requested, enhancement

#20691 fix: FormItem should not trigger feedback className without hasFeedback
  components/form/FormItem.tsx
Labels: PR: unreviewed, bug

#20689 fix: change maxHeight
  components/typography/util.tsx
Labels: PR: unreviewed, bug

#20696 docs: Update illustration.md
  docs/spec/illustration.md
Labels: PR: unreviewed, documentation

#20695 fix: Table ts define
  components/table/Column.tsx
  components/table/ColumnGroup.tsx
  components/table/Table.tsx
  components/table/__tests__/type.test.tsx
Labels: PR: unreviewed, bug

#20701 fix: Card cover image get skretched
  components/card/style/index.less
Labels: PR: unreviewed, bug

#20699 fix: Slider Tooltip not follow handler
  components/slider/SliderTooltip.tsx
  components/slider/index.tsx
  package.json
Labels: PR: unreviewed, bug

#20703 fix: Table should not crash with empty column children
  components/table/__tests__/Table.test.js
  components/table/hooks/useFilter/index.tsx
  components/table/hooks/useSorter.tsx
  components/table/interface.tsx
Labels: PR: reviewed-changes-requested, bug

#20705 fix: Chrome scale 125% should not display y-scrollbar
  components/table/style/index.less
Labels: PR: unreviewed, bug

#20702 refactor: improve digital input in tooltip demo
  components/input/demo/tooltip.md
Labels: PR: unreviewed, refactor

#20717 refactor: improve digital input in tooltip demo (#20702)
  components/input/demo/tooltip.md
Labels: 3.x, PR: unreviewed, refactor

#20718 fix: correct the collapse-borderless class variable
  components/collapse/style/index.less
Labels: PR: unreviewed, bug

#20720 fix: Cascader search bug when fieldNames existed
  components/cascader/__tests__/__snapshots__/index.test.js.snap
  components/cascader/__tests__/index.test.js
  components/cascader/index.tsx
Labels: PR: reviewed-changes-requested, bug

#20721 chore: cherry-pick #20718
  components/collapse/style/index.less
Labels: 3.x, PR: unreviewed, chore

#20725 fix: Form validate should keep refresh
  components/form/__tests__/index.test.js
  components/form/util.ts
Labels: PR: reviewed-changes-requested, 🐛 Bug

#20735 fix: RowSelection fixed should work
  components/table/__tests__/__snapshots__/Table.rowSelection.test.js.snap
  components/table/hooks/useSelection.tsx
Labels: PR: unreviewed, bug

#20733 chore: Warning when FormItem use render props and name at same time
  components/form/FormItem.tsx
  components/form/__tests__/index.test.js
Labels: PR: reviewed-changes-requested, chore

#20737 fix: TextArea autoSize blink in FireFox
  components/input/ResizableTextArea.tsx
Labels: PR: unreviewed, bug

#20747 style: 🔤 Tweak font family, same as tailwindcss
  components/style/themes/dark.less
  components/style/themes/default.less
  docs/spec/font.en-US.md
  docs/spec/font.zh-CN.md
Labels: PR: unreviewed, style

#20730 docs: 📝 update title to Replace Moment.js
  components/calendar/index.en-US.md
  components/calendar/index.zh-CN.md
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
  components/time-picker/index.en-US.md
  components/time-picker/index.zh-CN.md
  docs/react/faq.en-US.md
  docs/react/faq.zh-CN.md
  docs/react/replace-moment.en-US.md
  docs/react/replace-moment.zh-CN.md
Labels: PR: unreviewed, documentation

#20751 fix: tweak @zindex-badge for table fixed column
  components/style/themes/default.less
Labels: PR: unreviewed

#20753 fix: Tree switcher icon
  components/tree/Tree.tsx
  components/tree/__tests__/__snapshots__/demo.test.js.snap
  components/tree/__tests__/index.test.js
Labels: PR: unreviewed

#20755 fix: Tree switcherIcon shown in leaf node (#20753)
  components/tree/__tests__/index.test.js
  components/tree/utils/iconUtil.tsx
Labels: PR: unreviewed, bug

#20760 fix: 修复DatePicker 预设范围的选择按钮样式
  components/date-picker/style/index.less
Labels: PR: unreviewed, bug

#20765 fix: .iconfont-size-under-12px not working
  components/pagination/style/index.less
  components/style/mixins/iconfont.less
  components/table/style/index.less
Labels: PR: unreviewed, bug

#20762 fix: Grid initial gutter
  components/_util/responsiveObserve.ts
  components/descriptions/index.tsx
  components/grid/__tests__/__snapshots__/demo.test.js.snap
  components/grid/row.tsx
Labels: PR: unreviewed, bug

#20767 feat: increase article length
  components/typography/__tests__/__snapshots__/demo.test.js.snap
  components/typography/demo/suffix.md
Labels: PR: unreviewed, enhancement

#20777 chore: Add log generate
  package.json
  scripts/print-changelog.js
Labels: PR: unreviewed, chore

#20781 fix: 修复 Carousel 组件 left/right 模式下卡片轮播方向
  components/carousel/__tests__/__snapshots__/index.test.js.snap
  components/carousel/index.tsx
Labels: PR: unreviewed, bug

#20783 chore: Not block input when Input value is `undefined`
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/input/ClearableLabeledInput.tsx
  components/input/Input.tsx
  components/input/__tests__/index.test.js
  docs/react/migration-v4.en-US.md
  docs/react/migration-v4.zh-CN.md
Labels: PR: unreviewed

#20789 chore: Add missing Table export interface
  components/table/index.tsx
Labels: PR: unreviewed, chore

#20794 fix: Move table-bg less variable into table background instead of td
  components/table/style/index.less
Labels: PR: unreviewed, bug

#20791 fix: npm start warning
  .eslintignore
  .gitignore
  package.json
  scripts/print-changelog.js
  site/theme/template/Color/ColorPicker.tsx
  site/theme/template/Layout/Footer.d.ts
  site/theme/template/Layout/Footer.tsx
  site/theme/template/utils.d.ts
  site/theme/template/utils.tsx
Labels: PR: unreviewed

#20796 chore: dark site images address
  components/button/index.en-US.md
  components/button/index.zh-CN.md
  components/empty/__tests__/__snapshots__/demo.test.js.snap
  components/empty/demo/customize.md
  components/empty/index.en-US.md
  components/empty/index.zh-CN.md
  components/page-header/__tests__/__snapshots__/demo.test.js.snap
  components/page-header/demo/content.md
  site/theme/static/dark.less
  site/theme/template/Content/Demo/index.jsx
Labels: 4.x, PR: unreviewed, chore, 🐛 Bug

#20736 tweak: DatePicker styling
  components/date-picker/style/panel.less
  components/style/themes/dark.less
  components/style/themes/default.less
Labels: 4.x, PR: unreviewed

#20790 style: 优化calendar若干样式
  components/calendar/Header.tsx
  components/calendar/style/index.less
Labels: PR: reviewed-approved

#20805 fix: Update table deps & fix bordered placeholder missing border right
  components/table/style/bordered.less
  package.json
Labels: PR: unreviewed, bug

#20808 fix: Table expand icon not clickable when expandRowByClick is set
  components/table/ExpandIcon.tsx
  components/table/__tests__/Table.expand.test.js
Labels: PR: reviewed-changes-requested, bug

#20786 chore: Descriptions warning message upgrade
  components/descriptions/__tests__/index.test.js
  components/descriptions/index.tsx
Labels: PR: unreviewed, chore

#20683 chore: pause deploy site
  .github/workflows/deploy-site.yml
Labels: PR: unreviewed

#20830 docs: Fix Documentation for Form API
  components/form/demo/complex-form-control.md
Labels: PR: unreviewed, documentation

#20838 fix: fix contributors css overflow not wrap
  site/theme/static/contributors.less
Labels: PR: unreviewed, bug

#20832 docs: 4.0.0-rc.1 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed, documentation

#20843 Update buttons.md
  docs/spec/buttons.md
Labels: PR: unreviewed

#20844 Update data-list.md
  docs/spec/data-list.md
Labels: PR: unreviewed

#20845 Update visualization-page.md
  docs/spec/visualization-page.md
Labels: PR: unreviewed

#20846 Update detail-page.md
  docs/spec/detail-page.md
Labels: PR: unreviewed

#20836 fix(Form.Item): label text align not correct when media less than xs and span not 24
  components/form/style/vertical.less
Labels: PR: unreviewed, bug

#20849 chore: upgrade stylelint
  package.json
Labels: PR: unreviewed, chore

#20815 feat: 🆕 Add buttonsRender to Dropdown
  components/dropdown/__tests__/__snapshots__/demo.test.js.snap
  components/dropdown/demo/dropdown-button.md
  components/dropdown/dropdown-button.tsx
  components/dropdown/index.en-US.md
  components/dropdown/index.zh-CN.md
Labels: PR: unreviewed, enhancement

#20853 fix: 修复中文模式下，更新日志的 Head 中 Menu 显示
  site/theme/template/Layout/Header.jsx
Labels: PR: unreviewed, bug

#20856 fix: message shadow get cutted
  components/message/style/index.less
Labels: PR: unreviewed, bug

#20858 fix: Table onChange return cached data
  components/table/__tests__/Table.filter.test.js
  components/table/hooks/useFilter/index.tsx
  components/table/hooks/useSorter.tsx
Labels: PR: reviewed-changes-requested, bug

#20818 feat: add back @border-radius-sm
  components/style/themes/default.less
Labels: PR: unreviewed, enhancement

#20869 Remove magic number of style align
  components/button/style/index.less
  components/button/style/mixin.less
  components/input/style/affix.less
  components/input/style/mixin.less
  components/select/style/multiple.less
  components/select/style/single.less
  components/style/themes/default.less
Labels: PR: unreviewed

#20821 fix: better approach to solve not show overflow content when in elastic
  components/table/style/index.less
Labels: 3.x, PR: unreviewed, bug

#20745 docs: tree-select docs upgrade
  components/tree-select/index.en-US.md
  components/tree-select/index.zh-CN.md
Labels: PR: unreviewed

#20861 fix: select 多选时的 padding
  components/select/style/multiple.less
  components/select/style/single.less
Labels: PR: unreviewed, bug

#20873 docs: 3.26.7 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed, documentation

#20880 chore: change check commit
  scripts/check-commit.js
Labels: PR: reviewed-changes-requested, chore

#20883 fix: Select placeholder style issue
  components/select/style/index.less
  components/select/style/multiple.less
Labels: PR: unreviewed, bug

#20872 fix: Input affix use inline-flex
  components/input/ClearableLabeledInput.tsx
  components/input/Input.tsx
  components/input/__tests__/__snapshots__/Password.test.js.snap
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/__tests__/__snapshots__/index.test.js.snap
  components/input/demo/presuffix.md
  components/input/style/affix.less
  components/input/style/index.less
  components/input/style/mixin.less
  components/transfer/__tests__/__snapshots__/search.test.js.snap
Labels: PR: unreviewed, bug

#20886 fix: help will shake in Form
  components/form/FormItemInput.tsx
  components/form/__tests__/index.test.js
  components/form/util.ts
Labels: PR: reviewed-changes-requested, bug

#20890 docs: add tabBarExtraContent version in doc
  components/card/index.en-US.md
  components/card/index.zh-CN.md
Labels: 3.x, PR: unreviewed, documentation

#20892 fix: update docs & table version
  components/table/__tests__/__snapshots__/Table.expand.test.js.snap
  components/table/__tests__/__snapshots__/Table.filter.test.js.snap
  components/table/__tests__/__snapshots__/Table.pagination.test.js.snap
  components/table/__tests__/__snapshots__/Table.rowSelection.test.js.snap
  components/table/__tests__/__snapshots__/Table.sorter.test.js.snap
  components/table/__tests__/__snapshots__/Table.test.js.snap
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/transfer/__tests__/__snapshots__/demo.test.js.snap
  docs/react/migration-v4.en-US.md
  docs/react/migration-v4.zh-CN.md
  package.json
Labels: PR: unreviewed, bug

#20894 fix: Tooltip hidden when title is 0
  components/tooltip/__tests__/tooltip.test.js
  components/tooltip/index.tsx
Labels: PR: reviewed-changes-requested, bug

#20898 chore: update azure config to support site deploy
  azure-pipelines.yml
Labels: PR: unreviewed, chore

#20899 chore: Feature merge master
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  azure-pipelines.yml
  components/button/style/index.less
  components/button/style/mixin.less
  components/dropdown/__tests__/__snapshots__/demo.test.js.snap
  components/dropdown/demo/dropdown-button.md
  components/dropdown/dropdown-button.tsx
  components/dropdown/index.en-US.md
  components/dropdown/index.zh-CN.md
  components/form/FormItemInput.tsx
  components/form/__tests__/index.test.js
  components/form/demo/complex-form-control.md
  components/form/style/vertical.less
  components/form/util.ts
  components/input/ClearableLabeledInput.tsx
  components/input/Input.tsx
  components/input/__tests__/__snapshots__/Password.test.js.snap
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/__tests__/__snapshots__/index.test.js.snap
  components/input/demo/presuffix.md
  components/input/style/affix.less
  components/input/style/index.less
  components/input/style/mixin.less
  components/message/style/index.less
  components/select/style/index.less
  components/select/style/multiple.less
  components/select/style/single.less
  components/style/mixins/compatibility.less
  components/style/themes/default.less
  components/table/__tests__/Table.filter.test.js
  components/table/__tests__/__snapshots__/Table.expand.test.js.snap
  components/table/__tests__/__snapshots__/Table.filter.test.js.snap
  components/table/__tests__/__snapshots__/Table.pagination.test.js.snap
  components/table/__tests__/__snapshots__/Table.rowSelection.test.js.snap
  components/table/__tests__/__snapshots__/Table.sorter.test.js.snap
  components/table/__tests__/__snapshots__/Table.test.js.snap
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/hooks/useFilter/index.tsx
  components/table/hooks/useSorter.tsx
  components/tooltip/__tests__/tooltip.test.js
  components/tooltip/index.tsx
  components/transfer/__tests__/__snapshots__/demo.test.js.snap
  components/transfer/__tests__/__snapshots__/search.test.js.snap
  components/tree-select/index.en-US.md
  components/tree-select/index.zh-CN.md
  docs/react/faq.en-US.md
  docs/react/faq.zh-CN.md
  docs/react/migration-v4.en-US.md
  docs/react/migration-v4.zh-CN.md
  docs/react/replace-moment.en-US.md
  docs/react/replace-moment.zh-CN.md
  package.json
  site/theme/static/contributors.less
  site/theme/template/Layout/Header.jsx
Labels: PR: reviewed-changes-requested, chore

#20900 chore: Add DatePicker related interface ts export
  components/date-picker/index.tsx
Labels: PR: unreviewed, chore

#20904 chore: Update comment
  azure-pipelines.yml
  scripts/azure-github-comment.js
Labels: PR: reviewed-changes-requested, chore

#20774 4.0 Form scrollToField: Pass options to form scrollToField
  components/form/__tests__/index.test.js
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/form/interface.ts
  components/form/util.ts
Labels: PR: reviewed-approved, scrollToField

#20897 fix: List actions inconsistent position
  components/list/Item.tsx
  components/list/__tests__/__snapshots__/demo.test.js.snap
  components/list/style/index.less
Labels: PR: unreviewed, bug

#20884 style: Optimize select other sizes placeholder text centered
  components/select/index.en-US.md
  components/select/index.zh-CN.md
  components/select/style/multiple.less
Labels: PR: unreviewed, style

#20912 fix: Update index.en-US.md
  components/icon/index.en-US.md
Labels: PR: unreviewed, bug

#20911 docs: Add Tree virtual scroll demo
  components/tree/DirectoryTree.tsx
  components/tree/Tree.tsx
  components/tree/__tests__/demo.test.js
  components/tree/demo/virtual-scroll.md
  package.json
  site/theme/template/Content/ComponentDoc.jsx
  typings/custom-typings.d.ts
Labels: PR: unreviewed, documentation

#20913 docs: fix typo
  components/icon/index.en-US.md
Labels: PR: unreviewed, documentation

#20914 fix: Avoid Select clear icon overlap with selections
  components/select/style/multiple.less
Labels: PR: unreviewed, bug

#20915 chore: Feature merge master
  azure-pipelines.yml
  components/date-picker/index.tsx
  components/icon/index.en-US.md
  components/list/Item.tsx
  components/list/__tests__/__snapshots__/demo.test.js.snap
  components/list/style/index.less
  components/select/index.en-US.md
  components/select/index.zh-CN.md
  components/select/style/multiple.less
  components/tree/DirectoryTree.tsx
  components/tree/Tree.tsx
  components/tree/__tests__/demo.test.js
  components/tree/demo/virtual-scroll.md
  package.json
  scripts/azure-github-comment.js
  site/theme/template/Content/ComponentDoc.jsx
  typings/custom-typings.d.ts
Labels: PR: reviewed-changes-requested, chore

#20926 docs: fix range-picker docs error
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
Labels: 3.x, PR: unreviewed, documentation

#20939 feat: use @ant-design/icons-rc.0
  package.json
Labels: PR: unreviewed, enhancement

#20944 docs: tfjs icon 3 to 4
  site/theme/template/IconDisplay/IconPicSearcher.tsx
Labels: PR: unreviewed, documentation

#20951 chore: feature merge master
  components/select/style/multiple.less
  components/table/__tests__/__snapshots__/demo.test.js.snap
  package.json
  site/theme/template/IconDisplay/IconPicSearcher.tsx
Labels: PR: reviewed-approved, chore

#20942 docs: 🐛 Fix icons missing in document
  site/theme/template/IconDisplay/fields.ts
Labels: PR: unreviewed, documentation

#20954 docs: Fix wording of a FAQ entry in form documentation
  components/form/index.en-US.md
Labels: PR: unreviewed, documentation

#20962 docs: Update index.zh-CN.md
  components/tabs/index.zh-CN.md
Labels: PR: unreviewed, documentation

#20946 docs: fix auto complete demo
  components/auto-complete/__tests__/__snapshots__/demo.test.js.snap
  components/auto-complete/demo/certain-category.md
  components/auto-complete/demo/uncertain-category.md
Labels: PR: unreviewed, documentation

#20963 fix: Form.Item keep render even it's not a Field
  components/form/FormItem.tsx
  components/form/FormItemInput.tsx
  components/form/FormItemLabel.tsx
  components/form/__tests__/index.test.js
Labels: PR: unreviewed, bug

#20965 Update MorePage.tsx
  site/theme/template/Home/MorePage.tsx
Labels: PR: unreviewed

#20966 Update article.zh-CN.md
  docs/spec/article.zh-CN.md
Labels: PR: unreviewed

#20964 docs: Fix autoComplete demo
  components/auto-complete/demo/basic.md
Labels: PR: unreviewed, documentation

#20960 fix: Tooltip doesn't disappear on disabled Dropdown.Button
  components/dropdown/__tests__/dropdown-button.test.js
  components/dropdown/dropdown-button.tsx
Labels: PR: reviewed-changes-requested, bug

#20682 chore: 3.x deploy site
  .github/workflows/deploy-site.yml
Labels: 3.x, PR: unreviewed

#20967 chore: Remove `labelInValue` in AutoComplete props
  components/auto-complete/index.tsx
Labels: PR: unreviewed, chore

#20968 fix: Table selectAll should not checked when all the checkbox is disa…
  components/table/__tests__/Table.rowSelection.test.js
  components/table/hooks/useSelection.tsx
Labels: PR: reviewed-changes-requested, bug

#20969 docs: fix contributing docs
  docs/react/contributing.en-US.md
  docs/react/contributing.zh-CN.md
Labels: PR: unreviewed, documentation

#20972 Revert "docs: fix contributing docs"
  docs/react/contributing.en-US.md
  docs/react/contributing.zh-CN.md
Labels: PR: reviewed-approved, documentation

#20977 docs: Update visualization-page.md
  docs/spec/visualization-page.md
Labels: PR: unreviewed, documentation

#20980 Update data-list.md
  docs/spec/data-list.md
Labels: PR: unreviewed

#20981 Update detail-page.md
  docs/spec/detail-page.md
Labels: PR: unreviewed

#20970 docs: Format string notation of all components
  components/avatar/index.en-US.md
  components/avatar/index.zh-CN.md
  components/badge/index.zh-CN.md
  components/collapse/index.en-US.md
  components/collapse/index.zh-CN.md
  components/config-provider/index.en-US.md
  components/config-provider/index.zh-CN.md
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
  components/descriptions/index.en-US.md
  components/descriptions/index.zh-CN.md
  components/divider/index.en-US.md
  components/divider/index.zh-CN.md
  components/drawer/index.en-US.md
  components/drawer/index.zh-CN.md
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/grid/index.en-US.md
  components/grid/index.zh-CN.md
  components/layout/index.en-US.md
  components/layout/index.zh-CN.md
  components/list/index.en-US.md
  components/list/index.zh-CN.md
  components/mentions/index.en-US.md
  components/mentions/index.zh-CN.md
  components/menu/index.en-US.md
  components/menu/index.zh-CN.md
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
  components/progress/index.en-US.md
  components/progress/index.zh-CN.md
  components/result/index.en-US.md
  components/result/index.zh-CN.md
  components/skeleton/index.en-US.md
  components/skeleton/index.zh-CN.md
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/transfer/index.en-US.md
  components/transfer/index.zh-CN.md
  components/typography/index.en-US.md
  components/typography/index.zh-CN.md
Labels: PR: reviewed-approved, documentation

#20984 docs: translation API description
  components/form/index.en-US.md
  components/list/index.en-US.md
  components/list/index.zh-CN.md
  components/pagination/index.zh-CN.md
Labels: PR: unreviewed, documentation

#20983 fix:Drawer组件添加 footerStyle 控制台报错
  components/drawer/__tests__/__snapshots__/Drawer.test.js.snap
  components/drawer/index.tsx
Labels: PR: unreviewed

#20988 docs: update drawer demo
  components/drawer/demo/form-in-drawer.md
  components/drawer/demo/multi-level-drawer.md
Labels: PR: unreviewed, documentation

#20989 chore: Update RecommendPage.tsx
  site/theme/template/Home/RecommendPage.tsx
Labels: PR: unreviewed, chore

#21003 docs: Update buttons.md
  docs/spec/buttons.md
Labels: PR: unreviewed, documentation

#21000 chore: browserslist typo
  package.json
Labels: PR: unreviewed, chore

#21004 docs: Update buttons.md
  docs/spec/buttons.md
Labels: PR: unreviewed, documentation

#21013 feat: (Timeline): add @timeline-item-padding variable
  components/style/themes/default.less
  components/timeline/style/index.less
Labels: PR: reviewed-approved, enhancement

#21015 chore: Revert #21013 and upgrade
  components/style/themes/default.less
  components/timeline/style/index.less
Labels: PR: unreviewed, chore

#21024 fix: Table locale emptyText should work
  components/table/Table.tsx
  components/table/__tests__/__snapshots__/empty.test.js.snap
  components/table/__tests__/empty.test.js
Labels: PR: reviewed-changes-requested, bug

#21026 fix: Form.Item ignore help = ''
  components/form/FormItem.tsx
  components/form/__tests__/index.test.js
Labels: PR: reviewed-changes-requested, bug

#20754 docs: Design doc
  components/auto-complete/demo/certain-category.md
  components/auto-complete/demo/uncertain-category.md
  docs/spec/buttons.md
  docs/spec/copywriting.md
  docs/spec/dark.md
  docs/spec/data-display.en-US.md
  docs/spec/data-display.zh-CN.md
  docs/spec/data-entry.en-US.md
  docs/spec/data-entry.zh-CN.md
  docs/spec/data-format.md
  docs/spec/data-list.md
  docs/spec/detail-page.md
  docs/spec/feedback.en-US.md
  docs/spec/feedback.zh-CN.md
  docs/spec/form-page.md
  docs/spec/icon.en-US.md
  docs/spec/icon.zh-CN.md
  docs/spec/navigation.en-US.md
  docs/spec/navigation.zh-CN.md
  docs/spec/overview.zh-CN.md
  docs/spec/shadow.md
  docs/spec/visualization-page.md
  site/bisheng.config.js
  site/theme/static/dark.less
  site/theme/static/design-doc.less
  site/theme/static/index.less
  site/theme/template/Content/MainContent.jsx
  site/theme/template/Home/MorePage.tsx
  site/theme/template/Home/RecommendPage.tsx
  site/theme/template/utils.tsx
Labels: PR: unreviewed
