Repository ant-design/ant-design, pull requests merged in 2020-06, with the labels that each got.

#24631 fix: Select input style
  components/select/style/index.less
Labels: PR: unreviewed

#24633 fix: demo on Typography.paragraph
  components/typography/demo/ellipsis.md
Labels: PR: unreviewed

#24615 fix: #24519 Upload delete icon cannot be navigate via keyboard
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/upload/UploadList.tsx
  components/upload/__tests__/__snapshots__/demo.test.js.snap
  components/upload/__tests__/__snapshots__/uploadlist.test.js.snap
  components/upload/style/index.less
  components/upload/style/index.tsx
Labels: PR: unreviewed

#24632 fix: adjust notification default place in rtl
  components/notification/index.tsx
Labels: PR: unreviewed

#24622 fix: #24614 text button style inconsistent in `danger`
  components/button/__tests__/__snapshots__/demo.test.ts.snap
  components/button/demo/danger.md
  components/button/demo/disabled.md
  components/button/style/index.less
  components/button/style/mixin.less
Labels: PR: unreviewed

#24641 docs: improve form validate rule
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: PR: unreviewed

#24644 chore: Steps children
  package.json
Labels: PR: unreviewed

#24648 chore: Add TabPaneProps def
  components/tabs/index.tsx
Labels: PR: unreviewed

#24651 fix: Remove dropdownMatchSelectWidth warning
  components/drawer/index.tsx
Labels: PR: unreviewed

#24654 test: fix lighthouse ci
  .github/workflows/lighthouse-ci.yml
Labels: PR: unreviewed

#24657 chore: 📦 enable ESBUILD for site again
  .github/workflows/lighthouse-ci.yml
  components/radio/__tests__/__snapshots__/demo.test.js.snap
  components/radio/demo/disabled.md
  package.json
  site/theme/template/Content/MainContent.jsx
Labels: PR: unreviewed

#24658 chore: merge master into feature
  components/button/__tests__/__snapshots__/demo.test.ts.snap
  components/button/demo/danger.md
  components/button/demo/disabled.md
  components/button/style/index.less
  components/button/style/mixin.less
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/drawer/index.tsx
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/notification/index.tsx
  components/radio/__tests__/__snapshots__/demo.test.js.snap
  components/radio/demo/disabled.md
  components/select/style/index.less
  components/tabs/__tests__/__snapshots__/demo.test.js.snap
  components/tabs/__tests__/__snapshots__/index.test.js.snap
  components/tabs/index.tsx
  components/typography/demo/ellipsis.md
  components/upload/UploadList.tsx
  components/upload/__tests__/__snapshots__/demo.test.js.snap
  components/upload/__tests__/__snapshots__/uploadlist.test.js.snap
  components/upload/style/index.less
  components/upload/style/index.tsx
  package.json
  site/theme/template/Content/MainContent.jsx
Labels: PR: reviewed-approved

#24661 fix: table component wrapped in a row components, table no scrollbar
  components/table/style/index.less
Labels: PR: unreviewed

#24665 fix: Increase dependency version: scroll-into-view-if-needed@^2.2.25
  package.json
Labels: PR: unreviewed

#24643 fix: tabs inkbar border lost
  components/tabs/style/card.less
  components/tabs/style/index.less
  components/tabs/style/position.less
  components/tabs/style/rtl.less
Labels: PR: unreviewed

#24677 fix: Tabs dropdown extra horizontal scrollbar
  components/dropdown/style/index.less
  components/tabs/style/dropdown.less
Labels: PR: unreviewed

#24678 fix: btn loading
  components/button/__tests__/type.test.tsx
  components/button/button.tsx
  components/button/demo/loading.md
Labels: PR: unreviewed

#24666 fix: Radio.Group options: Element type is invalid
  components/radio/index.tsx
  components/radio/radio.tsx
Labels: PR: unreviewed

#24683 docs: 4.3.1 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#24686 test: ✅ fix tests checker
  .github/tests_checker.yml
Labels: PR: unreviewed

#24685 test: 📦 use ESBUILD in codesandbox ci
  webpack.config.js
Labels: PR: reviewed-changes-requested

#24687 test: ✅ fix codesandbox ci
  package.json
Labels: PR: unreviewed

#24689 docs: Corrected documentation grammar errors on replacing Moment.js
  docs/react/replace-moment.en-US.md
Labels: PR: reviewed-approved

#24693 fix: Radio typescript error typo
  components/radio/index.tsx
Labels: PR: reviewed-approved

#24673 fix: 💄 IE11 input height issue (#23955)
  components/input/style/IE11.less
  components/input/style/index.less
Labels: PR: reviewed-approved

#24695 fix: Cal onPanelChange
  components/calendar/__tests__/index.test.js
  components/calendar/generateCalendar.tsx
Labels: PR: unreviewed

#24655 feat: add successColor for Progress
  components/progress/Circle.tsx
  components/progress/Line.tsx
  components/progress/__tests__/__snapshots__/index.test.js.snap
  components/progress/__tests__/index.test.js
  components/progress/demo/segment.md
  components/progress/index.en-US.md
  components/progress/index.zh-CN.md
  components/progress/progress.tsx
Labels: PR: reviewed-approved

#24702 fix: Dropdown menu item link color when has icon
  components/dropdown/style/index.less
  components/menu/__tests__/__snapshots__/demo.test.js.snap
  components/menu/demo/vertical.md
Labels: PR: unreviewed

#24701 docs: update the usage of craco-less
  docs/react/use-with-create-react-app.en-US.md
  docs/react/use-with-create-react-app.zh-CN.md
Labels: PR: unreviewed

#24703 docs: Update use-in-typescript.md
  docs/react/use-in-typescript.en-US.md
  docs/react/use-in-typescript.zh-CN.md
Labels: PR: unreviewed

#24706 fix: adjust select default listItemHeight for small size & compact mode
  components/select/index.tsx
Labels: PR: unreviewed

#24682 feat: modal method rtl
  components/modal/ConfirmDialog.tsx
  components/modal/Modal.tsx
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
  components/modal/style/rtl.less
  components/modal/useModal/HookModal.tsx
Labels: PR: unreviewed

#24707 fix: 🌑 Dropdown dark menu color
  components/dropdown/style/index.less
Labels: PR: unreviewed

#24713 fix: btn loading 2 twice
  components/button/__tests__/type.test.tsx
  components/button/button.tsx
Labels: PR: unreviewed

#24715 style: optimize tabs dropdown rtl style
  components/tabs/style/rtl.less
  package.json
Labels: PR: unreviewed

#24714 feat: #24670 allow user customize table font size with less variable
  components/style/themes/default.less
  components/table/style/index.less
  components/table/style/size.less
Labels: PR: unreviewed

#24716 chore: Adds Hebrew localisations for Form
  components/locale/he_IL.tsx
Labels: PR: reviewed-approved

#24718 feat: Support rowSelection.dirty
  components/table/__tests__/Table.rowSelection.test.js
  components/table/demo/ajax.md
  components/table/hooks/useSelection.tsx
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/table/interface.tsx
Labels: PR: reviewed-approved

#24727 feat: drawer support getPopupContainer and getPrefixCls by ConfigProvider
  components/config-provider/__tests__/container.test.js
  components/drawer/__tests__/__snapshots__/demo.test.js.snap
  components/drawer/demo/config-provider.md
  components/drawer/index.tsx
Labels: PR: unreviewed

#24742 Update MorePage.tsx
  site/theme/template/Home/MorePage.tsx
Labels: PR: unreviewed

#24743 fix: Tag.CheckableTag don't support onClick
  components/tag/CheckableTag.tsx
  components/tag/__tests__/index.test.js
Labels: PR: unreviewed

#24734 feat: add ghost prop for collapse
  components/collapse/Collapse.tsx
  components/collapse/__tests__/__snapshots__/demo.test.js.snap
  components/collapse/demo/ghost.md
  components/collapse/index.en-US.md
  components/collapse/index.zh-CN.md
  components/collapse/style/index.less
Labels: PR: reviewed-approved

#24756 chore: Update antd tools
  package.json
Labels: PR: unreviewed

#24429 fix: paramter type error
  components/tree/Tree.tsx
  components/tree/__tests__/type.test.tsx
Labels: PR: partially-approved

#24711 feat: form instance support getFieldInstance
  components/form/Form.tsx
  components/form/FormItem.tsx
  components/form/FormItemInput.tsx
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/__tests__/ref.test.tsx
  components/form/context.tsx
  components/form/demo/ref-item.md
  components/form/hooks/useCacheErrors.ts
  components/form/hooks/useForm.ts
  components/form/hooks/useFrameState.ts
  components/form/hooks/useItemRef.ts
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/form/interface.ts
  components/form/util.ts
Labels: PR: reviewed-approved

#24764 refactor: Card demo and code
  components/card/__tests__/__snapshots__/demo.test.js.snap
  components/card/demo/basic.md
  components/card/demo/border-less.md
  components/card/demo/in-column.md
  components/card/demo/loading.md
  components/card/demo/tabs.md
  components/card/index.tsx
  components/tabs/__tests__/__snapshots__/demo.test.js.snap
  components/tabs/demo/editable-card.md
Labels: PR: merged

#23869 feat: dropdown support arrow
  components/dropdown/__tests__/__snapshots__/demo.test.js.snap
  components/dropdown/demo/arrow.md
  components/dropdown/dropdown.tsx
  components/dropdown/index.en-US.md
  components/dropdown/index.zh-CN.md
  components/dropdown/style/index.less
Labels: PR: reviewed-approved

#24724 fix: badge offset in rtl
  components/badge/__tests__/__snapshots__/demo.test.js.snap
  components/badge/__tests__/__snapshots__/index.test.js.snap
  components/badge/__tests__/index.test.js
  components/badge/demo/offset.md
  components/badge/index.en-US.md
  components/badge/index.tsx
  components/badge/index.zh-CN.md
Labels: PR: unreviewed

#24779 docs: remove Tag afterClose from docs
  components/tag/__tests__/index.test.js
  components/tag/index.en-US.md
  components/tag/index.zh-CN.md
Labels: PR: unreviewed

#24514 fix: bugs on pageSize change in List
  components/list/__tests__/pagination.test.js
  components/list/index.tsx
Labels: PR: unreviewed

#24782 fix: Statistic don't work with Tooltip
  components/statistic/Statistic.tsx
  components/statistic/__tests__/index.test.js
Labels: PR: unreviewed

#24781 fix: TimePicker.RangePicker bordred when has className
  components/date-picker/generatePicker/generateRangePicker.tsx
  components/time-picker/__tests__/__snapshots__/demo.test.js.snap
  components/time-picker/__tests__/__snapshots__/index.test.js.snap
  components/time-picker/__tests__/index.test.js
  components/time-picker/demo/bordered.md
Labels: PR: unreviewed

#24783 feat: Add ko_KR localizations for Form
  components/locale/ko_KR.tsx
Labels: PR: unreviewed

#24785 chore: ⚡️ upgarde rc-select@11.0.0 and rc-tree-select@4.0.0
  package.json
Labels: PR: unreviewed

#24765 docs: 4.3.2 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#24790 fix: grammer in english font documentation page
  docs/spec/font.en-US.md
Labels: PR: reviewed-approved

#24792 fix: typo on skeleton element
  components/skeleton/demo/element.md
Labels: PR: reviewed-approved

#24802 fix: Drawer cannot open
  components/drawer/__tests__/Drawer.test.js
  components/drawer/__tests__/__snapshots__/Drawer.test.js.snap
  components/drawer/index.tsx
Labels: PR: unreviewed

#24806 fix: Menu SubMenu scroll problem
  components/menu/style/index.less
Labels: PR: unreviewed

#24808 test: ✅ Add test cases for Notification
  components/notification/__tests__/hooks.test.js
  components/notification/__tests__/index.test.js
Labels: PR: unreviewed

#24814 docs: select dropdownRender no longer accepts props
  components/select/index.en-US.md
  components/select/index.zh-CN.md
Labels: PR: unreviewed

#24824 fix: rewrite drag table demo
  components/table/demo/drag-sorting.md
Labels: PR: unreviewed

#24762 chore: change the style of ghost collapse & demo modified
  components/collapse/__tests__/__snapshots__/demo.test.js.snap
  components/collapse/demo/ghost.md
  components/collapse/index.en-US.md
  components/collapse/index.zh-CN.md
  components/collapse/style/index.less
Labels: PR: unreviewed

#24812 feat: cascader dropdown-render prop
  components/cascader/__tests__/__snapshots__/demo.test.js.snap
  components/cascader/demo/custom-dropdown.md
  components/cascader/index.en-US.md
  components/cascader/index.tsx
  components/cascader/index.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#24829 chore: steps nav active line height, 3px -> 2px
  components/steps/style/nav.less
Labels: PR: unreviewed

#24842 feat: 🆕 support Drawer closeIcon
  components/drawer/__tests__/Drawer.test.js
  components/drawer/__tests__/DrawerEvent.test.js
  components/drawer/__tests__/__snapshots__/Drawer.test.js.snap
  components/drawer/index.en-US.md
  components/drawer/index.tsx
  components/drawer/index.zh-CN.md
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
Labels: PR: partially-approved

#24843 docs: 🔍 Add search input to overview page
  site/theme/en-US.js
  site/theme/template/Content/ComponentOverview.jsx
  site/theme/template/Content/ComponentOverview.less
  site/theme/zh-CN.js
Labels: PR: unreviewed

#24847 fix: Fixed code that increased package size if tree shaking is disabled
  components/transfer/ListItem.tsx
Labels: PR: unreviewed

#24852 fix: table multiple sorter
  components/table/__tests__/Table.sorter.test.js
  components/table/hooks/useSorter.tsx
Labels: PR: unreviewed

#24853 docs: Update placeholder type for Rangepicker
  components/time-picker/index.en-US.md
Labels: PR: unreviewed

#24861 docs: update picker placeholder
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
  components/time-picker/index.en-US.md
  components/time-picker/index.zh-CN.md
Labels: PR: unreviewed

#24865 feat: cascader expandIcon
  components/cascader/__tests__/__snapshots__/demo.test.js.snap
  components/cascader/demo/suffix.md
  components/cascader/index.en-US.md
  components/cascader/index.tsx
  components/cascader/index.zh-CN.md
Labels: PR: partially-approved

#24867 fix: Form List warning
  components/form/FormItem.tsx
  components/form/__tests__/index.test.js
  components/form/__tests__/list.test.js
  components/form/util.ts
  tests/utils.ts
Labels: PR: unreviewed

#24846 refactor: reduce CSS size
  components/button/style/mixin.less
Labels: PR: reviewed-approved

#24866 fix: export CardInterface from Card resolves #24864
  components/card/index.tsx
Labels: PR: unreviewed

#24873 fix: Tabs shaking of content
  components/card/__tests__/__snapshots__/demo.test.js.snap
  components/page-header/__tests__/__snapshots__/demo.test.js.snap
  components/tabs/__tests__/__snapshots__/demo.test.js.snap
  package.json
Labels: PR: unreviewed

#24697 feat: add table onChange an action param
  components/table/Table.tsx
  components/table/__tests__/Table.filter.test.js
  components/table/__tests__/Table.pagination.test.js
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/table/interface.tsx
Labels: PR: unreviewed

#24878 docs: refine typo of Skeleton
  components/skeleton/index.en-US.md
  components/skeleton/index.zh-CN.md
Labels: PR: reviewed-approved

#24877 style: add `@divider-orientation-margin` less
  components/divider/style/index.less
  components/divider/style/rtl.less
  components/style/themes/default.less
Labels: PR: unreviewed

#24883 docs: typo of Typography
  components/typography/__tests__/__snapshots__/demo.test.js.snap
  components/typography/demo/basic.md
Labels: PR: reviewed-approved

#24870 fix: Add interface for Option props.
  components/select/index.tsx
Labels: PR: unreviewed

#24881 refactor: clean up some deprecated API
  components/auto-complete/index.tsx
  components/config-provider/context.tsx
  components/input/Group.tsx
  components/modal/useModal/HookModal.tsx
  components/typography/Typography.tsx
Labels: PR: unreviewed

#24869 style: optimize comment actions style
  components/comment/style/index.less
  components/comment/style/rtl.less
Labels: PR: reviewed-approved

#24885 feat: add closeIcon customize tag close
  components/tag/__tests__/__snapshots__/demo.test.js.snap
  components/tag/demo/customize.md
  components/tag/index.en-US.md
  components/tag/index.tsx
  components/tag/index.zh-CN.md
  components/tag/style/index.less
  components/tag/style/rtl.less
Labels: PR: reviewed-approved

#24900 test: fix jest with less import
  .jest.js
  package.json
Labels: PR: unreviewed

#24899 docs: fix typos and grammar
  docs/react/contributing.en-US.md
  docs/spec/cases.en-US.md
Labels: PR: unreviewed

#24905 chore: Feature merge master
  .jest.js
  components/auto-complete/index.tsx
  components/card/__tests__/__snapshots__/demo.test.js.snap
  components/card/index.tsx
  components/comment/style/index.less
  components/comment/style/rtl.less
  components/config-provider/context.tsx
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
  components/divider/style/index.less
  components/divider/style/rtl.less
  components/form/FormItem.tsx
  components/form/__tests__/index.test.js
  components/form/__tests__/list.test.js
  components/input/Group.tsx
  components/modal/useModal/HookModal.tsx
  components/page-header/__tests__/__snapshots__/demo.test.js.snap
  components/select/__tests__/__snapshots__/demo.test.js.snap
  components/select/index.tsx
  components/skeleton/index.en-US.md
  components/skeleton/index.zh-CN.md
  components/style/themes/default.less
  components/table/__tests__/Table.sorter.test.js
  components/table/hooks/useSorter.tsx
  components/tabs/__tests__/__snapshots__/demo.test.js.snap
  components/tabs/demo/position.md
  components/tag/__tests__/__snapshots__/demo.test.js.snap
  components/time-picker/index.en-US.md
  components/time-picker/index.zh-CN.md
  components/transfer/ListItem.tsx
  components/typography/Typography.tsx
  components/typography/__tests__/__snapshots__/demo.test.js.snap
  components/typography/demo/basic.md
  docs/react/contributing.en-US.md
  docs/spec/cases.en-US.md
  package.json
  site/theme/en-US.js
  site/theme/template/Content/ComponentOverview.jsx
  site/theme/template/Content/ComponentOverview.less
  site/theme/zh-CN.js
  tests/utils.ts
Labels: PR: unreviewed

#24893 docs: caveat about testing in contributing.md
  docs/react/contributing.en-US.md
  docs/react/contributing.zh-CN.md
Labels: PR: unreviewed

#24809 feat: add radio `optionType` api to set radio option type
  components/radio/__tests__/__snapshots__/demo.test.js.snap
  components/radio/demo/radiogroup-options.md
  components/radio/group.tsx
  components/radio/index.en-US.md
  components/radio/index.zh-CN.md
  components/radio/interface.tsx
  components/radio/radio.tsx
Labels: PR: partially-approved

#24903 feat: expand rate character
  components/rate/__tests__/__snapshots__/demo.test.js.snap
  components/rate/demo/character-function.md
  components/rate/demo/character.md
  components/rate/demo/clear.md
  components/rate/index.en-US.md
  components/rate/index.zh-CN.md
  package.json
Labels: PR: unreviewed

#24910 docs: fix Import in Browser link not found
  docs/react/faq.en-US.md
  docs/react/faq.zh-CN.md
Labels: PR: unreviewed

#24908 docs: reduce button demo
  components/button/__tests__/__snapshots__/demo.test.ts.snap
  components/button/demo/block.md
  components/button/demo/disabled.md
  components/button/demo/icon.md
  components/button/demo/legacy-group.md
  components/button/demo/multiple.md
  components/button/demo/size.md
Labels: PR: unreviewed

#24912 test: ✅ add test case to Select
  components/select/__tests__/__snapshots__/index.test.js.snap
  components/select/__tests__/index.test.js
Labels: PR: unreviewed

#24887 Refactor demo code box actions
  site/theme/static/dark.less
  site/theme/static/demo.less
  site/theme/template/Content/ComponentDoc.jsx
  site/theme/template/Content/Demo/CodePenIcon.jsx
  site/theme/template/Content/Demo/CodeSandboxIcon.jsx
  site/theme/template/Content/Demo/RiddleIcon.jsx
  site/theme/template/Content/Demo/index.jsx
Labels: PR: unreviewed

#24917 style: add `@rate-star-hover-scale`
  components/rate/style/index.less
  components/style/themes/default.less
Labels: PR: reviewed-approved

#24926 docs: adapt table edit-rows demo's style to 4.0
  components/table/demo/edit-row.md
Labels: PR: unreviewed

#24923 docs: remove combobox related descriptions of Select
  components/select/index.en-US.md
  components/select/index.zh-CN.md
Labels: PR: unreviewed

#24915 docs: reduce typography demo
  components/typography/__tests__/__snapshots__/demo.test.js.snap
  components/typography/demo/ellipsis-debug.md
  components/typography/demo/ellipsis.md
  components/typography/demo/interactive.md
  components/typography/demo/paragraph-debug.md
  components/typography/demo/suffix.md
  components/typography/demo/title.md
Labels: PR: unreviewed

#24928 fix: Tabs dropdown overflow
  components/tabs/style/dropdown.less
Labels: PR: unreviewed

#24929 fix: Field id
  components/form/FormItem.tsx
  components/form/__tests__/index.test.js
Labels: PR: unreviewed

#24936 feat: Upload support patch method
  components/upload/interface.tsx
Labels: PR: unreviewed

#24925 refactor(avatar): rewrite with hook
  components/avatar/__tests__/Avatar.test.js
  components/avatar/__tests__/__snapshots__/Avatar.test.js.snap
  components/avatar/index.tsx
Labels: PR: unreviewed

#24938 fix: getTargetContainer is not omit in Drawer
  components/drawer/index.tsx
Labels: PR: unreviewed

#24945 style: Adjust result children
  components/result/__tests__/__snapshots__/demo.test.js.snap
  components/result/index.tsx
  components/style/themes/default.less
Labels: PR: reviewed-approved

#24907 feat: remove content max-width on dot-step
  components/steps/style/progress-dot.less
Labels: PR: reviewed-approved

#24944 fix: Avatar falling back to children on image error
  components/avatar/__tests__/Avatar.test.js
  components/avatar/__tests__/__snapshots__/Avatar.test.js.snap
  components/avatar/index.en-US.md
  components/avatar/index.tsx
  components/avatar/index.zh-CN.md
Labels: PR: reviewed-approved

#24952 fix: shoundn't keep table filterDropdown inner status in controlled mode
  components/table/__tests__/Table.filter.test.js
  components/table/hooks/useFilter/FilterDropdown.tsx
Labels: PR: unreviewed

#24955 fix: List grid not working in React.Fragment or wrapped List.Item
  components/list/__tests__/__snapshots__/Item.test.js.snap
  components/list/__tests__/__snapshots__/demo.test.js.snap
  components/list/demo/grid-test.md
  components/list/index.tsx
Labels: PR: unreviewed

#24956 fix: add modal confirm default icon
  components/modal/confirm.tsx
Labels: PR: unreviewed

#24901 refactor: rewrite Search with hook
  components/input/ClearableLabeledInput.tsx
  components/input/Search.tsx
  components/input/__tests__/Search.test.js
  components/input/style/rtl.less
Labels: PR: unreviewed

#24963 fix: Table shouldCellUpdate
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  package.json
Labels: PR: unreviewed

#24805 feat: add Skeleton-Image
  components/skeleton/Avatar.tsx
  components/skeleton/Element.tsx
  components/skeleton/Image.tsx
  components/skeleton/Skeleton.tsx
  components/skeleton/__tests__/__snapshots__/demo.test.js.snap
  components/skeleton/__tests__/__snapshots__/index.test.js.snap
  components/skeleton/__tests__/index.test.js
  components/skeleton/demo/element.md
  components/skeleton/style/index.less
  components/style/themes/compact.less
  components/style/themes/default.less
Labels: PR: unreviewed

#24922 chore: fix tabs-demo style in compact mode
  components/tabs/demo/card-top.md
Labels: PR: reviewed-approved

#24961 feat: Mentions support autoSize
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/mentions/__tests__/__snapshots__/demo.test.js.snap
  components/mentions/__tests__/__snapshots__/index.test.js.snap
  components/mentions/demo/autoSize.md
  components/mentions/demo/basic.md
  components/mentions/index.en-US.md
  components/mentions/index.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#24965 chore: add displayName to Search
  components/input/Search.tsx
Labels: PR: unreviewed

#24948 chore: remove emptyText from TableProps
  components/table/Table.tsx
Labels: PR: reviewed-approved

#24966 chore: replace textarea with rc-textarea
  components/input/ResizableTextArea.tsx
  components/input/TextArea.tsx
  components/input/__tests__/textarea.test.js
  components/input/calculateNodeHeight.tsx
  components/typography/__tests__/index.test.js
  package.json
Labels: PR: reviewed-approved

#24964 feat: update pagination@2.3.0 support onChange called when pageSize change
  components/list/__tests__/pagination.test.js
  components/list/index.tsx
  components/pagination/__tests__/index.test.js
  components/table/__tests__/Table.pagination.test.js
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#24958 feat: Implement centered prop in Tabs
  components/tabs/__tests__/__snapshots__/demo.test.js.snap
  components/tabs/demo/centered.md
  components/tabs/index.en-US.md
  components/tabs/index.tsx
  components/tabs/index.zh-CN.md
  components/tabs/style/index.less
Labels: PR: partially-approved

#24979 fix: Form.validateTrigger not work
  components/form/FormItem.tsx
  components/form/__tests__/index.test.js
Labels: PR: unreviewed

#24981 docs: 4.3.4 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#24982 docs: changelog 3.26.18
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#24996 refactor: Reduce Button CSS size
  components/button/style/mixin.less
Labels: PR: unreviewed

#24997 fix: subMenu background when dark compact
  components/menu/style/dark.less
Labels: PR: unreviewed

#24652 fix: fixed typedef of Slider value
  components/slider/index.tsx
Labels: PR: unreviewed

#24773 feat: Add modal style parameter
  components/modal/style/modal.less
  components/style/themes/compact.less
  components/style/themes/default.less
Labels: PR: reviewed-approved

#24991 fix: PageHeader tabs broken style since 4.3.0
  components/page-header/style/index.less
Labels: PR: reviewed-approved

#25007 test: fix buildkite/puppeteer version
  Dockerfile.ui-test
Labels: PR: unreviewed

#24992 fix: List.Item.Meta width overflow
  components/list/style/index.less
Labels: PR: unreviewed

#25001 refactor: reduce table filter max height
  components/table/style/index.less
Labels: PR: unreviewed

#25017 test(Search): remove useless async
  components/input/__tests__/Search.test.js
Labels: PR: unreviewed

#25018 fix: List label text not start aligned in safari
  components/descriptions/style/index.less
Labels: PR: unreviewed

#24983 fix: allow selecting only value on double click on DescriptionsItem
  components/descriptions/style/index.less
Labels: PR: unreviewed

#25006 feat: export Tabs addIcon
  components/rate/__tests__/__snapshots__/demo.test.js.snap
  components/tabs/index.en-US.md
  components/tabs/index.tsx
  components/tabs/index.zh-CN.md
  components/tabs/style/index.less
Labels: PR: reviewed-approved

#25032 feat: showNow on timepicker and datetimepicker
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
  components/time-picker/index.en-US.md
  components/time-picker/index.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#25012 refactor: rewrite Password with hooks
  components/input/Password.tsx
  components/input/__tests__/Password.test.js
  components/input/__tests__/__snapshots__/Password.test.js.snap
Labels: PR: unreviewed

#24995 fix: nested unbordered table inside a bordered table has border.
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/demo/nest-table-border-debug.md
  components/table/style/bordered.less
Labels: PR: reviewed-approved

#25035 feat: update rc-picker@1.7.1 and fix icons of month and quarter picker in DatePicker Component
  components/date-picker/__tests__/__snapshots__/other.test.js.snap
  package.json
Labels: PR: reviewed-approved

#25036 refactor: refine some typos
  components/input/__tests__/Password.test.js
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/demo/autosize-textarea.md
  components/input/demo/group.md
  components/input/demo/presuffix.md
  components/input/demo/search-input-loading.md
Labels: PR: partially-approved

#25004 docs: reduce affix demo
  components/affix/__tests__/__snapshots__/demo.test.ts.snap
  components/affix/demo/basic.md
Labels: PR: unreviewed

#25003 docs: reduce layout demo
  components/layout/__tests__/__snapshots__/demo.test.js.snap
  components/layout/demo/basic.md
Labels: PR: unreviewed

#25005 docs: reduce dropdown demo
  components/dropdown/__tests__/__snapshots__/demo.test.js.snap
  components/dropdown/demo/placement.md
Labels: PR: unreviewed

#25049 fix: Search crash in AutoComplete
  components/input/Search.tsx
  components/input/__tests__/Search.test.js
Labels: PR: unreviewed

#25026 docs: remove unnecessary
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/demo/dynamic-settings.md
Labels: PR: unreviewed

#25053 docs: fix missing
  components/time-picker/index.zh-CN.md
Labels: PR: reviewed-approved

#25045 fix: Update `Form.Item` TypeScript definition
  components/form/FormItem.tsx
Labels: PR: unreviewed

#25059 fix: avoid colorPalette error when the saturation/value === 1
  components/style/color/colorPalette.less
Labels: PR: unreviewed

#25065 feat: add type export
  components/tree/index.tsx
Labels: PR: unreviewed

#25019 fix: TimePicker panel align
  components/date-picker/style/panel.less
Labels: PR: unreviewed

#25073 style: Add empty style for Table empty filters menu
  components/locale/default.tsx
  components/locale/zh_CN.tsx
  components/locale/zh_TW.tsx
  components/table/__tests__/Table.filter.test.js
  components/table/hooks/useFilter/FilterDropdown.tsx
  components/table/interface.tsx
Labels: PR: unreviewed
