Repository ant-design/ant-design, pull requests merged in 2020-12, with the labels that each got.

#28092 fix: Collapse.Panel collapsible should be optional
  components/collapse/CollapsePanel.tsx
Labels: PR: reviewed-approved

#28102 docs: 4.9.1 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#28095 refactor: optimize <Timeline/> bundle size
  components/timeline/Timeline.tsx
Labels: PR: unreviewed

#28094 refactor: <Timeline/> move defaultProps into single destructuring
  components/timeline/Timeline.tsx
Labels: PR: unreviewed

#28090 fix: Make dontAnimate optional in CarouselRef interface
  components/carousel/index.tsx
Labels: PR: unreviewed

#27268 chore: 🆙 upgrade react 17
  .github/workflows/lighthouse-ci.yml
  .github/workflows/test.yml
  .travis.yml
  components/alert/__tests__/__snapshots__/index.test.tsx.snap
  components/alert/__tests__/index.test.tsx
  components/config-provider/__tests__/locale.test.js
  components/grid/__tests__/index.test.js
  components/switch/__tests__/__snapshots__/index.test.js.snap
  components/switch/__tests__/index.test.js
  package.json
  scripts/travis-script.sh
  site/bisheng.config.js
  tests/setup.js
Labels: PR: unreviewed

#28117 doc: supplement Form.List errors
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: PR: unreviewed

#28136 chore: merge master into feature
  .github/workflows/compressed-size.yml
  .github/workflows/lighthouse-ci.yml
  .github/workflows/test.yml
  .travis.yml
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/alert/__tests__/__snapshots__/index.test.tsx.snap
  components/alert/__tests__/index.test.tsx
  components/carousel/index.tsx
  components/collapse/CollapsePanel.tsx
  components/config-provider/__tests__/locale.test.js
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/grid/__tests__/index.test.js
  components/switch/__tests__/__snapshots__/index.test.js.snap
  components/switch/__tests__/index.test.js
  components/timeline/Timeline.tsx
  package.json
  scripts/travis-script.sh
  site/bisheng.config.js
  tests/setup.js
Labels: PR: reviewed-approved

#28140 docs: set image preview false in placeholder demo
  components/image/demo/placeholder.md
Labels: PR: unreviewed

#28133 test: skip List loading demo
  components/list/__tests__/image.test.ts
Labels: PR: unreviewed

#28130 fix: TextArea showCount style while using with Form
  components/form/style/index.less
Labels: PR: unreviewed

#28122 chore: optimize useModal performance
  components/_util/hooks/usePatchElement.tsx
  components/modal/useModal/index.tsx
Labels: PR: unreviewed

#28153 fix: Add type of initialValue prop to Form.List
  components/form/FormList.tsx
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: PR: unreviewed

#28150 fix(Tree): fix tree drop indicator default direction
  components/tree/utils/dropIndicator.tsx
Labels: PR: unreviewed

#28148 feat: add onClick props to Message component (#28131)
  components/message/__tests__/index.test.js
  components/message/index.en-US.md
  components/message/index.tsx
  components/message/index.zh-CN.md
Labels: PR: reviewed-approved

#27682 Allow overlayInnerStyle to pass through in Tooltip component
  components/tooltip/__tests__/tooltip.test.js
  components/tooltip/index.tsx
Labels: PR: unreviewed

#28164 docs: fix typo
  components/form/index.en-US.md
Labels: PR: unreviewed

#28167 chore: Add auto merge action
  .github/workflows/label-merge.yml
Labels: PR: unreviewed

#28172 chore: Feature merge master
  .github/workflows/label-merge.yml
  components/_util/hooks/usePatchElement.tsx
  components/form/FormList.tsx
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/form/style/index.less
  components/image/demo/placeholder.md
  components/list/__tests__/image.test.ts
  components/modal/useModal/index.tsx
  components/tooltip/__tests__/tooltip.test.js
  components/tooltip/index.tsx
  components/tree/utils/dropIndicator.tsx
  docs/react/migration-v4.en-US.md
  docs/react/migration-v4.zh-CN.md
Labels: BranchAutoMerge, PR: reviewed-approved, PR: unreviewed

#28173 fix: Table selection position
  components/table/style/index.less
Labels: PR: unreviewed

#28177 chore: Feature merge master
  .github/workflows/label-merge.yml
  components/table/style/index.less
Labels: BranchAutoMerge, PR: reviewed-approved, PR: unreviewed

#28180 fix: Dropdown click area
  components/dropdown/style/index.less
Labels: PR: unreviewed

#28145 feat: add showCount.formatter for TextArea
  components/input/TextArea.tsx
  components/input/__tests__/textarea.test.js
  components/input/index.en-US.md
  components/input/index.zh-CN.md
Labels: PR: partially-approved

#28126 style(steps): Fix Steps progressDot style
  components/steps/style/progress-dot.less
Labels: PR: reviewed-approved

#28182 refactor: add className in BreadcrumbItemProps
  components/breadcrumb/BreadcrumbItem.tsx
  components/breadcrumb/index.en-US.md
  components/breadcrumb/index.zh-CN.md
Labels: PR: unreviewed

#28192 docs: Enable en aritles
  docs/resources.en-US.md
  docs/resources.zh-CN.md
  site/theme/template/Home/index.tsx
Labels: PR: unreviewed

#28193 fix: 防止手动设置 selectedRowKeys 为 undefined 时，derivedSelectedKeys 为 undefined，导致 js crash。
  components/table/__tests__/Table.rowSelection.test.js
  components/table/hooks/useSelection.tsx
Labels: PR: unreviewed

#28195 fix: typo in test
  components/table/__tests__/Table.rowSelection.test.js
Labels: PR: reviewed-approved

#28207 refactor: cleanup <LoadingIcon /> and reduce bundle size on ~1.25kb
  components/button/LoadingIcon.tsx
Labels: PR: unreviewed

#28201 perf(📦): remove @ant-design/css-animation
  components/_util/wave.tsx
  package.json
Labels: PR: unreviewed

#28206 fix: SelectionSelectFn类型定义中selectedRows属性改为T范型
  components/table/interface.tsx
Labels: PR: reviewed-approved

#28176 fix: Layout overflow style for table sticky
  components/layout/style/index.less
Labels: PR: unreviewed

#28211 refactor: <Button /> rewrite props defaults in a way to use single source of truth
  components/button/button.tsx
Labels: PR: unreviewed

#28219 fix: Tag cursor style
  components/tag/style/index.less
Labels: PR: unreviewed

#28108 style: Alert rtl
  components/alert/style/index.less
  components/alert/style/rtl.less
Labels: PR: unreviewed

#28224 docs: use Space improve demo
  components/dropdown/__tests__/__snapshots__/demo.test.js.snap
  components/dropdown/demo/dropdown-button.md
Labels: PR: unreviewed

#28227 chore: Add pr as condition
  .github/workflows/test.yml
Labels: PR: unreviewed

#28053 feat: Modal.method support afterClose
  components/modal/Modal.tsx
  components/modal/__tests__/confirm.test.js
  components/modal/confirm.tsx
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
Labels: PR: reviewed-approved

#28221 docs: changelog 4.9.2
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#28235 feat: Image add preview style
  components/avatar/__tests__/__snapshots__/demo.test.js.snap
  components/image/__tests__/__snapshots__/demo.test.js.snap
  components/image/__tests__/__snapshots__/index.test.js.snap
  components/image/demo/placeholder.md
  components/image/index.tsx
  components/image/style/index.less
  components/locale-provider/index.tsx
  components/locale/default.tsx
  components/locale/zh_CN.tsx
  components/message/__tests__/index.test.js
  components/style/themes/default.less
  package.json
Labels: PR: unreviewed

#28240 fix: Standalone Badge motion style
  components/badge/ScrollNumber.tsx
  components/badge/__tests__/__snapshots__/demo.test.js.snap
  components/badge/demo/no-wrapper.md
  components/badge/index.tsx
  components/badge/style/index.less
Labels: PR: unreviewed

#28242 docs: Fixed typo in preview property
  components/image/demo/placeholder.md
Labels: PR: reviewed-approved

#28264 docs: fix tree api and improve other api
  components/alert/index.en-US.md
  components/alert/index.zh-CN.md
  components/breadcrumb/index.en-US.md
  components/breadcrumb/index.zh-CN.md
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
  components/tree/index.en-US.md
  components/tree/index.zh-CN.md
Labels: PR: unreviewed

#28262 fix: TS definition for Tree
  components/tree/Tree.tsx
  components/tree/index.en-US.md
  components/tree/index.zh-CN.md
Labels: PR: unreviewed

#28220 fix: table filter
  components/table/Table.tsx
  components/table/__tests__/Table.filter.test.js
  components/table/hooks/useFilter/index.tsx
Labels: PR: unreviewed

#28249 feat: Table expandable column width
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#28270 docs: fix Form errorFields name
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: PR: unreviewed

#28274 docs: add discussions link
  README-zh_CN.md
  docs/react/introduce.en-US.md
  docs/react/introduce.zh-CN.md
Labels: PR: unreviewed

#28269 style: fix Tree node hover background of unselectable
  components/tree/Tree.tsx
  components/tree/style/mixin.less
  components/tree/style/rtl.less
Labels: PR: unreviewed

#28278 docs: remove gitter & add discussion
  README-pt_BR.md
  README-zh_CN.md
  README.md
  docs/react/introduce.en-US.md
  docs/react/introduce.zh-CN.md
  site/theme/en-US.js
  site/theme/template/Layout/Footer.tsx
  site/theme/zh-CN.js
Labels: PR: unreviewed

#28223 chore: statisc suffix fontsize inherit from value style
  components/statistic/style/index.less
Labels: PR: unreviewed

#28263 fix: Image.PreviewGroup typescript definition
  components/image/PreviewGroup.tsx
Labels: PR: reviewed-approved

#28291 chore: Wave component isHidden function has not invaild hidden css attribute
  components/_util/wave.tsx
Labels: PR: unreviewed

#28294 chore: Feature merge master
  components/_util/wave.tsx
  components/image/PreviewGroup.tsx
Labels: BranchAutoMerge, PR: reviewed-approved

#28304 fix: improve message().then type
  components/message/__tests__/type.test.tsx
  components/message/index.tsx
Labels: PR: unreviewed

#28311 docs: Update complex-form-control.md
  components/form/demo/complex-form-control.md
Labels: PR: unreviewed

#28272 feat: Form scrollToFirstError support ScrollLogicalPosition
  components/form/Form.tsx
  components/form/__tests__/index.test.js
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: PR: unreviewed

#28326 fix: titles of TransferProps type to ReactNode
  components/transfer/index.tsx
  components/transfer/list.tsx
Labels: PR: unreviewed

#28324 feat: Form scrollToFirstError change type from ScrollLogicalPosition to Options
  components/form/Form.tsx
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: PR: reviewed-approved

#28340 docs: fix AutoComplete allowClear description
  components/auto-complete/index.en-US.md
  components/auto-complete/index.zh-CN.md
Labels: PR: unreviewed

#28197 docs: optimize trigger of Form.Item
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: PR: unreviewed

#28341 docs(✨): changelog for 4.9.3
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#28346 fix: Fixed columns z-index issue
  .prettierignore
  components/alert/index.en-US.md
  components/auto-complete/index.en-US.md
  components/auto-complete/index.zh-CN.md
  components/breadcrumb/index.en-US.md
  components/breadcrumb/index.zh-CN.md
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/modal/index.zh-CN.md
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/table/style/index.less
  components/tree/index.en-US.md
  components/tree/index.zh-CN.md
  docs/react/introduce.en-US.md
  docs/react/introduce.zh-CN.md
Labels: PR: unreviewed

#28347 docs: add English translations in customize-theme
  docs/react/customize-theme.en-US.md
Labels: PR: reviewed-approved

#28354 fix(Tree): leaf-line should set relative position
  components/tree/style/mixin.less
Labels: PR: unreviewed

#28363 chore: Update gitleaks.yml
  .github/workflows/gitleaks.yml
Labels: PR: unreviewed

#28362 fix: message.loading return hide type
  components/message/__tests__/type.test.tsx
  components/message/index.tsx
Labels: PR: unreviewed

#28365 docs: Remove Upload `transformFile` prop
  components/upload/Upload.tsx
  components/upload/__tests__/__snapshots__/demo.test.js.snap
  components/upload/__tests__/uploadlist.test.js
  components/upload/demo/transform-file.md
  components/upload/demo/upload-with-aliyun-oss.md
  components/upload/index.en-US.md
  components/upload/index.zh-CN.md
  components/upload/interface.tsx
Labels: PR: partially-approved

#28367 feat: Upload support `maxCount`
  components/upload/Upload.tsx
  components/upload/__tests__/__snapshots__/demo.test.js.snap
  components/upload/__tests__/upload.test.js
  components/upload/demo/max-count.md
  components/upload/interface.tsx
Labels: PR: reviewed-approved

#28372 fix: Menu title hover transition bug in Chrome
  components/menu/style/index.less
Labels: PR: unreviewed

#28376 docs: add 4.9.4 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#28374 Set title as not required property
  components/page-header/index.tsx
Labels: PR: unreviewed

#28381 chore: merge master into feature
  .github/workflows/gitleaks.yml
  .prettierignore
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/alert/index.en-US.md
  components/auto-complete/index.en-US.md
  components/auto-complete/index.zh-CN.md
  components/breadcrumb/index.en-US.md
  components/breadcrumb/index.zh-CN.md
  components/form/demo/complex-form-control.md
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/menu/style/index.less
  components/message/__tests__/type.test.tsx
  components/message/index.tsx
  components/modal/index.zh-CN.md
  components/page-header/index.tsx
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/table/style/index.less
  components/transfer/__tests__/__snapshots__/demo.test.js.snap
  components/transfer/demo/basic.md
  components/transfer/index.tsx
  components/transfer/list.tsx
  components/tree/index.en-US.md
  components/tree/index.zh-CN.md
  components/tree/style/mixin.less
  components/upload/Upload.tsx
  components/upload/__tests__/__snapshots__/demo.test.js.snap
  components/upload/__tests__/uploadlist.test.js
  components/upload/demo/transform-file.md
  components/upload/demo/upload-with-aliyun-oss.md
  components/upload/index.en-US.md
  components/upload/index.zh-CN.md
  components/upload/interface.tsx
  docs/react/customize-theme.en-US.md
  docs/react/introduce.en-US.md
  docs/react/introduce.zh-CN.md
  package.json
Labels: BranchAutoMerge, PR: partially-approved, PR: unreviewed

#28382 fix: fix drawer wrong characters
  components/drawer/index.zh-CN.md
Labels: PR: reviewed-approved

#28396 docs: fix typo
  docs/spec/illustration.en-US.md
  docs/spec/illustration.zh-CN.md
Labels: PR: unreviewed

#28397 docs: fix typo
  docs/spec/illustration.zh-CN.md
Labels: PR: unreviewed

#28389 chore: Add demo tsx check
  .eslintignore
  .github/workflows/test.yml
  components/affix/demo/target.md
  components/alert/__tests__/__snapshots__/demo.test.ts.snap
  components/alert/demo/error-boundary.md
  components/auto-complete/demo/non-case-sensitive.md
  components/auto-complete/demo/uncertain-category.md
  components/drawer/demo/config-provider.md
  components/form/demo/advanced-search.md
  components/form/demo/basic.md
  components/form/demo/control-hooks.md
  components/form/demo/control-ref.md
  components/form/demo/customized-form-controls.md
  components/form/demo/dynamic-rule.md
  components/form/demo/form-context.md
  components/form/demo/form-in-modal.md
  components/form/demo/global-state.md
  components/form/demo/inline-login.md
  components/form/demo/layout.md
  components/form/demo/nest-messages.md
  components/form/demo/normal-login.md
  components/form/demo/register.md
  components/form/demo/required-mark.md
  components/form/demo/size.md
  components/form/demo/time-related-controls.md
  components/form/demo/validate-other.md
  components/form/demo/without-form-create.md
  components/mentions/demo/form.md
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/demo/edit-cell.md
  components/table/demo/edit-row.md
  components/table/demo/row-selection.md
  components/table/demo/virtual-list.md
  components/tree/demo/basic-controlled.md
  components/tree/demo/basic.md
  components/tree/demo/directory.md
  components/tree/demo/dynamic.md
  components/tree/demo/line.md
  components/upload/Upload.tsx
  components/upload/interface.tsx
  package.json
  scripts/check-ts-demo.js
  typings/custom-typings.d.ts
Labels: PR: unreviewed

#28401 chore: merge master info feature
  .eslintignore
  .github/workflows/test.yml
  components/affix/demo/target.md
  components/alert/__tests__/__snapshots__/demo.test.ts.snap
  components/alert/demo/error-boundary.md
  components/auto-complete/demo/non-case-sensitive.md
  components/auto-complete/demo/uncertain-category.md
  components/drawer/demo/config-provider.md
  components/drawer/index.zh-CN.md
  components/form/demo/advanced-search.md
  components/form/demo/basic.md
  components/form/demo/control-hooks.md
  components/form/demo/control-ref.md
  components/form/demo/customized-form-controls.md
  components/form/demo/dynamic-rule.md
  components/form/demo/form-context.md
  components/form/demo/form-in-modal.md
  components/form/demo/global-state.md
  components/form/demo/inline-login.md
  components/form/demo/layout.md
  components/form/demo/nest-messages.md
  components/form/demo/normal-login.md
  components/form/demo/register.md
  components/form/demo/required-mark.md
  components/form/demo/size.md
  components/form/demo/time-related-controls.md
  components/form/demo/validate-other.md
  components/form/demo/without-form-create.md
  components/mentions/demo/form.md
  components/message/index.zh-CN.md
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/demo/edit-cell.md
  components/table/demo/edit-row.md
  components/table/demo/row-selection.md
  components/table/demo/virtual-list.md
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/tree/demo/basic-controlled.md
  components/tree/demo/basic.md
  components/tree/demo/directory.md
  components/tree/demo/dynamic.md
  components/tree/demo/line.md
  components/upload/Upload.tsx
  components/upload/interface.tsx
  docs/spec/illustration.en-US.md
  docs/spec/illustration.zh-CN.md
  package.json
  scripts/check-ts-demo.js
  typings/custom-typings.d.ts
Labels: BranchAutoMerge, PR: reviewed-approved, PR: unreviewed

#28402 test(✅): fix Modal coverage
  components/modal/__tests__/confirm.test.js
Labels: PR: reviewed-approved

#28421 docs: fixed typo in documentation
  components/modal/index.en-US.md
Labels: PR: reviewed-approved

#28439 fix: image 5px problem
  components/image/style/index.less
Labels: PR: unreviewed

#28447 chore(🆙): upgrade devDeps
  package.json
Labels: PR: unreviewed

#28455 fix: fix warning of transformFile prop for upload
  components/upload/Upload.tsx
Labels: PR: unreviewed

#28456 fix: TextArea value get cut if ime mode
  components/input/TextArea.tsx
  components/input/__tests__/textarea.test.js
Labels: PR: unreviewed

#28459 feat: support Steps responsive prop
  components/steps/index.en-US.md
  components/steps/index.tsx
  components/steps/index.zh-CN.md
  components/steps/style/nav.less
Labels: PR: reviewed-approved

#28458 feat: upgraded hr_HR locale
  components/date-picker/locale/hr_HR.tsx
  components/locale/hr_HR.tsx
  components/time-picker/locale/hr_HR.tsx
Labels: PR: reviewed-approved

#28465 fix: Add parentheses to less mixin calls
  components/alert/style/index.less
  components/anchor/style/index.less
  components/auto-complete/style/index.less
  components/avatar/style/index.less
  components/back-top/style/index.less
  components/badge/style/index.less
  components/badge/style/ribbon.less
  components/breadcrumb/style/index.less
  components/breadcrumb/style/rtl.less
  components/button/style/index.less
  components/calendar/style/index.less
  components/card/style/index.less
  components/carousel/style/index.less
  components/cascader/style/index.less
  components/checkbox/style/mixin.less
  components/collapse/style/index.less
  components/date-picker/style/index.less
  components/divider/style/index.less
  components/dropdown/style/index.less
  components/form/style/index.less
  components/image/style/index.less
  components/input-number/style/index.less
  components/input/style/index.less
  components/input/style/mixin.less
  components/list/style/index.less
  components/mentions/style/index.less
  components/menu/style/index.less
  components/message/style/index.less
  components/modal/style/modal.less
  components/notification/style/index.less
  components/page-header/style/index.less
  components/pagination/style/index.less
  components/popover/style/index.less
  components/progress/style/index.less
  components/radio/style/index.less
  components/rate/style/index.less
  components/select/style/index.less
  components/slider/style/index.less
  components/spin/style/index.less
  components/statistic/style/index.less
  components/steps/style/index.less
  components/switch/style/index.less
  components/table/style/index.less
  components/tabs/style/dropdown.less
  components/tabs/style/index.less
  components/tag/style/index.less
  components/timeline/style/index.less
  components/tooltip/style/index.less
  components/transfer/style/index.less
  components/tree/style/mixin.less
  components/upload/style/index.less
Labels: PR: unreviewed

#28469 fix: typo in example code
  components/dropdown/demo/event.md
Labels: PR: unreviewed

#28475 docs: Fix drag sorter handler
  components/table/demo/drag-sorting-handler.md
Labels: PR: unreviewed

#28507 fix: Collapse header style
  components/collapse/style/index.less
Labels: PR: reviewed-approved

#28499 Fix Typo steps-desciption-max-width to steps-description-max-width
  components/steps/style/index.less
  components/steps/style/progress-dot.less
  components/steps/style/rtl.less
  components/style/themes/default.less
Labels: PR: unreviewed

#28517 ci: add issue reply
  .github/workflows/issue-reply.yml
Labels: PR: unreviewed

#28486 feat: bumped version of `rc-image` 4.2.0 -> 4.4.0
  package.json
Labels: PR: reviewed-approved

#28529 chore: inactive day change to 3
  .github/workflows/issue-reply.yml
Labels: PR: unreviewed

#28520 feat: Select support responsive `maxTagCount`
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/select/__tests__/__snapshots__/demo.test.js.snap
  components/select/demo/big-data.md
  components/select/demo/responsive.md
  components/select/index.en-US.md
  components/select/index.zh-CN.md
  components/select/style/multiple.less
  components/select/style/rtl.less
  components/tree-select/__tests__/__snapshots__/demo.test.js.snap
  components/tree-select/__tests__/__snapshots__/index.test.js.snap
  components/tree-select/index.en-US.md
  components/tree-select/index.zh-CN.md
  package.json
Labels: PR: unreviewed

#28466 chore(🆙): upgrade less to 4.0.0
  components/badge/style/index.less
  components/button/style/mixin.less
  components/calendar/style/index.less
  components/collapse/style/index.less
  components/date-picker/style/index.less
  components/date-picker/style/panel.less
  components/date-picker/style/rtl.less
  components/drawer/style/drawer.less
  components/dropdown/style/index.less
  components/layout/style/index.less
  components/popover/style/index.less
  components/progress/style/index.less
  components/radio/style/index.less
  components/select/style/index.less
  components/select/style/multiple.less
  components/select/style/rtl.less
  components/spin/style/index.less
  components/steps/style/index.less
  components/steps/style/label-placement.less
  components/steps/style/progress-dot.less
  components/steps/style/rtl.less
  components/steps/style/small.less
  components/style/themes/compact.less
  components/style/themes/default.less
  components/switch/style/index.less
  components/table/style/index.less
  components/table/style/size.less
  components/transfer/style/index.less
  components/tree/style/mixin.less
  components/tree/style/rtl.less
  components/upload/style/index.less
  package.json
Labels: PR: reviewed-approved

#28519 ci: add issue more
  .github/workflows/issue-check-inactive.yml
  .github/workflows/issue-close-require.yml
  .github/workflows/issue-open-check.yml
  .github/workflows/issue-remove-inactive.yml
  .github/workflows/issue-reply.yml
Labels: PR: unreviewed

#28553 ci: fix action helper
  .github/workflows/issue-close-require.yml
  .github/workflows/issue-open-check.yml
  .github/workflows/issue-reply.yml
Labels: PR: unreviewed

#28554 ci: update merge token
  .github/workflows/label-merge.yml
Labels: PR: unreviewed

#28545 fix: typography focus
  components/typography/Editable.tsx
  components/typography/__tests__/index.test.js
Labels: PR: unreviewed

#28527 fix: draggable Modal should have boundary
  components/modal/demo/modal-render.md
Labels: PR: unreviewed

#28568 fix: Table childColumnName should support checkStrictly
  components/table/__tests__/Table.rowSelection.test.js
  components/table/hooks/useSelection.tsx
  package.json
Labels: PR: unreviewed

#28551 add prettier plugin for formatting jsdoc
  components/_util/__tests__/getScrollNode.test.ts
  components/_util/transButton.tsx
  components/_util/type.ts
  components/affix/index.tsx
  components/alert/index.tsx
  components/auto-complete/index.tsx
  components/avatar/avatar.tsx
  components/badge/index.tsx
  components/breadcrumb/BreadcrumbItem.tsx
  components/button/button.tsx
  components/cascader/index.tsx
  components/comment/index.tsx
  components/date-picker/locale/ru_RU.tsx
  components/drawer/index.tsx
  components/empty/index.tsx
  components/form/ErrorList.tsx
  components/form/FormItemInput.tsx
  components/form/context.tsx
  components/form/hooks/useCacheErrors.ts
  components/form/index.zh-CN.md
  components/input/ClearableLabeledInput.tsx
  components/input/__tests__/textarea.test.js
  components/modal/confirm.tsx
  components/progress/Line.tsx
  components/result/index.tsx
  components/table/Column.tsx
  components/table/ColumnGroup.tsx
  components/table/Table.tsx
  components/table/__tests__/Table.pagination.test.js
  components/tag/CheckableTag.tsx
  components/time-picker/locale/ru_RU.tsx
  components/timeline/TimelineItem.tsx
  components/transfer/list.tsx
  components/tree/Tree.tsx
  package.json
  scripts/dark-vars.js
  scripts/default-vars.js
  scripts/generateLegacyLocale.js
  site/theme/template/AppShell.jsx
  tests/shared/demoTest.ts
Labels: PR: unreviewed

#28567 ci: merge auto-close into issue-reply
  .github/workflows/auto-close.yml
  .github/workflows/issue-reply.yml
Labels: PR: unreviewed

#28571 chore: merge master into feature
  .github/workflows/auto-close.yml
  .github/workflows/issue-reply.yml
  components/_util/__tests__/getScrollNode.test.ts
  components/_util/transButton.tsx
  components/_util/type.ts
  components/affix/index.tsx
  components/alert/index.tsx
  components/auto-complete/index.tsx
  components/avatar/avatar.tsx
  components/badge/index.tsx
  components/breadcrumb/BreadcrumbItem.tsx
  components/button/button.tsx
  components/cascader/index.tsx
  components/comment/index.tsx
  components/date-picker/locale/ru_RU.tsx
  components/drawer/index.tsx
  components/empty/index.tsx
  components/form/ErrorList.tsx
  components/form/FormItemInput.tsx
  components/form/context.tsx
  components/form/hooks/useCacheErrors.ts
  components/input/ClearableLabeledInput.tsx
  components/input/__tests__/textarea.test.js
  components/modal/confirm.tsx
  components/modal/demo/modal-render.md
  components/progress/Line.tsx
  components/result/index.tsx
  components/table/Column.tsx
  components/table/ColumnGroup.tsx
  components/table/Table.tsx
  components/table/__tests__/Table.pagination.test.js
  components/table/__tests__/Table.rowSelection.test.js
  components/table/hooks/useSelection.tsx
  components/tag/CheckableTag.tsx
  components/time-picker/locale/ru_RU.tsx
  components/timeline/TimelineItem.tsx
  components/transfer/list.tsx
  components/tree/Tree.tsx
  docs/spec/colors.en-US.md
  docs/spec/colors.zh-CN.md
  package.json
  scripts/dark-vars.js
  scripts/default-vars.js
  scripts/generateLegacyLocale.js
  site/theme/template/AppShell.jsx
  tests/shared/demoTest.ts
Labels: BranchAutoMerge, PR: unreviewed

#28570 ci: add needs more info deal
  .github/workflows/issue-close-require.yml
  .github/workflows/issue-remove-inactive.yml
Labels: PR: unreviewed

#28574 fix: Click TreeSelect placeholder close the dropdown
  components/select/style/index.less
Labels: PR: unreviewed

#28440 fix: add the missing import for the checkbox component
  components/checkbox/index.tsx
Labels: PR: unreviewed

#28576 fix: Table selection behavior when inside Checkbox.Group
  components/checkbox/Checkbox.tsx
  components/checkbox/__tests__/group.test.js
  components/table/hooks/useSelection.tsx
Labels: PR: unreviewed

#28578 style: Dropdown Menu.Item disabled link
  components/dropdown/style/index.less
Labels: PR: unreviewed

#28579 docs: update Tree method scrollTo params
  components/tree/index.en-US.md
  components/tree/index.zh-CN.md
Labels: PR: unreviewed

#28580 feat: add select none functionality
  components/locale/default.tsx
  components/locale/zh_CN.tsx
  components/locale/zh_HK.tsx
  components/locale/zh_TW.tsx
  components/table/Table.tsx
  components/table/__tests__/Table.rowSelection.test.js
  components/table/__tests__/__snapshots__/Table.rowSelection.test.js.snap
  components/table/demo/row-selection-custom.md
  components/table/hooks/useSelection.tsx
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/table/interface.tsx
Labels: PR: reviewed-approved

#28583 chore: upgrade @ant-design/tools
  .eslintrc.js
  package.json
Labels: PR: unreviewed

#28530 fix: percent={(3 / 9) * 100} steps={9} shows 2
  components/progress/Steps.tsx
  components/progress/__tests__/__snapshots__/demo.test.js.snap
  components/progress/__tests__/index.test.js
Labels: PR: unreviewed

#28585 chore: merge master into feature
  .eslintrc.js
  .github/workflows/issue-close-require.yml
  .github/workflows/issue-remove-inactive.yml
  components/checkbox/Checkbox.tsx
  components/checkbox/__tests__/group.test.js
  components/checkbox/index.tsx
  components/dropdown/style/index.less
  components/progress/Steps.tsx
  components/progress/__tests__/__snapshots__/demo.test.js.snap
  components/progress/__tests__/index.test.js
  components/select/style/index.less
  components/table/hooks/useSelection.tsx
  components/tree/index.en-US.md
  components/tree/index.zh-CN.md
  package.json
Labels: BranchAutoMerge, PR: partially-approved, PR: unreviewed

#28586 ci: update issues-helper version
  .github/workflows/issue-check-inactive.yml
  .github/workflows/issue-close-require.yml
Labels: PR: unreviewed

#28592 feat(🆕): Slider supports range.draggableTrack
  components/slider/__tests__/__snapshots__/demo.test.js.snap
  components/slider/demo/dragableTrack.md
  components/slider/index.en-US.md
  components/slider/index.tsx
  components/slider/index.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#28594 fix: Tooltip arrow style
  components/tooltip/style/index.less
Labels: PR: unreviewed

#28602 feat: Input focus support cursor
  components/input/Input.tsx
  components/input/TextArea.tsx
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/__tests__/focus.test.tsx
  components/input/demo/focus.md
  components/input/index.en-US.md
  components/input/index.zh-CN.md
Labels: PR: unreviewed

#28616 style: fix Radio align issue
  components/radio/style/index.less
Labels: PR: reviewed-approved

#28613 feat: desc support root level label & content style
  components/descriptions/Row.tsx
  components/descriptions/__tests__/__snapshots__/demo.test.js.snap
  components/descriptions/demo/style.md
  components/descriptions/index.en-US.md
  components/descriptions/index.tsx
  components/descriptions/index.zh-CN.md
Labels: PR: reviewed-approved

#28623 docs: fix typo
  components/select/demo/option-label-prop.md
Labels: PR: reviewed-approved

#28626 chore: Feature merge master
  .github/workflows/issue-check-inactive.yml
  .github/workflows/issue-close-require.yml
  components/radio/style/index.less
  components/select/demo/option-label-prop.md
  components/table/demo/resizable-column.md
  components/tooltip/style/index.less
Labels: BranchAutoMerge, PR: reviewed-approved

#28621 chore: bump rc-picker to 2.5.1
  package.json
Labels: PR: reviewed-approved

#28624 style: optimize card cover style
  components/card/style/index.less
Labels: PR: unreviewed

#28631 fix: Select tag closable less 4 style
  components/select/style/multiple.less
Labels: PR: reviewed-approved
