Repository ant-design/ant-design, pull requests merged in 2020-03, with the labels that each got.

#21751 fix: input group demo
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/demo/group.md
Labels: PR: unreviewed

#20763 feat: expose all Dropdown props of BreadcrumbItem
  components/breadcrumb/BreadcrumbItem.tsx
  components/breadcrumb/index.en-US.md
  components/breadcrumb/index.zh-CN.md
Labels: Inactive, PR: unreviewed

#21655 fix: Date Picker disabled style
  components/date-picker/style/Picker.less
Labels: PR: unreviewed

#21825 fix: Fix table column filtered not work
  components/table/__tests__/Table.filter.test.js
  components/table/hooks/useFilter/FilterDropdown.tsx
  components/table/hooks/useFilter/index.tsx
  components/table/interface.tsx
Labels: PR: reviewed-changes-requested

#21835 feat: Form `validateMessages` support `${label}`
  components/form/FormItem.tsx
  components/form/__tests__/index.test.js
  components/form/demo/nest-messages.md
  package.json
Labels: PR: reviewed-changes-requested

#21836 docs: rewrite drag-drop demo by react-dnd hooks
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/demo/drag-sorting.md
Labels: PR: unreviewed

#21838 docs: clarify duration example description
  components/notification/demo/duration.md
Labels: PR: unreviewed

#21768 style: optimization dropdown menu style
  components/dropdown/demo/overlay-visible.md
  components/dropdown/index.zh-CN.md
  components/dropdown/style/index.less
Labels: PR: unreviewed

#21844 docs: 📝 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/pr_cn.md
Labels: PR: unreviewed

#21847 Revert "feat: add support use dots to provide dotsClasse"
  components/carousel/__tests__/index.test.js
  components/carousel/index.en-US.md
  components/carousel/index.tsx
  components/carousel/index.zh-CN.md
Labels: PR: reviewed-changes-requested

#21849 chore: Merge master to feature
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/pr_cn.md
  components/carousel/__tests__/index.test.js
  components/carousel/index.en-US.md
  components/carousel/index.tsx
  components/carousel/index.zh-CN.md
  components/dropdown/demo/overlay-visible.md
  components/dropdown/index.zh-CN.md
  components/dropdown/style/index.less
  components/form/demo/control-hooks.md
  components/form/v3.en-US.md
  components/form/v3.zh-CN.md
  components/notification/demo/duration.md
  components/table/__tests__/Table.filter.test.js
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/demo/drag-sorting.md
  components/table/hooks/useFilter/FilterDropdown.tsx
  components/table/hooks/useFilter/index.tsx
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/table/interface.tsx
Labels: PR: reviewed-changes-requested

#21846 docs: 4.0.1 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
  scripts/print-changelog.js
Labels: PR: unreviewed

#21848 feat: 🆕 add support use dots to provide dotsClasses
  components/carousel/__tests__/index.test.js
  components/carousel/index.en-US.md
  components/carousel/index.tsx
  components/carousel/index.zh-CN.md
Labels: PR: reviewed-approved

#21855 docs: pracitical use umi 3
  docs/react/practical-projects.en-US.md
  docs/react/practical-projects.zh-CN.md
Labels: PR: unreviewed, needs-more-info

#21863 Revert "chore(deps): bump rc-field-form from 1.0.1 to 1.1.0"
  package.json
Labels: PR: unreviewed

#20652 Fix rtl docs: aside and bottom nav
  site/theme/static/common.less
  site/theme/static/dark.less
  site/theme/static/page-nav.less
  site/theme/static/responsive.less
Labels: Inactive, PR: unreviewed

#21867 fix: 🐛 Fix Menu bottom margin missing
  components/style/mixins/clearfix.less
Labels: PR: unreviewed

#21826 test: ✅ add test case to tooltip
  components/tooltip/__tests__/tooltip.test.js
  components/tooltip/index.tsx
  components/tooltip/placements.tsx
Labels: PR: unreviewed

#21872 docs: add list grid anchor
  components/list/index.en-US.md
  components/list/index.zh-CN.md
Labels: PR: unreviewed

#21875 docs: Auto redirect v3 link
  .eslintignore
  .gitignore
  site/theme/template/NotFound.jsx
  site/theme/template/NotFound.tsx
Labels: PR: unreviewed

#21880 fix: Select with '' string value align issue
  components/select/style/single.less
Labels: PR: unreviewed

#21876 chore: use react internal replace PureRenderMixin
  components/transfer/ListItem.tsx
  components/transfer/__tests__/__snapshots__/index.test.js.snap
  components/transfer/list.tsx
Labels: PR: unreviewed

#21834 fix(module:badge): fix number transition
  components/badge/ScrollNumber.tsx
  components/badge/__tests__/index.test.js
Labels: PR: unreviewed

#21887 fix(module:badge): fix toggling animation for 3.x
  components/badge/ScrollNumber.tsx
  components/badge/__tests__/index.test.js
Labels: PR: reviewed-changes-requested

#21896 fix: Nest FormItem warning
  components/form/FormItem.tsx
Labels: PR: unreviewed

#21895 fix: ref in radio button has not forward
  components/radio/radioButton.tsx
Labels: PR: reviewed-approved

#21901 fix: Desctiption miss style when value is number 0
  components/descriptions/Cell.tsx
  components/descriptions/__tests__/index.test.js
Labels: PR: unreviewed

#21905 fix: Table overflow layout
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/style/index.less
  package.json
Labels: PR: unreviewed

#20227 feat: add outline-fade less variable
  components/input/style/mixin.less
  components/style/themes/default.less
Labels: Inactive, PR: unreviewed

#21911 chore: Form.Item renderProps define
  components/form/FormItem.tsx
Labels: PR: unreviewed

#21912 style: Add less variable @form-item-label-height
  components/form/style/index.less
Labels: PR: unreviewed

#21915 fix: Table expandIconColumnIndex with rowSelect
  components/table/Table.tsx
  components/table/__tests__/Table.expand.test.js
  components/table/__tests__/__snapshots__/Table.expand.test.js.snap
  components/table/hooks/useSelection.tsx
Labels: PR: reviewed-changes-requested

#21925 fix: MenuItem with icon only will still have additional margin
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/form/__tests__/index.test.js
  components/layout/__tests__/__snapshots__/demo.test.js.snap
  components/menu/MenuItem.tsx
  components/menu/__tests__/__snapshots__/demo.test.js.snap
  components/menu/style/index.less
  components/table/__tests__/__snapshots__/Table.rowSelection.test.js.snap
Labels: PR: reviewed-approved

#21927 chore: Form.useForm return same instance now
  components/form/__tests__/index.test.js
  components/form/util.ts
Labels: PR: reviewed-changes-requested

#21930 style: 💄 vertical menu should has max height
  components/menu/style/index.less
Labels: PR: unreviewed

#21931 docs: Update demo ts define
  components/table/demo/edit-row.md
Labels: PR: unreviewed

#21937 style: add datepicker cursor style
  components/date-picker/style/index.less
Labels: PR: unreviewed

#21942 fix: Table small header background color
  components/style/themes/default.less
Labels: PR: unreviewed

#21940 style: fix select content style
  components/select/style/multiple.less
Labels: PR: unreviewed

#21943 docs: remove key props
  components/select/index.en-US.md
  components/select/index.zh-CN.md
Labels: PR: unreviewed

#21946 style: add search input border color in RTL
  components/input/style/search-input.less
Labels: PR: unreviewed, rtl

#21948 feat: TimePicker.RangePicker support `order`
  components/time-picker/index.en-US.md
  components/time-picker/index.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#21955 feat: Tree/TreeSelect/Select support `virtual` prop to disable virtual scroll
  components/list/__tests__/__snapshots__/pagination.test.js.snap
  components/select/index.en-US.md
  components/select/index.zh-CN.md
  components/tree-select/index.en-US.md
  components/tree-select/index.zh-CN.md
  components/tree/index.en-US.md
  components/tree/index.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#21960 fix: fix issue #21954
  components/carousel/style/index.less
Labels: PR: unreviewed

#21953 fix: Input.Password ConfigProvider prefixCls not work
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/config-provider/__tests__/components.test.js
  components/input/Password.tsx
Labels: PR: unreviewed

#21967 docs: ❇️ Release 3.26.13
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#21974 fix: Table className & style in wrong place
  components/empty/__tests__/__snapshots__/demo.test.js.snap
  components/table/Table.tsx
  components/table/__tests__/__snapshots__/demo.test.js.snap
Labels: PR: unreviewed

#21975 docs: Update Tree dynamic update demo
  components/tree/demo/dynamic.md
Labels: PR: unreviewed

#21978 chore: remove unnecessary loop
  components/form/FormItem.tsx
Labels: PR: unreviewed

#21988 docs: add className for Icon
  components/icon/index.en-US.md
  components/icon/index.zh-CN.md
Labels: PR: unreviewed

#21991 refactor: Form.Item with pure children will only render once
  components/form/FormItem.tsx
  components/form/__tests__/index.test.js
Labels: PR: unreviewed

#21980 perf(Form): FormContext use a memoized value(#21976)
  components/form/Form.tsx
Labels: PR: unreviewed

#21993 docs: ❇️ release 4.0.2
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: reviewed-approved, needs-more-info

#22003 style: 💄 Avoid negative padding in less
  components/button/style/mixin.less
  components/select/style/multiple.less
  components/style/themes/default.less
Labels: PR: unreviewed

#22014 fix: 🐛 TextArea[autoSize] don't scroll bottom in Firefox
  components/input/ResizableTextArea.tsx
  components/input/__tests__/textarea.test.js
Labels: PR: reviewed-changes-requested

#22016 chore: 🎬 Improve Input demo and test case
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/__tests__/textarea.test.js
  components/input/demo/align.md
  components/input/demo/group.md
Labels: PR: reviewed-changes-requested

#22021 fix: Only menu icon
  components/menu/style/index.less
Labels: PR: unreviewed

#22024 docs: 📝 documentation for DatePicker inputReadOnly
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
Labels: PR: unreviewed

#22029 docs: 📝 correct inline to noStyle
  components/form/v3.en-US.md
  components/form/v3.zh-CN.md
Labels: PR: unreviewed

#22030 style: 💄 fix PageHeader overflow hidden and responsive style
  components/page-header/__tests__/__snapshots__/demo.test.js.snap
  components/page-header/demo/content.md
  components/page-header/style/index.less
Labels: PR: unreviewed

#22025 chore: 🔨 merge master into feature
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/breadcrumb/index.en-US.md
  components/breadcrumb/index.zh-CN.md
  components/button/style/mixin.less
  components/carousel/index.en-US.md
  components/carousel/style/index.less
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/config-provider/__tests__/components.test.js
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
  components/empty/__tests__/__snapshots__/demo.test.js.snap
  components/form/Form.tsx
  components/form/FormItem.tsx
  components/form/__tests__/index.test.js
  components/icon/index.en-US.md
  components/icon/index.zh-CN.md
  components/input/Password.tsx
  components/input/ResizableTextArea.tsx
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/__tests__/textarea.test.js
  components/input/demo/align.md
  components/input/demo/group.md
  components/menu/style/index.less
  components/select/style/multiple.less
  components/style/themes/default.less
  components/table/Table.tsx
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/tree/demo/dynamic.md
  package.json
Labels: PR: reviewed-changes-requested

#22033 fix: 🐛 Fix Select ellipsis bug in Firefox
  components/select/style/index.less
Labels: PR: unreviewed

#22038 fix: Avatar in Menu
  components/avatar/style/index.less
Labels: PR: unreviewed

#22053 fix: fix FormItem hooks render error
  components/form/FormItem.tsx
Labels: PR: unreviewed

#22034 feat: Support render props for <Popover/> and <Popconfirm/>
  components/_util/getRenderPropValue.ts
  components/popconfirm/__tests__/__snapshots__/index.test.js.snap
  components/popconfirm/__tests__/index.test.js
  components/popconfirm/index.en-US.md
  components/popconfirm/index.tsx
  components/popconfirm/index.zh-CN.md
  components/popover/__tests__/__snapshots__/index.test.js.snap
  components/popover/__tests__/index.test.js
  components/popover/index.en-US.md
  components/popover/index.tsx
  components/popover/index.zh-CN.md
Labels: PR: reviewed-approved

#22055 chore: 🆙 upgrade rc-visual-list
  package.json
Labels: PR: reviewed-approved

#22058 fix: fix FormList Operation type definitions
  components/form/FormList.tsx
Labels: PR: unreviewed

#22061 docs: Update demo preview link
  components/select/__tests__/__snapshots__/demo.test.js.snap
  components/select/demo/big-data.md
Labels: PR: unreviewed

#22066 style: fix radio button in rtl
  components/radio/style/index.less
Labels: PR: reviewed-approved

#21914 fix: FixedColumns issue in rtl
  components/table/Table.tsx
  components/table/style/index.less
  package.json
Labels: PR: unreviewed

#21959 feat: pagination could change its size by the width of the window
  components/pagination/Pagination.tsx
  components/pagination/__tests__/index.test.js
  components/pagination/index.en-US.md
  components/pagination/index.zh-CN.md
Labels: PR: unreviewed

#22079 fix: Table filter menu reset not working
  components/table/hooks/useFilter/FilterDropdown.tsx
Labels: PR: unreviewed

#21907 fix: basic form style abnormal
  components/form/style/horizontal.less
  components/form/style/index.less
  components/form/style/vertical.less
  components/grid/style/index.less
Labels: PR: unreviewed

#22072 style: 💄 New table filter menu buttons
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/dropdown/style/index.less
  components/table/__tests__/Table.filter.test.js
  components/table/__tests__/Table.rowSelection.test.js
  components/table/__tests__/__snapshots__/Table.filter.test.js.snap
  components/table/hooks/useFilter/FilterDropdown.tsx
  components/table/style/index.less
  components/table/style/index.tsx
Labels: PR: reviewed-approved

#22087 fix: Should also fix expand col when selection fixed
  components/table/__tests__/Table.rowSelection.test.js
  components/table/__tests__/__snapshots__/Table.rowSelection.test.js.snap
  components/table/hooks/useSelection.tsx
Labels: PR: reviewed-changes-requested

#22090 style: changed display of anticon
  components/menu/style/index.less
Labels: PR: unreviewed

#22092 feat: ellipsis onExpand function takes event parameter
  components/typography/Base.tsx
  components/typography/index.en-US.md
Labels: PR: reviewed-approved

#22096 fix: Don't non-null assertion
  components/table/hooks/useFilter/FilterDropdown.tsx
Labels: PR: unreviewed

#22098 style: fix dropdown menu icon
  components/dropdown/style/index.less
Labels: PR: unreviewed

#22101 fix: 🐛 Fix Select ellipsis bug of Firefox in another way
  components/select/style/single.less
Labels: PR: unreviewed

#22100 docs: Update Demo icon
  components/menu/__tests__/__snapshots__/demo.test.js.snap
  components/menu/demo/inline-collapsed.md
Labels: PR: unreviewed

#22104 style: optimize dropdown RTL icon
  components/dropdown/style/index.less
Labels: PR: unreviewed

#22103 feat: Refine locale types
  components/locale-provider/index.tsx
  components/locale/ar_EG.tsx
  components/locale/az_AZ.tsx
  components/locale/bg_BG.tsx
  components/locale/ca_ES.tsx
  components/locale/cs_CZ.tsx
  components/locale/da_DK.tsx
  components/locale/de_DE.tsx
  components/locale/default.tsx
  components/locale/el_GR.tsx
  components/locale/en_GB.tsx
  components/locale/es_ES.tsx
  components/locale/et_EE.tsx
  components/locale/fa_IR.tsx
  components/locale/fi_FI.tsx
  components/locale/fr_BE.tsx
  components/locale/fr_FR.tsx
  components/locale/he_IL.tsx
  components/locale/hi_IN.tsx
  components/locale/hr_HR.tsx
  components/locale/hu_HU.tsx
  components/locale/hy_AM.tsx
  components/locale/id_ID.tsx
  components/locale/is_IS.tsx
  components/locale/it_IT.tsx
  components/locale/ja_JP.tsx
  components/locale/kn_IN.tsx
  components/locale/ko_KR.tsx
  components/locale/ku_IQ.tsx
  components/locale/lv_LV.tsx
  components/locale/mk_MK.tsx
  components/locale/mn_MN.tsx
  components/locale/ms_MY.tsx
  components/locale/nb_NO.tsx
  components/locale/ne_NP.tsx
  components/locale/nl_BE.tsx
  components/locale/nl_NL.tsx
  components/locale/pl_PL.tsx
  components/locale/pt_BR.tsx
  components/locale/pt_PT.tsx
  components/locale/ro_RO.tsx
  components/locale/ru_RU.tsx
  components/locale/sk_SK.tsx
  components/locale/sl_SI.tsx
  components/locale/sr_RS.tsx
  components/locale/sv_SE.tsx
  components/locale/ta_IN.tsx
  components/locale/th_TH.tsx
  components/locale/tr_TR.tsx
  components/locale/uk_UA.tsx
  components/locale/vi_VN.tsx
  components/locale/zh_CN.tsx
  components/locale/zh_TW.tsx
  components/modal/locale.tsx
Labels: PR: reviewed-approved

#22086 docs: translating
  docs/spec/dark.en-US.md
  docs/spec/dark.zh-CN.md
Labels: PR: unreviewed

#21174 docs: documentation about browser keyboards and restrictions
  components/input-number/index.en-US.md
Labels: Inactive, PR: unreviewed

#22115 docs: fix ColorPicker covered by page-nav
  site/theme/static/common.less
Labels: PR: unreviewed

#22122 fix: fr_FR locale in date_picker
  components/date-picker/locale/fr_FR.tsx
Labels: PR: unreviewed

#22111 chore: 🔀 merge master into feature
  README.md
  components/avatar/style/index.less
  components/dropdown/style/index.less
  components/form/FormItem.tsx
  components/form/FormList.tsx
  components/form/style/horizontal.less
  components/form/style/index.less
  components/form/style/vertical.less
  components/form/v3.en-US.md
  components/form/v3.zh-CN.md
  components/grid/style/index.less
  components/menu/__tests__/__snapshots__/demo.test.js.snap
  components/menu/demo/inline-collapsed.md
  components/menu/style/index.less
  components/page-header/__tests__/__snapshots__/demo.test.js.snap
  components/page-header/demo/content.md
  components/page-header/style/index.less
  components/radio/style/index.less
  components/select/__tests__/__snapshots__/demo.test.js.snap
  components/select/demo/big-data.md
  components/select/style/index.less
  components/select/style/single.less
  components/table/Table.tsx
  components/table/__tests__/Table.rowSelection.test.js
  components/table/__tests__/__snapshots__/Table.rowSelection.test.js.snap
  components/table/hooks/useFilter/FilterDropdown.tsx
  components/table/hooks/useSelection.tsx
  components/table/style/index.less
  docs/spec/dark.en-US.md
  docs/spec/dark.zh-CN.md
  package.json
Labels: PR: reviewed-changes-requested

#22043 fix: fix tooltip trigger type
  components/rate/index.tsx
  components/tooltip/index.en-US.md
  components/tooltip/index.tsx
  components/tooltip/index.zh-CN.md
  package.json
Labels: PR: unreviewed

#22182 fix: Menu inlineCollpsed item title
  components/menu/style/index.less
Labels: PR: unreviewed

#22179 chore: 🔀 merge master into feature
  components/breadcrumb/style/index.less
  components/calendar/style/index.less
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/date-picker/locale/fr_FR.tsx
  components/input-number/index.en-US.md
  components/pagination/style/index.less
  components/rate/index.tsx
  components/select/style/single.less
  components/slider/style/index.less
  components/steps/demo/step-next.md
  components/steps/style/index.less
  components/steps/style/label-placement.less
  components/steps/style/small.less
  components/style/themes/default.less
  components/table/Table.tsx
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/demo/resizable-column.md
  components/table/hooks/useFilter/index.tsx
  components/table/style/index.less
  components/tooltip/index.en-US.md
  components/tooltip/index.tsx
  components/tooltip/index.zh-CN.md
  package.json
  site/theme/static/common.less
Labels: PR: reviewed-approved

#22135 fix: fix vertical handle position
  components/slider/index.tsx
  components/slider/style/index.less
  package.json
Labels: PR: unreviewed

#22187 Update index.zh-CN.md
  components/table/index.zh-CN.md
Labels: PR: unreviewed

#22188 Update index.en-US.md
  components/table/index.en-US.md
Labels: PR: unreviewed

#22186 style: add checkout grop RTL
  components/checkbox/Group.tsx
  components/checkbox/__tests__/__snapshots__/demo.test.js.snap
  components/checkbox/__tests__/__snapshots__/group.test.js.snap
  components/checkbox/demo/controller.md
  components/checkbox/style/index.less
  components/checkbox/style/rtl.less
Labels: PR: reviewed-approved

#22191 style: fix cascader RTL small icon
  components/cascader/style/index.less
  components/cascader/style/index.tsx
  components/cascader/style/rtl.less
Labels: PR: unreviewed

#22199 Update resources.zh-CN.md
  docs/resources.zh-CN.md
Labels: PR: unreviewed

#22200 Update resources.en-US.md
  docs/resources.en-US.md
Labels: PR: unreviewed

#22202 feat: Menu.Item Tooltip could be hidden by title prop
  components/menu/MenuItem.tsx
  components/menu/__tests__/index.test.js
Labels: PR: reviewed-approved

#22197 fix: inputgroup search icon
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/demo/group.md
  components/input/style/mixin.less
Labels: PR: unreviewed

#22207 feat: Card support tabProps
  components/card/__tests__/index.test.js
  components/card/index.en-US.md
  components/card/index.tsx
  components/card/index.zh-CN.md
Labels: PR: reviewed-approved

#22211 docs: Update research-form.zh-CN.md
  docs/spec/research-form.zh-CN.md
Labels: PR: reviewed-approved

#22214 style: fix form item rtl style
  components/form/style/index.less
Labels: PR: unreviewed

#22222 style: fix form item with feedback in rtl
  components/form/style/index.less
  components/form/style/status.less
Labels: PR: unreviewed

#22229 fix: revert Radio no wrapping style
  components/radio/style/index.less
Labels: PR: unreviewed

#22230 fix: Table filter sub menu max height with many items
  components/dropdown/style/index.less
  components/table/style/index.less
Labels: PR: unreviewed

#22226 feat: useBreakpoint hook
  components/__tests__/__snapshots__/index.test.js.snap
  components/grid/__tests__/__snapshots__/demo.test.js.snap
  components/grid/__tests__/index.test.js
  components/grid/demo/useBreakpoint.md
  components/grid/hooks/useBreakpoint.tsx
  components/grid/index.tsx
  components/index.tsx
  tests/__snapshots__/index.test.js.snap
Labels: PR: unreviewed

#22231 fix: style of card mode of Calendar
  components/calendar/style/index.tsx
Labels: PR: unreviewed

#22234 docs: Dark theme in create-react-app
  docs/react/customize-theme.en-US.md
  docs/react/customize-theme.zh-CN.md
  docs/react/use-with-create-react-app.en-US.md
  docs/react/use-with-create-react-app.zh-CN.md
Labels: PR: unreviewed

#22217 docs: 📝 add 4.0.3 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: reviewed-approved

#22238 fix: remove acute accents in datepicker FR locale
  components/date-picker/locale/fr_FR.tsx
Labels: PR: reviewed-approved

#22236 fix: timeline pendingDot default value in docs
  components/timeline/index.en-US.md
  components/timeline/index.zh-CN.md
Labels: PR: reviewed-approved

#22242 docs: Add Tree faq
  components/tree/index.en-US.md
  components/tree/index.zh-CN.md
Labels: PR: unreviewed

#22243 Revert "chore: pause deploy site"
  .github/workflows/deploy-site.yml
Labels: PR: unreviewed

#22245 refactor: Adjust Radio.Group logic that value is undefined should be uncontrolled mode.
  components/radio/__tests__/group.test.js
  components/radio/group.tsx
  components/radio/interface.tsx
Labels: PR: reviewed-changes-requested

#22248 fix: 🐛 Menu unexpected scrollbar
  components/menu/style/index.less
Labels: PR: unreviewed

#22247 docs: Add dynamic multiple fields demo
  components/form/demo/dynamic-form-item.md
Labels: PR: unreviewed

#22251 style: 💄 fix Select dropdown menu vertical padding
  components/select/style/index.less
Labels: PR: unreviewed

#22252 style: add rtl.less of button\typography\grid
  components/button/style/index.less
  components/button/style/mixin.less
  components/button/style/mixin.rtl.less
  components/button/style/rtl.less
  components/grid/style/index.less
  components/grid/style/mixin.less
  components/grid/style/mixin.rtl.less
  components/grid/style/rtl.less
  components/typography/style/index.less
  components/typography/style/rtl.less
Labels: PR: unreviewed

#22255 chore: 🔀 merge master into feature
  .github/workflows/deploy-site.yml
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/button/style/index.less
  components/button/style/mixin.less
  components/button/style/mixin.rtl.less
  components/button/style/rtl.less
  components/calendar/style/index.tsx
  components/cascader/style/index.less
  components/cascader/style/index.tsx
  components/cascader/style/rtl.less
  components/checkbox/Group.tsx
  components/checkbox/__tests__/__snapshots__/demo.test.js.snap
  components/checkbox/__tests__/__snapshots__/group.test.js.snap
  components/checkbox/demo/controller.md
  components/checkbox/style/index.less
  components/checkbox/style/rtl.less
  components/date-picker/locale/fr_FR.tsx
  components/dropdown/style/index.less
  components/form/demo/dynamic-form-item.md
  components/form/style/index.less
  components/form/style/status.less
  components/grid/style/index.less
  components/grid/style/mixin.less
  components/grid/style/mixin.rtl.less
  components/grid/style/rtl.less
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/demo/group.md
  components/input/style/mixin.less
  components/menu/style/index.less
  components/radio/__tests__/group.test.js
  components/radio/group.tsx
  components/radio/interface.tsx
  components/radio/style/index.less
  components/select/__tests__/__snapshots__/demo.test.js.snap
  components/select/demo/basic.md
  components/select/demo/big-data.md
  components/select/demo/coordinate.md
  components/select/demo/size.md
  components/select/demo/suffix.md
  components/select/style/index.less
  components/slider/index.tsx
  components/slider/style/index.less
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/table/style/index.less
  components/timeline/index.en-US.md
  components/timeline/index.zh-CN.md
  components/tree/index.en-US.md
  components/tree/index.zh-CN.md
  components/typography/style/index.less
  components/typography/style/rtl.less
  docs/react/customize-theme.en-US.md
  docs/react/customize-theme.zh-CN.md
  docs/react/use-with-create-react-app.en-US.md
  docs/react/use-with-create-react-app.zh-CN.md
  docs/resources.en-US.md
  docs/resources.zh-CN.md
  docs/spec/research-form.zh-CN.md
  package.json
Labels: PR: reviewed-changes-requested

#22260 style: fix button rtl.less
  components/button/style/mixin.rtl.less
Labels: PR: unreviewed

#22258 style: add rtl.less of breadcrumb\dropdown
  components/breadcrumb/style/index.less
  components/breadcrumb/style/rtl.less
  components/dropdown/style/index.less
  components/dropdown/style/rtl.less
Labels: PR: reviewed-approved

#22271 style: add rtl.less of Menu\Pagination\PageHeader
  components/menu/style/index.less
  components/menu/style/rtl.less
  components/page-header/style/index.less
  components/page-header/style/rtl.less
  components/pagination/style/index.less
  components/pagination/style/rtl.less
Labels: PR: unreviewed

#22270 improvement: Update german translation
  components/locale/de_DE.tsx
Labels: PR: unreviewed

#22284 fix: Typography list style
  components/typography/__tests__/__snapshots__/demo.test.js.snap
  components/typography/demo/paragraph-debug.md
  components/typography/style/index.less
Labels: PR: unreviewed

#22287 feat: 🆕 Add keyboard prop to Tabs
  components/card/__tests__/__snapshots__/demo.test.js.snap
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/list/__tests__/__snapshots__/pagination.test.js.snap
  components/page-header/__tests__/__snapshots__/demo.test.js.snap
  components/tabs/__tests__/__snapshots__/demo.test.js.snap
  components/tabs/__tests__/__snapshots__/index.test.js.snap
  components/tabs/index.en-US.md
  components/tabs/index.tsx
  components/tabs/index.zh-CN.md
  components/tabs/style/index.less
  package.json
Labels: PR: reviewed-approved

#22294 style: add rtl.less of Rate\Switch\Slider
  components/rate/style/index.less
  components/rate/style/rtl.less
  components/slider/style/index.less
  components/slider/style/rtl.less
  components/switch/style/index.less
  components/switch/style/rtl.less
Labels: PR: unreviewed

#22290 style: add rtl.less of Steps
  components/steps/style/custom-icon.less
  components/steps/style/custom-icon.rtl.less
  components/steps/style/index.less
  components/steps/style/nav.less
  components/steps/style/nav.rtl.less
  components/steps/style/rtl.less
  components/steps/style/small.less
  components/steps/style/small.rtl.less
  components/steps/style/vertical.less
  components/steps/style/vertical.rtl.less
Labels: PR: unreviewed

#22299 chore: update recommend page
  site/theme/template/Home/RecommendPage.tsx
Labels: PR: unreviewed

#22301 chore: Feature merge master
  components/breadcrumb/style/index.less
  components/breadcrumb/style/rtl.less
  components/button/style/mixin.rtl.less
  components/dropdown/style/index.less
  components/dropdown/style/rtl.less
  components/locale/de_DE.tsx
  components/menu/style/index.less
  components/menu/style/rtl.less
  components/page-header/style/index.less
  components/page-header/style/rtl.less
  components/pagination/style/index.less
  components/pagination/style/rtl.less
  components/rate/style/index.less
  components/rate/style/rtl.less
  components/slider/style/index.less
  components/slider/style/rtl.less
  components/steps/style/custom-icon.less
  components/steps/style/custom-icon.rtl.less
  components/steps/style/index.less
  components/steps/style/nav.less
  components/steps/style/nav.rtl.less
  components/steps/style/rtl.less
  components/steps/style/small.less
  components/steps/style/small.rtl.less
  components/steps/style/vertical.less
  components/steps/style/vertical.rtl.less
  components/switch/style/index.less
  components/switch/style/rtl.less
  components/typography/__tests__/__snapshots__/demo.test.js.snap
  components/typography/demo/paragraph-debug.md
  components/typography/style/index.less
  site/theme/template/Home/RecommendPage.tsx
Labels: PR: reviewed-approved

#22303 chore: Adjust Tag processing color
  components/badge/demo/colorful.md
  components/tag/style/index.less
Labels: PR: reviewed-approved

#22307 style: add rtl.less of Select\Transfer\Upload
  components/select/style/index.less
  components/select/style/multiple.less
  components/select/style/multiple.rtl.less
  components/select/style/rtl.less
  components/select/style/single.less
  components/select/style/single.rtl.less
  components/transfer/style/index.less
  components/transfer/style/rtl.less
  components/upload/style/index.less
  components/upload/style/rtl.less
Labels: PR: unreviewed

#22310 style: AutoComplete clear icon overclap on Search icon
  components/auto-complete/style/index.less
Labels: PR: unreviewed

#16142 feat: Inherit menu line-height from header
  components/layout/__tests__/__snapshots__/demo.test.js.snap
  components/layout/demo/fixed.md
  components/layout/demo/top-side-2.md
  components/layout/demo/top-side.md
  components/layout/demo/top.md
  components/menu/style/index.less
Labels: Inactive, PR: unreviewed

#22315 chore: 🔧 fix codesandbox React.Fragment support
  site/theme/static/markdown.less
  site/theme/template/Color/ColorBlock.jsx
  site/theme/template/Color/ColorPalettes.jsx
  site/theme/template/Content/Demo/index.jsx
  site/theme/template/Home/RecommendPage.tsx
Labels: PR: unreviewed

#22317 fix: Table onFilter only should work
  components/table/__tests__/Table.filter.test.js
  components/table/hooks/useFilter/index.tsx
Labels: PR: unreviewed

#22318 refactor: tree dir
  components/tree/DirectoryTree.tsx
Labels: PR: unreviewed

#22316 docs: improve transiton between light & dark mode
  site/theme/static/common.less
Labels: 4.x, PR: reviewed-approved, PR: unreviewed

#22304 docs: 📝 fix array type field of Form.Item name
  components/form/v3.en-US.md
  components/form/v3.zh-CN.md
Labels: PR: unreviewed

#22330 style: add rtl.less of Carousel\Descriptions\Empty
  components/carousel/style/index.less
  components/carousel/style/rtl.less
  components/descriptions/style/index.less
  components/descriptions/style/rtl.less
  components/empty/style/index.less
  components/empty/style/rtl.less
Labels: PR: unreviewed

#22277 fix: Table column filter value type could be any
  components/table/hooks/useFilter/FilterDropdown.tsx
  components/table/hooks/useFilter/index.tsx
  components/table/interface.tsx
Labels: PR: unreviewed

#22320 style: add rtl.less of Badge\Comment\Collapse
  components/badge/style/index.less
  components/badge/style/rtl.less
  components/collapse/style/index.less
  components/collapse/style/rtl.less
  components/comment/style/index.less
  components/comment/style/rtl.less
Labels: PR: unreviewed

#22334 fix: Table row expand icon show error in ipad
  components/table/style/index.less
Labels: PR: unreviewed

#22335 style: add rtl.less of Tree\Tooltip\Timeline
  components/timeline/style/index.less
  components/timeline/style/rtl.less
  components/tooltip/style/index.less
  components/tooltip/style/rtl.less
  components/tree/style/index.less
  components/tree/style/rtl.less
Labels: PR: unreviewed

#22339 style: add rtl.less of Tag\Tabs\Alert
  components/alert/style/index.less
  components/alert/style/rtl.less
  components/tabs/style/card-style.less
  components/tabs/style/card-style.rtl.less
  components/tabs/style/index.less
  components/tabs/style/rtl.less
  components/tag/style/index.less
  components/tag/style/rtl.less
Labels: PR: unreviewed

#22354 style: add rtl.less of Drawer\Modal\Progress\Result
  components/drawer/style/drawer.less
  components/drawer/style/index.tsx
  components/drawer/style/rtl.less
  components/modal/style/index.tsx
  components/modal/style/modal.less
  components/modal/style/rtl.less
  components/progress/style/index.less
  components/progress/style/index.tsx
  components/progress/style/rtl.less
  components/result/style/index.less
  components/result/style/index.tsx
  components/result/style/rtl.less
Labels: PR: unreviewed

#18397 chore: Move openAnimation out of defaultProps
  components/collapse/Collapse.tsx
Labels: Inactive, PR: unreviewed

#22352 style: page-header-demo-content rtl
  components/page-header/demo/content.md
Labels: PR: unreviewed

#22362 test: add test case for collapse
  components/collapse/__tests__/__snapshots__/index.test.js.snap
  components/collapse/__tests__/index.test.js
  components/page-header/__tests__/__snapshots__/demo.test.js.snap
Labels: PR: unreviewed

#22367 fix: Table row height
  components/table/style/index.less
Labels: PR: unreviewed
