Repository ant-design/ant-design, pull requests merged in 2020-11, with the labels that each got.

#27488 chore: merge feature into master
  components/avatar/__tests__/__snapshots__/demo.test.js.snap
  components/avatar/avatar.tsx
  components/avatar/demo/group.md
  components/avatar/demo/type.md
  components/avatar/group.tsx
  components/avatar/index.en-US.md
  components/avatar/index.zh-CN.md
  components/collapse/style/index.less
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/config-provider/__tests__/__snapshots__/form.test.js.snap
  components/config-provider/__tests__/form.test.js
  components/config-provider/context.tsx
  components/config-provider/demo/size.md
  components/config-provider/index.en-US.md
  components/config-provider/index.tsx
  components/config-provider/index.zh-CN.md
  components/form/Form.tsx
  components/grid/RowContext.tsx
  components/grid/__tests__/__snapshots__/demo.test.js.snap
  components/grid/col.tsx
  components/grid/demo/flex-stretch.md
  components/grid/index.en-US.md
  components/grid/index.zh-CN.md
  components/grid/row.tsx
  components/grid/style/index.less
  components/image/index.en-US.md
  components/image/index.zh-CN.md
  components/input/TextArea.tsx
  components/input/__tests__/__snapshots__/textarea.test.js.snap
  components/input/__tests__/textarea.test.js
  components/modal/ConfirmDialog.tsx
  components/modal/Modal.tsx
  components/modal/__tests__/confirm.test.js
  components/modal/confirm.tsx
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
  components/statistic/Statistic.tsx
  components/statistic/__tests__/__snapshots__/demo.test.js.snap
  components/statistic/__tests__/index.test.js
  components/statistic/demo/basic.md
  components/statistic/index.en-US.md
  components/statistic/index.zh-CN.md
  components/statistic/style/index.tsx
  package.json
  site/theme/template/Home/RecommendPage.tsx
Labels: PR: reviewed-approved

#27487 fix: Typography.Link color not disabled
  components/typography/style/index.less
Labels: PR: unreviewed

#27446 chore: update rc-image
  package.json
Labels: PR: reviewed-approved

#27489 chore: bump ⬆️ rc-slider to 9.6.1
  package.json
Labels: PR: partially-approved

#27491 test: use action cache v2
  .github/workflows/test.yml
Labels: PR: reviewed-approved

#27485 fix(pageHeader): if title is null,no render title view
  components/page-header/__tests__/index.test.js
  components/page-header/index.tsx
Labels: PR: reviewed-approved

#27497 chore: update rc-rate
  package.json
Labels: PR: reviewed-approved

#27499 fix: Steps responsive ui
  components/steps/__tests__/__snapshots__/demo.test.js.snap
  components/steps/index.tsx
  components/steps/style/custom-icon.less
  components/steps/style/index.less
  components/steps/style/progress.less
  components/steps/style/vertical.less
Labels: PR: partially-approved

#27490 release: 4.8.0 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#27505 chore: merge master into feature
  .github/workflows/test.yml
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/avatar/index.en-US.md
  components/avatar/index.zh-CN.md
  components/page-header/__tests__/index.test.js
  components/page-header/index.tsx
  components/steps/__tests__/__snapshots__/demo.test.js.snap
  components/steps/index.tsx
  components/steps/style/custom-icon.less
  components/steps/style/index.less
  components/steps/style/progress.less
  components/steps/style/vertical.less
  components/tree/style/mixin.less
  components/tree/style/rtl.less
  components/typography/style/index.less
  package.json
  site/theme/template/Home/RecommendPage.tsx
Labels: PR: reviewed-approved

#27511 style: supplement steps rtl
  components/steps/style/rtl.less
Labels: PR: unreviewed

#27482 fix: select ref typescript typo
  components/auto-complete/index.tsx
  components/select/index.tsx
Labels: PR: unreviewed

#27514 fix: Steps inside Steps style
  components/steps/__tests__/__snapshots__/demo.test.js.snap
  components/steps/demo/steps-in-steps.md
  components/steps/style/index.less
  components/steps/style/rtl.less
  components/steps/style/vertical.less
Labels: PR: unreviewed

#27515 fix: Progress.Line strokeColor direction in rtl
  components/config-provider/context.tsx
  components/config-provider/index.tsx
  components/progress/Line.tsx
  components/progress/progress.tsx
Labels: PR: unreviewed

#27513 docs(popconfirm): add async demo
  components/popconfirm/__tests__/__snapshots__/demo.test.js.snap
  components/popconfirm/demo/async.md
Labels: PR: unreviewed

#27529 chore: update compressed-size-action ci
  .github/workflows/compressed-size.yml
Labels: PR: unreviewed

#27524 fix: update Avatar src type
  components/avatar/avatar.tsx
Labels: PR: unreviewed

#27536 perf(📦): reduce Steps responsive css size
  components/steps/index.tsx
  components/steps/style/index.tsx
  components/steps/style/rtl.less
  components/steps/style/vertical.less
Labels: PR: unreviewed

#27540 refactor: direction type define
  components/cascader/index.tsx
  components/drawer/index.tsx
  components/input/ClearableLabeledInput.tsx
  components/input/Input.tsx
  components/menu/MenuContext.tsx
  components/modal/Modal.tsx
  components/page-header/index.tsx
  components/transfer/index.tsx
  components/transfer/operation.tsx
  components/typography/Editable.tsx
Labels: PR: unreviewed

#27527 perf: reduce css size
  components/anchor/style/rtl.less
  components/avatar/style/group.less
  components/avatar/style/rtl.less
  components/badge/style/index.less
  components/badge/style/rtl.less
  components/breadcrumb/style/rtl.less
  components/rate/style/index.less
  components/rate/style/rtl.less
  components/spin/style/rtl.less
  components/statistic/style/rtl.less
Labels: PR: unreviewed

#27546 docs: 🚹 improve riddle/codesandbox/codepen
  site/theme/template/Content/Demo/index.jsx
Labels: PR: unreviewed

#27560 test: enable argos batch mode
  package.json
Labels: PR: unreviewed

#27559 docs(Modal): async change to hook
  components/modal/demo/async.md
Labels: PR: unreviewed

#27564 docs(steps): step next change to hooks
  components/steps/demo/step-next.md
Labels: PR: unreviewed

#27543 feat: fetch siteData from remote
  site/theme/template/Home/MorePage.tsx
  site/theme/template/Home/RecommendPage.tsx
  site/theme/template/Home/util.tsx
Labels: PR: unreviewed

#27569 fix: vertical Tabs long active title style
  components/tabs/__tests__/__snapshots__/demo.test.js.snap
  components/tabs/demo/position.md
  components/tabs/style/index.less
  components/tabs/style/position.less
Labels: PR: unreviewed

#27531 fix: Avatar group size
  components/avatar/SizeContext.tsx
  components/avatar/avatar.tsx
  components/avatar/group.tsx
Labels: PR: reviewed-approved

#27580 Revert "test: enable argos batch mode"
  package.json
Labels: PR: unreviewed

#27592 docs(select): size demo change hook
  components/select/demo/size.md
Labels: PR: reviewed-approved

#27594 chore: improve select ref type
  components/select/index.tsx
Labels: PR: unreviewed

#27523 feat: upgrade rc-select version and add demo to bring in filterSort f…
  components/select/__tests__/__snapshots__/demo.test.js.snap
  components/select/demo/search-sort.md
  components/select/index.en-US.md
  components/select/index.zh-CN.md
  package.json
Labels: PR: partially-approved

#27595 refactor(layout): rewrite with hook
  components/layout/index.tsx
  components/layout/layout.tsx
Labels: PR: unreviewed

#27591 Prevent Input.Search component to throw passing null as enterButton prop value
  components/input/Search.tsx
  components/input/__tests__/Search.test.js
Labels: PR: unreviewed

#27584 feat: add 'setSelectionRange' for the ref of Input and TextArea
  components/input/Input.tsx
  components/input/TextArea.tsx
  components/input/__tests__/index.test.js
  components/input/__tests__/textarea.test.js
Labels: PR: reviewed-approved

#27600 docs: tree conduction logic
  components/tree/index.en-US.md
  components/tree/index.zh-CN.md
Labels: PR: unreviewed

#27604 docs: Update responsive.md
  components/grid/demo/responsive.md
Labels: PR: unreviewed

#27565 feat: Menu support expandIcon
  components/menu/index.en-US.md
  components/menu/index.tsx
  components/menu/index.zh-CN.md
  components/menu/style/index.less
Labels: PR: unreviewed

#27605 docs: update responsive-more.md
  components/grid/demo/responsive-more.md
Labels: PR: unreviewed

#27608 docs(checkbox): change check all demo to hook
  components/checkbox/__tests__/__snapshots__/demo.test.js.snap
  components/checkbox/demo/check-all.md
Labels: PR: unreviewed

#27610 style: fix Pagination extra margin right
  components/pagination/style/index.less
  components/pagination/style/rtl.less
Labels: PR: unreviewed

#27620 docs: Update nest-messages.md
  components/form/demo/nest-messages.md
Labels: PR: reviewed-approved

#27632 perf: Optimize menu animation
  components/style/core/motion.less
Labels: PR: unreviewed

#27634 docs: format inline code
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/button/demo/block.md
  components/grid/demo/sort.md
  components/menu/index.en-US.md
  components/message/index.zh-CN.md
  components/notification/demo/duration.md
  components/switch/index.zh-CN.md
  components/table/index.zh-CN.md
  components/tooltip/index.zh-CN.md
  components/transfer/index.zh-CN.md
  components/tree/index.zh-CN.md
  docs/react/migration-v4.zh-CN.md
  docs/react/practical-projects.zh-CN.md
  docs/spec/reaction.zh-CN.md
Labels: PR: unreviewed

#27607 fix: Select error outline style in Form
  components/form/style/status.less
  components/select/style/index.less
  components/select/style/multiple.less
  components/select/style/single.less
Labels: PR: unreviewed

#27618 docs(switch): change demo to hook
  components/switch/demo/disabled.md
Labels: PR: unreviewed

#27593 refactor(tree-select): rewrite with hook
  components/tree-select/__tests__/index.test.js
  components/tree-select/index.tsx
Labels: PR: unreviewed

#27630 fix: introduce generic type for transfer item
  components/transfer/ListBody.tsx
  components/transfer/ListItem.tsx
  components/transfer/index.en-US.md
  components/transfer/index.tsx
  components/transfer/index.zh-CN.md
  components/transfer/list.tsx
Labels: PR: unreviewed

#27625 fix: menu expand arrow style
  components/menu/style/index.less
Labels: PR: reviewed-approved

#27638 docs(menu): switch mode demo change to hook
  components/menu/demo/switch-mode.md
Labels: PR: unreviewed

#27640 fix: Menu bg style flickering
  components/menu/style/index.less
Labels: PR: unreviewed

#27643 docs(menu): sider demo change to hook
  components/menu/demo/sider-current.md
Labels: PR: unreviewed

#27646 style: optimize pagination link
  components/pagination/style/index.less
Labels: PR: unreviewed

#27635 docs: ✨ release 4.8.1
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#27644 chore: merge master into feature
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/button/demo/block.md
  components/checkbox/__tests__/__snapshots__/demo.test.js.snap
  components/checkbox/demo/check-all.md
  components/form/demo/nest-messages.md
  components/form/style/status.less
  components/grid/demo/responsive-more.md
  components/grid/demo/responsive.md
  components/grid/demo/sort.md
  components/input/Search.tsx
  components/input/__tests__/Search.test.js
  components/layout/index.tsx
  components/layout/layout.tsx
  components/menu/demo/sider-current.md
  components/menu/demo/switch-mode.md
  components/menu/index.en-US.md
  components/menu/style/index.less
  components/message/index.zh-CN.md
  components/notification/demo/duration.md
  components/pagination/style/index.less
  components/pagination/style/rtl.less
  components/select/style/index.less
  components/select/style/multiple.less
  components/select/style/single.less
  components/style/core/motion.less
  components/switch/demo/disabled.md
  components/switch/index.zh-CN.md
  components/table/index.zh-CN.md
  components/tooltip/index.zh-CN.md
  components/transfer/ListBody.tsx
  components/transfer/ListItem.tsx
  components/transfer/index.en-US.md
  components/transfer/index.tsx
  components/transfer/index.zh-CN.md
  components/transfer/list.tsx
  components/tree-select/__tests__/index.test.js
  components/tree-select/index.tsx
  components/tree/index.en-US.md
  components/tree/index.zh-CN.md
  docs/react/migration-v4.zh-CN.md
  docs/react/practical-projects.zh-CN.md
  docs/spec/reaction.zh-CN.md
  package.json
  site/theme/template/Color/ColorPicker.tsx
Labels: PR: unreviewed

#27650 fix: Pagination jumper margin lost
  components/pagination/style/rtl.less
Labels: PR: unreviewed

#27654 fix: Steps navigation broken style
  components/steps/style/custom-icon.less
  components/steps/style/index.less
  components/steps/style/vertical.less
Labels: PR: unreviewed

#27652 docs: ✨ release 4.8.2
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#27649 test: pull request target action
  .github/workflows/ui.yml
Labels: PR: unreviewed

#27659 chore: Merge master to feature
  .github/workflows/ui.yml
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/pagination/style/rtl.less
  components/steps/style/custom-icon.less
  components/steps/style/index.less
  components/steps/style/vertical.less
  package.json
Labels: PR: reviewed-approved

#27664 chore: bump rc-field-form
  package.json
Labels: PR: reviewed-approved

#27670 perf: reduce css
  components/alert/style/rtl.less
  components/breadcrumb/style/index.tsx
  components/button/style/rtl.less
  components/calendar/style/rtl.less
  components/card/style/size.less
Labels: PR: unreviewed

#27651 style: revert Menu easing functions
  components/menu/style/index.less
Labels: PR: reviewed-approved

#27672 chore: 🆙 upgrade devDeps
  package.json
Labels: PR: unreviewed

#27673 fix: RangePicker align active-bar with small size
  components/date-picker/style/index.less
  components/date-picker/style/rtl.less
Labels: PR: reviewed-approved

#27679 fix: update the slice rule when the TextArea component limits maxLength
  components/input/TextArea.tsx
  components/input/__tests__/textarea.test.js
Labels: PR: unreviewed

#27655 refactor(editable): rewrite with hook
  components/typography/Editable.tsx
Labels: PR: reviewed-approved

#27689 style(💄): fix Select mutiple cursor position
  components/select/style/multiple.less
  components/select/style/rtl.less
Labels: PR: unreviewed

#27691 style: fix Avatar src Image style
  components/avatar/style/index.less
Labels: PR: unreviewed

#27695 chore(✅): Add codacy-analysis.yml
  .github/workflows/codacy-analysis.yml
Labels: PR: unreviewed

#27694 refactor(carousel): rewirte with hook
  components/carousel/__tests__/index.test.js
  components/carousel/index.tsx
Labels: PR: unreviewed

#27663 chore: UPDATE menu version
  components/dropdown/style/index.less
  components/dropdown/style/rtl.less
  components/menu/__tests__/index.test.js
  components/menu/style/index.less
  components/menu/style/rtl.less
  package.json
Labels: PR: unreviewed

#27698 docs(carousel): change demo to hook
  components/carousel/demo/position.md
Labels: PR: reviewed-approved

#27703 style: add @radio-border-width
  components/radio/style/index.less
  components/style/themes/default.less
Labels: PR: unreviewed

#27704 fix : Specific Note for option other for Gender in Form
  components/form/demo/control-ref.md
Labels: PR: unreviewed

#27722 docs(radio): change demo to hook
  components/radio/demo/radiogroup.md
Labels: PR: reviewed-approved

#27723 docs(grid): fix api table
  components/grid/index.en-US.md
Labels: PR: reviewed-approved

#27731 fix: DateRangePicker hover effect overflow
  components/date-picker/style/panel.less
  components/date-picker/style/rtl.less
Labels: PR: reviewed-approved

#27724 docs(Form): fixed nested ternary operator in Form
  components/form/demo/control-ref.md
Labels: PR: unreviewed

#27715 chore: merge master into feature
  .github/workflows/codacy-analysis.yml
  components/alert/style/rtl.less
  components/avatar/style/index.less
  components/breadcrumb/style/index.tsx
  components/button/style/rtl.less
  components/calendar/style/rtl.less
  components/card/style/size.less
  components/carousel/__tests__/index.test.js
  components/carousel/demo/position.md
  components/carousel/index.tsx
  components/cascader/index.en-US.md
  components/cascader/index.zh-CN.md
  components/date-picker/style/index.less
  components/date-picker/style/rtl.less
  components/dropdown/style/index.less
  components/dropdown/style/rtl.less
  components/form/demo/control-ref.md
  components/input/TextArea.tsx
  components/input/__tests__/textarea.test.js
  components/menu/__tests__/index.test.js
  components/menu/style/index.less
  components/menu/style/rtl.less
  components/radio/style/index.less
  components/select/style/multiple.less
  components/select/style/rtl.less
  components/style/themes/default.less
  components/tree/demo/dynamic.md
  components/typography/Editable.tsx
  package.json
  site/theme/static/common.less
Labels: PR: partially-approved

#27734 fix: Typography.Link disabled hover style
  components/typography/style/index.less
Labels: PR: unreviewed

#27736 docs(select): change demo to hook
  components/select/demo/coordinate.md
Labels: PR: reviewed-approved

#27717 fix: checked 非必须
  components/tag/CheckableTag.tsx
Labels: PR: unreviewed

#27741 fix: Field under renderProps can not get latest rules
  package.json
Labels: PR: unreviewed

#27751 docs(date-picker): modify datepicker select-in-range demo
  components/date-picker/demo/select-in-range.md
Labels: PR: unreviewed

#27752 perf(⬆️): unify rc-trigger version
  package.json
Labels: PR: unreviewed

#27758 docs: Fix mispelling for 'palette'
  docs/spec/dark.en-US.md
Labels: PR: reviewed-approved

#27759 remove proxy function in Button.tsx
  components/button/button.tsx
Labels: PR: unreviewed

#27760 move array initialisation out of render <Col/>
  components/grid/col.tsx
Labels: PR: unreviewed

#27765 Update LoadingIcon.tsx
  components/button/LoadingIcon.tsx
Labels: PR: unreviewed

#27728 test: and pull_request_target branches-ignore
  .github/workflows/ui.yml
  .jest.image.js
  docker-compose.yml
  jest-puppeteer.config.js
  package.json
  tests/shared/imageTest.ts
Labels: PR: unreviewed

#27726 fix(select): fix tags mode white space wrapping issue
  components/select/style/multiple.less
Labels: PR: unreviewed

#27771 test: skip tree virtual-scroll render
  .github/workflows/ui.yml
  components/tree/__tests__/image.test.ts
Labels: PR: unreviewed

#27778 test: disable image request
  tests/shared/imageTest.ts
Labels: PR: unreviewed

#27772 docs: add 4.8.3 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#27781 docs: fix typo in demo
  components/popconfirm/demo/basic.md
Labels: PR: unreviewed

#27794 style(💄): fix Button and Form loading spin animation
  components/button/style/index.less
  components/form/style/status.less
Labels: PR: unreviewed

#27657 refactor(search): use context
  components/input/Search.tsx
Labels: PR: unreviewed

#27797 fix: Modal.confirm locale missing
  components/config-provider/__tests__/__snapshots__/form.test.js.snap
  components/config-provider/__tests__/form.test.js
  components/config-provider/index.tsx
Labels: PR: unreviewed

#27802 docs(✨): release 4.8.4
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#27804 refactor: improve card/Grid to save some bundle size after transpilation
  components/card/Grid.tsx
Labels: PR: unreviewed

#27805 docs(TreeSelect): add onDropdownVisibleChange api description
  components/tree-select/index.en-US.md
  components/tree-select/index.zh-CN.md
Labels: PR: unreviewed

#27745 docs(cascader): change demo to hook
  components/cascader/demo/lazy.md
Labels: PR: unreviewed

#27807 refactor: review radio/Group and get it ready for upcoming react changes
  components/radio/group.tsx
Labels: PR: unreviewed

#27814 refactor: make autosize true by default
  components/typography/Editable.tsx
Labels: PR: unreviewed

#27821 chore: Use rc-util composeRef
  components/_util/hooks/useCombinedRefs.tsx
  components/slider/SliderTooltip.tsx
Labels: PR: unreviewed

#27822 chore: merge master into feature
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/_util/hooks/useCombinedRefs.tsx
  components/_util/wave.tsx
  components/anchor/Anchor.tsx
  components/button/style/index.less
  components/card/Grid.tsx
  components/cascader/demo/lazy.md
  components/config-provider/__tests__/__snapshots__/form.test.js.snap
  components/config-provider/__tests__/form.test.js
  components/config-provider/index.tsx
  components/form/style/status.less
  components/input/Search.tsx
  components/menu/index.en-US.md
  components/menu/index.zh-CN.md
  components/radio/group.tsx
  components/slider/SliderTooltip.tsx
  components/tree-select/index.en-US.md
  components/tree-select/index.zh-CN.md
  components/typography/Editable.tsx
  package.json
Labels: PR: partially-approved

#27838 fix(Select): export SelectInterface to avoid ts error
  components/select/index.tsx
Labels: PR: unreviewed

#27840 refactor: Replace BackTop with rc-motion
  components/_util/reactNode.ts
  components/back-top/index.tsx
Labels: PR: unreviewed

#27743 refactor(trans-button): rewrite with hook
  components/_util/__tests__/util.test.js
  components/_util/transButton.tsx
  components/typography/Base.tsx
Labels: PR: unreviewed

#27693 refactor(textarea): rewirte with hook
  components/input/ClearableLabeledInput.tsx
  components/input/TextArea.tsx
  components/input/__tests__/textarea.test.js
Labels: PR: unreviewed

#27839 fix: Spin render 0
  components/spin/__tests__/index.test.js
  components/spin/index.tsx
Labels: PR: reviewed-approved

#27846 feat(type): export ImageProps interface
  components/image/index.tsx
Labels: PR: reviewed-approved

#27810 refactor: remove duplicate deconstruction in components/form/Form.tsx
  components/form/Form.tsx
Labels: PR: unreviewed

#27854 test: Update snapshot
  components/badge/__tests__/__snapshots__/index.test.js.snap
  components/badge/__tests__/index.test.js
Labels: PR: unreviewed

#27857 Revert "fix(Select): export SelectInterface to avoid ts error"
  components/select/index.tsx
Labels: PR: unreviewed

#27836 style(💄): optimize Skeleton color
  components/skeleton/style/index.less
  components/style/themes/dark.less
  components/style/themes/default.less
  package.json
Labels: PR: unreviewed

#27848 refactor: Replace Badge with rc-motion
  components/badge/ScrollNumber.tsx
  components/badge/__tests__/__snapshots__/demo.test.js.snap
  components/badge/__tests__/__snapshots__/index.test.js.snap
  components/badge/__tests__/index.test.js
  components/badge/index.tsx
Labels: PR: unreviewed

#27860 style(💄): fix Switch loading style
  components/switch/style/index.less
Labels: PR: unreviewed

#27872 feat: Form.List support `initialValue`
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#27876 fix: Tree switcher icon in rtl
  components/tree/style/rtl.less
Labels: PR: unreviewed

#27719 refactor(layout.sider): rewrite with hook
  components/layout/Sider.tsx
  components/layout/__tests__/__snapshots__/index.test.js.snap
  components/layout/__tests__/index.test.js
  components/layout/index.tsx
  components/layout/layout.tsx
Labels: PR: partially-approved

#27739 refactor(checkbox): rewrite with hook
  components/checkbox/Checkbox.tsx
  components/checkbox/Group.tsx
  components/checkbox/__tests__/checkbox.test.js
  components/checkbox/__tests__/type.test.tsx
  components/checkbox/index.tsx
  components/transfer/__tests__/__snapshots__/index.test.js.snap
Labels: PR: partially-approved

#27870 fix: AutoComplete dataSource prop type error
  components/auto-complete/index.tsx
Labels: PR: unreviewed

#27892 refactor: AutoComplete dataSource prop type
  components/auto-complete/index.tsx
Labels: PR: unreviewed

#27893 chore: mergin master into feature
  README-zh_CN.md
  README.md
  components/_util/__tests__/util.test.js
  components/_util/reactNode.ts
  components/_util/transButton.tsx
  components/auto-complete/index.tsx
  components/back-top/index.tsx
  components/badge/ScrollNumber.tsx
  components/badge/__tests__/__snapshots__/demo.test.js.snap
  components/badge/__tests__/__snapshots__/index.test.js.snap
  components/badge/__tests__/index.test.js
  components/badge/index.tsx
  components/checkbox/Checkbox.tsx
  components/checkbox/Group.tsx
  components/checkbox/__tests__/checkbox.test.js
  components/checkbox/__tests__/type.test.tsx
  components/checkbox/index.tsx
  components/form/Form.tsx
  components/image/index.tsx
  components/input/ClearableLabeledInput.tsx
  components/input/TextArea.tsx
  components/input/__tests__/textarea.test.js
  components/layout/Sider.tsx
  components/layout/__tests__/__snapshots__/index.test.js.snap
  components/layout/__tests__/index.test.js
  components/layout/index.tsx
  components/layout/layout.tsx
  components/skeleton/style/index.less
  components/spin/__tests__/index.test.js
  components/spin/index.tsx
  components/style/themes/dark.less
  components/style/themes/default.less
  components/switch/style/index.less
  components/transfer/__tests__/__snapshots__/index.test.js.snap
  components/tree/style/rtl.less
  components/typography/Base.tsx
  docs/react/migration-v4.en-US.md
  docs/react/migration-v4.zh-CN.md
  package.json
Labels: PR: partially-approved

#27864 chore: replace raf with rc-util/lib/raf
  components/_util/__tests__/util.test.js
  components/_util/raf.ts
  components/_util/scrollTo.ts
  components/_util/throttleByAnimationFrame.tsx
  components/collapse/openAnimation.tsx
  components/form/__tests__/list.test.js
  components/form/hooks/useFrameState.ts
  components/slider/SliderTooltip.tsx
  package.json
Labels: PR: unreviewed

#27899 docs: Fix internationalization url
  README-zh_CN.md
Labels: PR: reviewed-approved

#27897 feat: Support label & content style of Desc
  components/descriptions/Cell.tsx
  components/descriptions/Item.tsx
  components/descriptions/Row.tsx
  components/descriptions/__tests__/__snapshots__/demo.test.js.snap
  components/descriptions/demo/style.md
  components/descriptions/index.en-US.md
  components/descriptions/index.zh-CN.md
Labels: PR: reviewed-approved

#27895 refactor: input remove not use code
  components/input/Input.tsx
Labels: PR: unreviewed

#27904 Remove duplicate links
  README.md
Labels: PR: unreviewed

#27881 feat: FormItem support _internalItemRender
  components/button/LoadingIcon.tsx
  components/form/ErrorList.tsx
  components/form/FormItemInput.tsx
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/__tests__/index.test.js
  package.json
Labels: PR: unreviewed

#27914 Fix typo
  docs/resources.en-US.md
Labels: PR: unreviewed

#27919 docs: recommend typo on Component Overview docs
  components/overview/index.en-US.md
Labels: PR: reviewed-approved

#27920 chore: use rc-util instead of ref.ts
  components/_util/ref.ts
  components/avatar/avatar.tsx
  components/mentions/index.tsx
  components/radio/radio.tsx
  components/typography/Typography.tsx
Labels: PR: unreviewed

#27923 refactor: UploadList use `rc-motion` instead of `rc-animate`
  components/_util/reactNode.ts
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/style/themes/default.less
  components/upload/UploadList.tsx
  components/upload/UploadList/ListItem.tsx
  components/upload/UploadList/index.tsx
  components/upload/__tests__/__snapshots__/demo.test.js.snap
  components/upload/__tests__/__snapshots__/uploadlist.test.js.snap
  components/upload/__tests__/uploadlist.test.js
  components/upload/interface.tsx
  components/upload/style/index.less
  package.json
Labels: PR: unreviewed

#27926 refactor: remove not use code
  components/upload/style/index.less
Labels: PR: unreviewed

#27909 feat: Support closeIcon of Modal.method
  components/modal/ConfirmDialog.tsx
  components/modal/Modal.tsx
  components/modal/__tests__/confirm.test.js
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
  components/modal/style/confirm.less
Labels: PR: unreviewed

#27884 feat: change statistic deciaml font size
  components/style/themes/default.less
Labels: PR: reviewed-approved, 💄 Design

#27930 docs(✨): release 4.8.5
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: partially-approved

#27935 CarouselRef type
  components/carousel/index.tsx
Labels: PR: reviewed-approved

#27934 fix: fix _internalItemRender transparent transmission problem
  components/form/FormItem.tsx
Labels: PR: unreviewed

#27938 chore(merge): Merge master branch into feature
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/style/themes/default.less
  components/upload/style/index.less
  package.json
Labels: PR: reviewed-approved

#27946 fix: 修改beforeUpload ts定义
  components/upload/interface.tsx
Labels: PR: unreviewed

#27957 fix(🐛): Carousel throws error `Unable to preventDefault inside passive event listener`
  components/carousel/style/index.less
Labels: PR: unreviewed

#27960 fix: Input.Search addonBefore style
  components/input/style/search-input.less
Labels: PR: unreviewed

#27548 chore: ignore-emit-webpack-plugin upgrade
  package.json
Labels: PR: unreviewed

#27987 docs: change link of react-markdown
  docs/react/recommendation.en-US.md
  docs/react/recommendation.zh-CN.md
Labels: PR: unreviewed

#27982 fix: Typography.Link copyable text default behavior
  components/typography/Base.tsx
Labels: PR: unreviewed

#27963 refactor: rewrite props defaults in a way to use single source of truth
  components/collapse/Collapse.tsx
Labels: PR: unreviewed

#27961 chore: make Timeline.Item a bit lighter, drop unneeded omit.js and defaultProps
  components/timeline/TimelineItem.tsx
Labels: PR: unreviewed
