Repository ant-design/ant-design, pull requests merged in 2020-07, with the labels that each got.

#25328 fix: ref lost in Radio.Group
  components/radio/group.tsx
Labels: PR: unreviewed

#25321 feat: validateFirst support parallel
  components/config-provider/__tests__/index.test.js
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  package.json
Labels: PR: unreviewed

#25315 fix: Tooltip custom color typescript type definition
  components/tooltip/index.tsx
Labels: PR: unreviewed

#25269 docs: fix version change
  site/theme/template/Layout/Header/index.tsx
Labels: PR: unreviewed

#25336 fix: Form.Item hidden no working
  components/form/FormItem.tsx
  components/form/__tests__/__snapshots__/index.test.js.snap
  components/form/style/index.less
Labels: PR: unreviewed

#25339 docs: format api input/inputnumber/mentions
  components/input-number/index.en-US.md
  components/input-number/index.zh-CN.md
  components/input/index.en-US.md
  components/input/index.zh-CN.md
  components/mentions/index.en-US.md
  components/mentions/index.zh-CN.md
Labels: PR: unreviewed

#25341 fix: Menu transition finished by opacity
  components/_util/motion.tsx
Labels: PR: unreviewed

#25340 fix: PageHeader Tabs margin bottom
  components/page-header/style/index.less
Labels: PR: unreviewed

#25342 docs: format api radio/rate/switch
  components/radio/index.en-US.md
  components/radio/index.zh-CN.md
  components/rate/index.en-US.md
  components/rate/index.zh-CN.md
  components/switch/index.en-US.md
  components/switch/index.zh-CN.md
Labels: PR: unreviewed

#25348 docs: format api select/slider/treeselect
  components/select/index.en-US.md
  components/select/index.zh-CN.md
  components/slider/index.en-US.md
  components/slider/index.zh-CN.md
  components/tree-select/index.en-US.md
  components/tree-select/index.zh-CN.md
Labels: PR: unreviewed

#25351 docs: format api timepicker/transfer/upload
  components/time-picker/index.en-US.md
  components/time-picker/index.zh-CN.md
  components/transfer/index.en-US.md
  components/transfer/index.zh-CN.md
  components/upload/index.en-US.md
  components/upload/index.zh-CN.md
Labels: PR: unreviewed

#25361 docs: clarify Select labelInValue onChange argument
  components/select/demo/label-in-value.md
  components/select/index.en-US.md
  components/select/index.zh-CN.md
Labels: PR: unreviewed

#25337 fix: Table component docs - updated Typescript example
  components/table/index.en-US.md
Labels: PR: unreviewed

#25363 docs: format api avatar/badge/comment
  components/avatar/index.en-US.md
  components/badge/index.en-US.md
  components/badge/index.zh-CN.md
  components/comment/index.en-US.md
  components/comment/index.zh-CN.md
Labels: PR: unreviewed

#25364 docs: format api card/carousel/collapse
  components/card/index.en-US.md
  components/card/index.zh-CN.md
  components/carousel/index.en-US.md
  components/carousel/index.zh-CN.md
  components/collapse/index.en-US.md
  components/collapse/index.zh-CN.md
Labels: PR: unreviewed

#25366 docs: format api calendar/descriptions/empty
  components/calendar/index.en-US.md
  components/calendar/index.zh-CN.md
  components/descriptions/index.en-US.md
  components/descriptions/index.zh-CN.md
  components/empty/index.en-US.md
Labels: PR: unreviewed

#25358 fix: slider typescript definition gets type warning in onChange
  components/slider/__tests__/type.test.tsx
  components/slider/index.tsx
Labels: PR: unreviewed

#25356 fix: change progress to percent in success props & warning in Progress
  components/progress/Circle.tsx
  components/progress/Line.tsx
  components/progress/__tests__/index.test.js
  components/progress/demo/segment.md
  components/progress/index.en-US.md
  components/progress/index.zh-CN.md
  components/progress/progress.tsx
Labels: PR: unreviewed

#25368 docs: format api list/popover/statistic
  components/list/index.en-US.md
  components/list/index.zh-CN.md
  components/popover/index.en-US.md
  components/popover/index.zh-CN.md
  components/statistic/index.en-US.md
  components/statistic/index.zh-CN.md
Labels: PR: unreviewed

#25375 docs: Update Tree virtual scroll desc
  components/tree/index.en-US.md
  components/tree/index.zh-CN.md
Labels: PR: unreviewed

#25319 fix: ResponsiveObserve unsubscribe (#25309)
  components/_util/__tests__/responsiveObserve.test.js
  components/_util/responsiveObserve.ts
  components/grid/row.tsx
Labels: PR: unreviewed

#25378 style: Fix Table header extra border of right column
  components/table/style/bordered.less
Labels: PR: reviewed-approved

#25377 docs: format api timeline/tooltip/tree
  components/timeline/index.en-US.md
  components/timeline/index.zh-CN.md
  components/tooltip/index.en-US.md
  components/tooltip/index.zh-CN.md
  components/tree/index.en-US.md
  components/tree/index.zh-CN.md
Labels: PR: unreviewed

#25381 fix: typo of pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: PR: unreviewed

#25383 docs: fix two typos in the docs
  components/overview/index.en-US.md
Labels: PR: reviewed-approved

#25384 docs: format api table/tabs/tag
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/tabs/index.en-US.md
  components/tabs/index.zh-CN.md
  components/tag/index.en-US.md
Labels: PR: unreviewed

#25387 docs: format api alert/drawer/modal
  components/alert/index.en-US.md
  components/alert/index.zh-CN.md
  components/drawer/index.en-US.md
  components/drawer/index.zh-CN.md
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
Labels: PR: unreviewed

#25388 docs: format api message/notification/progress
  components/message/index.en-US.md
  components/message/index.zh-CN.md
  components/notification/index.en-US.md
  components/notification/index.zh-CN.md
  components/progress/index.en-US.md
  components/progress/index.zh-CN.md
Labels: PR: unreviewed

#25390 docs: format api popconfirm/result/skeleton/spin
  components/popconfirm/index.en-US.md
  components/popconfirm/index.zh-CN.md
  components/result/index.en-US.md
  components/result/index.zh-CN.md
  components/skeleton/index.en-US.md
  components/skeleton/index.zh-CN.md
  components/spin/index.en-US.md
Labels: PR: unreviewed

#25393 docs: format api ancho/backtop/config
  components/anchor/index.en-US.md
  components/anchor/index.zh-CN.md
  components/back-top/index.en-US.md
  components/back-top/index.zh-CN.md
  components/config-provider/index.en-US.md
  components/config-provider/index.zh-CN.md
Labels: PR: unreviewed

#25391 chore: remove untranslated blocks in enUS site
  docs/resources.en-US.md
  site/theme/template/Home/index.tsx
Labels: PR: unreviewed

#25385 fix: shouldn't set input-bg inside a error form item
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/demo/disabled-input-debug.md
  components/form/style/mixin.less
Labels: PR: unreviewed

#25410 chore: merge feature into master
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/demo/disabled-input-debug.md
  components/form/demo/size.md
  components/form/style/mixin.less
  components/table/__tests__/__snapshots__/Table.rowSelection.test.js.snap
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/__tests__/__snapshots__/empty.test.js.snap
Labels: PR: reviewed-approved

#25413 docs: add debug on form/disabled-input-debug
  components/form/demo/disabled-input-debug.md
Labels: PR: unreviewed

#25408 feat: form item dep
  components/form/FormItem.tsx
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/__tests__/index.test.js
  components/form/demo/dep-debug.md
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#25414 fix: menu a color for #25412
  components/menu/style/index.less
Labels: PR: unreviewed

#25436 docs: Grammar
  components/form/index.en-US.md
Labels: PR: reviewed-approved

#25374 feat: improve nb_NO translations
  components/date-picker/locale/nb_NO.tsx
  components/locale/nb_NO.tsx
  components/time-picker/locale/nb_NO.tsx
  package.json
Labels: PR: unreviewed

#25369 refactor(menu): move feature to rc-menu(#24975)
  components/menu/MenuItem.tsx
  components/menu/__tests__/index.test.js
  components/menu/index.tsx
  components/table/hooks/useFilter/FilterDropdown.tsx
  package.json
Labels: PR: unreviewed

#25442 docs: 4.4.1 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
  scripts/print-changelog.js
Labels: PR: reviewed-approved

#25444 docs(comment): like and dislike number event binding #25437
  components/comment/__tests__/__snapshots__/demo.test.js.snap
  components/comment/demo/basic.md
Labels: PR: unreviewed

#25432 fix: support thumbnail for non-image files by upload onChange
  components/upload/__tests__/uploadlist.test.js
  components/upload/utils.tsx
Labels: PR: unreviewed

#25458 fix: RangePicker clear btn position
  components/date-picker/style/index.less
Labels: PR: unreviewed

#25460 feat: add missing translations in es_ES
  components/locale/es_ES.tsx
Labels: PR: reviewed-approved

#25472 docs: Update home articles
  site/theme/template/Home/MorePage.tsx
Labels: PR: unreviewed

#25449 fix: Popover wrong position when using Radio.Button
  components/radio/style/index.less
Labels: PR: unreviewed

#25476 style: add @select-item-selected-color
  components/select/style/index.less
  components/style/themes/default.less
Labels: PR: unreviewed

#25483 docs: reduce demo pageheader/pagination/steps
  components/page-header/__tests__/__snapshots__/demo.test.js.snap
  components/page-header/demo/actions.md
  components/page-header/demo/responsive.md
  components/pagination/__tests__/__snapshots__/demo.test.js.snap
  components/pagination/demo/all.md
  components/pagination/demo/changer.md
  components/pagination/demo/jump.md
  components/pagination/demo/mini.md
  components/pagination/demo/total.md
  components/steps/__tests__/__snapshots__/demo.test.js.snap
  components/steps/demo/clickable.md
  components/steps/demo/nav.md
  components/steps/demo/progress-dot.md
  components/steps/demo/step-next.md
Labels: PR: unreviewed

#25484 docs: reduce demo cascader/checkbox/form/inputno
  components/cascader/__tests__/__snapshots__/demo.test.js.snap
  components/cascader/demo/size.md
  components/checkbox/__tests__/__snapshots__/demo.test.js.snap
  components/checkbox/demo/check-all.md
  components/checkbox/demo/controller.md
  components/checkbox/demo/disabled.md
  components/checkbox/demo/group.md
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/demo/form-context.md
  components/form/demo/global-state.md
  components/form/demo/layout.md
  components/form/demo/size.md
  components/input-number/__tests__/__snapshots__/demo.test.js.snap
  components/input-number/demo/disabled.md
  components/input-number/demo/formatter.md
Labels: PR: unreviewed

#25486 docs: reduce demo mentions/slider/switch
  components/mentions/__tests__/__snapshots__/demo.test.js.snap
  components/mentions/demo/readonly.md
  components/slider/__tests__/__snapshots__/demo.test.js.snap
  components/slider/demo/basic.md
  components/slider/demo/event.md
  components/slider/demo/mark.md
  components/slider/demo/reverse.md
  components/slider/demo/tip-formatter.md
  components/slider/demo/vertical.md
  components/switch/__tests__/__snapshots__/demo.test.js.snap
  components/switch/demo/disabled.md
  components/switch/demo/loading.md
  components/switch/demo/size.md
  components/switch/demo/text.md
Labels: PR: unreviewed

#25487 docs: reduce demo transfer/upload
  components/transfer/__tests__/__snapshots__/demo.test.js.snap
  components/transfer/demo/basic.md
  components/transfer/demo/oneWay.md
  components/transfer/demo/table-transfer.md
  components/transfer/demo/tree-transfer.md
  components/upload/__tests__/__snapshots__/demo.test.js.snap
  components/upload/demo/picture-style.md
  components/upload/demo/preview-file.md
  components/upload/demo/transform-file.md
  components/upload/demo/upload-manually.md
Labels: PR: unreviewed

#25488 feat: DatePicker support `panelRender`
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
  package.json
Labels: PR: partially-approved

#25456 feat: Badge.Ribbon
  components/badge/Ribbon.tsx
  components/badge/__tests__/__snapshots__/demo.test.js.snap
  components/badge/__tests__/__snapshots__/index.test.js.snap
  components/badge/__tests__/index.test.js
  components/badge/demo/ribbbon.md
  components/badge/demo/ribbon-debug.md
  components/badge/index.en-US.md
  components/badge/index.tsx
  components/badge/index.zh-CN.md
  components/badge/style/index.tsx
  components/badge/style/ribbon.less
  components/badge/style/rtl.less
  components/badge/utils.tsx
Labels: PR: reviewed-approved

#25498 fix: nested Table cell background
  components/table/style/index.less
Labels: PR: unreviewed

#25439 docs: 📝 Update best practices
  docs/react/practical-projects.en-US.md
  docs/react/practical-projects.zh-CN.md
Labels: PR: unreviewed

#25502 docs: Update components/table/demo/custom-filter-panel.md
  components/table/demo/custom-filter-panel.md
Labels: PR: unreviewed

#25501 chore: 📦 Add bundle-stats and relative-ci
  .bundle-analyzerrc.json
  package.json
  webpack.config.js
Labels: PR: unreviewed

#25505 docs: update getPopupContainer
  components/drawer/demo/form-in-drawer.md
  docs/react/faq.en-US.md
  docs/react/faq.zh-CN.md
Labels: PR: unreviewed

#25516 chore: Default break word
  components/typography/style/index.less
Labels: PR: unreviewed

#25515 fix: Card cover margin bug when bordered is false
  components/card/style/index.less
Labels: PR: unreviewed

#25507 perf: 🆙 upgrade to omit.js@2.0.2
  package.json
  webpack.config.js
Labels: PR: unreviewed

#25518 fix: preserve warning in Form.Item
  components/form/FormItem.tsx
  components/form/__tests__/index.test.js
Labels: PR: unreviewed

#25525 docs: fix markdown typo
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: PR: unreviewed

#25523 Fix relative-ci setup
  webpack.config.js
Labels: PR: unreviewed

#25531 refactor: message style
  components/message/style/index.less
Labels: PR: reviewed-approved

#25530 perf: 📦 remove babel-runtime and enable @babel/runtime
  package.json
Labels: PR: unreviewed

#25539 refactor: Radio.Group use useMergedState
  components/_util/ref.ts
  components/radio/group.tsx
Labels: PR: unreviewed

#25544 docs: faq on components vertial alignment
  docs/react/faq.en-US.md
  docs/react/faq.zh-CN.md
Labels: PR: unreviewed

#25536 fix: Select showSearch align issue
  components/select/style/single.less
Labels: PR: unreviewed

#25553 docs: reduce demo calendar/carousel/collapse
  components/calendar/__tests__/__snapshots__/demo.test.js.snap
  components/calendar/demo/select.md
  components/carousel/__tests__/__snapshots__/demo.test.js.snap
  components/carousel/demo/position.md
  components/collapse/__tests__/__snapshots__/demo.test.js.snap
  components/collapse/demo/extra.md
Labels: PR: unreviewed

#25520 fix: Table onChange event is triggered twice
  components/table/__tests__/Table.pagination.test.js
  components/table/hooks/usePagination.ts
Labels: PR: unreviewed

#25565 docs: fix pagination api
  components/pagination/index.en-US.md
  components/pagination/index.zh-CN.md
Labels: PR: unreviewed

#25568 feat: RangePicker onCalendarChange info support
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#24460 fix: alert animation
  components/alert/index.tsx
  components/alert/style/index.less
Labels: PR: unreviewed

#24976 refactor(Grid): rewrite with hook
  components/grid/__tests__/__snapshots__/index.test.js.snap
  components/grid/__tests__/index.test.js
  components/grid/col.tsx
  components/grid/row.tsx
Labels: PR: unreviewed

#25574 docs: Update RecommendPage.tsx
  site/theme/template/Home/RecommendPage.tsx
Labels: PR: unreviewed

#25578 docs: remove unseless TreeNode in Tree demo
  components/tree/demo/basic-controlled.md
  components/tree/demo/basic.md
  components/tree/demo/dynamic.md
Labels: PR: reviewed-approved

#25579 docs: 4.4.2 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#25585 docs: fix drag table not correct
  components/table/demo/drag-sorting-handler.md
Labels: PR: reviewed-approved

#25587 feat: add missing translations in ar_EG
  components/locale/ar_EG.tsx
Labels: PR: reviewed-approved

#25590 docs: fix type in demo
  components/table/demo/drag-sorting-handler.md
Labels: PR: unreviewed

#25445 feat: multi-drawer-push
  components/drawer/__tests__/MultiDrawer.test.js
  components/drawer/index.en-US.md
  components/drawer/index.tsx
  components/drawer/index.zh-CN.md
Labels: PR: reviewed-approved

#25593 style: fix Descriptions breaks Table width when inside expandedRowRender
  components/table/style/index.less
Labels: PR: unreviewed

#25044 docs: add ProList recommendation
  components/list/index.zh-CN.md
Labels: PR: unreviewed

#25582 fix: Form.Item with `help` should display error style when validate failed
  components/form/FormItem.tsx
  components/form/__tests__/index.test.js
Labels: PR: unreviewed

#25192 feat: Avatar.Group
  components/avatar/__tests__/__snapshots__/demo.test.js.snap
  components/avatar/avatar.tsx
  components/avatar/demo/group.md
  components/avatar/group.tsx
  components/avatar/index.en-US.md
  components/avatar/index.tsx
  components/avatar/index.zh-CN.md
  components/avatar/style/group.less
  components/avatar/style/index.less
  components/avatar/style/index.tsx
  components/avatar/style/rtl.less
  components/style/themes/default.less
Labels: PR: partially-approved

#25598 fix: customRequest file interface
  components/upload/interface.tsx
Labels: PR: unreviewed

#25599 chore: upgrade react-slick to reduce bundle size
  package.json
Labels: PR: reviewed-approved

#25602 docs: fix layout demo
  components/layout/__tests__/__snapshots__/demo.test.js.snap
  components/layout/demo/basic.md
Labels: PR: unreviewed

#25604 chore: Feature merge master
  components/form/FormItem.tsx
  components/form/__tests__/index.test.js
  components/layout/__tests__/__snapshots__/demo.test.js.snap
  components/layout/demo/basic.md
  components/list/index.zh-CN.md
  components/table/style/index.less
  components/upload/interface.tsx
  package.json
Labels: PR: reviewed-approved

#25608 docs: 更正中文文档错别字
  docs/spec/shadow.zh-CN.md
Labels: PR: unreviewed

#25603 feat: support Modal.config for prefixCls
  components/message/index.en-US.md
  components/message/index.zh-CN.md
  components/modal/ConfirmDialog.tsx
  components/modal/__tests__/confirm.test.js
  components/modal/confirm.tsx
  components/modal/index.en-US.md
  components/modal/index.tsx
  components/modal/index.zh-CN.md
  docs/react/faq.en-US.md
  docs/react/faq.zh-CN.md
Labels: PR: unreviewed

#25611 docs: fix shadown md
  docs/spec/shadow.zh-CN.md
Labels: PR: unreviewed

#25610 docs: info version about Modal.config
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
Labels: PR: reviewed-approved

#25620 docs: Update Ant Design Pro Sketch Library
  docs/resources.en-US.md
  docs/resources.zh-CN.md
Labels: PR: unreviewed, 📝 Documentation

#25613 feat: Modal.config rootPrefixCls
  components/modal/ActionButton.tsx
  components/modal/ConfirmDialog.tsx
  components/modal/__tests__/confirm.test.js
  components/modal/confirm.tsx
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
  docs/react/faq.en-US.md
  docs/react/faq.zh-CN.md
Labels: PR: unreviewed

#25623 docs: Improve the Grid Col attribute description
  components/grid/index.en-US.md
  components/grid/index.zh-CN.md
Labels: PR: unreviewed

#25512 feat: Description list plus extra operation area
  components/descriptions/__tests__/__snapshots__/demo.test.js.snap
  components/descriptions/__tests__/index.test.js
  components/descriptions/demo/size.md
  components/descriptions/index.en-US.md
  components/descriptions/index.tsx
  components/descriptions/index.zh-CN.md
  components/descriptions/style/index.less
  components/style/themes/default.less
Labels: PR: reviewed-approved

#25624 feat: Tree support titleRender
  components/tree/index.en-US.md
  components/tree/index.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#25629 docs: fix table.md
  components/table/index.en-US.md
Labels: PR: reviewed-approved

#25635 docs: add input.password iconRender
  components/input/index.en-US.md
  components/input/index.zh-CN.md
Labels: PR: unreviewed

#25641 chore: merge master into feature
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/grid/index.en-US.md
  components/grid/index.zh-CN.md
  components/input/index.en-US.md
  components/input/index.zh-CN.md
  components/layout/__tests__/__snapshots__/demo.test.js.snap
  components/layout/demo/basic.md
  components/table/index.en-US.md
  docs/react/migration-v4.en-US.md
  docs/react/migration-v4.zh-CN.md
  docs/resources.en-US.md
  docs/resources.zh-CN.md
  docs/spec/shadow.zh-CN.md
  package.json
  site/bisheng.config.js
Labels: PR: reviewed-approved

#25422 Feat message hooks
  .eslintignore
  components/_util/usePatchElement.tsx
  components/message/__tests__/__snapshots__/demo.test.js.snap
  components/message/__tests__/hooks.test.js
  components/message/demo/hooks.md
  components/message/hooks/useMessage.tsx
  components/message/index.en-US.md
  components/message/index.tsx
  components/message/index.zh-CN.md
  components/notification/index.tsx
Labels: PR: reviewed-approved

#25638 feat: update rc-field-form@1.8.0 and support remove use array in Form.List
  components/form/FormList.tsx
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#25645 docs: fix layout demo style
  components/layout/demo/basic.md
Labels: PR: unreviewed

#25617 feat: Input & Input.TextArea support bordered prop
  components/input/ClearableLabeledInput.tsx
  components/input/Input.tsx
  components/input/TextArea.tsx
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/demo/borderless-debug.md
  components/input/demo/borderless.md
  components/input/index.en-US.md
  components/input/index.zh-CN.md
  components/input/style/mixin.less
  components/transfer/__tests__/__snapshots__/search.test.js.snap
Labels: PR: reviewed-approved

#25652 docs: umi hooks rename to ahooks
  docs/react/recommendation.en-US.md
  docs/react/recommendation.zh-CN.md
  site/theme/template/Layout/Footer.tsx
Labels: PR: unreviewed

#25651 docs: Add link to Zero config custom theme generator
  docs/react/customize-theme.en-US.md
  docs/react/customize-theme.zh-CN.md
Labels: PR: unreviewed

#25653 fix: Layout trigger
  components/layout/Sider.tsx
  components/layout/__tests__/index.test.js
Labels: PR: unreviewed

#25655 docs: 🎬 import Modal demo
  components/modal/__tests__/__snapshots__/demo.test.js.snap
  components/modal/__tests__/demo.test.js
  components/modal/demo/async.md
  components/modal/demo/basic.md
  components/modal/demo/button-props.md
  components/modal/demo/confirm-router.md
  components/modal/demo/dark.md
  components/modal/demo/footer.md
  components/modal/demo/hooks.md
  components/modal/demo/locale.md
  components/modal/demo/position.md
Labels: PR: unreviewed

#25675 docs: Update faq.en-US.md
  docs/react/faq.en-US.md
Labels: PR: reviewed-approved

#25673 docs: update i18n.en-US.md
  docs/react/i18n.en-US.md
Labels: PR: reviewed-approved

#25672 docs: Update getting-started.en-US.md
  docs/react/getting-started.en-US.md
Labels: PR: reviewed-approved

#25676 docs: update en-US.js
  site/theme/en-US.js
Labels: PR: reviewed-approved

#25685 docs: fix color docs comment typo
  docs/spec/colors.en-US.md
  docs/spec/colors.zh-CN.md
Labels: PR: reviewed-approved

#25697 style: fix classnames to classNames
  components/page-header/index.tsx
  components/result/index.tsx
Labels: PR: unreviewed

#25699 docs: update gitee
  site/theme/template/Layout/Footer.jsx
Labels: PR: unreviewed

#25700 docs: add faq about gitee
  docs/react/faq.zh-CN.md
Labels: PR: unreviewed

#25701 chore: className here is unnecessary
  components/table/demo/virtual-list.md
Labels: PR: unreviewed

#25704 fix: update rc-input-number@5.1.1 && onBlur should get value '' when clear the data
  package.json
Labels: PR: unreviewed

#25695 docs: changelog 4.4.3
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#25712 docs: optimize button docs
  components/button/demo/basic.md
  components/button/index.en-US.md
  components/button/index.zh-CN.md
Labels: PR: unreviewed

#25713 fix: offset in FormItem's labelCol isn't work if layout is vertical
  components/form/style/vertical.less
Labels: PR: unreviewed

#25718 docs: remove unused className
  components/table/demo/virtual-list.md
Labels: PR: unreviewed

#25722 style: 💄 change card actions color to body color
  components/style/themes/dark.less
  components/style/themes/default.less
Labels: PR: reviewed-approved

#25724 docs: optimize modal docs
  components/modal/__tests__/__snapshots__/demo.test.js.snap
  components/modal/demo/basic.md
  components/modal/demo/locale.md
Labels: PR: unreviewed

#25728 fix: Form control clear icon position
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/demo/validate-static.md
  components/form/style/rtl.less
  components/form/style/status.less
  package.json
Labels: PR: unreviewed

#25626 fix: Calendar validRange prevents disabledDate
  components/calendar/Header.tsx
  components/calendar/__tests__/index.test.js
  components/calendar/generateCalendar.tsx
Labels: PR: unreviewed

#25734 fix: FormItem with noStyle passing error logic
  components/form/FormItem.tsx
  components/form/__tests__/index.test.js
Labels: PR: unreviewed

#25735 feat: using alert role in form-item-explain
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/form/FormItemInput.tsx
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/form/__tests__/index.test.js
Labels: PR: reviewed-approved

#25731 feat(locale): 添加新语言支持zh-HK
  components/locale/zh-HK
Labels: PR: unreviewed

#25671 docs: Fixed typos
  components/grid/demo/flex-order.md
Labels: PR: unreviewed

#25738 docs: remove unnecessary code
  components/table/demo/virtual-list.md
Labels: PR: unreviewed

#25740 Revert "docs: remove unnecessary code"
  components/table/demo/virtual-list.md
Labels: PR: unreviewed

#25744 fix: Carousel findDOMNode warning
  package.json
Labels: PR: reviewed-approved

#25754 chore: Update rc-tree deps
  package.json
Labels: PR: reviewed-approved

#25755 fix: TreeSelect treeNodeLabelProp should only work on values
  package.json
Labels: PR: unreviewed

#25768 docs: Update DatePicker docs and add legacy notice
  components/date-picker/__tests__/QuarterPicker.test.js
  components/date-picker/__tests__/__snapshots__/QuarterPicker.test.js.snap
  components/date-picker/demo/disabled.md
  components/date-picker/generatePicker/generateSinglePicker.tsx
  components/date-picker/generatePicker/index.tsx
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
  components/form/demo/time-related-controls.md
  components/input/demo/align.md
Labels: PR: unreviewed

#25774 fix: ⌨️ improve Alert/message/notification accessibility by adding role
  components/alert/__tests__/__snapshots__/demo.test.ts.snap
  components/alert/__tests__/__snapshots__/index.test.tsx.snap
  components/alert/index.tsx
  components/calendar/__tests__/__snapshots__/demo.test.js.snap
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/message/index.tsx
  components/notification/index.tsx
  components/spin/__tests__/__snapshots__/demo.test.js.snap
Labels: PR: unreviewed

#25772 fix: pagination button cursor style
  components/pagination/style/index.less
Labels: PR: unreviewed

#25784 feat(date-picker): improve hovering experience
  package.json
Labels: PR: reviewed-approved

#25622 style: 💄 update Menu.Item horizontal style
  components/menu/style/index.less
  site/theme/template/Layout/Header/Navigation.less
Labels: PR: reviewed-approved

#25649 fix: Table getCheckboxProps indeterminate not working
  components/table/__tests__/Table.rowSelection.test.js
  components/table/__tests__/__snapshots__/demo.test.js.snap
  components/table/demo/tree-data.md
  components/table/hooks/useSelection.tsx
Labels: PR: unreviewed

#25795 docs: Update site docs
  site/theme/template/Home/MorePage.tsx
Labels: PR: unreviewed

#25806 fix: Avatar fallback bug
  components/avatar/__tests__/Avatar.test.js
  components/avatar/__tests__/__snapshots__/Avatar.test.js.snap
  components/avatar/__tests__/__snapshots__/demo.test.js.snap
  components/avatar/demo/fallback.md
  components/avatar/index.tsx
Labels: PR: unreviewed

#25816 fix: build site failed, lock webpack version
  package.json
Labels: PR: reviewed-approved

#25821 fix(radio): build site failed in webpack@4.44.0
  components/radio/index.tsx
  package.json
Labels: PR: unreviewed

#25823 feat: add de_DE localisation for defaultValidateMessages for Form Component
  components/locale/de_DE.tsx
Labels: PR: unreviewed

#25825 test: create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: PR: unreviewed

#25828 fix: ci lint error
  .eslintrc.js
Labels: PR: reviewed-approved
