Repository ant-design/ant-design, pull requests merged in 2020-02, with the labels that each got.

#21168 fix: FormItem required not work without name
  components/form/FormItem.tsx
  components/form/__tests__/index.test.js
Labels: PR: reviewed-changes-requested, bug

#21169 fix: Table `expandIcon` should work
  components/table/Table.tsx
  components/table/__tests__/Table.expand.test.js
  package.json
Labels: PR: reviewed-changes-requested, bug

#21170 fix: Fix Progress to use `React.Fragment` to remove unused div
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/progress/Line.tsx
  components/progress/__tests__/__snapshots__/demo.test.js.snap
  components/progress/__tests__/__snapshots__/index.test.js.snap
  components/upload/__tests__/__snapshots__/uploadlist.test.js.snap
Labels: PR: unreviewed, bug

#21175 fix: Select multiple selection margin
  components/select/style/multiple.less
Labels: PR: unreviewed, bug

#21176 refactor: Button disable `autoInsertSpaceInButton` will not calculate text length
  components/button/__tests__/index.test.js
  components/button/button.tsx
Labels: PR: reviewed-changes-requested, refactor

#21177 chore: Merge master
  components/button/__tests__/index.test.js
  components/button/button.tsx
  components/checkbox/Checkbox.tsx
  components/checkbox/Group.tsx
  components/checkbox/__tests__/group.test.js
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/form/FormItem.tsx
  components/form/__tests__/index.test.js
  components/layout/index.en-US.md
  components/progress/Line.tsx
  components/progress/__tests__/__snapshots__/demo.test.js.snap
  components/progress/__tests__/__snapshots__/index.test.js.snap
  components/select/style/multiple.less
  components/table/Table.tsx
  components/table/__tests__/Table.expand.test.js
  components/upload/__tests__/__snapshots__/uploadlist.test.js.snap
  components/upload/demo/fileList.md
  package.json
Labels: PR: reviewed-changes-requested, chore

#21178 feat: Form.Item support `validateFirst`
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  package.json
Labels: PR: reviewed-approved, enhancement

#21179 fix: Form.Item with name `0` should be validate
  components/form/FormItem.tsx
  components/form/__tests__/index.test.js
Labels: PR: reviewed-changes-requested, bug

#21184 Update dark.md
  docs/spec/dark.md
Labels: PR: unreviewed

#21188 docs: 🐛 fix site menu affix bug
  site/theme/static/responsive.less
  site/theme/template/Content/MainContent.jsx
Labels: PR: unreviewed

#21187 docs: ✨ release 3.26.8
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#20949 feat: Modal support hooks
  components/_util/usePatchElement.tsx
  components/modal/ConfirmDialog.tsx
  components/modal/Modal.tsx
  components/modal/__tests__/hook.test.js
  components/modal/confirm.tsx
  components/modal/demo/hooks.md
  components/modal/index.en-US.md
  components/modal/index.tsx
  components/modal/index.zh-CN.md
  components/modal/useModal/HookModal.tsx
  components/modal/useModal/index.tsx
Labels: PR: unreviewed

#21194 fix: Table.Column should correct handle sorter state
  components/table/__tests__/Table.sorter.test.js
  components/table/util.ts
Labels: PR: reviewed-changes-requested

#21186 fix: Form.Item name `0` processing
  components/form/FormItem.tsx
  components/form/__tests__/index.test.js
Labels: PR: reviewed-approved

#21200 fix: Fix wrong event type of AntTreeNodeMouseEvent
  components/tree/Tree.tsx
Labels: PR: unreviewed

#21201 docs: fix typo
  components/slider/demo/tip-formatter.md
Labels: PR: unreviewed

#21139 feat: resolve #20728 customize header checkbox labels in Transfer
  components/transfer/__tests__/__snapshots__/demo.test.js.snap
  components/transfer/__tests__/index.test.js
  components/transfer/demo/custom-select-all-labels.md
  components/transfer/index.en-US.md
  components/transfer/index.tsx
  components/transfer/index.zh-CN.md
  components/transfer/list.tsx
Labels: PR: reviewed-approved

#21202 fix: Collapse Panel with extra prop
  components/collapse/style/index.less
Labels: PR: unreviewed

#21212 chore: Update azure-pipelines.yml for CI message
  azure-pipelines.yml
Labels: PR: unreviewed

#21211 fix: Form.Item init status should also check help
  components/form/FormItem.tsx
Labels: PR: unreviewed

#21216 style: Add less variable @form-item-label-font-size
  components/form/style/index.less
  components/style/themes/default.less
Labels: PR: unreviewed

#21215 fix: Radio Group style with Badge
  components/radio/__tests__/__snapshots__/demo.test.js.snap
  components/radio/demo/badge.md
  components/radio/style/index.less
Labels: PR: unreviewed

#21217 fix: avoid reading innerText in Button
  components/button/button.tsx
Labels: PR: unreviewed

#21218 fix: Table customize filter update
  components/table/__tests__/Table.hooks.test.js
  components/table/hooks/useSyncState.ts
Labels: PR: unreviewed

#21219 feat: Add style prop for Checkbox & Radio Group options
  components/checkbox/Group.tsx
  components/checkbox/__tests__/__snapshots__/group.test.js.snap
  components/checkbox/__tests__/group.test.js
  components/radio/__tests__/__snapshots__/group.test.js.snap
  components/radio/__tests__/group.test.js
  components/radio/group.tsx
Labels: PR: reviewed-changes-requested

#21220 chore: Add article track
  site/theme/template/Home/MorePage.tsx
Labels: PR: unreviewed

#21185 chore: 🆙 upgrade jest 25
  components/input/__tests__/Password.test.js
  components/input/__tests__/index.test.js
  package.json
Labels: PR: unreviewed

#21101 docs: dark color tool
  docs/spec/dark.md
  site/theme/en-US.js
  site/theme/static/colors.less
  site/theme/template/Color/ColorBlock.jsx
  site/theme/template/Color/ColorPaletteToolDark.jsx
  site/theme/template/Color/ColorPalettes.jsx
  site/theme/template/Color/ColorPatterns.jsx
  site/theme/template/Color/Palette.jsx
  site/theme/zh-CN.js
Labels: PR: reviewed-approved, 📝 Documentation

#21125 fix: pt_BR locale rangePlaceholder translation
  components/date-picker/locale/pt_BR.tsx
Labels: PR: unreviewed

#21226 chore: Merge feature into master
  components/_util/usePatchElement.tsx
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/modal/ConfirmDialog.tsx
  components/modal/Modal.tsx
  components/modal/__tests__/hook.test.js
  components/modal/confirm.tsx
  components/modal/demo/hooks.md
  components/modal/index.en-US.md
  components/modal/index.tsx
  components/modal/index.zh-CN.md
  components/modal/useModal/HookModal.tsx
  components/modal/useModal/index.tsx
  components/transfer/__tests__/__snapshots__/demo.test.js.snap
  components/transfer/__tests__/index.test.js
  components/transfer/demo/custom-select-all-labels.md
  components/transfer/index.en-US.md
  components/transfer/index.tsx
  components/transfer/index.zh-CN.md
  components/transfer/list.tsx
  package.json
Labels: PR: reviewed-changes-requested

#21235 fix: Badge number style
  components/avatar/__tests__/__snapshots__/demo.test.js.snap
  components/badge/ScrollNumber.tsx
  components/badge/__tests__/__snapshots__/demo.test.js.snap
  components/badge/__tests__/__snapshots__/index.test.js.snap
  components/badge/style/index.less
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/radio/__tests__/__snapshots__/demo.test.js.snap
Labels: PR: unreviewed

#21237 fix: Badge number style
  components/avatar/__tests__/__snapshots__/demo.test.js.snap
  components/badge/ScrollNumber.tsx
  components/badge/__tests__/__snapshots__/demo.test.js.snap
  components/badge/__tests__/__snapshots__/index.test.js.snap
  components/badge/style/index.less
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
Labels: PR: unreviewed

#21244 fix(#19879): add drag class to slider and upgrade slider to 9.2.1
  components/slider/style/index.less
  package.json
Labels: PR: unreviewed

#21247 fix: Transfer search input style collapsed
  components/transfer/style/index.less
Labels: PR: unreviewed

#21242 feat: Add bordered prop for controls
  components/cascader/index.en-US.md
  components/cascader/index.tsx
  components/cascader/index.zh-CN.md
  components/cascader/style/index.less
  components/date-picker/__tests__/__snapshots__/demo.test.js.snap
  components/date-picker/demo/bordered.md
  components/date-picker/generatePicker.tsx
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
  components/date-picker/style/index.less
  components/select/__tests__/__snapshots__/demo.test.js.snap
  components/select/demo/bordered.md
  components/select/index.en-US.md
  components/select/index.tsx
  components/select/index.zh-CN.md
  components/select/style/index.less
  components/time-picker/index.en-US.md
  components/time-picker/index.zh-CN.md
  components/tree-select/index.en-US.md
  components/tree-select/index.tsx
  components/tree-select/index.zh-CN.md
Labels: PR: reviewed-approved

#21250 fix: Minor fix on ValidationRule to match AsyncValidator
  components/form/Form.tsx
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: PR: unreviewed

#21246 chore: dark site style
  components/slider/__tests__/__snapshots__/demo.test.js.snap
  components/slider/demo/icon-slider.md
  package.json
  scripts/generateColorLess.js
  site/theme/static/dark.less
Labels: PR: reviewed-approved

#21258 fix: Steps style when size="small" and labelPlacement="vertical"
  components/steps/style/label-placement.less
Labels: PR: unreviewed

#21243 docs: clean up TreeSelect deprecated usage
  components/tree-select/demo/basic.md
  components/tree-select/demo/checkable.md
  components/tree-select/demo/multiple.md
  components/tree-select/demo/suffix.md
  components/tree-select/demo/treeData.md
  components/tree-select/index.en-US.md
  components/tree-select/index.zh-CN.md
Labels: PR: unreviewed

#21256 style: 💄 New tabs style
  components/page-header/style/index.less
  components/style/themes/default.less
  docs/react/migration-v4.en-US.md
  docs/react/migration-v4.zh-CN.md
Labels: PR: reviewed-approved

#21268 fix: Typography editable should focus at the end
  components/typography/Editable.tsx
  components/typography/__tests__/index.test.js
Labels: PR: reviewed-changes-requested

#21273 refactor: fix lgtm problems
  scripts/azure-github-comment.js
  site/theme/template/Color/ColorPaletteToolDark.jsx
  site/theme/template/Color/Palette.jsx
Labels: PR: unreviewed

#21276 chore: remove react-router from devDeps
  components/breadcrumb/demo/router-4.md
  components/breadcrumb/demo/router.md
  package.json
Labels: PR: unreviewed

#21275 feat: Notification support hooks for context
  .eslintrc.js
  components/form/__tests__/type.test.tsx
  components/notification/__tests__/__snapshots__/demo.test.js.snap
  components/notification/__tests__/hooks.test.js
  components/notification/demo/hooks.md
  components/notification/hooks/useNotification.tsx
  components/notification/index.en-US.md
  components/notification/index.tsx
  components/notification/index.zh-CN.md
  components/notification/style/index.less
  components/table/__tests__/type.test.tsx
  package.json
  typings/custom-typings.d.ts
Labels: PR: reviewed-approved

#21279 docs: Update hooks description
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
  components/notification/index.en-US.md
  components/notification/index.zh-CN.md
Labels: PR: reviewed-approved

#21284 chore: Master merge feature
  .eslintrc.js
  components/cascader/index.en-US.md
  components/cascader/index.tsx
  components/cascader/index.zh-CN.md
  components/cascader/style/index.less
  components/date-picker/__tests__/__snapshots__/demo.test.js.snap
  components/date-picker/demo/bordered.md
  components/date-picker/generatePicker.tsx
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
  components/date-picker/style/index.less
  components/form/__tests__/type.test.tsx
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
  components/notification/__tests__/__snapshots__/demo.test.js.snap
  components/notification/__tests__/hooks.test.js
  components/notification/demo/hooks.md
  components/notification/hooks/useNotification.tsx
  components/notification/index.en-US.md
  components/notification/index.tsx
  components/notification/index.zh-CN.md
  components/notification/style/index.less
  components/select/__tests__/__snapshots__/demo.test.js.snap
  components/select/demo/bordered.md
  components/select/index.en-US.md
  components/select/index.tsx
  components/select/index.zh-CN.md
  components/select/style/index.less
  components/table/__tests__/type.test.tsx
  components/time-picker/index.en-US.md
  components/time-picker/index.zh-CN.md
  components/tree-select/index.en-US.md
  components/tree-select/index.tsx
  components/tree-select/index.zh-CN.md
  package.json
  typings/custom-typings.d.ts
Labels: PR: reviewed-changes-requested

#21265 fix: Explicitly add children prop to Timeline.
  components/timeline/Timeline.tsx
  components/timeline/TimelineItem.tsx
Labels: PR: reviewed-approved

#21289 docs: Add the changelog of 3.26.9
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: reviewed-approved

#21293 docs: Update font-awesome link
  docs/react/recommendation.zh-CN.md
Labels: PR: unreviewed

#21296 Corrected Grammatical Mistake
  docs/spec/values.en-US.md
Labels: PR: unreviewed

#21290 fix: form item Input size error with prefix or suffix
  components/input/Input.tsx
  components/input/Password.tsx
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/__tests__/__snapshots__/index.test.js.snap
  components/input/__tests__/index.test.js
  components/input/demo/size.md
Labels: PR: unreviewed

#21298 docs: fix link name
  docs/react/recommendation.zh-CN.md
Labels: PR: unreviewed

#21297 docs: Add the changelog of 4.0.0-rc.4
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  docs/spec/dark.md
Labels: PR: reviewed-approved

#21300 docs: fix link name in en docs
  docs/react/recommendation.en-US.md
Labels: PR: reviewed-approved

#21303 fix: fix tree node spread warning
  components/tree/DirectoryTree.tsx
Labels: PR: unreviewed

#21306 style: tweak steps 1px align
  components/steps/style/label-placement.less
Labels: PR: unreviewed

#21307 fix: Button.Group size style issue
  components/button/__tests__/__snapshots__/demo.test.js.snap
  components/button/demo/legacy-group.md
  components/button/style/mixin.less
Labels: PR: unreviewed

#21310 fix: Row style issue
  components/style/mixins/clearfix.less
Labels: PR: unreviewed

#21312 chore: improve dropdown demos in mobile
  components/dropdown/__tests__/__snapshots__/demo.test.js.snap
  components/dropdown/demo/basic.md
  components/dropdown/demo/event.md
  components/dropdown/demo/item.md
  components/dropdown/demo/menu-full.md
  components/dropdown/demo/overlay-visible.md
  components/dropdown/demo/sub-menu.md
  components/dropdown/demo/trigger.md
Labels: PR: unreviewed

#21314 fix: Menu collapsed jumping
  components/style/mixins/clearfix.less
Labels: PR: unreviewed

#21315 fix: expandable.expandIconColumnIndex setting failure in version 4.0
  components/table/Table.tsx
Labels: PR: unreviewed

#21316 fix: Some input style issue
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/input/demo/addon.md
  components/input/style/affix.less
  components/input/style/allow-clear.less
  components/input/style/index.less
  components/input/style/mixin.less
Labels: PR: unreviewed

#21321 fix: table export `ColumnProps`
  components/table/__tests__/type.test.tsx
  components/table/index.tsx
Labels: PR: unreviewed

#21322 docs: Fix site reproduce
  site/theme/template/Content/Demo/index.jsx
Labels: PR: unreviewed

#21325 fix: Alert button extra padding
  components/alert/style/index.less
Labels: PR: unreviewed

#21329 fix: validateFirst in console
  components/form/FormItem.tsx
  package.json
Labels: PR: unreviewed

#21333 fix: Badge color not working when contains children
  components/badge/__tests__/__snapshots__/index.test.js.snap
  components/badge/__tests__/index.test.js
  components/badge/index.tsx
Labels: PR: reviewed-changes-requested

#21323 docs: Form onFinish & getFieldsValue only get validate Field values
  components/badge/__tests__/index.test.js
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/form/v3.en-US.md
  components/form/v3.zh-CN.md
  package.json
Labels: PR: unreviewed

#21338 fix: input lg height issue
  components/style/themes/default.less
Labels: PR: unreviewed

#21064 feat: Adding custom renderer for select with demos
  components/select/__tests__/__snapshots__/demo.test.js.snap
  components/select/demo/custom-tag-render.md
  components/select/index.en-US.md
  components/select/index.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#21344 chore: upgrade rc-input-number
  package.json
Labels: PR: unreviewed

#21222 fix(Form): label width not correct when screen less than xs
  components/form/style/vertical.less
Labels: PR: unreviewed

#21364 test: Increase Slider and Input test coverage
  components/input/__tests__/index.test.js
  components/input/calculateNodeHeight.tsx
  components/slider/__tests__/index.test.js
  tests/shared/focusTest.js
Labels: PR: draft

#21393 docs: add 3.26.10 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: PR: unreviewed

#21363 feat: custom Upload action icons removeIcon and downloadIcon
  components/upload/Upload.tsx
  components/upload/UploadList.tsx
  components/upload/__tests__/__snapshots__/demo.test.js.snap
  components/upload/__tests__/__snapshots__/uploadlist.test.js.snap
  components/upload/__tests__/uploadlist.test.js
  components/upload/demo/upload-custom-action-icon.md
  components/upload/index.en-US.md
  components/upload/index.zh-CN.md
  components/upload/interface.tsx
Labels: PR: unreviewed

#21302 fix: 较小的@form-item-margin-bottom时表单验证信息切换时表单项抖动
  components/form/style/index.less
Labels: PR: unreviewed

#21522 fix: duplicate color
  site/theme/template/Color/ColorPatterns.jsx
Labels: 3.x

#21547 release: 3.26.12
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: 3.x, PR: unreviewed, needs-more-info

#21548 release: 4.0.0-rc.6
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: needs-more-info

#21580 fix: ignore lgtm rule
  components/notification/index.tsx
Labels: PR: draft

#21589 refactor: Remove DatePicker legacy cell className
  components/date-picker/demo/date-render.md
  components/date-picker/style/panel.less
  docs/react/migration-v4.en-US.md
  docs/react/migration-v4.zh-CN.md
Labels: PR: draft

#21518 fix: Grid rows overlapping when using vertical gutter and having columns of different heights
  components/grid/style/index.less
Labels: PR: unreviewed
