Repository ant-design/ant-design, pull requests merged in 2021-02, with the labels that each got.

#29141 Feature
  components/_util/styleChecker.tsx
  components/grid/__tests__/__snapshots__/demo.test.js.snap
  components/grid/__tests__/__snapshots__/index.test.js.snap
  components/grid/__tests__/gap.test.js
  components/grid/__tests__/index.test.js
  components/grid/__tests__/server.test.js
  components/grid/col.tsx
  components/grid/demo/playground.md
  components/grid/row.tsx
  components/grid/style/mixin.less
  components/input-number/__tests__/__snapshots__/demo.test.js.snap
  components/input-number/demo/keyboard.md
  components/input-number/index.en-US.md
  components/input-number/index.zh-CN.md
  components/modal/Modal.tsx
  components/table/Table.tsx
  components/table/__tests__/Table.sorter.test.js
  components/table/hooks/useSorter.tsx
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/table/interface.tsx
  package.json
Labels: PR: unreviewed

#29144 chore: Darken tag color
  components/tag/__tests__/__snapshots__/demo.test.js.snap
  components/tag/demo/colorful-inverse.md
  components/tag/style/index.less
Labels: PR: unreviewed

#29150 docs(Slider): fix syle documentation
  components/slider/index.en-US.md
  components/slider/index.zh-CN.md
Labels: PR: reviewed-approved

#29153 chore: upgrade rc-image
  components/image/index.en-US.md
  components/image/index.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#29105 feat: InputNumber support bordered prop
  components/input-number/__tests__/__snapshots__/demo.test.js.snap
  components/input-number/demo/borderless.md
  components/input-number/index.en-US.md
  components/input-number/index.tsx
  components/input-number/index.zh-CN.md
  components/input-number/style/index.less
  components/input-number/style/rtl.less
Labels: PR: partially-approved

#29118 fix: img should not overflow its container
  site/theme/static/markdown.less
Labels: PR: unreviewed

#29158 fix: Collapse header disappers with delay
  components/collapse/style/index.less
Labels: PR: unreviewed

#29159 Feature
  components/image/index.en-US.md
  components/image/index.zh-CN.md
  components/input-number/__tests__/__snapshots__/demo.test.js.snap
  components/input-number/demo/borderless.md
  components/input-number/index.en-US.md
  components/input-number/index.tsx
  components/input-number/index.zh-CN.md
  components/input-number/style/index.less
  components/input-number/style/rtl.less
  package.json
Labels: PR: unreviewed

#29161 ci: perfeact mirror action
  .github/workflows/mirror.yml
Labels: PR: unreviewed

#29176 docs: Update resource page
  docs/resources.en-US.md
  docs/resources.zh-CN.md
  site/theme/template/Resources/index.less
  site/theme/template/Resources/index.tsx
Labels: PR: unreviewed

#28981 style: add @progress-info-text-color
  components/progress/style/index.less
  components/style/themes/default.less
Labels: PR: unreviewed

#29180 docs: add Image onError doc
  components/image/index.en-US.md
  components/image/index.zh-CN.md
Labels: PR: unreviewed

#29182 fix: row style
  components/grid/style/mixin.less
Labels: PR: unreviewed

#29169 feat: added ref support to Sider component
  components/layout/Sider.tsx
  components/layout/__tests__/index.test.js
Labels: PR: reviewed-approved

#29131 docs: add 4.12.0 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/form/style/index.less
  components/table/Table.tsx
  components/table/__tests__/Table.pagination.test.js
  components/table/hooks/useSorter.tsx
  package.json
  tests/shared/demoTest.ts
Labels: PR: unreviewed

#29193 test: continue-on-error for github action mirror.yml
  .github/workflows/mirror.yml
Labels: PR: unreviewed

#29184 fix: Table pagination current change logic
  components/table/__tests__/Table.pagination.test.js
  components/table/hooks/usePagination.ts
Labels: PR: unreviewed

#29202 fix: Grid flexGap lazy check
  components/_util/__tests__/util.test.js
  components/_util/styleChecker.tsx
  components/grid/__tests__/gap.test.js
  components/grid/col.tsx
  components/grid/row.tsx
Labels: PR: reviewed-approved

#29198 chore: add changelog check script
  scripts/check-version-md.js
  scripts/test-all.sh
Labels: PR: unreviewed

#29204 docs: 4.12.1 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#29211 fix: only row gutter use gap
  components/grid/__tests__/gap.test.js
  components/grid/col.tsx
  components/grid/row.tsx
  components/grid/style/mixin.less
Labels: PR: unreviewed

#29205 ci: add verify-package-version
  .github/workflows/verify-package-version.yml
Labels: PR: unreviewed

#29214 style: make Table expand icon same size as checkbox
  components/table/style/index.less
Labels: PR: unreviewed

#29219 feat(drawer): support contentWrapperStyle
  components/drawer/index.en-US.md
  components/drawer/index.zh-CN.md
  package.json
Labels: PR: unreviewed

#29210 docs: Update FAQ
  docs/react/faq.en-US.md
  docs/react/faq.zh-CN.md
Labels: PR: unreviewed

#29223 docs: 4.12.2 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: reviewed-approved

#29228 test: fix codesandbox ci node version
  .codesandbox/ci.json
Labels: PR: unreviewed

#28437 docs: add missing docs for array rule
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: PR: unreviewed

#29234 Update index.en-US.md
  components/select/index.en-US.md
Labels: PR: unreviewed

#29229 refactor(drawer): rewrite with hook from @hosseinmd
  components/drawer/__tests__/Drawer.test.js
  components/drawer/__tests__/type.test.tsx
  components/drawer/index.tsx
Labels: PR: unreviewed

#29241 fix: fix confirm paramter ts type error
  components/table/interface.tsx
Labels: PR: unreviewed

#29242 fix: multiple Select disabled background in dark
  components/select/style/index.less
Labels: PR: unreviewed

#29245 fix: TextArea showCount should not be interactive
  components/form/style/index.less
  components/input/style/index.less
Labels: PR: unreviewed

#29257 docs: Fix data visualization color palette url
  docs/spec/colors.en-US.md
  docs/spec/colors.zh-CN.md
Labels: PR: reviewed-approved

#29238 ci: add pr welcome
  .github/workflows/pr-welcome.yml
Labels: PR: partially-approved

#29264 Update overview.zh-CN.md
  docs/spec/overview.zh-CN.md
Labels: PR: unreviewed

#29267 feat: Form.List nest item support `preserve`
  package.json
Labels: PR: reviewed-approved

#29271 fix: image ru_RU locale
  components/locale/ru_RU.tsx
Labels: PR: reviewed-approved

#29256 fix: pagination componnet is not displayed at the position is none of…
  components/table/Table.tsx
  components/table/__tests__/Table.pagination.test.js
  components/table/index.en-US.md
Labels: PR: unreviewed

#29269 docs: add rowKey prop for `List`.
  components/list/index.zh-CN.md
Labels: PR: unreviewed

#29285 feat: 添加全局静态配置
  components/config-provider/index.en-US.md
  components/config-provider/index.tsx
  components/config-provider/index.zh-CN.md
  components/message/__tests__/config.test.js
  components/message/index.en-US.md
  components/message/index.tsx
  components/message/index.zh-CN.md
  components/modal/__tests__/confirm.test.js
  components/modal/confirm.tsx
  components/modal/index.en-US.md
  components/modal/index.tsx
  components/modal/index.zh-CN.md
  components/notification/__tests__/index.test.js
  components/notification/index.en-US.md
  components/notification/index.tsx
  components/notification/index.zh-CN.md
  docs/react/faq.en-US.md
  docs/react/faq.zh-CN.md
Labels: PR: reviewed-approved

#29309 fix: update snapshot
  components/typography/__tests__/__snapshots__/demo.test.js.snap
Labels: PR: unreviewed

#29308 chore(slider): optimize tooltip align
  components/slider/SliderTooltip.tsx
Labels: PR: unreviewed

#29307 feat: new antd-colors, smaller size
  package.json
Labels: PR: unreviewed

#29300 docs(✨): release changelog 4.12.3
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: PR: unreviewed

#29288 feat: add api for transfer
  components/transfer/__tests__/__snapshots__/demo.test.js.snap
  components/transfer/__tests__/index.test.js
  components/transfer/demo/advanced.md
  components/transfer/index.en-US.md
  components/transfer/index.tsx
  components/transfer/index.zh-CN.md
  components/transfer/list.tsx
Labels: PR: unreviewed

#29450 branch: merge master into feature
  .github/workflows/issue-check-inactive.yml
  .github/workflows/issue-close-require.yml
  .github/workflows/issue-remove-inactive.yml
  .github/workflows/pr-check-ci.yml
  .github/workflows/rebase.yml
  components/affix/__tests__/Affix.test.tsx
  components/dropdown/demo/arrow.md
  components/dropdown/demo/basic.md
  components/dropdown/demo/item.md
  components/dropdown/demo/placement.md
  components/dropdown/demo/trigger.md
  components/dropdown/style/index.less
  components/layout/Sider.tsx
  components/select/style/multiple.less
  package.json
Labels: BranchAutoMerge

#29530 chore: Feature merge master
  components/config-provider/__tests__/__snapshots__/components.test.js.snap
  components/form/__tests__/__snapshots__/demo.test.js.snap
  components/input-number/__tests__/__snapshots__/demo.test.js.snap
  components/input-number/__tests__/__snapshots__/index.test.js.snap
  components/input-number/__tests__/index.test.js
  components/input-number/demo/digit.md
  components/input-number/demo/keyboard.md
  components/input-number/demo/out-of-range.md
  components/input-number/index.en-US.md
  components/input-number/index.tsx
  components/input-number/index.zh-CN.md
  components/input-number/style/index.less
  components/input/__tests__/__snapshots__/demo.test.js.snap
  components/slider/__tests__/__snapshots__/demo.test.js.snap
  components/transfer/__tests__/__snapshots__/demo.test.js.snap
  components/transfer/__tests__/index.test.js
  components/transfer/demo/advanced.md
  components/transfer/index.en-US.md
  components/transfer/index.tsx
  components/transfer/index.zh-CN.md
  components/transfer/list.tsx
  components/upload/Upload.tsx
  components/upload/__tests__/upload.test.js
  components/upload/__tests__/uploadlist.test.js
  components/upload/demo/upload-png-only.md
  components/upload/interface.tsx
  components/upload/useFreshState.ts
  components/upload/utils.tsx
  package.json
  typings/custom-typings.d.ts
Labels: BranchAutoMerge
