Repository ant-design/ant-design, pull requests merged in 2022-12, with the labels that each got.

#39132 chore(site): support for opening debug component demos
  .dumi/theme/slots/Content/index.tsx
Labels: codeball:needs-review

#39100 fix(steps): fix steps style
  components/steps/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/steps/__tests__/__snapshots__/demo.test.ts.snap
  components/steps/demo/progress-debug.tsx
  components/steps/style/progress.ts
Labels: codeball:needs-careful-review

#39103 fix(steps): fix steps style
  components/steps/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/steps/__tests__/__snapshots__/demo.test.ts.snap
  components/steps/demo/progress-debug.md
  components/steps/style/progress.less
  components/steps/style/rtl.less
  components/steps/style/vertical.less
Labels: codeball:needs-careful-review

#39138 site: fix site error
  .dumi/hooks/useMenu.tsx
  .dumi/pages/index/components/BannerRecommends.tsx
  .dumi/pages/index/components/RecommendsOld.tsx
  .dumi/theme/builtins/ComponentOverview/index.tsx
  .dumi/theme/builtins/Previewer/index.jsx
  .dumi/theme/builtins/ResourceArticles/index.tsx
  .dumi/theme/builtins/ResourceCards/index.tsx
  .dumi/theme/common/CommonHelmet.tsx
  .dumi/theme/layouts/DocLayout/index.tsx
  .dumi/theme/layouts/ResourceLayout/index.tsx
  .dumi/theme/slots/Content/index.tsx
  .dumi/theme/slots/Header/index.tsx
  .dumi/theme/utils.tsx
Labels: codeball:needs-review

#39140 type: demo type enhance
  components/tree/demo/draggable.tsx
  components/tree/demo/search.tsx
Labels: codeball:approved

#39060 refactor(type): replace interface with type for export component
  components/breadcrumb/BreadcrumbItem.tsx
  components/breadcrumb/BreadcrumbSeparator.tsx
  components/collapse/Collapse.tsx
  components/dropdown/dropdown-button.tsx
  components/dropdown/dropdown.tsx
  components/empty/index.tsx
  components/form/FormItem/index.tsx
  components/form/index.tsx
  components/pagination/Select.tsx
  components/skeleton/Skeleton.tsx
  components/statistic/Countdown.tsx
  components/statistic/Statistic.tsx
Labels: codeball:needs-review

#39078 fix(Transfer): clicking the checkbox position cannot be unchecked and onSelectChange is triggered twice
  components/checkbox/style/index.tsx
Labels: codeball:needs-review

#39027 style: popconfirm icon position regression
  components/popover/style/index.less
Labels: codeball:needs-review

#39042 docs: fix server/client mismatch hydrate error
  .dumi/theme/plugin.ts
Labels: codeball:needs-review

#39152 fix: fixed the value of color.hex when border-radius is changed
  components/config-provider/demo/theme.tsx
Labels: codeball:needs-review

#39150 docs: remove axure link
  docs/resources.en-US.md
  docs/resources.zh-CN.md
Labels: codeball:needs-review

#39153 docs: fix hydration
  .dumi/theme/layouts/DocLayout/index.tsx
  .dumi/theme/layouts/GlobalLayout.tsx
  .dumi/theme/plugin.ts
Labels: codeball:needs-review

#39154 refactor: bump rc-input-number
  components/input-number/index.tsx
  package.json
Labels: codeball:needs-review

#39155 chore: use startTransition to avoid affecting hydration
  .dumi/theme/layouts/GlobalLayout.tsx
  .dumi/theme/slots/ThemeContext.tsx
Labels: codeball:needs-review

#39121 fix: textarea attr(data-count) style
  components/input/style/index.tsx
Labels: codeball:needs-careful-review

#39165 fix(radio): fix disabled status check style
  components/radio/style/index.tsx
Labels: codeball:needs-review

#39182 fix: fix Badge Wave borderColor error
  components/badge/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/badge/__tests__/__snapshots__/demo.test.ts.snap
  components/badge/index.tsx
  components/badge/style/index.tsx
Labels: codeball:needs-careful-review

#39191 docs: fix demo card icons color
  .dumi/theme/builtins/Previewer/index.jsx
  .dumi/theme/common/GlobalStyles.tsx
  package.json
Labels: codeball:needs-review

#39201 docs: Add more desc & warning
  components/drawer/__tests__/Drawer.test.tsx
  components/drawer/demo/render-in-current.md
  components/drawer/index.tsx
Labels: codeball:needs-review

#39213 docs: Update index.zh-CN.md
  components/overview/index.zh-CN.md
Labels: codeball:approved

#39210 fix(Card): fix card actions' style
  components/card/style/index.tsx
Labels: codeball:needs-review

#39216 🤖 TEST: Use bundlesize2 instead
  package.json
Labels: codeball:approved

#39207 chore(Drawer): Improve warning message wording and demo doc
  components/drawer/__tests__/Drawer.test.tsx
  components/drawer/demo/render-in-current.md
  components/drawer/index.tsx
Labels: codeball:needs-careful-review

#39224 site: fix theme-editor link
  docs/react/customize-theme.en-US.md
  docs/react/customize-theme.zh-CN.md
Labels: codeball:needs-review

#39220 chore: enable bundlesize github checks
  package.json
Labels: codeball:needs-review

#39225 docs: fix extra line in index.md
  components/time-picker/index.en-US.md
  components/time-picker/index.zh-CN.md
Labels: codeball:approved

#39228 style: fix TimePicker panel style inside RangePicker
  components/date-picker/style/index.tsx
Labels: codeball:approved

#38802 docs: improve preview interaction
  .dumi/pages/index/components/Theme/ColorPicker.tsx
  .dumi/pages/index/components/Theme/ThemePicker.tsx
Labels: codeball:needs-careful-review

#39235 fix: Dropdown sub-menu missing motion
  .dumi/theme/slots/Footer/AdditionalInfo.tsx
  components/dropdown/style/index.tsx
Labels: codeball:needs-review

#39236 docs: fix table drag demo style is incorrect in codesandbox
  components/table/demo/drag-sorting.md
Labels: codeball:needs-review

#39209 chore(tree): remove flex style
  components/tree/style/index.tsx
Labels: codeball:needs-careful-review

#39249 style(Modal): Adopt a better way to break lines
  components/modal/style/index.tsx
Labels: codeball:needs-careful-review

#39242 chore: update tree snapshot
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/space/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/table/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/transfer/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/transfer/__tests__/__snapshots__/demo.test.ts.snap
  components/tree-select/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tree-select/__tests__/__snapshots__/index.test.tsx.snap
  components/tree/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tree/__tests__/__snapshots__/demo.test.ts.snap
  components/tree/__tests__/__snapshots__/directory.test.tsx.snap
  components/tree/__tests__/__snapshots__/index.test.tsx.snap
  package.json
Labels: codeball:needs-careful-review

#39254 chore: feature merge master
  .dumi/pages/index/components/Theme/ColorPicker.tsx
  .dumi/pages/index/components/Theme/ThemePicker.tsx
  .dumi/theme/builtins/Previewer/index.jsx
  .dumi/theme/common/GlobalStyles.tsx
  .dumi/theme/slots/Footer/AdditionalInfo.tsx
  components/card/style/index.tsx
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/date-picker/style/index.tsx
  components/drawer/__tests__/Drawer.test.tsx
  components/drawer/demo/render-in-current.md
  components/drawer/index.tsx
  components/dropdown/style/index.tsx
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/modal/style/index.tsx
  components/overview/index.zh-CN.md
  components/space/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/table/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/table/demo/drag-sorting.md
  components/time-picker/index.en-US.md
  components/time-picker/index.zh-CN.md
  components/transfer/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/transfer/__tests__/__snapshots__/demo.test.ts.snap
  components/tree-select/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tree-select/__tests__/__snapshots__/index.test.tsx.snap
  components/tree/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tree/__tests__/__snapshots__/demo.test.ts.snap
  components/tree/__tests__/__snapshots__/directory.test.tsx.snap
  components/tree/__tests__/__snapshots__/index.test.tsx.snap
  components/tree/style/index.tsx
  docs/react/customize-theme.en-US.md
  docs/react/customize-theme.zh-CN.md
  package.json
Labels: BranchAutoMerge, codeball:needs-careful-review

#39248 fix(Message): fix message RTL display location error
  components/message/style/index.tsx
Labels: codeball:needs-review

#39245 test: fix argo-ci skipped demo
  components/image/__tests__/image.test.ts
  tests/shared/demoTest.tsx
  tests/shared/imageTest.tsx
Labels: codeball:needs-review

#39257 chore: merge master into feature
  components/image/__tests__/image.test.ts
  components/message/style/index.tsx
  tests/shared/demoTest.tsx
  tests/shared/imageTest.tsx
Labels: BranchAutoMerge, codeball:needs-careful-review

#39255 docs: update Layout demo
  components/layout/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/layout/__tests__/__snapshots__/demo.test.ts.snap
  components/layout/demo/basic.md
  components/layout/demo/custom-trigger-debug.tsx
  components/layout/demo/custom-trigger.md
  components/layout/demo/custom-trigger.tsx
  components/layout/demo/fixed-sider.md
  components/layout/demo/fixed-sider.tsx
  components/layout/demo/fixed.md
  components/layout/demo/fixed.tsx
  components/layout/demo/responsive.md
  components/layout/demo/responsive.tsx
  components/layout/demo/side.md
  components/layout/demo/side.tsx
  components/layout/demo/top-side-2.md
  components/layout/demo/top-side-2.tsx
  components/layout/demo/top-side.md
  components/layout/demo/top-side.tsx
  components/layout/demo/top.md
  components/layout/demo/top.tsx
  components/layout/index.en-US.md
  components/layout/index.zh-CN.md
Labels: codeball:needs-careful-review

#38948 feat: New Component QRCode
  components/__tests__/__snapshots__/index.test.ts.snap
  components/index.tsx
  components/locale-provider/index.tsx
  components/locale/en_US.tsx
  components/locale/zh_CN.tsx
  components/mentions/index.en-US.md
  components/qrcode/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/qrcode/__tests__/__snapshots__/demo.test.ts.snap
  components/qrcode/__tests__/__snapshots__/index.test.tsx.snap
  components/qrcode/__tests__/demo-extend.test.ts
  components/qrcode/__tests__/demo.test.ts
  components/qrcode/__tests__/image.test.ts
  components/qrcode/__tests__/index.test.tsx
  components/qrcode/demo/Popover.md
  components/qrcode/demo/Popover.tsx
  components/qrcode/demo/base.md
  components/qrcode/demo/base.tsx
  components/qrcode/demo/customColor.md
  components/qrcode/demo/customColor.tsx
  components/qrcode/demo/customSize.md
  components/qrcode/demo/customSize.tsx
  components/qrcode/demo/download.md
  components/qrcode/demo/download.tsx
  components/qrcode/demo/errorlevel.md
  components/qrcode/demo/errorlevel.tsx
  components/qrcode/demo/icon.md
  components/qrcode/demo/icon.tsx
  components/qrcode/demo/status.md
  components/qrcode/demo/status.tsx
  components/qrcode/index.en-US.md
  components/qrcode/index.tsx
  components/qrcode/index.zh-CN.md
  components/qrcode/interface.ts
  components/qrcode/style/index.ts
  components/theme/interface/components.ts
  components/theme/themes/seed.ts
  components/theme/util/alias.ts
  components/theme/util/getAlphaColor.ts
  components/tour/style/index.tsx
  package.json
  tests/__snapshots__/index.test.ts.snap
Labels: codeball:needs-careful-review

#39262 fix(switch): only one of the two props `checkedChildren` or `unCheckedChildren` will not work
  components/switch/style/index.tsx
Labels: codeball:needs-review

#39241 fix: use before to avoid conflict with primary basic animation effect
  components/button/style/index.tsx
Labels: codeball:needs-careful-review

#39266 style: fix RangePicker hover range style
  .dumi/theme/slots/Footer/index.tsx
  components/date-picker/style/index.tsx
Labels: codeball:approved

#39268 chore: fix size-limit action
  .github/workflows/compressed-size.yml
  .github/workflows/size-limit.yml
  package.json
Labels: codeball:needs-careful-review

#39261 chore: remove useless node_modules
  .dumi/theme/builtins/Previewer/fromDumiProps.tsx
  package.json
Labels: codeball:needs-careful-review

#39277 chore: merge master to feature
  .dumi/theme/builtins/Previewer/fromDumiProps.tsx
  .dumi/theme/slots/Footer/AdditionalInfo.tsx
  .dumi/theme/slots/Footer/index.tsx
  .github/workflows/compressed-size.yml
  .github/workflows/size-limit.yml
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/button/index.zh-CN.md
  components/button/style/index.tsx
  components/date-picker/style/index.tsx
  components/layout/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/layout/__tests__/__snapshots__/demo.test.ts.snap
  components/layout/demo/basic.md
  components/layout/demo/custom-trigger-debug.tsx
  components/layout/demo/custom-trigger.md
  components/layout/demo/custom-trigger.tsx
  components/layout/demo/fixed-sider.md
  components/layout/demo/fixed-sider.tsx
  components/layout/demo/fixed.md
  components/layout/demo/fixed.tsx
  components/layout/demo/responsive.md
  components/layout/demo/responsive.tsx
  components/layout/demo/side.md
  components/layout/demo/side.tsx
  components/layout/demo/top-side-2.md
  components/layout/demo/top-side-2.tsx
  components/layout/demo/top-side.md
  components/layout/demo/top-side.tsx
  components/layout/demo/top.md
  components/layout/demo/top.tsx
  components/layout/index.en-US.md
  components/layout/index.zh-CN.md
  components/mentions/demo/render-panel.tsx
  components/switch/style/index.tsx
  components/tree/style/index.tsx
  package.json
Labels: BranchAutoMerge, codeball:needs-careful-review

#39275 docs: fix Grid demo slider tooltip
  components/grid/demo/playground.tsx
Labels: codeball:needs-careful-review

#39280 fix: he-il mistakes
  components/locale/he_IL.tsx
Labels: codeball:needs-review

#39267 docs: 4.24.5 changelog
  .github/workflows/compressed-size.yml
  .github/workflows/size-limit.yml
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/space/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/table/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/transfer/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/transfer/__tests__/__snapshots__/demo.test.ts.snap
  components/tree-select/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tree-select/__tests__/__snapshots__/index.test.tsx.snap
  components/tree/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tree/__tests__/__snapshots__/demo.test.ts.snap
  components/tree/__tests__/__snapshots__/directory.test.tsx.snap
  components/tree/__tests__/__snapshots__/index.test.tsx.snap
  package.json
Labels: codeball:needs-careful-review

#39285 chore: simpify size-limit output
  .github/workflows/size-limit.yml
  package.json
Labels: codeball:needs-review

#39282 fix: fix style error
  components/float-button/style/index.tsx
Labels: codeball:needs-review

#39292 fix: Tree selection style missing
  components/tree/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tree/__tests__/__snapshots__/demo.test.ts.snap
  components/tree/demo/block-node.tsx
  components/tree/index.en-US.md
  components/tree/index.zh-CN.md
  components/tree/style/index.tsx
Labels: codeball:needs-careful-review

#39297 docs: correct types
  components/checkbox/index.en-US.md
  components/checkbox/index.zh-CN.md
Labels: codeball:needs-review

#39299 fix: Select search style
  components/select/style/single.tsx
Labels: codeball:approved

#39046 feat : new components app
  components/__tests__/__snapshots__/index.test.ts.snap
  components/app/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/app/__tests__/__snapshots__/demo.test.ts.snap
  components/app/__tests__/__snapshots__/index.test.tsx.snap
  components/app/__tests__/demo-extend.test.ts
  components/app/__tests__/demo.test.ts
  components/app/__tests__/image.test.ts
  components/app/__tests__/index.test.tsx
  components/app/context.ts
  components/app/demo/message.md
  components/app/demo/message.tsx
  components/app/demo/modal.md
  components/app/demo/modal.tsx
  components/app/demo/notification.md
  components/app/demo/notification.tsx
  components/app/index.en-US.md
  components/app/index.tsx
  components/app/index.zh-CN.md
  components/app/style/index.tsx
  components/index.tsx
  components/style/index.tsx
  components/theme/interface/components.ts
  components/theme/util/genComponentStyleHook.ts
  tests/__snapshots__/index.test.ts.snap
  tests/shared/imageTest.tsx
Labels: codeball:needs-careful-review

#39305 type: TypeScript definition optimization
  components/anchor/Anchor.tsx
  components/anchor/AnchorLink.tsx
  components/anchor/index.en-US.md
  components/anchor/index.zh-CN.md
Labels: codeball:needs-review

#39290 docs: remove v3 to v4 migration docs
  components/auto-complete/index.en-US.md
  components/auto-complete/index.zh-CN.md
  components/breadcrumb/index.en-US.md
  components/breadcrumb/index.zh-CN.md
  components/dropdown/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/dropdown/__tests__/__snapshots__/demo.test.ts.snap
  components/dropdown/demo/deprecated.md
  components/dropdown/demo/deprecated.tsx
  components/dropdown/index.en-US.md
  components/dropdown/index.zh-CN.md
  components/form/index.en-US.md
  components/form/index.zh-CN.md
  components/form/v3.en-US.md
  components/form/v3.zh-CN.md
  components/menu/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/menu/__tests__/__snapshots__/demo.test.ts.snap
  components/menu/demo/deprecated.md
  components/menu/demo/deprecated.tsx
  components/menu/index.en-US.md
  components/menu/index.zh-CN.md
  components/steps/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/steps/__tests__/__snapshots__/demo.test.ts.snap
  components/steps/demo/deprecated.md
  components/steps/demo/deprecated.tsx
  components/steps/index.en-US.md
  components/steps/index.zh-CN.md
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/tabs/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tabs/__tests__/__snapshots__/demo.test.ts.snap
  components/tabs/demo/deprecated.md
  components/tabs/demo/deprecated.tsx
  components/tabs/index.en-US.md
  components/tabs/index.zh-CN.md
Labels: codeball:needs-careful-review

#39314 chore: unify useContext usage
  components/cascader/index.tsx
  components/checkbox/Checkbox.tsx
  components/checkbox/index.en-US.md
  components/checkbox/index.zh-CN.md
  components/form/FormItem/index.tsx
  components/image/index.tsx
  components/input-number/index.tsx
  components/radio/radio.tsx
  components/select/index.tsx
  components/tree-select/index.tsx
Labels: codeball:needs-careful-review

#39311 style: fix Popover width in rtl mode
  components/popover/style/index.tsx
Labels: codeball:approved

#39334 fix: Divider horizontal line align
  components/divider/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/divider/__tests__/__snapshots__/demo.test.ts.snap
  components/divider/demo/customize-style.md
  components/divider/style/index.less
Labels: codeball:needs-review

#39338 chore: update size-limit.yml
  .github/workflows/size-limit.yml
Labels: codeball:needs-review

#39339 fix: Divider horizontal line align
  components/divider/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/divider/__tests__/__snapshots__/demo.test.ts.snap
  components/divider/demo/customize-style.tsx
  components/divider/style/index.tsx
Labels: codeball:needs-review

#39352 fix: Tabs active bar missing
  package.json
Labels: codeball:approved

#39355 refactoring: jsx => tsx
  .dumi/theme/builtins/Palette/index.tsx
  .dumi/theme/common/BrowserFrame.jsx
  .dumi/theme/common/BrowserFrame.tsx
  .dumi/theme/common/CodePenIcon.tsx
  .dumi/theme/common/CodePreview.tsx
  .dumi/theme/common/CodeSandboxIcon.tsx
  .dumi/theme/common/Color/ColorBlock.tsx
  .dumi/theme/common/Color/ColorPaletteTool.tsx
  .dumi/theme/common/Color/ColorPaletteToolDark.tsx
  .dumi/theme/common/Color/ColorPalettes.jsx
  .dumi/theme/common/Color/ColorPalettes.tsx
  .dumi/theme/common/Color/ColorPatterns.tsx
  .dumi/theme/common/Color/ColorPicker.tsx
  .dumi/theme/common/Color/ColorStyle.tsx
  .dumi/theme/common/Color/Palette.tsx
  .dumi/theme/common/ExternalLinkIcon.tsx
  .dumi/theme/common/PrevAndNext.tsx
  .dumi/theme/common/RiddleIcon.tsx
  .dumi/theme/common/ThemeSwitch/ThemeIcon.tsx
  .dumi/theme/common/ThemeSwitch/index.tsx
Labels: codeball:needs-review

#39157 fix: disable button focus style in Space.Compact
  components/button/style/index.tsx
  components/date-picker/style/index.tsx
  components/select/style/index.tsx
  components/style/compact-item.tsx
Labels: codeball:needs-careful-review

#39312 ci: update site-deploy.yml
  .github/workflows/site-deploy.yml
Labels: skip-verify-files, codeball:needs-careful-review

#39360 refactoring: jsx => tsx
  .dumi/theme/builtins/ImagePreview/index.tsx
Labels: codeball:approved

#39351 docs: Table文档size参数不正确
  components/table/index.en-US.md
  components/table/index.zh-CN.md
Labels: codeball:approved

#39359 chore: fix size SSG hydration bug
  .dumi/theme/builtins/Previewer/fromDumiProps.tsx
  .dumi/theme/builtins/Previewer/index.jsx
Labels: codeball:needs-review

#39363 docs: update theme editor
  .dumi/pages/theme-editor/index.tsx
  components/theme/interface/seeds.ts
  scripts/generate-token-meta.js
Labels: codeball:needs-careful-review

#39048 feat: Modal.xxx supports footer
  components/modal/ConfirmDialog.tsx
  components/modal/Modal.tsx
  components/modal/__tests__/confirm.test.tsx
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
Labels: codeball:needs-careful-review

#39348 site: update docs styles
  .dumi/theme/builtins/ColorChunk/index.tsx
  .dumi/theme/builtins/TokenTable/index.tsx
  docs/react/customize-theme.en-US.md
  docs/react/customize-theme.zh-CN.md
  docs/react/migration-v5.en-US.md
  docs/react/migration-v5.zh-CN.md
Labels: codeball:needs-careful-review

#39379 docs: note for getContainer
  .gitignore
  components/drawer/index.en-US.md
  components/drawer/index.zh-CN.md
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
Labels: codeball:needs-review

#39383 refactoring: jsx => tsx
  .dumi/theme/builtins/Previewer/index.tsx
Labels: codeball:needs-review

#39380 docs: fix components api table
  components/table/index.zh-CN.md
  components/tabs/index.en-US.md
  components/tree/index.zh-CN.md
Labels: codeball:approved

#39392 chore: remove unused devDeps
  .dumi/theme/builtins/Previewer/fromDumiProps.tsx
  .dumi/theme/static/style.js
  package.json
  typings/custom-typings.d.ts
Labels: codeball:needs-review

#39250 feat(popconfirm): make title bold and add description prop
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
  components/popconfirm/PurePanel.tsx
  components/popconfirm/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/popconfirm/__tests__/__snapshots__/demo.test.ts.snap
  components/popconfirm/demo/async.tsx
  components/popconfirm/demo/basic.md
  components/popconfirm/demo/basic.tsx
  components/popconfirm/demo/dynamic-trigger.tsx
  components/popconfirm/demo/icon.tsx
  components/popconfirm/demo/locale.tsx
  components/popconfirm/demo/placement.tsx
  components/popconfirm/demo/promise.tsx
  components/popconfirm/demo/render-panel.tsx
  components/popconfirm/index.en-US.md
  components/popconfirm/index.tsx
  components/popconfirm/index.zh-CN.md
  components/popconfirm/style/index.tsx
Labels: codeball:needs-careful-review

#39395 chore: fix code box icons cannot display in Safari
  .dumi/theme/common/styles/Demo.tsx
Labels: codeball:approved

#39399 docs: Update Blog
  .dumi/hooks/useMenu.tsx
  .dumi/theme/slots/Content/index.tsx
  .dumi/theme/slots/Header/Navigation.tsx
  docs/blog/css-in-js.en-US.md
  docs/blog/css-in-js.zh-CN.md
  docs/blog/getContainer.en-US.md
  docs/blog/getContainer.zh-CN.md
Labels: codeball:needs-careful-review

#39398 chore: improve ThemeSwitcher implementation
  .dumi/theme/builtins/Previewer/fromDumiProps.tsx
  .dumi/theme/common/ThemeSwitch/ThemeIcon.tsx
  .dumi/theme/common/ThemeSwitch/index.tsx
  .dumi/theme/layouts/GlobalLayout.tsx
Labels: codeball:needs-review

#39401 docs: changelog of 5.0.5
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: codeball:needs-review

#39064 feat: New Component Watermark
  .jest.js
  components/__tests__/__snapshots__/index.test.ts.snap
  components/index.tsx
  components/watermark/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/watermark/__tests__/__snapshots__/demo.test.ts.snap
  components/watermark/__tests__/__snapshots__/index.test.tsx.snap
  components/watermark/__tests__/demo-extend.test.ts
  components/watermark/__tests__/demo.test.ts
  components/watermark/__tests__/image.test.ts
  components/watermark/__tests__/index.test.tsx
  components/watermark/demo/basic.md
  components/watermark/demo/basic.tsx
  components/watermark/demo/custom.md
  components/watermark/demo/custom.tsx
  components/watermark/demo/image.md
  components/watermark/demo/image.tsx
  components/watermark/demo/multi-line.md
  components/watermark/demo/multi-line.tsx
  components/watermark/index.en-US.md
  components/watermark/index.tsx
  components/watermark/index.zh-CN.md
  components/watermark/useMutationObserver.ts
  package.json
  tests/__snapshots__/index.test.ts.snap
Labels: codeball:needs-careful-review

#39405 chore: code style optimization
  components/watermark/__tests__/index.test.tsx
  components/watermark/index.en-US.md
  components/watermark/index.tsx
  components/watermark/useMutationObserver.ts
  package.json
Labels: codeball:needs-careful-review

#39414 test: Optimize test cases
  components/watermark/__tests__/__snapshots__/index.test.tsx.snap
  components/watermark/__tests__/index.test.tsx
Labels: codeball:needs-review

#39412 ci: add latest for v5
  .github/workflows/release-helper.yml
Labels: codeball:needs-review

#39411 ci: add latest for v5
  .github/workflows/release-helper.yml
Labels: codeball:needs-review

#39422 chore: skip useless part
  .jest.js
Labels: codeball:needs-review

#39416 feat: Update fr_CA internationalization
  components/locale/fr_CA.tsx
Labels: codeball:needs-review

#39425 fix: floatButton tooltip should support number 0
  components/float-button/FloatButton.tsx
  components/float-button/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/float-button/__tests__/index.test.tsx
Labels: codeball:needs-careful-review

#39436 fix(Cascader): reset margin
  components/cascader/style/index.tsx
Labels: codeball:needs-review

#39421 ci(deploy-site): add manual trigger flow
  .github/workflows/site-deploy.yml
Labels: skip-verify-files, codeball:needs-review

#39431 chore: increase size limit
  package.json
Labels: codeball:needs-review

#39428 perf: token update
  components/input/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/input/__tests__/__snapshots__/demo.test.ts.snap
  components/input/demo/addon.md
  components/input/demo/addon.tsx
  components/input/style/index.tsx
  components/message/style/index.tsx
  components/radio/style/index.tsx
  components/select/style/index.tsx
  components/slider/style/index.tsx
  components/theme/interface/alias.ts
  components/theme/interface/index.ts
  components/theme/interface/maps/font.ts
  components/theme/interface/maps/index.ts
  components/theme/interface/maps/size.ts
  components/theme/themes/compact/index.ts
  components/theme/themes/default/index.ts
  components/theme/themes/shared/genCommonMapToken.ts
  components/theme/themes/shared/genFontMapToken.ts
  components/theme/util/alias.ts
Labels: codeball:needs-careful-review

#39435 chore: code style optimization
  components/watermark/index.tsx
Labels: codeball:approved

#39439 perf: menu style
  components/menu/style/index.tsx
Labels: codeball:approved

#39445 chore: increase size limit
  package.json
Labels: codeball:needs-review

#39446 docs: improve markdown table style
  .dumi/theme/common/styles/Markdown.tsx
Labels: codeball:approved

#39453 doc: fix typos
  docs/blog/css-in-js.zh-CN.md
Labels: codeball:approved

#39043 Adapt to the mobile mode of the new official website
  .dumi/pages/index/components/Banner.tsx
  .dumi/pages/index/components/BannerRecommends.tsx
  .dumi/pages/index/components/ComponentsList.tsx
  .dumi/pages/index/components/DesignFramework.tsx
  .dumi/pages/index/components/Group.tsx
  .dumi/pages/index/components/SiteContext.tsx
  .dumi/pages/index/components/Theme/MobileCarousel.tsx
  .dumi/pages/index/components/Theme/index.tsx
  .dumi/pages/index/components/images/topic.png
  .dumi/pages/index/components/util.tsx
  .dumi/pages/index/index.tsx
  .dumi/theme/slots/Footer/index.tsx
  package.json
Labels: codeball:needs-careful-review

#39475 docs: update demo
  .dumi/pages/theme-editor/index.tsx
  components/float-button/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/float-button/__tests__/__snapshots__/demo.test.ts.snap
  components/float-button/demo/group.tsx
Labels: codeball:needs-review

#39468 Fix the issue where the clear icon does not show when hovering over the Select series component under the Space component.
  components/button/style/index.tsx
  components/cascader/style/index.tsx
  components/date-picker/style/index.tsx
  components/input-number/style/index.tsx
  components/input/style/index.tsx
  components/select/style/index.tsx
  components/space/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/space/__tests__/__snapshots__/demo.test.ts.snap
  components/space/demo/compact.tsx
  components/style/compact-item-vertical.tsx
  components/style/compact-item.tsx
Labels: codeball:needs-careful-review

#39485 docs: trim in CHANGELOG.zh-CN.md
  CHANGELOG.zh-CN.md
Labels: codeball:needs-review

#39488 docs: Adjust Anchor demo
  components/anchor/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/anchor/__tests__/__snapshots__/demo.test.ts.snap
  components/anchor/demo/basic.tsx
  components/anchor/demo/targetOffset.tsx
  components/anchor/index.en-US.md
  components/anchor/index.zh-CN.md
Labels: codeball:needs-review

#39476 fix: radio align
  components/radio/style/index.tsx
Labels: codeball:needs-review

#39513 fix: Modal hooks not pass CP
  components/config-provider/index.tsx
  components/modal/__tests__/hook.test.tsx
  components/select/demo/basic.tsx
Labels: codeball:needs-review

#39478 type: remove tuple、tupleNum、ElementOf
  components/_util/colors.ts
  components/_util/motion.tsx
  components/_util/statusUtils.tsx
  components/_util/type.ts
  components/badge/utils.tsx
  components/button/button.tsx
  components/date-picker/generatePicker/index.tsx
  components/drawer/index.tsx
  components/dropdown/dropdown.tsx
  components/form/FormItem/index.tsx
  components/grid/row.tsx
  components/input/ClearableLabeledInput.tsx
  components/progress/progress.tsx
  components/spin/index.tsx
  components/table/interface.tsx
  components/tag/index.tsx
  components/tooltip/index.tsx
  components/transfer/ListBody.tsx
  components/typography/Title.tsx
Labels: codeball:needs-careful-review

#39464 feat: The watermark is staggered by default
  components/watermark/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/watermark/__tests__/__snapshots__/demo.test.ts.snap
  components/watermark/__tests__/__snapshots__/index.test.tsx.snap
  components/watermark/__tests__/index.test.tsx
  components/watermark/demo/custom.tsx
  components/watermark/index.en-US.md
  components/watermark/index.tsx
  components/watermark/index.zh-CN.md
  components/watermark/useMutationObserver.ts
  components/watermark/utils.ts
Labels: codeball:needs-careful-review

#39524 docs: update Table async demo
  components/table/demo/ajax.tsx
Labels: codeball:needs-review

#39527 docs: add vite locale docs
  components/config-provider/index.en-US.md
  components/config-provider/index.zh-CN.md
Labels: codeball:needs-review

#39455 fix(Table): unexpected horizontal scroll bar
  components/table/style/bordered.tsx
Labels: codeball:needs-review

#39463 fix: Slider tooltip missing animation (#38492)
  components/style/motion/zoom.tsx
  components/tooltip/style/index.tsx
Labels: codeball:needs-careful-review

#39508 fix: Move antd-token-previewer to dev dependencies
  package.json
Labels: codeball:approved

#39539 docs: update API describe
  components/anchor/index.en-US.md
  components/anchor/index.zh-CN.md
Labels: codeball:needs-review

#39535 📝 docs: 5.0.7 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
  scripts/post-script.js
Labels: codeball:needs-review

#39547 docs: Add FAQ about why api should be less
  docs/react/faq.en-US.md
  docs/react/faq.zh-CN.md
Labels: codeball:needs-review

#39501 feat[float-button]: add clickOutAutoClose feature
  components/float-button/FloatButtonGroup.tsx
  components/float-button/__tests__/group.test.tsx
Labels: codeball:needs-careful-review

#39550 chore: Select `virtual=false` will bind to real element for a11y
  components/calendar/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/list/__tests__/__snapshots__/pagination.test.tsx.snap
  components/pagination/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/select/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/select/index.en-US.md
  components/select/index.zh-CN.md
  components/table/__tests__/__snapshots__/demo-extend.test.ts.snap
  package.json
Labels: codeball:needs-careful-review

#39347 feat: update app demo
  components/app/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/app/__tests__/__snapshots__/demo.test.ts.snap
  components/app/demo/basic.md
  components/app/demo/basic.tsx
  components/app/demo/message.md
  components/app/demo/message.tsx
  components/app/demo/modal.md
  components/app/demo/modal.tsx
  components/app/demo/notification.md
  components/app/demo/notification.tsx
  components/app/index.en-US.md
  components/app/index.zh-CN.md
Labels: codeball:needs-careful-review

#39566 docs: Tree conduction
  docs/blog/check-conduct.en-US.md
  docs/blog/check-conduct.zh-CN.md
Labels: codeball:needs-review

#39554 fix: add img cdn link for site
  .dumi/pages/index/components/Banner.tsx
  .dumi/pages/index/components/images/topic.png
Labels: codeball:approved

#39553 type: add FloatButtonGroupProps
  components/index.tsx
Labels: codeball:approved

#39575 fix: segmented icon margin
  components/segmented/style/index.tsx
Labels: codeball:approved

#39572 doc: Update app
  components/app/context.ts
  components/app/demo/basic.md
  components/app/index.en-US.md
Labels: codeball:needs-review

#39561 fix: Drawer should close if open is false
  components/drawer/index.tsx
  package.json
Labels: codeball:needs-review

#39576 demo: update demo
  components/float-button/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/float-button/__tests__/__snapshots__/demo.test.ts.snap
  components/float-button/demo/group-menu.md
  components/float-button/demo/group-menu.tsx
  components/float-button/demo/shape.md
  components/float-button/demo/shape.tsx
  components/float-button/demo/tooltip.md
  components/float-button/demo/type.md
Labels: codeball:needs-review

#39534 site: icon update
  .dumi/theme/common/ThemeSwitch/index.tsx
  .dumi/theme/utils.tsx
Labels: codeball:needs-careful-review

#39105 Make breakpoints use the token feature
  components/_util/__tests__/responsiveObserve.test.ts
  components/_util/__tests__/responsiveObserve.test.tsx
  components/_util/responsiveObserve.ts
  components/descriptions/index.tsx
  components/grid/__tests__/index.test.tsx
  components/grid/demo/responsive.md
  components/grid/hooks/useBreakpoint.tsx
  components/grid/row.tsx
Labels: codeball:needs-careful-review

#39580 docs: Add Form prefix demo
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/form/__tests__/__snapshots__/demo.test.ts.snap
  components/form/demo/form-item-path.md
  components/form/demo/form-item-path.tsx
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: codeball:needs-review

#39533 type: Button type optimization
  components/_util/ActionButton.tsx
  components/button/button.tsx
  components/button/index.en-US.md
  components/button/index.zh-CN.md
  components/dropdown/dropdown-button.tsx
  components/modal/Modal.tsx
  components/modal/PurePanel.tsx
  components/popconfirm/PurePanel.tsx
  components/select/demo/custom-dropdown-menu.tsx
  components/transfer/operation.tsx
Labels: codeball:needs-careful-review

#39599 chore: remove lodash/isEqual
  components/table/hooks/useFilter/FilterDropdown.tsx
Labels: codeball:approved

#39602 chore: remove lodash/debounce
  components/spin/__tests__/delay.test.tsx
  components/spin/index.tsx
  package.json
Labels: codeball:needs-careful-review

#39514 chore(date-picker): remove non-null assertion
  components/date-picker/generatePicker/generateRangePicker.tsx
Labels: codeball:needs-review

#39456 fix: disabled style miss when has href on Button
  components/button/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/button/__tests__/__snapshots__/demo.test.ts.snap
  components/button/button.tsx
  components/button/demo/disabled.tsx
  components/button/style/index.tsx
Labels: codeball:needs-careful-review

#39565 docs: Add FAQ about `@line-height-base`
  docs/react/faq.en-US.md
  docs/react/faq.zh-CN.md
Labels: codeball:approved

#39617 chore: fix terser
  package.json
  tests/shared/demoTest.tsx
Labels: codeball:needs-review

#39634 feat: @ant-design/react-slick upgrade
  package.json
Labels: codeball:needs-review

#39635 site: cc => fc
  .dumi/theme/common/Color/ColorBlock.tsx
  .dumi/theme/common/Color/ColorPaletteTool.tsx
  .dumi/theme/common/Color/ColorPaletteToolDark.tsx
  .dumi/theme/common/Color/ColorPicker.tsx
  components/button/__tests__/index.test.tsx
Labels: codeball:approved

#39382 fix: Fix tour step type
  components/tour/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tour/__tests__/__snapshots__/demo.test.ts.snap
  components/tour/__tests__/__snapshots__/index.test.tsx.snap
  components/tour/__tests__/index.test.tsx
  components/tour/index.tsx
  components/tour/panelRender.tsx
  components/tour/style/index.tsx
  package.json
Labels: codeball:needs-careful-review

#39504 chore(site): improve site
  .dumi/pages/index/components/Banner.tsx
  .dumi/pages/index/components/BannerRecommends.tsx
  .dumi/pages/index/components/ComponentsList.tsx
  .dumi/pages/index/components/DesignFramework.tsx
  .dumi/pages/index/components/Group.tsx
  .dumi/pages/index/components/SiteContext.tsx
  .dumi/pages/index/components/Theme/index.tsx
  .dumi/pages/index/index.tsx
  .dumi/theme/builtins/ComponentOverview/index.tsx
  .dumi/theme/builtins/Previewer/fromDumiProps.tsx
  .dumi/theme/builtins/Previewer/index.tsx
  .dumi/theme/common/ThemeSwitch/index.tsx
  .dumi/theme/layouts/DocLayout/index.tsx
  .dumi/theme/layouts/GlobalLayout.tsx
  .dumi/theme/slots/Header/SwitchBtn.tsx
  .dumi/theme/slots/Header/index.tsx
  .dumi/theme/slots/Sidebar/index.tsx
  .dumi/theme/slots/SiteContext.tsx
Labels: codeball:needs-careful-review

#39591 site: add blog about test library migration
  .dumi/theme/slots/Content/index.tsx
  docs/blog/check-conduct.en-US.md
  docs/blog/testing-migrate.en-US.md
  docs/blog/testing-migrate.zh-CN.md
Labels: codeball:needs-careful-review

#39457 format: site code format
  .dumi/hooks/useLocale.ts
  .dumi/pages/index-cn/index.ts
  .dumi/pages/index/components/SiteContext.ts
  .dumi/pages/index/components/util.ts
  .dumi/pages/theme-editor-cn/index.ts
  .dumi/theme/builtins/ColorPaletteTool/index.ts
  .dumi/theme/builtins/ColorPaletteToolDark/index.ts
  .dumi/theme/builtins/ColorPalettes/index.ts
  .dumi/theme/builtins/Palette/index.ts
  .dumi/theme/builtins/Previewer/index.tsx
  .dumi/theme/common/EditButton.tsx
  .dumi/theme/common/styles/BrowserMockup.tsx
  .dumi/theme/common/styles/Common.tsx
  .dumi/theme/common/styles/Demo.tsx
  .dumi/theme/common/styles/HeadingAnchor.tsx
  .dumi/theme/common/styles/Highlight.tsx
  .dumi/theme/common/styles/Icon.tsx
  .dumi/theme/common/styles/IconPickSearcher.tsx
  .dumi/theme/common/styles/Markdown.tsx
  .dumi/theme/common/styles/NProgress.tsx
  .dumi/theme/common/styles/PreviewImage.tsx
  .dumi/theme/common/styles/Reset.tsx
  .dumi/theme/common/styles/Responsive.tsx
  .dumi/theme/slots/DemoContext.ts
  .dumi/theme/slots/Header/interface.ts
  .dumi/theme/slots/SiteContext.ts
  .dumi/theme/static/style.ts
  .dumi/theme/utils.ts
Labels: codeball:needs-careful-review

#39626 fix: Optimize the custom-dropdown demo style
  components/dropdown/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/dropdown/demo/custom-dropdown.md
  components/dropdown/demo/custom-dropdown.tsx
Labels: codeball:needs-review

#39644 fix: update icon color token in Select
  components/cascader/style/index.tsx
  components/input/style/index.tsx
  components/select/style/index.tsx
Labels: codeball:approved

#39605 fix(component): badge auto width
  components/badge/style/index.tsx
Labels: codeball:needs-review

#39653 fix: Tabs inkBar in StrictMode
  components/card/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/card/__tests__/__snapshots__/demo.test.ts.snap
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/tabs/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tabs/__tests__/__snapshots__/demo.test.ts.snap
  components/tabs/__tests__/__snapshots__/index.test.tsx.snap
  package.json
Labels: codeball:needs-careful-review

#39649 docs: fix menu bg
  .dumi/theme/slots/Sidebar/index.tsx
Labels: codeball:needs-review

#39669 blog: add link for new component
  docs/blog/testing-migrate.en-US.md
  docs/blog/testing-migrate.zh-CN.md
Labels: codeball:needs-review

#39671 chore: add codeql
  .github/workflows/codeql.yml
  README.md
Labels: codeball:needs-review

#39686 docs: add table rowScope
  components/table/index.en-US.md
  components/table/index.zh-CN.md
Labels: codeball:needs-review

#39695 fix: App "two children with the same key" warning
  components/message/useMessage.tsx
  components/notification/useNotification.tsx
Labels: codeball:approved

#39683 docs: fix markdown table margin
  .dumi/theme/common/styles/Markdown.tsx
Labels: codeball:approved
