Repository ant-design/ant-design, pull requests merged in 2022-11, with the labels that each got.

#38431 fix: List key
  components/list/__tests__/Item.test.tsx
  components/list/index.tsx
Labels: codeball:needs-careful-review

#38488 fix: Result should hide icon when it is falsy
  components/result/__tests__/index.test.tsx
  components/result/index.tsx
Labels: codeball:approved

#38510 chore: type optimization
  components/_util/__tests__/util.test.tsx
  components/_util/__tests__/wave.test.tsx
  components/_util/wave.tsx
  components/config-provider/__tests__/form.test.tsx
  components/input/__tests__/focus.test.tsx
  components/layout/__tests__/index.test.tsx
  components/transfer/__tests__/list.test.tsx
  components/typography/__tests__/editable.test.tsx
  components/typography/__tests__/ellipsis.test.tsx
  components/upload/__tests__/uploadlist.test.tsx
  site/theme/template/Content/ComponentOverview.jsx
Labels: codeball:needs-review

#38512 chore ⚡️: add rome
  .husky/.gitignore
  .husky/pre-commit
  package.json
  rome.json
  scripts/check-version-md.js
Labels: codeball:needs-review

#38517 chore: format markdown by prettier
  package.json
Labels: codeball:needs-review

#38531 chore: upgrade rc-image to 5.12.0
  components/image/__tests__/__snapshots__/index.test.tsx.snap
  components/image/__tests__/index.test.tsx
  package.json
Labels: codeball:needs-review

#38528 chore: upgrade rc-menu to 9.7.2
  package.json
Labels: codeball:approved

#38533 chore: merge master to feature
  .circleci/config.yml
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/date-picker/__tests__/RangePicker.test.tsx
  components/date-picker/demo/select-in-range.md
  components/image/__tests__/__snapshots__/index.test.tsx.snap
  components/image/__tests__/index.test.tsx
  package.json
  scripts/print-changelog.js
  tests/shared/focusTest.tsx
Labels: BranchAutoMerge, codeball:needs-careful-review

#38535 docs: Optimized description
  components/auto-complete/index.zh-CN.md
  components/checkbox/index.zh-CN.md
  components/select/index.zh-CN.md
  components/switch/index.zh-CN.md
  components/tree-select/index.zh-CN.md
Labels: codeball:needs-review

#38536 chore: Next merge master
  .circleci/config.yml
  .github/workflows/codeball.yml
  .github/workflows/release-helper.yml
  .husky/.gitignore
  .husky/pre-commit
  .jest.js
  .jest.node.js
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/_util/__tests__/util.test.tsx
  components/_util/__tests__/wave.test.tsx
  components/_util/getRenderPropValue.ts
  components/_util/hooks/useSyncState.ts
  components/_util/wave/index.tsx
  components/auto-complete/index.zh-CN.md
  components/badge/ScrollNumber.tsx
  components/checkbox/index.zh-CN.md
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/config-provider/__tests__/form.test.tsx
  components/date-picker/__tests__/RangePicker.test.tsx
  components/dropdown/__tests__/dropdown-button.test.tsx
  components/dropdown/dropdown-button.tsx
  components/dropdown/dropdown.tsx
  components/image/__tests__/__snapshots__/index.test.tsx.snap
  components/image/__tests__/index.test.tsx
  components/input/__tests__/focus.test.tsx
  components/input/hooks/useRemovePasswordTimeout.ts
  components/layout/__tests__/index.test.tsx
  components/list/__tests__/Item.test.tsx
  components/list/index.tsx
  components/modal/useModal/index.tsx
  components/progress/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/progress/__tests__/__snapshots__/demo.test.ts.snap
  components/progress/__tests__/__snapshots__/index.test.tsx.snap
  components/progress/progress.tsx
  components/result/__tests__/index.test.tsx
  components/result/index.tsx
  components/steps/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/steps/__tests__/__snapshots__/demo.test.ts.snap
  components/steps/index.en-US.md
  components/switch/index.zh-CN.md
  components/timeline/Timeline.tsx
  components/transfer/__tests__/list.test.tsx
  components/tree-select/index.zh-CN.md
  components/typography/__tests__/editable.test.tsx
  components/typography/__tests__/ellipsis.test.tsx
  components/typography/hooks/useMergedConfig.ts
  components/typography/hooks/useUpdatedEffect.ts
  components/typography/style/index.tsx
  components/upload/__tests__/demo-extend.test.ts
  components/upload/__tests__/demo.test.ts
  components/upload/__tests__/uploadlist.test.tsx
  package.json
  rome.json
  scripts/check-version-md.js
  scripts/print-changelog.js
  tests/shared/focusTest.tsx
Labels: BranchAutoMerge, codeball:needs-careful-review

#38542 docs(Layout): update demo style to `sticky`
  components/layout/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/layout/__tests__/__snapshots__/demo.test.ts.snap
  components/layout/demo/fixed.md
Labels: codeball:needs-careful-review

#38540 fix: picker missing motion
  components/date-picker/style/index.tsx
Labels: codeball:approved

#38489 chore: remove `Slider` outline
  components/slider/style/index.tsx
Labels: codeball:needs-careful-review

#38546 docs: Update migration-v5.zh-CN.md #38544
  docs/react/migration-v5.en-US.md
  docs/react/migration-v5.zh-CN.md
Labels: codeball:needs-review

#38503 fix: checkbox trans in Firefox
  components/checkbox/style/index.tsx
  components/theme/interface.ts
  components/theme/themes/seed.ts
Labels: codeball:needs-review

#38547 fix: collapse end arrow rotate
  .dumi/theme/slots/Sidebar/index.tsx
  components/collapse/index.en-US.md
  components/collapse/index.zh-CN.md
  components/collapse/style/index.tsx
Labels: codeball:needs-review

#38543 chore: fix the wrong link address
  components/form/FormItem/index.tsx
  components/form/__tests__/index.test.tsx
Labels: codeball:needs-careful-review

#38550 chore: use prettier format less
  package.json
Labels: codeball:needs-review

#38551 docs: remove custom scrollbar style
  .dumi/theme/slots/Content/index.tsx
Labels: codeball:approved

#38556 docs: support for opening demos in a new window
  .dumi/theme/builtins/Previewer/index.jsx
  .dumi/theme/common/ExternalLinkIcon.jsx
  .dumi/theme/locales/en-US.json
  .dumi/theme/locales/zh-CN.json
Labels: codeball:needs-review

#38560 docs: use dumi helmet for pre-render
  .dumi/theme/builtins/ComponentOverview/index.tsx
  .dumi/theme/common/CommonHelmet.tsx
  .dumi/theme/common/Helmet.tsx
  .dumi/theme/layouts/DocLayout/index.tsx
Labels: codeball:needs-review

#38562 docs: Migration-v5.md div closing error
  docs/react/migration-v5.en-US.md
  docs/react/migration-v5.zh-CN.md
Labels: codeball:approved

#38563 chore: use prettier format json
  package.json
Labels: codeball:approved

#38565 chore: merge master to feature
  components/auto-complete/index.zh-CN.md
  components/checkbox/index.zh-CN.md
  components/form/FormItem/index.tsx
  components/form/__tests__/index.test.tsx
  components/layout/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/layout/__tests__/__snapshots__/demo.test.ts.snap
  components/layout/demo/fixed.md
  components/select/index.zh-CN.md
  components/switch/index.zh-CN.md
  components/tree-select/index.zh-CN.md
  package.json
Labels: BranchAutoMerge, codeball:needs-careful-review

#38567 fix: incorrect warning
  components/breadcrumb/Breadcrumb.tsx
  components/breadcrumb/BreadcrumbItem.tsx
  components/breadcrumb/__tests__/Breadcrumb.test.tsx
Labels: codeball:needs-review

#38569 chore: upgrade rc-tree-select to fix bundlesize
  package.json
Labels: codeball:needs-review

#38568 chore: fix typo
  components/breadcrumb/__tests__/Breadcrumb.test.tsx
  components/dropdown/__tests__/dropdown-button.test.tsx
Labels: codeball:approved

#38578 fix(Input.Search): pressing enter key don't trigger `onSearch` while …
  components/input/Search.tsx
  components/input/__tests__/Search.test.tsx
Labels: codeball:needs-review

#38572 docs: update site banner
  .dumi/hooks/useSiteToken.ts
  .dumi/pages/index/components/Banner.tsx
Labels: codeball:approved

#38583 fix: menu style missing
  components/menu/style/index.tsx
  components/menu/style/vertical.tsx
Labels: codeball:needs-review

#38584 feat(modal): support pass mousePosition to control modal's animation origin position
  components/modal/Modal.tsx
  components/modal/__tests__/Modal.test.tsx
  components/modal/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/modal/__tests__/__snapshots__/demo.test.ts.snap
  components/modal/demo/custom-mouse-position.md
Labels: codeball:needs-careful-review

#38582 fix: segmented dark mode
  components/segmented/style/index.tsx
Labels: codeball:approved

#38552 docs: fix site issue
  .dumi/theme/builtins/Alert/index.tsx
  .dumi/theme/builtins/ColorPaletteTool/index.tsx
  .dumi/theme/builtins/ColorPaletteToolDark/index.tsx
  .dumi/theme/builtins/ColorPalettes/index.tsx
  .dumi/theme/builtins/Palette/index.tsx
  .dumi/theme/common/Color/ColorBlock.jsx
  .dumi/theme/common/Color/ColorPaletteTool.jsx
  .dumi/theme/common/Color/ColorPaletteToolDark.jsx
  .dumi/theme/common/Color/ColorPalettes.jsx
  .dumi/theme/common/Color/ColorPatterns.jsx
  .dumi/theme/common/Color/ColorPicker.tsx
  .dumi/theme/common/Color/ColorStyle.tsx
  .dumi/theme/common/Color/Palette.jsx
  .dumi/theme/common/EditButton.tsx
  .dumi/theme/common/GlobalStyles.tsx
  .dumi/theme/common/Loading.tsx
  .dumi/theme/slots/Header/Logo.tsx
  .dumi/theme/slots/Header/Navigation.tsx
  components/breadcrumb/index.en-US.md
  components/breadcrumb/index.zh-CN.md
  components/dropdown/index.en-US.md
  components/dropdown/index.zh-CN.md
  components/menu/index.en-US.md
  components/menu/index.zh-CN.md
  components/steps/index.en-US.md
  components/steps/index.zh-CN.md
  components/switch/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/switch/__tests__/__snapshots__/demo.test.ts.snap
  components/switch/demo/text.tsx
  components/tabs/index.en-US.md
  components/tabs/index.zh-CN.md
  components/typography/index.en-US.md
  components/typography/index.zh-CN.md
  docs/spec/colors.en-US.md
  docs/spec/colors.zh-CN.md
  docs/spec/dark.en-US.md
  docs/spec/dark.zh-CN.md
  docs/spec/introduce.en-US.md
  docs/spec/introduce.zh-CN.md
  docs/spec/motion.en-US.md
  docs/spec/motion.zh-CN.md
  loading.js
Labels: codeball:needs-careful-review

#38585 fix(Table): don't trigger sort when pressing enter in filter dropdown
  components/table/__tests__/Table.sorter.test.tsx
  components/table/hooks/useFilter/FilterWrapper.tsx
Labels: codeball:approved

#38586 fix: Pass custom prefixCls to Typography from Base (#38580)
  components/typography/Base/index.tsx
  components/typography/__tests__/prefixCls.test.tsx
Labels: codeball:needs-careful-review

#38588 chore: Update .dumirc.ts
  .dumirc.ts
Labels: codeball:approved

#38589 chore: fix eslint OOM by ignoring server folder
  .eslintignore
  package.json
Labels: codeball:needs-review

#38591 chore: add ga & hotjar
  .dumirc.ts
Labels: codeball:needs-review

#38574 docs: remove ie support in introduction page
  README-ja_JP.md
  README-pt_BR.md
  README-sp_MX.md
  README-uk_UA.md
  README-zh_CN.md
  README.md
  docs/react/introduce.en-US.md
  docs/react/introduce.zh-CN.md
Labels: codeball:needs-careful-review

#38594 docs: update documentation
  .dumi/theme/slots/Footer/index.tsx
  docs/react/introduce.en-US.md
  docs/react/introduce.zh-CN.md
Labels: codeball:approved

#38597 fix: dumi build preview
  .github/workflows/preview-build.yml
  package.json
Labels: codeball:needs-review

#38599 chore: Adjust v5 conch script
  scripts/post-script.js
Labels: codeball:needs-review

#38602 docs: Remove less content
  README-ja_JP.md
  README-pt_BR.md
  README-sp_MX.md
  README-uk_UA.md
  README-zh_CN.md
  README.md
  components/config-provider/index.en-US.md
  components/config-provider/index.zh-CN.md
  docs/react/faq.en-US.md
  docs/react/faq.zh-CN.md
  docs/react/introduce.en-US.md
  docs/react/introduce.zh-CN.md
  docs/react/use-in-typescript.en-US.md
  docs/react/use-in-typescript.zh-CN.md
  docs/react/use-with-create-react-app.en-US.md
  docs/react/use-with-create-react-app.zh-CN.md
  docs/spec/colors.en-US.md
  docs/spec/colors.zh-CN.md
Labels: codeball:needs-careful-review

#38608 feat: theme seperated
  components/config-provider/__tests__/theme.test.tsx
  components/config-provider/context.tsx
  components/config-provider/hooks/useTheme.ts
  docs/react/customize-theme-v5.en-US.md
  docs/react/customize-theme-v5.zh-CN.md
Labels: codeball:needs-review

#38593 chore: bump tools
  package.json
Labels: codeball:needs-review

#38603 docs: correct code iframe values
  components/alert/index.en-US.md
  components/alert/index.zh-CN.md
  components/back-top/index.en-US.md
  components/back-top/index.zh-CN.md
  components/breadcrumb/index.en-US.md
  components/breadcrumb/index.zh-CN.md
  components/float-button/index.en-US.md
  components/float-button/index.zh-CN.md
  components/layout/index.en-US.md
  components/layout/index.zh-CN.md
  scripts/migrate.js
Labels: codeball:needs-review

#38615 docs: fix safari don't support webm video
  .dumi/pages/index/components/Banner.tsx
Labels: codeball:approved

#38598 docs: improve component demo style
  components/alert/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/alert/__tests__/__snapshots__/demo.test.ts.snap
  components/alert/demo/action.tsx
  components/alert/demo/banner.tsx
  components/alert/demo/closable.tsx
  components/alert/demo/custom-icon.tsx
  components/alert/demo/description.tsx
  components/alert/demo/icon.tsx
  components/alert/demo/smooth-closed.tsx
  components/alert/demo/style.tsx
  components/badge/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/badge/__tests__/__snapshots__/demo.test.ts.snap
  components/badge/demo/basic.tsx
  components/badge/demo/change.tsx
  components/badge/demo/colorful-with-count-debug.tsx
  components/badge/demo/dot.tsx
  components/badge/demo/mix.tsx
  components/badge/demo/overflow.tsx
  components/badge/demo/size.tsx
  components/badge/demo/title.tsx
  components/button/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/button/__tests__/__snapshots__/demo.test.ts.snap
  components/button/demo/basic.tsx
  components/button/demo/block.tsx
  components/button/demo/chinese-chars-loading.tsx
  components/button/demo/danger.tsx
  components/button/demo/debug-icon.md
  components/button/demo/debug-icon.tsx
  components/button/demo/disabled.md
  components/button/demo/disabled.tsx
  components/button/demo/ghost.md
  components/button/demo/ghost.tsx
  components/button/demo/icon.tsx
  components/button/demo/loading.tsx
  components/button/demo/multiple.tsx
  components/button/demo/size.tsx
  components/button/index.en-US.md
  components/button/index.zh-CN.md
Labels: codeball:needs-careful-review

#38618 chore: next merge master
  CHANGELOG.zh-CN.md
  components/breadcrumb/Breadcrumb.tsx
  components/breadcrumb/BreadcrumbItem.tsx
  components/breadcrumb/__tests__/Breadcrumb.test.tsx
  components/dropdown/__tests__/dropdown-button.test.tsx
  components/form/FormItem/index.tsx
  components/form/__tests__/index.test.tsx
  components/input/Search.tsx
  components/input/__tests__/Search.test.tsx
  components/layout/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/layout/__tests__/__snapshots__/demo.test.ts.snap
  components/layout/demo/fixed.tsx
  components/modal/Modal.tsx
  components/modal/__tests__/Modal.test.tsx
  components/modal/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/modal/__tests__/__snapshots__/demo.test.ts.snap
  components/modal/demo/custom-mouse-position.md
  components/modal/demo/custom-mouse-position.tsx
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
  components/table/__tests__/Table.pagination.test.tsx
  components/table/__tests__/Table.sorter.test.tsx
  components/table/hooks/useFilter/FilterWrapper.tsx
  components/typography/Base/index.tsx
  components/typography/__tests__/prefixCls.test.tsx
  package.json
Labels: BranchAutoMerge, codeball:needs-careful-review

#38577 chore: sync 4.x
  CHANGELOG.zh-CN.md
  components/breadcrumb/Breadcrumb.tsx
  components/breadcrumb/BreadcrumbItem.tsx
  components/breadcrumb/__tests__/Breadcrumb.test.tsx
  components/dropdown/__tests__/dropdown-button.test.tsx
  components/input/Search.tsx
  components/input/__tests__/Search.test.tsx
  components/modal/Modal.tsx
  components/modal/__tests__/Modal.test.tsx
  components/modal/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/modal/__tests__/__snapshots__/demo.test.ts.snap
  components/modal/demo/custom-mouse-position.md
  components/table/__tests__/Table.pagination.test.tsx
  components/table/__tests__/Table.sorter.test.tsx
  components/table/hooks/useFilter/FilterWrapper.tsx
  components/typography/Base/index.tsx
  components/typography/__tests__/prefixCls.test.tsx
  package.json
Labels: BranchAutoMerge, codeball:needs-careful-review

#38621 chore: markdown table style should be compat
  .prettierrc
Labels: codeball:needs-review

#38622 chore: remove useless scripts
  .eslintignore
  .prettierignore
  .stylelintrc.json
  scripts/compact-vars.js
  scripts/dark-vars.js
  scripts/default-vars.js
Labels: codeball:needs-review

#38623 docs: 4.24.3 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: codeball:approved

#38616 feat: anchor ink ball style
  .dumi/theme/slots/Content/index.tsx
  components/affix/index.en-US.md
  components/affix/index.zh-CN.md
  components/anchor/Anchor.tsx
  components/anchor/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/anchor/__tests__/__snapshots__/demo.test.ts.snap
  components/anchor/demo/basic.tsx
  components/anchor/demo/customizeHighlight.tsx
  components/anchor/demo/onChange.tsx
  components/anchor/demo/onClick.tsx
  components/anchor/demo/static.tsx
  components/anchor/demo/targetOffset.tsx
  components/anchor/index.en-US.md
  components/anchor/index.zh-CN.md
  components/anchor/style/index.tsx
Labels: codeball:needs-careful-review

#38633 docs: fix Grid demo color
  .dumi/theme/common/GlobalStyles.tsx
Labels: codeball:approved

#38624 docs: improve resouce page style
  .dumi/theme/common/Loading.tsx
  .dumi/theme/layouts/ResourceLayout/index.tsx
Labels: codeball:approved

#38626 fix: menu paddingTop centered with icon
  components/menu/style/index.tsx
  components/menu/style/vertical.tsx
Labels: codeball:needs-review

#38625 docs: fix Skeleton style and demo layout
  components/skeleton/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/skeleton/__tests__/__snapshots__/demo.test.ts.snap
  components/skeleton/demo/children.md
  components/skeleton/demo/children.tsx
  components/skeleton/index.en-US.md
  components/skeleton/style/index.tsx
Labels: codeball:needs-review

#38635 docs: improve some details about new site
  .dumi/pages/index/components/BannerRecommends.tsx
  .dumi/theme/common/EditButton.tsx
  .dumi/theme/common/ExternalLinkIcon.jsx
  .dumi/theme/common/GlobalStyles.tsx
  docs/spec/values.en-US.md
  docs/spec/values.zh-CN.md
Labels: codeball:needs-review

#38637 docs: correct style extract from demo markdown
  .dumi/theme/plugin.ts
Labels: codeball:approved

#38638 docs: add legacy version link of 4.x
  .dumi/theme/themeConfig.ts
  .github/workflows/issue-open-check.yml
  docs/react/faq.zh-CN.md
Labels: codeball:approved

#38641 docs: less usage guide
  .dumi/theme/slots/Header/Navigation.tsx
  docs/react/customize-theme-v5.en-US.md
  docs/react/customize-theme-v5.zh-CN.md
  docs/react/migration-v5.en-US.md
  docs/react/migration-v5.zh-CN.md
Labels: codeball:needs-careful-review

#38639 fix: Pagination jumper style
  components/pagination/style/index.tsx
Labels: codeball:needs-careful-review

#38647 docs: Adjust home page PurePanel & fix nav lang & popup for v5
  .dumi/pages/index/components/ComponentsList.tsx
  .dumi/pages/index/index.tsx
  .dumi/theme/locales/en-US.json
  .dumi/theme/locales/zh-CN.json
  .dumi/theme/slots/Footer/InfoNewVersion.tsx
  .dumi/theme/slots/Footer/index.tsx
Labels: codeball:needs-careful-review

#38643 docs: improve component demo style
  components/alert/demo/action.md
  components/alert/demo/basic.md
  components/alert/demo/style.md
  components/badge/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/badge/__tests__/__snapshots__/demo.test.ts.snap
  components/badge/demo/basic.md
  components/badge/demo/colorful-with-count-debug.md
  components/badge/demo/ribbbon.md
  components/badge/demo/ribbbon.tsx
  components/button/index.zh-CN.md
Labels: codeball:needs-careful-review

#38650 docs: correct demo style for tag
  components/tag/demo/colorful-inverse.md
  components/tag/demo/colorful.md
Labels: codeball:needs-review

#38654 docs: remove hotjar
  .dumi/theme/common/GlobalStyles.tsx
  .dumirc.ts
Labels: codeball:approved

#38645 style: fix SubMenu offset
  components/menu/MenuContext.tsx
  components/menu/SubMenu.tsx
  components/menu/menu.tsx
Labels: codeball:approved

#38657 docs: clean useless maark
  README-ja_JP.md
  README-pt_BR.md
  README-sp_MX.md
  README-uk_UA.md
  README-zh_CN.md
  README.md
Labels: codeball:needs-careful-review

#38617 fix: global icon style
  components/config-provider/__tests__/cssinjs.test.tsx
  components/config-provider/index.tsx
  components/config-provider/style/index.tsx
  components/message/__tests__/config.test.tsx
Labels: codeball:needs-careful-review

#38651 ci: add tag for more branch
  .github/workflows/release-helper.yml
Labels: codeball:needs-review

#38652 ci: add tag for more branch
  .github/workflows/release-helper.yml
Labels: codeball:needs-review

#38658 docs: use dumi built-in search bar
  .dumi/theme/slots/Header/SearchBar.tsx
  .dumi/theme/slots/Header/algolia-config.ts
  .dumi/theme/slots/Header/index.tsx
Labels: codeball:needs-review

#38664 style: fix large Input size
  components/input/style/index.tsx
Labels: codeball:approved

#38662 fix: preview-img style
  .dumi/rehypeAntd.ts
  .dumi/theme/builtins/ImagePreview/index.jsx
  .dumi/theme/common/GlobalStyles.tsx
Labels: codeball:needs-careful-review

#38667 docs: Update migration docs
  docs/react/migration-v5.en-US.md
  docs/react/migration-v5.zh-CN.md
Labels: codeball:needs-review

#38665 chore: bump notify on second time
  .dumi/theme/slots/Footer/AdditionalInfo.tsx
  .dumi/theme/slots/Footer/InfoNewVersion.tsx
  .dumi/theme/slots/Footer/index.tsx
  .dumi/theme/slots/Header/index.tsx
Labels: codeball:needs-review

#38642 docs: 5.0.0 changelog
  .antd-tools.config.js
  .dumi/theme/plugin.ts
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/back-top/index.en-US.md
  components/back-top/index.zh-CN.md
  package.json
Labels: codeball:needs-careful-review

#38668 docs: correct search bar space in header
  .dumi/theme/slots/Header/index.tsx
Labels: codeball:needs-review

#38670 fix: typo in doc
  docs/react/migration-v5.zh-CN.md
Labels: codeball:needs-review

#38672 docs: remove the dist/antd.css in the sample code
  docs/react/getting-started.en-US.md
  docs/react/getting-started.zh-CN.md
  docs/react/use-in-typescript.en-US.md
  docs/react/use-in-typescript.zh-CN.md
  docs/react/use-with-create-react-app.en-US.md
  docs/react/use-with-create-react-app.zh-CN.md
Labels: codeball:needs-review

#38675 docs: improve sourcecode styles
  .dumi/theme/common/GlobalStyles.tsx
Labels: codeball:needs-review

#38676 test: fix upload image test by skip one
  components/upload/__tests__/image.test.ts
Labels: codeball:approved

#38678 fix(site): fix antd/lib lint error
  package.json
Labels: codeball:needs-careful-review

#38669 fix(message): call onClose after removeNotice
  components/message/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/message/__tests__/__snapshots__/demo.test.ts.snap
  components/message/__tests__/type.test.tsx
  components/message/demo/loading.md
  components/message/index.tsx
Labels: codeball:needs-careful-review

#38674 chore: update mirror host
  components/upload/__tests__/demo-extend.test.ts
  components/upload/__tests__/demo.test.ts
  components/upload/__tests__/image.test.ts
  site/theme/template/Layout/Header/Navigation.tsx
  site/theme/template/Layout/index.tsx
Labels: codeball:needs-careful-review

#38681 docs: remove IE
  README-ja_JP.md
  README-pt_BR.md
  README-sp_MX.md
  README-uk_UA.md
  README-zh_CN.md
  README.md
  docs/react/introduce.en-US.md
  docs/react/introduce.zh-CN.md
Labels: codeball:needs-review

#38684 fix(dumi): update dumi theme
  .dumi/theme/common/GlobalStyles.tsx
Labels: codeball:needs-review

#38688 docs: tweak home banner height
  .dumi/hooks/useSiteToken.ts
  .dumi/pages/index/components/Banner.tsx
Labels: codeball:approved

#38689 fix: set default value for style
  components/tooltip/util.ts
Labels: codeball:needs-review

#38690 docs: dumi's first letter is lowercase
  .dumi/theme/slots/Footer/index.tsx
Labels: codeball:needs-review

#38696 docs: fix edit button position
  .dumi/theme/common/EditButton.tsx
Labels: codeball:approved

#38697 type: fix type
  components/float-button/FloatButtonGroup.tsx
Labels: codeball:approved

#38698 chore: type optimization
  components/form/FormItem/index.tsx
  components/steps/index.tsx
Labels: codeball:needs-review

#38710 docs: fix typo in use-custom-date-library.en-US.md
  docs/react/use-custom-date-library.en-US.md
Labels: codeball:approved

#38705 docs: improve home page text
  .dumi/pages/index/components/Banner.tsx
Labels: codeball:approved

#38706 chore: update workflow for 4.x-stable branch
  .github/workflows/sync-gitee.yml
  scripts/print-changelog.js
Labels: codeball:needs-review

#38711 chore: fix lgtm errors
  components/message/index.tsx
  components/notification/index.tsx
  components/slider/index.tsx
Labels: codeball:approved

#38707 chore: Update message hooks demo
  components/message/demo/hooks.tsx
Labels: codeball:needs-review

#38708 fix(dumi): get contributor error on 404 page
  .dumi/theme/slots/Content/index.tsx
Labels: codeball:needs-review

#38714 style: fix Menu submenu margin
  components/menu/style/vertical.tsx
Labels: codeball:needs-review

#38725 docs: update document format
  docs/react/introduce.en-US.md
  docs/react/introduce.zh-CN.md
Labels: codeball:needs-review

#38726 site: remove pointerEvents
  .dumi/pages/index/components/ComponentsList.tsx
Labels: codeball:approved

#38693 chore: remove throttleByAnimationFrameDecorator
  components/_util/__tests__/util.test.tsx
  components/_util/throttleByAnimationFrame.tsx
  components/affix/index.tsx
  components/back-top/index.tsx
  components/float-button/BackTop.tsx
Labels: codeball:needs-careful-review

#38723 chore: Definition message.config type
  components/message/__tests__/config.test.tsx
  components/message/index.tsx
Labels: codeball:needs-review

#38729 fix: ssr keyframes
  package.json
Labels: codeball:approved

#38666 fix(types): external module type error (CompoundedComponent)
  components/alert/index.tsx
  components/anchor/index.tsx
  components/badge/index.tsx
  components/breadcrumb/Breadcrumb.tsx
  components/button/button.tsx
  components/checkbox/index.tsx
  components/input/index.tsx
  components/layout/index.tsx
  components/mentions/index.tsx
  components/menu/index.tsx
  components/radio/index.tsx
  components/skeleton/Skeleton.tsx
  components/space/index.tsx
  components/steps/index.tsx
  components/switch/index.tsx
  components/table/Table.tsx
  components/timeline/Timeline.tsx
  components/tree-select/index.tsx
  components/upload/index.tsx
Labels: codeball:needs-careful-review

#38733 chore: simplify strokeWidth code
  components/progress/Circle.tsx
Labels: codeball:approved

#38738 docs: remove iconPicSearcher
  .dumi/theme/builtins/IconSearch/IconPicSearcher.tsx
  .dumi/theme/builtins/IconSearch/index.tsx
  .dumi/theme/locales/en-US.json
  .dumi/theme/locales/zh-CN.json
Labels: codeball:approved

#38737 docs: update zhihu blog url
  .dumi/theme/slots/Footer/index.tsx
  CHANGELOG.en-US.md
Labels: codeball:approved

#38739 chore: improve gh-pages workflow
  .github/workflows/site-deploy.yml
  package.json
Labels: codeball:needs-review

#38742 fix: style parse error
  components/form/style/index.tsx
  components/input/style/index.tsx
  components/select/style/single.tsx
  components/tree/style/index.tsx
Labels: codeball:needs-review

#38743 docs: spelling and grammar fix
  components/cascader/index.en-US.md
  components/drawer/index.en-US.md
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/form/__tests__/__snapshots__/demo.test.ts.snap
  components/form/demo/disabled.tsx
  components/form/index.en-US.md
  components/layout/index.en-US.md
  components/modal/index.en-US.md
  components/select/index.en-US.md
  components/slider/index.en-US.md
  components/tour/index.en-US.md
  components/transfer/index.en-US.md
  docs/react/faq.en-US.md
  docs/react/i18n.en-US.md
Labels: codeball:needs-review

#38748 fix: menu expansion submenu jitter
  components/menu/style/index.tsx
  components/menu/style/vertical.tsx
Labels: codeball:needs-review

#38746 chore: adjust deploy token
  .github/workflows/site-deploy.yml
Labels: codeball:approved

#38744 docs: update README badges
  README.md
Labels: codeball:approved

#38762 fix: bump rc-picker to remove moment
  package.json
Labels: codeball:approved

#38766 test: Update message test case
  components/message/__tests__/index.test.tsx
Labels: codeball:approved

#38751 refactor(MenuItem): rewrite CC => FC
  components/menu/MenuDivider.tsx
  components/menu/MenuItem.tsx
  components/menu/OverrideContext.tsx
  components/menu/SubMenu.tsx
  components/menu/index.tsx
  components/menu/menu.tsx
Labels: codeball:needs-review

#38768 test: Update button test case
  components/button/__tests__/index.test.tsx
  components/button/__tests__/wave.test.tsx
Labels: codeball:needs-review

#38770 fix: back-top animation error
  components/float-button/style/index.tsx
Labels: codeball:approved

#38741 fix(menu): menu horizontal border bottom when dark
  components/menu/style/theme.tsx
Labels: 5.x, codeball:needs-review

#38773 chore: change dumi dev port to 8001
  package.json
Labels: codeball:needs-review

#38776 docs: auto use Chinese mirror if in mirror
  .dumi/pages/index/components/BannerRecommends.tsx
  .dumi/theme/themeConfig.ts
Labels: codeball:needs-review

#38781 fix: delete Chinese subtitle in EN locale
  .dumi/theme/builtins/ComponentOverview/index.tsx
Labels: codeball:approved

#38782 fix: fix OverviewPage style
  .dumi/theme/builtins/ComponentOverview/index.tsx
Labels: codeball:needs-review

#38790 fix: delete Chinese locale
  .dumi/theme/builtins/ComponentOverview/index.tsx
Labels: codeball:approved

#38791 fix: collapsed inline menu style
  components/layout/style/index.tsx
Labels: codeball:needs-review

#38764 docs: guide about where config
  docs/react/customize-theme.en-US.md
  docs/react/customize-theme.zh-CN.md
  docs/react/faq.en-US.md
  docs/react/faq.zh-CN.md
Labels: codeball:needs-careful-review

#38727 docs: update document Table style
  .dumi/rehypeAntd.ts
  .dumi/theme/common/GlobalStyles.tsx
Labels: codeball:needs-review

#38801 docs(Badge): change file name
  components/badge/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/badge/__tests__/__snapshots__/demo.test.ts.snap
  components/badge/demo/ribbon.tsx
  components/badge/index.en-US.md
  components/badge/index.zh-CN.md
Labels: codeball:needs-review

#38630 Mentions data driven
  components/mentions/__tests__/index.test.tsx
  components/mentions/demo/async.tsx
  components/mentions/demo/autoSize.tsx
  components/mentions/demo/basic.tsx
  components/mentions/demo/form.tsx
  components/mentions/demo/placement.tsx
  components/mentions/demo/prefix.tsx
  components/mentions/demo/readonly.tsx
  components/mentions/demo/render-panel.tsx
  components/mentions/demo/status.tsx
  components/mentions/index.en-US.md
  components/mentions/index.tsx
  components/mentions/index.zh-CN.md
  package.json
Labels: codeball:needs-careful-review

#38810 docs(Tabs): fix markdown format
  components/tabs/index.en-US.md
Labels: codeball:approved

#38799 docs: Update v5 res & adjust cssinjs doc
  docs/react/customize-theme.en-US.md
  docs/react/customize-theme.zh-CN.md
  docs/react/migration-v5.en-US.md
  docs/react/migration-v5.zh-CN.md
  docs/resources.en-US.md
  docs/resources.zh-CN.md
Labels: codeball:needs-careful-review

#38819 site: fix site style
  .dumi/pages/index/components/Banner.tsx
Labels: codeball:approved

#38823 fix: Table children expand icons shouldn't be same line with parent's icon
  components/table/style/expand.tsx
Labels: codeball:needs-review

#38832 chore: revert compile with lib
  .antd-tools.config.js
  .github/workflows/test.yml
  package.json
  tests/dekko/lib.test.js
Labels: skip-verify-files, codeball:needs-careful-review

#38849 docs: fix TextArea showCount demo
  components/input/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/input/__tests__/__snapshots__/demo.test.ts.snap
  components/input/demo/textarea-show-count.tsx
Labels: codeball:needs-review

#38854 docs: 5.0.1 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  docs/react/migration-v5.en-US.md
  docs/react/migration-v5.zh-CN.md
  package.json
Labels: codeball:approved

#38829 fix(badge): fix the style issue in RTL mode
  components/badge/style/index.tsx
Labels: codeball:needs-careful-review

#38862 fix: Dropdown.Button's dropdownRender is not executed
  components/dropdown/__tests__/dropdown-button.test.tsx
  components/dropdown/dropdown-button.tsx
Labels: codeball:needs-review

#38861 docs: update table demo
  components/table/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/table/__tests__/__snapshots__/demo.test.ts.snap
  components/table/demo/size.tsx
Labels: codeball:needs-review

#38871 doc: spell error
  CHANGELOG.zh-CN.md
Labels: codeball:needs-review

#38869 fix(button): Button block prop not working
  components/button/style/index.tsx
Labels: codeball:needs-review

#38875 docs: improve markdown style
  .dumi/theme/common/GlobalStyles.tsx
Labels: codeball:approved

#38872 docs: use less-loader with `lib` folder in cjs
  docs/react/migration-v5.en-US.md
  docs/react/migration-v5.zh-CN.md
Labels: codeball:needs-review

#38886 bugfix(DisabledContextProvider): fix disabled logic
  components/config-provider/DisabledContext.tsx
  components/config-provider/__tests__/form.test.tsx
Labels: codeball:needs-review

#38893 chore(site): links to add query params
  .dumi/hooks/useMenu.tsx
Labels: codeball:needs-review

#38903 docs: fix typo
  docs/react/faq.zh-CN.md
Labels: codeball:approved

#38892 fix: Tabs missing slide motion def
  components/tabs/style/motion.tsx
Labels: codeball:needs-review
