Repository ant-design/ant-design, pull requests merged in 2023-01, with the labels that each got.

#39941 docs: blog about re-render
  docs/blog/render-times.en-US.md
  docs/blog/render-times.zh-CN.md
Labels: codeball:needs-review

#39947 docs: optimization docs
  docs/react/migration-v5.en-US.md
  docs/react/migration-v5.zh-CN.md
Labels: codeball:approved

#39952 Updated the Copyright Year
  components/layout/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/layout/__tests__/__snapshots__/demo.test.ts.snap
  components/layout/demo/fixed-sider.tsx
  components/layout/demo/fixed.tsx
  components/layout/demo/responsive.tsx
  components/layout/demo/side.tsx
  components/layout/demo/top-side.tsx
  components/layout/demo/top.tsx
Labels: codeball:needs-review

#39950 chore: use React.useContext() replace <Context.Provider />
  components/avatar/SizeContext.tsx
  components/config-provider/SizeContext.tsx
  components/form/FormItemLabel.tsx
  components/menu/MenuItem.tsx
  components/tabs/index.tsx
Labels: codeball:needs-careful-review

#39954 fix: Button wave follow issue
  components/_util/__tests__/wave.test.tsx
  components/_util/wave/WaveEffect.tsx
  components/_util/wave/style.ts
  components/_util/wave/useWave.ts
  components/_util/wave/util.ts
Labels: codeball:needs-careful-review

#39944 refactor: (Transfer) CC => FC
  components/transfer/ListBody.tsx
  components/transfer/__tests__/list.test.tsx
  components/transfer/list.tsx
Labels: codeball:needs-careful-review

#39955 type: remove redundant useContext
  components/cascader/index.tsx
  components/table/Table.tsx
Labels: codeball:needs-review

#39509 feat(ConfigProvider): add form scrollToFirstError
  components/config-provider/__tests__/form.test.tsx
  components/config-provider/context.ts
  components/config-provider/index.en-US.md
  components/config-provider/index.tsx
  components/config-provider/index.zh-CN.md
  components/form/Form.tsx
Labels: codeball:needs-careful-review

#39963 Fix demo grid
  components/grid/index.en-US.md
  components/grid/index.zh-CN.md
Labels: codeball:needs-review

#39961 docs: add Space for demo
  components/transfer/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/transfer/__tests__/__snapshots__/demo.test.ts.snap
  components/transfer/demo/table-transfer.tsx
Labels: codeball:approved

#39959 docs(list): Example display error in English environment
  components/list/index.en-US.md
Labels: codeball:approved

#39058 [v4] Fix(types): external module type error (CompoundedComponent)
  components/alert/index.tsx
  components/anchor/index.tsx
  components/badge/index.tsx
  components/breadcrumb/Breadcrumb.tsx
  components/breadcrumb/BreadcrumbItem.tsx
  components/breadcrumb/BreadcrumbSeparator.tsx
  components/button/button.tsx
  components/checkbox/index.tsx
  components/collapse/Collapse.tsx
  components/dropdown/dropdown-button.tsx
  components/dropdown/dropdown.tsx
  components/empty/index.tsx
  components/form/FormItem/index.tsx
  components/form/index.tsx
  components/input/index.tsx
  components/layout/index.tsx
  components/mentions/index.tsx
  components/pagination/Select.tsx
  components/radio/index.tsx
  components/skeleton/Skeleton.tsx
  components/space/index.tsx
  components/statistic/Countdown.tsx
  components/statistic/Statistic.tsx
  components/steps/index.tsx
  components/switch/index.tsx
  components/table/Table.tsx
  components/timeline/Timeline.tsx
  components/tree-select/index.tsx
  components/upload/index.tsx
Labels: codeball:needs-careful-review

#39967 chore: fix header menu style in mobile device
  .dumi/theme/slots/Header/Navigation.tsx
Labels: codeball:approved

#39966 fix: wave target position switch
  .gitignore
  components/_util/__tests__/wave.test.tsx
  components/_util/wave/WaveEffect.tsx
  components/button/__tests__/wave.test.tsx
  components/switch/__tests__/index.test.tsx
Labels: codeball:needs-careful-review

#39969 docs: page loading not working bug
  .dumi/loading.js
Labels: codeball:needs-review

#39980 feat(tour): tour support custom scroll into view options
  components/tour/index.en-US.md
  components/tour/index.zh-CN.md
  package.json
Labels: codeball:needs-review

#39974 Bugfix/checkbox style
  components/checkbox/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/checkbox/__tests__/__snapshots__/demo.test.ts.snap
  components/checkbox/demo/disabled.tsx
  components/checkbox/style/index.ts
Labels: codeball:needs-careful-review

#39994 chore: update style of github contributors
  .dumi/theme/slots/Content/index.tsx
Labels: codeball:approved

#39993 fix: Avatar.Group item could be wrapped
  components/avatar/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/avatar/__tests__/__snapshots__/demo.test.ts.snap
  components/avatar/demo/group.tsx
  components/avatar/style/index.ts
Labels: codeball:needs-review

#40000 chore: update token statistic script
  scripts/collect-token-statistic.js
Labels: codeball:approved

#40001 chore: add cssinjs linter
  .dumi/theme/layouts/GlobalLayout.tsx
  package.json
  tests/shared/demoTest.tsx
Labels: codeball:needs-review

#40005 chore: feature merge master
  .circleci/config.yml
  .dumi/loading.js
  .dumi/theme/layouts/GlobalLayout.tsx
  .dumi/theme/slots/Content/index.tsx
  .dumi/theme/slots/Header/Navigation.tsx
  .gitignore
  components/_util/__tests__/wave.test.tsx
  components/_util/wave/WaveEffect.tsx
  components/_util/wave/style.ts
  components/_util/wave/useWave.ts
  components/_util/wave/util.ts
  components/avatar/SizeContext.tsx
  components/avatar/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/avatar/__tests__/__snapshots__/demo.test.ts.snap
  components/avatar/demo/group.tsx
  components/avatar/style/index.ts
  components/button/__tests__/wave.test.tsx
  components/cascader/index.tsx
  components/checkbox/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/checkbox/__tests__/__snapshots__/demo.test.ts.snap
  components/checkbox/demo/disabled.tsx
  components/checkbox/style/index.ts
  components/config-provider/SizeContext.tsx
  components/form/FormItemLabel.tsx
  components/grid/index.en-US.md
  components/grid/index.zh-CN.md
  components/layout/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/layout/__tests__/__snapshots__/demo.test.ts.snap
  components/layout/demo/fixed-sider.tsx
  components/layout/demo/fixed.tsx
  components/layout/demo/responsive.tsx
  components/layout/demo/side.tsx
  components/layout/demo/top-side.tsx
  components/layout/demo/top.tsx
  components/list/index.en-US.md
  components/menu/MenuItem.tsx
  components/menu/style/index.tsx
  components/switch/__tests__/index.test.tsx
  components/table/Table.tsx
  components/tabs/demo/basic.tsx
  components/tabs/index.tsx
  components/transfer/ListBody.tsx
  components/transfer/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/transfer/__tests__/__snapshots__/demo.test.ts.snap
  components/transfer/__tests__/list.test.tsx
  components/transfer/demo/table-transfer.tsx
  components/transfer/index.tsx
  components/transfer/list.tsx
  components/transfer/operation.tsx
  components/transfer/search.tsx
  docs/blog/render-times.en-US.md
  docs/blog/render-times.zh-CN.md
  docs/react/migration-v5.en-US.md
  docs/react/migration-v5.zh-CN.md
  package.json
  scripts/collect-token-statistic.js
  tests/shared/demoTest.tsx
Labels: BranchAutoMerge, codeball:needs-careful-review

#40002 site: make icon search affix
  .dumi/theme/builtins/IconSearch/index.tsx
Labels: codeball:needs-careful-review

#40003 site: fix home page rtl style and footer icons
  .dumi/pages/index/components/BannerRecommends.tsx
  .dumi/pages/index/components/Theme/index.tsx
  .dumi/theme/common/styles/Reset.tsx
  .dumi/theme/locales/en-US.json
  .dumi/theme/locales/zh-CN.json
  .dumi/theme/slots/Footer/index.tsx
  .dumi/theme/slots/Header/Logo.tsx
  .dumi/theme/slots/Header/index.tsx
  package.json
Labels: codeball:needs-careful-review

#40013 chore: adjust tooltip for cov
  components/tooltip/index.tsx
  scripts/post-script.js
Labels: codeball:needs-review

#40004 fix: Table cell render closure
  package.json
Labels: codeball:needs-review

#40014 chore: step-next demo supports dark mode
  components/steps/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/steps/__tests__/__snapshots__/demo.test.ts.snap
  components/steps/demo/step-next.md
  components/steps/demo/step-next.tsx
Labels: codeball:needs-careful-review

#40019 fix: missing translation for Brazilian Portuguese
  components/locale/pt_BR.tsx
Labels: codeball:approved

#40023 fix: 修复 Tag onClick 为 undefined 的判断方式
  components/tag/__tests__/index.test.tsx
  components/tag/index.tsx
Labels: codeball:needs-careful-review

#39988 refactor: (TransferBody) CC => FC
  components/transfer/ListBody.tsx
  components/transfer/__tests__/list.test.tsx
  components/transfer/list.tsx
Labels: codeball:needs-careful-review

#40027 docs: add animated number demo for Statistic
  components/statistic/Countdown.tsx
  components/statistic/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/statistic/__tests__/__snapshots__/demo.test.ts.snap
  components/statistic/demo/animated.md
  components/statistic/demo/animated.tsx
  components/statistic/demo/card.md
  components/statistic/demo/countdown.tsx
  components/statistic/index.en-US.md
  components/statistic/index.zh-CN.md
  components/statistic/utils.ts
  docs/react/recommendation.en-US.md
  docs/react/recommendation.zh-CN.md
  package.json
Labels: codeball:needs-careful-review

#40028 site: improve demo card style
  .dumi/theme/builtins/Previewer/index.tsx
  .dumi/theme/common/styles/Demo.tsx
  components/card/demo/border-less.md
  components/card/demo/in-column.md
  components/card/index.en-US.md
  components/card/index.zh-CN.md
  components/layout/index.en-US.md
  components/layout/index.zh-CN.md
  components/statistic/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/statistic/__tests__/__snapshots__/demo.test.ts.snap
  components/statistic/demo/card.md
  components/statistic/demo/card.tsx
  components/statistic/index.en-US.md
  components/statistic/index.zh-CN.md
  components/tabs/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tabs/__tests__/__snapshots__/demo.test.ts.snap
  components/tabs/demo/card-top.tsx
  components/tabs/index.en-US.md
  components/tabs/index.zh-CN.md
  package.json
Labels: codeball:needs-careful-review

#40043 site: refactor CC => FC
  .dumi/theme/builtins/Previewer/index.tsx
Labels: codeball:needs-careful-review

#39992 fix: Button block prop not work
  components/button/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/button/__tests__/__snapshots__/demo.test.ts.snap
  components/button/demo/debug-block.md
  components/button/demo/debug-block.tsx
  components/button/index.en-US.md
  components/button/index.zh-CN.md
  components/button/style/index.ts
Labels: codeball:needs-careful-review

#39742 refactor: merge preset colors
  components/_util/colors.ts
  components/badge/Ribbon.tsx
  components/badge/index.tsx
  components/badge/style/index.ts
  components/badge/utils.ts
  components/style/index.ts
  components/style/presetColor.tsx
  components/tag/index.tsx
  components/tag/style/index.ts
  components/theme/interface/index.ts
  components/theme/interface/presetColors.ts
  components/theme/internal.ts
  components/tooltip/style/index.ts
  components/tooltip/util.ts
Labels: codeball:needs-careful-review

#40057 docs: add notice
  components/transfer/index.en-US.md
  components/transfer/index.zh-CN.md
Labels: codeball:needs-review

#39471 fix: missing css code in demo code preview
  .dumi/theme/builtins/Previewer/fromDumiProps.tsx
  .dumi/theme/common/CodePreview.tsx
  .dumi/theme/plugin.ts
  components/dropdown/index.zh-CN.md
  components/tooltip/index.zh-CN.md
Labels: codeball:needs-careful-review

#40060 site: update overview search style
  .dumi/theme/builtins/ComponentOverview/index.tsx
Labels: codeball:approved

#40067 fix: Cascader notFoundContent should be interactive
  components/cascader/style/index.ts
Labels: codeball:approved

#40069 site: fix anchor height
  .dumi/theme/slots/Content/index.tsx
Labels: codeball:needs-review

#40068 test: refactor test case demo CC => FC
  components/form/__tests__/type.test.tsx
  components/form/demo/control-ref.tsx
  components/segmented/__tests__/index.test.tsx
  components/table/__tests__/Table.filter.test.tsx
  components/table/__tests__/Table.sorter.test.tsx
  components/tree/__tests__/directory.test.tsx
  components/tree/demo/drag-debug.tsx
  components/upload/__tests__/upload.test.tsx
Labels: codeball:approved

#40070 test: refactor test case demo CC => FC
  components/config-provider/__tests__/locale.test.tsx
  components/date-picker/__tests__/RangePicker.test.tsx
  components/drawer/__tests__/MultiDrawer.test.tsx
  components/modal/__tests__/Modal.test.tsx
  components/tooltip/index.tsx
  components/tree/Tree.tsx
Labels: codeball:needs-review

#40063 refactor: Table render logic opt
  components/table/InternalTable.tsx
  components/table/RcTable.tsx
  components/table/Table.tsx
  components/table/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/table/__tests__/__snapshots__/demo.test.ts.snap
  components/table/__tests__/type.test.tsx
  components/table/demo/row-selection-debug.md
  components/table/demo/row-selection-debug.tsx
  components/table/index.en-US.md
  components/table/index.ts
  components/table/index.zh-CN.md
  components/table/interface.ts
  package.json
Labels: codeball:needs-careful-review

#40071 fix(menu): fix custom expand icon cannot be hidden
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/dropdown/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/menu/__tests__/index.test.tsx
  components/menu/menu.tsx
  components/menu/style/vertical.tsx
  components/table/__tests__/__snapshots__/Table.filter.test.tsx.snap
  components/table/__tests__/__snapshots__/demo-extend.test.ts.snap
Labels: codeball:needs-careful-review

#40079 demo: update demo
  components/button/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/button/__tests__/__snapshots__/demo.test.ts.snap
  components/button/button.tsx
  components/button/demo/block.tsx
  components/tooltip/index.tsx
Labels: codeball:needs-careful-review

#40018 fix: Allow users to handle promise rejections in ActionButton's onOk callback
  components/_util/ActionButton.tsx
  components/modal/__tests__/confirm.test.tsx
Labels: codeball:needs-careful-review

#40084 chore: update contributors list
  AUTHORS.txt
Labels: codeball:approved

#40085 chore: adjust desc style
  components/descriptions/style/index.ts
Labels: codeball:needs-review

#40088 site: site code style optimization
  .dumi/theme/common/JSONEditor/index.tsx
Labels: codeball:needs-review

#40048 fix: Transfer checkbox disabled error
  components/transfer/__tests__/list.test.tsx
  components/transfer/list.tsx
Labels: codeball:needs-careful-review

#40083 style: Code style optimization
  .dumi/theme/common/JSONEditor/index.tsx
  components/_util/ActionButton.tsx
  components/transfer/index.tsx
Labels: codeball:needs-careful-review

#40092 fix: add displayName
  components/_util/wave/index.ts
  components/alert/index.tsx
  components/anchor/Anchor.tsx
  components/auto-complete/index.tsx
  components/back-top/index.tsx
  components/badge/Ribbon.tsx
  components/badge/index.tsx
  components/breadcrumb/Breadcrumb.tsx
  components/calendar/generateCalendar.tsx
  components/card/index.ts
  components/carousel/index.tsx
  components/checkbox/index.ts
  components/collapse/Collapse.tsx
  components/config-provider/index.tsx
  components/descriptions/index.tsx
  components/divider/index.tsx
  components/dropdown/dropdown.tsx
  components/empty/index.tsx
  components/float-button/BackTop.tsx
  components/image/index.tsx
  components/input-number/index.tsx
  components/input/index.ts
  components/list/index.tsx
  components/locale/index.tsx
  components/menu/index.tsx
  components/modal/index.tsx
  components/pagination/Pagination.tsx
  components/popconfirm/index.tsx
  components/progress/progress.tsx
  components/qrcode/index.tsx
  components/result/index.tsx
  components/result/noFound.tsx
  components/result/serverError.tsx
  components/result/unauthorized.tsx
  components/select/index.tsx
  components/skeleton/Skeleton.tsx
  components/space/index.tsx
  components/statistic/Statistic.tsx
  components/steps/index.tsx
  components/tabs/index.tsx
  components/timeline/Timeline.tsx
  components/tree/Tree.tsx
  components/watermark/index.tsx
Labels: codeball:needs-careful-review

#40089 👌 IMPROVE: add direction prop to ConfigProvider of demos
  .dumi/theme/layouts/DocLayout/index.tsx
Labels: codeball:needs-review

#40091 chore: use React.useContext replace <Context.ConfigConsumer />
  components/cascader/index.tsx
  components/config-provider/defaultRenderEmpty.tsx
  components/list/index.tsx
  components/mentions/index.tsx
  components/select/index.tsx
  components/table/InternalTable.tsx
  components/transfer/index.tsx
  components/transfer/list.tsx
  components/tree-select/index.tsx
Labels: codeball:needs-careful-review

#40103 💄 STYLE: Fix text not being displayed in circular Progress in rtl mode
  components/progress/style/index.tsx
Labels: codeball:needs-review

#40102 chore: rewrite test case Demo CC => FC
  components/affix/__tests__/Affix.test.tsx
Labels: codeball:needs-review

#40105 fix: horizontal Menu style with
  components/menu/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/menu/__tests__/__snapshots__/demo.test.ts.snap
  components/menu/demo/horizontal-dark.md
  components/menu/demo/horizontal-dark.tsx
  components/menu/index.en-US.md
  components/menu/index.zh-CN.md
  components/menu/style/index.tsx
  components/menu/style/theme.tsx
Labels: codeball:needs-careful-review

#40106 Suggested change
  components/progress/style/index.tsx
Labels: codeball:needs-review

#40109 fix(cascader): cascader dropdown placement using isRtl
  components/cascader/index.tsx
Labels: codeball:needs-careful-review

#40116 fix: missing locale in pacakge
  package.json
  scripts/post-script.js
Labels: codeball:needs-review

#40117 docs: changelog 5.1.4
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: codeball:needs-review

#40081 chore: Watermark uses MutateObserver
  components/watermark/__tests__/index.test.tsx
  components/watermark/index.tsx
  components/watermark/useMutationObserver.ts
  components/watermark/utils.ts
  package.json
Labels: codeball:needs-careful-review

#40124 fix: markdown eslint error
  components/icon/index.en-US.md
  components/icon/index.zh-CN.md
Labels: codeball:needs-review

#40130 docs: override debug prop when show all demo
  .dumi/theme/builtins/DemoWrapper/index.tsx
Labels: codeball:needs-review

#40129 site: delete V5_NOTIFICATION
  .dumi/theme/slots/Header/index.tsx
Labels: codeball:needs-review

#40119 fix: breadcrumb last item color does not use the `breadcrumbLastItemColor` token.
  components/breadcrumb/style/index.ts
Labels: codeball:needs-careful-review

#40135 chore: feature merge master
  .dumi/theme/builtins/DemoWrapper/index.tsx
  .dumi/theme/slots/Header/index.tsx
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/cascader/index.tsx
  components/icon/index.en-US.md
  components/icon/index.zh-CN.md
  components/watermark/__tests__/index.test.tsx
  components/watermark/index.tsx
  components/watermark/useMutationObserver.ts
  components/watermark/utils.ts
  package.json
  scripts/post-script.js
Labels: BranchAutoMerge, codeball:needs-careful-review

#40080 dev: upgrade the developer experience
  .dumi/theme/builtins/ColorChunk/index.tsx
  .dumi/theme/builtins/Previewer/index.tsx
  .dumi/theme/locales/en-US.json
  .dumi/theme/locales/zh-CN.json
  docs/spec/colors.en-US.md
  docs/spec/colors.zh-CN.md
Labels: codeball:needs-careful-review

#40125 style: fix Badge rtl style on block element
  components/badge/style/index.ts
Labels: codeball:approved

#39394 fix: fix custom color displaying wrong classname & alignment overflow
  components/timeline/TimelineItem.tsx
  components/timeline/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/timeline/__tests__/__snapshots__/demo.test.ts.snap
  components/timeline/__tests__/index.test.tsx
  components/timeline/style/index.ts
Labels: codeball:needs-careful-review

#40077 refactor: button
  components/button/button-group.tsx
  components/button/button.tsx
  components/button/buttonHelpers.tsx
  components/button/index.ts
  components/dropdown/dropdown-button.tsx
Labels: codeball:needs-careful-review

#40143 chore: form global-state demo supports dark mode
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/form/__tests__/__snapshots__/demo.test.ts.snap
  components/form/demo/global-state.md
  components/form/demo/global-state.tsx
Labels: codeball:needs-careful-review

#40144 demo: collapse custom demo supports dark mode
  components/collapse/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/collapse/__tests__/__snapshots__/demo.test.ts.snap
  components/collapse/demo/custom.md
  components/collapse/demo/custom.tsx
Labels: codeball:needs-careful-review

#40151 test: fix bundlesize2 cache throw error
  .github/workflows/test.yml
Labels: codeball:approved

#40045 refactor: TextArea
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/form/__tests__/__snapshots__/demo.test.ts.snap
  components/input/ClearableLabeledInput.tsx
  components/input/Input.tsx
  components/input/TextArea.tsx
  components/input/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/input/__tests__/__snapshots__/demo.test.ts.snap
  components/input/__tests__/__snapshots__/textarea.test.tsx.snap
  components/input/__tests__/textarea.test.tsx
  components/input/style/index.ts
  components/input/utils.ts
  components/mentions/index.tsx
  components/typography/Base/index.tsx
  components/typography/Editable.tsx
  package.json
Labels: codeball:needs-careful-review

#40121 chore(deps): update dependency
  components/progress/__tests__/index.test.tsx
  package.json
Labels: codeball:needs-careful-review

#40153 fix(tour): findDomNode throw warning in strict mode
  package.json
Labels: codeball:needs-review

#40149 docs: markdown eslint error fix
  README-ja_JP.md
  README-pt_BR.md
  README-sp_MX.md
  README-uk_UA.md
  README-zh_CN.md
  README.md
  docs/react/migration-v5.en-US.md
  docs/react/migration-v5.zh-CN.md
  docs/react/practical-projects.en-US.md
  docs/react/practical-projects.zh-CN.md
  docs/react/use-custom-date-library.en-US.md
  docs/react/use-custom-date-library.zh-CN.md
  docs/react/use-in-typescript.en-US.md
  docs/react/use-in-typescript.zh-CN.md
Labels: codeball:needs-review

#40158 chore(deps): update dependency rc-trigger to v5.3.4
  package.json
Labels: codeball:approved

#40160 fix(tour): find dom node throw wranning in strict mode feature
  package.json
Labels: codeball:approved

#40164 docs: fix recommendation dark style and update react-monaco-editor url
  docs/react/recommendation.en-US.md
  docs/react/recommendation.zh-CN.md
Labels: codeball:needs-careful-review

#40166 ci: update issues-open-check workflow
  .github/workflows/issue-open-check.yml
Labels: skip-verify-files, codeball:needs-review

#40126 site: improve overview page
  .dumi/theme/builtins/ComponentOverview/index.tsx
  .dumi/theme/builtins/IconSearch/index.tsx
  .dumi/theme/slots/Sidebar/index.tsx
  components/button/LoadingIcon.tsx
Labels: codeball:needs-careful-review

#40172 ci: fix format error
  .github/workflows/issue-open-check.yml
Labels: skip-verify-files, codeball:needs-review

#40175 style: fix Segmented item hover radius style
  components/segmented/style/index.tsx
Labels: codeball:approved

#40178 docs: Update mark of third part
  .dumi/theme/builtins/ResourceCards/index.tsx
Labels: codeball:needs-review

#40179 style: fix Segmented thumb radius size
  components/segmented/style/index.tsx
Labels: codeball:approved

#40180 demo: form advanced-search beautification style
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/form/__tests__/__snapshots__/demo.test.ts.snap
  components/form/demo/advanced-search.md
  components/form/demo/advanced-search.tsx
Labels: codeball:needs-review

#40183 fix: eslint error
  components/pagination/Pagination.tsx
  components/select/index.tsx
Labels: codeball:approved

#40184 chore: add crossorigin="anonymous" to umi.js
  .dumirc.ts
Labels: codeball:approved

#40185 chore: fix lint and refactor some site code
  .dumi/theme/slots/Header/More.tsx
  .dumi/theme/slots/Header/index.tsx
Labels: codeball:needs-review

#40171 fix(Table): fix sticky table header shadow style error
  components/table/style/fixed.ts
Labels: codeball:needs-review

#40192 chore: adjust wave pos
  components/_util/wave/WaveEffect.tsx
  scripts/post-script.js
Labels: codeball:needs-review

#38520 fix: Dropdown accidental opening of container
  components/style/core/motion/slide.less
Labels: codeball:needs-review

#40193 docs: update EN-US blog
  docs/blog/testing-migrate.en-US.md
Labels: codeball:approved

#40198 fix(site): fix the failure of website code folding function
  .dumi/theme/builtins/DemoWrapper/index.tsx
  .dumi/theme/builtins/Previewer/index.tsx
Labels: codeball:needs-careful-review

#40201 fix: Dropdown accidental opening of container
  components/style/motion/slide.ts
Labels: codeball:needs-review

#40202 demo: tag demo supports dark mode
  components/tag/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tag/__tests__/__snapshots__/demo.test.ts.snap
  components/tag/demo/animation.md
  components/tag/demo/animation.tsx
  components/tag/demo/control.md
  components/tag/demo/control.tsx
Labels: codeball:needs-review

#40212 docs: 修改dropdownRender文档描述
  components/select/demo/custom-dropdown-menu.md
Labels: codeball:approved

#40220 chore: rm bundlesize check
  .github/workflows/test.yml
  package.json
Labels: codeball:approved

#40219 chore: feature merge master
  .dumi/theme/builtins/DemoWrapper/index.tsx
  .dumi/theme/builtins/Previewer/index.tsx
  .github/workflows/test.yml
  components/select/demo/custom-dropdown-menu.md
  components/style/motion/slide.ts
  components/tag/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tag/__tests__/__snapshots__/demo.test.ts.snap
  components/tag/demo/animation.md
  components/tag/demo/animation.tsx
  components/tag/demo/control.md
  components/tag/demo/control.tsx
  docs/blog/testing-migrate.en-US.md
  package.json
Labels: BranchAutoMerge, codeball:needs-careful-review

#40231 test: add test case for en-US blog to avoid omission in translation
  components/__tests__/blog.test.ts
Labels: codeball:approved

#40222 docs: add contribution guide
  docs/react/contributing.en-US.md
  docs/react/contributing.zh-CN.md
Labels: codeball:needs-review

#39926 fix : Tabs `onEdit` Callback parameter type problem
  components/tabs/demo/custom-add-trigger.tsx
  components/tabs/demo/editable-card.tsx
Labels: codeball:needs-careful-review

#40238 💄 STYLE: fix DatePicker's next & prev icons in rtl mode
  components/date-picker/style/index.ts
Labels: codeball:needs-review

#40239 demo: calendar demo supports dark mode
  components/calendar/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/calendar/__tests__/__snapshots__/demo.test.ts.snap
  components/calendar/demo/card.md
  components/calendar/demo/card.tsx
  components/calendar/demo/customize-header.md
  components/calendar/demo/customize-header.tsx
Labels: codeball:needs-review

#40208 fix: checkbox should have line-height
  components/checkbox/style/index.ts
Labels: codeball:needs-review

#40242 docs: changelog 5.1.5
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: codeball:needs-review

#40241 type: optimization undefined type
  .dumi/theme/layouts/ResourceLayout/AffixTabs.tsx
  components/_util/motion.ts
  components/_util/styleChecker.ts
  components/affix/utils.ts
  components/anchor/demo/targetOffset.tsx
  components/cascader/index.tsx
  components/collapse/__tests__/index.test.tsx
  components/config-provider/DisabledContext.tsx
  components/config-provider/cssVariables.ts
  components/descriptions/index.tsx
  components/form/util.ts
  components/input/Input.tsx
  components/message/index.tsx
  components/notification/index.tsx
  components/skeleton/Skeleton.tsx
  components/table/hooks/useFilter/FilterDropdown.tsx
  components/tree-select/demo/basic.tsx
  components/typography/Base/index.tsx
  components/upload/UploadList/ListItem.tsx
  tests/utils.tsx
Labels: codeball:needs-careful-review

#40244 chore: feature merge master
  .dumi/theme/layouts/ResourceLayout/AffixTabs.tsx
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/__tests__/blog.test.ts
  components/_util/motion.ts
  components/_util/styleChecker.ts
  components/affix/utils.ts
  components/anchor/demo/targetOffset.tsx
  components/calendar/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/calendar/__tests__/__snapshots__/demo.test.ts.snap
  components/calendar/demo/card.md
  components/calendar/demo/card.tsx
  components/calendar/demo/customize-header.md
  components/calendar/demo/customize-header.tsx
  components/cascader/index.tsx
  components/checkbox/style/index.ts
  components/collapse/__tests__/index.test.tsx
  components/config-provider/DisabledContext.tsx
  components/config-provider/cssVariables.ts
  components/date-picker/style/index.ts
  components/descriptions/index.tsx
  components/form/util.ts
  components/image/index.zh-CN.md
  components/input/Input.tsx
  components/message/index.tsx
  components/notification/index.tsx
  components/skeleton/Skeleton.tsx
  components/table/hooks/useFilter/FilterDropdown.tsx
  components/tabs/demo/custom-add-trigger.tsx
  components/tabs/demo/editable-card.tsx
  components/tree-select/demo/basic.tsx
  components/typography/Base/index.tsx
  components/upload/UploadList/ListItem.tsx
  docs/react/contributing.en-US.md
  docs/react/contributing.zh-CN.md
  package.json
  tests/utils.tsx
Labels: BranchAutoMerge, codeball:needs-careful-review

#40248 docs: antd-mini
  .dumi/theme/slots/Footer/index.tsx
  README-ja_JP.md
  README-pt_BR.md
  README-uk_UA.md
  README-zh_CN.md
  README.md
Labels: codeball:needs-review

#40258 type: undefined type optimization
  components/button/buttonHelpers.tsx
  components/input/Input.tsx
  components/table/demo/dynamic-settings.tsx
Labels: codeball:approved

#40257 chore: adjust wrap parameter order
  components/typography/Base/index.tsx
Labels: codeball:approved

#40255 chore: adjust flattenData parameter order
  components/table/hooks/useSelection.tsx
Labels: codeball:approved

#40256 chore: adjust renderSwitcherIcon parameter order
  components/tree-select/index.tsx
  components/tree/Tree.tsx
  components/tree/__tests__/util.test.tsx
  components/tree/utils/iconUtil.tsx
Labels: codeball:approved

#40254 chore: adjust injectFilter parameter order
  components/table/hooks/useFilter/index.tsx
Labels: codeball:approved

#40253 chore: adjust getPaginationParam parameter order
  components/table/InternalTable.tsx
  components/table/hooks/usePagination.ts
Labels: codeball:approved

#40249 chore: adjust getPlaceholder parameter order
  components/date-picker/generatePicker/generateSinglePicker.tsx
  components/date-picker/util.ts
Labels: codeball:needs-careful-review

#40250 chore: adjust getRangePlaceholder parameter order
  components/date-picker/generatePicker/generateRangePicker.tsx
  components/date-picker/util.ts
Labels: codeball:approved

#40251 chore: adjust getFilledItem parameter order
  components/descriptions/index.tsx
Labels: codeball:approved

#40267 docs: fix typo word
  components/auto-complete/index.zh-CN.md
Labels: codeball:needs-review

#40268 chore: fix Menu split line style error
  components/menu/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/menu/__tests__/__snapshots__/demo.test.ts.snap
  components/menu/demo/inline.tsx
  components/menu/style/index.tsx
Labels: codeball:needs-careful-review

#40270 fix: missing translation for Brazilian Portuguese
  components/locale/pt_BR.ts
Labels: codeball:needs-review

#40273 bugfix/radio_disable_style
  components/radio/style/index.tsx
Labels: codeball:needs-review

#40269 💄 STYLE: Button's color should override child anchor's color
  components/button/style/index.ts
Labels: codeball:needs-review

#40232 fix(Message): Message global static method 'config' setting duration is invalid
  components/message/__tests__/config.test.tsx
  components/message/index.tsx
  components/message/useMessage.tsx
Labels: codeball:needs-review

#40278 docs: Report 404 for monitor
  .dumi/pages/404/index.tsx
Labels: codeball:needs-review

#40281 Bugfix/modal destroy all with context
  components/modal/__tests__/hook.test.tsx
  components/modal/destroyFns.ts
  components/modal/useModal/index.tsx
Labels: codeball:needs-careful-review

#40264 chore: add linter of not selector
  .dumi/theme/layouts/GlobalLayout.tsx
  components/date-picker/style/index.ts
  components/input-number/style/index.ts
  components/input/style/index.ts
  components/mentions/style/index.ts
  components/radio/style/index.tsx
  components/select/style/index.tsx
  components/style/compact-item-vertical.ts
  components/style/compact-item.ts
  components/tag/style/index.ts
  components/transfer/style/index.ts
  components/tree/style/index.ts
  package.json
  tests/shared/demoTest.tsx
Labels: codeball:needs-careful-review

#40292 Update practical-projects.zh-CN.md and practical-projects.en-US.md
  docs/react/practical-projects.en-US.md
  docs/react/practical-projects.zh-CN.md
Labels: codeball:needs-review

#40298 reformat/typo: removed useless ts-ignore and 'ignore' typo fix
  .dumi/theme/builtins/Previewer/fromDumiProps.tsx
  .dumi/theme/builtins/TokenTable/index.tsx
  components/card/__tests__/index.test.tsx
Labels: codeball:needs-careful-review

#40295 demo: update demo
  components/tag/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tag/__tests__/__snapshots__/demo.test.ts.snap
  components/tag/demo/colorful-inverse.md
  components/tag/demo/colorful-inverse.tsx
  components/tag/demo/colorful.md
  components/tag/demo/colorful.tsx
  components/tag/demo/status.tsx
  components/tooltip/demo/colorful.md
  components/tooltip/demo/colorful.tsx
Labels: codeball:needs-review

#40303 chore: remove useless code
  components/anchor/demo/basic.md
  components/anchor/demo/legacy-anchor.md
Labels: codeball:needs-review

#40211 fix(Breadcrumb): fix wrong overlay deprecation warning in Dropdown when use Breadcrumb with menu props
  components/breadcrumb/BreadcrumbItem.tsx
  components/breadcrumb/__tests__/Breadcrumb.test.tsx
Labels: codeball:needs-careful-review

#40306 demo: update demo
  components/tag/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tag/__tests__/__snapshots__/demo.test.ts.snap
  components/tag/demo/basic.tsx
  components/tag/demo/checkable.tsx
  components/tag/demo/control.tsx
  components/tag/demo/icon.tsx
Labels: codeball:needs-review

#40313 demo: update demo
  components/card/demo/basic.md
  components/select/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/select/__tests__/__snapshots__/demo.test.ts.snap
  components/select/demo/basic.tsx
  components/select/demo/big-data.tsx
  components/select/demo/coordinate.tsx
  components/select/demo/debug.md
  components/select/demo/debug.tsx
  components/select/demo/multiple.tsx
  components/select/demo/option-label-prop.md
  components/select/demo/option-label-prop.tsx
  components/select/demo/size.md
  components/select/demo/size.tsx
  components/select/demo/status.md
  components/select/demo/suffix.md
  components/select/demo/suffix.tsx
  components/select/index.en-US.md
  components/select/index.zh-CN.md
  components/slider/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/slider/__tests__/__snapshots__/demo.test.ts.snap
  components/slider/demo/basic.md
  components/slider/demo/input-number.tsx
  components/slider/demo/vertical.tsx
  components/switch/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/switch/__tests__/__snapshots__/demo.test.ts.snap
  components/switch/demo/basic.md
  components/switch/demo/disabled.tsx
  docs/react/introduce.en-US.md
  docs/react/introduce.zh-CN.md
Labels: codeball:needs-careful-review

#40234 feat(tooltip): tooltip support arrow prop
  components/_util/placements.ts
  components/dropdown/dropdown.tsx
  components/dropdown/style/index.ts
  components/popover/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/popover/__tests__/__snapshots__/demo.test.ts.snap
  components/popover/demo/arrow-point-at-center.md
  components/popover/demo/arrow-point-at-center.tsx
  components/popover/demo/arrow.md
  components/popover/demo/arrow.tsx
  components/popover/index.en-US.md
  components/popover/index.tsx
  components/popover/index.zh-CN.md
  components/popover/style/index.tsx
  components/style/placementArrow.ts
  components/tooltip/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tooltip/__tests__/__snapshots__/demo.test.ts.snap
  components/tooltip/__tests__/__snapshots__/tooltip.test.tsx.snap
  components/tooltip/__tests__/tooltip.test.tsx
  components/tooltip/demo/arrow-point-at-center.md
  components/tooltip/demo/arrow-point-at-center.tsx
  components/tooltip/demo/arrow.md
  components/tooltip/demo/arrow.tsx
  components/tooltip/index.en-US.md
  components/tooltip/index.tsx
  components/tooltip/index.zh-CN.md
  components/tooltip/style/index.ts
  components/tour/index.tsx
  components/tour/style/index.ts
  package.json
Labels: codeball:needs-careful-review

#40307 fix(wave): validate detached dom node's wave style
  components/_util/wave/WaveEffect.tsx
Labels: codeball:needs-review

#40291 Focus outline: lineWidth -> lineWidthBold
  components/style/index.ts
Labels: codeball:needs-review

#40328 test: update snapshot
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/dropdown/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/layout/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/layout/__tests__/__snapshots__/demo.test.ts.snap
  components/menu/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/menu/__tests__/__snapshots__/demo.test.ts.snap
  components/menu/__tests__/__snapshots__/index.test.tsx.snap
  components/table/__tests__/__snapshots__/demo-extend.test.ts.snap
  package.json
Labels: codeball:needs-review

#40327 fix: delete useless keys to prevent page jitter caused by remounting component
  components/config-provider/demo/locale.tsx
Labels: codeball:needs-review

#40336 chore: update demo style
  components/layout/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/layout/__tests__/__snapshots__/demo.test.ts.snap
  components/layout/demo/basic.tsx
Labels: codeball:needs-review

#40325 perf: only one parent selector in style
  .dumi/theme/layouts/GlobalLayout.tsx
  components/alert/style/index.ts
  components/button/style/index.ts
  components/calendar/style/index.ts
  components/checkbox/style/index.ts
  components/config-provider/style/index.ts
  components/date-picker/style/index.ts
  components/divider/style/index.ts
  components/dropdown/style/index.ts
  components/float-button/style/index.ts
  components/input/style/index.ts
  components/pagination/style/index.tsx
  components/radio/style/index.tsx
  components/segmented/style/index.tsx
  components/select/style/dropdown.tsx
  components/select/style/index.tsx
  components/slider/style/index.tsx
  components/style/index.ts
  components/tag/style/index.ts
  components/tree/style/index.ts
  components/typography/style/index.ts
  package.json
  scripts/check-cssinjs.js
  tests/shared/demoTest.tsx
Labels: codeball:needs-careful-review

#40133 fix: DatePicker animation flicking
  components/theme/themes/seed.ts
Labels: codeball:approved

#40343 docs: 5.1.6 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: codeball:needs-review

#40347 fix: Badge `findDOMNode` warning
  components/badge/ScrollNumber.tsx
  components/badge/__tests__/index.test.tsx
  components/badge/index.tsx
Labels: codeball:needs-review

#40344 fix(Input): Fixed suffix not changing color with status
  components/input/style/index.ts
Labels: codeball:needs-review

#40350 chore: Let chatgpt review PRs
  .github/workflows/main.yml
Labels: codeball:needs-review

#40358 demo: update CP demo
  components/config-provider/demo/direction.tsx
Labels: codeball:approved

#40349 fix: Dropdown submenu wrong position
  components/dropdown/style/index.ts
Labels: codeball:approved
