Repository ant-design/ant-design, pull requests merged in 2023-02, with the labels that each got.

#40461 docs: update Button 、Segmented docs
  components/button/index.en-US.md
  components/button/index.zh-CN.md
  components/segmented/index.en-US.md
  components/segmented/index.zh-CN.md
Labels: codeball:needs-review

#40478 chore: codepen input render on client
  .dumi/theme/builtins/Previewer/index.tsx
  .dumi/theme/common/ClientOnly.tsx
Labels: codeball:needs-careful-review

#40445 ts(Tree.tsx): translated chinese ts definitions to english
  components/tree/Tree.tsx
Labels: codeball:approved

#40487 fix: Progress success should have animation
  components/progress/style/index.tsx
Labels: codeball:approved

#40443 feat: Add ref to Collapse and Panel component
  components/collapse/Collapse.tsx
  components/collapse/CollapsePanel.tsx
  components/collapse/__tests__/index.test.tsx
  package.json
Labels: codeball:needs-careful-review

#40446 chore: remove Select hover undefined line width
  components/select/style/index.tsx
Labels: codeball:needs-review

#40463 fix: Table filter does not work if column has grouped header #40203
  components/table/__tests__/Table.filter.test.tsx
  components/table/hooks/useFilter/index.tsx
Labels: codeball:needs-careful-review

#40516 refactor: adjust boxShadow token
  components/card/style/index.ts
  components/message/style/index.tsx
  components/modal/style/index.tsx
  components/notification/style/index.tsx
  components/segmented/style/index.tsx
  components/tabs/style/index.ts
  components/theme/interface/alias.ts
  components/theme/util/alias.ts
  components/tour/style/index.ts
Labels: codeball:needs-review

#40524 site style code optimization
  .dumi/pages/index/components/Banner.tsx
  .dumi/pages/index/components/Theme/BackgroundImage.tsx
  .dumi/pages/index/index.tsx
  .dumi/theme/builtins/Alert/index.tsx
  .dumi/theme/layouts/ResourceLayout/AffixTabs.tsx
  .dumi/theme/layouts/ResourceLayout/index.tsx
  .dumi/theme/layouts/SidebarLayout/index.tsx
  .dumi/theme/slots/Footer/AdditionalInfo.tsx
  .dumi/theme/slots/Footer/index.tsx
  .dumi/theme/slots/Header/Logo.tsx
  .dumi/theme/slots/Header/More.tsx
  .dumi/theme/slots/Header/SwitchBtn.tsx
  .dumi/theme/slots/Header/index.tsx
Labels: codeball:needs-careful-review

#40521 fix: optimize arrow style
  components/date-picker/style/index.ts
  components/dropdown/style/index.ts
  components/style/placementArrow.ts
  components/style/roundedArrow.ts
  components/theme/util/alias.ts
Labels: codeball:needs-review

#40526 feat: slider add support for disable keyboard events
  components/slider/index.en-US.md
  components/slider/index.tsx
  components/slider/index.zh-CN.md
  package.json
Labels: codeball:needs-careful-review

#40536 docs(select): make size demo check the default value
  components/select/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/select/__tests__/__snapshots__/demo.test.ts.snap
  components/select/demo/size.tsx
Labels: codeball:needs-review

#40540 demo: update demo
  components/mentions/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/mentions/__tests__/__snapshots__/demo.test.ts.snap
  components/mentions/demo/form.tsx
Labels: codeball:needs-review

#40539 fix: fix site style
  components/mentions/demo/async.md
  components/mentions/index.en-US.md
  components/mentions/index.zh-CN.md
Labels: codeball:needs-review

#40538 refactoring: use React.createRef replace ref function
  components/affix/index.tsx
  components/button/__tests__/index.test.tsx
  components/calendar/index.ts
  components/checkbox/__tests__/group.test.tsx
  components/slider/__tests__/index.test.tsx
  tests/utils.tsx
Labels: codeball:needs-careful-review

#40544 docs: update api
  components/checkbox/demo/group.tsx
  components/checkbox/index.en-US.md
  components/checkbox/index.zh-CN.md
Labels: codeball:needs-review

#40549 fix: fix DatePicker input style error
  components/date-picker/style/index.ts
Labels: codeball:approved

#40550 fix site style
  .dumi/theme/layouts/SidebarLayout/index.tsx
  components/mentions/index.en-US.md
  components/mentions/index.zh-CN.md
  components/table/index.en-US.md
  components/table/index.zh-CN.md
Labels: codeball:needs-review

#40554 fix(space): fix ant-space-item selector
  components/space/__tests__/index.test.tsx
  components/space/style/index.tsx
Labels: codeball:needs-review

#40413 Accessibility fix: aria-label cannot be used with role="presentation".
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/table/__tests__/__snapshots__/Table.sorter.test.tsx.snap
  components/table/__tests__/__snapshots__/Table.test.tsx.snap
  components/table/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/table/__tests__/__snapshots__/demo.test.ts.snap
  components/table/hooks/useSorter.tsx
Labels: codeball:needs-careful-review

#40563 chore: upgrade site && update pr-template
  .dumi/theme/builtins/Previewer/index.tsx
  .github/PULL_REQUEST_TEMPLATE/pr_cn.md
Labels: codeball:needs-review

#40558 chore: lock eslint-plugin-compat
  package.json
Labels: codeball:approved

#40575 branch: merge master into feature
  components/segmented/__tests__/index.test.tsx
  package.json
Labels: BranchAutoMerge, codeball:needs-review

#40579 Add support for railStyle prop to Slider component
  components/slider/index.en-US.md
  components/slider/index.tsx
Labels: codeball:needs-review

#40556 demo: remove immutability-helper from the project
  components/upload/demo/drag-sorting.tsx
  package.json
Labels: codeball:needs-review

#40584 style(Empty): fix text color in dark theme
  components/empty/style/index.ts
Labels: codeball:needs-review

#40585 type: update upload fileList type
  components/upload/utils.tsx
Labels: codeball:approved

#40583 chore: master merge feature again
  components/slider/index.en-US.md
  components/slider/index.tsx
  components/upload/demo/drag-sorting.tsx
  package.json
Labels: BranchAutoMerge, codeball:needs-careful-review

#40613 feat: support indicatorsRender
  components/tour/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tour/__tests__/__snapshots__/demo.test.tsx.snap
  components/tour/__tests__/__snapshots__/index.test.tsx.snap
  components/tour/__tests__/index.test.tsx
  components/tour/demo/indicator.md
  components/tour/demo/indicator.tsx
  components/tour/index.en-US.md
  components/tour/index.tsx
  components/tour/index.zh-CN.md
  components/tour/interface.ts
  components/tour/panelRender.tsx
  components/tour/style/index.ts
Labels: codeball:needs-review

#40475 fix(Spin): not close Spin immediately when using delay
  components/spin/__tests__/delay.test.tsx
  components/spin/index.tsx
Labels: codeball:needs-careful-review

#40615 docs: revert docs
  components/timeline/index.en-US.md
  components/timeline/index.zh-CN.md
Labels: codeball:needs-careful-review

#40614 chore: merge feature into master
  components/timeline/Timeline.tsx
  components/timeline/TimelineItem.tsx
  components/timeline/TimelineItemList.tsx
  components/timeline/__tests__/index.test.tsx
  components/timeline/demo/alternate.tsx
  components/timeline/demo/basic.tsx
  components/timeline/demo/color.tsx
  components/timeline/demo/custom.tsx
  components/timeline/demo/label.tsx
  components/timeline/demo/pending.tsx
  components/timeline/demo/right.tsx
  components/timeline/demo/wireframe.tsx
  components/timeline/index.en-US.md
  components/timeline/index.zh-CN.md
  components/timeline/useItems.tsx
  components/tour/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tour/__tests__/__snapshots__/demo.test.tsx.snap
  components/tour/__tests__/__snapshots__/index.test.tsx.snap
  components/tour/__tests__/index.test.tsx
  components/tour/demo/indicator.md
  components/tour/demo/indicator.tsx
  components/tour/index.en-US.md
  components/tour/index.tsx
  components/tour/index.zh-CN.md
  components/tour/interface.ts
  components/tour/panelRender.tsx
  components/tour/style/index.ts
Labels: BranchAutoMerge

#40659 chore: merge master into feature
  .dumi/theme/builtins/Previewer/index.tsx
  .dumi/theme/common/GlobalStyles.tsx
  .dumi/theme/common/styles/SearchBar.tsx
  .dumi/theme/common/styles/index.ts
  .dumi/theme/slots/Content/index.tsx
  .dumi/theme/slots/Header/index.tsx
  .github/workflows/codeball.yml
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  README.md
  components/date-picker/demo/format.md
  components/date-picker/demo/format.tsx
  components/date-picker/style/index.ts
  components/empty/style/index.ts
  components/locale/ru_RU.ts
  components/locale/uk_UA.ts
  components/spin/__tests__/delay.test.tsx
  components/spin/index.tsx
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/theme/interface/seeds.ts
  components/theme/themes/seed.ts
  components/timeline/index.en-US.md
  components/timeline/index.zh-CN.md
  components/tour/style/index.ts
  components/typography/style/mixins.ts
  components/upload/interface.tsx
  components/upload/utils.tsx
  package.json
  scripts/check-site.js
Labels: BranchAutoMerge

#40626 chore: fix test failed(4.x)
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/dropdown/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/layout/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/layout/__tests__/__snapshots__/demo.test.ts.snap
  components/menu/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/menu/__tests__/__snapshots__/demo.test.ts.snap
  components/menu/__tests__/__snapshots__/index.test.tsx.snap
  components/segmented/__tests__/index.test.tsx
  components/table/__tests__/Table.filter.test.tsx
  components/table/__tests__/Table.test.tsx
  components/table/__tests__/__snapshots__/demo-extend.test.ts.snap
  package.json
Labels: codeball:needs-careful-review

#40561 docs: changelog 4.24.8
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: codeball:needs-careful-review

#40215 feat: add useConfig hook to ConfigProvider
  components/config-provider/__tests__/useConfig.test.tsx
  components/config-provider/demo/useConfig.md
  components/config-provider/demo/useConfig.tsx
  components/config-provider/hooks/useConfig.ts
  components/config-provider/index.en-US.md
  components/config-provider/index.tsx
  components/config-provider/index.zh-CN.md
Labels: codeball:needs-careful-review

#40458 feat(App): add message & notification options (#40456)
  components/app/__tests__/index.test.tsx
  components/app/context.ts
  components/app/index.en-US.md
  components/app/index.tsx
  components/app/index.zh-CN.md
  components/notification/index.en-US.md
  components/notification/index.zh-CN.md
Labels: codeball:needs-careful-review

#40771 chore: feature merge master
  components/cascader/index.en-US.md
  components/cascader/index.zh-CN.md
  components/date-picker/style/index.ts
  components/locale/fr_FR.ts
  components/radio/__tests__/radio.test.tsx
  components/radio/radio.tsx
  components/skeleton/style/index.tsx
  components/tree-select/index.en-US.md
  components/tree-select/index.zh-CN.md
  docs/blog/tooltip-align.en-US.md
  docs/blog/tooltip-align.zh-CN.md
  docs/spec/cases.en-US.md
  docs/spec/cases.zh-CN.md
  package.json
Labels: BranchAutoMerge

#40369 chore: add lint cache
  .eslintignore
  package.json
Labels: codeball:needs-review

#40843 chore: feature merge master
  .dumi/theme/builtins/Previewer/CodePreviewer.tsx
  components/rate/style/index.tsx
  components/timeline/TimelineItemList.tsx
  components/timeline/__tests__/index.test.tsx
  components/upload/demo/drag-sorting.tsx
  docs/spec/visual.en-US.md
  docs/spec/visual.zh-CN.md
Labels: BranchAutoMerge

#40823 style: Checkbox should use @border-radius-sm
  components/style/themes/default.less
Labels: codeball:needs-review

#40889 chore: merge master into feature
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/pr_cn.md
  .stylelintrc.js
  components/affix/index.tsx
  components/affix/utils.ts
  components/badge/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/badge/__tests__/__snapshots__/demo.test.ts.snap
  components/badge/__tests__/__snapshots__/index.test.tsx.snap
  components/badge/index.tsx
  components/badge/style/index.ts
  components/breadcrumb/BreadcrumbSeparator.tsx
  components/breadcrumb/__tests__/__snapshots__/Breadcrumb.test.tsx.snap
  components/breadcrumb/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/breadcrumb/__tests__/__snapshots__/demo.test.ts.snap
  components/calendar/__tests__/index.test.tsx
  components/calendar/generateCalendar.tsx
  components/config-provider/index.tsx
  components/date-picker/generatePicker/generateRangePicker.tsx
  components/date-picker/generatePicker/generateSinglePicker.tsx
  components/descriptions/__tests__/index.test.tsx
  components/descriptions/index.tsx
  components/empty/index.tsx
  components/form/FormItemLabel.tsx
  components/locale-provider/LocaleReceiver.ts
  components/locale/LocaleReceiver.ts
  components/locale/useLocale.ts
  components/menu/__tests__/__snapshots__/index.test.tsx.snap
  components/menu/__tests__/index.test.tsx
  components/message/index.tsx
  components/modal/ConfirmDialog.tsx
  components/modal/Modal.tsx
  components/modal/PurePanel.tsx
  components/modal/useModal/HookModal.tsx
  components/notification/index.tsx
  components/pagination/Pagination.tsx
  components/popconfirm/PurePanel.tsx
  components/qrcode/index.tsx
  components/steps/demo/clickable.tsx
  components/style/index.ts
  components/table/InternalTable.tsx
  components/table/__tests__/Table.test.tsx
  components/tour/panelRender.tsx
  components/transfer/ListItem.tsx
  components/transfer/index.tsx
  components/typography/Base/index.tsx
  components/upload/Upload.tsx
  docs/blog/issue-helper.en-US.md
  docs/blog/issue-helper.zh-CN.md
  package.json
  tests/shared/rtlTest.tsx
Labels: BranchAutoMerge

#40533 fix: fix `ConfigProvider` form validation message order
  components/config-provider/__tests__/form.test.tsx
  components/config-provider/index.tsx
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: codeball:needs-careful-review
