Repository ant-design/ant-design, pull requests merged in 2023-04, with the labels that each got.

#41586 chore: merge master into feature
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/pr_cn.md
  components/breadcrumb/index.en-US.md
  components/breadcrumb/index.zh-CN.md
  components/cascader/index.tsx
  components/checkbox/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/checkbox/__tests__/__snapshots__/demo.test.tsx.snap
  components/checkbox/demo/debug-line.tsx
  components/checkbox/style/index.ts
  components/collapse/Collapse.tsx
  components/drawer/DrawerPanel.tsx
  components/dropdown/dropdown.tsx
  components/form/FormItem/ItemHolder.tsx
  components/form/__tests__/index.test.tsx
  components/mentions/index.tsx
  components/popconfirm/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/popconfirm/__tests__/__snapshots__/demo.test.tsx.snap
  components/popconfirm/demo/basic.tsx
  components/popconfirm/demo/dynamic-trigger.tsx
  components/popconfirm/demo/icon.tsx
  components/popconfirm/demo/locale.tsx
  components/select/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/select/__tests__/__snapshots__/demo.test.tsx.snap
  components/select/demo/search.tsx
  components/select/index.tsx
  components/slider/SliderTooltip.tsx
  components/slider/__tests__/index.test.tsx
  components/tooltip/__tests__/tooltip.test.tsx
  components/tooltip/index.tsx
  components/tour/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tour/__tests__/__snapshots__/index.test.tsx.snap
  components/tour/panelRender.tsx
  components/tree-select/index.tsx
  components/tree/Tree.tsx
  components/tree/__tests__/util.test.tsx
  components/tree/utils/iconUtil.tsx
  package.json
  tests/shared/demoTest.tsx
Labels: BranchAutoMerge

#41606 chore: merge master into feature
  .circleci/config.yml
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/form/FormItem/ItemHolder.tsx
  components/form/__tests__/index.test.tsx
  package.json
  scripts/check-cssinjs.js
  scripts/collect-token-statistic.js
  scripts/generate-cssinjs.js
Labels: BranchAutoMerge

#41622 chore: feature merge master
  components/cascader/index.tsx
  components/qrcode/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/qrcode/__tests__/__snapshots__/demo.test.ts.snap
  components/qrcode/demo/base.tsx
  components/select/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/select/__tests__/__snapshots__/demo.test.tsx.snap
  components/select/demo/debug-flip-shift.md
  components/select/demo/debug-flip-shift.tsx
  components/select/index.en-US.md
  components/select/index.tsx
  components/select/index.zh-CN.md
  components/select/useBuiltinPlacements.tsx
  components/tree-select/index.tsx
  docs/react/use-custom-date-library.en-US.md
  docs/react/use-custom-date-library.zh-CN.md
  package.json
  scripts/pre-publish-notice.js
Labels: BranchAutoMerge

#41692 chore: merge master into feature
  components/badge/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/badge/__tests__/__snapshots__/demo.test.ts.snap
  components/badge/demo/ribbon.tsx
  components/badge/style/index.ts
  components/button/button.tsx
  components/form/FormItem/ItemHolder.tsx
  components/form/__tests__/index.test.tsx
  components/grid/__tests__/index.test.tsx
  components/grid/style/index.ts
  components/mentions/style/index.ts
  components/modal/demo/modal-render.tsx
  components/notification/index.en-US.md
  components/notification/index.zh-CN.md
  components/table/InternalTable.tsx
  components/table/Table.tsx
  components/table/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/table/__tests__/__snapshots__/demo.test.ts.snap
  components/table/demo/selections-debug.md
  components/table/demo/selections-debug.tsx
  components/table/hooks/useSelection.tsx
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/table/style/selection.ts
  docs/react/use-custom-date-library.en-US.md
  docs/react/use-custom-date-library.zh-CN.md
  docs/resources.en-US.md
  docs/resources.zh-CN.md
  package.json
Labels: BranchAutoMerge

#40326 style: remove Space font style
  components/space/style/index.tsx
  components/theme/util/genComponentStyleHook.ts
Labels: codeball:needs-review

#41731 feature merge master
  components/affix/index.tsx
  components/alert/index.tsx
  components/avatar/__tests__/Avatar.test.tsx
  components/avatar/__tests__/__snapshots__/Avatar.test.tsx.snap
  components/avatar/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/avatar/__tests__/__snapshots__/demo.test.tsx.snap
  components/avatar/avatar.tsx
  components/avatar/demo/group.tsx
  components/card/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/card/__tests__/__snapshots__/demo.test.ts.snap
  components/card/demo/loading.tsx
  components/card/demo/meta.tsx
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/config-provider/__tests__/components.test.tsx
  components/empty/style/index.ts
  components/form/FormItem/ItemHolder.tsx
  components/form/FormItem/index.tsx
  components/form/FormItemLabel.tsx
  components/form/__tests__/index.test.tsx
  components/list/__tests__/Item.test.tsx
  components/list/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/list/__tests__/__snapshots__/demo.test.ts.snap
  components/list/demo/basic.tsx
  components/list/demo/pagination.tsx
  components/list/demo/vertical.tsx
  components/list/style/index.ts
  components/locale/th_TH.ts
  components/pagination/style/index.tsx
  components/popconfirm/__tests__/__snapshots__/index.test.tsx.snap
  components/popconfirm/__tests__/index.test.tsx
  components/segmented/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/segmented/__tests__/__snapshots__/demo.test.ts.snap
  components/segmented/demo/custom.tsx
  components/select/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/select/__tests__/__snapshots__/demo.test.tsx.snap
  components/select/demo/search.tsx
  components/select/style/dropdown.tsx
  components/select/style/single.tsx
  components/skeleton/demo/list.tsx
  components/space/style/index.tsx
  components/steps/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/steps/__tests__/__snapshots__/demo.test.ts.snap
  components/steps/demo/inline.tsx
  components/theme/util/genComponentStyleHook.ts
  components/tree/__tests__/index.test.tsx
  components/tree/utils/iconUtil.tsx
  docs/react/practical-projects.zh-CN.md
  package.json
  scripts/generate-cssinjs.js
Labels: BranchAutoMerge

#41980 chore: prevent ci from running on fork
  .github/workflows/mock-project-build.yml
  .github/workflows/pr-check-ci.yml
Labels: skip-verify-files
