Repository ant-design/ant-design, pull requests merged in 2023-05, with the labels that each got.

#42127 chore: feature merge master
  .github/workflows/test.yml
  AUTHORS.txt
  components/anchor/Anchor.tsx
  components/breadcrumb/Breadcrumb.tsx
  components/breadcrumb/BreadcrumbItem.tsx
  components/breadcrumb/__tests__/__snapshots__/itemRender.test.tsx.snap
  components/breadcrumb/__tests__/itemRender.test.tsx
  components/breadcrumb/index.en-US.md
  components/breadcrumb/index.zh-CN.md
  components/breadcrumb/useItemRender.tsx
  components/breadcrumb/useItems.ts
  components/button/button.tsx
  components/space/Item.tsx
  components/tabs/demo/position.tsx
  components/theme/util/genPresetColor.ts
  components/transfer/__tests__/index.test.tsx
  components/transfer/index.tsx
  components/transfer/list.tsx
  components/upload/index.ts
  components/upload/interface.ts
  package.json
  scripts/argos-upload.ts
  scripts/batch/convert-demo.js
  scripts/check-commit.ts
  scripts/check-cssinjs.ts
  scripts/check-demo.js
  scripts/check-site.ts
  scripts/check-ts-demo.ts
  scripts/check-version-md.ts
  scripts/collect-token-statistic.ts
  scripts/css-variable-sync.js
  scripts/generate-authors.ts
  scripts/generate-cssinjs.js
  scripts/generate-cssinjs.ts
  scripts/generate-token-meta.ts
  scripts/generate-version.ts
  scripts/post-script.js
  scripts/test-all.sh
  scripts/tmp-mv-dumi-site.js
  scripts/update-rc.js
  tsconfig.node.json
Labels: BranchAutoMerge

#42221 chore: feature merge master
  .circleci/config.yml
  .jest.js
  components/affix/index.zh-CN.md
  components/anchor/index.zh-CN.md
  components/card/Card.tsx
  components/card/__tests__/index.test.tsx
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/config-provider/__tests__/components.test.tsx
  components/grid/index.zh-CN.md
  components/input-number/index.zh-CN.md
  components/input/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/input/__tests__/__snapshots__/demo.test.tsx.snap
  components/input/demo/compact-style.tsx
  components/input/style/index.ts
  components/locale/bg_BG.ts
  components/pagination/Pagination.tsx
  components/tooltip/index.tsx
  package.json
  scripts/check-cssinjs.ts
  scripts/collect-token-statistic.ts
  scripts/generate-cssinjs.ts
Labels: BranchAutoMerge

#42231 chore: sync master into feature
  components/checkbox/style/index.ts
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/space/Compact.tsx
  components/space/__tests__/space-compact.test.tsx
  components/tag/index.tsx
Labels: BranchAutoMerge

#42245 chore: fix github action typo (disscustion -> discussion)
  .github/workflows/discussion-open-check.yml
Labels: skip-verify-files

#40418 fix(divider): no dashed line in vertical
  components/divider/style/index.ts
Labels: codeball:needs-review

#42343 chore: merge master into feature
  .dumi/theme/builtins/IconSearch/index.tsx
  .husky/.gitignore
  components/color-picker/ColorPicker.tsx
  components/color-picker/ColorPickerPanel.tsx
  components/color-picker/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/color-picker/__tests__/__snapshots__/demo.test.ts.snap
  components/color-picker/components/ColorAlphaInput.tsx
  components/color-picker/components/ColorClear.tsx
  components/color-picker/components/ColorHsbInput.tsx
  components/color-picker/components/ColorInput.tsx
  components/color-picker/components/ColorPresets.tsx
  components/color-picker/components/ColorRgbInput.tsx
  components/color-picker/components/ColorTrigger.tsx
  components/color-picker/demo/base.tsx
  components/color-picker/demo/format.tsx
  components/color-picker/demo/pure-panel.tsx
  components/color-picker/demo/trigger.tsx
  components/color-picker/hooks/useColorState.ts
  components/color-picker/index.en-US.md
  components/color-picker/index.ts
  components/color-picker/index.zh-CN.md
  components/color-picker/interface.ts
  components/color-picker/style/index.ts
  components/color-picker/style/picker.ts
  components/divider/style/index.ts
  components/progress/Circle.tsx
  components/progress/__tests__/index.test.tsx
Labels: BranchAutoMerge

#42469 chore: feature merge master
  components/color-picker/ColorPicker.tsx
  components/color-picker/ColorPickerPanel.tsx
  components/color-picker/interface.ts
  components/tooltip/style/index.ts
  package.json
Labels: BranchAutoMerge

#42509 chore: feature merge master
  components/affix/__tests__/Affix.test.tsx
  components/affix/index.tsx
  components/affix/utils.ts
  components/color-picker/ColorPicker.tsx
  components/color-picker/ColorPickerPanel.tsx
  components/color-picker/__tests__/index.test.tsx
  components/form/demo/layout.tsx
  components/layout/__tests__/__snapshots__/demo.test.ts.snap
  components/layout/demo/basic.tsx
  components/select/index.tsx
  components/table/style/filter.ts
  docs/react/migration-v5.en-US.md
  package.json
Labels: BranchAutoMerge

#42598 chore: merge master into feature
  components/date-picker/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/input-number/style/index.ts
Labels: BranchAutoMerge

#42668 chore: feature merge master
  .dumi/theme/builtins/ComponentTokenTable/index.tsx
  .github/workflows/pr-stat.yml
  .npmrc
  components/card/style/index.ts
  components/checkbox/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/checkbox/__tests__/__snapshots__/demo.test.tsx.snap
  components/checkbox/demo/debug-line.tsx
  components/checkbox/style/index.ts
  components/color-picker/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/color-picker/__tests__/__snapshots__/demo.test.ts.snap
  components/color-picker/demo/trigger-event.md
  components/color-picker/demo/trigger-event.tsx
  components/color-picker/index.en-US.md
  components/color-picker/index.zh-CN.md
  components/config-provider/index.tsx
  components/date-picker/locale/lt_LT.ts
  components/form/Form.tsx
  components/form/context.tsx
  components/locale/lt_LT.ts
  components/modal/__tests__/confirm.test.tsx
  components/modal/confirm.tsx
  components/select/style/multiple.tsx
  components/tag/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tag/__tests__/__snapshots__/demo.test.ts.snap
  components/tag/demo/borderless.tsx
  components/tag/style/index.ts
  components/tree/style/index.ts
  docs/react/contributing.en-US.md
  docs/react/contributing.zh-CN.md
  package.json
Labels: BranchAutoMerge

#42680 chore: merge master into feature
  .dumi/theme/builtins/Previewer/CodePreviewer.tsx
  .dumi/theme/plugin.ts
  components/empty/empty.tsx
  components/image/index.zh-CN.md
  components/image/style/index.ts
Labels: BranchAutoMerge
