Repository ant-design/ant-design, pull requests merged in 2023-06, with the labels that each got.

#42819 chore: merge master into feature
  .dumi/hooks/useMenu.tsx
  .dumi/theme/layouts/ResourceLayout/AffixTabs.tsx
  .dumi/theme/slots/Content/index.tsx
  .github/workflows/site-deploy.yml
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/_util/scrollTo.ts
  components/affix/index.en-US.md
  components/affix/index.zh-CN.md
  components/anchor/style/index.ts
  components/auto-complete/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/auto-complete/__tests__/__snapshots__/demo.test.ts.snap
  components/auto-complete/demo/borderless.md
  components/auto-complete/demo/borderless.tsx
  components/auto-complete/index.en-US.md
  components/auto-complete/index.zh-CN.md
  components/cascader/demo/lazy.tsx
  components/color-picker/ColorPicker.tsx
  components/color-picker/ColorPickerPanel.tsx
  components/color-picker/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/color-picker/__tests__/__snapshots__/demo.test.ts.snap
  components/color-picker/__tests__/index.test.tsx
  components/color-picker/demo/trigger-event.md
  components/color-picker/demo/trigger.tsx
  components/color-picker/index.en-US.md
  components/color-picker/index.zh-CN.md
  components/color-picker/style/index.ts
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/date-picker/locale/example.json
  components/divider/__tests__/index.test.tsx
  components/divider/index.en-US.md
  components/divider/index.tsx
  components/divider/index.zh-CN.md
  components/dropdown/dropdown.tsx
  components/dropdown/index.ts
  components/menu/__tests__/index.test.tsx
  components/menu/menu.tsx
  components/popconfirm/demo/placement.md
  components/progress/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/progress/__tests__/__snapshots__/demo.test.ts.snap
  components/progress/__tests__/__snapshots__/index.test.tsx.snap
  components/progress/__tests__/index.test.tsx
  components/progress/index.tsx
  components/progress/progress.tsx
  components/steps/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/steps/__tests__/__snapshots__/demo.test.ts.snap
  components/table/demo/drag-sorting-handler.tsx
  components/table/demo/drag-sorting.tsx
  components/tabs/index.en-US.md
  components/tabs/index.zh-CN.md
  components/upload/UploadList/ListItem.tsx
  components/upload/interface.ts
  docs/spec/data-format.zh-CN.md
  docs/spec/form-page.en-US.md
  docs/spec/form-page.zh-CN.md
  package.json
  webpack.config.js
Labels: BranchAutoMerge

#42975 chore: merge master into feature
  .dumi/theme/builtins/InlinePopover/index.tsx
  .dumi/theme/builtins/InstallDependencies/index.tsx
  .dumi/theme/builtins/InstallDependencies/npm.tsx
  .dumi/theme/builtins/InstallDependencies/pnpm.tsx
  .dumi/theme/builtins/InstallDependencies/yarn.tsx
  .dumi/theme/builtins/Previewer/CodePreviewer.tsx
  .dumi/theme/common/GlobalStyles.tsx
  .dumi/theme/common/styles/InlineCard.tsx
  .dumi/theme/common/styles/Markdown.tsx
  components/button/__tests__/index.test.tsx
  components/button/style/index.ts
  components/drawer/style/index.ts
  components/float-button/FloatButtonGroup.tsx
  components/float-button/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/float-button/__tests__/__snapshots__/demo.test.ts.snap
  components/float-button/__tests__/group.test.tsx
  components/float-button/demo/controlled.md
  components/float-button/demo/controlled.tsx
  components/float-button/demo/group-menu.tsx
  components/float-button/index.en-US.md
  components/float-button/index.zh-CN.md
  docs/react/use-in-typescript.en-US.md
  docs/react/use-in-typescript.zh-CN.md
  docs/react/use-with-create-react-app.en-US.md
  docs/react/use-with-create-react-app.zh-CN.md
  docs/react/use-with-next.en-US.md
  docs/react/use-with-next.zh-CN.md
  docs/react/use-with-typescript.en-US.md
  docs/react/use-with-typescript.zh-CN.md
  docs/react/use-with-vite.en-US.md
  docs/react/use-with-vite.zh-CN.md
  docs/spec/data-format.zh-CN.md
  docs/spec/feedback.zh-CN.md
  docs/spec/lightweight.en-US.md
  docs/spec/lightweight.zh-CN.md
Labels: BranchAutoMerge

#43179 fix: first open timepicker right panel position error
  components/date-picker/style/index.less
Labels: 4.x

#43207 refactor: ConfigProvider form dependency inversion for v4
  components/config-provider/index.tsx
  components/form/Form.tsx
  components/form/validateMessagesContext.tsx
Labels: 4.x, 📦 Bundlesize

#43223 chore: merge master into feature
  .dumi/theme/slots/Content/ColumnCard.tsx
  .dumi/theme/slots/Content/JuejinLogo.tsx
  .dumi/theme/slots/Content/index.tsx
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
  components/upload/Upload.tsx
  components/upload/__tests__/upload.test.tsx
  docs/blog/tree-shaking.en-US.md
  docs/blog/tree-shaking.zh-CN.md
  docs/blog/why-not-static.en-US.md
  docs/blog/why-not-static.zh-CN.md
  docs/react/faq.en-US.md
  docs/react/faq.zh-CN.md
  package.json
  scripts/post-script.js
Labels: BranchAutoMerge
