Repository ant-design/ant-design, pull requests merged in 2023-03, with the labels that each got.

#40304 style(Table): Add the rowScope style
  components/table/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/table/__tests__/__snapshots__/demo.test.ts.snap
  components/table/demo/colspan-rowspan.tsx
  components/table/style/bordered.ts
  components/table/style/empty.ts
  components/table/style/expand.ts
  components/table/style/index.ts
  components/table/style/size.ts
Labels: codeball:needs-review

#41065 chore: merge master into feature
  .dumi/theme/builtins/Previewer/CodePreviewer.tsx
  .dumi/theme/slots/Content/index.tsx
  components/message/style/index.tsx
  components/table/InternalTable.tsx
  components/table/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/table/__tests__/__snapshots__/demo.test.ts.snap
  components/table/demo/colspan-rowspan.tsx
  components/table/hooks/usePagination.ts
  components/table/hooks/useSelection.tsx
  components/table/style/bordered.ts
  components/table/style/empty.ts
  components/table/style/expand.ts
  components/table/style/index.ts
  components/table/style/size.ts
Labels: BranchAutoMerge

#40543 feat: breadcrumb support items
  components/breadcrumb/Breadcrumb.tsx
  components/breadcrumb/BreadcrumbItem.tsx
  components/breadcrumb/__tests__/Breadcrumb.test.tsx
  components/breadcrumb/__tests__/__snapshots__/Breadcrumb.test.tsx.snap
  components/breadcrumb/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/breadcrumb/__tests__/__snapshots__/demo.test.ts.snap
  components/breadcrumb/__tests__/__snapshots__/router.test.tsx.snap
  components/breadcrumb/demo/basic.tsx
  components/breadcrumb/demo/debug-routes.md
  components/breadcrumb/demo/debug-routes.tsx
  components/breadcrumb/demo/overlay.tsx
  components/breadcrumb/demo/react-router.tsx
  components/breadcrumb/demo/separator-component.md
  components/breadcrumb/demo/separator-component.tsx
  components/breadcrumb/demo/separator.tsx
  components/breadcrumb/demo/withIcon.tsx
  components/breadcrumb/index.en-US.md
  components/breadcrumb/index.ts
  components/breadcrumb/index.zh-CN.md
  components/breadcrumb/useItems.ts
Labels: codeball:needs-careful-review

#40422 fix(select): Fix Typography component is not centered in the Select component
  components/select/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/select/__tests__/__snapshots__/demo.test.tsx.snap
  components/select/demo/option-label-center.md
  components/select/demo/option-label-center.tsx
  components/select/index.en-US.md
  components/select/index.zh-CN.md
  components/select/style/dropdown.tsx
  components/select/style/index.tsx
Labels: codeball:needs-review

#41075 chore: merge feature into feature
  components/auto-complete/index.tsx
  components/breadcrumb/Breadcrumb.tsx
  components/breadcrumb/BreadcrumbItem.tsx
  components/breadcrumb/__tests__/Breadcrumb.test.tsx
  components/breadcrumb/__tests__/__snapshots__/Breadcrumb.test.tsx.snap
  components/breadcrumb/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/breadcrumb/__tests__/__snapshots__/demo.test.ts.snap
  components/breadcrumb/__tests__/__snapshots__/router.test.tsx.snap
  components/breadcrumb/demo/basic.tsx
  components/breadcrumb/demo/debug-routes.md
  components/breadcrumb/demo/debug-routes.tsx
  components/breadcrumb/demo/overlay.tsx
  components/breadcrumb/demo/react-router.tsx
  components/breadcrumb/demo/separator-component.md
  components/breadcrumb/demo/separator-component.tsx
  components/breadcrumb/demo/separator.tsx
  components/breadcrumb/demo/withIcon.tsx
  components/breadcrumb/index.en-US.md
  components/breadcrumb/index.ts
  components/breadcrumb/index.zh-CN.md
  components/breadcrumb/useItems.ts
  components/cascader/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/cascader/__tests__/__snapshots__/demo.test.tsx.snap
  components/cascader/__tests__/__snapshots__/index.test.tsx.snap
  components/cascader/index.tsx
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/form/__tests__/__snapshots__/demo.test.tsx.snap
  components/select/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/select/__tests__/__snapshots__/demo.test.tsx.snap
  components/select/index.tsx
  components/select/useShowArrow.ts
  components/space/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/space/__tests__/__snapshots__/demo.test.tsx.snap
  components/tree-select/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tree-select/__tests__/__snapshots__/demo.test.tsx.snap
  components/tree-select/__tests__/__snapshots__/index.test.tsx.snap
  components/tree-select/index.tsx
Labels: BranchAutoMerge

#41114 chore: merge master into feature
  .dumi/theme/builtins/ComponentOverview/index.tsx
  .dumi/theme/common/BehaviorMap/index.tsx
  .dumi/theme/common/Color/ColorPalettes.tsx
  .dumi/theme/common/Color/Palette.tsx
  .dumi/theme/common/styles/Demo.tsx
  .dumi/theme/common/styles/Markdown.tsx
  .dumi/theme/slots/Content/index.tsx
  .github/workflows/sync-gitee.yml
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/config-provider/demo/locale.tsx
  components/popover/style/index.tsx
  components/qrcode/index.en-US.md
  components/qrcode/index.zh-CN.md
  components/rate/index.tsx
  components/rate/style/index.tsx
  components/select/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/select/__tests__/__snapshots__/demo.test.tsx.snap
  components/select/demo/option-label-center.md
  components/select/demo/option-label-center.tsx
  components/select/index.en-US.md
  components/select/index.zh-CN.md
  components/select/style/dropdown.tsx
  components/select/style/index.tsx
  components/style/presetColor.tsx
  components/theme/interface/index.ts
  components/theme/interface/maps/index.ts
  components/theme/interface/presetColors.ts
  components/theme/themes/dark/index.ts
  components/theme/themes/default/index.ts
  components/tour/index.zh-CN.md
  components/upload/Upload.tsx
  components/upload/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/upload/__tests__/__snapshots__/demo.test.ts.snap
  components/upload/__tests__/upload.test.tsx
  components/upload/demo/drag.tsx
  components/upload/utils.ts
  components/upload/utils.tsx
  docs/blog/to-be-collaborator.en-US.md
  docs/blog/to-be-collaborator.zh-CN.md
  package.json
Labels: BranchAutoMerge

#41344 chore: merge master into feature
  components/anchor/Anchor.tsx
  components/anchor/__tests__/Anchor.test.tsx
  components/anchor/style/index.ts
  components/breadcrumb/Breadcrumb.tsx
  components/breadcrumb/__tests__/Breadcrumb.test.tsx
  components/button/style/index.ts
  components/date-picker/demo/select-in-range.tsx
  components/divider/index.tsx
  components/empty/empty.tsx
  components/empty/simple.tsx
  components/grid/style/index.ts
  components/index.ts
  components/input/TextArea.tsx
  components/qrcode/index.tsx
  components/statistic/index.tsx
  components/tabs/style/index.ts
  components/theme/interface/alias.ts
  components/theme/interface/maps/colors.ts
  components/theme/interface/maps/font.ts
  components/theme/interface/maps/style.ts
  components/transfer/index.tsx
  docs/blog/testing-migrate.en-US.md
  docs/blog/testing-migrate.zh-CN.md
  package.json
Labels: BranchAutoMerge

#41372 chore: merge master into feature
  .dumi/hooks/useLayoutState.ts
  .dumi/pages/index/components/Theme/ColorPicker.tsx
  .dumi/theme/builtins/Previewer/CodePreviewer.tsx
  .dumi/theme/common/ClientOnly.tsx
  .dumi/theme/layouts/GlobalLayout.tsx
  .github/workflows/chatgpt-cr.yml
  .github/workflows/mock-project-build.yml
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/calendar/index.en-US.md
  components/calendar/index.zh-CN.md
  components/statistic/demo/countdown.tsx
  components/table/demo/virtual-list.tsx
  docs/react/i18n.en-US.md
  docs/react/i18n.zh-CN.md
  package.json
  scripts/ci-mock-project-build.sh
Labels: BranchAutoMerge

#40519 fix(Form): Fix Form.Item not rendering correctly in Modal when it has help
  components/form/FormItem/ItemHolder.tsx
  components/form/__tests__/index.test.tsx
Labels: codeball:needs-review
