Repository ant-design/ant-design, pull requests merged in 2024-09, with the labels that each got.

#50707 chore: feature merge master
  .github/workflows/pr-contributor-welcome.yml
  .github/workflows/upgrade-deps.yml
  .lintstagedrc.json
  BUG_VERSIONS.json
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  biome.json
  components/avatar/demo/component-token.md
  components/button/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/button/__tests__/__snapshots__/demo.test.ts.snap
  components/button/demo/linear-gradient.tsx
  components/cascader/index.en-US.md
  components/cascader/index.zh-CN.md
  components/input/Password.tsx
  components/input/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/input/__tests__/__snapshots__/demo.test.tsx.snap
  components/input/demo/password-input.tsx
  components/input/style/index.ts
  components/locale/tr_TR.ts
  components/menu/style/vertical.ts
  components/select/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/space/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/table/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tour/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tour/__tests__/__snapshots__/demo.test.tsx.snap
  components/tour/__tests__/__snapshots__/index.test.tsx.snap
  components/tour/__tests__/index.test.tsx
  components/tour/demo/gap.md
  components/tour/demo/gap.tsx
  components/tour/index.en-US.md
  components/tour/index.zh-CN.md
  components/transfer/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/transfer/__tests__/__snapshots__/demo.test.ts.snap
  components/tree-select/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tree/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tree/__tests__/__snapshots__/demo.test.ts.snap
  components/tree/__tests__/__snapshots__/index.test.tsx.snap
  components/tree/__tests__/index.test.tsx
  components/typography/__tests__/ellipsis.test.tsx
  components/typography/hooks/useTooltipProps.ts
  docs/react/css-variables.en-US.md
  docs/react/css-variables.zh-CN.md
  docs/react/customize-theme.en-US.md
  docs/react/customize-theme.zh-CN.md
  docs/react/use-with-refine.en-US.md
  docs/react/use-with-refine.zh-CN.md
  package.json
Labels: BranchAutoMerge

#50748 chore: merge master into feature
  components/_util/wave/index.ts
  components/_util/wave/interface.ts
  components/_util/wave/useWave.ts
  components/badge/style/index.ts
  components/dropdown/style/index.ts
  components/input/style/index.ts
  components/radio/group.tsx
  components/select/index.en-US.md
  components/select/index.zh-CN.md
  components/table/__tests__/Table.virtual.test.tsx
  components/table/demo/virtual-list.tsx
  components/table/style/virtual.ts
Labels: BranchAutoMerge

#50038 feat:🔥New Component: Splitter
  components/__tests__/__snapshots__/index.test.ts.snap
  components/index.ts
  components/splitter/Panel.tsx
  components/splitter/SplitBar.tsx
  components/splitter/Splitter.tsx
  components/splitter/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/splitter/__tests__/__snapshots__/demo.test.ts.snap
  components/splitter/__tests__/demo-extend.test.ts
  components/splitter/__tests__/demo.test.ts
  components/splitter/__tests__/image.test.ts
  components/splitter/__tests__/index.test.tsx
  components/splitter/demo/collapsible.md
  components/splitter/demo/collapsible.tsx
  components/splitter/demo/control.md
  components/splitter/demo/control.tsx
  components/splitter/demo/debug.md
  components/splitter/demo/debug.tsx
  components/splitter/demo/group.md
  components/splitter/demo/group.tsx
  components/splitter/demo/multiple.md
  components/splitter/demo/multiple.tsx
  components/splitter/demo/size.md
  components/splitter/demo/size.tsx
  components/splitter/demo/vertical.md
  components/splitter/demo/vertical.tsx
  components/splitter/hooks/useItems.ts
  components/splitter/hooks/useResizable.ts
  components/splitter/hooks/useResize.ts
  components/splitter/hooks/useSizes.ts
  components/splitter/index.en-US.md
  components/splitter/index.tsx
  components/splitter/index.zh-CN.md
  components/splitter/interface.ts
  components/splitter/style/index.ts
  components/theme/interface/components.ts
  package.json
  scripts/__snapshots__/check-site.ts.snap
  tests/__snapshots__/index.test.ts.snap
Labels: ☘️ New Component, skip-verify-files

#50802 ci: auto remove unconfirmed label when add other labels
  .github/workflows/issue-labeled.yml
Labels: skip-verify-files

#50856 chore: merge master into feature
  .github/workflows/issue-labeled.yml
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  README-zh_CN.md
  README.md
  biome.json
  components/_util/__tests__/useZIndex.test.tsx
  components/_util/hooks/useZIndex.ts
  components/_util/toList.ts
  components/badge/index.tsx
  components/collapse/Collapse.tsx
  components/color-picker/ColorPicker.tsx
  components/color-picker/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/color-picker/__tests__/__snapshots__/demo.test.tsx.snap
  components/color-picker/__tests__/index.test.tsx
  components/color-picker/components/PanelPicker/index.tsx
  components/color-picker/demo/controlled.md
  components/color-picker/demo/controlled.tsx
  components/color-picker/index.en-US.md
  components/color-picker/index.zh-CN.md
  components/color-picker/util.ts
  components/date-picker/locale/el_GR.ts
  components/dropdown/style/index.ts
  components/input/OTP/OTPInput.tsx
  components/input/OTP/index.tsx
  components/input/__tests__/otp.test.tsx
  components/layout/Sider.tsx
  components/layout/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/layout/__tests__/__snapshots__/demo.test.ts.snap
  components/layout/demo/component-token.tsx
  components/layout/style/index.ts
  components/layout/style/light.ts
  components/layout/style/sider.ts
  components/locale/ar_EG.ts
  components/locale/el_GR.ts
  components/locale/es_ES.ts
  components/mentions/index.tsx
  components/menu/style/index.ts
  components/menu/style/vertical.ts
  components/pagination/style/index.ts
  components/select/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/select/__tests__/__snapshots__/demo.test.tsx.snap
  components/select/demo/custom-label-render.tsx
  components/table/__tests__/Table.rowSelection.test.tsx
  components/table/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/table/__tests__/__snapshots__/demo.test.ts.snap
  components/table/demo/tree-table-preserveSelectedRowKeys.md
  components/table/demo/tree-table-preserveSelectedRowKeys.tsx
  components/table/hooks/useSelection.tsx
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/typography/__tests__/copy.test.tsx
  components/typography/hooks/useCopyClick.ts
  components/watermark/index.tsx
  components/watermark/useClips.ts
  package.json
Labels: BranchAutoMerge

#50810 ci: send Unconfirmed Issues to DingTalk
  .github/workflows/issue-schedule.yml
Labels: skip-verify-files

#50899 ci(issue-schedule): update bot token
  .github/workflows/issue-schedule.yml
Labels: skip-verify-files

#50945 chore: merge feature into master
  components/checkbox/Checkbox.tsx
Labels: BranchAutoMerge

#50953 chore: merge feature to master
  components/pagination/Pagination.tsx
  components/pagination/__tests__/type.test.tsx
  components/pagination/index.en-US.md
  components/pagination/index.zh-CN.md
  components/select/demo/component-token.tsx
  components/select/style/token.ts
  components/select/style/variants.ts
  package.json
Labels: BranchAutoMerge

#50959 docs: update changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: skip-verify-files

#50988 chore: sync master to feature
  .dumi/theme/builtins/DemoWrapper/index.tsx
  .dumi/theme/builtins/Previewer/index.tsx
  .dumi/theme/common/styles/Demo.tsx
  .dumi/theme/common/styles/Markdown.tsx
  .lintstagedrc.json
  .prettierignore
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/alert/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/alert/demo/action.tsx
  components/calendar/demo/lunar.tsx
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/form/__tests__/__snapshots__/demo.test.tsx.snap
  components/form/demo/layout.tsx
  components/grid/demo/useBreakpoint.md
  components/image/demo/nested.tsx
  components/locale/tr_TR.ts
  components/menu/SubMenu.tsx
  components/select/style/index.ts
  components/splitter/index.en-US.md
  components/splitter/index.zh-CN.md
  components/tour/style/index.ts
  components/transfer/style/index.ts
  components/upload/demo/directory.md
  docs/blog/picker.en-US.md
  docs/blog/picker.zh-CN.md
  package.json
  scripts/generate-component-changelog.ts
  tests/shared/imageTest.tsx
Labels: BranchAutoMerge

#51070 site: add version update date for component changedoc
  .dumi/theme/common/ComponentChangelog/ComponentChangelog.tsx
  scripts/generate-component-changelog.ts
Labels: skip-verify-files
