Repository ant-design/ant-design, pull requests merged in 2024-08, with the labels that each got.

#50198 chore: merge master into feature
  .dumi/theme/builtins/Previewer/CodePreviewer.tsx
  .dumi/theme/icons/CodePenIcon.tsx
  .dumi/theme/icons/CodeSandboxIcon.tsx
  .dumi/theme/icons/DirectionIcon.tsx
  .dumi/theme/icons/ExternalLinkIcon.tsx
  .dumi/theme/icons/RiddleIcon.tsx
  .dumi/theme/slots/Header/index.tsx
  README-zh_CN.md
  README.md
  components/locale/es_ES.ts
  components/table/__tests__/Table.sorter.test.tsx
  components/table/hooks/useSorter.tsx
  components/tree/style/index.ts
  package.json
Labels: BranchAutoMerge

#50215 chore: merge master into feature
  components/radio/index.tsx
  docs/react/introduce.zh-CN.md
Labels: BranchAutoMerge

#50341 chore: merge master into feature
  .dumi/theme/builtins/IconSearch/Category.tsx
  .dumi/theme/builtins/IconSearch/CopyableIcon.tsx
  .dumi/theme/common/Color/ColorStyle.tsx
  .dumi/theme/common/styles/Markdown.tsx
  components/affix/__tests__/Affix.test.tsx
  components/affix/__tests__/__snapshots__/Affix.test.tsx.snap
  components/auto-complete/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/auto-complete/demo/certain-category.tsx
  components/auto-complete/index.en-US.md
  components/divider/index.en-US.md
  components/divider/index.tsx
  components/divider/index.zh-CN.md
  components/layout/__tests__/dynamic-breakpoint.test.tsx
  components/modal/demo/_semantic.tsx
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
  components/popconfirm/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/popconfirm/__tests__/__snapshots__/demo.test.tsx.snap
  components/popconfirm/demo/placement.md
  components/popconfirm/demo/placement.tsx
  components/popover/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/popover/__tests__/__snapshots__/demo.test.tsx.snap
  components/popover/demo/arrow.tsx
  components/popover/demo/placement.tsx
  components/tag/__tests__/index.test.tsx
  components/tooltip/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tooltip/__tests__/__snapshots__/demo.test.tsx.snap
  components/tooltip/demo/arrow.tsx
  components/tooltip/demo/placement.tsx
  components/transfer/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/transfer/__tests__/__snapshots__/demo.test.ts.snap
  components/transfer/demo/advanced.tsx
  components/typography/Base/index.tsx
  components/typography/Base/util.ts
  components/typography/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/typography/__tests__/__snapshots__/demo.test.tsx.snap
  components/typography/__tests__/ellipsis.test.tsx
  components/typography/__tests__/index.test.tsx
  components/typography/demo/copyable.tsx
  components/upload/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/upload/__tests__/__snapshots__/demo.test.ts.snap
  components/upload/demo/picture-style.md
  components/upload/demo/picture-style.tsx
  components/upload/demo/transform-file.tsx
  package.json
Labels: BranchAutoMerge

#50384 test: enable codecov bundle analysis
  .github/workflows/size-limit.yml
  package.json
  scripts/visual-regression/report-template.html
  webpack.config.js
Labels: ⚙️ Workflow

#50390 docs(card): use card semantic-dom instead of table
  components/card/demo/_semantic.tsx
  components/card/index.en-US.md
  components/card/index.zh-CN.md
  scripts/__snapshots__/check-site.ts.snap
Labels: skip-verify-files

#50404 chore: Reduce typo count.
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  README.md
  docs/blog/issue-helper.zh-CN.md
  docs/react/customize-theme.en-US.md
  docs/react/migrate-less-variables.zh-CN.md
  docs/react/recommendation.zh-CN.md
  docs/spec/copywriting.en-US.md
  docs/spec/overview.en-US.md
Labels: skip-verify-files

#50409 chore: merge master into feature
  components/float-button/FloatButtonGroup.tsx
  components/float-button/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/float-button/__tests__/__snapshots__/demo.test.ts.snap
  components/float-button/demo/controlled.md
  components/float-button/demo/controlled.tsx
  components/float-button/style/index.ts
Labels: BranchAutoMerge

#50430 docs: fix typos
  CHANGELOG.zh-CN.md
  components/tree-select/index.zh-CN.md
  components/typography/index.zh-CN.md
  docs/blog/extract-ssr.zh-CN.md
Labels: skip-verify-files

#50476 chore: sync master to feature
  .github/workflows/mock-project-build.yml
  .github/workflows/pkg.pr.new.yml
  .github/workflows/preview-build.yml
  .github/workflows/site-deploy.yml
  .github/workflows/test.yml
  .github/workflows/upgrade-deps.yml
  .github/workflows/visual-regression-diff-build.yml
  .github/workflows/visual-regression-diff-finish.yml
  .github/workflows/visual-regression-persist-start.yml
  components/_util/hooks/useClosable.tsx
  components/empty/index.en-US.md
  components/tag/index.tsx
  docs/blog/github-actions-workflow.en-US.md
  docs/blog/github-actions-workflow.zh-CN.md
  docs/react/introduce.en-US.md
  docs/react/introduce.zh-CN.md
  mako.config.json
  package.json
Labels: BranchAutoMerge

#50510 chore: merge master into feature
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/color-picker/__tests__/index.test.tsx
  components/color-picker/components/PanelPicker/index.tsx
  components/float-button/FloatButtonGroup.tsx
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/form/__tests__/__snapshots__/demo.test.tsx.snap
  components/form/demo/variant.tsx
  components/tabs/style/index.ts
  package.json
Labels: BranchAutoMerge

#50582 chore: merge master into feature
  .dumirc.ts
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  README-zh_CN.md
  codecov.yml
  components/drawer/index.en-US.md
  components/popconfirm/__tests__/index.test.tsx
  components/segmented/__tests__/index.test.tsx
  components/theme/index.tsx
  components/tree/demo/virtual-scroll.tsx
  components/typography/Base/Ellipsis.tsx
  components/typography/Base/index.tsx
  components/typography/Base/util.ts
  components/typography/__tests__/ellipsis.test.tsx
  docs/react/compatible-style.en-US.md
  docs/react/compatible-style.zh-CN.md
  package.json
Labels: BranchAutoMerge

#50557 feat[Collapse]: support classNames and styles
  components/collapse/__tests__/index.test.tsx
  components/collapse/demo/_semantic.tsx
  components/collapse/index.en-US.md
  components/collapse/index.zh-CN.md
  package.json
  scripts/__snapshots__/check-site.ts.snap
Labels: skip-verify-files

#50641 chore: sync master to feature
  .dumi/hooks/useMenu.tsx
  .dumi/theme/slots/Content/DocAnchor.tsx
  .dumi/theme/slots/Content/index.tsx
  .dumi/theme/slots/Sidebar/index.tsx
  .github/workflows/size-limit.yml
  .github/workflows/test.yml
  biome.json
  codecov.yml
  components/badge/style/index.ts
  components/color-picker/interface.ts
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/form/__tests__/__snapshots__/demo.test.tsx.snap
  components/form/demo/disabled.tsx
  components/menu/style/vertical.ts
  components/rate/index.tsx
  components/table/style/sorter.ts
  components/tag/demo/draggable.tsx
  components/typography/Base/CopyBtn.tsx
  components/typography/Base/Ellipsis.tsx
  components/typography/Base/index.tsx
  components/typography/Base/util.ts
  components/typography/Editable.tsx
  components/typography/Text.tsx
  components/typography/Title.tsx
  components/typography/Typography.tsx
  components/typography/hooks/useTooltipProps.ts
  components/typography/hooks/useUpdatedEffect.ts
  package.json
  webpack.config.js
Labels: BranchAutoMerge
