Repository ant-design/ant-design, pull requests merged in 2025-03, with the labels that each got.

#53020 chore: merge feature into next
  .github/workflows/preview-deploy.yml
  .github/workflows/visual-regression-diff-finish.yml
  .github/workflows/visual-regression-persist-finish.yml
  components/alert/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/alert/__tests__/__snapshots__/demo.test.ts.snap
  components/alert/demo/closable.tsx
  components/select/demo/automatic-tokenization.tsx
  components/select/demo/tags.tsx
  package.json
Labels: BranchAutoMerge

#53046 chore: sync master into feature
  components/date-picker/style/panel.ts
  components/menu/style/index.ts
  components/select/demo/search-box.tsx
  components/select/demo/select-users.tsx
  components/table/demo/ajax.tsx
  components/upload/__tests__/upload.test.tsx
  package.json
Labels: BranchAutoMerge

#53051 chore: sync feature into next
  components/date-picker/style/panel.ts
  components/menu/style/index.ts
  components/select/demo/search-box.tsx
  components/select/demo/select-users.tsx
  components/table/demo/ajax.tsx
  components/upload/__tests__/upload.test.tsx
  package.json
Labels: BranchAutoMerge

#53056 chore: sync master into feature
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/config-provider/hooks/useSize.ts
  components/locale/de_DE.ts
  components/table/__tests__/Table.test.tsx
  package.json
Labels: BranchAutoMerge

#53059 chore: sync feature into next
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/config-provider/hooks/useSize.ts
  components/locale/de_DE.ts
  components/table/__tests__/Table.test.tsx
  package.json
Labels: BranchAutoMerge

#52162 feat: [v6] new component Masonry
  components/__tests__/__snapshots__/index.test.ts.snap
  components/config-provider/__tests__/style.test.tsx
  components/config-provider/context.ts
  components/config-provider/index.en-US.md
  components/config-provider/index.tsx
  components/config-provider/index.zh-CN.md
  components/grid/hooks/useGutter.ts
  components/index.ts
  components/masonry/Masonry.tsx
  components/masonry/MasonryItem.tsx
  components/masonry/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/masonry/__tests__/__snapshots__/demo.test.ts.snap
  components/masonry/__tests__/demo-extend.test.ts
  components/masonry/__tests__/demo.test.ts
  components/masonry/__tests__/index.test.tsx
  components/masonry/demo/_semantic.tsx
  components/masonry/demo/basic.md
  components/masonry/demo/basic.tsx
  components/masonry/demo/dynamic.md
  components/masonry/demo/dynamic.tsx
  components/masonry/demo/fresh.md
  components/masonry/demo/fresh.tsx
  components/masonry/demo/image.md
  components/masonry/demo/image.tsx
  components/masonry/demo/responsive.md
  components/masonry/demo/responsive.tsx
  components/masonry/hooks/useDelay.ts
  components/masonry/hooks/usePositions.ts
  components/masonry/hooks/useRefs.ts
  components/masonry/index.en-US.md
  components/masonry/index.tsx
  components/masonry/index.zh-CN.md
  components/masonry/style/index.ts
  components/theme/interface/components.ts
  package.json
  scripts/__snapshots__/check-site.ts.snap
  tests/__snapshots__/index.test.ts.snap
  tests/setup.ts
Labels: ☘️ New Component, skip-verify-files

#53075 chore: sync master into feature
  .github/workflows/issue-labeled.yml
  components/button/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/button/__tests__/__snapshots__/demo.test.ts.snap
  components/button/demo/debug-icon.tsx
  components/drawer/__tests__/__snapshots__/demo-extend.test.tsx.snap
  components/form/Form.tsx
  components/form/FormItemLabel.tsx
  components/form/style/index.ts
  components/popconfirm/index.en-US.md
  components/popconfirm/index.zh-CN.md
  components/popover/index.en-US.md
  components/popover/index.zh-CN.md
  components/tooltip/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tooltip/__tests__/__snapshots__/demo.test.tsx.snap
  components/tooltip/demo/disabled.tsx
  components/tooltip/demo/wrap-custom-component.md
  components/tooltip/demo/wrap-custom-component.tsx
  components/tooltip/index.en-US.md
  components/tooltip/index.zh-CN.md
  components/tooltip/shared/sharedFAQ.en-US.md
  components/tooltip/shared/sharedFAQ.zh-CN.md
  docs/react/getting-started.en-US.md
  docs/react/use-custom-date-library.en-US.md
  docs/react/use-custom-date-library.zh-CN.md
  package.json
Labels: BranchAutoMerge

#53078 chore: sync feature into next
  .github/workflows/issue-labeled.yml
  components/button/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/button/__tests__/__snapshots__/demo.test.ts.snap
  components/button/demo/debug-icon.tsx
  components/drawer/__tests__/__snapshots__/demo-extend.test.tsx.snap
  components/form/Form.tsx
  components/form/FormItemLabel.tsx
  components/form/style/index.ts
  components/popconfirm/index.en-US.md
  components/popconfirm/index.zh-CN.md
  components/popover/index.en-US.md
  components/popover/index.zh-CN.md
  components/tooltip/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tooltip/__tests__/__snapshots__/demo.test.tsx.snap
  components/tooltip/demo/disabled.tsx
  components/tooltip/demo/wrap-custom-component.md
  components/tooltip/demo/wrap-custom-component.tsx
  components/tooltip/index.en-US.md
  components/tooltip/index.zh-CN.md
  components/tooltip/shared/sharedFAQ.en-US.md
  components/tooltip/shared/sharedFAQ.zh-CN.md
  docs/react/getting-started.en-US.md
  docs/react/use-custom-date-library.en-US.md
  docs/react/use-custom-date-library.zh-CN.md
  package.json
Labels: BranchAutoMerge

#53090 chore: install using bun
  README-zh_CN.md
  README.md
Labels: skip-verify-files

#53103 chore: sync feature into next
  README-zh_CN.md
  README.md
  components/affix/__tests__/Affix.test.tsx
  components/affix/index.tsx
  components/image/index.en-US.md
  components/image/index.zh-CN.md
  components/modal/demo/_semantic.tsx
  components/typography/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/typography/__tests__/__snapshots__/demo.test.tsx.snap
  components/typography/demo/componentToken-debug.tsx
  components/typography/style/index.ts
Labels: BranchAutoMerge

#53122 chore: sync master to feature
  .cursorrules
  .dumi/hooks/useMenu.tsx
  .dumi/theme/builtins/ComponentTokenTable/index.tsx
  .dumi/theme/slots/Footer/index.tsx
  components/date-picker/generatePicker/interface.ts
  components/date-picker/locale/ar_EG.ts
  components/date-picker/locale/example.json
  components/date-picker/locale/pl_PL.ts
  components/date-picker/locale/pt_PT.ts
  components/date-picker/locale/sl_SI.ts
  components/locale/hy_AM.ts
  components/locale/tr_TR.ts
  package.json
  scripts/visual-regression/local.ts
Labels: BranchAutoMerge

#53137 chore: sync feature into next
  .cursorrules
  .dumi/hooks/useMenu.tsx
  .dumi/theme/builtins/ComponentTokenTable/index.tsx
  .dumi/theme/slots/Footer/index.tsx
  components/cascader/__tests__/index.test.tsx
  components/cascader/index.en-US.md
  components/cascader/index.tsx
  components/cascader/index.zh-CN.md
  components/date-picker/generatePicker/interface.ts
  components/date-picker/locale/ar_EG.ts
  components/date-picker/locale/example.json
  components/date-picker/locale/pl_PL.ts
  components/date-picker/locale/pt_PT.ts
  components/date-picker/locale/sl_SI.ts
  components/locale/hy_AM.ts
  components/locale/tr_TR.ts
  components/table/__tests__/Table.test.tsx
  components/table/hooks/useSelection.tsx
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/table/interface.ts
  package.json
  scripts/visual-regression/local.ts
Labels: BranchAutoMerge

#53171 chore: merge master into feature
  .dumi/hooks/useThemeAnimation.ts
  components/float-button/FloatButton.tsx
  components/float-button/FloatButtonContent.tsx
  components/float-button/__tests__/image.test.ts
  components/input/TextArea.tsx
  components/input/__tests__/textarea.test.tsx
  components/input/hooks/useHandleResizeWrapper.ts
  components/upload/__tests__/requests.ts
  contributors.json
Labels: BranchAutoMerge

#53172 chore: merge feature into next
  .dumi/hooks/useThemeAnimation.ts
  components/_util/convertToTooltipProps.ts
  components/float-button/FloatButton.tsx
  components/float-button/FloatButtonContent.tsx
  components/float-button/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/float-button/__tests__/__snapshots__/demo.test.ts.snap
  components/float-button/__tests__/image.test.ts
  components/float-button/__tests__/index.test.tsx
  components/float-button/demo/tooltip.tsx
  components/float-button/index.en-US.md
  components/float-button/index.zh-CN.md
  components/float-button/interface.ts
  components/form/FormItemLabel.tsx
  components/input/TextArea.tsx
  components/input/__tests__/textarea.test.tsx
  components/input/hooks/useHandleResizeWrapper.ts
  components/upload/__tests__/requests.ts
  contributors.json
Labels: BranchAutoMerge

#53208 chore: merge master into feature
  .dumi/theme/layouts/GlobalLayout.tsx
  .github/workflows/site-deploy.yml
  .github/workflows/verify-files-modify.yml
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/config-provider/index.en-US.md
  components/config-provider/index.zh-CN.md
  components/input/TextArea.tsx
  components/input/__tests__/textarea.test.tsx
  components/input/hooks/useHandleResizeWrapper.ts
  package.json
Labels: BranchAutoMerge

#53211 chore: sync feature into next
  .dumi/theme/layouts/GlobalLayout.tsx
  .github/workflows/site-deploy.yml
  .github/workflows/verify-files-modify.yml
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/config-provider/index.en-US.md
  components/config-provider/index.zh-CN.md
  components/input/TextArea.tsx
  components/input/__tests__/textarea.test.tsx
  components/input/hooks/useHandleResizeWrapper.ts
  package.json
Labels: BranchAutoMerge

#53249 chore: sync master into feature
  .cursor/rules/demo.mdc
  .cursor/rules/docs.mdc
  .cursor/rules/git.mdc
  .cursor/rules/naming.mdc
  .cursor/rules/project.mdc
  .cursor/rules/styling.mdc
  .cursor/rules/testing.mdc
  .cursor/rules/typescript.mdc
  .cursorrules
  .dumi/theme/builtins/ColorChunk/index.tsx
  components/_util/responsiveObserver.ts
  components/carousel/style/index.ts
  components/color-picker/style/color-block.ts
  components/date-picker/style/panel.ts
  components/float-button/style/keyframes.ts
  components/form/style/index.ts
  components/input-number/style/index.ts
  components/input/TextArea.tsx
  components/input/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/input/__tests__/__snapshots__/demo.test.tsx.snap
  components/input/__tests__/textarea.test.tsx
  components/input/demo/textarea-resize.tsx
  components/input/hooks/useHandleResizeWrapper.ts
  components/input/style/index.ts
  components/input/style/textarea.ts
  components/input/style/variants.ts
  components/locale/fa_IR.ts
  components/mentions/style/index.ts
  components/notification/style/index.ts
  components/select/style/index.ts
  components/steps/style/index.ts
  components/table/style/sticky.ts
  components/tree-select/style/index.ts
  components/tree/style/index.ts
  docs/react/compatible-style.en-US.md
  docs/react/compatible-style.zh-CN.md
  package.json
  scripts/check-cssinjs.tsx
  scripts/generate-cssinjs.ts
  typings/custom-typings.d.ts
Labels: BranchAutoMerge

#53268 chore: sync feature into next
  .cursor/rules/demo.mdc
  .cursor/rules/docs.mdc
  .cursor/rules/git.mdc
  .cursor/rules/naming.mdc
  .cursor/rules/project.mdc
  .cursor/rules/styling.mdc
  .cursor/rules/testing.mdc
  .cursor/rules/typescript.mdc
  .cursorrules
  .dumi/theme/builtins/ColorChunk/index.tsx
  components/_util/__tests__/responsiveObserve.test.tsx
  components/_util/mediaQueryUtil.ts
  components/_util/responsiveObserver.ts
  components/carousel/style/index.ts
  components/color-picker/style/color-block.ts
  components/date-picker/style/panel.ts
  components/float-button/style/keyframes.ts
  components/form/style/index.ts
  components/grid/__tests__/__snapshots__/index.test.tsx.snap
  components/grid/__tests__/index.test.tsx
  components/input-number/style/index.ts
  components/input/TextArea.tsx
  components/input/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/input/__tests__/__snapshots__/demo.test.tsx.snap
  components/input/__tests__/textarea.test.tsx
  components/input/demo/textarea-resize.tsx
  components/input/hooks/useHandleResizeWrapper.ts
  components/input/style/index.ts
  components/input/style/textarea.ts
  components/input/style/variants.ts
  components/layout/Sider.tsx
  components/layout/__tests__/dynamic-breakpoint.test.tsx
  components/locale/fa_IR.ts
  components/mentions/style/index.ts
  components/notification/style/index.ts
  components/select/__tests__/index.test.tsx
  components/select/demo/_semantic.tsx
  components/select/index.en-US.md
  components/select/index.tsx
  components/select/index.zh-CN.md
  components/select/style/index.ts
  components/steps/style/index.ts
  components/table/style/sticky.ts
  components/transfer/__tests__/index.test.tsx
  components/tree-select/style/index.ts
  components/tree/style/index.ts
  components/upload/Upload.tsx
  docs/react/compatible-style.en-US.md
  docs/react/compatible-style.zh-CN.md
  package.json
  scripts/check-cssinjs.tsx
  scripts/generate-cssinjs.ts
  tests/setup.ts
  tests/shared/imageTest.tsx
  typings/custom-typings.d.ts
Labels: BranchAutoMerge

#53256 feat(CheckableTagGroup): new component
  components/tag/CheckableTagGroup.tsx
  components/tag/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tag/__tests__/__snapshots__/demo.test.tsx.snap
  components/tag/__tests__/demo.test.ts
  components/tag/__tests__/demo.test.tsx
  components/tag/__tests__/index.test.tsx
  components/tag/demo/_semantic_group.tsx
  components/tag/demo/checkable.md
  components/tag/demo/checkable.tsx
  components/tag/index.en-US.md
  components/tag/index.tsx
  components/tag/index.zh-CN.md
  components/tag/style/index.ts
  scripts/__snapshots__/check-site.ts.snap
Labels: skip-verify-files

#53297 chore: sync feature into next
  components/_util/PurePanel.tsx
  components/dropdown/__tests__/index.test.tsx
  components/dropdown/demo/custom-dropdown.tsx
  components/dropdown/dropdown-button.tsx
  components/dropdown/dropdown.tsx
  components/dropdown/index.en-US.md
  components/dropdown/index.zh-CN.md
  components/table/hooks/useFilter/FilterDropdown.tsx
  components/tree-select/__tests__/index.test.tsx
  components/tree-select/demo/_semantic.tsx
  components/tree-select/index.en-US.md
  components/tree-select/index.tsx
  components/tree-select/index.zh-CN.md
Labels: BranchAutoMerge

#53315 chore: sync feature into next
  .dumi/theme/builtins/ColorChunk/index.tsx
  .dumi/theme/builtins/Previewer/CodePreviewer.tsx
  .dumi/theme/builtins/TokenTable/index.tsx
  .dumi/theme/common/BezierVisualizer/Visualizer.tsx
  .dumi/theme/common/BezierVisualizer/index.tsx
  .dumi/theme/layouts/GlobalLayout.tsx
  .dumi/theme/plugin.ts
  .dumi/theme/utils/__tests__/runTests.ts
  .dumi/theme/utils/__tests__/tsToJs.test.ts
  .dumi/theme/utils/tsToJs.test.ts
  .dumi/theme/utils/tsToJs.ts
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/avatar/Avatar.tsx
  components/button/__tests__/index.test.tsx
  components/button/button.tsx
  components/color-picker/index.en-US.md
  components/color-picker/index.zh-CN.md
  components/config-provider/context.ts
  components/config-provider/index.en-US.md
  components/config-provider/index.zh-CN.md
  components/icon/index.en-US.md
  components/icon/index.zh-CN.md
  components/input-number/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/input-number/__tests__/__snapshots__/demo.test.tsx.snap
  components/input-number/__tests__/suffix.test.tsx
  components/input-number/index.tsx
  components/modal/Modal.tsx
  components/modal/__tests__/Modal.test.tsx
  components/notification/style/index.ts
  components/pagination/style/index.ts
  components/table/hooks/useLazyKVMap.ts
  package.json
  scripts/generate-component-changelog.ts
Labels: BranchAutoMerge

#53332 chore: sync master into feature
  .dumi/theme/builtins/Badge/index.tsx
  components/avatar/index.en-US.md
  components/avatar/index.zh-CN.md
  components/mentions/index.en-US.md
  components/mentions/index.zh-CN.md
  components/select/index.en-US.md
  components/select/index.zh-CN.md
  package.json
Labels: BranchAutoMerge

#53340 chore: merge master into feature
  .dumi/hooks/use.ts
  .dumi/hooks/useFetch/index.ts
  .dumi/pages/index/components/PreviewBanner/ComponentsBlock.tsx
  .dumi/pages/index/components/PreviewBanner/index.tsx
  .dumi/theme/common/ThemeSwitch/index.tsx
  .dumi/theme/layouts/GlobalLayout.tsx
  .dumi/theme/locales/en-US.json
  .dumi/theme/locales/zh-CN.json
  .dumi/theme/slots/Header/SwitchBtn.tsx
  .dumi/theme/slots/Header/index.tsx
  components/_util/responsiveObserver.ts
  components/modal/Modal.tsx
Labels: BranchAutoMerge

#53349 chore: sync feature into next
  .dumi/hooks/use.ts
  .dumi/hooks/useFetch/index.ts
  .dumi/pages/index/components/PreviewBanner/ComponentsBlock.tsx
  .dumi/pages/index/components/PreviewBanner/index.tsx
  .dumi/theme/builtins/Badge/index.tsx
  .dumi/theme/common/ThemeSwitch/index.tsx
  .dumi/theme/layouts/GlobalLayout.tsx
  .dumi/theme/locales/en-US.json
  .dumi/theme/locales/zh-CN.json
  .dumi/theme/slots/Header/SwitchBtn.tsx
  .dumi/theme/slots/Header/index.tsx
  components/_util/responsiveObserver.ts
  components/avatar/index.en-US.md
  components/avatar/index.zh-CN.md
  components/cascader/__tests__/index.test.tsx
  components/cascader/demo/_semantic.tsx
  components/cascader/index.en-US.md
  components/cascader/index.tsx
  components/cascader/index.zh-CN.md
  components/config-provider/context.ts
  components/mentions/index.en-US.md
  components/mentions/index.zh-CN.md
  components/modal/Modal.tsx
  components/select/index.en-US.md
  components/select/index.zh-CN.md
  package.json
Labels: BranchAutoMerge

#53354 chore: merge master into feature
  .dumi/components/SemanticPreview.tsx
  .dumi/hooks/useDark.tsx
  .dumi/pages/index/components/BannerRecommends.tsx
  .dumi/pages/index/components/ComponentsList.tsx
  .dumi/pages/index/components/DesignFramework.tsx
  .dumi/pages/index/components/Group.tsx
  .dumi/pages/index/components/PreviewBanner/index.tsx
  .dumi/pages/index/components/SiteContext.ts
  .dumi/pages/index/components/Theme/index.tsx
  .dumi/pages/index/index.tsx
  .dumi/pages/theme-editor/index.tsx
  .dumi/theme/SiteThemeProvider.tsx
  .dumi/theme/builtins/ComponentOverview/index.tsx
  .dumi/theme/builtins/DemoWrapper/index.tsx
  .dumi/theme/builtins/Previewer/CodePreviewer.tsx
  .dumi/theme/common/CodePreview.tsx
  .dumi/theme/common/PrevAndNext.tsx
  .dumi/theme/common/ThemeSwitch/index.tsx
  .dumi/theme/layouts/DocLayout/index.tsx
  .dumi/theme/layouts/GlobalLayout.tsx
  .dumi/theme/layouts/ResourceLayout/index.tsx
  .dumi/theme/slots/Content/Contributors.tsx
  .dumi/theme/slots/Content/index.tsx
  .dumi/theme/slots/Footer/index.tsx
  .dumi/theme/slots/Header/index.tsx
  .dumi/theme/slots/Sidebar/index.tsx
  components/_util/__tests__/util.test.tsx
  components/_util/responsiveObserver.ts
  components/_util/toList.ts
  components/badge/demo/_semantic.tsx
  components/button/demo/_semantic.tsx
  components/card/demo/_semantic.tsx
  components/collapse/demo/_semantic.tsx
  components/descriptions/demo/_semantic.tsx
  components/drawer/demo/_semantic.tsx
  components/empty/demo/_semantic.tsx
  components/input/demo/_semantic_input.tsx
  components/input/demo/_semantic_textarea.tsx
  components/list/demo/_semantic.tsx
  components/list/index.en-US.md
  components/list/index.zh-CN.md
  components/modal/demo/_semantic.tsx
  components/popconfirm/demo/_semantic.tsx
  components/popover/demo/_semantic.tsx
  components/slider/demo/_semantic.tsx
  components/space/demo/_semantic.tsx
  components/theme/__tests__/token.test.tsx
  components/tooltip/demo/_semantic.tsx
  components/transfer/list.tsx
  components/watermark/index.tsx
  components/watermark/useClips.ts
  components/watermark/useSingletonCache.ts
  docs/blog/config-provider-style.en-US.md
  docs/blog/config-provider-style.zh-CN.md
  eslint.config.mjs
  package.json
Labels: BranchAutoMerge
