Repository ant-design/ant-design, pull requests merged in 2025-09, with the labels that each got.

#54829 feat: The mentions component inherits the form's disable
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/form/__tests__/__snapshots__/demo.test.tsx.snap
  components/form/demo/disabled.tsx
  components/mentions/__tests__/index.test.tsx
  components/mentions/index.tsx
  components/mentions/style/index.ts
Labels: lgtm

#54821 feat(TreeSelect): support global config for switcher icon
  components/config-provider/context.ts
  components/config-provider/index.en-US.md
  components/config-provider/index.zh-CN.md
  components/tree-select/__tests__/index.test.tsx
  components/tree-select/index.tsx
Labels: lgtm

#54838 fix: site Anchor scroll failure
  .dumi/global.less
Labels: skip-verify-files, lgtm

#54831 feat: The transfer & tree component inherits the form disable
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/form/__tests__/__snapshots__/demo.test.tsx.snap
  components/form/demo/disabled.tsx
  components/transfer/__tests__/index.test.tsx
  components/transfer/index.tsx
  components/tree/Tree.tsx
  components/tree/__tests__/index.test.tsx
Labels: lgtm

#54842 fix(locale): added missing Italian translations for QRCode & ColorPicker components
  components/locale/it_IT.ts
Labels: lgtm

#54844 chore: adjust site config
  .dumi/theme/layouts/GlobalLayout.tsx
  .dumirc.ts
  .gitignore
  package.json
Labels: skip-verify-files, lgtm

#54845 fix(Button): round padding
  components/button/demo/component-token.tsx
  components/button/style/index.ts
Labels: lgtm

#54847 chore: next merge master
  .dumi/global.less
  .dumi/theme/layouts/GlobalLayout.tsx
  .dumirc.ts
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/button/demo/component-token.tsx
  components/button/style/index.ts
  components/locale/it_IT.ts
  components/pagination/style/index.ts
  package.json
Labels: BranchAutoMerge

#54863 chore: sync master into feature
  .dumi/global.less
  .dumi/theme/layouts/GlobalLayout.tsx
  .dumirc.ts
  .gitignore
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/button/demo/component-token.tsx
  components/button/style/index.ts
  components/locale/it_IT.ts
  components/pagination/style/index.ts
  components/table/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/table/__tests__/__snapshots__/demo.test.ts.snap
  components/table/__tests__/__snapshots__/empty.test.tsx.snap
  package.json
  tests/shared/imageTest.tsx
Labels: BranchAutoMerge

#54864 chore: sync feature into next
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/config-provider/context.ts
  components/config-provider/index.en-US.md
  components/config-provider/index.zh-CN.md
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/form/__tests__/__snapshots__/demo.test.tsx.snap
  components/form/demo/disabled.tsx
  components/mentions/style/index.ts
  components/transfer/__tests__/index.test.tsx
  components/transfer/index.tsx
  components/tree-select/__tests__/index.test.tsx
  components/tree-select/index.tsx
  components/tree/Tree.tsx
  components/tree/__tests__/index.test.tsx
  tests/shared/imageTest.tsx
Labels: BranchAutoMerge

#54850 fix(Input.OTP): Continuous deletion is not allowed.
  components/input/OTP/OTPInput.tsx
Labels: lgtm

#54878 docs: add preset colors token
  scripts/generate-token-meta.ts
Labels: skip-verify-files, lgtm

#54868 fix: Resolve style issues in RTL mode of Carousel components
  components/carousel/__tests__/index.test.tsx
  components/carousel/index.tsx
  components/carousel/style/index.ts
Labels: skip-verify-files, lgtm

#54871 fix(typography): correct margin when editable (#54848)
  components/typography/style/mixins.ts
Labels: lgtm

#54892 fix(Input.Search): prevent hover color change for border and icon in disabled search button
  components/input/style/index.ts
Labels: lgtm

#54900 fix(input-number): Remove default hiding of NumberInput controls on mobile
  package.json
Labels: lgtm

#54904 chore: sync feature into next
  .github/workflows/issue-inactivity-reminder.yml
  .github/workflows/issue-schedule.yml
  .github/workflows/preview-deploy.yml
  .github/workflows/visual-regression-diff-approver.yml
  .github/workflows/visual-regression-diff-finish.yml
  .github/workflows/visual-regression-persist-finish.yml
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/carousel/__tests__/index.test.tsx
  components/carousel/index.tsx
  components/carousel/style/index.ts
  components/dropdown/__tests__/index.test.tsx
  components/dropdown/dropdown.tsx
  components/input/OTP/OTPInput.tsx
  components/input/style/index.ts
  components/theme/interface/seeds.ts
  components/typography/style/mixins.ts
  docs/react/v5-for-19.en-US.md
  docs/react/v5-for-19.zh-CN.md
  package.json
  scripts/generate-token-meta.ts
Labels: BranchAutoMerge

#54910 fix(Table): fix duplicated filter dropdowns and tooltips is shown when Table is sticky
  components/table/InternalTable.tsx
  components/table/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/table/__tests__/__snapshots__/demo.test.ts.snap
  components/table/__tests__/demo.test.ts
  components/table/demo/measure-row-render.md
  components/table/demo/measure-row-render.tsx
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  package.json
Labels: skip-verify-files, lgtm

#54916 refactor: make isThenable function more strict
  components/_util/ActionButton.tsx
Labels: lgtm

#54911 site: img should not be draggable
  .dumi/pages/index/components/Theme/ThemePicker.tsx
  .dumi/pages/index/components/Theme/index.tsx
  .dumi/theme/builtins/ComponentOverview/index.tsx
  .dumi/theme/builtins/ImagePreview/index.tsx
  .dumi/theme/builtins/ResourceCards/index.tsx
  .dumi/theme/common/ComponentChangelog/ComponentChangelog.tsx
  .dumi/theme/common/Loading.tsx
  .dumi/theme/slots/Footer/index.tsx
  components/avatar/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/avatar/__tests__/__snapshots__/demo.test.tsx.snap
  components/avatar/demo/type.tsx
  components/card/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/card/__tests__/__snapshots__/demo.test.ts.snap
  components/card/demo/_semantic.tsx
  components/card/demo/flexible-content.tsx
  components/card/demo/meta.tsx
  components/empty/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/empty/__tests__/__snapshots__/demo.test.ts.snap
  components/empty/index.tsx
  components/flex/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/flex/__tests__/__snapshots__/demo.test.ts.snap
  components/flex/demo/combination.tsx
  components/list/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/list/__tests__/__snapshots__/demo.test.ts.snap
  components/list/demo/_semantic.tsx
  components/list/demo/vertical.tsx
  components/mentions/demo/async.tsx
  components/skeleton/demo/list.tsx
  components/tour/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tour/__tests__/__snapshots__/demo.test.tsx.snap
  components/tour/demo/basic.tsx
  components/tour/demo/gap.tsx
  components/tour/demo/mask.tsx
  components/tour/demo/non-modal.tsx
  components/tour/demo/render-panel.tsx
  components/upload/demo/avatar.tsx
  components/watermark/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/watermark/__tests__/__snapshots__/demo.test.ts.snap
  components/watermark/demo/custom.tsx
Labels: skip-verify-files, lgtm

#54919 feat(input): Support better customization with semantic classNames/styles as function
  components/input/Input.tsx
  components/input/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/input/__tests__/__snapshots__/demo.test.tsx.snap
  components/input/__tests__/index.test.tsx
  components/input/demo/style-class.md
  components/input/demo/style-class.tsx
  components/input/index.en-US.md
  components/input/index.zh-CN.md
Labels: lgtm

#54917 feat(float-button): Support better customization with semantic classNames/styles as function
  components/float-button/FloatButton.tsx
  components/float-button/FloatButtonGroup.tsx
  components/float-button/PurePanel.tsx
  components/float-button/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/float-button/__tests__/__snapshots__/demo.test.ts.snap
  components/float-button/__tests__/group.test.tsx
  components/float-button/__tests__/index.test.tsx
  components/float-button/demo/style-class.md
  components/float-button/demo/style-class.tsx
  components/float-button/index.en-US.md
  components/float-button/index.zh-CN.md
Labels: lgtm

#54930 chore: Organize cursor content into agents md
  .cursor/rules/demo.mdc
  .cursor/rules/docs.mdc
  .cursor/rules/git.mdc
  .cursor/rules/locale.mdc
  .cursor/rules/naming.mdc
  .cursor/rules/project.mdc
  .cursor/rules/styling.mdc
  .cursor/rules/testing.mdc
  .cursor/rules/typescript.mdc
  AGENTS.md
Labels: skip-verify-files, lgtm

#54932 fix: zero runtime Input.Output
  scripts/build-style.tsx
Labels: lgtm

#54933 fix(wave): make wave effect work with tailwind disabled variant
  components/_util/wave/index.ts
  components/switch/index.tsx
Labels: lgtm

#54934 test: update snapshot after rc-menu modification
  components/breadcrumb/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/button/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/date-picker/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/dropdown/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/dropdown/__tests__/__snapshots__/index.test.tsx.snap
  components/empty/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/layout/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/layout/__tests__/__snapshots__/demo.test.ts.snap
  components/menu/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/menu/__tests__/__snapshots__/demo.test.tsx.snap
  components/menu/__tests__/__snapshots__/index.test.tsx.snap
  components/space/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/table/__tests__/__snapshots__/Table.filter.test.tsx.snap
  components/table/__tests__/__snapshots__/Table.rowSelection.test.tsx.snap
  components/table/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/transfer/__tests__/__snapshots__/demo-extend.test.ts.snap
Labels: lgtm

#54997 refactor(splliter): simplify the for loop
  components/splitter/Splitter.tsx
Labels: lgtm

#55001 fix: add miss dep for useMemo
  components/_util/hooks/useMergeSemantic/index.ts
Labels: lgtm

#54998 chore: bump jsdom from 26 to 27
  package.json
Labels: skip-verify-files, lgtm

#55008 chore: merge master into feature
  biome.json
  components/splitter/SplitBar.tsx
  components/splitter/Splitter.tsx
  package.json
Labels: BranchAutoMerge

#52163 refactor: use Node.ELEMENT_NODE replace number
  components/_util/wave/index.ts
  tests/setup.ts
Labels: lgtm

#55018 chore: merge master into feature
  .github/workflows/site-deploy.yml
  components/_util/wave/index.ts
  components/_util/wave/useWave.ts
  components/carousel/index.tsx
  components/form/demo/register.tsx
  package.json
  tests/setup.ts
  tests/shared/imageTest.tsx
Labels: BranchAutoMerge

#54973 feat: stackblitz support zh registry
  .dumi/theme/builtins/Previewer/Actions.tsx
  .dumi/theme/builtins/Previewer/stackblitzConfig.ts
Labels: lgtm

#54949 feat(divider): Support better customization with semantic classNames/styles as function
  components/divider/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/divider/__tests__/__snapshots__/demo.test.ts.snap
  components/divider/__tests__/semantic.test.tsx
  components/divider/demo/style-class.md
  components/divider/demo/style-class.tsx
  components/divider/index.en-US.md
  components/divider/index.tsx
  components/divider/index.zh-CN.md
Labels: lgtm

#54950 feat(breadcrumb): Support better customization with semantic classNames/styles as function
  components/breadcrumb/Breadcrumb.tsx
  components/breadcrumb/__tests__/__snapshots__/Breadcrumb.test.tsx.snap
  components/breadcrumb/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/breadcrumb/__tests__/__snapshots__/demo.test.ts.snap
  components/breadcrumb/__tests__/__snapshots__/itemRender.test.tsx.snap
  components/breadcrumb/__tests__/__snapshots__/router.test.tsx.snap
  components/breadcrumb/__tests__/style-class.test.tsx
  components/breadcrumb/demo/style-class.md
  components/breadcrumb/demo/style-class.tsx
  components/breadcrumb/index.en-US.md
  components/breadcrumb/index.zh-CN.md
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/layout/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/layout/__tests__/__snapshots__/demo.test.ts.snap
Labels: lgtm

#55070 ci: update table snap
  components/table/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/table/__tests__/__snapshots__/demo.test.ts.snap
Labels: lgtm

#55074 refactor: clean up unused style code
  components/button/style/index.ts
Labels: lgtm

#55084 docs: improve document content
  components/breadcrumb/index.en-US.md
  components/breadcrumb/index.zh-CN.md
  components/button/index.en-US.md
  components/button/index.zh-CN.md
  components/divider/index.en-US.md
  components/divider/index.zh-CN.md
  components/float-button/demo/style-class.md
  components/float-button/index.en-US.md
  components/float-button/index.zh-CN.md
  components/input/demo/style-class.md
  components/input/index.en-US.md
  components/input/index.zh-CN.md
  components/masonry/index.en-US.md
  components/masonry/index.zh-CN.md
Labels: lgtm

#55063 feat: add boostLevel prop and support value segmentation
  components/qr-code/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/qr-code/__tests__/__snapshots__/demo.test.ts.snap
  components/qr-code/index.en-US.md
  components/qr-code/index.tsx
  components/qr-code/index.zh-CN.md
  package.json
Labels: lgtm

#55091 type(switch): improve semantic type
  package.json
Labels: lgtm

#55095 chore: merge master into feature
  README.md
  components/list/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/list/__tests__/__snapshots__/demo.test.ts.snap
  components/list/__tests__/demo-extend.test.ts
  components/list/demo/drag-sorting-handler.md
  components/list/demo/drag-sorting-handler.tsx
  components/list/demo/drag-sorting.md
  components/list/demo/drag-sorting.tsx
  components/list/demo/grid-drag-sorting-handler.md
  components/list/demo/grid-drag-sorting-handler.tsx
  components/list/demo/grid-drag-sorting.md
  components/list/demo/grid-drag-sorting.tsx
  components/list/index.en-US.md
  components/list/index.zh-CN.md
  package.json
Labels: BranchAutoMerge

#55100 fix(lint): react-web-api/no-leaked-interval
  components/affix/index.tsx
  components/spin/demo/percent.tsx
  components/spin/usePercent.ts
  components/typography/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/typography/__tests__/__snapshots__/demo.test.tsx.snap
  components/typography/__tests__/copy.test.tsx
  components/typography/demo/ellipsis-debug.tsx
Labels: lgtm

#54896 docs: showTime.defaultValue has deprecated
  components/date-picker/demo/disabled-date.tsx
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
Labels: lgtm

#55104 chore(biome): turn on style.useImportType
  .dumi/theme/builtins/Badge/index.tsx
  .dumi/theme/builtins/Previewer/stackblitzConfig.ts
  .dumi/theme/builtins/RefinedChangelog/index.tsx
  biome.json
  components/_util/hooks/useMergeSemantic/index.ts
  components/card/__tests__/index.test.tsx
  components/date-picker/demo/external-panel.tsx
  components/divider/index.tsx
  components/form/__tests__/ref.test.tsx
  components/input/Input.tsx
  components/list/demo/drag-sorting-handler.tsx
  components/list/demo/grid-drag-sorting-handler.tsx
  components/locale/__tests__/index.test.tsx
  components/modal/Modal.tsx
  components/modal/__tests__/confirm.test.tsx
  components/modal/__tests__/hook.test.tsx
  components/modal/confirm.tsx
  components/modal/interface.ts
  components/splitter/__tests__/lazy.test.tsx
  components/tooltip/util.ts
Labels: skip-verify-files, lgtm

#55105 chore(biome): rm some rules that do not need to be changed
  biome.json
Labels: skip-verify-files, lgtm

#55111 chore: sync master into feature
  .dumi/theme/builtins/Badge/index.tsx
  .dumi/theme/builtins/Previewer/stackblitzConfig.ts
  .dumi/theme/builtins/RefinedChangelog/index.tsx
  .dumi/theme/common/BezierVisualizer/index.tsx
  biome.json
  components/_util/hooks/useMergeSemantic/index.ts
  components/_util/wave/WaveEffect.tsx
  components/affix/index.tsx
  components/badge/index.tsx
  components/card/__tests__/index.test.tsx
  components/config-provider/UnstableContext.tsx
  components/config-provider/__tests__/unstable.test.tsx
  components/config-provider/demo/wave.tsx
  components/date-picker/demo/disabled-date.tsx
  components/date-picker/demo/external-panel.tsx
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
  components/divider/index.tsx
  components/form/Form.tsx
  components/form/FormItem/ItemHolder.tsx
  components/form/__tests__/ref.test.tsx
  components/form/demo/customized-form-controls.tsx
  components/input/Input.tsx
  components/layout/Sider.tsx
  components/list/demo/drag-sorting-handler.tsx
  components/list/demo/grid-drag-sorting-handler.tsx
  components/locale/__tests__/index.test.tsx
  components/modal/Modal.tsx
  components/modal/__tests__/confirm.test.tsx
  components/modal/__tests__/hook.test.tsx
  components/modal/confirm.tsx
  components/modal/interface.ts
  components/progress/Line.tsx
  components/progress/progress.tsx
  components/spin/demo/percent.tsx
  components/spin/usePercent.ts
  components/splitter/__tests__/lazy.test.tsx
  components/table/__tests__/Table.pagination.test.tsx
  components/table/hooks/useContainerWidth.ts
  components/table/hooks/useFilter/index.tsx
  components/table/hooks/useSelection.tsx
  components/tooltip/util.ts
  components/typography/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/typography/__tests__/__snapshots__/demo.test.tsx.snap
  components/typography/__tests__/copy.test.tsx
  components/typography/demo/ellipsis-debug.tsx
  components/upload/demo/customize-progress-bar.tsx
  scripts/visual-regression/build.ts
Labels: BranchAutoMerge

#55113 chore: Enhanced hints for unused variables
  biome.json
  components/form/FormItemInput.tsx
  components/tooltip/index.tsx
  index-style-only.js
Labels: skip-verify-files, lgtm

#55058 feat(Progress): Support better customization with semantic classNames & styles
  components/_util/hooks/useMergeSemantic/index.ts
  components/anchor/__tests__/semantic.test.tsx
  components/progress/Circle.tsx
  components/progress/Line.tsx
  components/progress/Steps.tsx
  components/progress/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/progress/__tests__/__snapshots__/demo.test.ts.snap
  components/progress/__tests__/semantic.test.tsx
  components/progress/__tests__/style-class.test.tsx
  components/progress/demo/style-class.md
  components/progress/demo/style-class.tsx
  components/progress/index.en-US.md
  components/progress/index.zh-CN.md
  components/progress/progress.tsx
Labels: lgtm

#55031 feat(space): Support better customization with semantic classNames/styles as function
  components/space/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/space/__tests__/__snapshots__/demo.test.tsx.snap
  components/space/__tests__/index.test.tsx
  components/space/demo/style-class.md
  components/space/demo/style-class.tsx
  components/space/index.en-US.md
  components/space/index.tsx
  components/space/index.zh-CN.md
Labels: lgtm

#55108 chore: rm @-ms-viewport
  biome.json
  components/style/reset.css
Labels: skip-verify-files, lgtm

#54957 feat(pagination): Support better customization with semantic classNames/styles as function
  components/pagination/Pagination.tsx
  components/pagination/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/pagination/__tests__/__snapshots__/demo.test.ts.snap
  components/pagination/__tests__/__snapshots__/semantic.test.tsx.snap
  components/pagination/__tests__/index.test.tsx
  components/pagination/__tests__/semantic.test.tsx
  components/pagination/demo/style-class.md
  components/pagination/demo/style-class.tsx
  components/pagination/index.en-US.md
  components/pagination/index.zh-CN.md
Labels: lgtm

#55128 docs: Update README
  README-zh_CN.md
  README.md
Labels: skip-verify-files, lgtm

#54956 feat(steps): Support better customization with semantic classNames/styles as function
  components/steps/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/steps/__tests__/__snapshots__/demo.test.ts.snap
  components/steps/__tests__/semantic.test.tsx
  components/steps/demo/style-class.md
  components/steps/demo/style-class.tsx
  components/steps/index.en-US.md
  components/steps/index.tsx
  components/steps/index.zh-CN.md
Labels: lgtm

#55114 feat(dropdown): Support better customization with semantic classNames/styles as function
  components/dropdown/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/dropdown/__tests__/__snapshots__/demo.test.tsx.snap
  components/dropdown/__tests__/index.test.tsx
  components/dropdown/demo/style-class.md
  components/dropdown/demo/style-class.tsx
  components/dropdown/dropdown.tsx
  components/dropdown/index.en-US.md
  components/dropdown/index.zh-CN.md
Labels: skip-verify-files, lgtm

#55145 demo: fix Collapse demo
  components/collapse/demo/_semantic.tsx
Labels: lgtm

#54959 feat(auto-complete): Support better customization with semantic classNames/styles as function
  components/auto-complete/AutoComplete.tsx
  components/auto-complete/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/auto-complete/__tests__/__snapshots__/demo.test.tsx.snap
  components/auto-complete/__tests__/__snapshots__/semantic.test.tsx.snap
  components/auto-complete/__tests__/semantic.test.tsx
  components/auto-complete/demo/_semantic.tsx
  components/auto-complete/demo/style-class.md
  components/auto-complete/demo/style-class.tsx
  components/auto-complete/index.en-US.md
  components/auto-complete/index.zh-CN.md
Labels: lgtm

#55055 docs(AutoComplete): add underlined variant demo
  components/auto-complete/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/auto-complete/__tests__/__snapshots__/demo.test.tsx.snap
  components/auto-complete/demo/variant.md
  components/auto-complete/demo/variant.tsx
  components/auto-complete/index.en-US.md
  components/auto-complete/index.zh-CN.md
Labels: lgtm

#55126 feat(form): Support better customization with semantic classNames/styles as function
  components/form/Form.tsx
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/form/__tests__/__snapshots__/demo.test.tsx.snap
  components/form/__tests__/index.test.tsx
  components/form/context.tsx
  components/form/demo/style-class.md
  components/form/demo/style-class.tsx
  components/form/index.en-US.md
  components/form/index.zh-CN.md
Labels: lgtm

#55148 chore: sync master into feature
  README-zh_CN.md
  README.md
  biome.json
  components/auto-complete/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/auto-complete/__tests__/__snapshots__/demo.test.tsx.snap
  components/auto-complete/demo/variant.md
  components/auto-complete/demo/variant.tsx
  components/auto-complete/index.en-US.md
  components/auto-complete/index.zh-CN.md
  components/collapse/demo/_semantic.tsx
  components/form/FormItemInput.tsx
  components/table/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/table/__tests__/__snapshots__/demo.test.ts.snap
  components/table/__tests__/__snapshots__/empty.test.tsx.snap
  components/table/style/index.ts
  components/tooltip/index.tsx
  components/upload/Upload.tsx
  index-style-only.js
  package.json
Labels: BranchAutoMerge

#55150 site: block Copilot bot、renovate bot、dependa bot
  .dumi/theme/slots/Content/ContributorAvatar.tsx
  .dumi/theme/slots/Content/Contributors.tsx
  contributors.json
  scripts/generate-authors.ts
Labels: skip-verify-files, lgtm

#55153 docs(Input): use Chinese for table headers as required​
  components/input/index.zh-CN.md
Labels: skip-verify-files, lgtm

#55158 chore: Unified variable naming style
  components/button/button.tsx
  components/pagination/Pagination.tsx
  components/space/index.tsx
Labels: lgtm

#55160 chore: update Security Policy from 4.x to 5.x
  SECURITY.md
Labels: skip-verify-files, lgtm

#54969 feat(date-picker_time-picker): Support better customization with semantic classNames/styles as function
  components/date-picker/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/date-picker/__tests__/__snapshots__/demo.test.tsx.snap
  components/date-picker/__tests__/semantic.test.tsx
  components/date-picker/demo/style-class.md
  components/date-picker/demo/style-class.tsx
  components/date-picker/generatePicker/generateSinglePicker.tsx
  components/date-picker/generatePicker/interface.ts
  components/date-picker/hooks/useMergedPickerSemantic.ts
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
  components/time-picker/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/time-picker/__tests__/__snapshots__/demo.test.tsx.snap
  components/time-picker/__tests__/index.test.tsx
  components/time-picker/demo/style-class.md
  components/time-picker/demo/style-class.tsx
  components/time-picker/index.en-US.md
  components/time-picker/index.tsx
  components/time-picker/index.zh-CN.md
Labels: lgtm

#55166 chore: turn on ts/consistent-type-imports
  components/color-picker/interface.ts
  eslint.config.mjs
  typings/custom-typings.d.ts
Labels: skip-verify-files, lgtm

#55171 chore: turn on test/prefer-hooks-in-order
  components/_util/__tests__/scrollTo.test.ts
  components/_util/__tests__/util.test.tsx
  components/_util/__tests__/warning.test.tsx
  components/_util/__tests__/wave.test.tsx
  components/affix/__tests__/Affix.test.tsx
  components/auto-complete/__tests__/focus.test.tsx
  components/config-provider/__tests__/form.test.tsx
  components/table/__tests__/empty.test.tsx
  components/tooltip/__tests__/tooltip.test.tsx
  components/upload/__tests__/upload.test.tsx
  components/upload/__tests__/uploadlist.test.tsx
  components/watermark/__tests__/index.test.tsx
  eslint.config.mjs
Labels: skip-verify-files, lgtm

#55169 chore: turn on unicorn/prefer-includes
  .dumi/remarkAnchor.ts
  .dumi/theme/layouts/DocLayout/index.tsx
  .dumi/theme/slots/Content/Contributors.tsx
  components/auto-complete/demo/non-case-sensitive.tsx
  components/cascader/demo/search.tsx
  components/menu/demo/sider-current.tsx
  components/tag/demo/animation.tsx
  components/transfer/demo/component-token.tsx
  components/transfer/demo/search.tsx
  components/tree/demo/search.tsx
  eslint.config.mjs
Labels: skip-verify-files, lgtm

#55176 chore: sync feature into next
  .dumi/remarkAnchor.ts
  .dumi/theme/common/styles/index.ts
  .dumi/theme/layouts/DocLayout/index.tsx
  .dumi/theme/slots/Content/ContributorAvatar.tsx
  .dumi/theme/slots/Content/Contributors.tsx
  SECURITY.md
  components/_util/__tests__/isPrimitive.test.ts
  components/_util/__tests__/scrollTo.test.ts
  components/_util/__tests__/util.test.tsx
  components/_util/__tests__/warning.test.tsx
  components/_util/__tests__/wave.test.tsx
  components/affix/__tests__/Affix.test.tsx
  components/auto-complete/__tests__/focus.test.tsx
  components/auto-complete/demo/non-case-sensitive.tsx
  components/cascader/demo/search.tsx
  components/color-picker/index.tsx
  components/color-picker/interface.ts
  components/config-provider/UnstableContext.tsx
  components/config-provider/__tests__/form.test.tsx
  components/index.ts
  components/input/index.zh-CN.md
  components/list/index.tsx
  components/masonry/__tests__/index.test.tsx
  components/menu/demo/sider-current.tsx
  components/menu/index.tsx
  components/message/interface.ts
  components/modal/useModal/index.tsx
  components/notification/interface.ts
  components/space/__tests__/gap.test.tsx
  components/table/__tests__/empty.test.tsx
  components/tag/demo/animation.tsx
  components/theme/interface/index.ts
  components/theme/internal.ts
  components/tooltip/__tests__/tooltip.test.tsx
  components/transfer/demo/component-token.tsx
  components/transfer/demo/search.tsx
  components/transfer/index.tsx
  components/tree/demo/search.tsx
  components/tree/index.tsx
  components/upload/__tests__/upload.test.tsx
  components/upload/__tests__/uploadlist.test.tsx
  components/upload/index.en-US.md
  components/upload/index.zh-CN.md
  components/upload/interface.ts
  components/watermark/__tests__/index.test.tsx
  contributors.json
  eslint.config.mjs
  package.json
  scripts/__snapshots__/check-site.ts.snap
  scripts/generate-authors.ts
  typings/custom-typings.d.ts
  typings/jest.d.ts
Labels: BranchAutoMerge

#55173 docs: fix popconfirm style
  components/popconfirm/demo/basic.tsx
Labels: lgtm

#54965 feat(slider): Support better customization with semantic classNames/styles as function
  components/slider/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/slider/__tests__/__snapshots__/demo.test.ts.snap
  components/slider/__tests__/index.test.tsx
  components/slider/demo/style-class.md
  components/slider/demo/style-class.tsx
  components/slider/index.en-US.md
  components/slider/index.tsx
  components/slider/index.zh-CN.md
Labels: lgtm

#55188 test: update snap
  components/transfer/__tests__/__snapshots__/demo-extend.test.ts.snap
Labels: lgtm

#55186 site: use SWR, make response always fast and reactive
  .dumi/hooks/useFetch/cache.ts
  .dumi/hooks/useFetch/index.ts
  .dumi/pages/index/components/BannerRecommends.tsx
  .dumi/pages/index/components/util.ts
  .dumi/theme/builtins/ResourceArticles/index.tsx
  .dumi/theme/common/ComponentChangelog/ComponentChangelog.tsx
  package.json
Labels: lgtm

#55117 feat(statistic): Support better customization with semantic classNames/styles as function
  components/statistic/Statistic.tsx
  components/statistic/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/statistic/__tests__/__snapshots__/demo.test.ts.snap
  components/statistic/__tests__/index.test.tsx
  components/statistic/demo/style-class.md
  components/statistic/demo/style-class.tsx
  components/statistic/index.en-US.md
  components/statistic/index.zh-CN.md
Labels: lgtm

#54983 feat(table): Support better customization with semantic classNames/styles as function
  components/table/InternalTable.tsx
  components/table/__tests__/Table.semantic.test.tsx
  components/table/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/table/__tests__/__snapshots__/demo.test.ts.snap
  components/table/demo/style-class.md
  components/table/demo/style-class.tsx
  components/table/index.en-US.md
  components/table/index.zh-CN.md
Labels: lgtm

#55096 feat(Drawer): Support better customization with semantic classNames & styles
  components/drawer/DrawerPanel.tsx
  components/drawer/__tests__/Drawer.test.tsx
  components/drawer/__tests__/__snapshots__/demo-extend.test.tsx.snap
  components/drawer/__tests__/__snapshots__/demo.test.ts.snap
  components/drawer/demo/classNames.tsx
  components/drawer/demo/style-class.md
  components/drawer/demo/style-class.tsx
  components/drawer/index.en-US.md
  components/drawer/index.tsx
  components/drawer/index.zh-CN.md
Labels: lgtm

#55081 feat(Modal): Support better customization with semantic classNames & styles
  components/modal/ConfirmDialog.tsx
  components/modal/Modal.tsx
  components/modal/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/modal/__tests__/__snapshots__/demo.test.tsx.snap
  components/modal/__tests__/style-class.test.tsx
  components/modal/demo/mask.tsx
  components/modal/demo/style-class.md
  components/modal/demo/style-class.tsx
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
  components/modal/interface.ts
Labels: lgtm

#55021 feat(notification): Support better customization with semantic classNames/styles as function
  components/notification/PurePanel.tsx
  components/notification/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/notification/__tests__/__snapshots__/demo.test.ts.snap
  components/notification/__tests__/semantic.test.tsx
  components/notification/demo/style-class.md
  components/notification/demo/style-class.tsx
  components/notification/index.en-US.md
  components/notification/index.zh-CN.md
  components/notification/interface.ts
  components/notification/useNotification.tsx
Labels: lgtm

#55157 feat(spin): Support better customization with semantic classNames/styles as function
  components/spin/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/spin/__tests__/__snapshots__/demo.test.ts.snap
  components/spin/__tests__/semantic.test.tsx
  components/spin/demo/style-class.md
  components/spin/demo/style-class.tsx
  components/spin/index.en-US.md
  components/spin/index.tsx
  components/spin/index.zh-CN.md
Labels: lgtm

#55054 feat(message): support better customization with semantic classNames/styles
  components/message/PurePanel.tsx
  components/message/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/message/__tests__/__snapshots__/demo.test.ts.snap
  components/message/__tests__/semantic.test.tsx
  components/message/demo/style-class.md
  components/message/demo/style-class.tsx
  components/message/index.en-US.md
  components/message/index.zh-CN.md
  components/message/interface.ts
  components/message/useMessage.tsx
  scripts/__snapshots__/check-site.ts.snap
Labels: skip-verify-files, lgtm

#55119 feat(segmented): Support better customization with semantic classNames/styles as function
  components/segmented/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/segmented/__tests__/__snapshots__/demo.test.ts.snap
  components/segmented/__tests__/index.test.tsx
  components/segmented/demo/style-class.md
  components/segmented/demo/style-class.tsx
  components/segmented/index.en-US.md
  components/segmented/index.tsx
  components/segmented/index.zh-CN.md
Labels: lgtm

#54985 feat(timeline): Support better customization with semantic classNames/styles as function
  components/timeline/Timeline.tsx
  components/timeline/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/timeline/__tests__/__snapshots__/demo.test.ts.snap
  components/timeline/__tests__/index.test.tsx
  components/timeline/demo/style-class.md
  components/timeline/demo/style-class.tsx
  components/timeline/index.en-US.md
  components/timeline/index.zh-CN.md
Labels: lgtm

#54987 feat(tour): Support better customization with semantic classNames/styles as function
  components/tour/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tour/__tests__/__snapshots__/demo.test.tsx.snap
  components/tour/__tests__/index.test.tsx
  components/tour/demo/style-class.md
  components/tour/demo/style-class.tsx
  components/tour/index.en-US.md
  components/tour/index.tsx
  components/tour/index.zh-CN.md
  components/tour/interface.ts
  components/tour/panelRender.tsx
Labels: lgtm

#54986 feat(Popover/Tooltip/Popconfirm): Support better customization with semantic classNames/styles as function
  components/popconfirm/PurePanel.tsx
  components/popconfirm/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/popconfirm/__tests__/__snapshots__/demo.test.tsx.snap
  components/popconfirm/__tests__/index.test.tsx
  components/popconfirm/demo/_semantic.tsx
  components/popconfirm/demo/style-class.md
  components/popconfirm/demo/style-class.tsx
  components/popconfirm/index.en-US.md
  components/popconfirm/index.tsx
  components/popconfirm/index.zh-CN.md
  components/popover/PurePanel.tsx
  components/popover/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/popover/__tests__/__snapshots__/demo.test.tsx.snap
  components/popover/__tests__/index.test.tsx
  components/popover/demo/_semantic.tsx
  components/popover/demo/style-class.md
  components/popover/demo/style-class.tsx
  components/popover/index.en-US.md
  components/popover/index.tsx
  components/popover/index.zh-CN.md
  components/tooltip/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tooltip/__tests__/__snapshots__/demo.test.tsx.snap
  components/tooltip/__tests__/tooltip.test.tsx
  components/tooltip/demo/_semantic.tsx
  components/tooltip/demo/style-class.md
  components/tooltip/demo/style-class.tsx
  components/tooltip/index.en-US.md
  components/tooltip/index.tsx
  components/tooltip/index.zh-CN.md
  components/tooltip/shared/sharedProps.en-US.md
  components/tooltip/shared/sharedProps.zh-CN.md
Labels: lgtm

#55099 feat(Skeleton): Support better customization with semantic classNames & styles
  components/skeleton/Skeleton.tsx
  components/skeleton/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/skeleton/__tests__/__snapshots__/demo.test.tsx.snap
  components/skeleton/__tests__/index.test.tsx
  components/skeleton/demo/_semantic_element.tsx
  components/skeleton/demo/style-class.md
  components/skeleton/demo/style-class.tsx
  components/skeleton/index.en-US.md
  components/skeleton/index.zh-CN.md
  components/skeleton/shared/sharedProps.en-US.md
  components/skeleton/shared/sharedProps.zh-CN.md
Labels: lgtm

#54962 feat(color-picker): Support better customization with semantic classNames/styles as function
  components/color-picker/ColorPicker.tsx
  components/color-picker/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/color-picker/__tests__/__snapshots__/demo.test.tsx.snap
  components/color-picker/__tests__/__snapshots__/semantic.test.tsx.snap
  components/color-picker/__tests__/semantic.test.tsx
  components/color-picker/demo/style-class.md
  components/color-picker/demo/style-class.tsx
  components/color-picker/index.en-US.md
  components/color-picker/index.zh-CN.md
  components/color-picker/interface.ts
  components/descriptions/index.en-US.md
  components/notification/index.en-US.md
  components/notification/index.zh-CN.md
  components/qr-code/index.en-US.md
  components/qr-code/index.tsx
  components/qr-code/index.zh-CN.md
  components/result/index.tsx
Labels: lgtm

#54977 feat(badge): Support better customization with semantic classNames/styles as function
  components/badge/Ribbon.tsx
  components/badge/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/badge/__tests__/__snapshots__/demo.test.tsx.snap
  components/badge/__tests__/index.test.tsx
  components/badge/__tests__/ribbon.test.tsx
  components/badge/demo/style-class.md
  components/badge/demo/style-class.tsx
  components/badge/index.en-US.md
  components/badge/index.tsx
  components/badge/index.zh-CN.md
Labels: lgtm

#54967 feat(tree-select): Support better customization with semantic classNames/styles as function
  components/tree-select/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tree-select/__tests__/__snapshots__/demo.test.tsx.snap
  components/tree-select/__tests__/index.test.tsx
  components/tree-select/demo/_semantic.tsx
  components/tree-select/demo/style-class.md
  components/tree-select/demo/style-class.tsx
  components/tree-select/index.en-US.md
  components/tree-select/index.tsx
  components/tree-select/index.zh-CN.md
Labels: lgtm
