Repository ant-design/ant-design, pull requests merged in 2025-04, with the labels that each got.

#53426 chore: sync master into feature
  .dumi/components/SemanticPreview.tsx
  .dumi/theme/builtins/Previewer/CodePreviewer.tsx
  .dumi/theme/slots/Footer/index.tsx
  package.json
Labels: BranchAutoMerge

#53470 chore: sync master into feature
  .dumi/pages/index/components/ComponentsList.tsx
  .dumi/pages/index/components/DesignFramework.tsx
  .dumi/pages/index/components/PreviewBanner/index.tsx
  .dumi/theme/layouts/ResourceLayout/index.tsx
  .dumi/theme/slots/Footer/index.tsx
  components/collapse/index.en-US.md
  components/collapse/index.zh-CN.md
  components/drawer/index.en-US.md
  components/drawer/index.zh-CN.md
  components/locale/zh_HK.ts
  components/locale/zh_TW.ts
  components/mentions/index.en-US.md
  components/mentions/index.zh-CN.md
  components/select/index.en-US.md
  components/select/index.zh-CN.md
  components/table/__tests__/Table.filter.test.tsx
  components/table/hooks/useFilter/index.tsx
  components/timeline/index.en-US.md
  components/timeline/index.zh-CN.md
  docs/blog/config-provider-style.en-US.md
  docs/blog/config-provider-style.zh-CN.md
  package.json
  scripts/generate-llms.ts
Labels: BranchAutoMerge

#53472 chore: sync feature into next
  .dumi/pages/index/components/ComponentsList.tsx
  .dumi/pages/index/components/DesignFramework.tsx
  .dumi/pages/index/components/PreviewBanner/index.tsx
  .dumi/theme/layouts/ResourceLayout/index.tsx
  .dumi/theme/slots/Footer/index.tsx
  components/collapse/index.en-US.md
  components/collapse/index.zh-CN.md
  components/drawer/index.en-US.md
  components/drawer/index.zh-CN.md
  components/locale/zh_HK.ts
  components/locale/zh_TW.ts
  components/mentions/index.en-US.md
  components/mentions/index.zh-CN.md
  components/select/index.en-US.md
  components/select/index.zh-CN.md
  components/table/__tests__/Table.filter.test.tsx
  components/table/hooks/useFilter/index.tsx
  components/timeline/index.en-US.md
  components/timeline/index.zh-CN.md
  components/upload/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/upload/__tests__/__snapshots__/demo.test.ts.snap
  components/upload/__tests__/upload.test.tsx
  components/upload/demo/paste.md
  components/upload/demo/paste.tsx
  components/upload/index.en-US.md
  components/upload/index.zh-CN.md
  components/upload/interface.ts
  docs/blog/config-provider-style.en-US.md
  docs/blog/config-provider-style.zh-CN.md
  package.json
  scripts/generate-llms.ts
Labels: BranchAutoMerge

#53401 feat: new component Statistic.Timer
  components/index.ts
  components/statistic/Countdown.tsx
  components/statistic/Timer.tsx
  components/statistic/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/statistic/__tests__/__snapshots__/demo.test.ts.snap
  components/statistic/__tests__/index.test.tsx
  components/statistic/demo/countdown.md
  components/statistic/demo/countdown.tsx
  components/statistic/demo/timer.md
  components/statistic/demo/timer.tsx
  components/statistic/index.en-US.md
  components/statistic/index.tsx
  components/statistic/index.zh-CN.md
  components/statistic/utils.ts
  scripts/__snapshots__/check-site.ts.snap
Labels: skip-verify-files

#53490 chore: sync master into feature
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: BranchAutoMerge

#53491 chore: sync feature into next
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/collapse/__tests__/index.test.tsx
  components/collapse/style/index.ts
  components/index.ts
  components/statistic/Countdown.tsx
  components/statistic/Timer.tsx
  components/statistic/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/statistic/__tests__/__snapshots__/demo.test.ts.snap
  components/statistic/__tests__/index.test.tsx
  components/statistic/demo/countdown.md
  components/statistic/demo/countdown.tsx
  components/statistic/demo/timer.md
  components/statistic/demo/timer.tsx
  components/statistic/index.en-US.md
  components/statistic/index.tsx
  components/statistic/index.zh-CN.md
  components/statistic/utils.ts
  package.json
  scripts/__snapshots__/check-site.ts.snap
Labels: BranchAutoMerge

#53498 docs: Fix the markdown syntax display issue in Carousel update log
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: skip-verify-files

#53524 chore: sync master into feature
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  README-zh_CN.md
  README.md
  components/descriptions/index.en-US.md
  components/input/style/textarea.ts
  components/list/index.tsx
  components/upload/UploadList/index.tsx
  components/upload/__tests__/uploadlist.test.tsx
  docs/blog/config-provider-style.en-US.md
  docs/blog/config-provider-style.zh-CN.md
  docs/react/migrate-less-variables.en-US.md
  package.json
Labels: BranchAutoMerge

#53527 chore: sync feature into next
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  README-zh_CN.md
  README.md
  components/descriptions/index.en-US.md
  components/input/style/textarea.ts
  components/list/index.tsx
  components/statistic/Countdown.tsx
  components/statistic/index.en-US.md
  components/statistic/index.zh-CN.md
  components/upload/UploadList/index.tsx
  components/upload/__tests__/uploadlist.test.tsx
  docs/blog/config-provider-style.en-US.md
  docs/blog/config-provider-style.zh-CN.md
  docs/react/migrate-less-variables.en-US.md
Labels: BranchAutoMerge

#53571 chore: sync master into feature
  .dumi/pages/index/components/DesignFramework.tsx
  .github/workflows/site-deploy.yml
  components/breadcrumb/Breadcrumb.tsx
  components/card/style/index.ts
  components/cascader/style/columns.ts
  components/date-picker/style/index.ts
  components/descriptions/style/index.ts
  components/dropdown/style/index.ts
  components/image/PreviewGroup.tsx
  components/input-number/style/index.ts
  components/input/style/index.ts
  components/input/style/textarea.ts
  components/mentions/style/index.ts
  components/select/style/index.ts
  components/table/style/filter.ts
  components/tabs/style/index.ts
  components/tag/style/index.ts
  components/tree-select/index.tsx
  components/typography/style/mixins.ts
  components/upload/style/index.ts
  components/upload/style/list.ts
Labels: BranchAutoMerge

#53568 docs: Improved English translations
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.en-US.md
  README.md
  docs/resources.en-US.md
  docs/spec/visualization-page.en-US.md
Labels: skip-verify-files

#53572 chore: sync feature into next
  .dumi/pages/index/components/DesignFramework.tsx
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/site-deploy.yml
  CHANGELOG.en-US.md
  README.md
  components/breadcrumb/Breadcrumb.tsx
  components/card/style/index.ts
  components/cascader/style/columns.ts
  components/date-picker/style/index.ts
  components/descriptions/style/index.ts
  components/dropdown/__tests__/index.test.tsx
  components/dropdown/dropdown-button.tsx
  components/dropdown/dropdown.tsx
  components/dropdown/index.en-US.md
  components/dropdown/index.zh-CN.md
  components/dropdown/style/index.ts
  components/image/PreviewGroup.tsx
  components/input-number/style/index.ts
  components/input/style/index.ts
  components/input/style/textarea.ts
  components/mentions/style/index.ts
  components/select/style/index.ts
  components/table/style/filter.ts
  components/tabs/style/index.ts
  components/tag/style/index.ts
  components/tree-select/index.tsx
  components/typography/style/mixins.ts
  components/upload/style/index.ts
  components/upload/style/list.ts
  docs/resources.en-US.md
  docs/spec/visualization-page.en-US.md
Labels: BranchAutoMerge

#53578 docs: release 5.24.8
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: skip-verify-files

#53591 docs: update changelog about llms.txt
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: skip-verify-files

#53593 chore: bump rc-image to 7.12.0 for rtl issue
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/image/__tests__/__snapshots__/index.test.tsx.snap
  package.json
Labels: skip-verify-files

#53597 chore: feature merge master
  .gitignore
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/form/__tests__/__snapshots__/demo.test.tsx.snap
  components/image/__tests__/__snapshots__/index.test.tsx.snap
  components/input/OTP/OTPInput.tsx
  components/input/OTP/index.tsx
  components/input/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/input/__tests__/__snapshots__/demo.test.tsx.snap
  components/input/__tests__/__snapshots__/otp.test.tsx.snap
  components/input/__tests__/otp.test.tsx
  components/input/style/otp.ts
  components/splitter/SplitBar.tsx
  components/splitter/Splitter.tsx
  components/splitter/__tests__/index.test.tsx
  components/splitter/__tests__/lazy.test.tsx
  components/splitter/__tests__/ssr.test.tsx
  components/splitter/style/index.ts
  components/timeline/TimelineItem.tsx
  package.json
  renovate.json
Labels: BranchAutoMerge

#53600 chore: next merge feature
  .gitignore
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/divider/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/divider/__tests__/__snapshots__/demo.test.ts.snap
  components/divider/__tests__/index.test.tsx
  components/divider/demo/size.md
  components/divider/demo/size.tsx
  components/divider/index.en-US.md
  components/divider/index.tsx
  components/divider/index.zh-CN.md
  components/divider/style/index.ts
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/form/__tests__/__snapshots__/demo.test.tsx.snap
  components/input/OTP/OTPInput.tsx
  components/input/OTP/index.tsx
  components/input/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/input/__tests__/__snapshots__/demo.test.tsx.snap
  components/input/__tests__/__snapshots__/otp.test.tsx.snap
  components/input/__tests__/otp.test.tsx
  components/input/style/otp.ts
  components/splitter/SplitBar.tsx
  components/splitter/Splitter.tsx
  components/splitter/__tests__/lazy.test.tsx
  components/splitter/__tests__/ssr.test.tsx
  components/splitter/style/index.ts
  components/timeline/TimelineItem.tsx
  package.json
  renovate.json
Labels: BranchAutoMerge

#53460 fix: Slider formatter returns fixed content, Tooltip position abnormal after dragging
  components/slider/SliderTooltip.tsx
  components/slider/__tests__/SliderTooltip.test.tsx
  components/slider/index.tsx
Labels: skip-verify-files

#53618 chore: sync feature into next
  .gitignore
  components/slider/SliderTooltip.tsx
  components/slider/__tests__/SliderTooltip.test.tsx
  components/slider/index.tsx
  package.json
Labels: BranchAutoMerge

#53642 chore: sync feature into next
  .dumi/theme/slots/Header/index.tsx
  components/auto-complete/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/auto-complete/__tests__/__snapshots__/demo.test.tsx.snap
  components/auto-complete/demo/certain-category.tsx
  components/auto-complete/demo/uncertain-category.tsx
  components/dropdown/__tests__/dropdown-button.test.tsx
  components/dropdown/dropdown-button.tsx
  components/dropdown/dropdown.tsx
  components/locale/bg_BG.ts
  components/locale/bn_BD.ts
  components/locale/by_BY.ts
  components/locale/ca_ES.ts
  components/locale/cs_CZ.ts
  components/locale/da_DK.ts
  components/locale/en_GB.ts
  components/locale/et_EE.ts
  components/locale/fi_FI.ts
  components/locale/fr_CA.ts
  components/locale/ga_IE.ts
  components/locale/gl_ES.ts
  components/locale/hi_IN.ts
  components/locale/hr_HR.ts
  components/locale/hu_HU.ts
  components/locale/hy_AM.ts
  components/locale/is_IS.ts
  components/locale/ka_GE.ts
  components/locale/kk_KZ.ts
  components/locale/kmr_IQ.ts
  components/locale/kn_IN.ts
  components/locale/ku_IQ.ts
  components/locale/lv_LV.ts
  components/locale/mk_MK.ts
  components/locale/ml_IN.ts
  components/locale/mn_MN.ts
  components/locale/nb_NO.ts
  components/locale/ro_RO.ts
  components/locale/si_LK.ts
  components/locale/sk_SK.ts
  components/locale/sl_SI.ts
  components/locale/sr_RS.ts
  components/locale/ta_IN.ts
  components/locale/tk_TK.ts
  components/locale/ur_PK.ts
  components/tour/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tour/__tests__/__snapshots__/demo.test.tsx.snap
  components/tour/__tests__/__snapshots__/index.test.tsx.snap
  components/tour/__tests__/index.test.tsx
  components/tour/panelRender.tsx
Labels: BranchAutoMerge

#53654 chore: unlock countup.js@2.8.0
  package.json
Labels: skip-verify-files

#53661 docs: Update README.md
  README-zh_CN.md
  README.md
Labels: skip-verify-files

#53666 docs(icon): add compatibility tips
  components/icon/index.en-US.md
  components/icon/index.zh-CN.md
Labels: skip-verify-files

#53676 docs: randomuser.me => mocky.io
  components/list/demo/infinite-load.tsx
  components/list/demo/loadmore.tsx
  components/list/demo/virtual-list.tsx
  components/select/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/select/demo/select-users.tsx
  components/table/demo/ajax.md
  components/table/demo/ajax.tsx
Labels: skip-verify-files

#53681 chore: sync master into feature
  .github/dependabot.yml
  BUG_VERSIONS.json
  README-zh_CN.md
  README.md
  components/affix/index.tsx
  components/icon/index.en-US.md
  components/icon/index.zh-CN.md
  components/list/demo/infinite-load.tsx
  components/list/demo/loadmore.tsx
  components/list/demo/virtual-list.tsx
  components/select/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/select/__tests__/image.test.ts
  components/select/demo/select-users.tsx
  components/select/style/index.ts
  components/splitter/SplitBar.tsx
  components/splitter/__tests__/lazy.test.tsx
  components/table/demo/ajax.md
  components/table/demo/ajax.tsx
  jest-puppeteer.config.js
  package.json
  tests/shared/imageTest.tsx
Labels: BranchAutoMerge

#53683 chore: sync feature into next
  .dumi/theme/builtins/ComponentTokenTable/index.tsx
  .dumi/theme/common/ComponentChangelog/ComponentChangelog.tsx
  .dumi/theme/slots/Header/index.tsx
  .github/dependabot.yml
  BUG_VERSIONS.json
  README-zh_CN.md
  README.md
  components/affix/index.tsx
  components/avatar/AvatarGroup.tsx
  components/color-picker/ColorPicker.tsx
  components/color-picker/index.en-US.md
  components/color-picker/index.zh-CN.md
  components/color-picker/interface.ts
  components/icon/index.en-US.md
  components/icon/index.zh-CN.md
  components/list/demo/infinite-load.tsx
  components/list/demo/loadmore.tsx
  components/list/demo/virtual-list.tsx
  components/popover/demo/_semantic.tsx
  components/select/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/select/__tests__/image.test.ts
  components/select/demo/select-users.tsx
  components/select/style/index.ts
  components/splitter/SplitBar.tsx
  components/splitter/__tests__/lazy.test.tsx
  components/table/demo/ajax.md
  components/table/demo/ajax.tsx
  components/tooltip/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tooltip/__tests__/__snapshots__/demo.test.tsx.snap
  components/tooltip/__tests__/tooltip.test.tsx
  components/tooltip/demo/destroy-on-close.md
  components/tooltip/demo/destroy-on-close.tsx
  components/tooltip/demo/destroy-tooltip-on-hide.md
  components/tooltip/index.en-US.md
  components/tooltip/index.tsx
  components/tooltip/index.zh-CN.md
  components/tooltip/shared/sharedProps.en-US.md
  components/tooltip/shared/sharedProps.zh-CN.md
  jest-puppeteer.config.js
  package.json
  tests/shared/imageTest.tsx
Labels: BranchAutoMerge

#53673 docs: update 5.24.9 changelog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: skip-verify-files

#53695 refactor: semantic dom structure
  .dumi/components/SelectSemanticTemplate.tsx
  .dumi/components/SemanticPreview.tsx
  .dumi/theme/slots/Header/index.tsx
  components/auto-complete/AutoComplete.tsx
  components/auto-complete/__tests__/index.test.tsx
  components/auto-complete/demo/_semantic.tsx
  components/auto-complete/demo/certain-category.tsx
  components/auto-complete/index.en-US.md
  components/auto-complete/index.zh-CN.md
  components/cascader/__tests__/index.test.tsx
  components/cascader/demo/_semantic.tsx
  components/cascader/index.en-US.md
  components/cascader/index.tsx
  components/cascader/index.zh-CN.md
  components/select/__tests__/index.test.tsx
  components/select/demo/_semantic.tsx
  components/select/index.en-US.md
  components/select/index.tsx
  components/select/index.zh-CN.md
  components/space/demo/compact.tsx
  components/tree-select/__tests__/index.test.tsx
  components/tree-select/demo/_semantic.tsx
  components/tree-select/demo/async.tsx
  components/tree-select/demo/basic.tsx
  components/tree-select/demo/component-token.tsx
  components/tree-select/demo/multiple.tsx
  components/tree-select/demo/placement.tsx
  components/tree-select/demo/suffix.tsx
  components/tree-select/demo/treeData.tsx
  components/tree-select/index.en-US.md
  components/tree-select/index.tsx
  components/tree-select/index.zh-CN.md
Labels: lgtm

#53696 chore: sync feature into next
  .dumi/components/SelectSemanticTemplate.tsx
  components/auto-complete/AutoComplete.tsx
  components/auto-complete/__tests__/index.test.tsx
  components/auto-complete/demo/_semantic.tsx
  components/auto-complete/index.en-US.md
  components/auto-complete/index.zh-CN.md
  components/cascader/__tests__/index.test.tsx
  components/cascader/demo/_semantic.tsx
  components/cascader/index.en-US.md
  components/cascader/index.tsx
  components/cascader/index.zh-CN.md
  components/select/__tests__/index.test.tsx
  components/select/demo/_semantic.tsx
  components/select/index.en-US.md
  components/select/index.tsx
  components/select/index.zh-CN.md
  components/tree-select/__tests__/index.test.tsx
  components/tree-select/index.en-US.md
  components/tree-select/index.tsx
  components/tree-select/index.zh-CN.md
Labels: BranchAutoMerge

#53694 feat: ConfigProvider support classNames and styles for Cascader
  .dumi/components/SelectSemanticTemplate.tsx
  components/auto-complete/AutoComplete.tsx
  components/cascader/__tests__/semantic.test.tsx
  components/cascader/demo/_semantic.tsx
  components/cascader/index.tsx
  components/select/index.tsx
  package.json
Labels: lgtm

#53697 refactor: popup structure
  components/color-picker/ColorPicker.tsx
  components/color-picker/__tests__/index.test.tsx
  components/color-picker/demo/_semantic.tsx
  components/color-picker/interface.ts
  components/tabs/demo/_semantic.tsx
  components/tabs/index.tsx
Labels: lgtm

#53702 chore: Compatible with Windows local run visual regression
  scripts/visual-regression/local.ts
Labels: lgtm

#53699 chore: clean similar function methods
  components/_util/wave/WaveEffect.tsx
  components/config-provider/UnstableContext.tsx
  components/message/index.tsx
  components/modal/confirm.tsx
  components/notification/index.tsx
Labels: lgtm

#53698 feat: ConfigProvider support classNames and styles for inputNumber
  components/config-provider/context.ts
  components/config-provider/index.en-US.md
  components/config-provider/index.zh-CN.md
  components/input-number/__tests__/index.test.tsx
  components/input-number/__tests__/semantic.test.tsx
  components/input-number/demo/_semantic.tsx
  components/input-number/index.en-US.md
  components/input-number/index.tsx
  components/input-number/index.zh-CN.md
  package.json
Labels: lgtm

#53705 docs: replace Chinese Punctuation Marks within English Documents
  components/config-provider/demo/holderRender.md
  components/config-provider/index.en-US.md
  components/form/index.en-US.md
  components/mentions/demo/status.md
  components/menu/index.en-US.md
  components/message/index.en-US.md
  components/radio/index.en-US.md
  components/typography/index.en-US.md
  docs/blog/contributor-development-maintenance-guide.en-US.md
  docs/react/introduce.en-US.md
  docs/react/migrate-less-variables.en-US.md
  docs/react/use-with-next.en-US.md
  docs/spec/data-entry.en-US.md
  docs/spec/navigation.en-US.md
  docs/spec/reaction.en-US.md
  docs/spec/visual.en-US.md
Labels: skip-verify-files, lgtm

#53703 fix(Splitter): use minimum value as fallback when historical value out of bound
  components/splitter/__tests__/index.test.tsx
  components/splitter/hooks/useResize.ts
Labels: lgtm

#53708 fix: Fixed the issue of multiple calls to onResizeEnd in lazy mode
  components/splitter/SplitBar.tsx
  components/splitter/Splitter.tsx
  components/splitter/__tests__/index.test.tsx
  components/splitter/__tests__/lazy.test.tsx
Labels: lgtm

#53709 chore: merge master into feature
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/__tests__/unstable.test.ts
  components/_util/wave/WaveEffect.tsx
  components/calendar/demo/lunar.tsx
  components/color-picker/__tests__/index.test.tsx
  components/color-picker/components/ColorAlphaInput.tsx
  components/color-picker/components/ColorHsbInput.tsx
  components/color-picker/components/ColorRgbInput.tsx
  components/config-provider/UnstableContext.tsx
  components/config-provider/demo/holderRender.md
  components/config-provider/index.en-US.md
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/form/__tests__/__snapshots__/demo.test.tsx.snap
  components/form/demo/layout-can-wrap.tsx
  components/form/index.en-US.md
  components/form/style/index.ts
  components/mentions/demo/status.md
  components/menu/index.en-US.md
  components/message/index.en-US.md
  components/message/index.tsx
  components/modal/confirm.tsx
  components/notification/index.tsx
  components/radio/index.en-US.md
  components/splitter/SplitBar.tsx
  components/splitter/Splitter.tsx
  components/splitter/__tests__/index.test.tsx
  components/splitter/__tests__/lazy.test.tsx
  components/splitter/hooks/useResize.ts
  components/table/demo/row-selection-debug.tsx
  components/table/hooks/useSorter.tsx
  components/typography/index.en-US.md
  components/watermark/index.tsx
  docs/blog/contributor-development-maintenance-guide.en-US.md
  docs/react/introduce.en-US.md
  docs/react/migrate-less-variables.en-US.md
  docs/react/use-with-next.en-US.md
  docs/spec/data-entry.en-US.md
  docs/spec/navigation.en-US.md
  docs/spec/reaction.en-US.md
  docs/spec/visual.en-US.md
  package.json
  scripts/visual-regression/local.ts
Labels: BranchAutoMerge
