Repository ant-design/ant-design, pull requests merged in 2025-08, with the labels that each got.

#54544 feat: add ContextIsolator component to Select
  components/cascader/__tests__/index.test.tsx
  components/cascader/index.tsx
  components/select/__tests__/index.test.tsx
  components/select/index.tsx
  components/select/usePopupRender.tsx
  components/tree-select/__tests__/index.test.tsx
  components/tree-select/index.tsx
Labels: skip-verify-files, lgtm

#54559 chore: sync feature into next
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/_util/__tests__/util.test.tsx
  components/_util/throttleByAnimationFrame.ts
  components/button/button.tsx
  components/cascader/__tests__/index.test.tsx
  components/cascader/index.tsx
  components/menu/interface.ts
  components/select/__tests__/index.test.tsx
  components/select/index.tsx
  components/select/usePopupRender.tsx
  components/splitter/SplitBar.tsx
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/tree-select/__tests__/index.test.tsx
  components/tree-select/index.en-US.md
  components/tree-select/index.tsx
  components/tree-select/index.zh-CN.md
  components/typography/Base/CopyBtn.tsx
  components/typography/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/typography/__tests__/__snapshots__/demo.test.tsx.snap
  components/upload/interface.ts
  package.json
Labels: BranchAutoMerge

#54569 chore: code optimization
  components/splitter/SplitBar.tsx
Labels: lgtm

#54552 feat: Adapt text color based on Tooltip color
  components/tooltip/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tooltip/__tests__/__snapshots__/demo.test.tsx.snap
  components/tooltip/__tests__/tooltip.test.tsx
  components/tooltip/style/index.ts
  components/tooltip/util.ts
Labels: lgtm

#54560 docs: select Q&A
  components/select/index.en-US.md
  components/select/index.zh-CN.md
Labels: skip-verify-files, lgtm

#54578 chore: fix Split eslint error
  components/select/index.en-US.md
  components/select/index.zh-CN.md
  components/splitter/SplitBar.tsx
Labels: skip-verify-files, lgtm

#54574 chore: fix convert ts 2 js logic
  .dumi/theme/utils/tsToJs.ts
Labels: skip-verify-files, lgtm

#54585 fix(InputNumber): fix suffix shift on hover in readonly state
  components/input-number/__tests__/suffix.test.tsx
  components/input-number/index.tsx
Labels: lgtm

#54595 refactor: semantic of notification
  components/notification/PurePanel.tsx
  components/notification/useNotification.tsx
Labels: lgtm

#54603 refactor: semantic of tour/empty/result
  components/empty/index.tsx
  components/result/index.tsx
  components/tour/index.tsx
Labels: lgtm

#54615 fix: formatter demo
  components/input-number/demo/formatter.tsx
Labels: lgtm

#54600 feat: Table check header props
  components/table/__tests__/Table.rowSelection.test.tsx
  components/table/hooks/useSelection.tsx
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/table/interface.ts
Labels: lgtm

#54619 fix: Modal and Drawer panelRef prop should work
  components/drawer/index.tsx
  components/modal/Modal.tsx
Labels: lgtm

#54611 fix: form layout style
  components/auto-complete/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/auto-complete/__tests__/__snapshots__/demo.test.tsx.snap
  components/button/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/button/__tests__/__snapshots__/demo.test.ts.snap
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/config-provider/__tests__/__snapshots__/form.test.tsx.snap
  components/drawer/__tests__/__snapshots__/demo-extend.test.tsx.snap
  components/form/Form.tsx
  components/form/FormItem/ItemHolder.tsx
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/form/__tests__/__snapshots__/demo.test.tsx.snap
  components/form/__tests__/__snapshots__/index.test.tsx.snap
  components/form/__tests__/index.test.tsx
  components/form/context.tsx
  components/form/demo/layout-multiple.tsx
  components/form/style/index.ts
  components/input/__tests__/__snapshots__/index.test.tsx.snap
  components/mentions/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/mentions/__tests__/__snapshots__/demo.test.tsx.snap
  components/select/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/select/__tests__/__snapshots__/demo.test.tsx.snap
  components/skeleton/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/skeleton/__tests__/__snapshots__/demo.test.tsx.snap
  components/table/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/table/__tests__/__snapshots__/demo.test.ts.snap
  components/upload/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/upload/__tests__/__snapshots__/demo.test.ts.snap
  components/watermark/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/watermark/__tests__/__snapshots__/demo.test.ts.snap
Labels: lgtm

#54621 feat(theme): Add new CSS variables for the "size" series.
  components/theme/useToken.ts
Labels: lgtm

#54622 refactor: remove unnecessary object spread syntax for genFocusOutline calls
  components/_util/wave/style.ts
  components/calendar/style/index.ts
  components/cascader/style/index.ts
  components/cascader/style/panel.ts
  components/checkbox/style/index.ts
  components/color-picker/style/index.ts
  components/empty/style/index.ts
  components/form/style/fallbackCmp.ts
  components/input/style/otp.ts
  components/input/style/textarea.ts
  components/layout/style/index.ts
  components/layout/style/sider.ts
  components/mentions/style/index.ts
  components/menu/style/theme.ts
  components/message/style/index.ts
  components/modal/style/confirm.ts
  components/pagination/style/bordered.ts
  components/pagination/style/index.ts
  components/radio/style/index.ts
  components/rate/style/index.ts
  components/segmented/style/index.ts
  components/skeleton/style/index.ts
  components/spin/style/index.ts
  components/splitter/style/index.ts
  components/statistic/style/index.ts
  components/steps/style/index.ts
  components/style/index.tsx
  components/theme/util/useResetIconStyle.ts
  components/timeline/style/index.ts
  components/tour/style/index.ts
  components/tree-select/style/index.ts
  components/tree/style/index.ts
  components/typography/style/index.ts
Labels: lgtm

#54502 feat(Empty): support image global config
  components/config-provider/context.ts
  components/config-provider/index.en-US.md
  components/config-provider/index.zh-CN.md
  components/empty/__tests__/index.test.tsx
  components/empty/index.tsx
Labels: lgtm

#54629 feat(Button): add iconGap design token
  components/button/style/index.ts
  components/button/style/token.ts
Labels: lgtm

#54634 style(DatePicker): avoid important syntax in week panel cell inner style
  components/date-picker/style/panel.ts
Labels: lgtm

#54636 fix: Tabs ref prop should work
  components/tabs/__tests__/index.test.tsx
  components/tabs/index.tsx
Labels: lgtm

#54607 feat[Modal]: add onClose into closable
  components/modal/ConfirmDialog.tsx
  components/modal/Modal.tsx
  components/modal/__tests__/Modal.test.tsx
  components/modal/__tests__/hook.test.tsx
  components/modal/components/ConfirmCancelBtn.tsx
  components/modal/components/ConfirmOkBtn.tsx
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
  components/modal/interface.ts
  package.json
  scripts/__snapshots__/check-site.ts.snap
Labels: lgtm

#54643 docs: changelog 5.27.0
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: skip-verify-files, lgtm

#54647 fix: correct the JSDoc description of WaveConfig
  components/config-provider/context.ts
Labels: skip-verify-files, lgtm

#54645 feat[Notification]: Add onClose into closable
  components/notification/PurePanel.tsx
  components/notification/__tests__/index.test.tsx
  components/notification/index.en-US.md
  components/notification/index.zh-CN.md
  components/notification/interface.ts
  components/notification/useNotification.tsx
  package.json
  scripts/__snapshots__/check-site.ts.snap
Labels: lgtm

#54651 fix[Modal]: refine closable type handling and conditional rendering logic
  components/modal/Modal.tsx
Labels: lgtm

#54658 docs: Optimize the description of the color attribute
  components/tooltip/index.en-US.md
  components/tooltip/index.zh-CN.md
  components/tooltip/style/index.ts
Labels: skip-verify-files, lgtm

#54671 docs(popover): remove redundant desc
  components/tooltip/shared/sharedProps.en-US.md
  components/tooltip/shared/sharedProps.zh-CN.md
Labels: skip-verify-files, lgtm

#54680 feat(Breadcrumb): support separator global config
  components/breadcrumb/Breadcrumb.tsx
  components/breadcrumb/__tests__/Breadcrumb.test.tsx
  components/config-provider/context.ts
  components/config-provider/index.en-US.md
  components/config-provider/index.tsx
  components/config-provider/index.zh-CN.md
Labels: lgtm

#54682 chore: fix biome error
  .dumi/theme/builtins/Previewer/stackblitzConfig.ts
  .dumi/theme/slots/Content/ContributorAvatar.tsx
  biome.json
  components/_util/isPrimitive.ts
  components/badge/__tests__/index.test.tsx
  components/button/button-group.tsx
  components/date-picker/__tests__/DatePicker.test.tsx
  components/date-picker/__tests__/RangePicker.test.tsx
  components/date-picker/style/variants.ts
  components/form/ErrorList.tsx
  components/image/demo/toolbarRender.tsx
  components/list/__tests__/Item.test.tsx
  components/locale/tr_TR.ts
  components/typography/Base/index.tsx
  components/upload/__tests__/uploadlist.test.tsx
  tests/__mocks__/rc-util/lib/Portal.tsx
  webpack.config.js
Labels: skip-verify-files, lgtm

#54688 chore(biome): turn off suspicious. noTsIgnore
  biome.json
Labels: skip-verify-files, lgtm

#54692 chore: bump biome@2.2.0
  package.json
Labels: skip-verify-files, lgtm

#54703 docs(theme): Add "size" series variables description
  components/theme/interface/maps/size.ts
Labels: lgtm

#54711 chore: sync feature into next
  .dumi/pages/theme-editor/index.tsx
  biome.json
  components/collapse/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/collapse/__tests__/__snapshots__/demo.test.ts.snap
  components/collapse/demo/collapsible.tsx
  components/collapse/style/index.ts
  components/image/demo/preview-group-top-progress.tsx
  components/image/demo/preview-group.tsx
  components/image/style/index.ts
  components/pagination/style/index.ts
  components/theme/interface/maps/size.ts
  package.json
Labels: BranchAutoMerge

#54707 feat[Drawer]: Add blur effect to mask
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/config-provider/context.ts
  components/drawer/__tests__/Drawer.test.tsx
  components/drawer/__tests__/__snapshots__/Drawer.test.tsx.snap
  components/drawer/__tests__/__snapshots__/DrawerEvent.test.tsx.snap
  components/drawer/__tests__/__snapshots__/demo-extend.test.tsx.snap
  components/drawer/__tests__/__snapshots__/demo.test.ts.snap
  components/drawer/demo/mask.md
  components/drawer/demo/mask.tsx
  components/drawer/index.en-US.md
  components/drawer/index.tsx
  components/drawer/index.zh-CN.md
  components/drawer/style/index.ts
Labels: lgtm

#54715 fix: Nest form with noStyle context passing
  components/form/Form.tsx
  components/form/__tests__/index.test.tsx
Labels: lgtm

#54717 docs: changelog of 5.27.1
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: skip-verify-files, lgtm

#54718 docs: fix typo in paste code snippet version attribute
  components/upload/index.en-US.md
Labels: skip-verify-files, lgtm

#54719 chore(qrcode): use direct icon import to enable tree shaking
  components/qr-code/QrcodeStatus.tsx
Labels: lgtm

#54727 feat: Add vertical attribute to Radio Group component
  components/radio/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/radio/__tests__/__snapshots__/demo.test.tsx.snap
  components/radio/__tests__/group.test.tsx
  components/radio/demo/radiogroup-more.tsx
  components/radio/group.tsx
  components/radio/index.en-US.md
  components/radio/index.zh-CN.md
  components/radio/interface.ts
  components/radio/style/index.ts
Labels: lgtm

#54731 docs(Table): update Table component doc
  components/table/index.en-US.md
  components/table/index.zh-CN.md
Labels: skip-verify-files, lgtm

#54661 fix(Radio) : Radio.Group display shows jagged edges and left border of the first element in the new row overflows.
  components/radio/style/index.ts
Labels: lgtm

#54740 chore: use webpack to bundle umd
  .fatherrc.ts
  package.json
Labels: lgtm

#54748 fix(locale): add missing vietnamese translation for color picker, qrcode, text components
  components/locale/vi_VN.ts
Labels: lgtm

#54628 feat(Row): The "gutter" parameter supports the string type.
  components/grid/RowContext.ts
  components/grid/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/grid/__tests__/__snapshots__/demo.test.ts.snap
  components/grid/__tests__/index.test.tsx
  components/grid/col.tsx
  components/grid/demo/gutter.md
  components/grid/demo/gutter.tsx
  components/grid/hooks/useGutter.ts
  components/grid/index.en-US.md
  components/grid/index.zh-CN.md
  components/grid/row.tsx
Labels: lgtm

#54209 docs(slider): improve en minor gramma
  components/slider/index.en-US.md
Labels: skip-verify-files, lgtm

#54752 fix: reset copybtn getPopupContainer
  components/typography/Base/CopyBtn.tsx
Labels: lgtm

#54756 feat(Upload ): Add pictureCardSize token
  components/upload/__tests__/uploadlist.test.tsx
  components/upload/style/index.ts
Labels: lgtm

#54747 fix: badge support text props as number 0
  components/badge/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/badge/__tests__/__snapshots__/demo.test.tsx.snap
  components/badge/demo/mix.tsx
  components/badge/index.tsx
Labels: lgtm

#54767 fix: Modal Demo Page error
  .dumi/global.less
Labels: skip-verify-files, lgtm

#54763 fix(Typography): linkHoverDecoration
  components/style/index.tsx
Labels: lgtm

#54702 feat(Image): support fallback global config
  components/config-provider/context.ts
  components/config-provider/index.en-US.md
  components/config-provider/index.zh-CN.md
  components/image/index.tsx
Labels: lgtm

#54714 feat[Image]: Add blur effect to mask
  components/_util/hooks/useMergedMask.ts
  components/config-provider/context.ts
  components/drawer/__tests__/Drawer.test.tsx
  components/drawer/index.tsx
  components/drawer/style/index.ts
  components/image/PreviewGroup.tsx
  components/image/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/image/__tests__/__snapshots__/demo.test.ts.snap
  components/image/__tests__/__snapshots__/index.test.tsx.snap
  components/image/__tests__/deprecated.test.tsx
  components/image/__tests__/index.test.tsx
  components/image/demo/mask.md
  components/image/demo/mask.tsx
  components/image/hooks/useMergedPreviewConfig.ts
  components/image/hooks/usePreviewConfig.ts
  components/image/index.en-US.md
  components/image/index.tsx
  components/image/index.zh-CN.md
  components/image/style/index.ts
  components/modal/__tests__/Modal.test.tsx
  components/modal/interface.ts
  components/modal/style/index.ts
  components/style/index.tsx
Labels: lgtm

#54794 fix(Tabs): tabs remove icon not align centered vertically
  components/tabs/style/index.ts
Labels: lgtm

#54787 fix: Button token.paddingInline not working when shape="round"
  components/button/demo/component-token.tsx
  components/button/style/index.ts
Labels: lgtm

#54799 chore: improve code style
  components/drawer/DrawerPanel.tsx
  components/form/__tests__/index.test.tsx
  components/grid/col.tsx
  components/grid/row.tsx
Labels: lgtm

#54790 fix: make suffixIcon=undefined behave same as when unset
  components/date-picker/__tests__/DatePicker.test.tsx
  components/date-picker/__tests__/__snapshots__/DatePicker.test.tsx.snap
  components/date-picker/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/date-picker/__tests__/__snapshots__/demo.test.tsx.snap
  components/date-picker/demo/suffixIcon-debug.md
  components/date-picker/demo/suffixIcon-debug.tsx
  components/date-picker/generatePicker/SuffixIcon.tsx
  components/date-picker/generatePicker/generateRangePicker.tsx
  components/date-picker/generatePicker/generateSinglePicker.tsx
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
Labels: lgtm

#54804 chore: sync feature into next
  components/date-picker/__tests__/DatePicker.test.tsx
  components/date-picker/__tests__/__snapshots__/DatePicker.test.tsx.snap
  components/date-picker/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/date-picker/__tests__/__snapshots__/demo.test.tsx.snap
  components/date-picker/demo/suffixIcon-debug.md
  components/date-picker/demo/suffixIcon-debug.tsx
  components/date-picker/generatePicker/SuffixIcon.tsx
  components/date-picker/generatePicker/generateRangePicker.tsx
  components/date-picker/generatePicker/generateSinglePicker.tsx
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
  components/drawer/DrawerPanel.tsx
  components/grid/col.tsx
  components/grid/demo/gutter.md
  components/grid/index.en-US.md
  components/grid/index.zh-CN.md
  components/grid/row.tsx
Labels: BranchAutoMerge, lgtm

#54807 refactor: semantic of drawer
  components/drawer/DrawerPanel.tsx
  components/drawer/index.tsx
Labels: lgtm
