Repository ant-design/ant-design, pull requests merged in 2025-07, with the labels that each got.

#54257 type: Replace `any` with `RcFile` in transformFile
  components/upload/Upload.tsx
Labels: lgtm

#54254 site: add BehaviorPattern for en page
  .dumi/theme/common/BehaviorMap/BehaviorMap.tsx
  .dumi/theme/slots/ContentTabs/index.tsx
  components/alert/design/behavior-pattern.tsx
  components/alert/design/demo/action.tsx
  components/alert/design/demo/content.tsx
  components/alert/design/demo/type.tsx
  components/alert/index.$tab-design.en-US.md
  components/breadcrumb/demo/basic.tsx
  components/breadcrumb/design/behavior-pattern.tsx
  components/breadcrumb/index.$tab-design.en-US.md
  components/date-picker/design/behavior-pattern.tsx
  components/date-picker/index.$tab-design.en-US.md
  components/pagination/design/behavior-pattern.tsx
  components/pagination/design/demo/mini.tsx
  components/pagination/design/demo/total.tsx
  components/pagination/index.$tab-design.en-US.md
  components/progress/design/behavior-pattern.tsx
  components/progress/design/demo/info.tsx
  components/progress/design/demo/status.tsx
  components/progress/index.$tab-design.en-US.md
Labels: skip-verify-files, lgtm

#54251 fix: set fontWeight unitless
  components/cascader/style/index.ts
Labels: lgtm

#54252 docs: support docs dark in iframe color
  .dumi/theme/SiteThemeProvider.tsx
  .dumi/theme/common/BrowserFrame.tsx
Labels: skip-verify-files, lgtm

#54260 feat: useWatch support dynamic name path
  package.json
Labels: lgtm

#54272 chore: sync master into feature
  .dumi/global.less
  .dumi/theme/SiteThemeProvider.tsx
  .dumi/theme/common/BehaviorMap/BehaviorMap.tsx
  .dumi/theme/common/BrowserFrame.tsx
  .dumi/theme/slots/ContentTabs/index.tsx
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  biome.json
  components/_util/hooks/useClosable.tsx
  components/_util/reactNode.ts
  components/alert/design/behavior-pattern.tsx
  components/alert/design/demo/action.tsx
  components/alert/design/demo/content.tsx
  components/alert/design/demo/type.tsx
  components/alert/index.$tab-design.en-US.md
  components/badge/index.tsx
  components/breadcrumb/demo/basic.tsx
  components/breadcrumb/design/behavior-pattern.tsx
  components/breadcrumb/index.$tab-design.en-US.md
  components/cascader/style/index.ts
  components/config-provider/index.en-US.md
  components/date-picker/design/behavior-pattern.tsx
  components/date-picker/index.$tab-design.en-US.md
  components/form/FormItem/index.tsx
  components/input-number/index.en-US.md
  components/input-number/style/index.ts
  components/menu/MenuItem.tsx
  components/menu/SubMenu.tsx
  components/menu/menu.tsx
  components/pagination/design/behavior-pattern.tsx
  components/pagination/design/demo/mini.tsx
  components/pagination/design/demo/total.tsx
  components/pagination/index.$tab-design.en-US.md
  components/popover/index.tsx
  components/progress/design/behavior-pattern.tsx
  components/progress/design/demo/info.tsx
  components/progress/design/demo/status.tsx
  components/progress/index.$tab-design.en-US.md
  components/select/style/index.ts
  components/spin/Indicator/index.tsx
  components/splitter/hooks/useItems.ts
  components/steps/useLegacyItems.ts
  components/table/__tests__/Table.filter.test.tsx
  components/tabs/hooks/useLegacyItems.ts
  components/tour/PurePanel.tsx
  components/transfer/list.tsx
  components/tree/utils/iconUtil.tsx
  components/upload/Upload.tsx
  components/upload/UploadList/index.tsx
  docs/react/migrate-less-variables.en-US.md
  package.json
Labels: BranchAutoMerge

#54274 chore: sync feature into next
  .dumi/global.less
  .dumi/theme/SiteThemeProvider.tsx
  .dumi/theme/common/BehaviorMap/BehaviorMap.tsx
  .dumi/theme/common/BrowserFrame.tsx
  .dumi/theme/slots/ContentTabs/index.tsx
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  biome.json
  components/_util/reactNode.ts
  components/alert/design/behavior-pattern.tsx
  components/alert/design/demo/action.tsx
  components/alert/design/demo/content.tsx
  components/alert/design/demo/type.tsx
  components/alert/index.$tab-design.en-US.md
  components/badge/index.tsx
  components/breadcrumb/demo/basic.tsx
  components/breadcrumb/design/behavior-pattern.tsx
  components/breadcrumb/index.$tab-design.en-US.md
  components/cascader/style/index.ts
  components/date-picker/design/behavior-pattern.tsx
  components/date-picker/index.$tab-design.en-US.md
  components/form/FormItem/index.tsx
  components/input-number/index.en-US.md
  components/input-number/style/index.ts
  components/menu/menu.tsx
  components/pagination/design/behavior-pattern.tsx
  components/pagination/design/demo/mini.tsx
  components/pagination/design/demo/total.tsx
  components/pagination/index.$tab-design.en-US.md
  components/popover/index.tsx
  components/progress/design/behavior-pattern.tsx
  components/progress/design/demo/info.tsx
  components/progress/design/demo/status.tsx
  components/progress/index.$tab-design.en-US.md
  components/select/style/index.ts
  components/splitter/hooks/useItems.ts
  components/table/__tests__/Table.filter.test.tsx
  components/tabs/hooks/useLegacyItems.ts
  components/tour/PurePanel.tsx
  components/transfer/Section.tsx
  components/tree/utils/iconUtil.tsx
  components/upload/UploadList/index.tsx
  docs/react/migrate-less-variables.en-US.md
  package.json
Labels: BranchAutoMerge

#54275 docs: use AlibabaSans as website font family
  .dumi/pages/index/components/Group.tsx
  .dumi/pages/index/components/PreviewBanner/index.tsx
  .dumi/pages/index/components/Theme/MobileCarousel.tsx
  .dumi/theme/common/styles/Reset.tsx
  .dumi/theme/layouts/DocLayout/index.tsx
  .dumi/theme/slots/Header/Logo.tsx
Labels: skip-verify-files, lgtm

#54279 feat[Button]: Semantic Placement Naming Standardization
  components/button/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/button/__tests__/__snapshots__/demo.test.ts.snap
  components/button/__tests__/index.test.tsx
  components/button/button.tsx
  components/button/demo/icon-placement.md
  components/button/demo/icon-placement.tsx
  components/button/demo/icon-position.md
  components/button/demo/loading.tsx
  components/button/index.en-US.md
  components/button/index.zh-CN.md
  components/button/style/index.ts
  components/dropdown/demo/dropdown-button.tsx
Labels: lgtm

#54285 fix: prevent unnecessary theme switch when current theme is already selected
  .dumi/theme/common/ThemeSwitch/index.tsx
  .dumi/theme/layouts/GlobalLayout.tsx
Labels: skip-verify-files, lgtm

#54273 feat[Segmented]: add tooltip to segmented option item
  components/segmented/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/segmented/__tests__/__snapshots__/demo.test.ts.snap
  components/segmented/__tests__/index.test.tsx
  components/segmented/demo/custom.md
  components/segmented/demo/custom.tsx
  components/segmented/index.en-US.md
  components/segmented/index.tsx
  components/segmented/index.zh-CN.md
  package.json
Labels: lgtm

#54288 fix(performance): Avoid redundant array copying in flattenData for large datasets
  components/table/hooks/useSelection.tsx
Labels: skip-verify-files, lgtm

#54293 chore: remove unused fonts style
  .dumi/theme/common/styles/Reset.tsx
Labels: skip-verify-files, lgtm

#54303 docs: emoji compatible
  components/button/index.en-US.md
  components/button/index.zh-CN.md
Labels: skip-verify-files, lgtm

#54304 chore: merge master into feature
  .dumi/pages/index/components/Group.tsx
  .dumi/pages/index/components/PreviewBanner/index.tsx
  .dumi/pages/index/components/Theme/MobileCarousel.tsx
  .dumi/theme/common/ThemeSwitch/index.tsx
  .dumi/theme/common/styles/Reset.tsx
  .dumi/theme/layouts/DocLayout/index.tsx
  .dumi/theme/layouts/GlobalLayout.tsx
  .dumi/theme/slots/Header/Logo.tsx
  components/button/index.en-US.md
  components/button/index.zh-CN.md
  components/table/hooks/useSelection.tsx
Labels: BranchAutoMerge

#54206 fix: prefer using the name passed in the FormItemContext
  components/form/FormItem/ItemHolder.tsx
  components/form/FormItem/StatusProvider.tsx
  components/form/FormItem/index.tsx
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/form/__tests__/__snapshots__/demo.test.tsx.snap
  components/form/context.tsx
  components/form/hooks/useForm.ts
  components/radio/__tests__/group.test.tsx
  components/radio/group.tsx
Labels: lgtm

#54298 feat[Tag.CheckableTag]: Tag.CheckableTag supports icon property
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/tag/CheckableTag.tsx
  components/tag/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tag/__tests__/__snapshots__/demo.test.ts.snap
  components/tag/__tests__/__snapshots__/index.test.tsx.snap
  components/tag/__tests__/index.test.tsx
  components/tag/demo/icon.md
  components/tag/demo/icon.tsx
  components/tag/index.en-US.md
  components/tag/index.tsx
  components/tag/index.zh-CN.md
Labels: lgtm

#54314 revert: MenuProps add activeKey in Dropdown
  components/dropdown/dropdown.tsx
Labels: lgtm

#54311 feat[Collapse]: Semantic Placement Naming Standardization
  components/collapse/Collapse.tsx
  components/collapse/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/collapse/__tests__/__snapshots__/demo.test.ts.snap
  components/collapse/__tests__/__snapshots__/index.test.tsx.snap
  components/collapse/__tests__/index.test.tsx
  components/collapse/demo/extra.tsx
  components/collapse/index.en-US.md
  components/collapse/index.zh-CN.md
  components/collapse/style/index.ts
  components/color-picker/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
Labels: lgtm

#54332 chore: Update verify-files-modify.yml
  .github/workflows/verify-files-modify.yml
Labels: skip-verify-files, lgtm

#54349 fix: Modal responsive width
  components/modal/style/index.ts
Labels: lgtm

#54351 chore: merge master into feature
  .github/workflows/verify-files-modify.yml
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/date-picker/design/demo/date-extra-info.tsx
  components/dropdown/dropdown.tsx
  components/form/FormItem/ItemHolder.tsx
  components/form/FormItem/StatusProvider.tsx
  components/form/FormItem/index.tsx
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/form/__tests__/__snapshots__/demo.test.tsx.snap
  components/form/context.tsx
  components/form/hooks/useForm.ts
  components/modal/style/index.ts
  components/notification/PurePanel.tsx
  components/notification/__tests__/index.test.tsx
  components/notification/style/index.ts
  components/radio/__tests__/group.test.tsx
  components/radio/group.tsx
  components/splitter/SplitBar.tsx
  package.json
Labels: BranchAutoMerge

#54350 chore: merge master into feature
  .github/workflows/verify-files-modify.yml
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/date-picker/design/demo/date-extra-info.tsx
  components/dropdown/dropdown.tsx
  components/form/FormItem/ItemHolder.tsx
  components/form/FormItem/StatusProvider.tsx
  components/form/FormItem/index.tsx
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/form/__tests__/__snapshots__/demo.test.tsx.snap
  components/form/context.tsx
  components/form/hooks/useForm.ts
  components/modal/style/index.ts
  components/notification/PurePanel.tsx
  components/notification/__tests__/index.test.tsx
  components/notification/style/index.ts
  components/radio/__tests__/group.test.tsx
  components/radio/group.tsx
  components/splitter/SplitBar.tsx
  package.json
Labels: BranchAutoMerge

#54354 chore: merge feature into next
  .github/workflows/verify-files-modify.yml
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/date-picker/design/demo/date-extra-info.tsx
  components/divider/index.tsx
  components/dropdown/dropdown.tsx
  components/form/FormItem/ItemHolder.tsx
  components/form/FormItem/StatusProvider.tsx
  components/form/FormItem/index.tsx
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/form/__tests__/__snapshots__/demo.test.tsx.snap
  components/form/context.tsx
  components/form/hooks/useForm.ts
  components/modal/style/index.ts
  components/notification/PurePanel.tsx
  components/notification/__tests__/index.test.tsx
  components/notification/style/index.ts
  components/radio/__tests__/group.test.tsx
  components/radio/group.tsx
  components/splitter/SplitBar.tsx
  components/tag/CheckableTag.tsx
  components/tag/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tag/__tests__/__snapshots__/demo.test.tsx.snap
  components/tag/__tests__/__snapshots__/index.test.tsx.snap
  components/tag/__tests__/index.test.tsx
  components/tag/demo/icon.md
  components/tag/demo/icon.tsx
  components/tag/index.en-US.md
  components/tag/index.zh-CN.md
  package.json
Labels: BranchAutoMerge

#54353 chore: merge feature into next
  .github/workflows/verify-files-modify.yml
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/date-picker/design/demo/date-extra-info.tsx
  components/divider/index.tsx
  components/dropdown/dropdown.tsx
  components/form/FormItem/ItemHolder.tsx
  components/form/FormItem/StatusProvider.tsx
  components/form/FormItem/index.tsx
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/form/__tests__/__snapshots__/demo.test.tsx.snap
  components/form/context.tsx
  components/form/hooks/useForm.ts
  components/modal/style/index.ts
  components/notification/PurePanel.tsx
  components/notification/__tests__/index.test.tsx
  components/notification/style/index.ts
  components/radio/__tests__/group.test.tsx
  components/radio/group.tsx
  components/splitter/SplitBar.tsx
  components/tag/CheckableTag.tsx
  components/tag/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tag/__tests__/__snapshots__/demo.test.tsx.snap
  components/tag/__tests__/__snapshots__/index.test.tsx.snap
  components/tag/__tests__/index.test.tsx
  components/tag/demo/icon.md
  components/tag/demo/icon.tsx
  components/tag/index.en-US.md
  components/tag/index.zh-CN.md
  package.json
Labels: BranchAutoMerge

#54261 fix(float-button): remove bottom border when pop left or right
  components/float-button/style/index.ts
Labels: lgtm

#54342 feat[input.password]: Input.Password support suffix property
  components/input/Password.tsx
  components/input/__tests__/Password.test.tsx
  components/input/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/input/__tests__/__snapshots__/demo.test.tsx.snap
  components/input/demo/presuffix.md
  components/input/demo/presuffix.tsx
Labels: lgtm

#54369 chore: openMotion use useMemo
  components/collapse/Collapse.tsx
Labels: lgtm

#54376 chore: merge feature into next
  .devcontainer/devcontainer.json
  .dumi/theme/common/ThemeSwitch/index.tsx
  components/_util/hooks/useClosable.tsx
  components/collapse/Collapse.tsx
  components/image/demo/toolbarRender.tsx
  components/input/Password.tsx
  components/input/__tests__/Password.test.tsx
  components/input/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/input/__tests__/__snapshots__/demo.test.tsx.snap
  components/input/demo/presuffix.md
  components/input/demo/presuffix.tsx
  components/splitter/SplitBar.tsx
  components/tag/__tests__/index.test.tsx
Labels: BranchAutoMerge

#54377 chore: next sync master useClosable tag test
  components/tag/__tests__/index.test.tsx
Labels: lgtm

#54381 fix: correct SiteState type property name in GlobalLayout
  .dumi/theme/layouts/GlobalLayout.tsx
Labels: lgtm

#54384 fix: resolve non-null assertion logic error in useLocale hook
  .dumi/hooks/useLocale.ts
Labels: lgtm

#54382 feat[TimeLine]: Semantic Placement Naming Standardization
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/timeline/Timeline.tsx
  components/timeline/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/timeline/__tests__/__snapshots__/demo.test.ts.snap
  components/timeline/__tests__/index.test.tsx
  components/timeline/index.en-US.md
  components/timeline/index.zh-CN.md
  components/timeline/style/horizontal.ts
  components/timeline/style/index.ts
  components/timeline/useItems.tsx
Labels: lgtm

#54385 feat: Table scrollTo support offset
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  package.json
Labels: lgtm

#54358 feat[Tabs]: Semantic Placement Naming Standardization
  components/tabs/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tabs/__tests__/__snapshots__/demo.test.ts.snap
  components/tabs/__tests__/index.test.tsx
  components/tabs/demo/component-token.tsx
  components/tabs/demo/nest.tsx
  components/tabs/demo/placement.md
  components/tabs/demo/placement.tsx
  components/tabs/demo/position.md
  components/tabs/demo/slide.tsx
  components/tabs/index.en-US.md
  components/tabs/index.tsx
  components/tabs/index.zh-CN.md
Labels: lgtm

#54395 test: update Affix component test case
  components/affix/__tests__/Affix.test.tsx
Labels: lgtm

#54400 chore: sync master into feature
  .dumi/hooks/useLocale.ts
  .dumi/theme/layouts/GlobalLayout.tsx
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/affix/__tests__/Affix.test.tsx
  components/flex/__tests__/index.test.tsx
  components/flex/index.tsx
  components/flex/interface.ts
  components/menu/interface.ts
  contributors.json
  package.json
Labels: BranchAutoMerge

#54397 docs<Anchor>:add the :target cannot trigger the FAQ.
  components/anchor/index.en-US.md
  components/anchor/index.zh-CN.md
Labels: skip-verify-files, lgtm

#54409 Fix: Input variant=underlined use activeBorderColor
  components/input/style/variants.ts
Labels: lgtm

#54404 docs: date-picker components demo error
  components/date-picker/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/date-picker/__tests__/__snapshots__/demo.test.tsx.snap
  components/date-picker/demo/allow-empty.tsx
Labels: lgtm

#54415 refactor: semantic of floatButton
  components/float-button/FloatButtonGroup.tsx
  components/float-button/__tests__/semantic.test.tsx
  components/float-button/demo/_semantic_group.tsx
Labels: lgtm

#54187 fix(Avatar): do not apply font size token
  components/avatar/demo/component-token.tsx
  components/avatar/style/index.ts
Labels: skip-verify-files, lgtm

#54392 docs: add tips of icons and static methods of message, Modal and notification
  components/icon/index.en-US.md
  components/icon/index.zh-CN.md
  components/message/demo/info.md
  components/modal/demo/static-info.md
  components/notification/demo/basic.md
Labels: skip-verify-files, lgtm

#54390 fix[Mentions]: fix overlap of clear and feedback icons in Mentions
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/form/__tests__/__snapshots__/demo.test.tsx.snap
  components/form/demo/custom-feedback-icons.tsx
  components/input/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/mentions/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/mentions/__tests__/__snapshots__/demo.test.tsx.snap
  components/mentions/style/index.ts
Labels: lgtm

#54424 chore: sync feature into next
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/anchor/index.en-US.md
  components/anchor/index.zh-CN.md
  components/avatar/demo/component-token.tsx
  components/avatar/style/index.ts
  components/date-picker/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/date-picker/__tests__/__snapshots__/demo.test.tsx.snap
  components/date-picker/demo/allow-empty.tsx
  components/date-picker/demo/disabled-date.tsx
  components/form/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/form/__tests__/__snapshots__/demo.test.tsx.snap
  components/form/demo/custom-feedback-icons.tsx
  components/icon/index.en-US.md
  components/icon/index.zh-CN.md
  components/input-number/style/index.ts
  components/input/style/variants.ts
  components/mentions/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/mentions/__tests__/__snapshots__/demo.test.tsx.snap
  components/mentions/style/index.ts
  components/message/demo/info.md
  components/modal/demo/static-info.md
  components/notification/demo/basic.md
  package.json
Labels: BranchAutoMerge

#54425 chore: code style optimization
  components/_util/hooks/useClosable.tsx
Labels: lgtm

#54427 docs: auto prefixer
  docs/react/compatible-style.en-US.md
  docs/react/compatible-style.zh-CN.md
  package.json
Labels: lgtm

#54431 chore: improve FloatButton
  components/float-button/FloatButtonGroup.tsx
  components/float-button/__tests__/semantic.test.tsx
Labels: lgtm

#54417 docs: Add more semantic desc of the content for llms
  .dumi/theme/common/SelectSemanticTemplate.tsx
  components/alert/demo/_semantic.tsx
  components/anchor/demo/_semantic.tsx
  components/badge/demo/_semantic.tsx
  components/badge/demo/_semantic_ribbon.tsx
  components/breadcrumb/demo/_semantic.tsx
  components/button/demo/_semantic.tsx
  components/calendar/demo/_semantic.tsx
  components/card/demo/_semantic.tsx
  components/checkbox/demo/_semantic.tsx
  components/collapse/demo/_semantic.tsx
  components/color-picker/demo/_semantic.tsx
  components/date-picker/demo/_semantic.tsx
  components/descriptions/demo/_semantic.tsx
  components/divider/demo/_semantic.tsx
  components/drawer/demo/_semantic.tsx
  components/dropdown/demo/_semantic.tsx
  components/empty/demo/_semantic.tsx
  components/float-button/demo/_semantic.tsx
  components/float-button/demo/_semantic_group.tsx
  components/form/demo/_semantic.tsx
  components/image/demo/_semantic.tsx
  components/input-number/demo/_semantic.tsx
  components/input/demo/_semantic_input.tsx
  components/input/demo/_semantic_otp.tsx
  components/input/demo/_semantic_textarea.tsx
  components/masonry/demo/_semantic.tsx
  components/mentions/demo/_semantic.tsx
  components/menu/demo/_semantic.tsx
  components/message/demo/_semantic.tsx
  components/modal/demo/_semantic.tsx
  components/notification/demo/_semantic.tsx
  components/pagination/demo/_semantic.tsx
  components/popconfirm/demo/_semantic.tsx
  components/popover/demo/_semantic.tsx
  components/progress/demo/_semantic.tsx
  components/qr-code/demo/_semantic.tsx
  components/radio/demo/_semantic.tsx
  components/result/demo/_semantic.tsx
  components/segmented/demo/_semantic.tsx
  components/skeleton/demo/_semantic.tsx
  components/slider/demo/_semantic.tsx
  components/space/demo/_semantic.tsx
  components/spin/demo/_semantic.tsx
  components/splitter/demo/_semantic.tsx
  components/statistic/demo/_semantic.tsx
  components/steps/demo/_semantic.tsx
  components/switch/demo/_semantic.tsx
  components/table/demo/_semantic.tsx
  components/tabs/demo/_semantic.tsx
  components/tag/demo/_semantic.tsx
  components/tag/demo/_semantic_group.tsx
  components/timeline/demo/_semantic.tsx
  components/tooltip/demo/_semantic.tsx
  components/tour/demo/_semantic.tsx
  components/transfer/demo/_semantic.tsx
  components/tree-select/demo/_semantic.tsx
  components/tree/demo/_semantic.tsx
  components/upload/demo/_semantic.tsx
Labels: lgtm

#54334 feat: zeroRuntime
  .antd-tools.config.js
  .gitignore
  components/badge/demo/_semantic_ribbon.tsx
  components/calendar/demo/_semantic.tsx
  components/collapse/demo/_semantic.tsx
  components/config-provider/context.ts
  components/date-picker/demo/_semantic.tsx
  components/descriptions/demo/_semantic.tsx
  components/drawer/demo/_semantic.tsx
  components/float-button/demo/_semantic_group.tsx
  components/image/demo/_semantic.tsx
  components/input-number/demo/_semantic.tsx
  components/input/demo/_semantic_textarea.tsx
  components/mentions/demo/_semantic.tsx
  components/qr-code/demo/_semantic.tsx
  components/segmented/demo/_semantic.tsx
  components/slider/demo/_semantic.tsx
  components/spin/demo/_semantic.tsx
  components/splitter/demo/_semantic.tsx
  components/statistic/demo/_semantic.tsx
  components/theme/context.ts
  components/theme/useToken.ts
  components/theme/util/genStyleUtils.ts
  components/transfer/demo/_semantic.tsx
  components/tree-select/demo/_semantic.tsx
  docs/react/customize-theme.en-US.md
  docs/react/customize-theme.zh-CN.md
  package.json
  scripts/build-style.tsx
  scripts/generate-cssinjs.ts
  scripts/tsconfig.json
  tests/dekko/dist.test.ts
Labels: lgtm

#54443 perf: delete unnecessary calculations
  components/_util/placements.ts
Labels: lgtm

#54451 site: fix color2Rgba result
  .dumi/theme/builtins/TokenCompare/index.tsx
Labels: skip-verify-files, lgtm

#54455 perf<Result>: Reduce the size of the status icons
  components/result/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/result/__tests__/__snapshots__/demo.test.ts.snap
  components/result/noFound.tsx
  components/result/serverError.tsx
  components/result/unauthorized.tsx
Labels: skip-verify-files, lgtm

#54460 docs: fix icon align issue in right header
  .dumi/theme/slots/Header/SwitchBtn.tsx
  .dumi/theme/slots/Header/index.tsx
Labels: skip-verify-files, lgtm

#54448 chore: [v6] Remove copy-to-clipboard
  .dumi/theme/builtins/ComponentMeta/index.tsx
  .dumi/theme/builtins/IconSearch/CopyableIcon.tsx
  .dumi/theme/common/Color/ColorBlock.tsx
  .dumi/theme/common/Color/Palette.tsx
  package.json
Labels: lgtm

#54462 feat(tabs): Support middle mouse button to close in editable mode
  package.json
Labels: lgtm

#54471 docs: enable zeroRuntime in prod
  .dumi/theme/common/Loading.tsx
  .dumi/theme/layouts/GlobalLayout.tsx
  .dumi/theme/plugin.ts
Labels: lgtm

#54466 chore: merge feature into next
  .dumi/theme/builtins/FlexWithImagePreview/index.tsx
  .dumi/theme/builtins/ImagePreview/index.tsx
  .dumi/theme/builtins/TokenCompare/index.tsx
  .dumi/theme/common/ThemeSwitch/index.tsx
  .dumi/theme/common/styles/Markdown.tsx
  .dumi/theme/locales/en-US.json
  .dumi/theme/locales/zh-CN.json
  .dumi/theme/plugin.ts
  .dumi/theme/slots/Content/index.tsx
  .dumi/theme/slots/Footer/index.tsx
  .dumi/theme/slots/Header/SwitchBtn.tsx
  .dumi/theme/slots/Header/index.tsx
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/_util/hooks/useClosable.tsx
  components/_util/placements.ts
  components/result/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/result/__tests__/__snapshots__/demo.test.ts.snap
  components/result/noFound.tsx
  components/result/serverError.tsx
  components/result/unauthorized.tsx
  docs/spec/lightweight.en-US.md
  docs/spec/lightweight.zh-CN.md
  docs/spec/stay.en-US.md
  docs/spec/stay.zh-CN.md
Labels: BranchAutoMerge

#54474 feat(Upload): support customRequest global config
  components/config-provider/context.ts
  components/config-provider/index.en-US.md
  components/config-provider/index.tsx
  components/config-provider/index.zh-CN.md
  components/upload/Upload.tsx
  components/upload/__tests__/upload.test.tsx
Labels: lgtm

#54398 docs: support hide layout param
  .dumi/theme/layouts/DocLayout/index.tsx
  .dumi/theme/layouts/SidebarLayout/index.tsx
Labels: skip-verify-files, lgtm

#54485 chore: bump rc-trigger version
  package.json
Labels: lgtm

#54513 test: rm useless test
  components/input/__tests__/textarea.test.tsx
Labels: lgtm

#54510 docs: update changelog info
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: skip-verify-files, lgtm

#54518 chore: merge feature into next
  .dumi/pages/index/components/Theme/index.tsx
  .dumi/theme/builtins/TokenCompare/index.tsx
  .dumi/theme/common/Color/ColorPalettes.tsx
  .dumi/theme/common/Color/Palette.tsx
  .dumi/theme/common/SemanticPreview.tsx
  .dumi/theme/common/styles/NProgress.tsx
  .dumi/theme/common/styles/Responsive.tsx
  .dumi/theme/layouts/DocLayout/index.tsx
  .dumi/theme/layouts/SidebarLayout/index.tsx
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/button/__tests__/index.test.tsx
  components/button/button.tsx
  components/card/Card.tsx
  components/card/__tests__/__snapshots__/index.test.tsx.snap
  components/card/__tests__/index.test.tsx
  components/config-provider/context.ts
  components/config-provider/index.en-US.md
  components/config-provider/index.tsx
  components/config-provider/index.zh-CN.md
  components/drawer/__tests__/__snapshots__/demo-extend.test.tsx.snap
  components/drawer/demo/classNames.tsx
  components/input/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/input/__tests__/__snapshots__/demo.test.tsx.snap
  components/input/__tests__/textarea.test.tsx
  components/input/demo/group.md
  components/input/demo/group.tsx
  components/layout/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/layout/__tests__/__snapshots__/demo.test.ts.snap
  components/layout/demo/component-token.tsx
  components/layout/demo/top-side-2.tsx
  components/modal/demo/classNames.tsx
  components/space/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/space/__tests__/__snapshots__/demo.test.tsx.snap
  components/space/demo/compact.tsx
  components/table/demo/drag-column-sorting.tsx
  components/tabs/TabPane.ts
  components/tabs/index.tsx
  components/upload/Upload.tsx
  components/upload/__tests__/upload.test.tsx
  components/watermark/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/watermark/__tests__/__snapshots__/demo.test.ts.snap
  components/watermark/demo/custom.tsx
  docs/spec/introduce.en-US.md
  docs/spec/introduce.zh-CN.md
  package.json
Labels: BranchAutoMerge

#54524 chore: merge feature into next
  .dumi/theme/common/Color/ColorPalettes.tsx
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/locale/tr_TR.ts
  components/message/index.tsx
  components/notification/index.tsx
Labels: BranchAutoMerge

#54522 docs: add Localization log
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: skip-verify-files, lgtm

#54540 type: adding missed generics with ShowUploadListInterface
  components/upload/interface.ts
Labels: lgtm

#54541 docs: table pagination position
  components/table/index.en-US.md
  components/table/index.zh-CN.md
Labels: skip-verify-files, lgtm

#54549 perf: use strict conditions
  components/_util/__tests__/util.test.tsx
  components/_util/throttleByAnimationFrame.ts
Labels: lgtm

#54449 fix: typography-demo-ellipsis-controlled shows error when drag slider faster
  components/typography/Base/CopyBtn.tsx
  components/typography/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/typography/__tests__/__snapshots__/demo.test.tsx.snap
Labels: skip-verify-files, lgtm
