Repository ant-design/ant-design, pull requests merged in 2025-06, with the labels that each got.

#53972 feat: Upload progress prop enhancement
  components/upload/UploadList/ListItem.tsx
Labels: lgtm

#53974 doc: update image demo
  components/image/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/image/__tests__/__snapshots__/demo.test.ts.snap
  components/image/demo/placeholder.tsx
Labels: lgtm

#53985 ci: update assignees for dependency upgrade PR
  .github/workflows/upgrade-deps.yml
Labels: lgtm

#53983 refactor(space): support separator and deprecate split
  components/space/Item.tsx
  components/space/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/space/__tests__/__snapshots__/demo.test.tsx.snap
  components/space/__tests__/__snapshots__/index.test.tsx.snap
  components/space/__tests__/index.test.tsx
  components/space/demo/_semantic.tsx
  components/space/demo/separator.md
  components/space/demo/separator.tsx
  components/space/index.en-US.md
  components/space/index.tsx
  components/space/index.zh-CN.md
Labels: lgtm

#53994 fix: Modal hooks with render function
  components/modal/__tests__/hook.test.tsx
  components/modal/confirm.tsx
  components/modal/useModal/HookModal.tsx
  components/modal/useModal/index.tsx
Labels: lgtm

#53993 ci: skip verify-files-modify for long-time contributors
  .github/workflows/verify-files-modify.yml
Labels: lgtm

#53902 fix: motion configuration does not work properly
  components/config-provider/MotionWrapper.tsx
  components/config-provider/__tests__/index.test.tsx
  components/config-provider/index.tsx
  components/modal/__tests__/confirm.test.tsx
  components/modal/__tests__/hook.test.tsx
  tests/utils.tsx
Labels: skip-verify-files, lgtm

#54010 chore: sync master into feature
  .github/workflows/preview-deploy.yml
  .github/workflows/upgrade-deps.yml
  .github/workflows/verify-files-modify.yml
  .github/workflows/visual-regression-diff-finish.yml
  .github/workflows/visual-regression-persist-finish.yml
  components/config-provider/MotionWrapper.tsx
  components/config-provider/__tests__/index.test.tsx
  components/config-provider/index.tsx
  components/image/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/image/__tests__/__snapshots__/demo.test.ts.snap
  components/image/demo/placeholder.tsx
  components/modal/__tests__/confirm.test.tsx
  components/modal/__tests__/hook.test.tsx
  components/modal/confirm.tsx
  components/modal/useModal/HookModal.tsx
  components/modal/useModal/index.tsx
  mako.config.json
  package.json
  scripts/check-site.ts
  scripts/tsconfig.json
  tests/utils.tsx
Labels: BranchAutoMerge

#54011 docs: ensure lastThemeKey is updated on theme switch
  .dumi/theme/common/ThemeSwitch/index.tsx
Labels: skip-verify-files, lgtm

#54021 chore: sync master into feature
  .dumi/theme/common/ThemeSwitch/index.tsx
  components/_util/warning.ts
  components/config-provider/__tests__/motion.test.tsx
  components/message/index.tsx
  components/notification/index.tsx
  components/version/index.tsx
  package.json
Labels: BranchAutoMerge

#54024 chore: sync feature into next
  .dumi/theme/common/ThemeSwitch/index.tsx
  components/_util/warning.ts
  components/config-provider/__tests__/motion.test.tsx
  components/message/index.tsx
  components/notification/index.tsx
  components/version/index.tsx
  package.json
Labels: BranchAutoMerge

#54030 Feature merge to master
  components/table/__tests__/__snapshots__/demo.test.ts.snap
  components/table/demo/expand-sticky.md
  components/table/demo/expand-sticky.tsx
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  components/upload/UploadList/ListItem.tsx
  package.json
Labels: BranchAutoMerge, skip-verify-files, lgtm

#54027 docs: Update changelog for version 5.26.0
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: skip-verify-files, lgtm

#53262 feat(Dropdown.Button): deprecated in favor of Space.Compact + Dropdown + Button
  components/button/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/button/__tests__/__snapshots__/demo.test.ts.snap
  components/button/demo/multiple.md
  components/button/demo/multiple.tsx
  components/dropdown/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/dropdown/__tests__/__snapshots__/demo.test.tsx.snap
  components/dropdown/demo/dropdown-button.tsx
  components/dropdown/demo/icon-debug.tsx
  components/dropdown/demo/loading.md
  components/dropdown/demo/loading.tsx
  components/dropdown/dropdown-button.tsx
  components/dropdown/index.en-US.md
  components/dropdown/index.tsx
  components/dropdown/index.zh-CN.md
  scripts/__snapshots__/check-site.ts.snap
Labels: skip-verify-files, lgtm

#54038 chore: merge master into feature
  .dumi/scripts/mirror-notify.js
  .dumi/theme/builtins/ComponentOverview/index.tsx
  .dumi/theme/builtins/Previewer/Actions.tsx
  .dumi/theme/builtins/Previewer/CodePreviewer.tsx
  .dumi/theme/builtins/Previewer/DesignPreviewer.tsx
  .dumi/theme/builtins/Previewer/Previewer.tsx
  .dumi/theme/builtins/Previewer/index.tsx
  .dumi/theme/slots/Content/Contributors.tsx
  .dumi/theme/slots/Footer/index.tsx
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: BranchAutoMerge, lgtm

#53793 chore: [v6] rm Dropdown.Button
  .dumi/pages/index/components/PreviewBanner/ComponentsBlock.tsx
  components/dropdown/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/dropdown/__tests__/__snapshots__/demo.test.tsx.snap
  components/dropdown/__tests__/dropdown-button.test.tsx
  components/dropdown/__tests__/image.test.ts
  components/dropdown/demo/icon-debug.tsx
  components/dropdown/dropdown-button.tsx
  components/space/__tests__/__snapshots__/demo-extend.test.ts.snap
  package.json
Labels: lgtm

#54040 docs: fix mirror notify click event tracking
  .dumi/scripts/mirror-notify.js
Labels: lgtm

#54062 chore: lock brace-expansion: 2.0.1
  package.json
Labels: skip-verify-files, lgtm

#54065 chore: sync master into feature
  .dumi/remarkAnchor.ts
  .dumi/scripts/mirror-notify.js
  components/button/button.tsx
  components/button/demo/loading.tsx
  components/calendar/__tests__/index.test.tsx
  components/descriptions/__tests__/index.test.tsx
  components/modal/__tests__/confirm.test.tsx
  components/table/__tests__/Table.rowSelection.test.tsx
  docs/spec/colors.en-US.md
  docs/spec/colors.zh-CN.md
  package.json
Labels: BranchAutoMerge

#54066 chore: sync feature into next
  .dumi/remarkAnchor.ts
  .dumi/scripts/mirror-notify.js
  components/button/button.tsx
  components/button/demo/loading.tsx
  components/calendar/__tests__/index.test.tsx
  components/descriptions/__tests__/index.test.tsx
  components/modal/__tests__/confirm.test.tsx
  components/table/__tests__/Table.rowSelection.test.tsx
  docs/spec/colors.en-US.md
  docs/spec/colors.zh-CN.md
  package.json
Labels: BranchAutoMerge

#54057 doc: Optimize external selection panel demo
  components/date-picker/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/date-picker/__tests__/__snapshots__/demo.test.tsx.snap
  components/date-picker/demo/external-panel.tsx
Labels: lgtm

#54072 feat: Timeline support `titleSpan`
  components/steps/style/icon.ts
  components/steps/style/index.ts
  components/steps/style/vertical.ts
  components/timeline/Timeline.tsx
  components/timeline/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/timeline/__tests__/__snapshots__/demo.test.ts.snap
  components/timeline/demo/label.md
  components/timeline/demo/title-span.md
  components/timeline/demo/title-span.tsx
  components/timeline/demo/title.md
  components/timeline/demo/title.tsx
  components/timeline/index.en-US.md
  components/timeline/index.zh-CN.md
  components/timeline/style/horizontal.ts
  components/timeline/style/index.ts
Labels: lgtm

#54077 demo: add optionRender usage for cascader
  components/cascader/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/cascader/demo/custom-render.tsx
Labels: lgtm

#54101 docs: Update CHANGE LOG
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: skip-verify-files, lgtm

#54109 chore: upgrade tsx from `~4.20.3` to `^4.20.3`
  package.json
Labels: skip-verify-files, lgtm

#54126 chore: remove unused devDeps
  package.json
Labels: skip-verify-files, lgtm

#54125 chore: replace icons with svg component
  .dumi/theme/builtins/Previewer/Actions.tsx
  .dumi/theme/builtins/Previewer/CodeBlockButton.tsx
  .dumi/theme/builtins/Previewer/CodePreviewer.tsx
  .dumi/theme/common/Loading.tsx
  .dumi/theme/common/styles/Demo.tsx
  .dumi/theme/icons/ExpandIcon.tsx
  .dumi/theme/icons/HituIcon.tsx
  .dumi/theme/icons/JuejinIcon.tsx
  .dumi/theme/icons/RiddleIcon.tsx
  .dumi/theme/slots/Content/ColumnCard.tsx
  .dumi/theme/slots/Content/JuejinLogo.tsx
Labels: skip-verify-files, lgtm

#54132 chore: sync pinSemantic
  .dumi/theme/common/Marker.tsx
  .dumi/theme/common/Markers.tsx
  .dumi/theme/common/SemanticPreview.tsx
Labels: skip-verify-files, lgtm

#54104 feat: Transfer actions prop supports ReactNode array
  .cursor/rules/project.mdc
  components/transfer/Actions.tsx
  components/transfer/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/transfer/__tests__/__snapshots__/demo.test.ts.snap
  components/transfer/__tests__/actions.test.tsx
  components/transfer/__tests__/index.test.tsx
  components/transfer/demo/actions.md
  components/transfer/demo/actions.tsx
  components/transfer/index.en-US.md
  components/transfer/index.tsx
  components/transfer/index.zh-CN.md
Labels: skip-verify-files, lgtm

#54155 fix: update rc-virtual-list and fix scrollbar color in dark theme
  components/list/style/index.ts
  components/table/style/index.ts
  components/tree/style/index.ts
  package.json
Labels: skip-verify-files, lgtm

#54157 chore(deps-dev): add @biomejs/cli-darwin-arm64
  package.json
Labels: lgtm

#54161 chore: lock @biomejs/biome version
  .dumi/rehypeAntd.ts
  .dumi/rehypeChangelog.ts
  components/date-picker/demo/external-panel.tsx
  package.json
Labels: skip-verify-files, lgtm

#54166 chore: rm biomejs/cli darwin arm64
  package.json
Labels: lgtm

#54162 fix(input): correct classNames and styles TypeScript definitions
  components/input/Input.tsx
Labels: lgtm

#54174 chore: unlock @biomejs/biome version
  package.json
Labels: skip-verify-files, lgtm

#54178 docs: update calendar demo with Flex and simplify options
  components/calendar/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/calendar/__tests__/__snapshots__/demo.test.ts.snap
  components/calendar/demo/customize-header.tsx
Labels: lgtm

#53668 style: fix incorrect DatePicker small token
  components/date-picker/style/index.ts
Labels: skip-verify-files, lgtm

#54190 Docs tree en
  components/tree/index.en-US.md
Labels: skip-verify-files, lgtm

#54193 chore(site): supports switching themes following the system
  .dumi/theme/common/ThemeSwitch/index.tsx
  .dumi/theme/layouts/GlobalLayout.tsx
Labels: skip-verify-files, lgtm

#54194 chore: sync feature into next
  .dumi/theme/SiteThemeProvider.tsx
  .dumi/theme/common/styles/Markdown.tsx
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  README-zh_CN.md
  README.md
  components/badge/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/badge/__tests__/__snapshots__/demo.test.tsx.snap
  components/badge/__tests__/index.test.tsx
  components/badge/demo/mix.tsx
  components/badge/index.tsx
  components/calendar/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/calendar/__tests__/__snapshots__/demo.test.ts.snap
  components/calendar/demo/customize-header.tsx
  components/date-picker/style/index.ts
  components/menu/menu.tsx
  components/select/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/select/__tests__/__snapshots__/demo.test.tsx.snap
  components/select/demo/debug.tsx
  components/select/index.en-US.md
  components/select/index.zh-CN.md
  components/select/style/multiple.ts
  components/splitter/SplitBar.tsx
  components/splitter/Splitter.tsx
  components/splitter/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/splitter/__tests__/__snapshots__/demo.test.ts.snap
  components/splitter/__tests__/index.test.tsx
  components/splitter/demo/collapsibleIcon.md
  components/splitter/demo/collapsibleIcon.tsx
  components/splitter/hooks/useItems.ts
  components/splitter/hooks/useResizable.ts
  components/splitter/index.en-US.md
  components/splitter/index.zh-CN.md
  components/splitter/interface.ts
  components/splitter/style/index.ts
  components/tree/index.en-US.md
  package.json
Labels: BranchAutoMerge

#54183 fix[#54146]: DirectoryTree drop indicator overflow bug
  components/tree/style/directory.ts
Labels: skip-verify-files, lgtm

#54212 enhance: form useWatch perf
  package.json
Labels: lgtm

#54222 site: update haitu i18n
  .dumi/theme/builtins/Previewer/Actions.tsx
  .dumi/theme/builtins/Previewer/CodeBlockButton.tsx
  .dumi/theme/builtins/Previewer/CodePreviewer.tsx
  .dumi/theme/locales/en-US.json
  .dumi/theme/locales/zh-CN.json
  .dumi/theme/slots/Content/Contributors.tsx
Labels: skip-verify-files, lgtm

#54219 site: update site hard code to i18n
  .dumi/pages/index/components/util.ts
  .dumi/remarkAnchor.ts
  .dumi/theme/builtins/IconSearch/CopyableIcon.tsx
  .dumi/theme/builtins/ImagePreview/index.tsx
  .dumi/theme/builtins/Previewer/CodeBlockButton.tsx
  .dumi/theme/builtins/Previewer/DesignPreviewer.tsx
  .dumi/theme/builtins/RefinedChangelog/index.tsx
  .dumi/theme/common/BehaviorMap/BehaviorMap.tsx
  .dumi/theme/common/BehaviorMap/index.tsx
  .dumi/theme/common/BezierVisualizer/index.tsx
  .dumi/theme/common/JSONEditor/index.tsx
  .dumi/theme/common/Marker.tsx
  .dumi/theme/common/Markers.tsx
  .dumi/theme/common/SemanticPreview.tsx
  components/breadcrumb/index.$tab-design.zh-CN.md
  package.json
Labels: skip-verify-files, lgtm

#54223 chore: sync master into feature
  .dumi/pages/index/components/util.ts
  .dumi/remarkAnchor.ts
  .dumi/theme/builtins/IconSearch/CopyableIcon.tsx
  .dumi/theme/builtins/ImagePreview/index.tsx
  .dumi/theme/builtins/Previewer/Actions.tsx
  .dumi/theme/builtins/Previewer/CodeBlockButton.tsx
  .dumi/theme/builtins/Previewer/CodePreviewer.tsx
  .dumi/theme/builtins/Previewer/DesignPreviewer.tsx
  .dumi/theme/builtins/RefinedChangelog/index.tsx
  .dumi/theme/common/BehaviorMap/BehaviorMap.tsx
  .dumi/theme/common/BehaviorMap/index.tsx
  .dumi/theme/common/BezierVisualizer/index.tsx
  .dumi/theme/common/JSONEditor/index.tsx
  .dumi/theme/common/Marker.tsx
  .dumi/theme/common/Markers.tsx
  .dumi/theme/common/SemanticPreview.tsx
  .dumi/theme/common/ThemeSwitch/index.tsx
  .dumi/theme/layouts/GlobalLayout.tsx
  .dumi/theme/locales/en-US.json
  .dumi/theme/locales/zh-CN.json
  .dumi/theme/slots/Content/Contributors.tsx
  components/breadcrumb/index.$tab-design.zh-CN.md
  components/float-button/FloatButton.tsx
  components/tree/style/directory.ts
  components/tree/style/index.ts
  components/typography/style/mixins.ts
  package.json
Labels: BranchAutoMerge

#54224 chore: rm css-select
  package.json
Labels: skip-verify-files, lgtm

#54225 chore: sync feature into next
  .dumi/pages/index/components/util.ts
  .dumi/remarkAnchor.ts
  .dumi/theme/builtins/IconSearch/CopyableIcon.tsx
  .dumi/theme/builtins/ImagePreview/index.tsx
  .dumi/theme/builtins/Previewer/Actions.tsx
  .dumi/theme/builtins/Previewer/CodeBlockButton.tsx
  .dumi/theme/builtins/Previewer/CodePreviewer.tsx
  .dumi/theme/builtins/Previewer/DesignPreviewer.tsx
  .dumi/theme/builtins/RefinedChangelog/index.tsx
  .dumi/theme/common/BehaviorMap/BehaviorMap.tsx
  .dumi/theme/common/BehaviorMap/index.tsx
  .dumi/theme/common/BezierVisualizer/index.tsx
  .dumi/theme/common/JSONEditor/index.tsx
  .dumi/theme/common/Marker.tsx
  .dumi/theme/common/Markers.tsx
  .dumi/theme/common/SemanticPreview.tsx
  .dumi/theme/common/ThemeSwitch/index.tsx
  .dumi/theme/layouts/GlobalLayout.tsx
  .dumi/theme/locales/en-US.json
  .dumi/theme/locales/zh-CN.json
  .dumi/theme/slots/Content/Contributors.tsx
  components/breadcrumb/index.$tab-design.zh-CN.md
  components/float-button/FloatButton.tsx
  components/tree/style/directory.ts
  components/tree/style/index.ts
  components/typography/style/mixins.ts
  package.json
Labels: BranchAutoMerge

#54229 type: update React.isValidElement type to generics
  components/_util/hooks/useClosable.tsx
  components/badge/index.tsx
  components/form/FormItem/index.tsx
  components/menu/MenuItem.tsx
  components/menu/SubMenu.tsx
  components/menu/menu.tsx
  components/popover/index.tsx
  components/spin/Indicator/index.tsx
  components/splitter/hooks/useItems.ts
  components/steps/useLegacyItems.ts
  components/table/__tests__/Table.filter.test.tsx
  components/tabs/hooks/useLegacyItems.ts
  components/tour/PurePanel.tsx
  components/transfer/list.tsx
  components/tree/utils/iconUtil.tsx
  components/upload/UploadList/index.tsx
Labels: lgtm

#54233 docs(InputNumber): minor grammar fixes in API
  components/input-number/index.en-US.md
Labels: skip-verify-files, lgtm

#54236 chore: add `$schema` for biome
  biome.json
Labels: lgtm

#54238 chore: bump antd-tools
  package.json
Labels: lgtm
