Repository ant-design/ant-design, pull requests merged in 2025-10, with the labels that each got.

#55210 chore: Unified variable naming style
  components/alert/Alert.tsx
  components/calendar/generateCalendar.tsx
  components/card/Card.tsx
  components/collapse/Collapse.tsx
  components/drawer/index.tsx
  components/image/index.tsx
  components/mentions/index.tsx
  components/modal/Modal.tsx
  components/popconfirm/index.tsx
  components/qr-code/index.tsx
  components/radio/radio.tsx
  components/result/index.tsx
  components/segmented/index.tsx
  components/skeleton/Avatar.tsx
  components/skeleton/Button.tsx
  components/skeleton/Input.tsx
  components/skeleton/Node.tsx
  components/skeleton/Skeleton.tsx
  components/slider/index.tsx
  components/spin/index.tsx
  components/statistic/Statistic.tsx
  components/switch/index.tsx
  components/tour/index.tsx
  components/tree/Tree.tsx
  components/upload/Upload.tsx
Labels: lgtm

#55211 chore: merge master into feature
  .dumi/hooks/useFetch/cache.ts
  .dumi/hooks/useFetch/index.ts
  .dumi/pages/index/components/BannerRecommends.tsx
  .dumi/pages/index/components/util.ts
  .dumi/theme/builtins/ResourceArticles/index.tsx
  .dumi/theme/common/ComponentChangelog/ComponentChangelog.tsx
  package.json
Labels: BranchAutoMerge

#55075 fix(list): adjust bordered list overflow styling
  components/list/style/index.ts
Labels: lgtm

#55217 site: compatible error & isLoading for site data
  .dumi/pages/index/components/BannerRecommends.tsx
  .dumi/pages/index/components/util.ts
  .dumi/theme/builtins/ResourceArticles/index.tsx
Labels: skip-verify-files, lgtm

#55227 chore: merge master into feature
  .dumi/pages/index/components/BannerRecommends.tsx
  .dumi/pages/index/components/util.ts
  .dumi/theme/builtins/ResourceArticles/index.tsx
  .github/workflows/site-deploy.yml
  components/list/style/index.ts
  eslint.config.mjs
  package.json
Labels: BranchAutoMerge

#55223 fix(site): fix prettier import path issue
  .dumi/theme/utils/tsToJs.ts
Labels: skip-verify-files, lgtm

#55224 fix(site): change button to div for fix hydration error
  .dumi/theme/common/CodePreview.tsx
  components/typography/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/typography/__tests__/__snapshots__/demo.test.tsx.snap
  components/typography/demo/ellipsis-debug.tsx
Labels: skip-verify-files, lgtm

#55235 chore: merge master into feature
  .dumi/theme/common/CodePreview.tsx
  .dumi/theme/utils/tsToJs.ts
  .github/workflows/site-deploy.yml
  components/flex/index.tsx
  components/typography/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/typography/__tests__/__snapshots__/demo.test.tsx.snap
  components/typography/demo/ellipsis-debug.tsx
Labels: BranchAutoMerge

#55236 chore: merge feature into next
  .dumi/theme/common/CodePreview.tsx
  .dumi/theme/utils/tsToJs.ts
  .github/workflows/site-deploy.yml
  components/flex/index.tsx
  components/typography/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/typography/__tests__/__snapshots__/demo.test.tsx.snap
  components/typography/demo/ellipsis-debug.tsx
Labels: BranchAutoMerge

#55156 fix: float button & float button group disabled prop type
  components/float-button/interface.ts
Labels: lgtm
