Repository ant-design/ant-design, pull requests merged in 2025-05, with the labels that each got.

#53722 type: remove ts-ignore
  components/breadcrumb/__tests__/Breadcrumb.test.tsx
Labels: lgtm

#53721 chore: code style optimization
  components/checkbox/Group.tsx
Labels: lgtm

#53701 perf: remove direct useState set calls in useEffect for color-picker
  components/color-picker/components/ColorAlphaInput.tsx
  components/color-picker/components/ColorHexInput.tsx
  components/color-picker/components/ColorHsbInput.tsx
  components/color-picker/components/ColorRgbInput.tsx
  components/color-picker/components/ColorSteppers.tsx
Labels: lgtm

#53687 fix<Anchor>: Click the anchor point to refresh the page.
  components/anchor/AnchorLink.tsx
  components/anchor/__tests__/Anchor.test.tsx
Labels: skip-verify-files, lgtm

#53723 fix: fix extra span element when children is null
  components/checkbox/Checkbox.tsx
Labels: lgtm

#53720 feat: Add cursor rules for locale
  .cursor/rules/locale.mdc
Labels: lgtm

#53724 chore: lint config update
  eslint.config.mjs
Labels: skip-verify-files, lgtm

#53688 docs: add external-panel demo
  components/date-picker/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/date-picker/__tests__/__snapshots__/demo.test.tsx.snap
  components/date-picker/demo/external-panel.md
  components/date-picker/demo/external-panel.tsx
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
Labels: lgtm

#53685 ♻️ refactor: try to merge similar function methods to reduce the bundle size.
  components/_util/extendsObject.ts
  components/_util/hooks/useClosable.tsx
  components/list/index.tsx
  components/table/hooks/useFilter/FilterDropdown.tsx
  components/table/hooks/usePagination.ts
Labels: lgtm

#53728 docs: move Tabs to Navigation group
  components/tabs/index.en-US.md
  components/tabs/index.zh-CN.md
Labels: lgtm

#53684 feat(Modal): config global okButtonProps & cancelButtonProps
  components/config-provider/context.ts
  components/modal/ConfirmDialog.tsx
  components/modal/Modal.tsx
  components/modal/__tests__/Modal.test.tsx
  components/modal/__tests__/confirm.test.tsx
Labels: lgtm

#53732 docs: updates of documentation
  docs/react/recommendation.en-US.md
  docs/react/recommendation.zh-CN.md
  docs/react/use-with-farm.en-US.md
  docs/react/use-with-farm.zh-CN.md
  docs/react/use-with-refine.en-US.md
  docs/react/use-with-refine.zh-CN.md
  docs/react/use-with-rsbuild.en-US.md
  docs/react/use-with-rsbuild.zh-CN.md
Labels: skip-verify-files, lgtm

#53731 test: fix ⛔️ Missing image: select-basic.mobile.css-var.png
  tests/shared/imageTest.tsx
Labels: skip-verify-files, lgtm

#53739 refactor: Unified destroyOnHidden API
  .cursor/rules/naming.mdc
  .dumi/theme/builtins/ComponentTokenTable/index.tsx
  .dumi/theme/common/ComponentChangelog/ComponentChangelog.tsx
  .dumi/theme/slots/Header/index.tsx
  components/avatar/AvatarGroup.tsx
  components/collapse/Collapse.tsx
  components/collapse/index.en-US.md
  components/collapse/index.zh-CN.md
  components/color-picker/ColorPicker.tsx
  components/color-picker/index.en-US.md
  components/color-picker/index.zh-CN.md
  components/color-picker/interface.ts
  components/drawer/__tests__/Drawer.test.tsx
  components/drawer/__tests__/DrawerEvent.test.tsx
  components/drawer/__tests__/__snapshots__/Drawer.test.tsx.snap
  components/drawer/demo/loading.tsx
  components/drawer/index.en-US.md
  components/drawer/index.tsx
  components/drawer/index.zh-CN.md
  components/dropdown/__tests__/dropdown-button.test.tsx
  components/dropdown/__tests__/index.test.tsx
  components/dropdown/dropdown-button.tsx
  components/dropdown/dropdown.tsx
  components/dropdown/index.en-US.md
  components/dropdown/index.zh-CN.md
  components/form/demo/form-in-modal.tsx
  components/image/demo/imageRender.tsx
  components/image/index.en-US.md
  components/image/index.tsx
  components/image/index.zh-CN.md
  components/modal/Modal.tsx
  components/modal/demo/nested.tsx
  components/modal/index.en-US.md
  components/modal/index.zh-CN.md
  components/modal/interface.ts
  components/tabs/index.en-US.md
  components/tabs/index.tsx
  components/tabs/index.zh-CN.md
  components/tooltip/__tests__/tooltip.test.tsx
  components/tooltip/demo/destroy-on-close.md
  components/tooltip/demo/destroy-on-close.tsx
  components/tooltip/index.tsx
  components/tooltip/shared/sharedProps.en-US.md
  components/tooltip/shared/sharedProps.zh-CN.md
  components/watermark/demo/portal.tsx
Labels: lgtm

#53734 chore: sync master into feature
  .cursor/rules/locale.mdc
  components/_util/extendsObject.ts
  components/_util/hooks/useClosable.tsx
  components/anchor/AnchorLink.tsx
  components/anchor/__tests__/Anchor.test.tsx
  components/breadcrumb/__tests__/Breadcrumb.test.tsx
  components/checkbox/Checkbox.tsx
  components/checkbox/Group.tsx
  components/color-picker/components/ColorAlphaInput.tsx
  components/color-picker/components/ColorHexInput.tsx
  components/color-picker/components/ColorHsbInput.tsx
  components/color-picker/components/ColorRgbInput.tsx
  components/color-picker/components/ColorSteppers.tsx
  components/date-picker/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/date-picker/__tests__/__snapshots__/demo.test.tsx.snap
  components/date-picker/demo/external-panel.md
  components/date-picker/demo/external-panel.tsx
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
  components/list/index.tsx
  components/table/hooks/useFilter/FilterDropdown.tsx
  components/table/hooks/usePagination.ts
  components/tabs/index.en-US.md
  components/tabs/index.zh-CN.md
  docs/react/recommendation.en-US.md
  docs/react/recommendation.zh-CN.md
  docs/react/use-with-farm.en-US.md
  docs/react/use-with-farm.zh-CN.md
  docs/react/use-with-refine.en-US.md
  docs/react/use-with-refine.zh-CN.md
  docs/react/use-with-rsbuild.en-US.md
  docs/react/use-with-rsbuild.zh-CN.md
  eslint.config.mjs
  tests/shared/imageTest.tsx
Labels: BranchAutoMerge

#53742 refactor: Unified destroyOnHidden API
  components/tabs/hooks/useLegacyItems.ts
  components/tabs/index.en-US.md
  components/tabs/index.tsx
  components/tabs/index.zh-CN.md
Labels: lgtm

#53744 chore: merge feature into master
  components/_util/hooks/useClosable.tsx
  components/anchor/AnchorLink.tsx
  components/date-picker/demo/external-panel.tsx
  components/tabs/hooks/useLegacyItems.ts
  components/tabs/index.en-US.md
  components/tabs/index.tsx
  components/tabs/index.zh-CN.md
Labels: BranchAutoMerge, skip-verify-files, lgtm

#53741 fix: Adds localization for QRCode and ColorPicker (cs_CZ)
  components/locale/cs_CZ.ts
Labels: lgtm

#53754 demo: replace the deprecated api of the Transfer
  components/transfer/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/transfer/demo/advanced.tsx
  components/transfer/demo/custom-item.tsx
Labels: lgtm

#53753 docs: improve semantic hightlight example for Skeleton
  components/skeleton/demo/_semantic_element.tsx
Labels: lgtm

#53718 feat(time-picker/date-picker): support popup semantic dom
  components/_util/hooks/useMergeSemantic/index.ts
  components/_util/hooks/useMergeSemantic/interface.ts
  components/button/index.zh-CN.md
  components/config-provider/context.ts
  components/config-provider/index.en-US.md
  components/config-provider/index.zh-CN.md
  components/date-picker/__tests__/DatePicker.test.tsx
  components/date-picker/__tests__/RangePicker.test.tsx
  components/date-picker/__tests__/semantic.test.tsx
  components/date-picker/demo/_semantic.tsx
  components/date-picker/generatePicker/generateRangePicker.tsx
  components/date-picker/generatePicker/generateSinglePicker.tsx
  components/date-picker/generatePicker/interface.ts
  components/date-picker/hooks/useMergedPickerSemantic.ts
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
  components/time-picker/demo/_semantic.tsx
  components/time-picker/demo/colored-popup.tsx
  components/time-picker/index.en-US.md
  components/time-picker/index.zh-CN.md
Labels: lgtm

#53755 chore: master merge feature
  components/_util/hooks/useMergeSemantic/index.ts
  components/_util/hooks/useMergeSemantic/interface.ts
  components/button/index.zh-CN.md
  components/config-provider/context.ts
  components/config-provider/index.en-US.md
  components/config-provider/index.zh-CN.md
  components/date-picker/__tests__/DatePicker.test.tsx
  components/date-picker/__tests__/RangePicker.test.tsx
  components/date-picker/__tests__/semantic.test.tsx
  components/date-picker/demo/_semantic.tsx
  components/date-picker/generatePicker/generateRangePicker.tsx
  components/date-picker/generatePicker/generateSinglePicker.tsx
  components/date-picker/generatePicker/interface.ts
  components/date-picker/hooks/useMergedPickerSemantic.ts
  components/date-picker/index.en-US.md
  components/date-picker/index.zh-CN.md
  components/time-picker/demo/_semantic.tsx
  components/time-picker/demo/colored-popup.tsx
  components/time-picker/index.en-US.md
  components/time-picker/index.zh-CN.md
Labels: BranchAutoMerge, skip-verify-files, lgtm

#53740 docs: changelog 5.25.0
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: skip-verify-files, lgtm

#53757 docs: update ChangeLog
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: skip-verify-files, lgtm

#53761 chore: merge master into feature
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/drawer/DrawerPanel.tsx
  components/locale/cs_CZ.ts
  components/statistic/utils.ts
  package.json
  scripts/check-repo.ts
Labels: BranchAutoMerge

#53762 chore: sync feature into next
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/drawer/DrawerPanel.tsx
  components/locale/cs_CZ.ts
  package.json
  scripts/check-repo.ts
Labels: BranchAutoMerge

#53766 docs: Use `onOpenChange` to fix `onPopupVisibleChange` in changedoc
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: skip-verify-files, lgtm

#53767 fix: Fix mask not hiding correctly in default mode
  BUG_VERSIONS.json
  components/splitter/Splitter.tsx
  components/splitter/__tests__/index.test.tsx
  components/splitter/__tests__/lazy.test.tsx
Labels: lgtm

#53765 refactor: Unified destroyOnHidden API
  components/card/__tests__/__snapshots__/index.test.tsx.snap
  components/tabs/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/tabs/__tests__/__snapshots__/demo.test.ts.snap
  components/tabs/hooks/useLegacyItems.ts
  components/tabs/index.tsx
  package.json
Labels: lgtm

#53771 Add Image preview translation to he locale
  components/locale/he_IL.ts
Labels: lgtm

#53773 refactor: update Masonry component types and improve useRefs hook
  components/masonry/Masonry.tsx
  components/masonry/demo/basic.tsx
  components/masonry/hooks/usePositions.ts
  components/masonry/hooks/useRefs.ts
Labels: lgtm

#53788 docs: changelog of 5.25.1
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: skip-verify-files, lgtm

#53785 feat(Message): Next message pause on hover
  components/message/__tests__/hooks.test.tsx
  components/message/index.en-US.md
  components/message/index.zh-CN.md
  components/message/interface.ts
  components/message/useMessage.tsx
  scripts/__snapshots__/check-site.ts.snap
Labels: skip-verify-files, lgtm

#53800 chore: merge master into feature
  BUG_VERSIONS.json
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/locale/he_IL.ts
  components/splitter/Splitter.tsx
  components/splitter/__tests__/index.test.tsx
  components/splitter/__tests__/lazy.test.tsx
  package.json
Labels: BranchAutoMerge

#53801 chore: merge feature into next
  BUG_VERSIONS.json
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/locale/he_IL.ts
  components/splitter/Splitter.tsx
  components/splitter/__tests__/index.test.tsx
  components/splitter/__tests__/lazy.test.tsx
  package.json
Labels: BranchAutoMerge

#53747 docs: Improve the document
  components/config-provider/index.en-US.md
  components/config-provider/index.zh-CN.md
Labels: skip-verify-files, lgtm

#53790 docs: fix codeblock load bug
  .dumi/theme/builtins/Previewer/CodeBlockButton.tsx
  .dumi/theme/builtins/Previewer/RiddleButton.tsx
  .dumi/theme/utils.ts
Labels: skip-verify-files, lgtm

#53817 test: fix image test
  components/statistic/Timer.tsx
  components/statistic/__tests__/__snapshots__/demo.test.ts.snap
  components/statistic/__tests__/image.test.ts
  components/statistic/__tests__/index.test.tsx
  tests/shared/imageTest.tsx
Labels: skip-verify-files, lgtm

#53808 chore: rm unsupported props inteface
  components/modal/interface.ts
Labels: lgtm

#53826 docs: fix the blank issue on the right side in mobile
  .dumi/theme/common/styles/Reset.tsx
Labels: lgtm

#53821 demo: fix warning for Breadcrumb
  components/layout/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/layout/demo/fixed.tsx
  components/layout/demo/side.tsx
  components/layout/demo/top-side.tsx
  components/layout/demo/top.tsx
Labels: lgtm

#53814 fix: revert changes to ColorHexInput to fix input issues
  components/color-picker/__tests__/components.test.tsx
  components/color-picker/components/ColorHexInput.tsx
Labels: lgtm

#53319 feat: Replace 'rc-notification' with '@rc-component/notification'
  components/_util/__tests__/hooks.test.tsx
  components/_util/hooks/useClosable.tsx
  components/message/PurePanel.tsx
  components/message/useMessage.tsx
  components/notification/PurePanel.tsx
  components/notification/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/notification/__tests__/__snapshots__/demo.test.ts.snap
  components/notification/__tests__/hooks.test.tsx
  components/notification/useNotification.tsx
  package.json
Labels: lgtm

#53837 chore: sync master into feature
  .dumi/theme/builtins/Previewer/CodeBlockButton.tsx
  .dumi/theme/builtins/Previewer/RiddleButton.tsx
  .dumi/theme/common/styles/Reset.tsx
  .dumi/theme/utils.ts
  components/auto-complete/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/auto-complete/__tests__/__snapshots__/demo.test.tsx.snap
  components/color-picker/__tests__/components.test.tsx
  components/color-picker/components/ColorHexInput.tsx
  components/config-provider/index.en-US.md
  components/config-provider/index.zh-CN.md
  components/input/Search.tsx
  components/input/__tests__/Search.test.tsx
  components/input/__tests__/__snapshots__/Search.test.tsx.snap
  components/input/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/input/__tests__/__snapshots__/demo.test.tsx.snap
  components/input/demo/variant.tsx
  components/input/style/index.ts
  components/input/style/variants.ts
  components/layout/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/layout/demo/fixed.tsx
  components/layout/demo/side.tsx
  components/layout/demo/top-side.tsx
  components/layout/demo/top.tsx
  components/modal/interface.ts
  components/statistic/Timer.tsx
  components/statistic/__tests__/__snapshots__/demo.test.ts.snap
  components/statistic/__tests__/image.test.ts
  components/statistic/__tests__/index.test.tsx
  components/table/__tests__/__snapshots__/demo-extend.test.ts.snap
  package.json
  tests/shared/imageTest.tsx
Labels: BranchAutoMerge

#53840 chore: sync feature into next
  .dumi/theme/builtins/Previewer/CodeBlockButton.tsx
  .dumi/theme/builtins/Previewer/RiddleButton.tsx
  .dumi/theme/common/styles/Reset.tsx
  .dumi/theme/utils.ts
  components/auto-complete/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/auto-complete/__tests__/__snapshots__/demo.test.tsx.snap
  components/color-picker/__tests__/components.test.tsx
  components/color-picker/components/ColorHexInput.tsx
  components/config-provider/index.en-US.md
  components/config-provider/index.zh-CN.md
  components/input/Search.tsx
  components/input/__tests__/Search.test.tsx
  components/input/__tests__/__snapshots__/Search.test.tsx.snap
  components/input/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/input/__tests__/__snapshots__/demo.test.tsx.snap
  components/input/demo/variant.tsx
  components/input/style/index.ts
  components/input/style/variants.ts
  components/layout/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/layout/demo/fixed.tsx
  components/layout/demo/side.tsx
  components/layout/demo/top-side.tsx
  components/layout/demo/top.tsx
  components/modal/interface.ts
Labels: BranchAutoMerge

#53836 site: fix deprecation warnings
  .dumi/theme/common/ComponentChangelog/ComponentChangelog.tsx
Labels: lgtm

#53842 fix: Add missing generic parameters to DraggerProps
  components/upload/Dragger.tsx
  components/upload/__tests__/type.test.tsx
Labels: lgtm

#53851 fix: actions semantic dom for InputNumber
  components/input-number/__tests__/semantic.test.tsx
  package.json
Labels: lgtm

#53671 feat(Slider): unify orientation attribute usage
  components/_util/__tests__/hooks.test.tsx
  components/_util/hooks/useOrientation.ts
  components/slider/__tests__/index.test.tsx
  components/slider/index.en-US.md
  components/slider/index.tsx
  components/slider/index.zh-CN.md
Labels: lgtm

#53566 feat: Add popupRender API for custom submenu popup rendering
  components/menu/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/menu/__tests__/__snapshots__/demo.test.tsx.snap
  components/menu/demo/custom-popup-render.md
  components/menu/demo/custom-popup-render.tsx
  components/menu/index.en-US.md
  components/menu/index.zh-CN.md
Labels: lgtm

#53855 feat: cascader support data-* & aria-* in option
  components/cascader/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/cascader/demo/basic.tsx
  package.json
Labels: lgtm

#53670 feat(Splitter): unify orientation attribute usage
  components/splitter/Splitter.tsx
  components/splitter/__tests__/index.test.tsx
  components/splitter/demo/collapsible.tsx
  components/splitter/demo/customize.tsx
  components/splitter/demo/group.tsx
  components/splitter/demo/lazy.tsx
  components/splitter/demo/vertical.tsx
  components/splitter/index.en-US.md
  components/splitter/index.zh-CN.md
  components/splitter/interface.ts
Labels: lgtm

#53664 feat(Segmented): unify orientation attribute usage
  components/segmented/__tests__/index.test.tsx
  components/segmented/demo/vertical.tsx
  components/segmented/index.en-US.md
  components/segmented/index.tsx
  components/segmented/index.zh-CN.md
Labels: lgtm

#53864 refactor(drawer): update destroyOnHidden API
  components/drawer/index.tsx
  package.json
Labels: lgtm

#53866 refactor(toolTip): update destroyOnHidden API
  components/tooltip/index.tsx
  package.json
Labels: lgtm

#53863 refactor(collapse): update destroyOnHidden API
  components/collapse/Collapse.tsx
  package.json
Labels: lgtm

#53648 feat(Flex): unify orientation attribute usage
  components/flex/__tests__/index.test.tsx
  components/flex/index.en-US.md
  components/flex/index.tsx
  components/flex/index.zh-CN.md
  components/flex/interface.ts
Labels: lgtm

#53865 refactor(modal): update destroyOnHidden API
  components/modal/Modal.tsx
  package.json
Labels: lgtm

#53867 docs: changelog for 5.25.2
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: skip-verify-files, lgtm

#53861 fix: Typography.Text delete did not follow state changing
  components/typography/Base/index.tsx
  components/typography/__tests__/index.test.tsx
Labels: lgtm

#53873 refactor: Rename Steps labelPlacement to titlePlacement
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/steps/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/steps/__tests__/__snapshots__/demo.test.ts.snap
  components/steps/__tests__/__snapshots__/index.test.tsx.snap
  components/steps/__tests__/a11y.test.ts
  components/steps/__tests__/index.test.tsx
  components/steps/demo/_semantic.tsx
  components/steps/demo/label-placement.md
  components/steps/demo/title-placement.md
  components/steps/demo/title-placement.tsx
  components/steps/demo/variant-debug.tsx
  components/steps/index.en-US.md
  components/steps/index.tsx
  components/steps/index.zh-CN.md
  components/steps/style/inline.ts
  components/steps/style/label-placement.ts
  components/steps/style/small.ts
  package.json
Labels: lgtm

#53882 chore: sync master into feature
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/typography/Base/index.tsx
  components/typography/__tests__/index.test.tsx
  components/upload/Dragger.tsx
  components/upload/__tests__/type.test.tsx
  package.json
Labels: BranchAutoMerge

#53877 fix(upload): apply merged styles to upload component for picture list types
  components/upload/Upload.tsx
  components/upload/__tests__/upload.test.tsx
Labels: lgtm

#53811 docs: Update log page add break change prompt
  .dumi/rehypeChangelog.ts
  .dumi/theme/builtins/RefinedChangelog/index.tsx
  .dumi/theme/common/ComponentChangelog/ComponentChangelog.tsx
  .dumi/theme/slots/Content/index.tsx
  .dumi/theme/utils.ts
  .dumirc.ts
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: skip-verify-files, lgtm

#53889 docs: improve codeblock button loading state and error handling
  .dumi/theme/builtins/Previewer/CodeBlockButton.tsx
Labels: skip-verify-files, lgtm

#53888 fix: statistic timer cannot display tooltip as a children
  components/statistic/Statistic.tsx
  components/statistic/__tests__/index.test.tsx
Labels: skip-verify-files, lgtm

#53899 docs: Blog about v6 css
  docs/blog/css-tricks.en-US.md
  docs/blog/css-tricks.zh-CN.md
  docs/blog/css-tricks/condition.tsx
  docs/blog/css-tricks/scope.tsx
Labels: skip-verify-files, lgtm

#53901 style: fix Tabs unexpected focus style
  components/tabs/style/index.ts
Labels: skip-verify-files, lgtm

#53908 chore: sync master into feature
  .dumi/rehypeChangelog.ts
  .dumi/theme/builtins/Previewer/CodeBlockButton.tsx
  .dumi/theme/builtins/RefinedChangelog/index.tsx
  .dumi/theme/common/ComponentChangelog/ComponentChangelog.tsx
  .dumi/theme/common/SelectSemanticTemplate.tsx
  .dumi/theme/common/SemanticPreview.tsx
  .dumi/theme/slots/Content/index.tsx
  .dumi/theme/utils/__tests__/runTests.ts
  .dumi/theme/utils/__tests__/tsToJs.test.ts
  .dumi/theme/utils/index.ts
  .dumi/theme/utils/tsToJs.test.ts
  .dumi/theme/utils/tsToJs.ts
  .dumirc.ts
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/auto-complete/demo/_semantic.tsx
  components/badge/demo/_semantic.tsx
  components/button/demo/_semantic.tsx
  components/card/demo/_semantic.tsx
  components/cascader/demo/_semantic.tsx
  components/collapse/demo/_semantic.tsx
  components/date-picker/demo/_semantic.tsx
  components/descriptions/demo/_semantic.tsx
  components/drawer/demo/_semantic.tsx
  components/empty/demo/_semantic.tsx
  components/input/demo/_semantic_input.tsx
  components/input/demo/_semantic_textarea.tsx
  components/list/demo/_semantic.tsx
  components/modal/demo/_semantic.tsx
  components/popconfirm/demo/_semantic.tsx
  components/popover/demo/_semantic.tsx
  components/select/demo/_semantic.tsx
  components/slider/demo/_semantic.tsx
  components/space/demo/_semantic.tsx
  components/statistic/Statistic.tsx
  components/statistic/__tests__/index.test.tsx
  components/tabs/style/index.ts
  components/tooltip/demo/_semantic.tsx
  components/tree-select/demo/_semantic.tsx
  components/upload/Upload.tsx
  components/upload/__tests__/upload.test.tsx
  docs/blog/css-tricks.en-US.md
  docs/blog/css-tricks.zh-CN.md
  docs/blog/css-tricks/condition.tsx
  docs/blog/css-tricks/scope.tsx
  package.json
Labels: BranchAutoMerge

#53910 chore: add test case for cascader
  components/cascader/__tests__/__snapshots__/index.test.tsx.snap
  components/cascader/__tests__/index.test.tsx
Labels: lgtm

#53914 docs: add changelog 5.25.3
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  package.json
Labels: skip-verify-files, lgtm

#53919 docs: fix CHANGELOG
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: skip-verify-files, lgtm

#53898 Codingories/fix 53897 input on press enter
  components/input/Search.tsx
  components/input/__tests__/Search.test.tsx
Labels: lgtm

#53939 docs: Modify dropdownRender to popupRender
  components/dropdown/demo/custom-dropdown.md
Labels: skip-verify-files, lgtm

#53934 docs: enhance theme switching functionality
  .dumi/theme/common/ThemeSwitch/index.tsx
Labels: skip-verify-files, lgtm

#53926 feat: support expandedRowOffset
  components/table/__tests__/__snapshots__/demo.test.ts.snap
  components/table/demo/expand-sticky.md
  components/table/demo/expand-sticky.tsx
  components/table/index.en-US.md
  components/table/index.zh-CN.md
  package.json
Labels: lgtm

#53951 docs: update wording
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
Labels: skip-verify-files, lgtm

#53930 docs(site): Network connection is not smooth notification
  .dumi/scripts/mirror-modal.js
  .dumi/scripts/mirror-notify.js
  .dumi/theme/layouts/GlobalLayout.tsx
  .dumirc.ts
Labels: skip-verify-files, lgtm

#53944 fix: use ol instead of ul in Timeline
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/timeline/TimelineItemList.tsx
  components/timeline/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/timeline/__tests__/__snapshots__/demo.test.ts.snap
  components/timeline/__tests__/__snapshots__/index.test.tsx.snap
Labels: lgtm

#53937 ci: update assignees for dependency upgrade PR
  .github/workflows/upgrade-deps.yml
Labels: lgtm

#53956 style: tweak Select selected item background in dark theme
  components/theme/themes/dark/index.ts
Labels: skip-verify-files, lgtm

#53965 chore(tsconfig): add jest types for improved testing support
  scripts/tsconfig.json
Labels: skip-verify-files, lgtm

#53963 chore: feature merge master
  .dumi/global.css
  .dumi/scripts/mirror-modal.js
  .dumi/scripts/mirror-notify.js
  .dumi/theme/builtins/Container/index.tsx
  .dumi/theme/builtins/Container/style.ts
  .dumi/theme/layouts/DocLayout/index.tsx
  .dumi/theme/layouts/GlobalLayout.tsx
  .dumi/theme/slots/Content/InViewSuspense.tsx
  .dumi/theme/slots/Content/index.tsx
  .dumi/theme/static/style.ts
  .dumirc.ts
  .github/workflows/upgrade-deps.yml
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/checkbox/style/index.ts
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/descriptions/Item.ts
  components/descriptions/__tests__/type.test.tsx
  components/descriptions/index.tsx
  components/theme/themes/dark/index.ts
  components/timeline/TimelineItemList.tsx
  components/timeline/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/timeline/__tests__/__snapshots__/demo.test.ts.snap
  components/timeline/__tests__/__snapshots__/index.test.tsx.snap
  package.json
  scripts/tsconfig.json
Labels: BranchAutoMerge, lgtm

#53966 chore: sync feature into next
  .dumi/global.css
  .dumi/scripts/mirror-modal.js
  .dumi/scripts/mirror-notify.js
  .dumi/theme/builtins/Container/index.tsx
  .dumi/theme/builtins/Container/style.ts
  .dumi/theme/layouts/DocLayout/index.tsx
  .dumi/theme/layouts/GlobalLayout.tsx
  .dumi/theme/slots/Content/InViewSuspense.tsx
  .dumi/theme/slots/Content/index.tsx
  .dumi/theme/static/style.ts
  .dumirc.ts
  .github/workflows/upgrade-deps.yml
  CHANGELOG.en-US.md
  CHANGELOG.zh-CN.md
  components/checkbox/style/index.ts
  components/config-provider/__tests__/__snapshots__/components.test.tsx.snap
  components/descriptions/Item.ts
  components/descriptions/__tests__/type.test.tsx
  components/descriptions/index.tsx
  components/theme/themes/dark/index.ts
  components/timeline/TimelineItemList.tsx
  components/timeline/__tests__/__snapshots__/demo-extend.test.ts.snap
  components/timeline/__tests__/__snapshots__/demo.test.ts.snap
  components/timeline/__tests__/__snapshots__/index.test.tsx.snap
  package.json
  scripts/tsconfig.json
Labels: BranchAutoMerge
